### ISSUE TITLE
Trilinos: how to avoid PR testing on non-code directories/files

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#10386]
## Question
@trilinos/framework @jwillenbring @ZUUL42 @e10harvey 

Changes to certain Trilinos subdirectories don't require extensive PR testing, e.g., `Trilinos/cmake/ctest/drivers`
Is there a mechanism for adding or marking new subdirectories to this "don't test category"?  Is this something that Trilinos developers can do, or must it be done outside of the Trilinos repo?

Specifically, #10378 is adding scripts to a performance subdirectory in Tpetra.  The changes will never affect how Trilinos configures or builds.  It would be nice to avoid wasting compute cycles and blocking other PRs by not doing extensive testing on #10378.

**Comment by jhux2** [comment]
@bartlettroscoe Expanding the category of Trilinos changes that don't need exhaustive configure/code builds would take pressure off of the PR test machines.  See #10775 for an example.

**Comment by bartlettroscoe** [comment]
CC: @ccober6 

@jhux2, this is a TriBITS feature request.  This has been talked about for a long time but it will add size and complexity to TriBITS and opens up more opportunities for mistakes.  For example, frustrated actors could list there entire package as not needing tested when there are changes under their package which would be a disaster.

Before we implement something like this, where are some ideas on how to reduce the overloading of the PR testing process:

* Stop having the autotester rerunning all of the PR builds a second time if the first time fails (even if no one even inspected the results from the first run)
* Don't allow anyone to use a bot that puts `AT: RETEST` on a PR over and over again (like what is happening currently that has lead to #10849).
* Don't push new commits to a PR unless you want the PR builds to run for that push.  (Otherwise, change the autotester to require developers to have to manually set `AT: RETEST` whenever they wanted to builds to PR builds again.)
* Run post merge CI builds for all the Trilinos PR builds and have CDash those send out emails for those failures to everyone so that these failures get seen right away.  (If a post merge CI build has a failure, you can guarantee that PR builds are also showing that error.)

Also, people should only add `AT: RETEST` to a PR after they have carefully inspected the PR results for the last failed iteration and then only add `AT: RETEST` if it seems pretty clear that it is a random failure that their PR branch did not cause (and they need to make sure there is a Trilinos GitHub issue that calls out the random failure like #10847 so that it can be addressed and does not keep taking out other PRs in the future).  And if there is a good chance that it is a random failure their PR branch is causing, then fix the random failure before merging the PR.

Trilinos PR builds are way too expensive to be firing them off so willy nilly.

Also, forced PR merge access should be given to a small number of trusted Trilinos developers to merge PRs when it is determined that the PR failures are not caused by that changes in that PR branch.  (This is exactly what Kitware does for CMake.)

Otherwise, PRs like #10775 are pretty rare so even if we implement finer grained logic, it will have a much smaller impact that making the above changes.

**Comment by bartlettroscoe** [comment]
This and the broader topic of PR testing throughput should be discussed at the next Trilinos developers meeting.

**Comment by jhux2** [comment]
> only add `AT: RETEST` if it seems pretty clear that it is a random failure that their PR branch did not cause

Developers have been resorting to retesting because:

1) There have been a large number of random failures.
2) We don't have any insight into the PR testing process itself.

**Comment by bartlettroscoe** [comment]
> Developers have been resorting to retesting because ...

@jhux2, but that is one cause of the log-jamming.
