### ISSUE TITLE
What do the Belos's timer account for?

### ISSUE THREAD

**Issue by kongm** [trilinos/Trilinos#1044]
Hi,

I'm getting this output from Belos:

Timer Name                                        Global time (num calls)
--------------------------------------------------------------------------------
Belos: Operation Op*x                             0.0009172 (12)
Belos: Operation Prec*x                           0.2256 (8)
Belos: Orthogonalization                          0.001559 (8)
Belos: PseudoBlockGmresSolMgr total solve time    0.2298 (4)

I'm guessing it's only computation time  and not communication time?  
Just in case, I'm using Trilinos 12.2.1

**Comment by aprokop** [comment]
Belos timers include both communication and computation. The operations typically have barriers in them. There is some work planned on asynchronous communication but I believe that has not been implemented yet. I'm not sure how that will affect timings in the future.

The results you present actually correspond to a serial run, it seems. This can be determined by the number of columns in the timer output. For parallel runs, there are going to be three columns: min, max, and average. So, in this case, it seems that you have no communication going on. Just FYI, the number in brackets is the number of calls to a particular operation.

**Comment by jjellio** [comment]
Hi,

Too see that output (1 column instead of 4), you must be running with 1 process?

That time does include communication. The timers are fairly simple. They start at the top of a region of code, and time until the region loses scope.

Opx : is the action of applying the operator (Sparse MatVec if you have a matrix)
Precx : applying the preconditioner.
Orthogonalization is what you think.

All include the total time spent in that region (aggregate). That includes both comm and comp time.


Sometime in the future, we hope to improve some of these labels, so that you know which kernels are used. GMRES defaults to DGKS orthogonalization which is numerically superior to classical gram schmidt. You can change to two-pass iterated classical gram schmidt. By setting "Orthogonalziation" to "ICGS" in your gmres solver parameter list. In the future, we will be exposing a comprehensive configuration process for these solvers. They support many features that are simply not exposed at the Belos::Solver level.


James


________________________________

**Comment by kongm** [comment]
Thanks. BTW, if I invoke the solver many times, creating a fresh new object for each call, do the timers account for the current solver call or do they aggregate somehow?

**Comment by aprokop** [comment]
If you create a timer with the same name, the times would aggregate. You can double check that by looking at the number of calls in parenthesis, which should show the total number for all iterations.

**Comment by jjellio** [comment]
The timer label is configurable through the parameter list you provide to the solver factory (or directory constructor)


RCP<ParameterList> belosParams ...


belosParams->set ("Timer Label", "something different")


The default is "Belos"



________________________________
