### ISSUE TITLE
Tpetra inout/CooMatrix test failure

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#1056]
## Summary

The test `TpetraCore_CooMatrix_MPI_2` fails.  

## Details

`TpetraCore_CooMatrix_MPI_2` fails when the Trilinos test suite is run with `ctest`.  When the `packages/tpetra/core/test/inout/TpetraCore_CooMatrix.exe` executable is run standalone, the following error is thrown:

```
inout$ mpiexec -np 2 ./TpetraCare_CooMatrix.exe
...
0. CooMatrix_doubleIntLongLong_UnitTest ...
 ! comm.is_null () = 1 == true : passed
 Test CooMatrix
  comm->getSize () >= 2 = 1 == true : passed
  CooMatrix default constructor...
 p=0: *** Caught standard std::exception of type 'std::runtime_error' :

  Constructing View and initializing data with uninitialized execution space
  Traceback functionality not available
...
```

[The failing line]( https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/test/inout/CooMatrix.cpp#L84) is:

```c++
  out << "CooMatrix default constructor... ";
  CooMatrix<SC, LO, GO> A_in;
  out << "done" << endl;
```

## System and Build information

- Platform: darwin, OS X 10.11
- Build branch: develop (with recent pull)
- Compiler vendor/version: gcc 6.3
- MPI vendor/version: openmpi 1.10.3
- Explicitly enabled packages: Tpetra, TpetraCore, Kokkos
- Explicitly disabled packages: FEI,Fortran,Pike,Piro,PyTrilinos,SEACAS,STK,ShyLU,Teko

@mhoemmen, I am glad to look for/provide a resolution.  Do you have an suggestions of where to start?

@trilinos/tpetra

**Comment by mhoemmen** [comment]
@tjfulle Thanks for offering!  The issue is that CooMatrix inherits from Tpetra::DistObject, and DistObject has some Kokkos::DualView buffers in it.  The default constructor should just initialize those to have length zero.  That _should_ be harmless.  However, Kokkos insists that the execution (and likely also memory) space be initialized in order to create Views with that space, even if the Views are empty (and therefore nothing needs to execute).  That's not horribly unreasonable; Tpetra has started using Kokkos, so Kokkos needs to be initialized.

Here are two possible fixes:

1. Make sure that the test initializes Kokkos at the beginning, and finalizes Kokkos at the end.  

Easiest way to do that is just to create an empty Tpetra::Map instance.  Map's default constructor creates a Node instance, which initializes Kokkos if it has not yet been initialized.

2. Have CooMatrix's default constructor first create a default-constructed Map, then get rid of that Map.  This will have the same effect as the proposed solution in the previous paragraph.

**Comment by tjfulle** [comment]
@mhoemmen it seems option 2 is a more general solution?  I'll look at pushing a fix tomorrow.

Can the test be made to fail on Linux too? (to get confidence in the fix, assuming it resolves the Darwin and Linux failures)

**Comment by mhoemmen** [comment]
Thanks for taking this! :-D

@tjfulle wrote:
> Can the test be made to fail on Linux too? (to get confidence in the fix, assuming it resolves the Darwin and Linux failures)

We could have the test check Kokkos::is_initialized (or the specific execution space) at the appropriate place.  That should manifest the issue that is likely causing the test failure.

**Comment by tjfulle** [comment]
@mhoemmen adding

```c++
  // Throw away map, just to make sure that Kokkos is initialized
  RCP<const map_type> throwaway_map;
  throwaway_map = rcp(new map_type(static_cast<GST>(0),
                                   static_cast<GO>(0),
                                   comm));
```

to the test resolves the test failure on Darwin.  The resolution is in [194efd39](https://github.com/tjfulle/Trilinos/commit/194efd39d47379309ba31dd03d9c9cf777754481), I could open up a pull request.  But, it seems like a better solution would be to modify the `CooMatrix` constructor so that users don't have to do this kind of thing.  Though, I believe the `CooMatrix` is only used for reading matrix files, so it may not be an issue?

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> But, it seems like a better solution would be to modify the CooMatrix constructor so that users don't have to do this kind of thing. Though, I believe the CooMatrix is only used for reading matrix files, so it may not be an issue?

It's not _currently_ an issue, because CooMatrix isn't used for anything yet.  However, the following use case would trigger this error, once CooMatrix is plugged into the Matrix Market reader:

  1. Create a communicator
  2. Give communicator to Matrix Market reader, and ask it to create the matrix's row Map

At (2), the user has not yet created a Map.  The interface can't create a row Map without reading in all the row indices from the file.  Thus, the CooMatrix needs to be created before any Maps get created.

**Comment by tjfulle** [comment]
@mhoemmen, shall I open a PR to fix this test, or hold off for a more comprehensive solution?

**Comment by mhoemmen** [comment]
@tjfulle The former for now.  I can work on a more comprehensive solution later.  Thanks!

**Comment by mhoemmen** [comment]
@tjfulle fixed it with the above pull request -- thanks!
