### ISSUE TITLE
Teuchos::ParameterList: Possible bug in one-argument get?

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1066]
@trilinos/teuchos 

@DrBooom reports the following: It looks like getEntryPtr returns NULL if the given parameter name does not exist in the parameter list.  The implementation of the following method:
```
template<typename T>
const T& ParameterList::get(const std::string& name_in) const 
```
uses the result of getEntryPtr directly.  @DrBooom proposes that the implementation of `get` "be modified to test the `foundEntry` for null, and/or change `validateEntryExists` to accept a null foundEntry.  Maybe just throw."

**Comment by bartlettroscoe** [comment]
Can someone contribute a unit test to demonstrate expected behavior?

**Comment by mhoemmen** [comment]
@bartlettroscoe I think this question can be answered by inspection.  Here is the current implementation of one-argument `get`:
```
template<typename T>
const T& ParameterList::get(const std::string& name_in) const
{
  const ParameterEntry *foundEntry = this->getEntryPtr(name_in);
  validateEntryExists("get",name_in,foundEntry);
  this->template validateEntryType<T>("get",name_in,*foundEntry);
  return getValue<T>(*foundEntry);
}
```
Here is the current implementation of `validateEntryExists`:
```
void ParameterList::validateEntryExists(
  const std::string & /*funcName*/, const std::string &name_in,
  const ParameterEntry *entry_in
  ) const
{
  TEUCHOS_TEST_FOR_EXCEPTION_PURE_MSG(
    entry_in==NULL, Exceptions::InvalidParameterName
    ,"Error!  The parameter \""<<name_in<<"\" does not exist"\
    "\nin the parameter (sub)list \""<<this->name()<<"\"."
    "\n\nThe current parameters set in (sub)list \""<<this->name()<<"\" are:\n\n"
    << this->currentParametersString()
    );
}
```
If the exception test macro does what it appears to do by name, then it looks like this addresses @DrBooom 's concern.

**Comment by bartlettroscoe** [comment]
So why did @DrBooom think there was a a problem?

**Comment by DrBooom** [comment]
If get is called with an invalid parameter name, it should likely throw, rather than segfaulting on a null pointer.


Chris Luchini
ORG 1443
Sandia National Laboratory
(505) 284 3484
(505) 690 5008 Cell (505) is required.
________________________________

**Comment by hkthorn** [comment]
@DrBooom @mhoemmen @bartlettroscoe   The code as Mark has pasted it does throw an exception if there is an invalid parameter name or type because the foundEntry will be NULL.  This is documented in the Teuchos::ParameterList class:

  /// If the given parameter is not in the list at all, this method
  /// throws Exceptions::InvalidParameter.  If the parameter is in the
  /// list but does not have type T, this method throws
  /// Exceptions::InvalidParameterType.  Both exceptions are
  /// subclasses of Exceptions::InvalidParameter.

The Teuchos::ParameterList unit tests check that this is the case.
So, what are you seeing, do you have an example where you can't catch the Exceptions::InvalidParameter and are, instead, seeing a seg fault?  If so, please reopen this bug and include the code snippet that is causing you problems.  Thanks!
