### ISSUE TITLE
All Packages:  HPC Install

### ISSUE THREAD

**Issue by danipoak** [trilinos/Trilinos#10936]
## Question
@trilinos/\<all packages\>

I'm trying to get Trilinos installed in an Cray HPC environment with openMPI support. I believe it is MPI that is causing issues. Using CMake I can configure Trilinos just fine but when I run the install it fails at about 32% at `Linking CXX executable cth_pressure_map`. The error output is:

```[ 32%] Linking CXX executable cth_pressure_map
/opt/cray/pe/cce/10.0.0/binutils/x86_64/x86_64-pc-linux-gnu/bin/ld: ../pamgen/libIopg.a(Iopg_DatabaseIO.C.o): undefined reference to symbol 'MPI_Rsend'
/opt/cray/pe/cce/10.0.0/binutils/x86_64/x86_64-pc-linux-gnu/bin/ld: /app/CSE/CSE.20210613/Release/openmpi-3.1.6/lib/libmpi.so.40: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [packages/seacas/libraries/ioss/src/main/cth_pressure_map] Error 1
make[1]: *** [packages/seacas/libraries/ioss/src/main/CMakeFiles/cth_pressure_map.dir/all] Error 2
make: *** [all] Error 2
```

My build script is below and I am able install when I don't have `-D TPL_ENABLE_MPI=ON`. I have tried adding `-D CMAKE_SYSTEM_NAME=CrayLinuxEnvironment` since it is a Cray system but that causes the configure stage to fail. 

```module load compiler/gcc/9.3.0
module load cseinit
module load cse/cmake/latest
module load cse/boost/latest
module load cse/netcdf/latest
module load cse/openmpi/latest

openmpi_path=/app/CSE/CSE.20210613/Release/openmpi-3.1.6/

mkdir build
cd build
cmake ..\
  -D CMAKE_C_COMPILER=/usr/cta/unsupported/cs/gcc/9.3.0/bin/gcc \
  -D CMAKE_CXX_COMPILER=/usr/cta/unsupported/cs/gcc/9.3.0/bin/g++ \
  -D CMAKE_Fortran_COMPILER=/usr/cta/unsupported/cs/gcc/9.3.0/bin/gfortran \
  -D MPI_BIN_DIR=""${openmpi_path}/bin";"${openmpi_path}/lib";"${openmpi_path}/etc";"${openmpi_path}/include";"${openmpi_path}/share""\
  -D CMAKE_FIND_PACKAGE_RESOLVE_SYMLINKS:BOOL=ON \
  -D TPL_ENABLE_MPI=ON \
  -D Trilinos_ENABLE_ALL_PACKAGES=ON \
  -D TPL_BLAS_LIBRARIES=/p/home/user/.local/lapack/libblas.a \
  -D TPL_LAPACK_LIBRARIES=/p/home/user/.local/lapack/liblapack.a \
  -D TPL_ENABLE_Matio=OFF \
  -D CMAKE_INSTALL_PREFIX:PATH=/p/home/user/trilinos/ \
  /p/home/user/Alpha/trilinos-12-12-1

make install
```

**Comment by jjellio** [comment]
I don't think Trilinos' Cmake for MPI will append the libraries needed.  Your options are probably: use mpicc/mpicxx/mpif90 from openmpi (set them as your C/CXX/Fortran compilers)  - or you'll need to add the MPI library information into the CMake stuff.

Adding it to the CMake stuff isn't always straightforward, CMAKE_EXE_LINKER_FLAGS will add things to the link line for executables. CMAKE_SHARED_LINKER_FLAGS will add them to shared library creation.  Another way, is to "hide mpi libs" inside a TPL that always gets linked - which is DLlib.
```
-DTPL_ENABLE_DLlib=ON
"-DDLlib_INCLUDE_DIRS=/your/mpi/include/paths;/maybe/more"
"-DDLlib_LIBRARAY_DIRS=/your/mpi/lib/;/maybe/more/lib"
"-DDLlib_LIBRARY_NAMES=dl;mpi;mpicxx;ofi;whatever;your;mpi;libs;require;names;only"
```

I'd need to verify some of the CMake variables - I prefer "hiding things" in DLlib, as that allows CMake to use Include/library DIRS variables to "find" the library names - which ensures they are actually where you think they are ... it's a bit advanced - you need to know the library names - and you need to know where they are. E.g., if your MPI depends on Cuda or HIP, you can add the needed MPI-Device libs there too ... making sure it all gets hooked up correctly - CMake will then automatically set RPATH - that way at runtime the libs will be found as well.

If you want the quick and easy - just use the MPI wrappers and see if that does it. If that doesn't then set the CMAKE_ variables to add the libs "CMAKE_...=-lmpi -L/path/to/it/lib -Wl,-rpath,/path/to/it/lib"  You'll need to spell out the -L and -Wl,rpath business  since you are specifying the raw lib.

That all assumes shared linkage...

If it's static, you can skip the RPATH stuff

FYI - unless cse/netcdf/latest  was built with your openmpi, you probably can't mix Cray's MPI-built libraries with openmpi ones, you very likely get missing symbols from Cray (usually allocators)
