### ISSUE TITLE
Framework: Mass gnu and clang PR test failures on new 'ascic0xyz' machines

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#10999]
Link:
https://trilinos-cdash.sandia.gov/test/11636999

Sample error:
```
/scratch/trilinos/workspace/Trilinos_PR_gcc-7.2.0-debug@2/pull_request_test/packages/amesos/example/Amesos_a_trivial_mpi_test.exe: symbol lookup error: /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/openmpi/1.10.1/lib/libmca_common_verbs.so.7: undefined symbol: ompi_common_verbs_usnic_register_fake_driver
```

Reported in [TRILINOSHD-203](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-203).

**Comment by csiefer2** [comment]
Nothing like watching over 2,000 tests fail...

**Comment by bartlettroscoe** [comment]
Hum, I saw the same error when trying to use one of the GenConfig builds on an 'hpws' machine showing runtime errors like:

```
1: /fgs/rabartl/Trilinos.base/BUILDS/ATDM/CHECKIN/sems-rhel7-intel-18.0.5-openmp-shared-release-debug/packages/teuchos/core/test/Allocator/TeuchosCore_Allocator_UnitTest.exe: symbol lookup error: /projects/sems/install/rhel7-x86_64/sems/compiler/intel/18.0.5/openmpi/1.10.1/lib/libmca_common_verbs.so.7: undefined symbol: ompi_common_verbs_usnic_register_fake_drivers
```

See [TRILINOSHD-59](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-59) and:

* https://github.com/trilinos/Trilinos/issues/10022#issuecomment-1239438691
* https://github.com/trilinos/Trilinos/issues/10836#issuecomment-1216017031

**Comment by bartlettroscoe** [comment]
NOTE: This PR build is running on the machine [ascic0193](https://trilinos-cdash.sandia.gov/viewSite.php?siteid=96&project=1&currenttime=1662609600) which is one of the 'ascic0xy' machines that was supposed to have been taken out of the pool of PR testing machines (see #10893).  How did it get back on?

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&date=2022-09-08&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=site&compare2=65&value2=ascic0&field3=testsfailed&compare3=43&value3=100) showing:

![image](https://user-images.githubusercontent.com/1959736/189216552-17799a56-f4c7-4795-97b1-dd31b5947e30.png)

this is taking out gnu-7.2.0, gnu-8.3.0, and clang-10.0.0 builds and impacting PRs #10962 and #109743 so far.

**Comment by ndellingwood** [comment]
How do we view progress on [TRILINOSHD-203](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-203) ? I have access to Jira but don't have permissions to view this specific issue

**Comment by bartlettroscoe** [comment]
@trilinos/framework, it is happening again (running on broken 'ascicj0XZ' nodes) as of 2022-10-21 as shown in [this query](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&begin=2022-10-01&end=2022-10-23&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=site&compare2=65&value2=ascic0).  As shown in [this query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2022-10-20&end=2022-10-23&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=site&compare2=65&value2=ascic0&field3=status&compare3=61&value3=failed&field4=testoutput&compare4=95&value4=ompi_common_verbs_usnic_register_fake_drivers), since 2022-10-21, we have seen 30708 failed tests so far in these PR builds with mpiexec init errors like:

```
/scratch/trilinos/workspace/Trilinos_PR_clang-10.0.0/pull_request_test/packages/stratimikos/adapters/amesos2/test/Stratimikos_test_single_amesos2_tpetra_solver_driver.exe: symbol lookup error: /projects/sems/install/rhel7-x86_64/sems/compiler/clang/10.0.0/openmpi/1.10.1/lib/libmca_common_verbs.so.7: undefined symbol: ompi_common_verbs_usnic_register_fake_drivers
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[18596,1],0]
  Exit code:    127
--------------------------------------------------------------------------
```

As shown by running:

```

$ ../TrilinosATDMStatus/create_trilinos_github_test_failure_issue_driver.sh -u "https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2022-10-20&end=2022-10-23&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=site&compare2=65&value2=ascic0&field3=status&compare3=61&value3=failed&field4=testoutput&compare4=95&value4=ompi_common_verbs_usnic_register_fake_drivers"

***
*** Getting data to create a new issue tracker
***

Downloading full list of nonpassing tests from CDash URL:

   https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2022-10-20&end=2022-10-23&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=site&compare2=65&value2=ascic0&field3=status&compare3=61&value3=failed&field4=testoutput&compare4=95&value4=ompi_common_verbs_usnic_register_fake_drivers

  Downloading CDash data from:
    https://trilinos-cdash.sandia.gov/api/v1/queryTests.php?project=Trilinos&begin=2022-10-20&end=2022-10-23&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=site&compare2=65&value2=ascic0&field3=status&compare3=61&value3=failed&field4=testoutput&compare4=95&value4=ompi_common_verbs_usnic_register_fake_drivers

Total number of nonpassing tests over all days = 30708

Total number of unique nonpassing test/build pairs over all days = 30657

Number of test names = 2828

Number of build names = 28

Writing out new issue tracker text to 'newGithubMarkdownIssueBody.md'

Writing out list of test/biuld pairs for CSV file 'newTestsWithIssueTrackers.csv'

real    0m7.274s
user    0m1.500s
sys     0m0.686s
```

This is taking out 28 different individual PR builds in that time impacting the PR builds:

* `PR-10926-test-rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1308`
* `PR-10926-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1292`
* `PR-10926-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1300`
* `PR-11053-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1283`
* `PR-11136-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1293`
* `PR-11136-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1301`
* `PR-11162-test-rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1298`
* `PR-11162-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1282`
* `PR-11162-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1290`
* `PR-11165-test-rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1302`
* `PR-11165-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1286`
* `PR-11165-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1294`
* `PR-11170-test-rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1301`
* `PR-11170-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1285`
* `PR-11170-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1293`
* `PR-11172-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1287`
* `PR-11172-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1295`
* `PR-11174-test-rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1306`
* `PR-11174-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1290`
* `PR-11174-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1298`
* `PR-11180-test-rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1307`
* `PR-11180-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1291`
* `PR-11180-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1299`
* `PR-11182-test-rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1310`
* `PR-11182-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1294`
* `PR-11182-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1302`
* `PR-11183-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1289`
* `PR-11183-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1297`

How do these broken 'ascic0XYZ' nodes keep getting put back in the node pool for PR build?

**Comment by e10harvey** [comment]
This should be resolved now.

**Comment by bartlettroscoe** [comment]
Unpinning because this should be resolved.
