### ISSUE TITLE
Framework:  #10648 deletes necessary files

### ISSUE THREAD

**Issue by dridzal** [trilinos/Trilinos#11101]
## Bug Report
@trilinos/framework 

### Description
The checkin test script, `cmake/std/sems/checkin-test-sems.sh`, used, for instance, by @trilinos/rol for the two-way repo merge, no longer works due to #10648 and related commits.  It appears that the cmake files required for configure/test have been removed without consideration of consequences. 

### Steps to Reproduce
Run the checkin test script.  It will fail with

```
-- Reading in configuration options from cmake/std/GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP.cmake ...
CMake Error at cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:180 (include):
  include could not find load file:

    cmake/std/GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP.cmake
```

**Comment by bartlettroscoe** [comment]
@dridzal, the solution is to upgrade the checkin-tests-sems.sh script to use the GenConfig system.  That is a much more complex system (e.g. having to run a separate script to get needed files, symlinks getting created, etc.) but it works and it is supported by the Trilinos framework team. 

Let's schedule a time later this week to go over what needs to be done.  It should not take long to get your sync process updated to use a GenConfig configuration.

**Comment by dridzal** [comment]
@bartlettroscoe:  Can we do anything right away?  We are looking at some time-sensitive deliveries.  Can we just back out the changes that remove the necessary files?

**Comment by bartlettroscoe** [comment]
> Can we do anything right away?

@dridzal, you could, just this one time, cross your fingers and manually do the sync each way, perhaps with just a local build of ROL using any approach that your team is already using to sync from the main repo to your ROL repo and rely on the PR builds for syncing from your ROL repo back to the main Trilinos repo.

Otherwise, updating `checkin-test-sems.sh` to use a GenConfig PR build should not be very hard.
