### ISSUE TITLE
Zoltan:  can't disable two failing tests

### ISSUE THREAD

**Issue by jmlapre** [trilinos/Trilinos#11212]
## Bug Report
@trilinos/zoltan @bartlettroscoe 

### Description
I'm trying to bring up the Intel 2021.3 compiler for nightly builds (test results):

https://trilinos-cdash.sandia.gov/viewTest.php?onlyfailed&buildid=555380

I was able to disable the `Zoltan_ch_simple_scotch_parallel` but I am unable to disable `Zoltan_ch_7944_parmetis_parallel` or `Zoltan_ch_simple_parmetis_parallel` by adding `TestName_DISABLE=ON` to `config-specs.ini`.  In fact, it seems to error out and not generate a valid configuration when adding `opt-set-cmake-var Zoltan_ch_simple_parmetis_parallel_DISABLE BOOL FORCE : ON`:

[CMakeError.log](https://github.com/trilinos/Trilinos/files/9904567/CMakeError.log)

All of this behavior is quite confusing.  Can anyone suggest a solution?

**Comment by bartlettroscoe** [comment]
@jmlapre, where is the branch with the changes that is used in this build?

**Comment by jmlapre** [comment]
Sorry, here is the code: https://github.com/e10harvey/Trilinos/pull/19

Here is the CMakeCache.txt as well.

[CMakeCache.txt](https://github.com/trilinos/Trilinos/files/9905159/CMakeCache.txt)

**Comment by bartlettroscoe** [comment]
@jmlapre, are we 100% sure that the branch represented in https://github.com/e10harvey/Trilinos/pull/19 is what is being tested in:

* https://trilinos-cdash.sandia.gov/build/555380/configure

?

Looking at that configure output, it shows:

```
--------------------------------------------------------------------------------
*** Base Git Repo: Trilinos
e2c88b5 [Wed Oct 26 11:42:28 2022 -0600] <trilinos@sandia.gov>
Merge remote-tracking branch 'source_remote/sprint17_cpp17' into develop
 --------------------------------------------------------------------------------
```

That suggests that this Trilinos build is merging the branch:

* https://github.com/e10harvey/Trilinos/tree/sprint17_cpp17

into 'develop' and **not** the branch:

* https://github.com/jmlapre/Trilinos/tree/TRILFRAME-387

Can you please just do a local build of this and run:

```
make dashboard
```

?

That will clean up what branch is actually being tested.  I would not suggest running these builds through Jenkins because there are just too many layers to obscure what is happening.  In fact, I might recommend that you run locally using the tool:

* https://gitlab-ex.sandia.gov/rabartl/run_trilinos_pr_builds

That way, you can locally run configure, add internal CMake print statements, and determine exactly what is happening.

**Comment by jmlapre** [comment]
@bartlettroscoe here is the output of `make dashboard`:

https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascicgpu050&field2=buildname&compare2=61&value2=Linux-build-387-clean&field3=buildstamp&compare3=61&value3=20221102-1336-Experimental

But again, `make dashboard` could not complete without the following change:
```
(rhel7_sems-intel-2021.3-sems-openmpi-4.0.5) $ git diff
diff --git a/packages/framework/ini-files/config-specs.ini b/packages/framework/ini-files/config-specs.ini
index 9f74aa5..a4237c2 100644
--- a/packages/framework/ini-files/config-specs.ini
+++ b/packages/framework/ini-files/config-specs.ini
@@ -1898,7 +1898,7 @@ use rhel7_sems-intel-2021.3-sems-openmpi-4.0.5_release-debug_shared_no-kokkos-ar
 use PACKAGE-ENABLES|ALL

 opt-set-cmake-var Zoltan_ENABLE_Scotch BOOL FORCE                       : OFF
-opt-set-cmake-var Zoltan_ch_simple_parmetis_parallel_DISABLE BOOL FORCE : ON
+# opt-set-cmake-var Zoltan_ch_simple_parmetis_parallel_DISABLE BOOL FORCE : ON

 [rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables]
 use RHEL7_SEMS_COMPILER|CUDA
```


Attempting to configure the unchanged source resulted in this (broken) [CMakeCache.txt](https://github.com/trilinos/Trilinos/files/9929935/CMakeCache.txt) and [CMakeError.log](https://github.com/trilinos/Trilinos/files/9929939/CMakeError.log).

I will look into your `run_trilinos_pr_builds` tool.

Thanks.

**Comment by bartlettroscoe** [comment]
@jmlapre and now we see the features of `tribits_ctest_driver()` coming to bear that we don't see in the ctest -S driver that is being used by the PR tester.  From looking at the [build on CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascicgpu050&field2=buildname&compare2=61&value2=Linux-build-387-clean&field3=buildstamp&compare3=61&value3=20221102-1336-Experimental), we see:

1. From the "update" link [5fdd37](https://testing.sandia.gov/cdash/viewUpdate.php?buildid=11325963) (which the PR CTest -S driver does not provide), you see that the file `config-specs.ini` is locally modified which means that no one can reproduce exactly what is being shown (because we have no idea what is modified in that file).  Please commit **everything** to the local branch and push so there are no local modifications so that other people can reproduce this.  (When there are locally modified files, all bets are off.)

2. From the uploaded [CMakeCache.clean.txt](https://testing.sandia.gov/cdash/build/11325963/notes#note2) file (which does not get uploaded from the PR CTest -S driver) you see there is no mention of `Zoltan_ch_simple_parmetis_parallel`, meaning that `Zoltan_ch_simple_parmetis_parallel_DISABLE` is **not** being set in the cache. 

When you see:

```
Zoltan_ch_simple_parmetis_parallel_DISABLE:BOOL=ON
```

set in that cache file, please contact me again about some possible problem.

> Attempting to configure the unchanged source resulted in this (broken) [CMakeCache.txt](https://github.com/trilinos/Trilinos/files/9929935/CMakeCache.txt) and [CMakeError.log](https://github.com/trilinos/Trilinos/files/9929939/CMakeError.log).

What do you mean by "broken"?  What is "broken"?

**Comment by jmlapre** [comment]
By "broken" I simply meant that CMake finished with the message:
```
-- Configuring incomplete, errors occurred!
See also "/scratch/jmlapre/Trilinos/build-387-clean/CMakeFiles/CMakeOutput.log".
See also "/scratch/jmlapre/Trilinos/build-387-clean/CMakeFiles/CMakeError.log".
```

But note that in the linked CMakeCache.txt file the line we're looking for is there:
```
//No help, variable specified on the command line.
Zoltan_ch_simple_parmetis_parallel_DISABLE:BOOL=ON
```

So what I am saying is that by adding that one variable causes CMake to fail and generate the linked CMakeError.log above.

**Comment by bartlettroscoe** [comment]
> By "broken" I simply meant that CMake finished with the message:

@jmlapre, please provide the full STDOUT+STDERR so I can see the actual error.

**Comment by jmlapre** [comment]
[typescript.txt](https://github.com/trilinos/Trilinos/files/9931609/typescript.txt)

**Comment by bartlettroscoe** [comment]
If you look at [typescript.txt](https://github.com/trilinos/Trilinos/files/9931609/typescript.txt) you can clearly see the problem:

```
CMake Error at packages/zoltan/test/ch_simple/CMakeLists.txt:65 (SET_PROPERTY):
  SET_PROPERTY given TEST names that do not exist:

    Zoltan_ch_simple_parmetis_parallel
```

This code shows:

https://github.com/trilinos/Trilinos/blob/194a3c36461d119fc48b7a3f5b57a1414ea62e31/packages/zoltan/test/ch_simple/CMakeLists.txt#L55-L66

The problem is that this Zoltan file did not follow:

* https://tribitspub.github.io/TriBITS/users_guide/index.html#setting-additional-test-properties-tribits-add-advanced-test

In other words, this is a bug in the Zoltan package, not in TriBITS.

That can be fixed by using the `RUN_SERIAL` option directly passed to [tribits_add_advanced_test()](https://tribitspub.github.io/TriBITS/users_guide/index.html#overall-arguments-tribits-add-advanced-test) and then just removing the if statement that directly calls `set_property()`.  So the above code block would just be:

```
  TRIBITS_ADD_ADVANCED_TEST(
    ${ZZTESTNAME}
    RUN_SERIAL
    # Test ParMETIS algorithms in parallel
    TEST_0 ${ZOLTAN_TEST_DRIVER} ${ZOLTAN_TEST_ARGS} ParMETIS
    CATEGORIES BASIC NIGHTLY PERFORMANCE
    COMM mpi
    OVERALL_NUM_MPI_PROCS ${ZOLTANNUMPROCS}
    FINAL_FAIL_REGULAR_EXPRESSION "FAILED"
    )
```

@jmlapre, would you be willing to put in a PR to fix this?  If so, I can review it.

**Comment by jmlapre** [comment]
Yes, I'll get it out ASAP.

**Comment by jmlapre** [comment]
https://github.com/trilinos/Trilinos/pull/11226

**Comment by sebrowne** [comment]
@jmlapre this is complete now, correct?

**Comment by jmlapre** [comment]
Yes, closing.
