### ISSUE TITLE
AztecOO:  Misleading Indentation in az_precond.c

### ISSUE THREAD

**Issue by Thinkpiet** [trilinos/Trilinos#11237]
Hi Trilinos team,

I just compiled Trilinos for the very first time. I noticed a compiler warning and had a quick look at it. 
In packages/aztecoo/src/az_precond.c line 314, there is no { after the for, but lines 317-354 are misleadingly indented.

I have absolutely no idea what this code is doing and if this is a bug or possibly intended like this. But on the first glance, it seems it will not be doing whatever it is supposed to do (for example in line 349, since we know that i == m, why would we write it like this?) - so I am opening this issue as a notification. 

Best, Piet

**Comment by cgcgcg** [comment]
@trilinos/aztecoo

**Comment by jhux2** [comment]
@Thinkpiet Thank you for the report.  @rstumin This looks like a bug to me, as well.  What do you think?
https://github.com/trilinos/Trilinos/blob/bbdb16bf6d880dc58a8171a7cfc3834ac9ff7bd8/packages/aztecoo/src/az_precond.c#L309-L355

**Comment by rstumin** [comment]
@jhux2   I actually think that the only issue is the indentation .... and that the code is correct. At this point in the code, I believe we just want to allocate some big arrays, which is what the various AZ_manage_memory() commands do. However, for one of the arrays we need to compute the amount of space needed for a whole bunch of block diagonal matrices. That is what the little loop that computes tsize does. The last argument to AZ_manage_memory is actually a returned status flag. It was probably a bad idea to reuse the variable 'i' for this, but that is what is done. We also don't actually check on what this status is ... except the "else if (i == AZ_NEW_ADDRESS)" statement. This statement checks to see that AZ_manage_memory() found the old previously stored data for Dmat because the user has requested to reuse the previous data. So the bottom line is I believe the indentation should change and the code should remain the same.

**Comment by jhux2** [comment]
Closing as fixed.
