### ISSUE TITLE
Framework: random failures blocking merge of PR

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#11361]
## Bug Report
@trilinos/framework 

### Description
There are a variety of random failures that are blocking the merge of PR #11341.  No of these are due to the PR itself, since it touches a Python utility that doesn't get exercised by the AT.

Reported in https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-235.

**Comment by GrahamBenHarper** [comment]
I believe other PRs have recently run into the problem of running out of memory, but I didn't mark which ones since they were fixed with a retest. If I find more instances, I'll make sure to link them here as related.

**Comment by GrahamBenHarper** [comment]
https://github.com/trilinos/Trilinos/pull/11330#issuecomment-1338009742 is another example of a job killed by (presumably) running out of memory. I found it by skimming a handful of PR builds which have exactly two errors as shown in [this cdash query](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-&field2=buildstarttime&compare2=84&value2=NOW&field3=buildstarttime&compare3=83&value3=Nov%2001%2C%202022).

**Comment by sebrowne** [comment]
The Intel build running out of memory is fixed (not really, but we turned the Intel build back off so a re-run will bypass the failure until we get the correct level of build parallelism figured out such that it won't overload the machine).

The MiniTensor test from earlier in that PR's testing history is fixed now.

The Domi test timed out and was on a CUDA build.  That is another thing we have immediate work planned for (hopefully by the end of the week) to avoid due to GPU oversubscription.

Framework empathizes with the difficulty that these nondeterministic results is causing, and we're working towards resolution on each of the issues as fast as we can.  I will update this once we get the CUDA changes in and the Intel build turned back on, if that's satisfactory.

**Comment by jhux2** [comment]
no longer an issue
