### ISSUE TITLE
Moving boost to a system include 

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1137]
I've been trying to move boost to a system include, however, when I run cmake and build it doesn't look right.

I applied these changes I think everywhere

```
./packages/stk/stk_classic/stk_usecases/io/CMakeLists.txt:INCLUDE_DIRECTORIES(SYSTEM ${Boost_INCLUDE_DIRS})
```

I make sure I didn't miss any, here is my silly script

```
dir-Trilinos (gcc) 31 $ grep INCLUDE_DIR `find . -name C\*txt -exec grep -l Boost {} \;`|grep Boost|grep -v SYSTEM
```

and it's clean.  but I see

```
-I/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/5.3.0/base/include
```
and not the `-Isystem`

where's my mistake?

```
cd /home/mbetten/builds/panzer/cuda/debug/packages/stk/stk_topology/stk_topology && /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/openmpi/1.10.1/bin/mpicxx -I/home/mbetten/builds/panzer/cuda/debug -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_topology -I/home/mbetten/builds/panzer/cuda/debug/packages/stk/stk_util/stk_util/use_cases -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_util/stk_util/use_cases -I/home/mbetten/builds/panzer/cuda/debug/packages/stk/stk_util/stk_util/registry -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_util/stk_util/registry -I/home/mbetten/builds/panzer/cuda/debug/packages/stk/stk_util/stk_util/parallel -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_util/stk_util/parallel -I/home/mbetten/builds/panzer/cuda/debug/packages/stk/stk_util/stk_util/diag -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_util/stk_util/diag -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_util/stk_util/environment -I/home/mbetten/builds/panzer/cuda/debug/packages/stk/stk_util/stk_util/util -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_util -I/home/mbetten/builds/panzer/cuda/debug/packages/stk/stk_util -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_util/stk_util/util -I/home/mbetten/Trilinos/Trilinos/packages/seacas/libraries/aprepro_lib -I/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/5.3.0/base/include -std=c++11 -g -O0   -o CMakeFiles/stk_topology.dir/topology.cpp.o -c /home/mbetten/Trilinos/Trilinos/packages/stk/stk_topology/stk_topology/topology.cpp
```

**Comment by bathmatt** [comment]
boost_as_system_lib has been added @bartlettroscoe can you look at this one?
Thanks

**Comment by bartlettroscoe** [comment]
@bathmatt, there should not be any statements like `INCLUDE_DIRECTORIES(SYSTEM ${Boost_INCLUDE_DIRS})` in STK CMakeLists.txt files.  That is not how you pull in a TPL.  See:

* https://tribits.org/doc/TribitsDevelopersGuide.html#how-to-add-a-new-tribits-tpl-dependency

I will rip all of these out and put in optional dependencies on the `Boost` and `BoostTpl` TPLs in the STK cmake/Dependencies.cmake files that will result in `-isystem` being added to all Boost includes by STK. 

I should be able to verify this on my local machine by just doing a `make VERBOSE=1` with STK and then grepping the output to make sure that Boost is always included with `-isystem` instead of `-I`.  I will then push this to a branch for you to try.

**Comment by bartlettroscoe** [comment]
@bathmatt, you don't build STKClassic anymore right?  So I don't need to worry about fixing up files under that subpakage?

**Comment by bartlettroscoe** [comment]
I made some progress on this and pushed a trial commit to the branch:

* https://github.com/trilinos/Trilinos/tree/stk-boost-isystem-1137

However, there are still many compile lines that have the `-I` form of Boost include instead of the `-isystem` form.  I am currently digging into why this might be the case and how to address this.

@bathmatt, one easy hack to remove get boost include dirs to use `-isystem` instead of `-I` is the post-process the CMake-generated `flags.cmake` files and replace `-I<boost_include_dir>` with `-system <boost_include_dir>`.  Is that something that would help you in debugging in the short term?  If so, I can likely provide a single script that will make these replacements pretty fast.  If not, I will keep digging trying to figure out how to get CMake to pu in `-isystem <boost_include_dir>` instead of `-I<boost_include_dir>`.

**Comment by bathmatt** [comment]
Correct, we don't use classic anymore.
There is no reason to build that script. I think we can wait until the full
merge.

**Comment by bathmatt** [comment]
@bartlettroscoe this is a huge huge improvement :)...  @mwglass can we look at getting this through the chain of commits to get it into the trilinos build?  Who takes care of this?  Is it @bmpersc

**Comment by mwglass** [comment]
Sure, if someone can send me a patch file with all the necessary changes we can get these pushed to the main STK repo.

**Comment by bathmatt** [comment]
Emailed to Mike internally

**Comment by bartlettroscoe** [comment]
> If someone can send me a patch file with all the necessary changes we can get these pushed to the main STK repo.

The patch can be created by simply doing:

```
$ cd Trilinos/
$ git remote add github git@github.com:trilinos/Trilinos.git
$ git fetch github
$ git format-patch -1 -o ../patches 644c9dc
```

The you just apply the patch to the STK native git repo using `git am -p<num> <name-of-git-patch>.patch`.  That way, my commit message is preserved and I get credit for the fix :-)

**Comment by bartlettroscoe** [comment]
Once this is committed to the STK repo and then STK is snapshotted back to Trilinos, then we can delete the branch `stk-boost-isystem-1137 ` and close this issue.

**Comment by mwglass** [comment]
The patch was pushed to the Sierra repo today so it will be available in the next STK snapshot.

**Comment by bathmatt** [comment]
Thanks!!

**Comment by bartlettroscoe** [comment]
I believe this was resolved a long time ago.  Closing as complete.
