### ISSUE TITLE
Nightly failure for XYCE build

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#1145]
Ifpack fails to build for the no-C++11 XYCE build as seen [here](http://testing.sandia.gov/cdash/viewBuildError.php?buildid=2788850).

@bmpersc have you looked at this at all?

This is the last current failure for the XYCE build remaining related to issue #1129

**Comment by mhoemmen** [comment]
That's weird, the build error suggests that EpetraExt is not enabled (or at least that `HAVE_IFPACK_EPETRAEXT` is not defined).

**Comment by jwillenbring** [comment]
Here is the output for this failure, and a newer link:

/data/jenkins/slave/workspace/Trilinos_XYCE_MPI/MPI_OPT_DEV_XYCE/Trilinos/packages/ifpack/src/Ifpack_SparseContainer.h: In member function ‘virtual int Ifpack_SparseContainer<T>::Initialize()’:
/data/jenkins/slave/workspace/Trilinos_XYCE_MPI/MPI_OPT_DEV_XYCE/Trilinos/packages/ifpack/src/Ifpack_SparseContainer.h:394: error: ‘Epetra_DataAccess’ is not a class or namespace

[http://testing.sandia.gov/cdash/viewBuildError.php?buildid=2883560](http://testing.sandia.gov/cdash/viewBuildError.php?buildid=2883560)

I was able to reproduce this failure with the following do-configure arguments on a vanilla RHEL 6 machine with no special setup:

cmake \
-DTrilinos_ENABLE_CXX11=OFF \
-DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-DTrilinos_ENABLE_Ifpack:BOOL=ON \
../Trilinos

I see a possibly related commit:

929ce0859b92a77400f
Ifpack_SparseContainer: Copy --> ::Copy to allow compilation with clang (#589)

@CamelliaDPG Do you know if the Epetra_DataAccess call change that you made is compatible with non-C++11 compilers? We still need to be able to compile Ifpack with gcc 4.4.7, which is not the case with several other Trilinos packages.

**Comment by hkthorn** [comment]
Unfortunately the scoping of the Epetra_DataAccess enumeration was made necessary by some C++11 compliant compilers.  I only say that because a similar change to that found in Ifpack was placed in Belos, by me, due to a user complaint.  If both Ifpack and Belos use the TEUCHOSCORE_CXX11 flag that is defined if Trilinos is compiled with C++11 enabled, we can circumvent this compiler issue.  If that's not too offensive, I can make the changes, test, and check them in.

**Comment by jwillenbring** [comment]
@hkthorn Given the situation, I find that to be a reasonable solution.

**Comment by hkthorn** [comment]
@jwillenbring @bmpersc If the changes that have been committed on the develop branch enable this testing to successfully complete, I would like to ask for a Trilinos 12.10.2 release that has (at the very least) this commit cherry-picked onto it.  Our immanent release of Xyce 6.7 does not require 12.10, but it is possible we will need a 12.10 for our next release this fall.

**Comment by hkthorn** [comment]
@jwillenbring @bmpersc So, it looks like the tests are not running, so jenkins is still reporting a failure for this testing script, https://jenkins-srn.sandia.gov/view/Trilinos/job/Trilinos_XYCE_MPI/.

However, the build is succeeding is succeeding now, the tests are not being run because of some issue, http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2888438
