### ISSUE TITLE
use find_package for MKL

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#11479]
I notice that you are using `find_package` left and right for both internal and external packages. Why not blas/mkl? Having to specify the location of the blas/lapack libraries is maybe my least favorite part of the cmake setup. So what's keeping you? I'd love to be able to `-D TPL_USE_MKL` and be done with it.

**Comment by jhux2** [comment]
@trilinos/framework

**Comment by sebrowne** [comment]
@VictorEijkhout  If you'd like to submit a pull request with this change, we'd be happy to consider adopting it if it passes testing.  We (framework team) do not have capacity to perform this work in the near future, given that it does currently function for all of our internal testing.

I will say that I think the main reason is that it's not quite as simple as find_package(mkl), because we do want to allow alternative BLAS/LAPACK implementations (ARMPL, ESSL, Netlib, etc.) and we usually end up just passing them explicitly in my experience.  MKL is the most verbose in terms of how many things you have to pass given how Intel has the libraries broken up, to be sure.
