### ISSUE TITLE
Site name consistency

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#1156]
@trilinos/framework @bartlettroscoe @bmpersc 

Kitware is implementing a feature that will help us identify when a test goes missing on the dashboard. To do this, a consistent site name is required. Our machines are currently identified on the CDash dashboard by machine name. However, in situations where jobs float (including parameterized builds on the other build farm), jobs can run on different machines, and are currently listed as different sites. Could we perhaps assign a single site to all machines on the build farm, or define a "site" per job run?

Done for this ticket is to better define the issue, determine how to get site consistency, and implement the solution.

**Comment by bmpersc** [comment]
Do we have control over the site name or is it always pulled from the machine's URL? If it is pulled from the URL I don't see how this would be possible since by definition floating jobs means they end up on different machines which also implies a different URL. If we can set the site name then we could set it to something like the build farm it is on which wouldn't change even if the job landed on a different jenkins slave.

**Comment by bartlettroscoe** [comment]
It is single variable `CTEST_SITE` you set for CTest Driver scripts using TribitsCTestDriverCore.cmake:

```
  # The name of the site in the dashboard (almost never need to override this)
  SET_DEFAULT_AND_FROM_ENV( CTEST_SITE ${CTEST_SITE_DEFAULT} )
```

So when you call `ctest -S <script_name>.cmake`, you can pass this in as `env CTEST_SITE=<whatevery> ctest -S <script_name>.cmake` or you can set a variable in your `<script_name>.cmake` file.

Any questions?



*

**Comment by bartlettroscoe** [comment]
NOTE: `CTEST_SITE` is a built-in ctest var:

* https://cmake.org/cmake/help/v3.1/variable/CTEST_SITE.html

TribitCTestDriverCore.cmake just gives it a logical default name.
