### ISSUE TITLE
python detection in 12-8-1

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#11592]
```
-- Found PythonInterp: /opt/apps/intel19/python3/3.7.0/bin/python3 (Required is at least version "2.6")
  File "<string>", line 1
    import sys; print sys.version.split()[0]
                        ^
```

Just guessing: you're using python2 syntax for the `print` statement.

**Comment by jhux2** [comment]
@trilinos/framework @ccober6 Not sure who should own this.

**Comment by sebrowne** [comment]
Agreed.  I'm not sure that v12-8-1 was ever intended to be compatible with Python3.  Is there a reason that you need that version (asking since it's from 09/2016)?

Not that it's not still an issue, and I'm perfectly willing to fix it (Framework can own that) if it is, but I'd rather not go fix it on the v12 branch unless there's a pressing reason.

@ccober6 as usual, I'll defer to you if you feel differently.

**Comment by ccober6** [comment]
In general, we are not going to support versions that old, but as @sebrowne mentioned we can we can fix it in more recent versions.  @VictorEijkhout can you confirm the issue still exists on the develop or master branch?

**Comment by VictorEijkhout** [comment]
I'm not sure where I got the notion to use this old version. I've switched to 13.4.1 (btw, why do you advertise it as `13.4.1` but the tar file says `13-4-1`?) and that works fine.
