### ISSUE TITLE
trilinos.org uses an invalid security certificate

### ISSUE THREAD

**Issue by Sbte** [trilinos/Trilinos#1162]
Firefox tells me this:

trilinos.org uses an invalid security certificate.

The certificate is not trusted because it was signed using a signature algorithm that was disabled because that algorithm is not secure. Error code:

SEC_ERROR_CERT_SIGNATURE_ALGORITHM_DISABLED

**Comment by aprokop** [comment]
Duplicate of #120.

**Comment by ericrhenry** [comment]
Resolved how? Attempted fetches from the site are still breaking because of certificate issues. This is a current attempt by Gentoo emerge to fetch trilinos:

Connecting to trilinos.org|207.211.63.18|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://trilinos.org/oldsite/download/files/trilinos-12.12.1-Source.tar.gz [following]
--2018-10-30 09:17:16--  https://trilinos.org/oldsite/download/files/trilinos-12.12.1-Source.tar.gz
Connecting to trilinos.org|207.211.63.18|:443... connected.
ERROR: The certificate of 'trilinos.org' is not trusted.
ERROR: The certificate of 'trilinos.org' hasn't got a known issuer.
!!! Couldn't download 'trilinos-12.12.1-Source.tar.gz'. Aborting.

**Comment by mhoemmen** [comment]
@trilinos/framework

**Comment by ericrhenry** [comment]
Sorry, that was a bit terse for me. (New to GitHub) Would it be possible to elaborate?


Thanks,

Eric


________________________________
