### ISSUE TITLE
Windows install capability test driver

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#1164]
@trilinos/framework 

We need to develop a small test driver to demonstrate the functionality of the Windows install capability described in issue #1163.

This ticket is for tracking the development of that driver, as well as setting up nightly testing through Jenkins to protect that functionality.

**Comment by mplooster** [comment]
@trilinos/framework 
Is it possible to simply re-use the test and/or examples code for each package and use that as the test driver? It seems like you might get more coverage that way.

**Comment by mplooster** [comment]
@trilinos/framework 
Or we could use some of the available tutorials as the test driver, which would give the tutorials some additional testing.

**Comment by bmpersc** [comment]
There is an existing capability that changes the Trilinos configure to build against an installed set of libraries and headers and then runs the same tests that a normal configure would run. Unfortunately this has never been tested on windows, and is possible that it has been broken in the general case as there have been numerous updates to the build system since the last time we ran it.

In any event the option is:

-DTrilinos_INSTALLATION_DIR=<path to installation of Trilinos>

Setting that should automatically put the configure/build into installation testing mode. However, if it doesn't you can force it with:

-DTrilinos_ENABLE_INSTALLATION_TESTING=ON
