### ISSUE TITLE
Ifpack2: error when both FastILU and Sacado enabled

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#11656]
If Ifpack2, Sacado and ShyLU_NodeFastILU are enabled together, there are a couple of build errors:

```
In file included from ompBuild/packages/stokhos/src/Ifpack2_Details_FastILU_Base_MP_Vector_16_OpenMP.cpp:51:
Trilinos/packages/ifpack2/src/Ifpack2_Details_FastILU_Base_def.hpp: In instantiation of ‘Ifpack2::Details::FastILU_Base<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Params::Params(const Teuchos::ParameterList&, std::string) [with Scalar = Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::OpenMP> >; LocalOrdinal = int; GlobalOrdinal = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>; std::string = std::__cxx11::basic_string<char>]’:
ompBuild/packages/stokhos/src/Ifpack2_Details_FastILU_Base_MP_Vector_16_OpenMP.cpp:55:1:   required from here
Trilinos/packages/ifpack2/src/Ifpack2_Details_FastILU_Base_def.hpp:508:13: error: cannot convert ‘const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::OpenMP> >’ to ‘double’ in assignment
  508 |       omega = pL.get<magnitude>("damping factor");
Trilinos/packages/ifpack2/src/Ifpack2_Details_FastILU_Base_def.hpp:519:13: error: cannot convert ‘const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::OpenMP> >’ to ‘double’ in assignment
  519 |       shift = pL.get<magnitude>("shift");
```

At first glance, it looks like the Ifpack2 wrapper for FastILU is assuming that Scalar can be implicitly converted to double.

**Comment by maartenarnst** [comment]
Hi @brian-kelley.  We've seen similar issues in the past when using stokhos and ifpack2 with shylu. I can talk a bit about what we saw, but it's probably best to check with @etphipp.

It seems the issue here is with the Stokhos ensemble type ("MP Vector").  Stokhos has two modes for working with the ensemble type in linear solvers.  The first one is called "without ensemble reduction" (cmake option `"Stokhos_ENABLE_Ensemble_Reduction" : "ON",`). In this case, the results of inner product and norm calculations are ensembles.  So, the magnitude type is an ensemble, which seems to then lead to the issue you are describing.  The second one is "with ensemble reduction" (cmake option `"Stokhos_ENABLE_Ensemble_Reduction" : "ON",`).  In that case, Stokhos automatically reduces the results of inner product and norm calculations to usual scalar types.  If you use this mode "with ensemble reduction", the particular problem that you raise in your issue above can be expected to disappear.

I guess the bigger issue though is whether the algorithm that you are calling from Ifpack2 remains valid when you instantiate it for the Scalar set to the ensemble type.  That question would be relevant both in the case with ensemble reduction and in the case without ensemble reduction.  You can prevent Stokhos from instantiating Ifpack2 functions for the ensemble type by using the cmake option `"Stokhos_ENABLE_Ifpack2" : "OFF"`.

When we experimented with all this some time ago, we found issues similar to the one you saw in files in shylu code itself too.

**Comment by etphipp** [comment]
It looks like the issue is `omega` and `shift` are stored explicitly as doubles, but assigning values of type `magnitude`, i.e., implicitly assuming `magnitude == double`.  I would suggest changing the type of `omega` and `shift` to `magnitude`, or just drop the lines that test for `magnitude` in the parameter list.
