### ISSUE TITLE
AztecOO: failing build with intel compiler

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#11788]
The Albany intel builds last night failed due to an AztecOO error that looks like this: 

```
az_util.c:(.text+0x30b): undefined reference to `ddot_'
/.../test/TrilinosIntelInstall/lib/libaztecoo.a(az_util.c.o): In function `AZ_compare_update_vs_soln':
```
Please see the following links for more info: 

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=47333
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=47330

Could someone please look at / resolve this?

@trilinos/aztecoo

**Comment by jhux2** [comment]
@ikalash I'd guess this is an environment issue. The Albany builds were clean on 11-April, and there weren't any changes after that in Trilinos that could cause this.
```
git log --oneline 8af57365121^..8af57365121
8af57365121 Merge pull request #11780 from trilinos/revert-11728-fix_stk_sycl
15d5c87f7c7 (origin/revert-11728-fix_stk_sycl) Revert "STK: Fix compiling with SYCL"
```

**Comment by ikalash** [comment]
Thanks @jhux2 .  I'm not sure I follow what you mean about it being an environment issue and how the stk commit above would cause the issue.  Can you please clarify?  I thought at first that it might be a glitch that randomly happened on one machine, but then noticed that we got the same error in all the intel builds we have, not just 1.

**Comment by jhux2** [comment]
@ikalash and I took at look at the link lines.  We noticed that the AztecOO library occurs after the MKL library in the link line.  I've seen cases where ordering matters (it's really linker dependent).  @ikalash is going to investigate a bit further.

**Comment by ikalash** [comment]
So I built Trilinos from 4/10 (when the nightlies were clean), and Albany on top of it, and still got the error.  This suggests the error is not due to changes to Trilinos or Albany, but rather the environment.  I tried adding to the link line in one of Albany's link.txt files another instance of the mkl library around the aztecoo library, and still got the error - this is something @jhux2 suggested (that maybe the order of mkl and aztecoo in the link line got messed up).  I'm not sure how to proceed, namely whether the issue is with the mkl library itself, or with the link line auto generated by Albany/Trilinos.

**Comment by jhux2** [comment]
@ikalash Could you check with `nm` if the symbol appears in the MKL library?

**Comment by ikalash** [comment]
I see a lot of variants of the undefined routines, e.g., 
```
_def_BLAS_ddot_d_s.o:
0000000000000000 T mkl_xblas_def_BLAS_ddot_d_s
```
It's true for the other undefined symbols too.  Is that what you are asking @jhux2 ?

**Comment by ikalash** [comment]
FWIW, I tried removing Epetra/AztecOO from the build, and got similar errors from blas coming from other libraries that use blas (not surprisingly): 

```
[ 98%] Building CXX object src/CMakeFiles/AlbanyAnalysis.dir/Main_Analysis.cpp.o
/projects/albany/nightlyCDash/repos/Trilinos/build-intel/install/lib/libkokkoskernels.a(KokkosBlas_Host_tpl.cpp.o): In function `KokkosBlas::Impl::HostBlas<float>::scal(int, float, float*, int)':
KokkosBlas_Host_tpl.cpp:(.text._ZN10KokkosBlas4Impl8HostBlasIfE4scalEifPfi[_ZN10KokkosBlas4Impl8HostBlasIfE4scalEifPfi]+0x24): undefined reference to `sscal_'
/projects/albany/nightlyCDash/repos/Trilinos/build-intel/install/lib/libkokkoskernels.a(KokkosBlas_Host_tpl.cpp.o): In function `KokkosBlas::Impl::HostBlas<float>::iamax(int, float const*, int)':
KokkosBlas_Host_tpl.cpp:(.text._ZN10KokkosBlas4Impl8HostBlasIfE5iamaxEiPKfi[_ZN10KokkosBlas4Impl8HostBlasIfE5iamaxEiPKfi]+0x14): undefined reference to `isamax_'
/projects/albany/nightlyCDash/repos/Trilinos/build-intel/install/lib/libkokkoskernels.a(KokkosBlas_Host_tpl.cpp.o): In function `KokkosBlas::Impl::HostBlas<float>::nrm2(int, float const*, int)':
KokkosBlas_Host_tpl.cpp:(.text._ZN10KokkosBlas4Impl8HostBlasIfE4nrm2EiPKfi[_ZN10KokkosBlas4Impl8HostBlasIfE4nrm2EiPKfi]+0x14): undefined reference to `snrm2_'
/projects/albany/nightlyCDash/repos/Trilinos/build-intel/install/lib/libkokkoskernels.a(KokkosBlas_Host_tpl.cpp.o): In function `KokkosBlas::Impl::HostBlas<float>::asum(int, float const*, int)':
KokkosBlas_Host_tpl.cpp:(.text._ZN10KokkosBlas4Impl8HostBlasIfE4asumEiPKfi[_ZN10KokkosBlas4Impl8HostBlasIfE4asumEiPKfi]+0x14): undefined reference to `sasum_'
```
and 
```
/projects/global/toss3/compilers/intel/intel_2019/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64/libmkl_core.a(_avx2_cpotrf_l_small.o): In function `mkl_lapack_ps_avx2_cpotrf_l_small':
cpotrf_l_small.f:(.text+0x73f): undefined reference to `mkl_blas_csscal'
cpotrf_l_small.f:(.text+0x8a9): undefined reference to `mkl_blas_cdotc'
cpotrf_l_small.f:(.text+0x928): undefined reference to `mkl_blas_cgemv'
/projects/global/toss3/compilers/intel/intel_2019/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64/libmkl_core.a(_avx_spotrf_l_small.o): In function `mkl_lapack_ps_avx_spotrf_l_small':
```
The symbols above are in the mkl lib on attaway according to ``nm``.  Does this mean that the link order is likely the culprit?

**Comment by jhux2** [comment]
> I see a lot of variants of the undefined routines, e.g.,
> 
> ```
> _def_BLAS_ddot_d_s.o:
> 0000000000000000 T mkl_xblas_def_BLAS_ddot_d_s
> ```
> 
> It's true for the other undefined symbols too. Is that what you are asking?

The linker error indicates that the symbol `ddot_` can't be found.  If `ddot_` were in libraries that appear on the link line, then reordering might help.  However, since the symbol is apparently not in the library, then reordering won't be effective.

Since you did find the symbols on attaway, adding the blas/lapack libraries at the end of the link line might be effective there.

**Comment by ikalash** [comment]
Thanks @jhux2 .  I tried hacking the link like in links.txt, but it is not helping.  I also tried using a different mkl, which also does not ask.

@jewatkins , can I ask you to please have a look at this?  Basically Albany doesn't built anymore with an intel compiler on CEE and attaway due to link errors having to do with blas/mkl.  The builds were fine 4/11.  If I clone a Trilinos from 4/10, I still get the problem, indicating the issue is somehow with the environment and/or mkl library.  I can open a separate Albany issue.

**Comment by sebrowne** [comment]
@ikalash how exactly are you linking with MKL?  It can get a bit complicated if you do it manually with the different libraries explicitly, but also even if you use the '-mkl' option to the compiler driver.  Also, are you using shared or static MKL?  If static, there is a special way that you have to tell the linker "these libraries may have circular dependencies, resolve those please instead of erroring" (or at least it used to).  I've found [this](https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-link-line-advisor.html) to be an excellent tool for helping figure out the "right" way to link against MKL.

**Comment by jewatkins** [comment]
@sebrowne they point to the static library and have `-mkl`. see:
https://github.com/sandialabs/Albany/blob/master/doc/dashboards/attaway-login1/do-cmake-trilinos-attaway-intel-serial#L15
https://github.com/sandialabs/Albany/blob/master/doc/dashboards/cee-compute011.sandia.gov/do-cmake-trilinos-mpi-sems-intel#L15
If you point me to what trilinos does in their nightlies I can just modify them to do the same. That's assuming you guys aren't seeing this issue.

**Comment by jjellio** [comment]
Alot of these kind of things can be aleviated if everything "we" add is wrapped in a `-Wl,--start-group` ... then after all of the linker flags + args, `-Wl,--end-group`.  `-mkl` creates a group around itself (ior use to), because MKL's link is circular.

For Trilinos, it's not that our stuff is circular, it's that it's obnoxiously long to write the proper order (it replicates libs + paths). Instead of all that replicate, I've advocated a few times to wrap our gunk (no duplicates) in a group.  It's not technically correct, i.e., if our libs define the same symbol twice. Spelling out the exact libs in order would ensure the correct symbol is found. But no one should be dropping duplicate symbols in the library to begin with.

The reason the linker group often fixes this stuff, is because if you spelled out:

`-lteuchos -llapack -lblas .... -lazetecoo -lfoo -lalbany_awesome.`  by default that would fail if azetecoo, foo, or albany_awesome want to use lapack/blas.  

Wrapped in a group, 
`-Wl,--start-group -lteuchos -llapack -lblas .... -lazetecoo -lfoo -lalbany_awesome -Wl,--end-group `  
the linker would hit albany_awesome, find a missing symbol - then "try again from the start of the group to find that symbol.... and it would conveniently find blas.  It's not foolproof, and package's Cmake logic can break it, if they try to compress/reorder the link line - if they aren't aware of how to respect groups.

Groups seems supported by every Linux (ELF) linker I've touched. No idea if Mac's support them.

**Comment by bartgol** [comment]
This seems to be a problem in propagating `-mkl` flag to albany. In our albany builds, we build trilinos adding `-mkl` manually to the compiler flags. This forces us to add it also to Albany, which is suboptimal (I want CMake to do all of the flags handling). If one accidentally forgets the flag (and that's what happened in our albany build), the compiler spits out this kind of errors.

Knowing how big of a CMake fan trilinos is, I digger in the cmake folder, and found this comment in FindTPLMKL.cmake:
```
# Here is a combination of CMake options that worked for me, when
# building and running on Linux, using the single dynamic library
# option with MKL 10.3:
#
# -D BLAS_LIBRARY_DIRS:FILEPATH="${MKLROOT}/lib/intel64" 
# -D BLAS_LIBRARY_NAMES:STRING="mkl_rt" 
# -D LAPACK_LIBRARY_DIRS:FILEPATH="${MKLROOT}/lib/intel64" 
# -D LAPACK_LIBRARY_NAMES:STRING="mkl_rt" 
# -D MKL_LIBRARY_DIRS:FILEPATH="${MKLROOT}/lib/intel64" 
# -D MKL_LIBRARY_NAMES:STRING="mkl_rt" 
# -D MKL_INCLUDE_DIRS:FILEPATH="${MKLROOT}/include" 
# 
# where the MKLROOT environment variable points to my MKL install
# directory.
```
Is the proper trilinos-approved way to build with MKL to specify those cache vars? Will this successfully propagate the flags to the downstream apps, without them having to add any mkl flag?

**Comment by jjellio** [comment]
That probably works if you always have lapack (and blas) used - almost always due to Trilinos. With Intel 19 (sems), this is what `icc -mkl foo.c` does:

```
ld    /lib/../lib64/crt1.o /lib/../lib64/crti.o /ssd_scratch/src/sems-projects/sems/install/rhel7-x86_64/sems/compiler/gcc/6.1.0/base/bin/../lib/gcc/x86_64-pc-linux-gnu/6.1.0/crtbegin.o --eh-frame-hdr --build-id -dynamic-linker /lib64/ld-linux-x86-64.so.2 -m elf_x86_64 -o a.out \
-L/ssd_scratch/src/sems-projects/sems/install/rhel7-x86_64/sems/compiler/intel/19.0.5/base/compilers_and_libraries_2019.5.281/linux/compiler/lib/intel64_lin \
-L/ssd_scratch/src/sems-projects/sems/install/rhel7-x86_64/sems/compiler/intel/19.0.5/base/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64_lin \
-L/ssd_scratch/src/sems-projects/sems/install/rhel7-x86_64/sems/compiler/gcc/6.1.0/base/bin/../lib/gcc/x86_64-pc-linux-gnu/6.1.0/ -L/ssd_scratch/src/sems-projects/sems/install/rhel7-x86_64/sems/compiler/gcc/6.1.0/base/bin/../lib/gcc/ -L/ssd_scratch/src/sems-projects/sems/install/rhel7-x86_64/sems/compiler/gcc/6.1.0/base/bin/../lib/gcc/x86_64-pc-linux-gnu/6.1.0/../../../../lib64 -L/ssd_scratch/src/sems-projects/sems/install/rhel7-x86_64/sems/compiler/gcc/6.1.0/base/bin/../lib/gcc/x86_64-pc-linux-gnu/6.1.0/../../../../lib64/ -L/lib/../lib64 -L/lib/../lib64/ -L/usr/lib/../lib64 -L/usr/lib/../lib64/ -L/ssd_scratch/src/sems-projects/sems/install/rhel7-x86_64/sems/compiler/gcc/6.1.0/base/bin/../lib/gcc/x86_64-pc-linux-gnu/6.1.0/../../../ -L/lib64 -L/lib/ -L/usr/lib64 -L/usr/lib \
--start-group -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 --end-group \
-Bdynamic --verbose /tmp/iccqip1Jo.o \
--start-group -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 --end-group \
-Bdynamic -Bstatic -limf -lsvml -lirng -Bdynamic -lm -Bstatic -lipgo -ldecimal --as-needed -Bdynamic -lcilkrts -lstdc++ --no-as-needed -lgcc -lgcc_s -Bstatic -lirc -Bdynamic -lpthread -Bstatic -lsvml -Bdynamic -lc -lgcc -lgcc_s -Bstatic -lirc_s -Bdynamic -ldl -lc /ssd_scratch/src/sems-projects/sems/install/rhel7-x86_64/sems/compiler/gcc/6.1.0/base/bin/../lib/gcc/x86_64-pc-linux-gnu/6.1.0/crtend.o /lib/../lib64/crtn.o
```

The way I've done MKL in Trilinos, is to set
`-D TPL_BLAS_LIBRARIES="-mkl"` (and lapack as well).  That way I'm not really telling Cmake to find Intel's libs.  It's been a while, but you could need to set that on the TPL_BLAS_INCLUDE line too. The `TPL_` lines get taken verbatim (no searches happen)

**Comment by bartgol** [comment]
@jjellio Does that get automatically propagated to downstream apps too? I would like not to have to add `-mkl` to all the apps building against trilinos, but have CMake do the job.

**Comment by jjellio** [comment]
It would propagate as your TPL blas or LAPACK library.
