### ISSUE TITLE
Consider taking advantage of new CUDA language support in CMake 3.8.0

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1180]
**Description:**

I was looking over the release notes for CMake 3.8 at:

* https://cmake.org/cmake/help/v3.8/release/3.8.html

and it says that CUDA is now a first-class CMake language and it supports the nvcc compiler.

Should this be something that we look into for Trilinos?

**CC:** @trilinos/framework, @trilinos/tpetra, @crtrott, @nmhamster

**Comment by bartlettroscoe** [comment]
@bradking, what is the story behind the new native CMake support for CUDA and NVCC with CMake 3.8?  Does it work correctly with Ninja?  Does it work with MPI?  What would it take to try this out for Trilinos (perhaps with changes in  TriBITS to support this)?  What are the advantages of this over the current approach that Trilinos uses now which is use nvcc_wrapper provided by Kokkos:

* https://github.com/kokkos/kokkos/blob/master/config/nvcc_wrapper

as the C++ compiler with the MPI compiler wrappers (using the env var `OMP_CXX`)?

@crtrott and @nmhamster, would you or others be interested in discussing this with Kitware employees and see if this might be a good thing for Kitware to try out with Trilinos (through the existing SNL Kitware contract work)?

It seems like it would be nice if CMake could just natively and more transparently handle CUDA and eliminate the need for something like nvcc_wrapper.  Or is that just not realistic?

**Comment by bradking** [comment]
@bartlettroscoe CMake 3.8 adds native support for the CUDA language and `nvcc` compiler so that one can just list `.cu` source files and they will be compiled as CUDA (one can also set the `LANGUAGE` source file property of `.cpp` files to have them treated as `CUDA`).  The language can be enabled with `enable_language(CUDA)` just like `C`, `CXX`, and `Fortran` can.  It works with the Ninja, Makefiles, and VS IDE generators.

IIUC `nvcc_wrapper` tries to make `nvcc` look like a normal C++ compiler so that CMake's normal C++ support can be used (CUDA in `.cpp` files).  With CMake's new native support, `nvcc` can be used directly instead, but should generally be used only for sources that really are CUDA.  CMake supports mixing CUDA and C++ together just as it does Fortran and C++ (I haven't tried CUDA+Fortran but in principle it should work).

`nvcc_wrapper` supports being run underneath the MPI compiler front-ends through `OMP_CXX` in order to allow `mpic++` to be the compiler and still run `nvcc` underneath.  Such a wrapper may still be necessary for that particular ordering because I don't think MPI compiler wrappers support something like `OMP_CUDA`.  However, there may be another approach.  With CUDA as a first-class language one could run `nvcc` as the CUDA compiler and then tell it to use `mpic++` as the host compiler.  This could be done with CMake with the environment `CC=mpicc CXX=mpic++ CUDACXX=nvcc CUDAHOSTCXX=mpic++`.

Alternatively if one keeps all the MPI code in `.cpp` files and all the CUDA code in `.cu` files then one could build with just `CC=mpicc CXX=mpic++ CUDACXX=nvcc` (plus other variables to make both the MPI compiler wrappers and nvcc use the same host compiler underneath if they don't by default).

**Comment by mhoemmen** [comment]
> With CMake's new native support, nvcc can be used directly instead, but should generally be used only for sources that really are CUDA.

A major point of Kokkos is that you can intersperse Kokkos::parallel_* calls with other code, including MPI code.  Thus, I don't think this feature will help us at all.  Otherwise, we would have to wrap everything that might possibly have CUDA things in it (including Kokkos::View declarations, since they have `__device__` instance methods) and put it in separate files from everything not-CUDA.

**Comment by bathmatt** [comment]
Will this resovle the ninja build issue maybe ???

**Comment by bartlettroscoe** [comment]
From the above discussion, it sounds like the CUDA language supported by CMake 3.8+ is likely not the best approach for Trilinos right now (or ever).

If there is no objections, we should close this issue.  But I think it is good we had this discussion so that when someone ask "why does Kokkos/Trilinos not just use built-in CUDA support in CMake?" then we can point to this issue for the reason.

> Will this resovle the ninja build issue maybe ???

@bradking already proposed a fix for nvcc_wrapper for ninja in:

* https://github.com/kokkos/nvcc_wrapper/pull/5

It has just not been further tested and accepted.  It is my hope that this will resolve the problems with ninja and nvcc_wrapper.

The script nvcc_wrapper is large enough and complex enough that it should likely have its own set of unit tests.  I would be nervous to make any major edits to that script without that in place.

**Comment by crtrott** [comment]
I will close this now, but add one comment: the biggest problem is still MPI. Unfortunately you can not use an MPI wrapper as the host compiler for NVCC. We tried that approach and it failed miserably for various reasons. Otherwise what CMAKE provides is actually sufficient, since we could just define all cpp files which contain Kokkos code as CUDA language files.
