### ISSUE TITLE
Teuchos: Remove Teuchos_ENABLE_LONG_LONG_INT option

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1183]
@trilinos/teuchos 

The ability to disable `long long` support in Teuchos causes spurious issues like #1161.  The only reason not to allow use of `long long` is because of some Teuchos users who do not enable C++11 in their builds.  We need to respect these users, but it doesn't make sense to make `Teuchos_ENABLE_LONG_LONG_INT` a user-settable option.  If you have C++11, you should get `long long`, whether you want it or not.

**Comment by bartlettroscoe** [comment]
In my opinion, the default global ordinal type for Trilinos should be `long long int` and users of Trilinos should need to ask for additional instantiations for global ordinal type `int`.  But I guess if the Epetra packages get enabled, then we have no choice but to also include `int` instantiations?  Note that Epetra does support 64 bit integers so in theory, even with Epetra turned on, we could disable global ordinal `int` instantiations.  However, even if the user asks for global ordinal instantations of type `int` and never needs (or wants) `long long int`, I don't think we need to bother with disabling `long long int` instantiations.  The only price they pay is longer build times.  That is all.

I think we need to make this change, otherwise, we will be suffering two sets of template instantiations, for the Tpetra stack one for `long long int` and  one for `int`.

**Comment by ibaned** [comment]
Isn't enabling `long long` in Teuchos different from instantiating it as a global ordinal type in Tpetra ? I think the Tpetra option has much more effect in terms of compile time *and binary size*.

Still, I agree with @bartlettroscoe that `long long` is a good default global ordinal type for Tpetra. There should be only one default, from which it follows that `int` would need to be explicitly requested.

On the other hand, I don't think it should be impossible to disable `long long` as a Tpetra global ordinal. There should remain some way to disable it, although it can becomes less default and more explicit, thats fine.

Again, all the above applies to Tpetra defaults. This issue is for Teuchos, in which case I agree with @mhoemmen that unless you don't have C++11, `long long` can always be enabled in Teuchos.

**Comment by mhoemmen** [comment]
@ibaned wrote:
> Isn't enabling `long long` in Teuchos different from instantiating it as a global ordinal type in Tpetra ?

That's correct.  This issue is about Teuchos' support for `long long`.  This matters mainly because Teuchos must support C++98 compilers that do not implement `long long`.  I'm proposing that, rather than having a separate CMake option for `long long` support, Teuchos should instead just test C++11.

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> In my opinion, the default global ordinal type for Trilinos should be `long long int` and users of Trilinos should need to ask for additional instantiations for global ordinal type `int`.

I'm with you :-) In fact, I would go a bit farther to say that that Tpetra should have one 64-bit global ordinal type, whatever it happens to be, and it should not be a template parameter.  Users who want other GO types should do the conversions themselves.  Almost all the pain with too many enabled template parameter combinations came from giving users choice where they didn't need it, because it never had a significant effect on performance for most applications.  The only index type in Tpetra that matters for performance or capability is the local ordinal type.  See #280.

> But I guess if the Epetra packages get enabled, then we have no choice but to also include `int` instantiations?

See #74, #537, etc.

**Comment by bartlettroscoe** [comment]
> I would go a bit farther to say that that Tpetra should have one 64-bit global ordinal type, whatever it happens to be, and it should not be a template parameter. 

Yes.  A Teuchos::Comm should not be templated on an ordinal parameter either (and I argued against that at the time but was overruled).  In fact, that abstract class should not be templated at all.  Only the helper functions that real with real data should be templated.

This is a great lession on the dangers of over-templating.  I was criticized for not templating the main Thyra interfaces on an ordinal type but I think that was the right thing to do and this discussion just backs that up.
