### ISSUE TITLE
STK: why doesn't stk store all dimensions of a field?

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#11865]
## Question
I was trying to retrieve the dimension of an N-dim field, but noticed that stk only stores the number of scalars per entity and the first dimension, but loses all information about the other dims passed to `put_field_on_mesh`. What's the reason for this choice? Wouldn't it be desirable to be able to query for the original shape of the field? Otherwise what's the point of having all the overloads

```
field_type & put_field_on_mesh(field_type &field, const Selector &selector,  unsigned n1, const typename stk::mesh::FieldTraits<field_type>::data_type* init_value)
field_type & put_field_on_mesh(field_type &field, const Selector &selector,  unsigned n1, unsigned n2, const typename stk::mesh::FieldTraits<field_type>::data_type* init_value)
field_type & put_field_on_mesh(field_type &field, const Selector &selector,  unsigned n1, unsigned n2, unsigned n3, const typename stk::mesh::FieldTraits<field_type>::data_type* init_value)
field_type & put_field_on_mesh(field_type &field, const Selector &selector,  unsigned n1, unsigned n2, unsigned n3, unsigned n4, const typename stk::mesh::FieldTraits<field_type>::data_type* init_value)
field_type & put_field_on_mesh(field_type &field, const Selector &selector,  unsigned n1, unsigned n2, unsigned n3, unsigned n4, unsigned n5, const typename stk::mesh::FieldTraits<field_type>::data_type* init_value)
```
if stk only cares about the product of the 2nd-Nth dimensions? Is there a way for stk to distinguish between the following two?
```
put_field_on_mesh (f, selector, 2,3,4)
put_field_on_mesh (f, selector, 2, 12)
```

Elaborating a bit, It seems to me that `FieldRestriction` could simply store `size_type m_dimension[5]` (since 5 seems to be the max rank per entity), and allow to retrieve the original field layout (field.m_field_rank, if accessible, could help figuring out where to stop when parsing the array).

Is this simply something that was never needed by stk customers, or is there a deeper design choice?

Thanks!

@trilinos/stk

**Comment by tasmith4** [comment]
@alanw0 @djglaze

**Comment by djglaze** [comment]
Hi Luca,

You have locked in on some confusing parts of STK `Field`s that came from the original design that predates everyone currently on the team.  Some of these design choices have been bothering us for a long time, so we've been gradually chipping away at a redesign of how `Field`s are managed for the last couple years.

One issue (that's not directly mentioned in your question) is confusion with the template parameters used at `Field` declaration time, such as:
```
using VectorField = stk::mesh::Field<double, stk::mesh::Cartesian3d>;
VectorField & field = meta.declare_field<VectorField>(stk::topology::NODE_RANK, "velocity");
stk::mesh::put_field_on_mesh(field, meta.universal_part(), 3, nullptr);
```
There is a size and "shape" implied by the template parameter, but also in the numbers passed to `put_field_on_mesh()`.  This is confusing and potentially a source of silent data corruption bugs.  We are in the process of removing the template parameters and relying solely on the `put_field_on_mesh()` calls to give `Field`s their size, like this:
```
using VectorField = stk::mesh::Field<double>;
VectorField & field = meta.declare_field<double>(stk::topology::NODE_RANK, "velocity");
stk::mesh::put_field_on_mesh(field, meta.universal_part(), 3, nullptr);
stk::io::set_field_output_type(field, stk::io::FieldOutputType::VECTOR_3D);  // Optional
```
So, getting to your questions, the up-to-five-dimensional `put_field_on_mesh()` calls are quite misleading, and we actually tried deprecating everything beyond two-dimensional calls a few months ago.  (We had to revert that change, and I don't remember why at the moment.  We'll try again at some point in the future.)

The first "dimension" actually has more meaning than most people realize.  This number is intended to represent the entirety of the datatype per `Entity`.  For example, a value of 1 represents a scalar, 3 might represent a 3D vector, and 9 might represent a full tensor.  This concept is linked closely to I/O, where we can assign a "shape" to this number with a call to `set_field_output_type()` so that components will be subscripted correctly in the output file (e.g. `_xx`, `_xy`, `_xz`, etc. for a tensor).  In application code, it's up to the user to index into the `Field` values correctly for their desired layout.

The second dimension of `put_field_on_mesh()` should be interpreted as the number of "copies" of the fundamental data type.  So, if you wanted to store a full tensor at each of the 8 Gauss points for a linear Hex element, the call might look something like:
```
stk::mesh::put_field_on_mesh(field, meta.universal_part(), 9, 8, nullptr);
```
For output, this would be subscripted as `_xx_1`, `_xy_1`, ..., `_xx_8`, `_xy_8`, ... .  The I/O layers only support two levels of indexing, and inside STK Mesh we only support two levels as well.  If the user provided 3, 4, or 5 dimensions, these would be lumped into the second dimension as copies-of-copies.  We felt this was misleading and confusing, so we tried to deprecate everything beyond 2 dimensions.

We have recently added another set of free functions alongside `stk::mesh::field_scalars_per_entity()`:
```
stk::mesh::field_extent0_per_entity()
stk::mesh::field_extent1_per_entity()
```
which would, for the above example of 8 full tensors per Element, would return 9 and 8, respectively.  Please let me know if this doesn't answer your questions.

Dave

**Comment by alanw0** [comment]
@bartgol could you let us know which application group you are working in, and a short summary of your use-case for multi-dimensional fields?

**Comment by bartgol** [comment]
@djglaze thanks for the thorough overview of how things are the way they are! It helps a lot to understand the underlying assumptions/logic.

@alanw0 , I bumped into this issue while working on Albany. After putting fields on the mesh, in a separate area of the code we are trying to wrap the pointers to the field data into some stk agnostic types. The goal is to allow for a meshLib-agnostic representation of fields, since we are about to support a second mesh library. The highest dimensional fields that Albany supports are 2nd order tensors, located at quadrature points or nodes. After noticing `field_extent0_per_entity/field_extent1_per_entity`, I was assuming there was a `field_extentN_per_entity`, and got puzzled by the fact that it wasn't there. Luckily, I think tensors in Albany are always assumed to be square anyways, so I can get away with 2 dimensions, lumping the tensor dims into a single NxN number.

Follow up question: in Dave's explanation, I notice you guys suggest a layout (element,vector-dim,quadpoint). Is there a reason for making the QP index stride faster than the vec dim? I assume it's probably up to the app what layout to use, but maybe I'm wrong, and there's a deeper reason, perhaps related to how postprocessing tools (like paraview) handle this kind of fields?

**Comment by djglaze** [comment]
@bartgol In STK `Field`s, the first "dimension" strides the fastest.  This is usually the scalar (length 1), vector (length 3), or tensor (length 9) portion of the data.  The second "dimension" is where you should put your multiple copies of the tensor for your QP index.

The low-level SEACAS library will only provide meaningful output subscripting on the first dimension (`_xx`, `_xy`, `_xz`, etc.).  The second dimension (if it's non-unity) will only get numerical subscripts (`_1`, `_2`, `_3`, etc.) appended to the end of the first subscript.  You're right that it's up to the app to index into the block of data for each Entity correctly.  You have free latitude to stride into it however you want, although it's strongly suggested to match the ordering that I/O expects and will subscript for you since there's no way to change that.  Again, the first NxN tensor dimension strides the fastest and the second QP dimension strides second-fastest.

I didn't remember that you were on the Albany team.  I contacted the team a couple months ago about the STK "simple fields" migration to the new workflow.  I volunteered to convert the code for your team since I was already experienced with the kinds of changes needed.  I quickly got stuck and then I've been side-tracked on some other work for a while and haven't returned to it yet.

I found many uses in Albany that that didn't follow this recommended pattern.  For instance, I think I saw things like a 3x3 tensor field being registered with something like `put_field_on_mesh(field, part, 3, 3, nullptr)` instead of `put_field_on_mesh(field, part, 9, nullptr)` like it should be.  This kind of thing would mess up output, and I saw some comments in the code referring to unexpected output subscripting.

Fixing this kind of thing would change the semantics of some of the code and probably cause some tests to diff because some fields might be subscripted differently in the output files, and I don't feel right about making that kind of change as a non-Albany developer.  I think, ideally, I would want to collaborate with you or others on your team to make these changes.  Do you think someone on your team would be open to helping out with this migration?  It almost sounds tangentially related to what you're working on now.

Thanks!
Dave

**Comment by djglaze** [comment]
@bartgol Yes, you're right about the striding.  I just slapped together a quick unit test to demonstrate the striding (and also to confirm my thinking, as I'm starting to second-guess myself).  I create a vector field with two copies like this:
```
auto & field = m_meta->declare_field<int>(stk::topology::NODE_RANK, "junk");
std::array<int, 6> init {1, 2, 3, 4, 5, 6};
stk::mesh::put_field_on_mesh(field, m_meta->universal_part(), 3, 2, init.data());
stk::io::set_field_output_type(field, stk::io::FieldOutputType::VECTOR_3D);
```
So, the vector length (3) comes first and the number of copies (2) comes second.  The 6 initial values are intended to have `{1, 2, 3}` in the first vector and `{4, 5, 6}` in the second vector.  I wrote out the file and then used the `ncdump` tool to see the contents of the Exodus file.  The relevant parts are as follows:
```
 name_nod_var =
  "coordinates_x",
  "coordinates_y",
  "coordinates_z",
  "junk_x_1",
  "junk_y_1",
  "junk_z_1",
  "junk_x_2",
  "junk_y_2",
  "junk_z_2" ;
}

 vals_nod_var1 =  0 ;
 vals_nod_var2 =  0 ;
 vals_nod_var3 =  0 ;
 vals_nod_var4 =  1 ;
 vals_nod_var5 =  2 ;
 vals_nod_var6 =  3 ;
 vals_nod_var7 =  4 ;
 vals_nod_var8 =  5 ;
 vals_nod_var9 =  6 ;
```
You can clearly see that the values are stacked in the `junk` field in the expected order, with the first dimension cycling the fastest.  I'm not sure how you got away with assuming the opposite striding.  As long as you're consistent with it for your calculations and you don't handle file I/O that much, perhaps it's not a big deal.

Although it sounds like a big effort, it might be worth straightening out Albany to stride in the "correct" order and to fix the `put_field_on_mesh()` calls to properly treat the first dimension as the complete datatype length and the second dimension as the number of copies.  The simple fields conversion might amplify any misuse, especially since we still plan on deprecating anything beyond two registered "dimensions".

I'd be happy to consult on these changes if you think it would be helpful.

Dave

**Comment by bartgol** [comment]
Thanks for the follow up Dave.

I suspect the current state of Albany does not use anything other than vectors at nodes (or elems), so 1-dim fields. That would explain why I never noticed that. Old versions of Albany (especially the mechanics pkg) were probably using tensors, but that code has long been removed, so I can't check what it did.

Well, I will keep this in mind, as I go through the code.

Thanks!
