### ISSUE TITLE
Teuchos::SerialDenseMatrix|Vector cannot be used with ParameterList

### ISSUE THREAD

**Issue by vryy** [trilinos/Trilinos#11876]
`Teuchos::SerialDenseMatrix|Vector` does not implement the `operator <<` for stream output, so they cannot be used with `Teuchos::ParameterList`. Because the condition for the parameter entry is `Teuchos::is_printable` returns type `bool`. The code below fails to compile:

    Teuchos::ParameterList params;

    Teuchos::SerialDenseVector<int, int> iv;
    params.set("iv", iv);

Is this the intention or design problem?

**Comment by hkthorn** [comment]
Can you explain what the use case is for a SerialDenseMatrix being a parameter in a parameter list and not an object that is passed in through an object interface?  Thanks!

**Comment by vryy** [comment]
@hkthorn can you elaborate more on the point "object that is passed in through an object interface"? I just want to store the matrix in the ParameterList, just like `Epetra_SerialDenseMatrix`. It is possible, meanwhile not with `Teuchos::SerialDenseMatrix`.

**Comment by hkthorn** [comment]
So, we have been careful about what defines a parameter in a parameter list.  It's often used as a database of items to pass into another object instead of directly through the object interface itself.   I was curious about your use case.

However, in this case, the ostream operators have been deprecated from the serial dense objects in Teuchos.  Please see the PR and associated issues:

https://github.com/trilinos/Trilinos/pull/5085

**Comment by vryy** [comment]
I see, so we should pass the RCP to the parameter instead of a copy

    Teuchos::ParameterList params;

    Teuchos::SerialDenseVector<int, int> iv;
    auto piv = Teuchos::rcpFromRef(iv);
    params.set("iv", piv);

That's fair enough. Thank you.
