### ISSUE TITLE
Kokkos/TriBITs:  cmake complaining about unknown command TRIBITS_EXCLUDE_AUTOTOOLS_FILES

### ISSUE THREAD

**Issue by glhenni** [trilinos/Trilinos#12057]
## Bug Report
As of Friday we have started receiving the error below from cmake when using `github:Trilinos/develop`. I'm guessing it's a sequence error between the kokkos snapshot and the tribits snapshot as they exist within Trilinos. Suggestions?
```
CMake Error at Trilinos/packages/kokkos/cmake/fake_tribits.cmake:176 (TRIBITS_EXCLUDE_AUTOTOOLS_FILES):
  Unknown CMake command "TRIBITS_EXCLUDE_AUTOTOOLS_FILES".
```
@bartlettroscoe 
@crtrott 
@ndellingwood 
@dalg24

**Comment by bartlettroscoe** [comment]
@glhenni, support for `TRIBITS_EXCLUDE_AUTOTOOLS_FILES()` got removed.  See

* https://github.com/TriBITSPub/TriBITS/pull/585

which got snaphotted and merged to Trilinos 'develop' on Thursday in:

* https://github.com/trilinos/Trilinos/pull/12044

It looks like the workaorund I used in:

* https://github.com/trilinos/Trilinos/pull/12044/commits/8495fa0c47cce301bc1bff9491a896416c15119c#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a'

to avoid needing to edit that Kokkos file is not helping Charon because it is not getting that definition.  I can move that dummy  macro into a file that will get processed by the Charon TriBITS project.

**Comment by glhenni** [comment]
I'm a little confused. The change associated with 8495fa0 isn't in develop (4968200) as far as I can tell. 

I can add it to charon's `CMakeLists.txt` easily enough.

**Comment by bartlettroscoe** [comment]
> I'm a little confused. The change associated with [8495fa0](https://github.com/trilinos/Trilinos/commit/8495fa0c47cce301bc1bff9491a896416c15119c) isn't in develop ([4968200](https://github.com/trilinos/Trilinos/commit/49682000bcab01eb43c0335faf1104bc9ac41301)) as far as I can tell.

It is in commit https://github.com/trilinos/Trilinos/pull/12044/commits/8495fa0c47cce301bc1bff9491a896416c15119c as part of PR #12044 that was merged last Thursday as shown in https://github.com/trilinos/Trilinos/pull/12044#event-9815892578.

> I can add it to charon's `CMakeLists.txt` easily enough.

That would be faster.

Once a new Kokkos and KokkosKerenls is snapshotted, this workaround will not be needed.
