### ISSUE TITLE
STK: new put_field_on_mesh syntax

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#12060]
Recently, the syntax in STK changed for routines such as put_field_on_mesh.  In Albany-LCM, we were using the following syntax to deal with stress fields for a number of the solid mechanics problems we have: 

```
  stk::mesh::put_field_on_mesh(
              *qptensor_states.back(), metaData->universal_part(), dim[3], dim[2], dim[1], nullptr);
```
https://github.com/sandialabs/LCM/blob/main/src/disc/stk/Albany_GenericSTKFieldContainer_Def.hpp#L118-L119

This line no longer compiles due to STK changes.  Could someone from the STK team please advise me on how to rewrite the line to work with the current version of STK?

@trilinos/STK

**Comment by djglaze** [comment]
Hi Irina,

We deprecated and eventually removed all overloads of `put_field_on_mesh()` that took more than two numerical arguments.  The main reason was that, internally, we only stored and officially supported two "dimensions".  This is rooted strongly in the fact that the SEACAS library we are built on for file IO only supports two dimensions for output variable name subscripting.

The first dimension is intended to be the size of the fundamental type, so 1 for a scalar, 3 for a vector, 9 for a full tensor, etc.  The second dimension is intended to be the number of "copies" of this datatype.  This is often interpreted as having one of the fundamental datatypes at, say, each gauss point of an element.  Anything beyond these two size arguments were lumped into the second dimension as sort of copies-of-copies so that the overall size of the field would remain correct.  We do not store these extra dimensions and have no way of retrieving them, so it was almost a lie to suggest to the user that they had meaning.

You can recover the old behavior with the new (reduced) API with something like this:
```
stk::mesh::put_field_on_mesh(
            *qptensor_states.back(), metaData->universal_part(), dim[3], dim[2]*dim[1], nullptr);
```

Hope this helps,
Dave

**Comment by ikalash** [comment]
Thank you very much!  This fixes the problem - closing.
