### ISSUE TITLE
Tpetra: Rectangular CrsMatrix

### ISSUE THREAD

**Issue by aellery** [trilinos/Trilinos#12139]
@csiefer2

I am having some difficulty initialising a rectangular Crs Matrix. How can I initialise a CrsMatrix in ℝ^{47x67} which has 100 non-zero elements?

The following code:
`int indexBase = 0;`
`auto comm = Tpetra::getDefaultComm();`
`Teuchos::RCP<const Tpetra::Map<>> row    = Teuchos::rcp ( new Tpetra::Map<>((Tpetra::global_size_t) 100, indexBase, comm));`
`Teuchos::RCP<const Tpetra::Map<>> col    = Teuchos::rcp ( new Tpetra::Map<>((Tpetra::global_size_t) 100, indexBase, comm));`
`Teuchos::RCP<const Tpetra::Map<>> domain = Teuchos::rcp ( new Tpetra::Map<>((Tpetra::global_size_t) 47, indexBase, comm));`
`Teuchos::RCP<const Tpetra::Map<>> range  = Teuchos::rcp ( new Tpetra::Map<>((Tpetra::global_size_t) 67, indexBase, comm));`
`typedef Tpetra::CrsMatrix<double,int,int,Kokkos::Compat::KokkosOpenMPWrapperNode> matrix_type;`
`Teuchos::RCP<matrix_type> A (new matrix_type(row, col, 9));`
`Teuchos::RCP<Teuchos::ParameterList> parameters = Teuchos::parameterList();`
`A->fillComplete(domain,range,parameters);`
`std::string descript = A->description(); `
`std::cout << descript << std::endl;`

Produces the output 
`Tpetra::CrsMatrix (Kokkos refactor): {isFillComplete: true, global dimensions: [100, 47], global number of entries: 0}`

**Comment by cgcgcg** [comment]
The 4 maps work this way:
- (`rangemap`, `domainmap`) specify the distribution of vectors that can be multiplied from left and right. Every index lives on exactly one MPI rank.
- (`rowmap`, `colmap`) describe the distribution of the matrix entries. `rowmap` describes the row indices of the matrix, `colmap` the column indices. `rowmap` is generally (needs to be?) so that every index lives on one rank. `colmap`, on the other hand, can have repeated indices. This corresponds to a row-wise distribution of the matrix.

In your case you want (`rangemap`, `domainmap`) to be of sizes 47 and 67 respectively. `rowmap` should also be of size 47 and match `rangemap`. I would suggest to not specify `colmap` as Tpetra can figure that out for you once you call `fillComplete`. The number of entries in `colmap` is unrelated to the number of nonzeros in the matrix. It's a map of column indices that appear in the rows of the matrix.

Maybe have a look at https://docs.trilinos.org/latest-release/packages/tpetra/doc/html/index.html

**Comment by cgcgcg** [comment]
@aellery Please reopen if you have follow-up questions.
