### ISSUE TITLE
Create and publish an official Trilinos Change Management Policy

### ISSUE THREAD

**Issue by maherou** [trilinos/Trilinos#1233]
While the Trilinos project has a rigorous backward compatibility policy, other forms of change management are not well define.  This issue is for creating a more comprehensive statement of how  we manage changes.  The policy should cover these things (and probably more):
- [ ] How we inform users of commits to the repository that could change numerical results.
- [ ] When these kinds of changes can be pushed into the repository and how.
- [ ] As we start to introduce non-deterministic algorithms, how do we indicate when a function may produce results that vary from run to run.

cc: @trilinos/framework

**Comment by ibaned** [comment]
Indicating non-determinism is very important, I'd expect this to be at least indicated in a functions' Doxygen documentation. I'd also be interested to know whether the non-determinism arises due to:
 - using a random input stream or using the current time to make decisions
 - non-deterministic MPI-parallel algorithms
 - non-deterministic use of OpenMP
 - non-deterministic use of CUDA

The latter two can be combined into a single "Kokkos" category as appropriate. At some point @mhoemmen mentioned that the MPI standard allows non-deterministic reductions, so some distinction between theoretical and practical non-determinism may be important in this case (all MPI implementations I've worked with seem to use deterministic reductions).

**Comment by mhoemmen** [comment]
@ibaned wrote:
> At some point @mhoemmen mentioned that the MPI standard allows non-deterministic reductions . . . .

Even though MPI implementations might not exploit this, the general issue is relevant.  For example, Kokkos might decide to dispatch parallel_reduce straight to OpenMP (@nmhamster has discussed this as a way to help the compiler optimize), and OpenMP does not promise deterministic reductions.

**Comment by bartlettroscoe** [comment]
> While the Trilinos project has a rigorous backward compatibility policy

Actually, that policy has almost completely disintegrated in the last few years, especially since backward compatibility testing has not been run for many years now.  

If we are serious about backward compatibility (which always included both compile-time APIs and behavior), we need to implement the TriBITS lifecycle model in Triilnos (and provide support for it in the TriBITS system itself).   The plan for that (several years old now) is documented at:

* http://trac.trilinos.org/wiki/TribitsDevelopmentPractices#maturity_level_practices

and is graded based on the maturity of the packages or subpackage (i.e. lower maturity packages don't have to maintain any backward compatibility at all).

**Comment by nmhamster** [comment]
@mhoemmen @ibaned - its my understanding that the Intel OpenMP runtime can provide deterministic reductions if forced into that mode (using the `KMP_DETERMINISTIC_REDUCTION` environment variable). It opens the door for areas where we can directly use OpenMP reductions (assuming an OpenMP backend) to improve levels of vectorization and optimization. Also some of the MPI implementations will guarantee at some level of reproducibility between runs if forced into those kind of modes (may get slightly slower performance though).

**Comment by bartlettroscoe** [comment]
@maherou updated:

* https://github.com/trilinos/Trilinos/wiki/Trilinos-Support-Policy

to ask users to send email to the trilinos-help mail list and then @maherou will make sure that issues get created and passed on to how needs to address them.
