### ISSUE TITLE
Trilinos no longer finding Netcdf when Netcdf exists

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#12376]
The Albany nightlies started failing today due to Netcdf libs not being found even though they are there and are pointed to.  Here is how the error looks like: 

```
--   Searching for lib 'netcdf' ...
--     Found lib '/nightlyCDash/albany-tpls-gcc-11.1.1-openmpi-4.1.0/lib/libnetcdf.so'
-- Searching for a lib in the set "pnetcdf":
--   Searching for lib 'pnetcdf' ...
-- ERROR: Did not find a lib in the lib set "pnetcdf" for the TPL 'Netcdf'!
-- ERROR: Could not find the libraries for the TPL 'Netcdf'!
-- TIP: If the TPL 'Netcdf' is on your system then you can set:
     -DNetcdf_LIBRARY_DIRS='<dir0>;<dir1>;...'
   to point to the directories where these libraries may be found.
   Or, just set:
     -DTPL_Netcdf_LIBRARIES='<path-to-libs0>;<path-to-libs1>;...'
   to point to the full paths for the libraries which will
   bypass any search for libraries and these libraries will be used without
   question in the build.  (But this will result in a build-time error
   if not all of the necessary symbols are found.)
-- ERROR: Failed finding all of the parts of TPL 'Netcdf' (see above), Aborting!

-- TPL_Netcdf_PARALLEL is False
-- NOTE: The find module file for this failed TPL 'Netcdf' is:
     /nightlyAlbanyTests/Results/Trilinos/cmake/tribits/common_tpls/FindTPLNetcdf.cmake
   which is pointed to in the file:
     /nightlyAlbanyTests/Results/Trilinos/TPLsList.cmake

TIP: Even though the TPL 'Netcdf' was explicitly enabled in input,
it can be disabled with:
  -DTPL_ENABLE_Netcdf=OFF
which will disable it and will recursively disable all of the
downstream packages that have required dependencies on it.
When you reconfigure, just grep the cmake stdout for 'Netcdf'
and then follow the disables that occur as a result to see what impact
this TPL disable has on the configuration of Trilinos.

CMake Error at cmake/tribits/core/package_arch/TribitsProcessEnabledTpls.cmake:278 (message):
  ERROR: TPL_Netcdf_NOT_FOUND=TRUE, aborting!

```
The full output is attached.  If I pull the code with this sha, everything works: f90adc44e76bc0ff119900340dc5114a3061432f .   Am example configure script can be found here: https://github.com/sandialabs/Albany/blob/master/doc/nightlyTestHarness/camobap/do-cmake-trilinos-mpi-camobap .

I suspect the culprit is related to some of the Tribits changes by @sebrowne .

[trilinos_cmake_out.txt](https://github.com/trilinos/Trilinos/files/12836283/trilinos_cmake_out.txt)

**Comment by sebrowne** [comment]
@ikalash just to confirm, the "pnetcdf" library is available and at a path included in the TPL_NetCDF_LIBRARY_DIRS variable?  If not, this is actually good because it confirms that the new behavior is working.  This change got wrapped into a semi-related one because of CMakery, but this will be the new behavior going forwards (if any one TPL library is not found, fail the 'find' action, as opposed to now, where if at least one is found, pass it).

**Comment by sebrowne** [comment]
Including at @bartlettroscoe just to keep him in the loop.

**Comment by bartlettroscoe** [comment]
@ikalash, do you have the Trilinos configure out for when it last "worked"?  Is this posted to your CDash?  That would show is if it was finding the `pnetcdf` library before and not now.

**Comment by bartlettroscoe** [comment]
@sebrowne and @ikalash, the best solution going forward is likely to switch to calling `find_package(Netcdf)` and let it take care of these details.  In fact, that is already supported by setting `-D Netcdf_ALLOW_MODERN=TRUE` as you can see [here](https://github.com/trilinos/Trilinos/blob/develop/cmake/tribits/common_tpls/FindTPLNetcdf.cmake#L42) and [here](cmake/tribits/common_tpls/FindTPLHDF5.cmake).  But you have to have newer versions of HDF5 and NetCDF installed for that to work.

**Comment by ikalash** [comment]
Thanks everyone for all the suggestions/discussion.  It actually looks like the problem went away on its own mysteriously over the weekend.  I will go ahead and close.

**Comment by sebrowne** [comment]
@ikalash #12387 may reintroduce the issue, I think it may have gone away because the change was bundled with the one that caused the Zoltan missing library failure.

**Comment by ikalash** [comment]
@sebrowne : you were right that this got reintroduced.  I am confused about something.  Why is Trilinos looking for pnetcdf when I am telling it to turn off PNetcdf and Netcdf_PARALLEL: 

```
  -D TPL_ENABLE_PNetCDF:BOOL=OFF \
   -D TPL_Netcdf_PARALLEL:BOOL=OFF \
```

```
Processing enabled external package/TPL: Netcdf (enabled explicitly, disable with -DTPL_ENABLE_Netcdf=OFF)
-- Netcdf_LIBRARY_NAMES='netcdf;pnetcdf'
-- Must find at least one lib in each of the lib sets "netcdf;pnetcdf"
-- Searching for libs in Netcdf_LIBRARY_DIRS='/nightlyCDash/albany-tpls-gcc-11.1.1-openmpi-4.1.0/lib'
-- Searching for a lib in the set "netcdf":
--   Searching for lib 'netcdf' ...
--     Found lib '/nightlyCDash/albany-tpls-gcc-11.1.1-openmpi-4.1.0/lib/libnetcdf.so'
-- Searching for a lib in the set "pnetcdf":
--   Searching for lib 'pnetcdf' ...
-- ERROR: Did not find a lib in the lib set "pnetcdf" for the TPL 'Netcdf'!
-- ERROR: Could not find the libraries for the TPL 'Netcdf'!
-- TIP: If the TPL 'Netcdf' is on your system then you can set:
     -DNetcdf_LIBRARY_DIRS='<dir0>;<dir1>;...'
   to point to the directories where these libraries may be found.
   Or, just set:
     -DTPL_Netcdf_LIBRARIES='<path-to-libs0>;<path-to-libs1>;...'
```
Indeed the problem is that I don't have pnetcdf on one of the testing platforms, but I don't think it was needed before.

**Comment by ikalash** [comment]
As expected, installing pnetcdf resolved the issue.  I think the underlying question is whether pnetcdf is required now when building Trilinos with netcdf turned on, and whether 
```
 -D TPL_ENABLE_PNetCDF:BOOL=OFF \
   -D TPL_Netcdf_PARALLEL:BOOL=OFF \
```
is supposed to enable you to build w/o pnetcdf.  Currently the code seems to expect pnetcdf regardless or whether the above flags are set.

**Comment by gsjaardema** [comment]
If not using parallel then you should not need pnetcdf.

**Comment by ikalash** [comment]
@gsjaardema : this is what I would expect and how it used to work, but it looks like the code fails to configure now regardless of whether the parallel flag is set if the pnetcdf library is missing.

**Comment by bartlettroscoe** [comment]
> As expected, installing pnetcdf resolved the issue. I think the underlying question is whether pnetcdf is required now when building Trilinos with netcdf turned on, and whether
> 
> ```
>  -D TPL_ENABLE_PNetCDF:BOOL=OFF \
>    -D TPL_Netcdf_PARALLEL:BOOL=OFF \
> ```
> 
> is supposed to enable you to build w/o pnetcdf. Currently the code seems to expect pnetcdf regardless or whether the above flags are set.

@ikalash, the other solution would have been to override what libraries are being looked for by setting:

```
-D Netcdf_LIBRARY_NAMES=netcdf
```

(see documentation [here](https://docs.trilinos.org/files/TrilinosBuildReference.html#specifying-the-location-of-the-parts-of-an-enabled-external-package-tpl)).

Now, why are there two separate TriBITS/Trilinos TPLs "Netcdf" and "Pnetcdf"  that appear to have no relation to each other and where, at some point, the "Netcdf" TPL was updated to also look for the library `pnetcdf` when MPI is enabled as you can see that in:

https://github.com/trilinos/Trilinos/blob/dbca2e956356e722eec2766593c8dd3037bd6056/cmake/tribits/common_tpls/FindTPLNetcdf.cmake#L73-L75

?

Yes, that file is in TriBITS now, but that is not where it started out (it started out in Trilinos as can be seen below).

I don't remember being  involved in adding these two TPLs but you can see what happened by looking at the Git history.  Below is the best I can piece together from looking at the Git history.

It looks like the TriBITS/Trilinos "Netcdf" TPL was defined first by @gsjaardema in Trilinos commit  a93c14ae3cc922d706ce75086eb9eec06496dd55 in Jun 2010 and initially was just set up to find just the library `netcdf`.

Then later, the (apparently unrelated) TriBITS/Trilinos "Pnetcdf" TPL was added by @bmpersc in the Trilinos commit 9473e0c872f5c0b0fde42d807b863ca3fbe7de8c in Oct 2011 and was set up to find the library `pnetcdf` (but that file actually started out in the "trios" package which has since been removed from Trilinos but was added initially by Ron Oldfield in commit 0d309d6476b634e23ba1e417bc8c480d5b0f5272 in Sept 2011).

At some point, parallel support for the "Netcdf" TPL was added by adding the library `pnetcdf`.  It looks like the `pnetcdf` library was added the the "Netcdf" TPL when MPI is enabled in the commit 09e765db0adccbbc146cf777ec3d5d4bfb1f748b in April 2020.

With the updated TriBITS TPL system that properly tracks TPL dependencies, should we could fix this to have the "Netcdf" TPL depend on the "Pnetcdf" TPL?  But this will break backward compatibility which will impact a lot of developers and users.  But with newer versions of Netcdf now supporting installed `netCDFConfig.cmake` files, how is Pnetcdf handled there?

The TPL support in Trilinos is really hard to address because about any change breaks people's existing configure scripts.  But at some point, all of this should be cleaned up and we will need to help developers and users adjust.  But this will be a long, incremental process with lots of pain along the way (and this one GitHub issue is just the tip of the iceberg)☹️

**Comment by gsjaardema** [comment]
> Now, why are there two separate TriBITS/Trilinos TPLs "Netcdf" and "Pnetcdf" that appear to have no relation to each other and where, at some point, the "Netcdf" TPL was updated to also look for the library pnetcdf when MPI is enabled as you can see that in:

The `PnetCDF` library is used by the parallel build of `NetCDF` to provide some parallel I/O capability for reading/writing.  It is a separate library, but it is used by netCDF.

**Comment by bartlettroscoe** [comment]
> > Now, why are there two separate TriBITS/Trilinos TPLs "Netcdf" and "Pnetcdf" that appear to have no relation to each other and where, at some point, the "Netcdf" TPL was updated to also look for the library pnetcdf when MPI is enabled as you can see that in:
> 
> The `PnetCDF` library is used by the parallel build of `NetCDF` to provide some parallel I/O capability for reading/writing. It is a separate library, but it is used by netCDF.

@gsjaardema, the relationship between the `netcdf` and `pnetcdf` library files themselves is clear.  Instead, I was referring to the  relationship (or lack of) between the two TriBITS/Trilinos TPLs "Netcdf" and "Pnetcdf".   It would seem logical that the "Netcdf" TPL should depend on the "Pnetcdf" TPL but that is not how it is currently set up.  Currently, the "Netcdf" TPL just directly pulls in the `pnetcdf` library and ignores the existence of the "Pnetcdf" TPL.  The problem is that @ikalash logically assumed that if she disabled the "Pnetcdf" TPL using `-D TPL_ENABLE_Pnetcdf=OFF`, there there should be no search for the `pnetcdf` library.  That is the problem here as I see it.  It is just confusing to users that enabling or disabling the "Pnetcdf" TPL has no impact on the search for the `pnetcdf` library or on the "Netcdf" TPL at all.

NOTE: With the updated TriBITS system now able to define TPL dependencies (see [here](https://tribitspub.github.io/TriBITS/users_guide/index.html#tpldefsdir-findtpl-tplname-dependencies-cmake)), we could make it so that the "Netcdf" TPL requires the "Pnetcdf" TPL and enables it automatically when MPI is enabled.  (That would require an extension to the TriBITS TPL system but it would not be hard to do.)  But that change would break backwards compatibility and break many people's existing configure scripts.  But at some point, we are going to have to break their configure scripts anyway when more external packages install modern CMake `<Package>Config.cmake` files and we move their `FindTPL<Package>.cmake` file over as described in:

* https://tribitspub.github.io/TriBITS/users_guide/index.html#creating-findtpl-tplname-cmake-using-find-package-with-imported-targets

Does that make sense?

**Comment by gsjaardema** [comment]
@bartlettroscoe The netcdf package used to (i thought) check whether it needed/depended on pnetcdf and then only added it as a dependency if that was the case:
```
            # If --has-pnetcdf returns true, then add pnetcdf as dependent library.
            execute_process(COMMAND sh -c "${netcdf_config} --has-pnetcdf"
                            RESULT_VARIABLE _ret_code
                            OUTPUT_VARIABLE _stdout
                            ERROR_VARIABLE  _stderr
                           )
            string(REGEX MATCH "yes|no" _pnetcdf_answer ${_stdout})
            message(STATUS "${netcdf_config} --has-pnetcdf returned '${_pnetcdf_answer}'")
            string(COMPARE EQUAL "${_pnetcdf_answer}" "yes" _has_pnetcdf)
            if (${_has_pnetcdf} )
                set(NetCDF_NEEDS_PNetCDF True)
            else()
                set(NetCDF_NEEDS_PNetCDF False)
            endif()
```
I might be talking about a different file than you, this is `../cmake/tribits/common_tpls/find_modules/FindNetCDF.cmake`
