### ISSUE TITLE
Zoltan: missing target when building Albany

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#12371]
It seems that we are seeing an error related to a missing target in Zoltan when building Albany: 

```
Call Stack (most recent call first):
  /projects/albany/nightlyCDash/build/TrilinosSerialInstall/lib64/cmake/TrilinosSS/TrilinosSSConfig.cmake:133 (include)
  /projects/albany/nightlyCDash/build/TrilinosSerialInstall/lib64/cmake/Amesos/AmesosConfig.cmake:161 (include)
  /projects/albany/nightlyCDash/build/TrilinosSerialInstall/lib64/cmake/Stratimikos/StratimikosConfig.cmake:148 (include)
  /projects/albany/nightlyCDash/build/TrilinosSerialInstall/lib64/cmake/Piro/PiroConfig.cmake:148 (include)
  /projects/albany/nightlyCDash/build/TrilinosSerialInstall/lib64/cmake/Trilinos/TrilinosConfig.cmake:123 (include)
  CMakeLists.txt:81 (find_package)


CMake Error at /projects/albany/nightlyCDash/build/TrilinosSerialInstall/lib64/cmake/Zoltan/ZoltanTargets.cmake:61 (set_target_properties):
  The link interface of target "Zoltan::zoltan" contains:

    Zoltan::m

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```
https://sems-cdash-son.sandia.gov/cdash/build/52980/configure

Can someone please look into this?

@trilinos/zoltan

**Comment by cgcgcg** [comment]
@bartlettroscoe Do you understand why that could be happening?

**Comment by bartlettroscoe** [comment]
Yea, it is most certainly caused by:

* #12362

The CMake documentation for [LINK_LIBRARIES_ONLY_TARGETS](https://cmake.org/cmake/help/latest/prop_tgt/LINK_LIBRARIES_ONLY_TARGETS.html#prop_tgt:LINK_LIBRARIES_ONLY_TARGETS) did not mention that issue (but I should have realized this would happen).

@sebrowne, we should revert that PR ASASP and come up with a different solution.  (And that solution will likely be a "MLib" TPL that will generate the correct targets for the installed `<Package>Config.cmake` files and new TriBITS already supports that use case so this will be very little CMake code.)

**Comment by bartlettroscoe** [comment]
PR:

* #12371

reverts the change.  Someone just needs to approve that PR and it needs to get rough PR testing.

**Comment by ikalash** [comment]
Thanks!  I can reviews if you add me as a reviewer.

**Comment by ikalash** [comment]
It looks like this has been resolved through the revert.  Do you want me to keep this issue open, since I presume a different workaround from the revert is desired, or should I close it?

**Comment by bartlettroscoe** [comment]
@ikalash, this was a mistake that got through Trilinos testing.  It was reverted in:

* https://github.com/trilinos/Trilinos/pull/12372

I will converse with @sebrowne on how to address this property.

**Comment by ikalash** [comment]
Ok I will close in this case.
