### ISSUE TITLE
checkin script question

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#1241]
@bartlettroscoe I've noticed recently that when I run the checkin script, many upstream packages get rebuilt, even if there are no new changes pulled into those packages.  I seem to recall that at one point, rebuilding during checkin was quite a bit faster because there was less recompilation of unchanged packages.  For example, my last checkin run pulled in changed to panzer, rol, and minitensor, and I made changes to xpetra. And yet zoltan, ifpack, ml, and amesos are all gettting rebuilt.

**Comment by dridzal** [comment]
MueLu gets rebuilt every time I run make after changing a CMakeLists file in ROL, even if I haven't pulled from the repo.

**Comment by bartlettroscoe** [comment]
My guess is that this has nothing to do with the checkin-test.py script.  My guess is that this is caused by some Trilinos package (or packages) are updating some config.h file or something which is triggering a bunch of downstream files to get rebuilt.  If someone has the time, we can use ninja to diagnose what is triggering these rebuilds (you can't really do that sometimes with the generated makefiles).

If you give me a concrete use case with all info to be 100% reproducable, then I can take some time to look into this.  Usually it is not that hard to diagnose (but fixing it can be a different story depending on how bad this is).

**Comment by bartlettroscoe** [comment]
People like @rppawlo have reported the same thing and we discussed this at the "Improving stability of Trilinos" meeting on 5/31/2017.

I created the new Issue #1386 to address the underlying cause of this.   Therefore, unless someone can provide some evidence that the checkin-test.py script itself is causing this, I think we need to close this.

I am putting this in review.  @jhux2, can you please close now that #1386 is created?  (It should be the policy that the person who created an issue or is the customer of the issue should close issues.  That way we can be sure that the customer is satisfied.)

CC: @trilinos/framework, @maherou

**Comment by jhux2** [comment]
> I am putting this in review. @jhux2, can you please close now that #1386 is created? (It should be the policy that the person who created an issue or is the customer of the issue should close issues. That way we can be sure that the customer is satisfied.)

Closing.  This will be investigated in #1386.
