### ISSUE TITLE
Nalu Fails: STK SkinBoundary change in behavior

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#12531]
@alanw0, it looks like some changes to skin-mesh were pushed yesterday as I am now noting fails in our unit tests.

```
Error: Cannot use create_all_sides while in another mod cycle.
" thrown in the test body.
[  FAILED  ] KokkosME.test_hex8_views (0 ms)
[ RUN      ] KokkosME.test_tet4_views
unknown file: Failure
C++ exception with description "Requirement( bulkData.in_synchronized_state() ) FAILED
Error occurred at: stk_mesh/stk_mesh/base/SkinBoundary.cpp:88
```

My guess this is simple, however, I wanted to check to make sure that this was desired behavior change.

Good:

```
NaluCFD/Nalu SHA1: eacfcdc402cea5fe8394240c3982c23917f64f9c
Trilinos/develop SHA1: bc2bd582d0f56372a9a35725d779de8fbdcc4365

```
Bad:

```
NaluCFD/Nalu SHA1: eacfcdc402cea5fe8394240c3982c23917f64f9c
Trilinos/develop SHA1: 90789eb72f38c644737aaf689eb05b5311c7676e
```

**Comment by alanw0** [comment]
Stefan! Ugh, this is indeed a "on-purpose" behavior change, I had forgotten that we had done this since the last stk-trilinos snapshot. This was done to address a ticket from a sierra user...
The summary is: stk functions that contain a mod-cycle, (BulkData::modification_begin .. BulkData::modification_end) shouldn't silently allow being called within an "outer" mod-cycle because that opens up not-well-defined error possibilities, and prevents some internal optimization possibilities.
So some stk functions (notably these skinning functions) are now beginning to enforce the requirement that mod-cycles should not be nested.
So the solution (hopefully simple and easy) is to close the "outer" mod-cycle in the calling code by calling BulkData::modification_end().

**Comment by spdomin** [comment]
Okay, I will pursue that path. Really, a skinning effort can be something done at the first step of any unit test in its own mod-based cycle. I am not sure why this was not done already in the unit tests to follow what Nalu does during initialization. For instance, we have a call to:

`stk::mesh::create_exposed_block_boundary_sides(*bulkData_, activePart, partVec);`

in a rather safe location during start-up.

**Comment by alanw0** [comment]
Hmm, so unit tests were accidentally depending on the nested-mod-cycle behavior. Probably my fault... or Shreyas, I can blame him since he was also writing unit-tests in there... :-)
But more seriously, there is a "law" that any observable behavior of a software function, if left in place long enough, will be depended on by calling code.
On the stk side we have a "policy" for deprecating public APIs, but it is more subtle/difficult to deprecate behavior that shouldn't have been in there in the first place.
Sorry for the disruption!

**Comment by spdomin** [comment]
Wait, nested mod cycles was never "allowed"? I certainly never coded one, however, good to know.

I will have this cleaned up shortly.

**Comment by alanw0** [comment]
Well, nested mod cycles are allowed in the sense that they aren't prohibited/prevented in general. You can call BulkData::modification_begin as many times as you want. But BulkData::modification_end knows nothing of nesting, and it will close the mod-cycle no matter how many times mod-begin has been called.
But nested mod cycles are certainly not recommended.

**Comment by spdomin** [comment]
I am trying to find where the nesting is... Is there a chance you have an STK method that is nesting?

**Comment by alanw0** [comment]
Looks like you got a fix, great.

**Comment by spdomin** [comment]
Yes, I love one line changes that fix hundreds of tests.

When the suite runs successfully tomorrow, I will close the ticket. Thanks.

**Comment by spdomin** [comment]
Strange... I wonder if the work "resolves" automatically closes the ticket? Well, if the tests fail tomorrow, I will re-open.

**Comment by alanw0** [comment]
> Strange... I wonder if the word "resolves" automatically closes the ticket? Well, if the tests fail tomorrow, I will re-open.

Interesting, I didn't know that either.
