### ISSUE TITLE
Framework: links to subprojects on dashboard are incorrect

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#1270]
@trilinos/framework 

At the top of the MueLu testing [page](http://testing.sandia.gov/cdash/index.php?project=Trilinos&subproject=MueLu) are links to Subproject Dependencies.  Those links have the form http://testing.sandia.gov/cdash/index.php?subproject=<some_package>&, but clicking on any of those links redirects to http://testing.sandia.gov/cdash/viewProjects.php.

I believe the correct form of those links should be http://testing.sandia.gov/cdash/index.php?project=Trilinos&subproject=<some_package>.

**Comment by bartlettroscoe** [comment]
Hopefully this will be fixed in the next upgrade of CDash (testing for which should begin soon).  We need to add this test case to our manual acceptance testing process (yet to be officially drafted)

**Comment by bartlettroscoe** [comment]
It looks like this defect still exists even with the latest CDash 3.0.3 release as you can see [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&subproject=MueLu).  This was not a feature that any of our prior Kitware contracts paid for and I have never used this in the 12+ years I have been using CDash.   When I want to look at results on a subproject-by-subproject (i.e. package-by-package) basis, I use:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=1&showfilters=1&field1=subprojects&compare1=93&value1=MueLu

which is more flexible (since it can include more than one subproject) and does not include that "SubProject Dependencies" list at the top.

@jhux2, to get this on Kitware's radar you might try to post an issue to https://github.com/Kitware/CDash/issues.  You can see [here](https://github.com/Kitware/CDash/issues?q=is%3Aissue+is%3Aopen++subproject) that there are not many issues filed that contain "subproject".

Otherwise, this is not a Trilinos issue per say so I think this could be closed.

**Comment by jhux2** [comment]
> Otherwise, this is not a Trilinos issue per say so I think this could be closed.

@bartlettroscoe I've opened an issue on the Kitware github, closing this one.
