### ISSUE TITLE
Trilinos config problem in FiniteValue.cmake and GCC 5.4.0

### ISSUE THREAD

**Issue by raovgarimella** [trilinos/Trilinos#1272]
Trilinos 12.6.1 and 12.10.1 configuration fails with gcc 5.4.0 and cmake 3.5.1 because of an issue with trilinos/cmake/tribits/core/config_tests/FiniteValue.cmake. The complaint is that "```isnan  was not declared in this scope```". 

Upon investigating further, it seems that FiniteValue.cmake tries to test for existence of '```isnan```' within the global namespace and the ```std::``` namespace but in both cases uses the ```<cmath>``` header.

According to the following post on StackOverflow, it seems however that one should include ```<math.h>``` when calling '```isnan```' and ```<cmath>``` when calling  '```std::isnan```'

http://stackoverflow.com/questions/18128899/is-isnan-in-the-std-namespace-more-in-general-when-is-std-necessary-optio

Making this change allows the configuration to proceed. I checked and this problem persists in the HEAD version of the master as well.

Here is a trivial patch file for fixing the problem in 12.10.1 release

```
--- cmake/tribits/core/config_tests/FiniteValue.cmake   2016-11-22 15:43:07.000000000 -0700
+++ cmake/tribits/core/config_tests/FiniteValue.cmake.new       2017-04-26 22:27:08.016402800 -0600
@@ -58,7 +58,7 @@ INCLUDE(CheckCXXSourceCompiles)

 SET(SOURCE_GLOBAL_ISNAN
   "
-#include <cmath>
+#include <math.h>
 int main()
 {
   double x = 1.0;
@@ -105,7 +105,7 @@ ENDIF()

 SET(SOURCE_GLOBAL_ISINF
   "
-#include <cmath>
+#include <math.h>
 int main()
 {
   double x = 1.0;
```

**Comment by mhoemmen** [comment]
@trilinos/framework

**Comment by bartlettroscoe** [comment]
Okay, this does look like the right change to make for this configure-time test.  However, does fixing this configure-time test also fix the build for this compiler on the platform?  @raovgarimella, can you confirm that it does?  Also, I think you can fix the configure by setting `-D FINITE_VALUE_HAVE_GLOBAL_ISNAN=[ON|OFF]` etc. to bypass the configure-time check as needed for that compiler so that you don't need to modify Trilinos source code to make it do the right thing (assuming the build works).  If you can confirm that you can overriding `FINITE_VALUE_HAVE_GLOBAL_ISINF`, `FINITE_VALUE_HAVE_STD_ISINF`, `FINITE_VALUE_HAVE_GLOBAL_ISNAN`, and/or `FINITE_VALUE_HAVE_STD_ISNAN` fixes your configure and build, then that would be good to know and would reduce the need to patch older releases of Trilinos.

Now some background on this ...

Given the policies about mixing C and C++ headers for Trilinos for many years as documented at:

* https://software.sandia.gov//trilinos/developer/policies/namespace_safety.html

which states:

> 3. Only include the C++ version of standard C headers <cX> and never the C version <X.h>. For example, only include <cstdlib> in C++ code and never include <stdlib.h>. Significant portability problems occur on some platforms when you mix the standard C++ and the standard C versions of the same headers; don't do it!
>
> 4. Use full std:: qualification for every symbol from the standard C++ library in all Trilinos header files.

it is not good for Trilinos code to be including both `<cmath>` and now `<math.h>`.   But given the unfortunate nature of `isnan()` and `isinf()` with C++98/03, C99, and C++11, I don't see a way around this.
 
It looks like the macros defined by these configure-time tests are only used in one place in Trilinos:

```
$ find packages/ -type f -exec grep -nH FINITE_VALUE_HAVE.*IS.* {} \;
packages/nox/cmake/NOX_Config.h.in:8:#cmakedefine FINITE_VALUE_HAVE_GLOBAL_ISINF
packages/nox/cmake/NOX_Config.h.in:9:#cmakedefine FINITE_VALUE_HAVE_STD_ISINF
packages/nox/cmake/NOX_Config.h.in:10:#cmakedefine FINITE_VALUE_HAVE_GLOBAL_ISNAN
packages/nox/cmake/NOX_Config.h.in:11:#cmakedefine FINITE_VALUE_HAVE_STD_ISNAN
packages/nox/src/NOX_StatusTest_FiniteValue.C:171:#elif defined(FINITE_VALUE_HAVE_STD_ISNAN)
packages/nox/src/NOX_StatusTest_FiniteValue.C:173:#elif defined(FINITE_VALUE_HAVE_GLOBAL_ISNAN)
packages/nox/src/NOX_StatusTest_FiniteValue.C:187:#elif defined(FINITE_VALUE_HAVE_STD_ISINF)
packages/nox/src/NOX_StatusTest_FiniteValue.C:189:#elif defined(FINITE_VALUE_HAVE_GLOBAL_ISINF)
```

That was added to NOX way back in in 2009 in the commits:

```
commit 9158ecd8f6118a2980324910d62725bf5f1e71bb
Author: Roger P. Pawlowski <rppawlo@sandia.gov>
Date:   Fri Jan 9 23:05:26 2009 +0000

         SUMMARY:
    
    Adding cmake support to nox.  Not fully functional yet.
    
    1. Supported: src, src-epetra, src-thyra
    2. NOT supported yet: loca, src-petsc, src-belos.
    
    Only 14 tests are up and running - still have a long way to go. I am checking this in so that packages that require nox can now start the cmakeification process.  I'll finish l
    
    
    (checklist version 2007-06-20)

A       packages/nox/cmake/NOX_Config.h.in
M       packages/nox/src/NOX_StatusTest_FiniteValue.C

commit 39d17168149c2c8c579d56c6cda7895260aaddf9
Author: Roger P. Pawlowski <rppawlo@sandia.gov>
Date:   Fri Jan 9 22:58:13 2009 +0000

         SUMMARY:
    
    Changes to top level cmake system to support nox:
    
    1. Added a finite value support configure check to the top level cmake builds.
    2. Added FindDoxygen to locate the "dot" library so that cmake can set the Doxygen HAVE_DOT command in Doxyfiles to the correct value in the Doxyfiles.
    3. Minor tweaks to AddOptionAndDefine.cmake to handle values better.
    
    
    (checklist version 2007-06-20)

A       cmake/config_tests/FiniteValue.cmake
```

Given that NOX needs to continue to work with C++98/03 (at least for now) and `std::isnan()` and `std::isinf()` are only guaranteed to be supplied by C++11 (or by C++98/03 compiliers that implement the C99 standard), then I guess there is not much we can do to get rid of this code right now.

@rppawlo (that author of this configure test and code), do you agree with that assessment?  Given that this configure-time test is only used in NOX, would you be apposed to moving this configure-time test to Trilinos/packages/nox/cmake/ and removing it from TriBITS?  This allows TriBITS to shrink and not loose any general functionality (which is always good).

Once Trilinos can mandate C++11, then this configure-time test can be deleted and NOX (and the rest of Trilinos) can just use `std::isnan()` and `std::isinf()`.

**Comment by bartlettroscoe** [comment]
@mhoemmen

> NOX could depend optionally on C++11, just like TeuchosCore does.

Yes, but that does not negate the need for a configure-time check since this needs to check for the C99 functions in the global namepsace as well.

**Comment by rppawlo** [comment]
It's fine to make that change. In fact I think we could remove the check altogether and just use the std::isnan implementation. The particular check was for an old platform that should not be around anymore.

If you want the history - this was actually an issue back in the 2006 time frame. One of the main Xyce test platforms was an old OpenBSD machine with bad compilers. std::isnan from <cmath> and the global isnan from <math.h> would hang at runtime. The fallback that relied on IEEE 748 compliance also failed on that machine. The only thing that worked was to remove all the includes and we would find isnan from the system headers which actually worked. So the first check without math.h was to try to find in system headers and second check was for c++ compliant version. What fun times!  

Anyway this shouldn't be a problem now as this machine was very old in 2006. We could probably remove the check completely and use <cmath> reliably since Trilinos now requires gnu4.7 compilers at a minimum.

**Comment by bartlettroscoe** [comment]
@rppawlo,

> Anyway this shouldn't be a problem now as this machine was very old in 2006. We could probably remove the check completely and use reliably since Trilinos now requires gnu4.7 compilers at a minimum.

Actually, Trilinos still needs to support GCC 4.4.7 for the non-C++11 software in Trilinos which is still used by Xyce.  I guess if we can get this code to work with GCC 4.4.7 with C++11 disabled and with GCC 4.7.2 with C++11 enabled, then I think we can remove this configure-time check.

@raovgarimella,

Can you confirm if the patch shown above results in a correct build of NOX and a successful pass of all of its unit tests?  It looks like I have access to a machine with GCC 5.3.0 and 6.1.0 but not 5.4.0.   Therefore, we could manually test one of these.

However, note that Trilinos does not have any automated builds for GCC compilers more recent than GCC 5.2.0 as shown by:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-04-27

Therefore, in general, we would have no way to maintain working builds on GCC 5.4.0.  In general, Trilinos can't support updated versions of compilers for which we have no automated builds.

**Comment by raovgarimella** [comment]
This error occurred in Trilinos build triggered through a TPL build in another software (https://github.com/lanl/jali.git). I tried my best to reproduce the problem through a standalone build but I could not. 

Still, I applied the patch to the master, configured and built and ran ```make test``` and all tests passed.

The configure command I used was

```
/usr/bin/cmake \
    -DCMAKE_C_COMPILER=`which mpicc` \
    -DCMAKE_CXX_COMPILER=`which mpiCC` \
    -DCMAKE_Fortran_COMPILER=`which mpif90` \
    -DCMAKE_CXX_FLAGS="-std=c++11" \
    -DCMAKE_BUILD_TYPE:STRING=Release \
    -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
    -DTrilinos_ENABLE_Epetra:BOOL=ON \
    -DTrilinos_ENABLE_NOX:BOOL=ON \
    -DTrilinos_ENABLE_AztecOO:BOOL=ON \
    -DTrilinos_ENABLE_Zoltan:BOOL=ON \
    -DTrilinos_ENABLE_Stratimikos:BOOL=OFF \
    -DTPL_ENABLE_MPI:BOOL=ON \
    -DMPI_EXEC:STRING="/usr/bin/mpiexec" \
    -DMPI_EXEC_NUMPROCS_FLAG:STRING="-np" \
    -DTPL_ENABLE_Boost:BOOL=ON \
    -DTPL_Boost_INCLUDE_DIRS:FILEPATH=/home/rao/packages/jali-tpl/include \
    -DTPL_Boost_LIBRARY_DIRS:FILEPATH=/home/rao/packages/jali-tpl/lib \
    -DTPL_ENABLE_Netcdf:BOOL=ON \
    -DTPL_Netcdf_INCLUDE_DIRS:FILEPATH=/home/rao/packages/jali-tpl/include \
    -DTPL_Netcdf_LIBRARIES:STRING="/home/rao/packages/jali-tpl/lib/libnetcdf.a;/home/rao/packages/jali-tpl/lib/libhdf5_hl.a;/home/rao/packages/jali-tpl/lib/libhdf5.a;/home/rao/packages/jali-tpl/lib/libz.a;m" \
    -DTrilinos_VERBOSE_CONFIGURE:BOOL=ON \
    -DTrilinos_ENABLE_TESTS:BOOL=OFF \
    -DTrilinos_ENABLE_Gtest:BOOL=OFF \
    ..
```

**Comment by raovgarimella** [comment]
The build was on an Ubuntu 16.04 system

**Comment by bartlettroscoe** [comment]
With Trilinos having been updated to use C++11, I suspect this issue was likely fixed years ago.

**Comment by william76** [comment]
> With Trilinos having been updated to use C++11, I suspect this issue was likely fixed years ago.

FYI @bartlettroscoe @mhoemmen by commenting on this issue you told the bot that you'd like to reset the counter to another year of keeping this issue open.  If you're ok with the issue being closed out then please refrain from making any activity on the issue, or you can also close it out and free up a slot for the autocloser.

I'm going to go ahead and close this because issues that were given activity to confirm that the bot can close them out kind of messes with the bot's ability to get through the backlog of abandoned issues.
