### ISSUE TITLE
Error compiling Trilinos/Kokkos example

### ISSUE THREAD

**Issue by GVE871** [trilinos/Trilinos#12850]
## Question
I am trying to compile the  [example 1](https://github.com/trilinos/Trilinos_tutorial/wiki/KokkosExample01) from the Trilinos [hands on tutorial](https://github.com/trilinos/Trilinos_tutorial/wiki/TrilinosHandsOnTutorial). But trying to `make` the example, this is what I get  

```
c++: error: unrecognized command line option ‘-Wext-lambda-captures-this’
c++: error: unrecognized command line option ‘-arch=sm_61’
make[2]: *** [KokkosTpetra/CMakeFiles/EuroTUG_01_init.dir/build.make:76: KokkosTpetra/CMakeFiles/EuroTUG_01_init.dir/01_init.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:98: KokkosTpetra/CMakeFiles/EuroTUG_01_init.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
```

**Comment by ccober6** [comment]
@trilinos/kokkos

**Comment by jhux2** [comment]
@GVE871 What are you interested in learning?   The tutorial you're trying to run is quite old, and I'm unsurprised it doesn't compile correctly.  I'd suggest looking at the Kokkos tutorials https://github.com/kokkos/kokkos-tutorials.  Otherwise Tpetra itself has some hands-on examples:  https://github.com/trilinos/Trilinos/tree/master/packages/tpetra/core/example.
