### ISSUE TITLE
Piro: pointless #ifdef ALBANY_BUILD?

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#1295]
The ifdefs appear pointless to me (besides mentioning downstream software in trilinos, which appears conceptually wrong, and can open the door to potentially several similar ifdefs down the road).

In particular, when ALBANY_BUILD is defined, some classes (lsuch as Piro_TempusSolver) accept template arguments for LO/GO/Node, and some default values are provided. When ALBANY_BUILD is not defined, no LO/GO/Node types can be passed to Piro classes, and Tpetra::CrsMatrix and enableMueLu are called without LO/GO/Node arguments; however, the default values that Tpetra::CrsMatrix and enableMueLu use are exactly the same default values that Piro uses when ALBANY_BUILD is defined. In other words, there is no practical difference between the two cases, since the user can in both cases instantiate classes passing only the scalar type, and the same default template arguments will be used by tpetra and muelu.

**Comment by lxmota** [comment]
Pinging @ikalash to see if she knows anything about this, as she has been working in Tempus recently.

**Comment by ikalash** [comment]
I agree that this seems irrelevant at this point. My Piro::TempusSolver code is based on what was done in Piro_RythmosSolver_Def.hpp at the end of 2015, it looks like by @gahansen:  
 
4eae9463 packages/piro/src/Piro_RythmosSolver_Def.hpp             (Glen Hansen           2015-12-21 22:20:00 -0700   94) #ifdef ALBANY_BUILD

I presume this was needed at some point due to different template arguments, but I agree that it does not seem needed anymore.  @gahansen , perhaps you can comment on why you put this in?
