### ISSUE TITLE
Framework:  AT is down

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#13027]
## Bug Report

There are a few PR's that are blocked from merging due to reported failures, but nothing shows up on the dashboard:

#13019 
#13014 

@trilinos/framework

**Comment by cgcgcg** [comment]
Could someone from @trilinos/framework acknowledge that there is an issue? Thanks!

**Comment by achauphan** [comment]
The AutoTester should now be running as the rhel8 upgrade hit us with two issues:

1. rhel8 upgrade on our GPU machines had the Java path previously used in their Jenkin's configurations changed unexpectedly.
2. GenConfig and how it uses the SEMS modules in our PR scripts were NOT prepared for the rhel8 upgrade. Specifically, he config `rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables` attempts to load the SEMS module `sems-openmpi/4.0.5-cuda-11.4.2` which no longer exists since CUDA is now built into the module `openmpi/4.0.5` in this new version of SEMS modules, so the configuration had issues finding that.

The second issue currently has a temporary fix in-place so that the AutoTester can actually run as the real fix is still being worked on and requires changes to the PR scripts that are in this repo (which would require AutoTester to pass to be implemented).

While the AutoTester should be working today, I will update this further when the desired fixed in place for that second issue.

**Comment by jhux2** [comment]
Thanks for the update, @achauphan.

**Comment by achauphan** [comment]
> @achauphan @sebrowne This doesn't look good #13032

Responded in this [comment](https://github.com/trilinos/Trilinos/pull/13032#issuecomment-2127624972)

**Comment by jhux2** [comment]
@achauphan Some PRs have merged, but there are others, e.g., #13017, where there are no obvious failure reports (except for the new non-blocking PR test), but the AT reports that tests failed.

**Comment by jhux2** [comment]
fixed
