### ISSUE TITLE
MueLu:  No PostSmoother warning printed out every iteration

### ISSUE THREAD

**Issue by rstumin** [trilinos/Trilinos#1382]
When a PostSmoother is not used (i.e. set to NoSmoother), a warning is printed out for each iteration
(see below). I believe that this also prints out on multiple levels. It would be nice if this just printed out once and not for every iteration.

...

******* WARNING *******
Level 0: No PostSmoother!
Iter  42, [ 1] :    2.209041e-03

******* WARNING *******
Level 0: No PostSmoother!
Iter  43, [ 1] :    1.991614e-03

******* WARNING *******
Level 0: No PostSmoother!
Iter  44, [ 1] :    1.771778e-03

******* WARNING *******
Level 0: No PostSmoother!
Iter  45, [ 1] :    1.586263e-03

******* WARNING *******
Level 0: No PostSmoother!
Iter  46, [ 1] :    1.418797e-03

**Comment by aprokop** [comment]
@trilinos/muelu 

@rstumin Probably doable, but a bit hacky. We could pass a parameter to `Iterate()` that would disable printing those after the first iteration. This would require adjusting API, and adding a couple lines of code in the adapters. Not the best approach, as this would pollute the `Iterate` API. 

A different kind of approach would be to tweak the verbosity level after the first iteration to get rid of Warnings1. Still ugly.

@tawiesn @jhux2 Any other ideas?

**Comment by aprokop** [comment]
Thinking further:
1. Why is this warning present in the first place?
2. If we do need it, why is it in the `Iterate` and not `Setup`?

**Comment by tawiesn** [comment]
@aprokop I think the right place for the warnings would be in TopSmootherFactory::Build. In Hierarchy::Setup it is somewhat hard since the Setup routine never really checks for the smoothers (why should it?). We should remove the warnings from the Hierarchy::Iterate call
@jhux2 Any opinion/concerns?

**Comment by aprokop** [comment]
Not sure if/how it would work with `TopSmootherFactory`. Will need to check the code.

**Comment by tawiesn** [comment]
@aprokop SmootherFactory would be the alternative to do the check.
We could also guard the warnings with the MUELU_DEBUG keyword such that the user only gets flooded with warnings if he uses a debug version...

**Comment by jhux2** [comment]
> @aprokop I think the right place for the warnings would be in TopSmootherFactory::Build. In Hierarchy::Setup it is somewhat hard since the Setup routine never really checks for the smoothers (why should it?). We should remove the warnings from the Hierarchy::Iterate call
> @jhux2 Any opinion/concerns?

I agree that having the warning print every iteration is ... not good.   Why is this warning even necessary?  The user who report this must have actively done something to get in this situation.  One can always look at the multigrid summary;  we could even print a big fat warning there.

**Comment by aprokop** [comment]
> Why is this warning even necessary?

I think the original idea (and it may have been me who did this) was to detect configuration errors, so that we have at least a smoother and a coarse solver available. However, as Warnings1 level is quite high, the Hierarchy summary would already print out this info (like missing smoothers/coarse solvers). So, I would actually be fine with completely removing these warnings. The only difference would be that we'll print something like "No smoother" or "No coarse solver" as a statement, and not as a warning, which may not be as visible.

@tawiesn I don't think we should put layer on top of layer of complexities. If our verbosity levels do not work as expected, hiding them behind MUELU_DEBUG is just postponing the problem.

**Comment by tawiesn** [comment]
@aprokop @jhux2 I'm fine with just removing the warnings, too. @jhux2 is right: you should get the information from the MueLu Hierarchy summary printed right after the setup (if you have turned it on). Furthermore, it's rather hard to trigger this warning (in the sense you actively have to choose NoSmoother).
@jhux2 you decide what's the right thing to do.

**Comment by aprokop** [comment]
> Furthermore, it's rather hard to trigger this warning (in the sense you actively have to choose NoSmoother).

Assuming no bugs in the code, aren't we? :)

**Comment by jhux2** [comment]
Fixed in d7a7780f.
