### ISSUE TITLE
`Kokkos::OpenMP` or `Kokkos::Threads` for code using C++11 threads

### ISSUE THREAD

**Issue by teoHPC** [trilinos/Trilinos#1391]
From footnote on page 23, [Kokkos The Programming Guide](https://github.com/kokkos/kokkos/blob/master/doc/Kokkos_PG.pdf) 

>If you use a thread-parallel host execution space, we prefer Kokkos’ OpenMP back-end, as this ensures compatibility of Kokkos’ threads with the application’s direct use of OpenMP threads. Kokkos cannot promise that its Threadsback-end will not conflict with the application’s direct use of operating system threads.

Is `OpenMP` the preferred parallelization back-end if other parts of my application are parallelized with `C++11` threads? None of the `C++11` threads will interact directly with threads spawned by `Kokkos` (i.e. parallel regions do not overlap in time). However I'm not entirely sure whether they will not compete for resources anyway. Could you please clarify if there are known potential pitfalls? 
 
From [Tpetra's FAQ](https://github.com/trilinos/Trilinos/blob/master/packages/tpetra/doc/FAQ.txt) I was left with the impression that `Kokkos::Threads` is the least preferred back-end (eg. from Q: How does Tpetra pick its default Kokkos execution space?). Why is that the case? If `Kokkos::Threads` is preferred backend when using `C++11` threads, would that have impact on `Tpetra`'s performance? Why is `Kokkos::Serial` not the last, fallback option in `Tpetra`? 

Lastly, how do I change the default executions space from `Kokkos::Serial` to `Kokkos::Threads` when `Tpetra_INST_PTHREAD=ON` and `Kokkos_ENABLE_Pthread=ON`? Why is `Kokkos::Threads` not enabled by default when when `TPL_ENABLE_Pthread=ON`?

**Comment by ibaned** [comment]
Hi @teoHPC , that is a lot of questions! I won't be able to answer them all, but here is some information:

1. When asking a question about Kokkos, you will get more response if you ask it in the [Kokkos repository](https://github.com/kokkos/kokkos). However, your questions also relate to Tpetra, so it makes sense to keep it here.

1. @dsunder is currently refactoring the Kokkos thread back-ends, so he is probably the best person to answer your questions including how the answers will change in the upcoming new version of Kokkos, and correct anything wrong I say below.

1. The @trilinos/tpetra team should be able to answer questions regarding Tpetra's use of Kokkos.

1. The fundamental issue with mixing a Kokkos thread backend with your own threads is the competition for resources. To avoid slow creation/destruction of threads, both OpenMP and the Kokkos Threads backend will employ a thread pool, meaning that Kokkos threads will still exist in the background when the other parts of your application use their own threads. Features like thread binding will make this worse, as Kokkos will bind its threads assuming full control of the hardware.

1. It is important to distinguish three things: `C++11` threads, `pthreads`, and `Kokkos::Threads`. Until recently, `Kokkos::Threads` has been implemented using `pthreads`, but after @dsunder 's changes it will use `C++11` threads instead. Thus `TPL_ENABLE_Pthread` and `Kokkos_ENABLE_Pthread` do not necessarily imply `Kokkos_ENABLE_Threads`.

1. I don't think Tpetra will be much slower using `Kokkos::Threads` than `Kokkos::OpenMP`, but certainly that case doesn't get as much testing.

1. It is likely that `Kokkos::OpenMP` and `Kokkos::Threads` will be equally problematic to mix with your own `C++11` threading. The reason we prefer OpenMP is that it is more common for HPC applications to use OpenMP for parallelism, and if you were to parallelize the rest of your application with OpenMP instead of `C++11` threads, then `Kokkos::OpenMP` would be okay because they would both use the same thread pool. The trouble with `C++11` threads is that it is not one single system, your system is different from the Kokkos system and they will conflict.

**Comment by mhoemmen** [comment]
Hi @teoHPC ! @ibaned kindly answered your question in detail :-) .

We do not regularly test Trilinos with `Kokkos::Threads`.  In particular, we have been doing all performance studies with the `OpenMP`, `Cuda`, and `Serial` back-ends.

Third-party BLAS implementations that use threads for parallelism, tend to use OpenMP.  OpenMP is currently the only cross-language way to ensure that different libraries' CPU threads do not fight for resources.  Even still, this assumes that the libraries were built with the same compiler and OpenMP run-time environment.

> How do I change the default executions space from `Kokkos::Serial` to `Kokkos::Threads` when Tpetra_INST_PTHREAD=ON and Kokkos_ENABLE_Pthread=ON? 

Set the following CMake options:
```
Tpetra_INST_PTHREAD:BOOL=ON
Tpetra_INST_SERIAL:BOOL=OFF
```

> Why is `Kokkos::Threads` not enabled by default when when `TPL_ENABLE_Pthread=ON`?

Trilinos automatically detects the Pthread TPL.  (This is because the Pthread library (`-lpthread`) has uses other than for performance-oriented thread parallelism.  A good example is `pthread_once`.  Furthermore, some third-party libraries may require linking with the Pthread TPL.)  This means that Trilinos usually enables the Pthread TPL by default, even if users did not enable Tpetra's `Kokkos::Threads` back-end, and even if OpenMP is enabled.  This causes problems for tests (e.g., Tpetra wants to test over all enabled Node types), for the reasons mentioned above.

**Comment by teoHPC** [comment]
Thank you for the prompt answers! I will try the three different combinations (Serial, Threads and OpenMP) and see what works best for me.

**Comment by dsunder** [comment]
@teoHPC You will be best served by using the OpenMP backend and using OpenMP threads within your own code.  As @mhoemmen and @ibaned  both mentioned using your own thread model (c++11 or pthreads) can cause live-lock by over subscripting resources.  OpenMP is the only portable model that works with 3rd party libraries on also allows c/c++ integration with fortran codes. If you are using a compiler which supports OpenMP 4.0 or better please set the following environment variables

OMP_PLACES=[threads|cores] -- threads if you want to use hyper threads, otherwise cores
OMP_PROC_BIND=spread,close -- spread the first level of parallelism, nested levels should be close

Also make sure that the process cpuset binding is correct.  With mpirun this is done with the appropriate '--map-by' clause;  hwloc-bind, taskset and numactl can also be used to set the process mask.  See https://stackoverflow.com/questions/28216897/syntax-of-the-map-by-option-in-openmpi-mpirun-v1-8 for help with setting the '--map-by' clause with mpirun.

**Comment by ibaned** [comment]
@teoHPC I'll assume you have your answers for now, feel free to open additional issues or reopen this one as new questions arise.
