### ISSUE TITLE
yaml-cpp SEMS module built using GCC 4.4.7 (could break C++11)

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1410]
@trilinos/framework

**Comment by ibaned** [comment]
@mhoemmen can you elaborate on what you mean by that?

**Comment by mhoemmen** [comment]
The yaml-cpp module was built using GCC 4.4.7, likely with C++98.  The C++11 ABI differs from the C++98 ABI, even for C++98 language features.  This could cause build, link, or even possibly run-time errors, when attempting to use the yaml-cpp module with a C++11 compiler.

**Comment by ibaned** [comment]
Yep, you're right that can cause trouble. On the other hand, I just looked at the configure output of the CI build and saw this:
```
-- TPL_yaml-cpp_LIBRARIES='/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.9.3/base/lib/libyaml-cpp.a'
```
So it looks like the module being used by the CI build was built with GCC 4.9.3.

**Comment by bartlettroscoe** [comment]
I this issue still valid and useful?  If not, let's close it.

**Comment by ibaned** [comment]
I believe I saw this issue manifest for the `yaml-cpp/2017???` module on Ride, which is a different install though. In particular, one sees undefined references to APIs which take `std::string`, since the ABI of that changed in C++11. I don't know which module @mhoemmen was referring to so I'm not sure if the original issue is valid.

**Comment by bartlettroscoe** [comment]
Since the SEMS-build yaml-cpp TPL is being tested continuously with Trilinos (see #1167) as just shown this morning at:

* yaml-cpp TPL enabled (https://testing.sandia.gov/cdash/viewConfigure.php?buildid=3087266)
*  TeuchosParameterList_YamlParser_test_MPI_1 (https://testing.sandia.gov/cdash/testDetails.php?test=41051671&build=3087266)

the general issue of yaml-cpp compatibility is not a problem.  Therefore, I am going to close this particular issue unless there is need to keep it open.

@ibaned, if you see an specific issue with a yaml-cpp module on some system like 'ride', I don't think that is a Trilinos issue, per say.  I think that is an issue for the Advanced Technology Test Bed team.  I think we can track that here and in the SART board to discuss at regular SART meetings.  Or if it is more Sandia specific, we might consider instead tracking an issue like this on the internal Trilinos Kanban board:

* https://software-sandbox.sandia.gov/jira/secure/RapidBoard.jspa?rapidView=4&projectKey=TRIL&quickFilter=219

Closing ...
