### ISSUE TITLE
Tpetra: Debug build throws exception all the time.

### ISSUE THREAD

**Issue by lxmota** [trilinos/Trilinos#143]
Hi,

I am unable to use a debug version of Trilinos. When linked into Albany and run, the following exception is thrown regardless of the input file:

p=0: *** Caught standard std::exception of type 'std::runtime_error' :

/home/amota/LCM/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:3098:

Throw number = 1

Throw test that evaluated to true: (this->vectorIndexOutOfRange (j))

Tpetra::MultiVector<double,int,int,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::getVector(NonConst): Input index j (== 1) exceeds valid range [0, 1 - 1].

This exception is only thrown when Trilinos is compiled in debug mode. Any help would be appreciated.

Thanks,

Alejandro

**Comment by ambrad** [comment]
@lxmota, this looks very much like a bug in Albany. Here's the relevant trace:

#0  __cxxabiv1::__cxa_throw (obj=0xa76c50, tinfo=0x6bf940, dest=0x7fffcf614ef0 <std::runtime_error::~runtime_error()>)
    at ../../../../gcc-4.7.2/libstdc++-v3/libsupc++/eh_throw.cc:70
#1  0x00007fffd81d0ec2 in Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>, false>::getVector (this=0xa76410, j=1)
    at /home/ambradl/bigcode/tril/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:3095
#2  0x00007fffd81d111c in Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>, false>::getVectorNonConst (this=0xa76410, j=1)
    at /home/ambradl/bigcode/tril/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:3116
#3  0x00007ffff56db75d in AAdapt::AdaptiveSolutionManagerT::AdaptiveSolutionManagerT (this=0xa6ddd0, appParams=..., 
    initial_guessT=..., param_lib=..., stateMgr=..., rc_mgr=..., commT=...)
    at /home/ambradl/bigcode/alb/stable/Albany/src/adapt/AAdapt_AdaptiveSolutionManagerT.cpp:134
#4  0x00007ffff6b89c36 in Albany::Application::finalSetUp (this=0x9b3120, params=..., initial_guess=...)
    at /home/ambradl/bigcode/alb/stable/Albany/src/Albany_Application.cpp:500
#5  0x00007ffff6b84136 in Albany::Application::Application (this=0x9b3120, comm_=..., params=..., initial_guess=...)
    at /home/ambradl/bigcode/alb/stable/Albany/src/Albany_Application.cpp:89
#6  0x00007ffff6953705 in Albany::SolverFactory::createAndGetAlbanyApp (this=0x7fffffffd230, albanyApp=..., appComm=..., 
    solverComm=..., initial_guess=..., createAlbanyApp=true)
    at /home/ambradl/bigcode/alb/stable/Albany/src/Albany_SolverFactory.cpp:369
#7  0x00007ffff6955317 in Albany::SolverFactory::createThyraSolverAndGetAlbanyApp (this=0x7fffffffd230, albanyApp=..., 
    appComm=..., solverComm=..., initial_guess=..., createAlbanyApp=true)
    at /home/ambradl/bigcode/alb/stable/Albany/src/Albany_SolverFactory.cpp:491
#8  0x000000000045d33e in main (argc=2, argv=0x7fffffffdeb8)
    at /home/ambradl/bigcode/alb/stable/Albany/src/Main_Solve.cpp:182

Moreover,

(gdb) print num_time_deriv
$7 = 0
(gdb) 
(gdb) print (*current_soln).getNumVectors()
$8 = 1

I speculate that it is a bug associated with the recent time derivative work. I'm going to close this issue since it's (almost certainly) an Albany bug.
