### ISSUE TITLE
STK fixtures

### ISSUE THREAD

**Issue by jrood-nrel** [trilinos/Trilinos#1433]
Recently (today 6/15/2017) I have seen that Trilinos omits installing the `includes/stk_mesh/fixtures` directory during `make install`, and it appears they install to the base `includes` directory instead. Is this intentional?

**Comment by ibaned** [comment]
@trilinos/stk

**Comment by khpierson** [comment]
The last change that I can find in the repository that probably affected where these header files would be installed was intentionally re-arranging code to improve dependencies. Sorry for the confusion, we will try not to perform these structural directory changes as much in the future.

-Kendall

commit e3962e6ee692e5f6c25d419d670e787081d7d6ab (master~1378)
Author: Todd S. Coffey <tscoffe@sandia.gov>
Date:   Thu May 4 10:58:15 2017 -0600

    Trac #16717
    Remove symbolic links under stk directory
    stk_io/testsForDocumentation
    stk_io/unit_tests
    stk_mesh/testsForDocumentation
    stk_mesh/unit_tests
    stk_mesh/stk_mesh/fixtures
    stk_simd/testsForDocumentation
    stk_tools/unit_tests
    stk_transfer/unit_tests
    stk_transfer/use_cases
    stk_util/testsForDocumentation
    stk_util/unit_tests
    stk_topology/tests_for_documentation
    stk_topology/unit_tests
    
    Cleaned up dependencies between stk_simd/unit_tests and stk_simd/testsForDocumentation
    
    Moved includes to point to stk_unit_tests/stk_mesh_fixtures/ instead of stk_mesh/fixtures

**Comment by jrood-nrel** [comment]
Thanks for the clarification. Understandable. I was just curious if our project should adapt to the change or if it was unintentional. I will close this then.

**Comment by jrood-nrel** [comment]
@khpierson Actually I made the changes to my project to account for the relocated headers, but I'm not sure this has been fully accounted for in Trilinos as seen in the error below. Am I missing something?

```
... /trilinos-develop-kmsdpyrspocad3g56s5rukjoswbzphxi/include/HexFixture.hpp:44:66: fatal error: stk_unit_tests/stk_mesh_fixtures/CoordinateMapping.hpp: No such file or directory
```

**Comment by khpierson** [comment]
Where is CoordinateMapping.hpp found in your repository? 

We do not work with an installed version of Trilinos when we develop stk. The file CoordinateMapping.hpp is located (for me) in stk/stk_unit_tests/stk_mesh_fixtures/CoordinateMapping.hpp

**Comment by jrood-nrel** [comment]
It is in the base `include/` directory after `make install` occurs.

**Comment by khpierson** [comment]
I will have to ask someone on the Trilinos side to better understand the rules with make install and why the files are moved. I think you could add a symbolic link to the header file where it is missing or modify the HexFixture file to point to the include directory.

**Comment by bmpersc** [comment]
It looks like there was a change to one of the cmake files to change one of the directories where files are installed due to a change in internal paths. The change was to remove a no longer existing path, but the new path was not added back in. I am currently testing a fix for this and if it works I will add the patch here since this probably won't make it back into Trilinos before the end of the day.

**Comment by bmpersc** [comment]
[0001-STK-Fix-Trilinos-build-install-issue.patch.txt](https://github.com/trilinos/Trilinos/files/1089415/0001-STK-Fix-Trilinos-build-install-issue.patch.txt)
Here is the patch that should fix this. I will work to get this applied to the places it needs to be. In the mean time if you apply this to your copy of Trilinos you should be able to do your regular configure/build/install process. Note that this patch will not show up exactly this way in Trilinos because of the way we integrate STK so you will probably need to remove the patch before pulling the real update. It is likely that a git pull --rebase will automatically drop this patch for you once the fix is in Trilinos, but I can't guarantee that.

**Comment by jrood-nrel** [comment]
Thanks @bmpersc . I can probably wait until this makes its way into the develop branch.

**Comment by bmpersc** [comment]
There is currently a blocker getting this into Trilinos. I ran the integration and just as a sanity check tried to build Nalu against an install and it was unable to find some of the fixtures because it was directly using the old paths. I need to speak with the Nalu team about this before I just update.

**Comment by nmhamster** [comment]
@bmpersc - I hit this too but the NALU binary is actually built correctly, its the `unit_tests` build which fail. Can you check the binary is actually in the build directory (`naluX`)?

**Comment by bmpersc** [comment]
@nmhamster I do not have the Nalu executable in my build, but this was not the only issue I ran into. I also hit a linking issue due to a -Bstatic being in a bad place and causing the linker to want to link a Trilinos shared library as static, which it rightfully complained about. I didn't mention that before since it wasn't germane to this issue. In any event I don't really want to break one project to fix another. We need to break fewer people each time we fix something. However, it looks like this report may have been related to Nalu all along.

**Comment by jrood-nrel** [comment]
@bmpersc At the moment with the current Trilinos develop branch, I have been seeing the Nalu binary build successfully, but the unit test binary is what fails to compile. We will have to change the STK header locations in the Nalu unit test files, but as long as the other Trilinos headers have accounted for the change in location of STK headers, that should be sufficient right? Is the patch file listed here still the exact fix? I can apply it to Trilinos and make the necessary modifications to Nalu and see what I come up with. Currently Nalu only builds statically, but I have a modification to Nalu I am waiting to merge in which should allow it to build with shared libraries.

**Comment by jrood-nrel** [comment]
@bmpersc Actually can you just get Nalu to use the shared libraries instead? I have a root-level CMakeLists.txt at https://github.com/jrood-nrel/Nalu/blob/cmake_reorg/CMakeLists.txt that should allow for this.

**Comment by bmpersc** [comment]
@jrood-nrel I am still having issues building Nalu with your CMakeLists.txt. And of course it is a different issue. I'm happy to work with you on getting the new shared build for Nalu working, but we should track that in a different ticket that this one. If you have a Nalu ticket for this please let me know which it is. I briefly looked at Nalu's issues and none of them jumped out at me.

**Comment by jrood-nrel** [comment]
@bmpersc I'm not worried about getting Nalu to build and use shared libraries as I have done it before. I was just trying to avoid having to patch and rebuild Trilinos and patch Nalu to test this. I will test the patch right now.

**Comment by jrood-nrel** [comment]
@bmpersc The patch works, and Nalu builds successfully when I update the header locations. I think the change should be merged in. Then I will update Nalu when that is done.

**Comment by bmpersc** [comment]
@jrood-nrel I just pushed an update to STK which will include this fix as well as the breakage to Nalu that was noted. If you notice any issues with this please let me know.

**Comment by jrood-nrel** [comment]
We have merged the fix into Nalu and it builds again.
