### ISSUE TITLE
Phalanx::MDField::dimensions to use fieldTag data layout rather than underlying view

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#1452]
I was wondering if there is any reason for MDField to inspect the underlying Kokkos View rather than the stored data layout in order to properly fill the dimension vector, when the 'dimensions' method is called.

The reason (for me) to prefer using the data layout is that it is available at any time (unless one used the default constructor), and yields the expected result, while the current implementation (which relies on the call to the dimension method of the Kokkos view) yields 0's until setFieldData has been called.

It would seem to me that if the data layout is available (i.e., not null), then one should trust it, and use it. Is there a reason for checking the view instead of the data layout? I know there are some uses of MDFields which are a little more complex and require attention, so maybe I'm missing something here...

**Comment by rppawlo** [comment]
@bartgol - my apologies - I did not see this ticket until today. I have made the change locally and can push after review next week. However, I'm not sure if making this change is the right thing to do. Here's some background. The requested change assumes that you are using the MDALayout that requires size information at construction. But the DataLayout is actually a pure virtual base class and other implementations (in particular one that will be added next week) will not have this restriction. The new layout will not have size information until the call to bind memory is made. We have some new applications that require delayed sizing - building the evaluators before the field sizes are known. So far the assumption is that the MDField is not a usable object until both the tag and data are set. The debug checks currently force both the layout and memory to be set so that it is guaranteed to be ready for use. So we can make this change but the delayed sizing use case becomes slightly less safe - there is a chance that the data layout will be set but contain all zeroes just like the kokkos view prior to memory binding. Adding @eric-c-cyr and @seamill to get their opinion. I don't think any of the other applications even use the dimensions() function since it is limited to host-only. So its probably fine to change.

Also, you can already access the data layout dimensions method directly without any changes to phalanx via:

my_mdfield.tag().dataLayout().dimensions(...);

**Comment by seamill** [comment]
I have to agree with @rppawlo on this one. If the data space isn't assigned, then it would be dangerous to have MDField tell you otherwise.

**Comment by bartgol** [comment]
That's fine with me. After all, as Roger said, I can always get the data layout from the tag, and use that. I am wondering if it would be helpful, at least in debug mode, to throw some sort of exception in case one calls the dimensions method on the field before the bind memory is made. Perhaps not, since one could use this to check if the data has been set.

Anyways, thanks for the feedback. I'm going to close this, since it appears there are enough reasons not to modify the current behavior.

**Comment by rppawlo** [comment]
> I am wondering if it would be helpful, at least in debug mode, to throw some sort of exception in case one calls the dimensions method on the field before the bind memory is made.

This should already happen in debug mode. The current implementation is:

```
//**********************************************************************
template<typename DataT,
	 typename Tag0,typename Tag1, typename Tag2, typename Tag3,
	 typename Tag4,typename Tag5, typename Tag6, typename Tag7>
template<typename iType>
void PHX::MDField<DataT,Tag0,Tag1,Tag2,Tag3,Tag4,Tag5,Tag6,Tag7>::
dimensions(std::vector<iType>& dims)
{
#if defined( PHX_DEBUG) && !defined (__CUDA_ARCH__ )
  TEUCHOS_TEST_FOR_EXCEPTION(!m_tag_set, std::logic_error, m_field_tag_error_msg);
  TEUCHOS_TEST_FOR_EXCEPTION(!m_data_set, std::logic_error, m_field_data_error_msg);
#endif

  dims.resize(m_field_data.Rank);
  for ( size_type i = 0 ; i <  m_field_data.Rank; ++i ) 
    dims[i] = static_cast<iType>(m_field_data.dimension(i));
}
```
