### ISSUE TITLE
Set up new continuous builds

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#1457]
@trilinos/framework 

In alignment with the discussion at the Framework Standup this morning, we need to set up 2 new continuous builds on the newer build farm - one to support GCC 4.8.4, the other to support GCC 4.9.3.

**Comment by bmpersc** [comment]
Initial work on this was to figure out if jenkins could send the necessary sha1 that was determined by a single check of the repo to a job through the parameter system. This was actually pretty easy as jenkins provides a variable that has the git sha1 which can be used in a build step or passed as a parameter to jobs that are started. This solves the question of if we can  have a driver job to start off multiple continuous runs on the same sha1, the answer is yes! Jenkins is even smart enough to give the current sha1 when the job is started by hand or timer even if there hasn't been an update since the last run. So it should be able to maintain the existing behavior that we have with the single job.

In addition to that test I have setup a prototype of the continuous job to make sure that the tribits system will work with the information that we give the jenkins job. The first run on Friday died early because I had an improperly setup environment. There was no parmetis module loaded so the configure failed. I have fixed this and started another job. The current concern I have for this is the copy of the repo that tribits clones being based on the sha1 we want. I forget exactly how the continuous works here so once a job runs I will need to inspect the repo to make sure the right sha1 is used.

**Comment by bmpersc** [comment]
Currently this is stalled. The Jenkins parts are working as expected, however, when the testing scripts are run they clone an additional version of trilinos to run the testing against which is defaulting to the develop branch. I have looked into finding an option for telling the testing to use a specific sha1, however, all I could find was to tell it a specific branch.

After speaking with @jwillenbring  about this we decided that we needed to think a bit more about what we want out of the continuous testing before looking at ways of addressing this. Until we have a better idea of what we want to accomplish with this testing this will be on hold.

**Comment by bartlettroscoe** [comment]
> I have looked into finding an option for telling the testing to use a specific sha1, however, all I could find was to tell it a specific branch.

Why do you need to give it a specific SHA1?  Why is the tip of 'develop' not good enough for a CI server?

In any case, you can always just let Jenkins do the version control and then turn off updates in the TribitsCTestDriverCore.cmake code (just set `CTETS_DO_UPDATES=OFF`).
