### ISSUE TITLE
Tpetra and Kokkos default node types

### ISSUE THREAD

**Issue by srajama1** [trilinos/Trilinos#1463]
I am not able to find documentation on default node types. In particular, there is this question from an user for which I don't have a good answer to.

 Is there a reason why Tpetra doesn’t just use `Kokkos::DefaultExecutionSpace`?

@trilinos/tpetra 

More info from the user..

Kokkos::Serial is available.
Kokkos::OpenMP is available. (Control num-threads via env-var OMP_NUM_THREADS)
Default execution space info: Kokkos::OpenMP KOKKOS_ENABLE_OPENMP thread_pool_topology[ 1 x 24 x 1 ]

In Tpetra_ConfigDefs.hpp, it seems to be setting

      //! Default value of Node template parameter.
      typedef KokkosClassic::DefaultNode::DefaultNodeType node_type;

**Comment by srajama1** [comment]
@kddevin @tjfulle

**Comment by mhoemmen** [comment]
Tpetra imitates Kokkos' default behavior for its defaults, but has its own settings.

Care to submit a pull request implementing the behavior that you would prefer?

**Comment by srajama1** [comment]
I am trying to understand the behavior for an user. If it will match Kokkos then let me request an example from the user. In his use case, he sees them different. I would rather leave the changing to Tpetra experts.

**Comment by mhoemmen** [comment]
I need information about the user and their needs in order to prioritize work.  The best option has always been to enable OpenMP, CUDA, etc. at the Trilinos level, and let the defaults propagate into Tpetra.  For example:

  - Enabling CUDA (by using NVCC and `nvcc_wrapper`) makes CUDA Tpetra's default execution space.
  - Enabling OpenMP (`Trilinos_ENABLE_OpenMP:BOOL=ON`), but not enabling CUDA, makes OpenMP Tpetra's default execution space.
  - The Pthreads (`Kokkos::Threads`) back-end is a special case; it does not get enabled by default.  This avoids surprises, because Trilinos enables its Pthreads TPL by default as long as it can detect it.  Users may set CMake options to enable use of Pthreads in Tpetra, and to make it default.

Users who set nondefault CMake options will get nondefault behavior.  For example, a major internal application sets all sorts of CMake options that turn off threads in Tpetra.  I'm working with their framework team now to change that, but it's complicated.

If your user wants Tpetra support, perhaps they should speak with the Tpetra team or someone who understands CMake?

**Comment by srajama1** [comment]
I understand CMake quite well. Thanks ! It is not realistic to assume all Trilinos developers  to look at Tpetra source code and CMake files. If that is the case for Tpetra support please add it to @maherou 's Trilinos support policy. All that is needed is to have this three bullets in the above comment in an accessible document and a pointer to that one. Any Trilinos developer is not going to do that and generate a PR for the Tpetra team. It is the responsibility of people who get paid to be Tpetra developers and who gets to brag about it.

A simple question on Tpetra doesn't have to become a recruiting effort for Tpetra PRs or questioning Tpetra users' knowledge of CMake. These outbursts are precisely why there needs to be a layer between Tpetra support and the users. Please learn proper way of commenting in a public forum.

**Comment by tjfulle** [comment]
@srajama1, I've been working on a @trilinos/tpetra user's guide and have included guidance on choosing node types.  The guide needs to go through R&A and @mhoemmen and I are looking in to how to link the html version to Tpetra's existing online doxygen documentation.

**Comment by srajama1** [comment]
@tjfulle : Thanks for the update. Please feel free to close the issue whenever appropriate.

**Comment by mhoemmen** [comment]
The tpetra/doc/FAQ.txt explains default choices of Node and `execution_space`, and how to change those.  @tjfulle please feel free to reference that and update documentation as necessary; thanks!
