### ISSUE TITLE
Tpetra::MultiVector::dot: Reduce overhead for CUDA

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1470]
@trilinos/tpetra 
@jjellio 
See #1455 discussion.

**Comment by mhoemmen** [comment]
- Avoid `getVector()` and other calls that create a new DistObject instance.
  - Instead of `getVector()`, use the `DualView` and `whichVectors_` directly.
  - Think about how to optimize the case where the output array lives in host memory, but the input (multi)vectors do not.  This will be a common case for users who run Belos' iterative solvers.

**Comment by mhoemmen** [comment]
btw this came to light because of @jjellio 's performance tests.

**Comment by mhoemmen** [comment]
#1560 should help with this, by reducing getVector() overhead.

**Comment by mhoemmen** [comment]
@jjellio Did my #1560 fix help?  If so, I'll close this issue.  Thanks!

**Comment by jjellio** [comment]
@mhoemmen Sorry for the late reply, for whatever reason I seem to randomly get notifications.

We have not run newer builds on Trilinos yet ... Once we get the performance variations figured out we will. The problem is that the machine is producing performance variations that are too large.  With the prior study, you really cannot not determine if code modifications are helpful or detrimental, because the run to run variations are so large they dwarf issues like the one tracked here.

**Comment by mhoemmen** [comment]
Thanks @jjellio !  I think what I'll do is close this issue, since the underlying reallocation of communication buffers in DistObject is no longer an issue for getVector and getVectorNonConst.  We can open a new issue with a more concrete goal later.
