### ISSUE TITLE
MueLu, Teuchos build error on Windows (MSVC)

### ISSUE THREAD

**Issue by mplooster** [trilinos/Trilinos#1485]
Found while working on #1160. For [this build](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2993301) using Visual Studio 2015, [this error](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=2993320) in MueLu was introduced recently:

> C:\Users\mgploos\TrilinosProject\MPI_Release_12.11\Trilinos\packages\teuchos\core\src\Teuchos_Array.hpp(1352): error C2102: '&' requires l-value

I can trace it back to this commit a couple of weeks ago - 2c0690c45b14ba38392f49fca5dd268b914e57eb. If I comment out the line

`level->Set(varName, Teuchos::getValue<Array<bool> >(it2->second), NoFactory::get());`

MueLu builds fine. The ArrayRCP\<bool\> version that was also added in this commit compiles without any problems, so I am not sure what it is about Array\<bool\> that would cause this to start failing. I do know that the call to Teuchos::getValue in [MueLu_HierarchyUtils_def.hpp](https://github.com/trilinos/Trilinos/blob/2c0690c45b14ba38392f49fca5dd268b914e57eb/packages/muelu/src/MueCentral/MueLu_HierarchyUtils_def.hpp#L228) ends up using [Teuchos::Array\<T\>::view](https://github.com/trilinos/Trilinos/blob/2c0690c45b14ba38392f49fca5dd268b914e57eb/packages/teuchos/core/src/Teuchos_Array.hpp#L1352) after lots of casting and calls to other template functions.

Can anyone on the @trilinos/muelu @trilinos/teuchos or @trilinos/framework teams comment on what might be happening here that would cause this build error?

**Comment by ambrad** [comment]
Just a guess: Array<T>::vec_ is a std::vector<T>. Hence Array<bool> behaves exactly as std::vector<bool>. &v[k] for v a std::vector<bool> isn't defined. See this, e.g.:

https://stackoverflow.com/questions/17794569/why-is-vectorbool-not-a-stl-container

**Comment by ambrad** [comment]
BTW, if `Array<T>` were to decide it wants to be a container even for `T=bool` (so it could support views, e.g., as in the issue above), I think it could metaprogram around the `std::vector<bool>` detail by declaring `vec_` to be `std::vector<typename ContainedType<T>::type>`, with `ContainedType<T>::type == T` by default and with specialization `ContainedType<bool>::type == char`.

**Comment by mplooster** [comment]
> Hence Array<bool> behaves exactly as std::vector<bool>. &v[k] for v a std::vector<bool> isn't defined.

That would explain it. So why aren't other platforms like Linux and Mac complaining about this?

> BTW, if Array<T> were to decide it wants to be a container even for T=bool (so it could support views, e.g., as in the issue above), I think it could metaprogram around the std::vector<bool> detail by declaring vec_ to be std::vector<typename ContainedType<T>::type>, with ContainedType<T>::type == T by default and with specialization ContainedType<bool>::type == char.

I imagine that would probably also require changing functions like `vec()` so that they return `std::vector<typename ContainedType<T>::type>` as well - or changing the view function to use `vec_` instead of `vec()`.

**Comment by mplooster** [comment]
> So why aren't other platforms like Linux and Mac complaining about this?

Could it be because I am not building with Tpetra enabled, and CMake/TriBITS apparently turns off Explicit Template Instantiation for MueLu? From my CMake output:

> Processing enabled package: MueLu (Libs, Tests)
-- Disabling MueLu explicit template instantation (ETI) because Tpetra is disabled.

**Comment by bmpersc** [comment]
@mplooster There is a good chance that this isn't showing up because of an issue with ETI. Almost all (maybe all, I haven't checked) of our nightly testing does enable ETI explicitly. You should be able to do a quick test by enabling ETI explicitly as well by adding:

-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON

to your configure. I'm not really sure what will happen on windows with ETI on as the last windows testing we had running disabled it. Muelu wasn't built either so there are lots variables here from our last windows testing. It can't hurt much to try enabling ETI though. I know that I've had to do that on linux to get past issues unrelated to what I was working on before so this wouldn't be the first time that the non-ETI build was broken an no one noticed for a bit.

**Comment by mplooster** [comment]
@bmpersc I have that option enabled, but unfortunately, MueLu has some CMake logic [here](https://github.com/trilinos/Trilinos/blob/c6be0a2b04589e40452fe0f875384f0bf324db30/packages/muelu/CMakeLists.txt#L47) that turns it back off if Tpetra happens to be disabled (which it is in my case). If I comment out those lines and build, the build still fails in the same place. I can tell from the CMake output that ETI for MueLu is on:

> Processing enabled package: MueLu (Libs, Tests)
-- MueLu ETI support enabled
-- <float,   int, int>       : OFF
-- <double,  int, int>       : OFF
-- <double,  int, long>      : OFF
-- <double,  int, long long> : OFF
-- <complex, int, int>       : OFF
-- HAVE_MUELU_SERIAL       : ON
-- HAVE_MUELU_PTHREAD      : 
-- HAVE_MUELU_OPENMP       : 
-- HAVE_MUELU_CUDA         : 

I'm not sure about whether I need to enable some of the <double, int, int> options or not, or if that would have any effect on it.

**Comment by ibaned** [comment]
I think we have a fundamental choice to make here. Either:

1. `Teuchos::Array` should *not* support `T=bool`. It does not currently, because of the special behavior of `std::vector<bool>` and the fact that the `ArrayView` system assumes that `std::vector<T>` is internally an array of type `T*`, which is not true for `std::vector<bool>`. If we choose to make this officially unsupported, then MueLu is at fault for trying to use it. We should add a `static_assert` to `Teuchos::Array` (protected by a `CXX11` support macro) to ensure no one instantiates it with `bool` due to this limitation.

2. `Teuchos::Array` *should* support `T=bool`. In this case we can do something like @ambrad's suggestion of `ContainedType`, but I suspect it will take more work than that; we may still see errors about casting between `bool*` and `char*`.

**Comment by mplooster** [comment]
@tawiesn How necessary is it for you to support Array\<bool\>, which you added in this commit - 2c0690c45b14ba38392f49fca5dd268b914e57eb?

**Comment by tawiesn** [comment]
@mplooster Well, so far it is only used in one place and we could circumvent the problem by using an Array<LO> with 1 for true and 0 for false. Not very elegant, but possible.

**Comment by ibaned** [comment]
Yea, this is unfortunately an edge case that `Array<bool>` inherits from `std::vector<bool>`. If you could handle this case via `Array<int>`, then we can add compile-time checks to ensure no one else tries to use `Array<bool>` until it is ready, if ever.

**Comment by tawiesn** [comment]
@ibaned Would `Array<char>` work as well? I don't really want to waste too much memory.

**Comment by ibaned** [comment]
I guess... that shouldn't be a weird case for `std::vector` at least...  I don't know if this involves `ParameterList`, but I know the YAML `ParameterList` system doesn't support any array types besides `int`, `double`, and `std::string`.

By the way, I think in GCC `sizeof(bool) == sizeof(int)`.

**Comment by tawiesn** [comment]
@mplooster I pushed commit 1926d6e122 which removes the problematic Array<bool> and ArrayRCP<bool>. Please let me know if you find more problems related to that.

**Comment by mplooster** [comment]
@tawiesn I ran [this build](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3009900) and MueLu is once again building without compile errors. That seems to have done the trick. Thanks!
