### ISSUE TITLE
Teko: tpetra testdriver failing

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#1511]
Using unmodified code from commit c6be0a2b04589e40452fe0f875384f0bf324db30, the test ```Teko_testdriver_tpetra_MPI_1``` fails. The error when running ```ctest -V -R Teko_testdriver_tpetra_MPI_1``` is:

```
484: Running test "LSCStabilized_tpetra"
484: Teko: LSCPrecFact::buildPO BuildStateTime = 0
484: Teko: LSCPrecFact::buildPO GetInvTime = 1.09673e-05
484: Teko: LSCPrecFact::buildPO TotalTime = 0.000582933
484:    "diagonal" ... PASSED
484: Teko: Inverse "Ifpack2" is of type strat prec = 1, strat solv = 0, block prec = 0
484: Teko: LSC::initializeState Build Scaling <mass> type "Diagonal"
484:    Teko: Begin debug MSG
484:       LSC Gamma Parameter = 0.237413
484:       LSC Alpha Parameter = 0.667104
484:    Teko: End debug MSG
484: Teko: LSC::buildState BuildOpsTime = 0.0320289
484: Teko: LSC::computeInverses Building inv(F)
484: Teko: LSC::computeInverses GetInvF = 0.000749826
484: Teko: LSC::computeInverses Building inv(BQBtmC)
484: Teko: LSC::computeInverses GetInvBQBt = 0.000702858
484: Teko: LSC::buildState BuildInvTime = 0.00148702
484: Teko: LSCPrecFact::buildPO BuildStateTime = 0.033529
484: Teko: LSCPrecFact::buildPO GetInvTime = 7.86781e-06
484: Teko: LSCPrecFact::buildPO TotalTime = 0.0341179
484:    "strategy" ... FAILED ( PID = 0 )
484: Test "LSCStabilized_tpetra" completed ... FAILED (1)
```

Configure script:
```
cmake \
-DTrilinos_TRIBITS_DIR:PATH=$TRILNOS_PATH/cmake/tribits \
-DTrilinos_ENABLE_TESTS:BOOL=ON \
-DTrilinos_TEST_CATEGORIES:STRING=BASIC \
-DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF \
-DDART_TESTING_TIMEOUT:STRING=600.0 \
-DBUILD_SHARED_LIBS=ON \
-DTrilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES=ON \
-DTrilinos_TRACE_ADD_TEST=ON \
-DTrilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=OFF \
-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/MpiReleaseDebugSharedPtSettings.cmake,cmake/std/BasicCiTestingSettings.cmake \
-D BUILD_SHARED_LIBS:BOOL=ON \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D TPL_BLAS_LIBRARIES:PATH="/usr/lib64/libblas.so.3" \
-D TPL_LAPACK_LIBRARIES:PATH="/usr/lib64/liblapack.so.3" \
-D BoostLib_INCLUDE_DIRS:PATH="${SEMS_BOOST_INCLUDE_PATH}" \
-D BoostLib_LIBRARY_DIRS:PATH="${SEMS_BOOST_LIBRARY_PATH}" \
-D Boost_LIBRARY_DIRS:FILEPATH="${SEMS_BOOST_LIBRARY_PATH}" \
-D Boost_INCLUDE_DIRS:FILEPATH="${SEMS_BOOST_INCLUDE_PATH}" \
-D SuperLU_LIBRARY_DIRS:PATH="${SEMS_SUPERLU_LIBRARY_PATH}" \
-D SuperLU_INCLUDE_DIRS:PATH="${SEMS_SUPERLU_INCLUDE_PATH}" \
-D yaml-cpp_LIBRARY_DIRS:FILEPATH="${SEMS_YAML_CPP_LIBRARY_PATH}" \
-D yaml-cpp_INCLUDE_DIRS:FILEPATH="${SEMS_YAML_CPP_INCLUDE_PATH}" \
-DTrilinos_ENABLE_MueLu:BOOL=ON \
-DTrilinos_ENABLE_Stokhos:BOOL=ON \
-DTrilinos_ENABLE_Xpetra:BOOL=ON \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
-DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON \
$TRILINOS_PATH
```

**Comment by mhoemmen** [comment]
@trilinos/teko

**Comment by ibaned** [comment]
@bartlettroscoe this impeded checkin of a Kokkos snapshot

**Comment by bartlettroscoe** [comment]
The test `Teko_testdriver_tpetra_MPI_1` is shown currently passing in the standard CI build as shown at:

* https://testing.sandia.gov/cdash/viewTest.php?onlypassed&buildid=3104481

Therefore, if it is failing on this machine, either one of the following is occurring:

1. A push was made to Trilinos since this CI build ran that is breaking this test.
2. The env and configuration options used to configure Trilinos for this build are different from the standard CI build
3. The standard CI env and build is exactly matched, but this test is failing on this machine do to hardware diffrences.
4. Changes made on the local branch not yet pushed to the Trilinos 'develop' branch are triggering this failure.

You can rule out case-1 above because I verified that no pushes to Trilinos have been done yet since this CI build ran.

So that leaves case-2 through case-4.  To see which it is, what happens if the [standard CI build with the SEMS env](https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing) is performed?  You can try that (relatively) quickly on any SNL COE RHEL 6 or 7 machine that has the SEMS env mounted using:

```
$ cd Trilinos/
$ mkdir CHECKIN/
$ ln -s ../cmake/std/sems/checkin-test-sems.sh .
$ source ../cmake/load_sems_dev_env.sh
$ ./checkin-test-sems.sh --allow-no-pull --configure
$ cd MPI_RELEASE_DEBUG_SHARED_PT/
$ cd packages/teko/tests/
$ make -j16 Teko_testdriver_tpetra
$ ctest -R Teko_testdriver_tpetra_MPI_1
```

Does that that test pass or fail?

**Comment by bartlettroscoe** [comment]
Ignore my comment ...

Sorry, I did not read the dates on the comments.  This was an old issue that was actually already resolved.

@ibaned, thanks for the archival pointer.

**Comment by mhoemmen** [comment]
@bartlettroscoe Not sure if the relevant developers are getting GitHub notifications.  I'll forward this to them.

**Comment by ibaned** [comment]
Um, I think there is some confusion. I'm referring to the Kokkos snapshot that just happened yesterday, kokkos/kokkos#1721. @crtrott referenced this issue to explain why this Teko test failed during the checkin process yesterday (see https://github.com/trilinos/Trilinos/pull/1721#issuecomment-328708707).

I'd also like to offer an option (5) as to why the test fails, namely that the test fails nondeterministically. This is just an option to keep in mind, since I've seen this happen with other tests without much explanation.

Strangely, I don't see the CI build testing Teko in the last 16 hours, which is the time that this snapshot has been in Trilinos.

**Comment by bartlettroscoe** [comment]
@ibaned,

> Um, I think there is some confusion. I'm referring to the Kokkos snapshot that just happened yesterday, #1721 . @crtrott referenced this issue to explain why this Teko test failed during the checkin process yesterday (see #1721 (comment)).

Okay, I take back my comment then :-)  Since this issue was so old, I was assuming this was already resolved.

> I'd also like to offer an option (5) as to why the test fails, namely that the test fails nondeterministically. This is just an option to keep in mind, since I've seen this happen with other tests without much explanation.

That is a possibility.  To test that, just run it by itself multiple times and see if you see any random behavior.

> Strangely, I don't see the CI build testing Teko in the last 16 hours, which is the time that this snapshot has been in Trilinos.

When you go to:

* https://github.com/trilinos/Trilinos/wiki/Policies--%7C-Testing#post_push_ci_testing

and click on the "Continuous Integration Build" link whic takes you to:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=66&value1=-MPI_RELEASE_DEBUG_SHARED_PT_CI&field2=groupname&compare2=61&value2=Continuous&field3=buildstarttime&compare3=84&value3=now

you don't see the CI build:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3104

which started this morning at 4 AM MDT?

**Comment by ibaned** [comment]
> you don't see the CI build which started this morning at 4 AM MDT?

Oops, simple mistake on my end. I didn't see that there are multiple pages of packages with only 10 packages per page. Teko is there in page 4.

**Comment by bartlettroscoe** [comment]
Given the discussion in #1721, it seems that this test as currently implemented passes on some machines that use the SEMS env and fails on others using the same SEMS env.  That is bad.  Really we should fix this test so that it passes on all RHEL 6 and 7 systems with the SEMS env.  The first concern that I have is that no automated build in the entire Trilinos CDash DB over the last 6 weeks on all platforms ever shows this test failing in 266 total builds on various platforms as shown in the query:

* https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=Teko_testdriver_tpetra_MPI_1&field2=buildstarttime&compare2=84&value2=now

(just sort by the "Status" column to see failed tests, which there are none currently).

@crtrott, what type of machine are you running the checkin-test-sems.sh script on with the mounted SEMS env where this test is failing for you?  Once we document that, then we can reason what to do.

Please let me know if someone on the @trrilinos/teko team can fix this soon.  Otherwise, we might just remove this test from the standard CI build (but it will still run in all other builds where it has always passed for the last 6 weeks).

**Comment by eric-c-cyr** [comment]
@egphill We should do two things. One figure out how to convince teko to write out more stuff regarding this issue. Two, probably relax the tolerances.

https://testing.sandia.gov/cdash/buildSummary.php?buildid=3297669

**Comment by bartlettroscoe** [comment]
Is this still an issue?  Other than one troublesome individual unit tests that we disabled for some of that ATDM Builds as described in #2712, this test has been okay in all of the other builds (or at least we have not had any recent issues with this).

**Comment by mayrmt** [comment]
I opened this issue as this problem came up quite a while ago. @bartlettroscoe feel free to close it, if nobody objects.

**Comment by bartlettroscoe** [comment]
> I opened this issue as this problem came up quite a while ago. @bartlettroscoe feel free to close it, if nobody objects.

Closing.
