### ISSUE TITLE
g++ -Wconversion warnings

### ISSUE THREAD

**Issue by bradbell** [trilinos/Trilinos#1524]
Compiling a simple Sacado example using the -Wconversion flag with g++ yields many warnings. 

Example 1:
include/Teuchos_ScalarTraits.hpp:180:49: warning: conversion to ‘char’ from ‘int’ may alter its value [-Wconversion]
   static inline char random() { return std::rand(); } // RAB: This version should be used for an unsigned char, not char
                                        ~~~~~~~~~^~

Example 2:
include/Teuchos_as.hpp:1318:27: warning: conversion to ‘double’ alters ‘long int’ constant value [-Wfloat-conversion]
         t < minVal || t > maxVal,
                           ^

Kludge: Adding the following at the beginning of files that include triinos headers seems to work:
  \# if COMPILER_IS_GNUCXX
  \# pragma GCC diagnostic ignored "-Wfloat-conversion"
  \# pragma GCC diagnostic ignored "-Wconversion"
  \# endif

**Comment by aprokop** [comment]
@trilinos/teuchos

**Comment by mhoemmen** [comment]
@trilinos/sacado

**Comment by ibaned** [comment]
This is a more general issue of how to include Trilinos headers in projects that use stricter warning flags than Trilinos does in its testing.

I'm not sure what build system you're using, but one thing to try would be to include the Trilinos `include` directory with `-isystem` instead of `-I`:

```bash
gcc -isystem /path/to/Trilinos/include foo.cpp -o foo.o
```

I'm not sure if you're compiling this example using TriBITS or by itself outside of Trilinos, but I am pretty sure Trilinos will not cleanly compile with `-Wconversion`.

**Comment by bartlettroscoe** [comment]
Converting from an 'int' to a 'char' is dangerous.   We should likely fix this and other examples by being more careful (and using explicit casts and other checks, etc.).  But fixing all of these warnings in Trilinos would be a lot of work.  Therefore, I would recommend that you try using `-isystem` as suggested above for now.

**Comment by mhoemmen** [comment]
Converting the result of std::rand to char is probably harmless, but it would make sense for ScalarTraits to make the conversion more explicit there.

**Comment by jwillenbring** [comment]
@MicheldeMessieres I wanted you to see this. No action item currently, but it relates to our conversation yesterday.
