### ISSUE TITLE
STK docs on trilinos.org not found.

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#163]
if you go here
https://trilinos.org/packages/stk/
and look for docs you get a 404.  I think Jim is in charge of the website?

**Comment by jwillenbring** [comment]
@bmpersc should know about this too.

It appears that when STK split into classic and new, they stopped using the supported approach for generating Doxygen documentation for Trilinos packages. Tpetra did the same, and this is not surprising considering the level of documentation. The only way to resolve this within the current framework is to get STK to use the Trilinos supported mechanism. They would need a build_docs file and would need to change their directory structure. I don't know if they would be willing to do this. I have CC'ed Brent to see if he has advice on this. Given that this has gone unnoticed since 11.10, I suspect people don't go to Trilinos.org too often for STK documentation.

**Comment by jhux2** [comment]
> Given that this has gone unnoticed since 11.10, I suspect people don't go to Trilinos.org too often for STK documentation.

As a data point, this same request was made recently in Trilinos Users:  https://trilinos.org/pipermail/trilinos-users/2016-February/005368.html.

There's also an internal-only STK user's manual, but that may not have the detail that Matt wants.
