### ISSUE TITLE
MueLu: why do we need to call Kokkos::initialize() when using MueLu_Test_ETI.hpp?

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#1653]
@trilinos/muelu 

I got hit by the fact that I cannot run the MueLu Driver like this:
```
$ mpirun -np 4 ./MueDriver.exe --node=serial
```
when compiled with both OpenMP and Serial nodes. It results in
```
p=0: *** Caught standard std::exception of type 'std::runtime_error' :

 Constructing View and initializing data with uninitialized execution space
 Traceback functionality not available
```
Further debugging shows that OpenMP (and not Serial) is not initialized. Explicitly calling `Kokkos::initalize()` before `MPI_Global_Session` and `Kokkos::finalize()` at the end fixes that.

I remember there was a discussion on the topic at some point, but I can no longer find it.

**Comment by mhoemmen** [comment]
Tpetra's Nodes call `Kokkos::execution_space::initialize` if the execution space is not initialized, but they don't call `Kokkos::initialize`.  However, `Tpetra::initialize` calls `Kokkos::initialize`.

`Teuchos::GlobalMPISession` captures its command-line arguments for later use; I take advantage of this in Tpetra.

You might like to initialize Kokkos after MPI, so that MPI has the chance to bind processes correctly before Kokkos touches things.

**Comment by aprokop** [comment]
@mhoemmen Thanks for the explanation! So if #1376 was fixed, we won't need it, right?

**Comment by mhoemmen** [comment]
@aprokop wrote:
> So if #1376 was fixed, we won't need it, right?

Yes :-) .  There were some issues with #1376:

  1. Kokkos lacks a "global" `is_initialized` function; one can only ask if a specific execution space is initialized.
  2. Other folks advocated against Tpetra doing any Kokkos initialization.  See https://github.com/trilinos/Trilinos/issues/763 .

One could work around (1) by checking if the default execution space is initialized, since `Kokkos::initialize` always initializes the default execution space.  However, `Kokkos::initialize` does other things, like setting up Kokkos' profiling library.  One could check whether the latter has been set up, but it is possible to disable Kokkos' profiling library at configure time (some applications do, perhaps because it requires `dlopen`).

(2) is a social issue.  I understand arguments for and against.  I would recommend just initializing MPI and Kokkos yourself.  You can even do this in unit tests, by specifying a different unit test "main" .cpp file.  Tpetra will not double-initialize or double-finalize either MPI or Kokkos.

**Comment by jjellio** [comment]
Worth pointing out, you should init Kokkos is you ever expect anyone to pass kokkos command line arguments. The default initilizers most likely do not have access to argv/argc and therefore initialize as if nothing was present on the command line. I know that I have been bitten by this.  It is mostly relevant on Cuda, where you may need to set ndevices, or with OpenMP if you want Kokkos to see only a subset of the threads.

On the flip side, if a user ever uses Kokkos command line arguments, and you don't call initialize with argc/argv, those options will never be removed from argv and the Teuchos commandline parser will whine about unprocessed arguments. (That is, Kokkos init modifies argv/argc).

**Comment by aprokop** [comment]
@mhoemmen @jjellio Thanks a lot for the insight! If I were to document that somewhere, where would the best place be? Particularly, the comment about "first MPI, then Kokkos" for binding is probably unknown to a lot of people.

**Comment by mhoemmen** [comment]
@jjellio wrote:
> The default initializers most likely do not have access to argv/argc and therefore initialize as if nothing was present on the command line.

Tpetra itself will ask `Teuchos::GlobalMPISession` for command-line arguments, and imitate Kokkos' logic for removing them and applying their values.  However, that requires using GlobalMPISession.

**Comment by mhoemmen** [comment]
@aprokop wrote:
> Particularly, the comment about "first MPI, then Kokkos" for binding is probably unknown to a lot of people.

`Kokkos::initialize` could actually check that, and print a warning (on Process 0 only, otherwise people will be angry when they blow through disk capturing stderr on 1M processes ;-) ).

**Comment by jhux2** [comment]
@mhoemmen wrote:
> (2) is a social issue. I understand arguments for and against. I would recommend just initializing MPI and Kokkos yourself. You can even do this in unit tests, by specifying a different unit test "main" .cpp file. Tpetra will not double-initialize or double-finalize either MPI or Kokkos.

@aprokop wrote:
> Thanks a lot for the insight! If I were to document that somewhere, where would the best place be? Particularly, the comment about "first MPI, then Kokkos" for binding is probably unknown to a lot of people.

What about checking state in Tpetra and erroring out with a helpful error message, e.g., "Tpetra  does not do any Kokkos initializations.  Applications are responsible for this, i.e., calling Kokkos::initialize() after MPI is initialized."

**Comment by jhux2** [comment]
> What about checking state in Tpetra and erroring out with a helpful error message, e.g., "Tpetra does not do any Kokkos initializations. Applications are responsible for this, i.e., calling Kokkos::initialize() after MPI is initialized."

Of course, MueLu can also check state in the unit tests.

**Comment by mhoemmen** [comment]
@jhux2 wrote:
> What about checking state in Tpetra and erroring out with a helpful error message....

This is a backwards compatibility change, so we would need to wait until the next major release to add it.  We could add a warning, though!  Would that be better?

It seems like the issue is Kokkos and MPI, and thus more general than Tpetra.  This suggests that perhaps Kokkos should print the warning.  For example, many applications will want to use Kokkos before they ever get to the solver.

**Comment by jhux2** [comment]
> It seems like the issue is Kokkos and MPI, and thus more general than Tpetra. This suggests that perhaps Kokkos should print the warning. For example, many applications will want to use Kokkos before they ever get to the solver.

@mhoemmen I agree.

**Comment by jhux2** [comment]
See also Kokkos issue [1060](https://github.com/kokkos/kokkos/issues/1060).

**Comment by aprokop** [comment]
Fixed in MueLu. The follow up discussions in Kokkos and #1376.
