### ISSUE TITLE
Performance of Intrepid2 for PIC

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#167]
@trilinos/intrepid2 @rppawlo 

In PIC methods we have lagrangian particles which migrate throughout the system.  We have these particles with position x_i, velocity v_i.  We can then derive a current which is the J_i = q v_i(x_i).  This is a delta function, we will integrate J for the source of a Maxwell solve.  Since J is just a sum of delta functions this integration is nothing more than an evaluation of the basis function at the point x_i.

The current typically use the HCurl basis, but for electrostatics we use the HGrad basis..

What we need is a fast way to perform a basis evaluation.  

For example, if one wants the tet hcurl basis value at order 2 or higher one calls

Basis_HCURL_TET_In_FEM<Scalar, ArrayScalar>::getValues

which creates a temp array 
          ArrayScalar phisCur( scalarBigN , numPts );
and calls functions in a new basis functoin 
  Basis_HGRAD_TET_Cn_FEM_ORTH<Scalar,ArrayScalar > Phis_;

which in this constructor we create more temps.

```
      Phis_.getValues( phisCur , inputPoints , OPERATOR_VALUE );
```

which creates a field container of sfads 
    FieldContainerSacado::Fad::SFad<Scalar,3 > dZ( z.dimension(0) , z.dimension(1) );

```
FieldContainer<Sacado::Fad::SFad<Scalar,3> > dResult(card,np);
```

which calls tabulate recursively. 

Then once this is all done it multiplies some output with some local array coeffs_.

This chain skips some steps (I think their may be a human sacrifice in the code as well), but clearly this isn't really a performant call stack if I want to know what basis value is at point (3.1,4.5)...

What I need is a shallow call stack for this which doesn't allocate any memory and can be called on GPUs.  

What I've done in the past is to make local versions of this call stack and optimize it with stack vars and other tricks to speed it up.  It gave me a factor of 10x improvements on CPU and allowed me to run on GPU.

**Comment by kyungjoo-kim** [comment]
My response is inlined.

**Comment by bathmatt** [comment]
--> How do you use the high order basis functions ? The current Intrepid DOF enumeration does not allow to assemble element matrices correctly. Do you test only for one element ?

I figured out the numbering for higher order elements and use the correct numbering.  If you order the element nodes n0<n1<(n2 and n3) then your face dofs are anti-symmetric of each other, i.e, face dof 1 of element a is - FD2 of element b, and vice verse.  This will give you continuity of the field tangents.

--> Yes it does but you also understand the basic interface assumes that there is a list of points to eveluate together (not a single point) and for high order elements, the number of quadrature points grows quickly with O(p^3). 

Not in my case, the number of quadrature points is fixed and is 1 and does not grow.

 -> I understand that we should remove all allocation and the required workspace should be provided from the user. I presume that your deisred shallow call stack is just stripping the allocation (not shortening the workflow to construct the basis).

Since I only need 1 value I can greatly simplify things, remove loops and all temps.

 -> You mean the unit test on a single element, right ? Do you have any trick to run the code with multiple elements ?

On a real code with a real mesh.  I don't use quadrature points, I use particles, and they are not constant for an element.  This is the mismatch between the design of intrepid and my use case.

I understand that

**Comment by kyungjoo-kim** [comment]
Your use case is not well suited to the designed use cases in Intrepid.

1. You have a sinlge point to evaluate. Is this a generic feature in PIC (a single particle in a cell) ? Or Do we have a case that includes more than 1 particle in a cell ?

2. Since you evaluate on the the reference element, you can gather the required points for many different cells and evaluate once on the reference cell. After then, the values evaluated on the different points (associated with different cells) can be scattered to each element. Can this be an alternative solution ?

3. The temporary allocation should be replaced with subview where the subview is from preallocated workspace. We can possibly make a fixed workspace inside of the basis object and evaluate a chunk of points that fits on the workspace and batch the job.  This possibly remove the temporal allocation problem and fix the performance issue without limiting the use case to the single point evaluation case (From you explanation, I see that you can simplify the procedure with using local stack variables).

4. I still don't understand how the high order DOFs could be assembled in general. From my understanding, the lagrange points in the current high order elements is not consistently aligned to the faces local coordinates where the face parameterization is given from shards. Do you test the code for p = 4 , which provides non-trivial DOF enumeration for faces ?   Also you give an example for HCURL. HCURL needs sign flipping and currently the necessary sign modification is made on Panzer and Panzer does not deal with arbitrary order of elements.


Best,
Kyungjoo Kim



Center for Computing Research,
Sandia National Labs,
P.O. Box 5800, MS 1320,
Albuquerque, NM 87185-1320.

**Comment by bathmatt** [comment]
1: If a particle starts in an element and move to the neighbor, now we need to evaluate that neighbor element.  THere could be another thread already working that element.  The safest way is to do one at a time.

2:We can engineer a solution to gather several trajectories into a block and evaluate it.  However, it isn't an intuitive way to write the code and will require atomics and lot of clean up code and might be very error prone.

3: I simplified based on getting one point, then you know the size of arrays and if things are inlined it shouldn't be too much overhead vs a block of values.  

4: I only went to 3rd order.  Other errors become dominate at that order.  This was also outside of panzer

**Comment by kyungjoo-kim** [comment]
Possibly the best way to account for your use case is to use an internal workspace (fixed size) and iterate sequence of internal getValue when the number of points to evaluate is larger than workspace container. Once the kokkos dynamic rank view arrives, we can consider the modification of the basis objects.


Best,
Kyungjoo Kim


Center for Computing Research,
Sandia National Labs,
P.O. Box 5800, MS 1320,
Albuquerque, NM 87185-1320.

**Comment by kyungjoo-kim** [comment]
In the refactored version, we provide a sequential interface (single or handful amount of points evaluation that can be callable inside Kokkos functor) in the basis, which is suited for this particular use case.
