### ISSUE TITLE
Tpetra: shadow warnings

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#1672]
Did a clean build of trilinos this morning and get a ton of repeated shadow warnings with gcc7.2:

```
/ascldap/users/rppawlo/junk/ALBANY/Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrixFactory.hpp:351:131:   required from here
/ascldap/users/rppawlo/junk/ALBANY/Trilinos/packages/tpetra/core/src/Tpetra_Details_packCrsMatrix.hpp:473:12: warning: declaration of ‘gid’ shadows a previous local [-Wshadow]
         GO gid = col_map.getGlobalElement(lids_in[k]);
            ^~~
/ascldap/users/rppawlo/junk/ALBANY/Trilinos/packages/tpetra/core/src/Tpetra_Details_packCrsMatrix.hpp:442:14: note: shadowed declaration is here
     const GO gid = 0; // packValueCount wants this
              ^~~
/ascldap/users/rppawlo/junk/ALBANY/Trilinos/packages/tpetra/core/src/Tpetra_Details_packCrsMatrix.hpp:480:15: warning: declaration of ‘pid’ shadows a previous local [-Wshadow]
           int pid = pids_in[lids_in[k]];
               ^~~
/ascldap/users/rppawlo/junk/ALBANY/Trilinos/packages/tpetra/core/src/Tpetra_Details_packCrsMatrix.hpp:447:15: note: shadowed declaration is here
     const int pid = 0; // packValueCount wants this
               ^~~
```

**Comment by ibaned** [comment]
@trilinos/tpetra @tjfulle @mhoemmen This is very closely related to #1666 (basically one of these popped up yesterday too. It looks like this is a systematic issue, where the conventional use of `packValueCount` is claiming symbols that are better used for other purposes, and these warnings are being repeatedly introduced as code is modified. I once again propose that the common-case definition of `PackTraits` allow calling `packValueCount` with no arguments.

**Comment by tjfulle** [comment]
Thanks @rppawlo!  I believe these warnings will be resolved with PR #1665

**Comment by mhoemmen** [comment]
@ibaned wrote:
> I once again propose that the common-case definition of `PackTraits` allow calling `packValueCount` with no arguments.

I'm OK with this, as long as we specialize PackTraits so that this zero-argument definition only exists for built-in types.  It's too easy to break Stokhos otherwise.

`PackTraits` is really supposed to be a known-thread-safe replacement for `MPI_Pack`, `MPI_Pack_size`, etc.  I think `MpiTypeTraits` already has the optional zero-argument overload mapping from a type (e.g., `Scalar`, `GO`) to an `MPI_Datatype` instance.  Since `MPI_Pack_size` takes an `MPI_Datatype` instance, not an instance of the thing to pack, it seems like we could refactor `PackTraits` and `MpiTypeTraits` accordingly.  The only issue is that `MPI_Datatype` is overkill for the common case:

  - Only packing and unpacking built-in types (`double`, `long long`, etc.)
  - All processes have the same bit representation of built-in types (e.g., no endian issues; types like `long double` and `long` have the same lengths and representations)

In the common case, it's perfectly fine to `memcpy` bytes into or out of a `char*` buffer, and this is perfectly thread safe (C++11 / C99 promises `memcpy` is thread safe; `memcpy` works in CUDA device code on a single thread, as of CUDA 6.0).  Any use of `MPI_*` in a thread-parallel context technically requires `MPI_THREAD_MULTIPLE`, and will only work on host.  That's why we don't use `MPI_Pack` etc.

Anyway, I would welcome feedback about how to refactor `PackTraits` etc. to be efficient and easy to use, without breaking Stokhos.

**Comment by ibaned** [comment]
Stokhos seems to have its own template specialization of `PackTraits`, so as long as that one is left alone and is visible when packing is done with Stokhos types, then even if we modify the common-case `PackTraits::packValueCount` in Tpetra to work with no arguments, it should still give a compile error if we try to pass no arguments to `packValueCount` for a Stokhos type, because the specialized version doesn't allow it. I don't think it becomes any more dangerous than it is now.

**Comment by tjfulle** [comment]
`packValueCount` is only used in a few places and can be made to take zero arguments.  The Stokhos specialization would need to be modified accordingly, since it calls the default version.  The unpacking work I am currently doing is directly related, so I can make these updates when I am done chasing down the last test failure.

**Comment by ibaned** [comment]
To ease the transition, we can have it take one or zero, for example with a default argument or just a separate overload.

**Comment by rppawlo** [comment]
Thanks @tjfulle ! I usually just ignore most warnings, but shadow warnings are usually more serious so figured I'd report it.

**Comment by mhoemmen** [comment]
@tjfulle This is a quick fix, so I'll just take care of the shadow warnings for now.  Sorry if that causes merge drama :-) .

**Comment by tjfulle** [comment]
@mhoemmen , it's already taken care of in #1665 too

**Comment by mhoemmen** [comment]
Sorry @tjfulle -- actually my internet is a little weird today, so I should un-take this :-) .

**Comment by mhoemmen** [comment]
Fixed in develop; thanks @ibaned !
