### ISSUE TITLE
Tpetra's CMake should check & require Kokkos_ENABLE_Cuda_Lambda=ON

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1682]
@trilinos/tpetra @tjfulle 

Kokkos used to enable `KOKKOS_LAMBDA` purely at build (not configure time), as a function of `CUDA_VERSION`.  Recently, Kokkos changed to require setting a CMake option to enable lambdas.  Tpetra requires that `KOKKOS_LAMBDA` work, so it would make sense for Tpetra to check at configure time whether that CMake option is enabled.

This currently only matters for CUDA builds.

**Comment by tjfulle** [comment]
There also seems to be a disconnect between `c++11` and `lambda` options.  Specifically, to compile `Kokkos` with `KOKKOS_LAMBDA` enabled, the CMake option `Kokkos_ENABLE_LAMBDA=ON` **and** `--expt-extended-lambda` must be added to `CMAKE_CXX_FLAGS`.  But, if `--expt-extended-lambda` is added to `CMAKE_CXX_FLAGS`, then `-std=c++11` must also to avoid configure time errors.  It would seem that these last two `CMAKE_CXX_FLAGS` should be implied by `Kokkos_ENABLE_LAMBDA=ON` and `Trilinos_ENABLE_CXX11=ON`.

**Comment by csiefer2** [comment]
Is this related to the CUDA 8 transition?

**Comment by mhoemmen** [comment]
@csiefer2 No.  You need the options with both CUDA 7.5 and with CUDA 8.

**Comment by tjfulle** [comment]
@mhoemmen, is the issue larger than Tpetra?  For example, if `Kokkos_ENABLE_LAMBDA` is on, shouldn't TriBITs make sure the appropriate `CMAKE_CXX_FLAGS` are set?  Likewise, if `Trilinos_ENABLE_CXX11=ON`, it seems unnecessary to also manually add `-std=c++11` in `CMAKE_CXX_FLAGS`.  @bartlettroscoe ?

**Comment by mhoemmen** [comment]
@tjfulle I'm hoping that all these lambda flags are a temporary measure, and that once we actually need to deploy GPU-enabled solvers for serious production work, everything will just automatically happily build and run with the default options.  This could be utter fantasy, though ;-) .

**Comment by bartlettroscoe** [comment]
> Likewise, if `Trilinos_ENABLE_CXX11=ON`, it seems unnecessary to also manually add `-std=c++11` in `CMAKE_CXX_FLAGS`.

That is correct.  There are configure-time checks that will select the right option to use to enable C++11. or you can manually override the compiler options using `-D Trilinos_CXX11_FLAGS="<compiler flags>"`.  See:

* https://trilinos.org/docs/files/TrilinosBuildReference.html#enabling-support-for-c-11

**Comment by tjfulle** [comment]
@bartlettroscoe, right, but if `--expt-extended-lambda` is added to `CMAKE_CXX_FLAGS` I have observed that the configure fails unless `-std=c++11` is *also* added - regardless of the value of `Trilinos_ENABLE_CXX11` or `Trilinos_CXX11_FLAGS`

**Comment by bartlettroscoe** [comment]
@tjfulle,

> right, but if `--expt-extended-lambda` is added to `CMAKE_CXX_FLAGS` I have observed that the configure fails unless `-std=c++11` is *also* added - regardless of the value of `Trilinos_ENABLE_CXX11` or `Trilinos_CXX11_FLAGS`

I would have to see the full compiler commandline (which you can see with `make VERBOSE=1 <some_target>` to know for sure what is happening.

**Comment by ibaned** [comment]
This needs to be implemented soon. Existing CUDA builds of Trilinos are starting to fail because of the increasing use of lambdas while these builds don't have the proper configure options (see e.g. #1717). Users should get a configure-time error explaining that Tpetra requires certain lambda options, rather than getting down to an obscure compile error at the first lambda.

**Comment by tjfulle** [comment]
@bartlettroscoe, maybe this will help.  If I configure Trilinos (on `ride.sandia.gov`) with

```
-D Trilinos_ENABLE_CXX11:BOOL=ON
-D Kokkos_ENABLE_LAMBDA:BOOL=ON
```

and the following flags (see [Building with CUDA Support](https://trilinos.org/about/documentation/building-with-cuda-support/))

```
 CMAKE_CXX_FLAGS="-arch=sm_60 -lineinfo  \
 -Xcudafe --diag_suppress=conversion_function_not_usable \
 -Xcudafe --diag_suppress=cc_clobber_ignored \
 -Xcudafe --diag_suppress=code_is_unreachable"
```

Trilinos will configure without error but then a build error of the type described in #1717 occurs.  The build error suggests adding `--expt-extended-lambda` to the compiler command.  Ok, so I add `--expt-extended-lambda` to `CMAKE_CXX_FLAGS`.  Then I get configure time errors:

```
 Building CXX object CMakeFiles/cmTC_756d1.dir/testCXXCompiler.cxx.o

/home/projects/pwr8-rhel73-lsf/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/bin/mpicxx
  -arch=sm_60 -lineinfo --expt-extended-lambda -Xcudafe
  --diag_suppress=conversion_function_not_usable -Xcudafe
  --diag_suppress=cc_clobber_ignored -Xcudafe
  --diag_suppress=code_is_unreachable -o
  CMakeFiles/cmTC_756d1.dir/testCXXCompiler.cxx.o -c
  /home/tjfulle/Developer/VCS/github.com/tjfulle/Trilinos/develop/CHECKIN/gcc-5.4.0_cuda-8.0.44-test/CMakeFiles/CMakeTmp/testCXXCompiler.cxx



  /home/projects/pwr8-rhel73-lsf/cuda/8.0.44/bin/../targets/ppc64le-linux/include/cuda_runtime.h:133:29:
  error: template argument 1 is invalid

   #if defined(__cplusplus) && !defined(__CUDACC_RTC__)
                               ^

  /home/projects/pwr8-rhel73-lsf/cuda/8.0.44/bin/../targets/ppc64le-linux/include/cuda_runtime.h:138:32:
  warning: variadic templates only available with -std=c++11 or -std=gnu++11
```

Finally, adding `-std=c++11` to `CMAKE_CXX_FLAGS` gets by the configure and compiler errors.

It seems that if `-D Trilinos_ENABLE_CXX11:BOOL=ON` and `-D Kokkos_ENABLE_LAMBDA:BOOL=ON` are specified, no further modifications of `CMAKE_CXX_FLAGS` should be necessary.

CC: @ibaned, @mhoemmen

**Comment by tjfulle** [comment]
Forgot to add, `-D Trilinos_CXX11_FLAGS="<compiler flags>"` also results in failure for the previous configure time test - the options must by added to `CMAKE_CXX_FLAGS`

**Comment by tjfulle** [comment]
And, perhaps related, on my `ride` builds using the aforementioned `CMAKE_CXX_FLAGS`, the make log file is inundated with

```
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
```

While, benign, there are thousands of them and meaningful warnings (e.g., #1672) get lost.

**Comment by mhoemmen** [comment]
@tjfulle `Kokkos_ENABLE_LAMBDA` is not the right CMake option.  You want `Kokkos_ENABLE_Cuda_Lambda`.

**Comment by tjfulle** [comment]
@mhoemmen , right, it was a typo

**Comment by mhoemmen** [comment]
I changed Tpetra's CMake logic, to check that `Kokkos_ENABLE_Cuda_Lambda` is `DEFINED` and `ON`.  I'm running the remote check-in tests now.

**Comment by tjfulle** [comment]
@mhoemmen , I'd still like to get @bartlettroscoe's feedback RE why `CMAKE_CXX_FLAGS` need to be set in addition to the other flags.

**Comment by bartlettroscoe** [comment]
@tjfulle 

>  I'd still like to get @bartlettroscoe's feedback RE why `CMAKE_CXX_FLAGS` need to be set in addition to the other flags.

Like I said [above](https://github.com/trilinos/Trilinos/issues/1682#issuecomment-327595175):

"I would have to see the full compiler commandline (which you can see with make `VERBOSE=1 <some_target>` to know for sure what is happening.

That is what you need to focus on.  After we know the actual compiler comandline being used, then we can figure out what is there now, how it got there, and what it needs to look like to get this to work.  It is that simple.

**Comment by tjfulle** [comment]
@bartlettroscoe , the error is during configure, not make.  The compiler line that is used is in my comment above, repeated here:

```
Building CXX object CMakeFiles/cmTC_756d1.dir/testCXXCompiler.cxx.o

/home/projects/pwr8-rhel73-lsf/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/bin/mpicxx
  -arch=sm_60 -lineinfo --expt-extended-lambda -Xcudafe
  --diag_suppress=conversion_function_not_usable -Xcudafe
  --diag_suppress=cc_clobber_ignored -Xcudafe
  --diag_suppress=code_is_unreachable -o
  CMakeFiles/cmTC_756d1.dir/testCXXCompiler.cxx.o -c
  /home/tjfulle/Developer/VCS/github.com/tjfulle/Trilinos/develop/CHECKIN/gcc-5.4.0_cuda-8.0.44-test/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
```

**Comment by bartlettroscoe** [comment]
@tjfulle,

> the error is during configure, not make. The compiler line that is used is in my comment above, repeated here

Okay, thinks for clarifying.  I think we might have a chicken and egg problem here.  Can you please attach your full cmake configure command line and the full STDOUT from that cmake configure?  I need to see that to confirm my suspicion.

**Comment by mhoemmen** [comment]
I pushed a fix to develop.  Tpetra's CMake logic now checks `Kokkos_ENABLE_Cuda_Lambda`.  It does _not_ check `CMAKE_CXX_FLAGS` for any of the required options, though the error message does remind users to add the `--expt-extended-lambda` option.

**Comment by tjfulle** [comment]
@bartlettroscoe , attached is the configure script and log file.

[do-configure-ride.sh.txt](https://github.com/trilinos/Trilinos/files/1293545/do-configure-ride.sh.txt)

[configure.out.txt](https://github.com/trilinos/Trilinos/files/1293546/configure.out.txt)

**Comment by bartlettroscoe** [comment]
> attached is the configure script and log file.

Okay, thanks for that.  This is what I suspected.  This is a a bit of a chicken and the egg problem.  The issue is that TriBITS has logic for automatically determining what compiler options to use to enable C++11, but it only can run those **after** the C++ compiler is found (which also checks if it works).  It assume the raw compiler can compile that silly little C++ program that CMake generates for it.  You can see the order for "Check for working CXX compiler" and the check for the right C++11 option in the standard CI build, for example, at:

* https://testing.sandia.gov/cdash/viewConfigure.php?buildid=3102532

which shows:

```
-- Check for working CXX compiler: /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.8.4/openmpi/1.6.5/bin/mpicxx
-- Check for working CXX compiler: /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.8.4/openmpi/1.6.5/bin/mpicxx -- works
[...]
-- Search for C++11 compiler flag ...
-- Performing Test CXX11_FLAGS_COMPILE_RESULT_0
-- Performing Test CXX11_FLAGS_COMPILE_RESULT_0 - Success
-- Successful C++11 flag: '-std=c++11'
```

So that is the problem.

But we can't just hard-code the C++11 flag `-std=c++11` because some compilers don't use that compiler option (which is why TriBITS was extended to perform this behavior many years ago).

I think if we talked with Kitware about this, they would say that the compiler we are trying to use is fundamentally broken if it can't compile that little `testCXXCompiler.cxx` file that CMake (not TriBITS) generates without needing extra commandline options.

And so we have a problem here.  We can't do the automate check to find the right option to enable C++11 compiler and we can't even verify the compiler without knowing the right C++11 option.

Since this is a bit of a strange situation (that I would not expect to exist in that compiler long term), I would say to just hack it and add `-std=c++11` to `CMAKE_CXX_FLAGS` and the document why you had to do that hack (and just point to this issue comment).  Or, if you want something a little more clean, you could set `-DTrilinos_CXX11_FLAGS=-std=c++11` as described at:

* https://trilinos.org/docs/files/TrilinosBuildReference.html#enabling-support-for-c-11

But I think we would need to extend TriBITS in that case to add `${${PROJECT_NAME}_CXX11_FLAGS}` to `CMAKE_CXX_FLAGS` **before** `ENABLE_COMPILER(CXX)` is called by TriBITS.  Is that worth it in this case?  If you think that is worth it, I can add that to TriBITS and snapshot into Trilinos.

**Comment by crtrott** [comment]
Hi folks,

the core problem for the CMAKE_CXX_FLAGS is that --expt-extended-lambda can only be added if the c++ standard is 11 since Lambdas don't exist before that. Now CMake is using the user defined flags during its "Does the compiler work" check before adding the C++11 flag. 

So what should happen is: either add the C++11 flag right away to everything, or don't use the user provided flags during the basic "does this compiler work" test. Otherwise how I am supposed to add a flag to a cmake build which requires the standard to be c++11??

Adding -std=c++11 to the CMAKE_CXX_FLAGS solves that issue partly (because now this expt-extended-lambda is not alone anymore). But it adds the issue that I now get the std flag twice. That in turn makes some compilers fail (including nvcc) which only allow this definition to appear once. nvcc_wrapper catches that right now, gives you a warning and continues with using the first encountered std setting. But again that is not a good way of doing this. 

One alternative is to define the 
```
-D Trilinos_CXX11_FLAGS="--expt-extended-lambda -std=c++11"
```
but that is somewhat esoteric for most users.

**Comment by crtrott** [comment]
What I think should happen is:
* Check whether compiler works without using CMAKE_CXX_FLAGS 
* Figure out C++11 flags
* Check again whether compiler works with C++11 flag and CMAKE_CXX_FLAGS

Only issue: the first thing might not work if there are required architecture flags, but if it not actually runs the code example it should probably work.

**Comment by tjfulle** [comment]
I'll probably adopt using @crtrott's proposed alternative:

```
-D Trilinos_CXX11_FLAGS="--expt-extended-lambda -std=c++11"
```

But, a better long term solution should be worked out as use of lambdas becomes more common.

**Comment by bartlettroscoe** [comment]
> What I think should happen is:
> 
> *  Check whether compiler works without using CMAKE_CXX_FLAGS

I just checked and we don't seem to be able to control whether CMake will use CMAKE_CXX_FLAGS while running ENABLE_LANGUAGE().  If it is set, it gets used, period.  I guess we could copy it and then set CMAKE_CXX_FLAGS to empty before calling ENABLE_LANGUAGE() and then set CMAKE_CXX_FLAGS back again but that seems like a hack.  (We already get criticized enough for messing around with raw CMake behavior.)  Short of doing that hack, I think setting:

```
-D Trilinos_CXX11_FLAGS="--expt-extended-lambda -std=c++11"
```
is the only viable solution that I can think of.  I think that is as logical as anything.

**Comment by etphipp** [comment]
Why won't this work:

- User provides no c++11/lambda flags in CMAKE_CXX_FLAGS or Trilinos_CXX_FLAGS
- CMake does the regular check if the C++ compiler works (as it does now)
- Tribits does the check for the c++11 flag if c++11 is enabled, and adds the right flag to CMAKE_CXX_FLAGS (as it does now)
- Tribits then adds --expt-extended-lambda to CMAKE_CXX_FLAGS if Kokkos_ENABLE_Cuda_Lambda=ON and c++11 was enabled (and errors out if c++11 was not enabled or the flag couldn't be determined).  It could also check that it works by compiling a test code that uses a lambda.

From that point on you have both flags and the user didn't have to set either of them.

**Comment by tjfulle** [comment]
I like @etphipp suggestion

**Comment by crtrott** [comment]
Yeah thats a good idea. If you guys agree to this we make it default on for CUDA 7.5 and 8.0.

**Comment by mhoemmen** [comment]
@crtrott I like @etphipp 's suggestion.

**Comment by mhoemmen** [comment]
I would like to state for the record:
```
$ cd Trilinos/packages && grep -R KOKKOS_LAMBDA * | wc -l
233
$ cd kokkos && grep -R KOKKOS_LAMBDA * | wc -l
71
$ cd ../kokkos-kernels && grep -R KOKKOS_LAMBDA * | wc -l
37
$ cd ../tpetra && grep -R KOKKOS_LAMBDA * | wc -l
30
```
Tpetra has been conservative about `KOKKOS_LAMBDA`, compared to other packages.

**Comment by tjfulle** [comment]
A more detailed accounting of `lambda` usage:

Package | `lambda`s (including tests and examples) | `lambda`s (excluding tests and examples)
--------|-----------|-----------------------------------------
intrepid | 1 | 1
intrepid2 | 2 | 0
kokkos | 71 | 9
kokkos-kernels | 37 | 0
muelu | 24 | 5
phalanx | 9 | 9
sacado | 6 | 6
shylu | 13 | 0
stk | 40 | 0
tpetra | 30 | 16
total | 233 | 46

**Comment by crtrott** [comment]
The important question is whether the LAMBDA usage is protected appropriately, and whether the code still works if you don't enable it. But if Trilinos makes the decision to use an experimental feature by default for CUDA that is fine with me. You just need to make that decision, and make sure the code works if it is turned off, or not allowing it to be turned off.
