### ISSUE TITLE
Tpetra Configures But Tests Do Not Build on IBM XL POWER8LE with INT_INT and INT_LONG in ETI

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#173]
Building TPetra tests with IBM XL with INT/INT and INT/LONG both enabled causes a multiple definition failure during tests (see below).

```
../../src/libtpetra.a(Tpetra_DistObject_DOUBLE_INT_LONG_OPENMP.cpp.o):(.data+0x1230): multiple definition of `_ZNK6Kokkos4Impl11ParallelForINS0_9ViewRemapINS_4ViewIPmNS_6OpenMPEvvNS0_11ViewDefaultEEENS3_IS4_NS_11LayoutRightENS_6DeviceIS5_NS_9HostSpaceEEEvS6_EELj1EEENS_11RangePolicyIJS5_EEES5_E16execute_scheduleINS_6StaticEEENSt9enable_ifIXsr3std7is_sameIT_SI_EE5valueEvE4typeEv$$OL$$5RVL420A'
../../src/libtpetra.a(Tpetra_DistObject_DOUBLE_INT_INT_OPENMP.cpp.o):(.data+0x1230): first defined here
```

**Comment by crtrott** [comment]
How wonderful. My understanding is a build, fix, build cycle takes 12 hours for this?

**Comment by nmhamster** [comment]
Yes. The issue is that I don't specify what I want TPetra to use, so this is coming out of the box from standard configuration procedure. You're lucky I got this down from 3.5 days in my few attempts.

**Comment by crtrott** [comment]
:+1:  

Ok so what I don't understand is: in this case I expect multiple definitions of that functions, since it is a template function which is not explicitly instantiated anywhere else. Both instantiations of DistObject will use that same function and thus will have it in their object file. Isn't that supposed to work??

**Comment by nmhamster** [comment]
I haven't dug into this sufficiently yet but my initial thought is that the underlying type is essentially the same (`int == long`) so as you say, they are compiled down to the same function signature and then appear twice because the objects are both in the `libtpetra.a` when the test gets linked. I'm going to do a disable of `INT_LONG` and then explicitly enable `INT_INT` and `INT_LONG_LONG`.

**Comment by mhoemmen** [comment]
If int == long, I mean literally if long is just a typedef of int and not a distinct type that happens to have the same size, would it make sense for Tpetra just to force INT_LONG OFF?

**Comment by nmhamster** [comment]
I'm running that now and I'll let you know. The issue here is that without specifying anything in the CMake the configuration decided what to do itself and this was the result. As you know I'm not a fan of having to go through every possible incantation that CMake may need to get it right but in this instance I think it may be all we have in the interim.

**Comment by mhoemmen** [comment]
Thanks Si :-)  It would make a lot of sense to automate this.  I've never encountered a compiler where long was a typedef of int (vs. a separate type which might happen to have the same bit representation), else I would have done it myself.  That may even violate the standard, but it's not hard to work around in CMake.

**Comment by nmhamster** [comment]
I'm trying to understand more about our options here. The problem is that it takes so long to get a reconfigure and recompile. The TPetra ETI objects take in excess of 8 hours to link for test and its there where I get the failure. I will update you on this issue as I get more information.

**Comment by crtrott** [comment]
I am not sure that it would be legal for long being a typedef of int. I am pretty sure those have to be distinct types, even if they are the same size.

**Comment by mhoemmen** [comment]
@crtrott My internet's a little weird at the moment or I would actually check the standard.  Regardless, it's not hard to add a CMake test that builds a little program to check the value of `std::is_same<long, int>::value`.  INT_LONG should not actually be enabled by default -- I much prefer `long long` because the standard guarantees it has at least 64 bits.

btw, for others reading this: The reason Tpetra doesn't use `int64_t`, `int32_t`, etc. is because those are typedefs and not actual types.  It could be that `int64_t` is a typedef of `long`, or a typedef of `long long`.  That makes it hard to do full specializations (even with ETI OFF -- this is not just an ETI issue) and ensure correct linking, esp. when users mix int*_t typedefs with built-in types.  We've dealt with this issue before in Teuchos as well, and you might notice some comments in there talking about it.

**Comment by mhoemmen** [comment]
@nmhamster What's the story here?  Does this work now?

**Comment by mhoemmen** [comment]
This is currently in the works.  Kokkos also encounters this issue in its unit tests.  @nmhamster knows and they are working out a test case to give to the compiler folks.

**Comment by jjellio** [comment]
I was able to dodge this in Tpetra by increasing the threshold for inlining (250 is overkill, 100 may work) for specific ETIs.

**Comment by mhoemmen** [comment]
This seems to be related to recent XL build issues that manifest also in Kokkos unit tests.
