### ISSUE TITLE
md5 checksum changed for 12.10.1

### ISSUE THREAD

**Issue by davydden** [trilinos/Trilinos#1737]
just noticed that `md5` checksum changed for https://github.com/trilinos/Trilinos/archive/trilinos-release-12-10-1.tar.gz from `40f28628b63310f9bd17c26d9ebe32b1` to `667333dbd7c0f031d47d7c5511fd0810`. Can you please confirm that this is a desired change and the tarball was not compromized.

**Comment by aprokop** [comment]
@trilinos/framework @jwillenbring @bmpersc

**Comment by bmpersc** [comment]
@davydden I don't know of any thing that has changed on the 12.10 branch. Looking at the log in github it does look like it is still at the 12.10.1 tag. Our official release is not done through github's downloads so I'm not really familiar with what could have happened. There are a couple things that spring to mind as possibilities. I assume you've already ruled this out, but I want to say the obvious possibility that the download was corrupted somehow. The other thing that comes to mind is that github might have changed something with how they tar tags up. Maybe they changed the compression ratio?

The only other thought that comes to mind would be to diff the contents of the tarballs and see what comes up. That might at least shed light on why the md5 is different.

Just for fun I decided to download the trilinos tarball from the link you gave and found that I have the same md5 sum that you are seeing now. I don't have a copy from earlier so I can't really compare the md5 sum to. At least that pretty much completely precludes a corrupted download.

**Comment by davydden** [comment]
> I assume you've already ruled this out, but I want to say the obvious possibility that the download was corrupted somehow.

I am quite certain that this is not the case. I see it on my mac, and on the cluster. My colleague told me about the whole issue while building `trilinos` last evening.

> The other thing that comes to mind is that github might have changed something with how they tar tags up.

with this I have no experience. 

> diff the contents of the tarballs

I only have the new one :smile:

**Comment by aprokop** [comment]
Can somebody diff the tarball with the tip of 12.10.1 branch?

**Comment by bmpersc** [comment]
There was someone here working with spack about 6 months ago, I'll ask and see if he has a tarball from trilinos from that time. Maybe it will show us something. If he doesn't I think I'd like to change the direction of this from "why did the md5 sum on github change" to  "can spack use the official release tarballs of Trilinos" instead. Let me see what we have here before we worry about that too much.

**Comment by bmpersc** [comment]
@davydden I just spoke with the person I mentioned above and they did not have a tarball of Trilinos so we won't be able to do any comparisons.

So at this point I think we need to decide what is the path forward. I'm not real keen on the idea of spending a lot of time hunting down an issue in a process we don't control and don't use as part of our official releases.

There are a couple low cost paths forward: 

1. I assume that spack is only using the md5 to verify the download which I'm sure is an error right now. However, spack could just update the md5 for Trilinos. As long as the Trilinos spack is downloading from github still works, which I suspect it will, then things are fixed. It looks like this option is what you have in the linked spack issue.

2. Switch spack to download the official Trilinos release tarballs instead of using github. That is something we have control over so if something changes we will probably know what and we can do something about it. The downside is that the direct download urls aren't readily available, but we can work with you to get them I'm sure. Another benefit is that the official Trilinos release tarball does contain packages that are external to the Trilinos repo. However, I'm skeptical that spack is building those packages.

Both of these options require changes to spack and not Trilinos so really spack needs to decide what is the better solution. Or if you feel this is important enough to continue investigating we can look into it more. However, before we go that route I'd like @maherou and/or @jwillenbring to have some say in this.

**Comment by davydden** [comment]
> 1. ... It looks like this option is what you have in the linked spack issue.

correct.

> 2. Switch spack to download the official Trilinos release tarballs instead of using github.

We switched to downloading from github a year ago https://github.com/LLNL/spack/commit/aca8576de4f92498ab15f2a8ca0b0409205520b4 . The reason was that Trilinos servers were down for a considerable amount of time https://github.com/LLNL/spack/issues/1578 . IIRC [homebrew](https://github.com/Homebrew/homebrew-science/blob/master/trilinos.rb) switched to github downloads at the same time.

Trilinos package in Spack is already complicated but appears to be stable and polished over time. For the sake of error-free build, I think it's better to keep things as-is and download from GitHub tagged releases.

> Or if you feel this is important enough to continue investigating we can look into it more

The change of checksum appears to be harmless so i don't think we need to spend any more time hunting the origin of the change. Thanks for your time and prompt response.

**Comment by aprokop** [comment]
It seems that the checksum change was github-wide. [Spack](https://github.com/LLNL/spack/issues/5411) and other package managers are dealing with the problem.

**Comment by bmpersc** [comment]
@aprokop That is good to know, in some ways. It lends some credence to the theory that github changed the way they make the tarballs. It is unfortunate in the long run since no project on github can control those tarballs and changing the md5 breaks anyone doing the smart thing which is to verify that the download was correct.
