### ISSUE TITLE
Stokhos: Overload Kokkos::deep_copy specializations to take execution space instance

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1778]
@trilinos/stokhos 

See #1776 comments.  @etphipp wrote: "I should add an overload [of Kokkos::deep_copy specializations for Stokhos and Sacado Scalar types] that takes the execution space as an argument though."

**Comment by etphipp** [comment]
I just pushed a change that adds the overloads.  However if you look in Kokkos, the corresponding overloads actually ignore the execution space argument, so that's what I had to do here (because Stokhos provides a partial specialization of the ViewFill<> implementation, and so the execution space would have to be added there for me to use it here).

**Comment by mhoemmen** [comment]
@etphipp I added that issue to Kokkos: https://github.com/kokkos/kokkos/issues/1127 Thanks for working on this! :-D
