### ISSUE TITLE
Framework: Windows Build Not Posting To Dashboard

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#1829]
See title

**Comment by bmpersc** [comment]
@csiefer2 I have gotten the machine back up and running. The jenkins process had stopped running. I'm not sure why and I thought I'd put in some things to handle a lot of the ways it could stop so that it would be restarted automatically. However, it looks like those fail safes either don't handle this case or didn't work. I'll have to look into that further. But, for now the tests are currently running again.
