### ISSUE TITLE
unsigned/signed comparison in CrsMatrixUtils_UnitTests.cpp

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#1854]
This shows up when using warnings-as errors. (see https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3164856 ) Not sure if it would be better to use size_type from the template class or change the template to always return size_t.

**Comment by mhoemmen** [comment]
@trilinos/xpetra @trilinos/muelu

**Comment by tawiesn** [comment]
One can use, e.g.,
`for(decltype(CRS_rowptr.size()) row = 1; row < CRS_rowptr.size(); ++row)`
 to avoid the problem

**Comment by tawiesn** [comment]
@lucbv

**Comment by lucbv** [comment]
Using `decltype()` is always an option but it does not look optimal since in that case we do not really know what type we end-up using and we could have to propagate this `decltype()` through large amount of code.
On the other hand I could do a `static_cast<size_t>()` on the return value of the ArrayView.

**Comment by mhoemmen** [comment]
Would use of `decltype` break Epetra-only and Windows builds?  Otherwise, I don't mind it.  Better yet, the local number of rows (plus 1) should always fix in LocalOrdinal, so you could just cast everything to LocalOrdinal.

**Comment by tawiesn** [comment]
@mhoemmen That is a good point. If i remember correctly, we've decided to allow C++11 code in MueLu (and Xpetra) as long as it does not break the Epetra-only (Windows) build. I would expect, that the Microsoft compilers support decltype. I never checked the details but i thought the problem with the Epetra build for Windows is that Kokkos uses even more modern syntax that is not supported by the Microsoft compilers.

**Comment by tawiesn** [comment]
@lucbv I get the point. It would be good to know the exact type that we are using. But if you know it you should also use it. decltype might be more "flexible" than static_casts which i don't find very elegant...

**Comment by lucbv** [comment]
Visual studio is supporting `decltype` since their 2010 version so it should be safe to assume that the windows build will be fine.
I am not sure why it would break the Epetra only builds. Are there specific programming language restrictions for the Epetra stack?
I pushed 844920d to fix the issue on ascic141, I will monitor the Epetra only build on the muelu dashboard

**Comment by prwolfe** [comment]
Thanks for the quick response!

**Comment by mhoemmen** [comment]
> I never checked the details but i thought the problem with the Epetra build for Windows is that Kokkos uses even more modern syntax that is not supported by the Microsoft compilers.

There are a few issues.  In terms of C++, Kokkos doesn't use anything newer than C++11.  However, Kokkos has some compiler-specific paths, and doesn't appear to have one for Windows.
