### ISSUE TITLE
There isn't an '@trilinos/<packagename>' tag for all packages

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#1872]
@trilinos/framework 

Since I'm keeping an eye on the nightlies, etc. when the clean track goes red I'll probably put in a ticket if there doesn't appear to be one about that already.  I've noticed that there isn't an @trilinos/<package> tag for all the packages set up.  (i.e., today there is a test failing in FEI and there is no @trilinos/fei tag)

It'd be nice if we had one for every package.  If packages have no 'team' then perhaps to the owner or someone who is best able to look at a package and know what's going on in it?

**Comment by jmgate** [comment]
Any movement on this?  I'm working on #2013, and it'd be useful if every package had a team attached that we could @mention.

**Comment by jmgate** [comment]
Actually I'm just going to go ahead and set these up.

**Comment by jmgate** [comment]
Most packages now have a trilinos team associated with them.  The sole member for each team was the point of contact listed on the trilinos.org package page.  The packages that do not yet have teams are:
* fei:  We can create this and add Alan Williams (@alanw0; william@sandia.gov), but he needs to be added to the trilinos organization first.  @jwillenbring, can you take care of adding him to trilinos?
* galeri:  Contacted marzio.sala@gmail.com to see who the point of contact should be here.
* meshinggenie
* minitensor
* pike
* ThreadPool
* trilinoscouplings (email to trilinoscouplings-developers@sandia.gov bounced)
* trios (email to trios-developers@software.sandia.gov didn't go through because I'm not a member of that group)

meshinggenie&ndash;ThreadPool don't have trilinos.org pages, so I wasn't sure who the point of contact should be.  Anyone have any ideas?
