### ISSUE TITLE
Trilinos Windows Build did not post last night

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#1878]
Again

**Comment by ibaned** [comment]
Link please? I guess I'm not good a navigating CDash...

**Comment by ibaned** [comment]
oooh sorry you said "post" not "pass"

**Comment by csiefer2** [comment]
NP.

@bmpersc asked me to file an issue each time this happens so we can have some record of the frequency of this particular problem.  He's out of the office today, so we'll need to wait 'til Monday.

**Comment by ibaned** [comment]
This seems to be part of a larger problem today, see #1880

**Comment by bmpersc** [comment]
@csiefer2, it looks like this is a new problem. According to the logs the jenkins slave has stayed up and has been running the job since 10/16/2017. it looks like sometimes the run is making it to the dashboard as an update error and sometimes it does not. It looks like there is an error during the update, but it is unclear what has changed recently to cause this error. I'm currently trying a completely clean build to see if this was just a bad state for the workspace. But, that is a bit of a shot in the dark. If that doesn't work I'll need to dig into things more to see why the update is failing.

**Comment by bmpersc** [comment]
@csiefer2, the clean build did not help, however, it did give a more useful error message. Apparently the clone/pull for each build is timing out on the slave which leads to the update failure. I have done some digging and it looks like github may be throttling Trilinos. I'm going to investigate how to increase the timeout for the clone so we can try and get this working asap. At the same time I'm going to see if we can't get github to stop throttling Trilinos. This has generally been an issue on other machines so it is worth looking into.

**Comment by bmpersc** [comment]
@csiefer2 sorry for the lack of response lately, between TUG and other things I haven't had much time to dig into this. Adjusting the timeout is not really possible since it is hard coded in tribits. I have been attempting to get a local copy of Trilinos in a place we can clone without being throttled. Unfortunately I'm having issues authenticating to that repo. I will continue looking into this.

**Comment by bmpersc** [comment]
@csiefer2 I have addressed the authentication issues for windows machine getting the local copy. We'll see tonight if the windows build can now complete. I will say that I have not setup anything to keep the local copy up-to-date yet, so if it does work it will be stagnant over the weekend. I did update it today so it isn't woefully out-of-date. If this seems like a viable path forward we will setup an automatic update of this local copy so that it will basically always be up-to-date.

**Comment by bmpersc** [comment]
@csiefer2, The windows tests look to be posting regularly again after moving them to a local mirror of Trilinos. Since this is working I have setup some automated syncing for the mirror so that it won't be very far behind the github repo. If everything works tonight I will close this issue...until the next time windows falls down.

**Comment by bmpersc** [comment]
@csiefer2 The update of the mirror allowed the windows builds to get the most recent Trilinos and that ran as well as expected. I'm closing this for now. If you notice the windows builds misbehaving again please open a ticket about it.
