### ISSUE TITLE
Document best practices for linking apps against Trilinos with CUDA

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1888]
@trilinos/framework @trilinos/tpetra 

It looks like applications are not linking against Trilinos with CUDA in the way that Trilinos itself builds and links with CUDA.  See discussion here: https://github.com/gahansen/Albany/issues/195

This suggests that Trilinos needs to document best practices for linking applications against Trilinos with CUDA.  It could be that applications have multiple good options, in which case Trilinos should document the strengths and weaknesses of each.

**Comment by jjellio** [comment]
@mhoemmen I ended up needing to help a new Trilinos user with CUDA support.

I've attached the 'dummy' script I got working for him.

The highlights:
How to set the CUDA lambda flag and c++11 flag. 

I also show how to set the CUDA frontend flags to minimize spam.

Do Not:
~~CMAKE_CXX_FLAGS="--expt-extended-lambda"~~
~~Trillions_CXX_FLAGS="--expt-extended-lambda"~~
DO:
*Trilinos_CXX11_FLAGS="-std=c++11 --expt-extended-lambda"*


[do-configure-trilinos-gcc-cuda.txt](https://github.com/trilinos/Trilinos/files/1415360/do-configure-trilinos-gcc-cuda.txt)

**Comment by mhoemmen** [comment]
@nmhamster suggested elsewhere: 
```
CUDA_VISIBLE_DEVICES=<put the number of the best GPU here>
```
as a way to control which CUDA device to use.  Is that a good idea, or is it better to use the Kokkos command-line argument?

**Comment by mhoemmen** [comment]
@crtrott says elsewhere: "[A] longstanding issue [is] that `nvidia_smi` numbering is not consistent with PICe numbers is not consistent with CUDA get_device numbers ...."

**Comment by nmhamster** [comment]
@mhoemmen - some MPI (and even scheduler) environments in the future will auto-set this environment variable as a way to direct software. We are not sure if this will be totally robust but if this is available, it will make end-users lives much easier.

**Comment by jjellio** [comment]
@mhoemmen Cuda MPS should be addressed. It is not precisely a Trilinos thing, it seems like a best practice to be aware of (and potentially use) MPS.

**Comment by mhoemmen** [comment]
@jjellio this may be relevant to your interests

**Comment by jjellio** [comment]
This seems outdated. The ATDMDevSettings + Kokkos efforts have moved the flags into Kokkos  (for the most part).  The only real trouble maker is RDC and duplicate flags due to Tribits/Kokkos not playing together as well as they should - but Ross is doing a refactor to pull Tribits up (I think it's been frozen at CMake 2.7 or 3.x (with x being low)).  Now things are going up to 3.17 (I believe) - so hopefully the flags and linker stuff can get smoothed over.

At this point the best practice is to use the ATDM "environment" (DevSettings) things and report errors . In that framework, I don't think I've had to fiddle with a cuda flag once. (Using Clang + Kokkos also moslty works w/out nvcc_wrapper - but that's going to be experimental until TriBits is updated).

**Comment by mhoemmen** [comment]
@jjellio I don't have a say in this issue any more, but I would interpret what you're saying as "best practice has changed."  That doesn't necessarily mean that best practices have been documented (in a way that Trilinos users who don't know anything about ATDM could find).
