### ISSUE TITLE
TrilinosCouplings/STKClassic: ‘FieldBase’ does not name a type

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#19]
**Next Action Status:**

STKClassic support in TrilinosCouplings is now always disabled by default (even if TrilinosCouplings and STKClassic are both enabled).  Next: Fix or remove code dependent on STKClassic?

**Description:**

When configuring Trilinos with

```
cmake \
  -DCMAKE_INSTALL_PREFIX:PATH=/opt/trilinos/ \
  -DCMAKE_BUILD_TYPE:STRING=Debug \
  -DCMAKE_C_COMPILER=mpicc \
  -DCMAKE_CXX_COMPILER=mpicxx \
  -DCMAKE_Fortran_COMPILER=mpif90 \
  -DBUILD_SHARED_LIBS:BOOL=ON \
  -DCMAKE_SKIP_RPATH:BOOL=ON \
  -DTrilinos_INSTALL_INCLUDE_DIR:PATH=include/trilinos/ \
  -DTrilinos_ENABLE_DEVELOPMENT_MODE:BOOL=OFF \
  -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON \
  -DTrilinos_ENABLE_SECONDARY_STABLE_CODE:BOOL=ON \
  -DTrilinos_ASSERT_MISSING_PACKAGES:BOOL=OFF \
  -DTrilinos_ENABLE_MeshingGenie:BOOL=ON \
  -DTrilinos_ENABLE_ForTrilinos:BOOL=OFF \
  -DTrilinos_ENABLE_Optika:BOOL=OFF \
  -DTrilinos_ENABLE_Phdmesh:BOOL=ON \
  -DTrilinos_ENABLE_PyTrilinos:BOOL=OFF \
  -DTrilinos_ENABLE_STKSearch:BOOL=OFF \
  -DTrilinos_ENABLE_STKTransfer:BOOL=OFF \
  -DTrilinos_ENABLE_ShyLU:BOOL=ON \
  -DTrilinos_ENABLE_Trios:BOOL=ON \
  -DPanzer_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
  -DSEACASExodus_ENABLE_MPI:BOOL=OFF \
  -DTrilinos_ENABLE_EXAMPLES:BOOL=ON \
  -DTrilinos_ENABLE_TESTS:BOOL=ON \
  -DPiro_ENABLE_TESTS:BOOL=OFF \
  -DShyLU_ENABLE_TESTS:BOOL=OFF \
  -DTPL_ENABLE_BinUtils:BOOL=ON \
  -DTPL_ENABLE_Boost:BOOL=ON \
  -DTPL_ENABLE_MATLAB:BOOL=OFF \
  -DTPL_ENABLE_Matio:BOOL=OFF \
  -DTPL_ENABLE_MPI:BOOL=ON \
  -DTPL_ENABLE_MUMPS:BOOL=ON \
  -DTPL_ENABLE_Netcdf:BOOL=ON \
  -DTPL_ENABLE_ParMETIS:BOOL=OFF \
  -DTPL_ENABLE_Scotch:BOOL=ON \
  -DTPL_Scotch_INCLUDE_DIRS:PATH=/usr/include/scotch/ \
  -DTPL_ENABLE_Eigen:BOOL=ON \
  -DTPL_Eigen_INCLUDE_DIRS:PATH=/usr/include/eigen3/ \
  -DTPL_ENABLE_TBB:BOOL=ON \
  -DTPL_ENABLE_X11:BOOL=OFF \
  -DTPL_ENABLE_Zlib:BOOL=ON \
  ../../source-upstream/
```

(perhaps there is this can be trimmed down), one gets the compilation error

```
[...]
[100%] Building CXX object packages/trilinoscouplings/examples/scaling/CMakeFiles/TrilinosCouplings_Example_Poisson_STKclassic.dir/example_Poisson_stkclassic.cpp.o
In file included from /home/nschloe/software/trilinos/source-upstream/packages/trilinoscouplings/examples/scaling/example_Poisson_stkclassic.cpp:135:0:
/home/nschloe/software/trilinos/source-upstream/packages/stk/stk_classic/stk_mesh/stk_mesh/fem/../../stk_mesh/base/FieldData.hpp:79:30: error: ‘FieldBase’ does not name a type
 bool field_data_valid( const FieldBase & f ,
[...]
```

**Comment by nschloe** [comment]
More errors occur when compiling that same file, e.g.,
```
/path/to/packages/trilinoscouplings/examples/scaling/example_Poisson_stkclassic.cpp:962:35: error: ‘worksetNodes’ was not declared in this scope
            for (size_t i = 0; i < worksetNodes.size(); i++) {
                                   ^
```

**Comment by boegel** [comment]
I'm running into the same problems... Did you ever figure out more @nschloe?

**Comment by nschloe** [comment]
Unfortunately no. As far as I see, your only option is to disable STKClassic. It's unsupported anyways.

**Comment by boegel** [comment]
@nschloe: thanks, that's helpful, I'll just configure with `cmake -DTrilinos_ENABLE_STKClassic=OFF ...`

**Comment by bartlettroscoe** [comment]
@trilinos/framework

I got bit by this too while testing out the new SEMSDevEnv.cmake (see #158).

Since the TrilinosCouplings package fails to build everywhere it is being tested as shown here:

http://my.cdash.org/index.php?project=Trilinos&subproject=TrilinosCouplings&date=2016-06-22
http://testing.sandia.gov/cdash/index.php?subproject=TrilinosCouplings&project=Trilinos&date=2016-06-22

and seems to be disabled in CI testing as shown here:

http://testing.sandia.gov/cdash/index.php?date=2016-06-22&project=Trilinos&parentid=2483512

I am going to go ahead and switch TrilinosCouplings to an Experimental package for now.   Apparently no one seems to care about the TrilinosCoupling package anymore since this this build failure has been there since at least Nov 20, 2015 as @nschloe reported!

**Comment by nschloe** [comment]
The good news is: @rppawlo let me know that that they will shortly remove their STKClassic dependency, making it possible to finally get rid of STKClassic altogether. This should prevent a bouquet of errors like these.

**Comment by bartlettroscoe** [comment]
> The good news is: @rppawlo let me know that that they will shortly remove their STKClassic dependency, making it possible to finally get rid of STKClassic altogether. This should prevent a bouquet of errors like these.

That is good, but who is going to upgrade TrilinosCouplings to use the new STK?  No one seems to care about this package since this has been failing since Nov 2015!

**Comment by bartlettroscoe** [comment]
So it looks like parts of TrilinosCouplings still work since there are recent commits like:

```
da75914 "Stokhos:  Add ensemble ETI for ensemble size = 8."
Author: Eric Phipps <etphipp@sandia.gov>
Date:   Tue Jun 14 12:47:33 2016 -0600 (10 days ago)

M       packages/trilinoscouplings/examples/fenl/main_ensemble.cpp
```

Therefore, I will just disable the STKClassic part of this package and see if that works.

**Comment by bartlettroscoe** [comment]
So this is interesting.  It appears that I was the one who disabled TrilinosCouplings in the CI build way back in the commit:

```
commit 5260450862f14bf489154db3c2564600796bb808
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Sat Dec 6 21:43:48 2014 -0500

    Disable Optika and TrilinosCouplings in CI build (Trilinos #6265)
    
    These packages have failed to build in this CI build for many months.
    Obviously it is not important to test these in the CI build so to maintain the
    integrity of the CI build they are being disabled for this CI build.

diff --git a/cmake/ctest/drivers/trilinos-test2/ctest_linux_continuous_mpi_opt_shared_trilinos-test2_jenkins.cmake b/cmake/ctest/drivers/trilinos-test2/ctest_linux_continuous_mpi_o
index 83da9b5..6a6146f 100644
--- a/cmake/ctest/drivers/trilinos-test2/ctest_linux_continuous_mpi_opt_shared_trilinos-test2_jenkins.cmake
+++ b/cmake/ctest/drivers/trilinos-test2/ctest_linux_continuous_mpi_opt_shared_trilinos-test2_jenkins.cmake
@@ -71,7 +71,7 @@ SET( CTEST_PARALLEL_LEVEL "12" )
 
 SET(Trilinos_ENABLE_SECONDARY_STABLE_CODE ON)
 
-SET(EXTRA_EXCLUDE_PACKAGES Claps)
+SET(EXTRA_EXCLUDE_PACKAGES Claps Optika TrilinosCouplings)
 
 SET( EXTRA_CONFIGURE_OPTIONS
   "-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON"
```

That was  3 weeks after @nschloe created this issue ticket.  I must have not known about this GitHub issue because I did not reference this GitHub Issue ID.  I should have done a search and found this.  I likely would have also noticed that it was failing in **all** builds at the time and therefore should have just disabled STKClassic support in TrilinosCouplings by default for **all** builds.

BTW: The way that I found this issue what that I tripped on this build failure myself and then decided to do a search of the Trilinos GitHub issues for all mentions of TrilnosCouplings and I found this.

**Comment by etphipp** [comment]
Yes, I build TrilinosCouplings without STKClassic all the time, and it works fine.

-Eric

**Comment by bartlettroscoe** [comment]
Responding to @etphipp from [above comment](https://github.com/trilinos/Trilinos/issues/19#issuecomment-228359207):
> Yes, I build TrilinosCouplings without STKClassic all the time, and it works fine.

Right.  But if you enable with:

```
  -DTrilinos_ENABLE_TrilinosCouplings=ON \
  -DTrilinos_ENABLE_STK=ON \
```
which seems like a reasonable thing for someone to do if they don't know better.

What is your exact set of enables/disable that you use to configure TrilinosCouplings with STK also enabled (or do you never enable STK)?

I am disabling STKClassic support TrilinosCouplings by default to see if the rest of it passes.  If it does, I will push the change and then we will get automated testing for TrilinosCouplings again.

**Comment by etphipp** [comment]
I've never tried to build TrilinosCouplings with any manner of STK enabled.

**Comment by bartlettroscoe** [comment]
> I've never tried to build TrilinosCouplings with any manner of STK enabled.

@etphipp, can you please post the exact list of configure enables/disables that you use with TrilinosCouplings and provide the lines "Final set of enabled packages:" and "Final set of enabled SE packages:" from the cmake configure out?

**Comment by etphipp** [comment]
Sure.  Here is a trilinos configure script that enables TrilinosCouplings without STK.  

[do_configure.txt](https://github.com/trilinos/Trilinos/files/332013/do_configure.txt)

Here is the final set of enabled packages and SE packages:

Final set of enabled packages:  Kokkos Teuchos RTOp Sacado Epetra Zoltan Shards Triutils Tpetra EpetraExt Thyra Xpetra AztecOO Galeri Amesos Zoltan2 Ifpack ML Belos Amesos2 Anasazi Ifpack2 Stratimikos Phalanx NOX MueLu Stokhos TrilinosCouplings 28

Final set of enabled SE packages:  KokkosCore KokkosContainers KokkosAlgorithms Kokkos TeuchosCore TeuchosParameterList TeuchosComm TeuchosNumerics TeuchosRemainder TeuchosKokkosCompat TeuchosKokkosComm Teuchos RTOp Sacado Epetra Zoltan Shards Triutils TpetraClassic TpetraKernels TpetraTSQR TpetraCore Tpetra EpetraExt ThyraCore ThyraEpetraAdapters ThyraEpetraExtAdapters ThyraTpetraAdapters Thyra Xpetra AztecOO Galeri Amesos Zoltan2 Ifpack ML Belos Amesos2 Anasazi Ifpack2 Stratimikos Phalanx NOX MueLu Stokhos TrilinosCouplings 46

**Comment by bartlettroscoe** [comment]
> Sure. Here is a trilinos configure script that enables TrilinosCouplings without STK.
>
> do_configure.txt

Thanks that helps.  In parallel, I was able to get TrilinosCouplings to build with STKClassic globally enabled but support for STKClassic disabled in TrilinosCouplings (whoever wrote the CMakeLists.txt files must not have understood [how to do this correctly](https://tribits.org/doc/TribitsDevelopersGuide.html#support-for-optional-se-package-tpl-can-be-explicitly-disabled), looks like some more documentation is needed to explain this).

This is slightly off topic but it is interesting to see the actual do-configure scripts people are using.  It seems like many people disable all optional packages and then explicitly turning on packages they think they need (i.e. "white-listing").  This leads to a very long configure script (This one is 146 lines long).  I might suggest that instead people should leave optional packages turned on, only enable the actual packages they want to test, and then disable the packages they don't want (i.e. "blacklisting").   This proved to be much better for Panzer and Drekar, for example, as shown [here](https://github.com/trilinos/Trilinos/issues/215#issuecomment-198538224).

I think that these (perhaps unnecessarily) long and complex configure scripts that people use and pass around are one reason why Trilinos has the reputation for being so hard to configure and build.

**Comment by etphipp** [comment]
This is a configure script that has accrued a lot of crap over many years, so you can't read anything into it.

**Comment by nschloe** [comment]
> That is good, but who is going to upgrade TrilinosCouplings to use the new STK?

I would say that if no one is interested in doing this, we should simply remove that part. STKClassic is outdated, unsupported, and full of errors. The only reason that it's still part of anything is that one particular upstream projects of Roger's was using it, but that reason will be gone this week or the next.

**Comment by bartlettroscoe** [comment]
> This is a configure script that has accrued a lot of crap over many years, so you can't read anything into it.

The fact that experienced Trilinos developers need to hold onto and modify the same configure script for "years" is a symptom of the problem.  Not trying to criticize, just trying to point out these data points that point to a larger problem with Trilinos.  We need to get Trilinos in shape so that developers can start new  reasonable configure scripts from scratch frequently and get good results.  I am addressing part of that in #158 (almost done) and #172 (much harder and will not a lot more work because it is a moving target and CUDA builds have lots of challenges).

**Comment by bartlettroscoe** [comment]
Note that TrilinosCouplings is now running and passing in CI testing was shown here:

http://testing.sandia.gov/cdash/index.php?date=2016-06-24&project=Trilinos&parentid=2486283

This is an MPI build.

This does not really fix the defect that this ticket was meant to address but at least no one else will have to deal with this build failure just because they did something a innocent and configuring Trilinos with `-DTrilinos_ENABLE_TrilinosCouplings=ON`.  If you want to generate this build failure now, you would have to configure Trilinos and explicitly set `-DTrilinosCouplings_ENABLE_STKClassic=ON`.

Who do we turn this issue over to now?  Who is the maintainer of TrilinosCouplings at this point?

**Comment by alanw0** [comment]
This has been resolved.
