### ISSUE TITLE
Announcement of develop-to-master promotions?

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1934]
@trilinos/framework How does Trilinos announce develop-to-master promotions?

I'm asking because a colleague who works on an app said that they find this out by pulling master by hand, and seeing if new commits arrived.  Is that the recommended procedure?  Given that #1154 is still open, users won't normally expect nightly updates of master.  Thus, it might be helpful to have some kind of announcement on each promotion, like an e-mail to trilinos-users or a post on the website.  Kokkos posts an issue for each develop-to-master promotion, then closes the issue when it's done.

**Comment by jwillenbring** [comment]
@william76 We spoke about this some. Sounds like a note to the developers list is not a good idea because this is a user asking. I am hesitant to spam the many hundreds of people on the user list each time a promotion is done. We could file an issue like Kokkos, or we could file one issue and comment on it every time a promotion happens, and log the errors when it doesn’t happen. Then people could follow this issue in GitHub if they want to know. Thoughts? I don’t want this to be too much overhead.

**Comment by mhoemmen** [comment]
@jwillenbring I like Kokkos' approach of having a separate issue for each promotion, that's closed on successful promotion.  This also helps track what new features and bug fixes came in with each promotion.  It's more automated than the process of asking for humans to write release notes.
