### ISSUE TITLE
ShyLU: ShyLU_Node Tests Failing in CDash Clean builds

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#1935]
@trilinos/shylu 

There are failing tests in the [nightly clean track for ShyLU_Node](https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3193185)

- [ShyLU_NodeTacho_Tacho_TestSerial_dcomplex](https://testing.sandia.gov/cdash/testDetails.php?test=42399106&build=3193533)
```
[----------] 3 tests from DenseMatrixView
[ RUN      ] DenseMatrixView.flat
[       OK ] DenseMatrixView.flat (0 ms)
[ RUN      ] DenseMatrixView.hier
[       OK ] DenseMatrixView.hier (0 ms)
[ RUN      ] DenseMatrixView.memorypool
Kokkos MemoryPool size constraint violation  MemoryPool min_block_alloc_size(128) max_block_alloc_size(8192) min_superblock_size(4096) min_total_alloc_size(8192) ; max_superblock_size(2147483648) max_block_per_superblock(33554432)
```

- [ShyLU_NodeTacho_Tacho_TestSerial_double](https://testing.sandia.gov/cdash/testDetails.php?test=42399105&build=3193533)
```
[----------] 3 tests from DenseMatrixView
[ RUN      ] DenseMatrixView.flat
[       OK ] DenseMatrixView.flat (0 ms)
[ RUN      ] DenseMatrixView.hier
[       OK ] DenseMatrixView.hier (0 ms)
[ RUN      ] DenseMatrixView.memorypool
Kokkos MemoryPool size constraint violation  MemoryPool min_block_alloc_size(128) max_block_alloc_size(8192) min_superblock_size(4096) min_total_alloc_size(8192) ; max_superblock_size(2147483648) max_block_per_superblock(33554432)
```

**Comment by bmpersc** [comment]
@kyungjoo-kim, please let me know if you will be able to address this today. This has been failing for a while and is the only issue with the current clean builds. We need to address this either with a fix or backing out the offending change before the next set of nightly tests run.

**Comment by srajama1** [comment]
@bmpersc : You said  " We need to address this either with a fix or backing out the offending change before the next set of nightly tests run." 

Why ? We were not getting any notifications for the past few days, and as you can see I assigned it to him 37 minutes ago. It appears fixable, but I would like to understand the reason behind that statement. Are we going to use a 5 day rule (from when the bug was filed). I am fine if that is the case, but I would like to understand better.

**Comment by kyungjoo-kim** [comment]
@hcedwar @ibaned @srajama1 @bmpersc 

This seems to be a kokkos error.
```
        if ( ( size_t(max_superblock_size) < min_superblock_size ) || \\ why this is an error case ? max is smaller than min ? 
             ( min_total_alloc_size < min_superblock_size ) ||
             ( max_superblock       < min_superblock_size ) || // again why max superblock is smaller than min superblock ?
             ( min_superblock_size  < max_block_alloc_size ) || 
             ( max_block_alloc_size < min_block_alloc_size ) ) {
```

**Comment by kyungjoo-kim** [comment]
In my print statement
```
2:   MemoryPool 
  min_block_alloc_size(8) 
  max_block_alloc_size(8192) 
  min_superblock_size(4096) 
  min_total_alloc_size(8192) ; 
  max_superblock_size(2147483648) 
  max_block_per_superblock(33554432)                                                                                                                                                      

2:  max_superblock_size(2147483648) < min_superblock_size(4096)    // okay                                                                                                      
2:  min_total_alloc_size(8192) < min_superblock_size(4096)                  // okay                                                                                             
2:  max_superblock(268435456) < min_superblock_size(4096)              // okay                                                                                                  
2:  min_superblock_size(4096) < max_block_alloc_size(8192)               // this is not okay                                                                                     
2:  max_block_alloc_size(8192) < min_block_alloc_size(8)                     // okay
```
I think that all parameters are correct but this not okay comparison is weird.

**Comment by ibaned** [comment]
It makes sense to me. A superblock must be at least as big as a block. therefore, the minimum superblock size must be at least as big as the maximum block size.

**Comment by kyungjoo-kim** [comment]
@ibaned 

Oh...... you are right. I did not set the parameter correctly. It used to be working though. I think that Kokkos constructor used to set (override) the max_block_size according to the superblock size. Instead of we get this error when the pool attempts to allocate it, can we check the error in the constructor level ?

**Comment by kyungjoo-kim** [comment]
@bmpersc 

This should fix the test failure.

**Comment by jwillenbring** [comment]
>@bmpersc : You said " We need to address this either with a fix or backing out the offending change before the next set of nightly tests run."

>Why ? We were not getting any notifications for the past few days, and as you can see I assigned it to him 37 minutes ago. It appears fixable, but I would like to understand the reason behind that statement. Are we going to use a 5 day rule (from when the bug was filed). I am fine if that is the case, but I would like to understand better.

@srajama1, @bmpersc is expressing a draft ideas of policies associated with the various tracks. The current thought for the clean branch is that all issues should be resolved in not more than 1 working day, if not sooner. However, we anticipate that the pull request testing will cover the clean cases eventually, leaving only very limited situations where any changes will get in that break the clean builds because the pull request testing will fail.

The timing of the GitHub notification failure was very unfortunate for this issue. Do you see general issues with backing the change out? In general, I think of this not as being heavy-handed, but as giving people time to calmly and cleanly fix an issue, rather than causing errors for others.

Currently, we do not update master when there are any clean failures, so clean failures impact those using master, including one key customer. I think it is reasonable to let this go until tomorrow at this point if it must. Do you object to backing this out before the end of the day tomorrow if it is not resolved?

**Comment by srajama1** [comment]
@jwillenbring : If the policy is going to be one day then it is good. I was just surprised by the timing of the comment. The issue was sitting there for five days and right after I assigned it, a fix was requested right away. Yes, pull request testing would have caught this. As you can see @kyungjoo-kim has fixed the failing test already. Please close this after clean tests pass. 

BTW, please let us know directly if you don't see a response from us for something we should have responded to. Github is starting to annoy me with this e-mail notification thing.

**Comment by kyungjoo-kim** [comment]
A few things about this issue. Tacho is EX state and it is not going to be compiled with check-in script. Does this mean that any pull request test compiles all packages including packages with the EX state ?

This runtime error does not pop up before and it used to be okay. With the recent kokkos promotion, kokkos memory pool has additional error checking for using 64bit integer that allows 2GB allocation in the memory pool. So, it seems that my code is not tested in the procedure promoting kokkos (I need to double check this with Christian) and it is tested in some nightly tests. Although we use a pull request model, this type of errors may not be easily caught unless all of package moderators perform all unit tests including all packages.

**Comment by ibaned** [comment]
@kyungjoo-kim here is the Trilinos configuration used in the Kokkos promotion:
https://github.com/trilinos/Trilinos/blob/master/sampleScripts/Sandia-SEMS/configure-testbeds-jenkins-all
Is something missing there to enable Tacho? If so we'll add it

**Comment by kyungjoo-kim** [comment]
Yes. Tacho should be explicitly enabled. Amesos2 has interface to Tacho but it is optional and it is not enabled by default. Could add the following lines ?
```
-DTrilinos_ENABLE_ShyLU_NodeTacho:BOOL=ON
-DShyLU_NodeTacho_ENABLE_TESTS:BOOL=ON
-DShyLU_NodeTacho_ENABLE_EXAMPLES:BOOL=ON
 ```

I guess that Tacho is the only package that uses kokkos tasking aggressively.

**Comment by ibaned** [comment]
done!

**Comment by srajama1** [comment]
I would like to change Tacho to ST as well. It is blocked because of TPL dependencies #1782

**Comment by srajama1** [comment]
@ibaned : Thanks!

**Comment by bmpersc** [comment]
The clean builds showed that these tests are now passing.
