### ISSUE TITLE
Create CODEOWNERS File

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#2013]
@trilinos/framework 

## Expectations

It'd be great for us to include a [CODEOWNERS](https://help.github.com/articles/about-codeowners/) file in the Trilinos repo root.  Having such a file makes it such that we can assign default people or @trilinos/teams as reviewers when pull requests are created, depending on what files/packages/etc. are modified.

## Current Behavior

Currently we rely on the one submitting the pull request to assign an appropriate reviewer if they know of one.

## Motivation and Context

This would provide some backup to ensure that the right people are reviewing the changes coming in.

## Related Issues

* Related to #1583

**Comment by jwillenbring** [comment]
This sounds like a really nice feature.

**Comment by jmgate** [comment]
This `CODEOWNERS` file has made it into `master`, but it doesn't look like teams are being auto-assigned as pull request reviewers.

**Comment by jmgate** [comment]
Email response from GitHub staff:

> Hey Jason,
> 
> Thanks for reaching out!  Do the teams that you are listing in your CODEOWNERS file have explicit write permission on the repository?  You'll have to grant that team direct write access to the repository before the team can be requested as a reviewer:
> 
> https://help.github.com/articles/managing-team-access-to-an-organization-repository
> 
> Can you double check that the team has been granted write permissions, and let me know if you're still having any trouble?
> 
> Cheers,
> Antonio

@trilinos/framework, can someone give the various `@trilinos/teamName` teams write access to the Trilinos repository?  Currently the Developers team has write access, a few teams have read access, and the vast majority of the teams have no access to Trilinos at all.  I'd happily make this change myself, but I don't have the required permissions.

@jwillenbring, @bmpersc, @william76

**Comment by bmpersc** [comment]
@jmgate I have 2 concerns with adding write access to every team.

The first is that I'm not sure that the "right people"(ie people with admin access on Trilinos) always have control over who is on a team. I thought that we allowed package leads to add people to their teams as they saw fit. The concern here is that they might add someone who is not a member of the developer team, there by giving them access they wouldn't otherwise have. I could see a case where someone wants to be in the loop of issues, but shouldn't have write access. I don't know if that is being used at this point though. This is something we can mitigate by requiring people not to add folks to teams without some consideration of their role on Trilinos.

The second is the potential maintenance cost of having to keep all of the groups with the right permissions. Up until this point we've used them only for communication, which required no access as you discovered. My biggest concern is if we decide to change the access to a branch (like we're about to do with develop) that we'll have a big mess if we have to make sure 40ish teams are set right instead of the current one team. This is harder to mitigate, but I don't think that we'll have a lot of cases where we change existing branches, rules, etc. The most common would be making sure that new teams get the proper access when created.

Those concerns aside I'm certainly not against adding write access to a handful of groups to test out this feature. It might very well be that the benefits out weigh the concerns. I definitely like the idea of automatically having the reviewers assigned to something reasonable.

**Comment by jmgate** [comment]
@bmpersc, I've emailed GitHub support about your first question&mdash;it may be the case that this is something we should do only after we lock down `develop` such that changes only come in via PR.

**Comment by jmgate** [comment]
In the meantime, would you like to add write access to @trilinos/panzer to test out this feature?  All the members of that team are already part of the Developers team.

**Comment by jmgate** [comment]
GitHub's recommendation would be to:
* Give all our `@trilinos/package` teams read access to Trilinos.
* Create `developers` subteams with write access for each team (that is, `@trilinos/package/developers` would have write access).
* Use the `@trilinos/package/developers` teams in the `CODEOWNERS` file.
* Add those who want to watch `package` to `@trilinos/package`.
* Add those who develop `package` to `@trilinos/package/developers`.

Any time you mention `@trilinos/package`, `@trilinos/package/developers` get notified as well, but not the other way around.

GitHub pointed me to the bits of their API having to do with teams such that we could automate the creation of these subteams, applying all the right permissions, etc.  Then we'd have to contact team maintainers and have them add the appropriate people to the `developers` subteams.  Of course, we'd first have to ensure all teams have maintainers assigned (many, if not most, don't).

Do we want to go through with all this?  May be best to just bring it up at the next Framework meeting.

**Comment by jmgate** [comment]
I can confirm that PR #2113 demonstrates this capability to be working for Panzer.  @trilinos/panzer was automatically requested as a reviewer, and @rppawlo approved the PR on Panzer's behalf.

**Comment by jmgate** [comment]
Just an update here:  @trilinos/panzer is the only team that has been given write access to Trilinos to test out this feature.  PRs against Panzer do in fact request Panzer as a reviewer, and anyone on the Panzer team who submits a review satisfies that request.  Unfortunately, PRs against any other package also seem to be requesting Panzer as a reviewer (see, e.g., #2152, #2135, #2122).  I've contacted GitHub support and they've escalated this up to the appropriate people.  No ETA on a solution, but they should be in touch soon.

**Comment by bmpersc** [comment]
@jmgate, Thanks for the update. This is good to know that this is behaving this way. I'm wondering if that is a side effect of only having one team with write access or if the behavior is all teams with write access get assigned to all PRs. I'll talk with the rest of the Framework team to see if we either want to disable Panzer's write access or test out another package to see what happens.

**Comment by bmpersc** [comment]
@jmgate, I have added the FEI team, which is just you at this point, to the set of teams that have write access. FEI isn't very active so if it does get added to a PR as reviewer it is almost certainly in error. Hopefully this will give us some insight into the issue.

**Comment by jmgate** [comment]
Very good.  I'll keep my eyes on PRs for the next few days and see what happens.  Then this reminds me I need to add the actual POC to the FEI team and then remove myself.  Thanks @bmpersc.

**Comment by jmgate** [comment]
#2156 (Tempus PR) was just created and neither Panzer nor FEI were requested as reviewers.  Previously Panzer had been requested as a reviewer for Tempus changes.  Not sure if this new behavior is because we have two teams with write access, or if GitHub fixed something behind the scenes.  Haven't heard back from them yet.

**Comment by jmgate** [comment]
#2158 (Phalanx) is exhibiting the correct behavior now, whereas a Phalanx PR in the past requested Panzer as a reviewer.

**Comment by bmpersc** [comment]
@jmgate it is good to know that this is now behaving as expected, whether that is the change I made or a bug having been fixed doesn't matter too much at this point.

**Comment by jmgate** [comment]
#2162 just requested a review from Panzer when it shouldn't have.  Seems something is still amiss.  I'll ping GitHub.

**Comment by bmpersc** [comment]
@jmgate did you remove the requested reviewer for the panzer team from that ticket? I only see Jim and myself as requested reviewers, but I don't see a removal of a requested reviewer.

**Comment by jmgate** [comment]
@bartlettroscoe removed it almost immediately after the PR was created.

**Comment by bmpersc** [comment]
Ahh, I see that now. I was hidden behind Jim and I being added in the same notification. I was beginning to wonder if different people were seeing different reviewers which would have been a whole different kind of error.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe removed it almost immediately after the PR was created.

What did I do and how did I do it?  I did see that PR #2162 assigned Panzer as the reviewer by default which is crazy for the file that is changed in the PR.

BTW, @william76, @bmpersc or @jwillenbring, can you please review #2162?  That should take care of one of the problems with that build.  Also, what is the plan to clean up the Nightly builds so that CDash emails can be turned on?

**Comment by bmpersc** [comment]
@bartlettroscoe you didn't do anything that was a problem, @jmgate was just answering my question. I wasn't seeing the panzer reviewer and wasn't sure if that was more information about the issue we're seeing with this code owners capability or if it was an intentional action to have panzer removed as a reviewer.

**Comment by jmgate** [comment]
Another example of the wrong team being requested for review:  #2238.  I pinged GitHub earlier in the week, and I'll do that again.  I'm tempted to say if they don't have a solution I'll just comment everything out in the CODEOWNERS file and wait till they get the feature sorted out.

**Comment by jmgate** [comment]
Well, we finally figured out what was going on here.  GitHub's CODEOWNERS feature is behaving exactly as it should&mdash;we're just seeing human error manifesting as a technical problem.  All the examples of "incorrect" behavior we've seen over the last month involve pull requests that were initially created against `master`, and then later the base branch was switched to `develop`.  At the point of creation, GitHub looks at all the changes between `master` and the feature branch, which include all the change in `develop` that haven't yet made it into `master`, and assigns code owners as reviewers accordingly.  When the developer switches the base branch to `develop`, the damage has already been done.

We have the following options moving forward:
1. Live with it.
1. Try to emphasize to developers the importance of creating PRs against `develop`.
1. Switch our default branch in GitHub to `develop`.  This would mean PRs would automatically have `develop` as the base branch.  It would also mean when someone clones Trilinos, git will checkout `develop` right off the bat.  That would require educating users to manually checkout `master` right away so they're using the more-stable branch.
1. Pester GitHub until they allow a distinction between a "default checkout branch" and a "default PR branch".
1. Delete our `CODEOWNERS` file and pretend none of this ever happened.

@trilinos/framework, what say ye?  I like option 4 the best, but I'm not about to hold my breath.

For what it's worth, it has been useful for the Panzer team to be requested as a reviewer for any PR touching our package.  We wind up with more eyes on a change-set before it makes it into `develop`, which has the potential to improve the code over time.

**Comment by mperego** [comment]
Thanks @jmgate . I also like option 4 (and maybe 2 in the meanwhile).

**Comment by bartlettroscoe** [comment]
I agree with @mperego.  Short-term option-2 is the best solution (and warn people to carefully check the selected default reviewers after the PR is first created).  But long-term option-4 would be best.

Note that option-3 would make make the develop/master workflow almost completely worthless as a way to shield casual users from the instabilities on the `develop` branch.

**Comment by bmpersc** [comment]
@jmgate, thanks for looking into this, that is a tricky cause. Option 4 would be ideal, but like you I'm not going to hold my breath. If github flow used a master/develop like portion then I would think it might happen. Option 3 really isn't an option. We discussed that when we first went to the master/develop model as a way to make it harder to accidentally push to the wrong place, however, we didn't want to make it harder for people who wanted to use Trilinos.

Option 2 certainly seems like something we should invest some effort into. I know that I've made the mistake of just accepting the default since it wasn't immediately obvious where I was issuing the PR to. I'm not really sure what would be helpful there other than some training. I guess mistakes would have a bit of peer pressure when basically everyone gets automatically added as a reviewer when someone makes a mistake.

**Comment by jmgate** [comment]
From [this comment](https://github.com/trilinos/Trilinos/issues/2013#issuecomment-354846931) a while back:

> GitHub's recommendation would be to:
> 
> - Give all our `@trilinos/package` teams read access to Trilinos.
> - Create developers subteams with write access for each team (that is, `@trilinos/package/developers` would have write access).
> - Use the `@trilinos/package/developers` teams in the CODEOWNERS file.
> - Add those who want to watch package to `@trilinos/package`.
> - Add those who develop package to `@trilinos/package/developers`.

@trilinos/framework, now that PR testing is mandatory, is this something you want to explore further?  I'm happy to do the work if I have the requisite permissions.

**Comment by jmgate** [comment]
Ping.  Closing as "nobody cares"&hellip;

**Comment by jmgate** [comment]
Reopening to continue the conversation with @srajama1.  From his email:

> What would it take to implement this now for all Tpetra stack as you suggested in that comment?

There are two potential answers to that question, depending on the answer to this one:  Does Trilinos intend to have members of `@trilinos/<package>` teams that should not have write-access to the Trilinos repository?

If yes (non-developers can be on `@trilinos/<package>` teams):
1. Under each `@trilinos/<package>` team, create a `developers` sub-team.
1. Give each `developers` sub-team write-access to the Trilinos repository.
1. Add the folks in the `@trilinos/<package>` team who should have write-access to the repository to the corresponding `@trilinos/<package>/developers` sub-team.  The barrier for entry should be the same as for being added to the `@trilinos/developers` team.
1. Modify the `CODEOWNERS` file and replace `@trilinos/<package>` with `@trilinos/<package>/developers` everywhere.

If no (non-developers *cannot* be on `@trilinos/<package>` teams):
1. Review each of the `@trilinos/<package>` teams and remove any people who should not have write-access to the repository.
1. Give each `@trilinos/<package>` team write-access to the repository.

This second case is what's already been done for Panzer (initially just to test out the feature), MueLu, and now Kokkos-Kernels.

> I would also request an additional feature, two developer teams for each package, a developer team at Sandia and developer team anywhere. Any PR would require approval from the former. I am actually going to request this feature for Amesos2, Zoltan2, and ShyLU. If you want to do it for all of Trilinos now might be the time.

Again, two answers:  You can have multiple users/teams automatically assigned to review pull requests.  Whereas now a line in our `CODEOWNERS` file looks like this
```
/packages/panzer @trilinos/panzer 
```
you would just need to modify it as follows:
```
/packages/panzer @trilinos/panzer @team2 @other-user @etc
```
Unfortunately every one of those users or teams must have write-access to the repository in order to be automatically assigned to review a pull request.  If your non-Sandia developer team somewhere else has write-access, no problem.  If it doesn't, and you don't want to give them write-access, it won't work.  It won't hurt to have the teams mentioned in the `CODEOWNERS` file, but they won't be assigned to review the PRs.

CC:  @maherou, @mmwolf, @jwillenbring, @lucbv
