### ISSUE TITLE
No Trilinos checkin emails

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#2029]
I haven't received any Trilinos checkin emails since November 22nd.

@trilinos/framework 
@bmpersc

**Comment by bartlettroscoe** [comment]
Same for me

**Comment by dridzal** [comment]
Would providing github with a different email address solve these problems?  An email address associated with a non-Sandia server that does not reject email.

**Comment by bmpersc** [comment]
@dridzal the email we are using is not on a Sandia machine. It is on the trilinos.org server. This issue is actually different than the throttling issue for notifications. I don't know all the specifics, but it has to do with the mailman server on trilinos.org. I know that the issue is being looked into, but I don't know what the status of it is.

**Comment by jwillenbring** [comment]
John P is looking into this and hopes to have it fixed by the end of the day.

**Comment by jwillenbring** [comment]
This should now be resolved. Please close if it isn't. It was a problem with the server trying to use the wrong mail protocol.

**Comment by jhux2** [comment]
@jwillenbring Thanks!

**Comment by jhux2** [comment]
I'm still not receiving any checkin emails.

**Comment by bartlettroscoe** [comment]
I just checked and I can confirm that I am not getting any checking emails since 11/22/2017 either.
