### ISSUE TITLE
[Framework] Windows build once again not posting

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#2084]
Happy holidays @bmpersc

**Comment by bmpersc** [comment]
@csiefer2 it looks like there is an issue with the windows machine communicating with jenkins. Strangely both machines are up and otherwise seem to be working. I'll have to dig more into this since it isn't the simple restart the jenkins process.

**Comment by bmpersc** [comment]
@csiefer2 The jenkins issue has been resolved. The jenkins server was having some issues which have now been fixed and jenkins can connect to the windows test machine. However, there is a new issue. Apparently there are a number of files that have been introduced to Trilinos that are too long to clone on windows. These files are in Kokkos-kernels so it is not a package we are currently worried about for windows. However, since this is preventing the clone from completing it is impacting this. We will have to discuss this with that team to see what solution we can come to.

**Comment by bmpersc** [comment]
@csiefer2, I have been able to work around the issue without having to make the Kokkos-kernels folks change their file names. Apparently the windows git be default still uses the 260 max path length to be backwards compatible. However, the machine we are running this on supports much greater, 32k, which is even longer than the typical linux max of 4k. Thankfully the windows git had a configure option to allow it to use the longer paths and setting that seems to have worked. Windows tests are now submitting again.
