### ISSUE TITLE
CMake error on the nightlies

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#2085]
Many packages in the nightly build had a CMake configure error... 
https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-12-19

Hey @bartlettroscoe, it's not clear to me where this one is coming from, do you mind taking a quick look at the error messages from CMake?  It's complaining about a ForTrilinosUtils package but I'm not entirely certain which 'package' that is...

## Current Behavior
Here's what the error messages are looking like on CMake:
* Example: https://testing.sandia.gov/cdash/viewConfigure.php?buildid=3282433
```
CMake Error at /space/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:738 (INCLUDE):
  include could not find load file:

    /space/nightlyTesting/SERIAL_DEBUG_DEV_MueLu_ExtraTypes/Trilinos/packages/ForTrilinos/src/utils/cmake/Dependencies.cmake
Call Stack (most recent call first):
  /space/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:776 (TRIBITS_READ_SUBPACKAGE_DEPENDENCIES)
  /space/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:882 (TRIBITS_READ_ALL_PACKAGE_SUBPACKAGE_DEPENDENCIES)
  /space/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:1005 (TRIBITS_READ_PACKAGE_DEPENDENCIES)
  /space/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1509 (TRIBITS_READ_ALL_PACKAGE_DEPENDENCIES)
  /space/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:160 (TRIBITS_READ_PACKAGES_PROCESS_DEPENDENCIES_WRITE_XML)
  /space/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:93 (TRIBITS_PROJECT)


CMake Error at /space/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:1068 (MESSAGE):
  Error, the package variable LIB_REQUIRED_DEP_PACKAGES was not defined
  correctly for package ForTrilinosUtils!
Call Stack (most recent call first):
  /space/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:521 (TRIBITS_ASSERT_DEFINED_PACKAGE_VAR)
  /space/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:740 (TRIBITS_ASSERT_READ_DEPENDENCY_VARS)
  /space/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:776 (TRIBITS_READ_SUBPACKAGE_DEPENDENCIES)
  /space/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:882 (TRIBITS_READ_ALL_PACKAGE_SUBPACKAGE_DEPENDENCIES)
  /space/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:1005 (TRIBITS_READ_PACKAGE_DEPENDENCIES)
  /space/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1509 (TRIBITS_READ_ALL_PACKAGE_DEPENDENCIES)
  /space/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:160 (TRIBITS_READ_PACKAGES_PROCESS_DEPENDENCIES_WRITE_XML)
  /space/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:93 (TRIBITS_PROJECT)


-- Configuring incomplete, errors occurred!
CMake Error: CTEST_USE_LAUNCHERS is enabled, but the RULE_LAUNCH_COMPILE global property is not defined.
Did you forget to include(CTest) in the toplevel CMakeLists.txt ?
```

**Comment by bartlettroscoe** [comment]
> Hey @bartlettroscoe, it's not clear to me where this one is coming from, do you mind taking a quick look at the error messages from CMake? It's complaining about a ForTrilinosUtils package but I'm not entirely certain which 'package' that is...

@william76, can we get on Skype for Business and go over this together?  I can show you how to track down something like this.

**Comment by bartlettroscoe** [comment]
See trilinos/ForTrilinos#195

What is happening is that the ForTrilinos git repo is getting cloned into the Trillinos source true due to it being listed in `Trilinos/cmake/ExtraRepositoriesList.cmake` as as `Nightly` git repo.  Since ForTrilinos is listed in `Trilinos/PackagesList.cmake` file as an `EX` package, if that directory exists, then its Dependencies.cmake files get processed.

In the short term the way to fix this is to just comment out ForTrilinos in those two files.  But that will mean that ForTrilinos developers will not be able to configure ForTrilinos with Trilinos for now.  The solution for that would be to change ForTrilinos to be treated as an Extra Repo instead of an inserted package.





The problem is that ForTrilinos/src/utils/cmake/Dependencies.cmake

**Comment by bartlettroscoe** [comment]
NOTE: You can reproduce this failure by just cloning ForTrilinos in the right place with:

```
$ cd Trilinos/
$ ./clone_extra_repos.py --extra-repos=ForTrilinos_repo
```

and then *any* configure of Trilinos will fail.

For example, I verified this with:
```
./checkin-test-sems.sh --enable-all-packages=off --enable-packages=Teuchos --no-enable-fwd-packages --do-all
```

which failed the configure right away.

I am pushing a fix right now to remove ForTrilinos from the list of inserted packages.  I will describe what I believe is the best way to move forward from here in the next comment after the push.

**Comment by bartlettroscoe** [comment]
@aprokop,

I just pushed the tested commit dcb8dad that removes ForTrilinos from the list of inserted packages.

In my opinion, the way to allow ForTrilinos develoeprs to keep developing on ForTrilinos against Trilinos is to change ForTrilinos into an extra repo.  For that, you just need simple PackageList.cmake and TPLsList.cmake files as described at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-repository-core-files

Then you just clone ForTrilinos at the base level of Trilinos instead under Trilinos/packages/ and then configure Trilinos with `-DTrilinos_EXTRA_REPOSITORIES=ForTrilinos`.  That will work because no existing Trilinos packages have even an optional dependence on ForTrilinos.

I can do a PR for the trilinos/ForTrilinos repo for this change if you like.
