### ISSUE TITLE
Reorganize Belos adapters into subpackages

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#21]
Belos offers [a number of adapters](https://github.com/trilinos/Trilinos/tree/master/packages/belos) for their linear solvers, most notably Epetra and Tpetra. Unfortunately, there is no adapter for Thyra though. – Oh wait, [there is one](https://github.com/trilinos/Trilinos/blob/master/packages/stratimikos/adapters/belos/src/BelosThyraAdapter.hpp)! In Stratimikos.

**Comment by mhoemmen** [comment]
@trilinos/belos

The original title of this bug was "Belos/Stratimikos: Move BelosThyraAdapter.hpp to Belos".  If we're going to move Belos' adapters around, we might as well reorganize them into subpackages.  That would make it easier for Belos to express dependencies on other packages.

**Comment by tawiesn** [comment]
Btw: the Belos adapter for Xpetra is in MueLu. This is definitely the wrong place.

**Comment by tawiesn** [comment]
In order to close this issue the following subtasks have to be completed:
- [ ]  Move Epetra adapter to sub-package belos-epetra
- [ ] Move Tpetra adapter to sub-package belos-tpetra
- [ ] Move Thyra adapter from Stratimikos to belos and create a new sub-package belos-thyra
- [ ] Move the Xpetra adapter from MueLu and create a new sub-package belos-xpetra

belos-thyra and belos-xpetra both depend on Epetra and/or Tpetra but they should not depend on belos-epetra and belos-tpetra. The new subpackages may have required (instead of optional) dependencies on the corresponding linear algebra implementation. Could this cause dependency issues?
