### ISSUE TITLE
Test Zoltan2_OrderingScotch_MPI_4 hanging on crf450

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2131]
**CC:** @trilinos/zoltan2

## Description

The test `Zoltan2_OrderingScotch_MPI_4` is only run in automated builds associated with the CI build run on the machine `ceerws1113` linked to from [here](https://github.com/trilinos/Trilinos/wiki/Policies--%7C-Testing#post_push_ci_testing) and the [checkin-test-sems.sh](https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing) script.  This test is currently passing fine when run on the machine `ceerws1113` as shown here:

* https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-01-04&limit=0&filtercount=2&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=Zoltan2_OrderingScotch_MPI_4&field2=buildstarttime&compare2=84&value2=now

However, for some reason, this test started hanging on my machine `crf450`.  It is blocking my push with the checkin-test-sems.sh script.  The test shows the output:

```
Starting everything
UserInputForTests, Read: ./simple_ordering.mtx
UserInputForTests, Read: ./simple_ordering_coord.mtx
NumRows     = 25
NumNonzeros = 25
NumProcs = 4
Going to solve
Ordering does not support distributed matrices.
Ordering does not support distributed matrices.
Ordering does not support distributed matrices.
```

and then just hangs and times-out at 300s.  The passing test shown, for example, at:

* https://testing.sandia.gov/cdash/testDetails.php?test=43287778&build=3314362

shows that same output and the line:

```
Scotch Ordering test with 4 processes has test return code 0 and is exiting in the PASSED state
```

The version of Trilinos I used to test this was:

```
commit 052a35ccf89d09ae9d1ca13f40ee469f84aafcb3
Author: Jonathan Hu <jhu@sandia.gov>
Date:   Thu Jan 4 15:49:05 2018 -0800

    Testing: geminga: disable complex for cuda builds
    
    This commit removes scalar type complex<double> from the configure line,
    pending resolution of github issue #2115.

M       cmake/ctest/drivers/geminga/TrilinosCTestDriverCore.geminga.gcc-cuda.cmake
M       cmake/ctest/drivers/geminga/ctest_linux_nightly_mpi_release_muelu_kokkos_refactor_cuda_geminga.cmake
```

I produced this on crf450 with:

```
./checkin-test-sems.sh --no-enable-fwd-packages --enable-packages=Zoltan2 --local-do-all
```

with that above version of Trilinos.

**Comment by bartlettroscoe** [comment]
Since this test is passing on the post-push CI machine `ceerws1113` I will leave this test enabled for that build (and every other build for Trilinos).  To to avoid having this test trip up other people trying to push with the checkin-test-sems.sh script (which more people will need to use for now until the PR testing gets fixed), I will disable the test just for the checkin-test-sems.sh script.

**Comment by MicheldeMessieres** [comment]
@kddevin @bartlettroscoe Karen I could look into this.

Note the failing test output is slightly different as the line "Ordering does not support distributed matrices." appears 4x for pass and 3x for fail. Guessing this issue is related to some procs throwing while just one continues and hits the comm barrier.

However I may be delayed to test this properly as my sems access has expired - working on getting that fixed. Karen I expect a short term fix is to just disable the #ifdef MDM temp debugging code.

**Comment by bartlettroscoe** [comment]
> Guessing this issue is related to some procs throwing while just one continues and hits the comm barrier.

I have verified with the automated test [TeuchosCore_testTeuchosTestForTermination_2_MPI_4](https://testing-vm.sandia.gov/cdash/testDetails.php?test=42749316&build=3247013), for example, that if one processor dies (by calling `std::terminate()`) then this MPI implementation will bring down the other processes as well.

We could add tests for throwing uncaught exceptions as well but my guess is that it should have the same behavior. 

Could the test be updated to print which process ranks is printing which line?  That might help to debug this.  (In general, of more than just the root process prints, then each line should be prefixed with the proc rank.  But that will create mangled output in general.)

**Comment by egboman** [comment]
One option is simply not to run this test in parallel. However, it might be useful to check that Zoltan2 gives a graceful exit if somebody attempts parallel ordering.

**Comment by MicheldeMessieres** [comment]
@bartlettroscoe To clarify in this case we are catching the exception. I ran a few simple tests to confirm that barrier() will not hang if just some ranks call std::terminate or throw an uncaught exception (as you indicated) but will hang if the exception is caught.

I think that might be expected behavior but not sure how consistent this would across all implementations. Testing with a clang mpich build here:

```
  // This will hang - I think the test is following this pattern
  try {
    if(comm->getRank() != 0) {
      throw std::logic_error("caught exception");
    }
    comm->barrier();
  }
  catch(...) {
  }
```
  
```
  // This will not hang - uncaught exception 
  if(comm->getRank() != 0) {
    throw std::logic_error("uncaught exception");
  }
  comm->barrier();
```

```
  // Adding std::terminate will prevent hang (or we can throw it again)
  try {
    if(comm->getRank() != 0) {
      throw std::logic_error("caught exception");
    }
    comm->barrier();
  }
  catch(...) {
    std::terminate(); // prevents hang
  }
```

**Comment by MicheldeMessieres** [comment]
@egboman  I actually don’t see this exception for any of my local builds, as in I never get the statement:
     _Ordering does not support distributed matrices_
So until I get back on the SEMS I won’t be able to test this fully from my end. I was not aware the CI build was running differently.

I’m recalling now I added some comment about this exception catch as I didn’t understand why it had been setup this way. I expect we will want to make some changes here.

Also I could change this to 1 proc, add e.what() to the output for better information, and setup a PR to test if you want. Or add more rank info as Ross suggested if we keep multiple procs planning for the future. But this might need some design discussion - this test was updated for the EvaluateOrdering but never fully set up.

Note: My suggestion to remove the #define MDM code may work to prevent the hang but is not really sufficient since the caught exception can cause a hang if any code in the try block calls something like a barrier(). For example Problem constructor calls comm->duplicate() which would hang if a proc had already thrown a caught exception. I’m not sure yet where the exception is coming from though.

I think we might guarantee no hang by adding std::terminate() to the catch, or throw the exception again.

I’ll proceed however you recommend or maybe we can just hold on this since Ross fixed it for the CI. Once I get back on SEMS I’ll evaluate the differences in the builds but expect that to be at least a week or so.

**Comment by kddevin** [comment]
@egboman @MicheldeMessieres :  thanks for looking at this issue.

Ordering is performed on local matrices.  If the matrix is distributed, the ordering should be applied to each processor's local part of the matrix independently, correct?  The GraphModel should return a local graph on each processor.  

Rather than try to fix the termination, we should figure out what actually went wrong in AlgScotch.  Maybe we haven't correctly asked for the local graph instead of the global graph, or perhaps the test is not set up for this use case.  Agreeing with the comment below, I propose removing the following code in the catch Zoltan2_orderingScotch.cpp:502
    if (comm->getSize() != 1) {
      // need to resolve - exactly why is this placed here?
      std::cout << "Ordering does not support distributed matrices." <<
        std::endl;
    } else
and instead letting the catch print what the actual error was (e.what()).  Then we can decide the next step for a fix.

**Comment by bartlettroscoe** [comment]
I just pushed the commit 5c01d87 which disables this test **ONLY** for the checkin-test-sems.sh script (i.e. it is enabled for every other build of Trilinos).  Once someone can reproduce this failure and then fix it and we can confirm it is fixed, then we can revert that commit.

**Comment by egboman** [comment]
@kddevin @MicheldeMessieres 
Thanks for your comments.
We have to decide what we want Zoltan2 to do with ordering in Scotch. Karen is right most ordering methods will take a distributed matrix (or graph), extract the local part, and perform local ordering on each MPI rank. However, it looks like Scotch does not do this, probably because Zoltan2_AlgScotch.hpp was written for partitioning and builds a distributed (global) graph.
I know global ordering with Scotch is not currently supported.
Is there any option to do local ordering within each MPI process with Scotch?

**Comment by kddevin** [comment]
Thank you for reporting this issue.  It is now fixed in Trilinos/develop with PR #2415.
When you re-enable the test, please let us know if you see further problems.

**Comment by bartlettroscoe** [comment]
I re-enabled the test in commit 539d02b and verified that the test `Zoltan2_OrderingScotch_MPI_4` is enabled.  Hopefully this will also pass in the post-push CI server.  We can leave this open until that verification.

**Comment by bartlettroscoe** [comment]
As noted in https://github.com/trilinos/Trilinos/issues/2397#issuecomment-374586450, this test `Zoltan2_OrderingScotch_MPI_4` was shown to be newly added and passing in the CI iteration this morning.

Closing as complete.
