### ISSUE TITLE
Request for a windows nightly build for the Tpetra stack

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#2174]
@trilinos/framework @trilinos/kokkos @trilinos/tpetra @trilinos/belos @trilinos/muelu 
@xyshal @wppowers

The Kokkos issue at kokkos/kokkos#1313 has had some discussion about windows and the tpetra stack. Since the testing in question is really beyond the scope of just Kokkos and more of a Trilinos issue we should move any further discussion here.

I have added the package teams that were explicitly mentioned in the Kokkos issue. However, there are probably more packages that would be involved since Muelu has quite a few dependencies.

The Trilinos Framework does have an existing windows test machine that has free cycles so we have hardware to support this. What we are lacking is a driver and buy in from the package teams to support such a build.

What we would need to know is what kind of testing is expected and what kind of support is expected for a windows build.

**Comment by wppowers** [comment]
@bmpersc  From our perspective, we would like to be able to build and link Trilinos when it is configured with the packages we use. That list of packages is in the configure script I attached to the kokkos/kokkos#1313 issue. The packages that required changes were amesos, amesos2, ifpack2, kokkos, tpetra and zoltan2. Those changes are also attached to kokkos/kokkos#1313.

**Comment by ibaned** [comment]
I work on an application whose internal customer has interest in having a build of Kokkos, Teuchos, and in the future also Belos and MueLu, on Windows, as part of a roadmap to have our entire application build and run on Windows. Their interest includes enabling the CUDA backend of Kokkos on Windows. As a member of the Kokkos team I could assist with code changes to Kokkos that improve the Windows compilation, correctness, and performance situations. Kokkos has historically avoided Windows compilation due to severe non-compliance of Visual Studio, but I'm told that very recent versions (2017 and up) have corrected some of these bugs (in particular two-phase lookup).

With respect to @bmpersc 's question, a possible vision would be:
 - [ ] a nightly test on Windows which uses the packages and configurations relevant to @wppowers initially, and posts results to an (internally) visible place such as the Sandia CDash site.
 - [ ] the framework team would only be responsible for ensuring the nightly test job runs
 - [ ] package teams will be notified of (or at least can easily find out about) compilation and test failures and can reasonably be expected to review pull requests, but debugging and forming the patches can't yet be a requirement
 - [ ] some degree of support (access to machine?) for those willing to volunteer to debug, or at least documentation on how to set up such a build given a Windows machine

**Comment by mhoemmen** [comment]
How hard would it be to have a Windows virtual machine available for testing?  If it's hard don't worry about it.

**Comment by jwillenbring** [comment]
> How hard would it be to have a Windows virtual machine available for testing? If it's hard don't worry about it.

My understanding is that there should be plenty of cycles available on the (VM) test machine, but generally people are allowed to log into this machine for debugging. I think it would be possible to set up a second VM if there was demand and funding for it that mirrors the first. That said, the first machine isn't likely configured with the right compilers and such at this moment for what you are trying to do.

**Comment by mhoemmen** [comment]
@jwillenbring Clarification: something like a VirtualBox etc. virtual machine file, that we can use for our own local testing purposes.  Thanks!

**Comment by jwillenbring** [comment]
@mhoemmen I have never looked closely at that due to Windows licensing issues.

**Comment by crtrott** [comment]
I think for Kokkos to give you official windows support as Dan said we would want 
i) the framework team to maintain a windows machine with the right compiler stack (both VS and Intel for Windows which if I remember correctly was one of the customers running involved with Chris Siefert). 
ii) someone setting the test up on it
iii) access for debugging and testing. 

If we get all three things I am pretty sure that we can afford to make Windows a supported platform.

**Comment by xyshal** [comment]
Hey, just a reminder that we're very interested in getting a modern version of Trilinos compiling successfully on Windows.  If there's anything we can do to help move this along, please let us know.

**Comment by mhoemmen** [comment]
@maherou

**Comment by jwillenbring** [comment]
@bmpersc @william76 Do you know if we have access to an Intel compiler on Windows currently?

**Comment by bmpersc** [comment]
To my knowledge the site license is only for Linux, so we would have to purchase one for windows.

**Comment by jwillenbring** [comment]
We do not currently have an Intel compiler on our Windows VM. Is there anyone who could get access to a Machine at Sandia who has time and interest in this effort? The @trilinos/framework team cannot devote significant resources to this at least until after the Pull Request testing is farther along.

**Comment by mhoemmen** [comment]
@jwillenbring Must the machine be at Sandia?
