### ISSUE TITLE
Proposing Tpetra::subview, a flexible free function which returns a view of a existing Tpetra::MultiVector in the spirit of Kokkos::subview

### ISSUE THREAD

**Issue by Novermars** [trilinos/Trilinos#2184]
At this moment, Tpetra::MultiVector offers the member methods MultiVector::subView(NonConst) and MultiVector::offsetView(NonConst). I would like to propose a new free function Tpetra::subview which generalizes these two functions.

First of all, why a free function instead of a member method: There are a couple of reasons, first and foremost, there already is a subView member method, as described above. Secondly, Kokkos uses a free function Kokkos::subview. Having Tpetra be consistent with Kokkos, then it would be easier for users to use both libraries. And finally, MultiVector already has a great number of member methods. Adding more would is something that might be preferred to be prevented. 

In my mind, I had the following interface:
```
namespace Tpetra
{
    using MV = typename Tpetra::MultiVector;
    MV subview(MV const& mvec, std::pair<int, int> rowRange,
                               std::pair<int, int> colRange);
}
```

The aforementioned member method all return a Teuchos::RCP to a MV, but since Kokkos::subview returns a Kokkos::view, I opted to be consistent with Kokkos. This can be changed of course.

Unfortunately, the mentioned interface does not support noncontiguous rows or columns. A possible solution would be an overload taking two tuples with indices of the requested rows and/or columns.

And just like with Kokkos, it would be nice to have an "all rows/cols" tag, just like Kokkos::ALL().

Let me know what you think!

**Comment by aprokop** [comment]
@trilinos/tpetra

**Comment by mhoemmen** [comment]
@Novermars Thanks for writing the proposal here!  It's helpful for discussion and a better distribution of work if we move public feature requests from e-mail to GitHub.  I appreciate that you took the time to do this.

I agree that this should be a free function.  It should return MV and not RCP<MV>, like Kokkos.  We should overload it like `Kokkos::subview`, and the overloads that view a single column should return `Tpetra::Vector`.  I have a few questions:

  1. Do you mean for the row ranges to be per MPI process, or global (over all processes in the MultiVector's communicator)?  
  2. What should the returned MV's Map be?  (This gets tricky even with `offsetView*` if the offset is nonzero.)
  3. A true "view" of a noncontiguous set of row indices would complicate the implementation and may perform poorly.  We could use a "generalized view" approach, in which the returned MV is a separate allocation that copies back on destruction.  However, that could confuse users.  What do you think?

Thanks!

**Comment by Novermars** [comment]
@mhoemmen 
Hi Mark,
These questions are difficult for me to answer, as we consider only the latter limited case of contiguous views of locally replicated MultiVectors when we care about non-full row ranges.

Let me try anyway, please tell me if I said something stupid...
1. I think global would be the most intuitive, and it would be the same as in Kokkos
2. No clue to be honest, what are the options?
3. If I recall it correctly, one of the promises Tpetra makes is that there are no hidden copies. So it might be better to take the penalty hit by default and possibly add a parameter which allows the user to specify the strategy. Downside is that this clutters the interface and needs to documented very well, if the performance is really poor.

As I said in the email correspondence, I am just a mere intern who is still learning a lot on these kind of things. For some reason they don't teach you about this stuff in university.

**Comment by mhoemmen** [comment]
@Novermars Thanks for your answer!  It's good to have a novice's perspective, because I have been working on Tpetra for eight years and may not realize what parts of the interface are not intuitive.  (I already know that many parts are not ;-) .  Tpetra is a palimpsest that I inherited, and I couldn't change as much as I would have liked.)

An interface like this really needs to be local to each MPI process.  Tpetra already has collective (global) interfaces for redistributing data over MPI processes (doImport, doExport, {import, export}AndFillComplete); or changing the distribution (replaceMap, removeEmptyProcessesInPlace), possibly to a subset of processes.

Here are some issues:
  - The interface returns a new MultiVector (MV), so the returned MV needs the right Map.
  - If the new MV Y views some subset of rows of another MV X, then Y's Map needs to have only that subset of row indices in it.
  - Map creation is, in general, currently an MPI collective.[1][2]

This means that
  - if you want the interface to have local semantics, and
  - if you want the interface to be more general than `offsetView*`, 

then the interface must take a pre-constructed Map as an input argument.  (I don't like how `offsetView*` works for nonzero offsets.)  That Map would be the returned MultiVector's Map.  The Map suffices for specifying which rows to view / copy.  Users would need to specify a range of column indices as well.  So, it might look like this:
```
template<class MV>
MV subview (
  const MV& X, 
  const typename MV::map_type& map, 
  const std::pair<typename MV::local_ordinal_type, typename MV::local_ordinal_type> columnIndexRange);
```

Regarding noncontiguous sets of row or column indices, `Kokkos::subview` does not currently support this.  When users say they want to view noncontiguous sets of row (or column!) indices, often what they _really_ want to do (or should do, for best performance) is copy from the noncontiguous view to contiguous storage.  For example, consider Belos' pseudoblock GMRES.  Suppose that you start by solving 10 right-hand sides at a time.  Some noncontiguous subset of right-hand sides converges.  You want to fix their solutions, remove those right-hand sides from the solve, and keep going with the remaining right-hand sides.  Belos currently does this by creating a MultiVector that views a noncontiguous subset of columns (the right-hand sides that have not yet converged), then running pseudoblock GMRES with that view.  However, this is inefficient, because all the computational kernels (e.g., sparse matrix-vector multiply, multivector update (AXPY), GEMM, and GEMV) are optimized for the case of contiguous columns.  A more efficient approach would be to copy out those columns into a contiguous MultiVector first. 

The "copy noncontiguous things into contiguous storage" interface would look different from the "view noncontiguous things" interface.  Belos has both interfaces, actually.

Regarding the "generalized view" (copy back on destruction) idea, this can be helpful for dealing with things like "getting a host view of GPU device data."  However, it may be confusing for users to have many different generalized views flying around.  If Tpetra were to allow this, I think each Tpetra object should only permit one generalized view of itself to exist at a time.  If users attempt to create another generalized view before the first has fallen out of scope, the Tpetra object should throw an exception or otherwise report the error.  I've already talked with you and Jonas about different interfaces for viewing data that would avoid this problem.

Does this explanation help?  Would the above interface serve your needs?
Thanks!

Notes:

  1. Map has a constructor that takes lists of indices on each MPI process.  Map also has a method that returns the global number of indices over all processes in its communicator.
  2. I have proposed changing Map so that it lazily (i.e., on demand) initializes global quantities.  This would change Map methods like getGlobalNumElements to have collective semantics, at least on first call.  (Right now, they just return the value.)  We are very likely to make this change at some point, since it will have benefits for MueLu (algebraic multigrid) setup cost.  @csiefer2 can tell you more.  I would be even a bit more radical than that, and expose such methods as nonblocking collectives by having them return something like an `std::future`, but nobody else seems to like that ;-) .

**Comment by mhoemmen** [comment]
@kddevin @tjfulle @csiefer2 @jhux2 @william76 @DrBooom 
This might be relevant to Tpetra refactoring discussions.

**Comment by Novermars** [comment]
Hi Mark,

Thanks the great answer. I have definitely learned some stuff. Before I go into detail, let me first answer your question if this interface would serve our needs:

To which I can answer yes. In PHIST we have two classes of MultiVectors. (1) Normal, distributed MultiVectors and (2) small (small!) locally replicated MultiVectors. At this time, we only care about general blocks (i,e, rows and columns) for the locally replicated MultiVectors, for which it is easy to get the right map. It is in this case that we use the dirty trick/workaround mentioned in our email conversations. So with the interface you proposed, it would be easy to implement it properly.

Ideally, for ease of use in this case, it would be nice to have the interface I proposed and if it is not locally replicated it throws an exception (or in a perfect world, a compile time error), but this clutters the interface and may not be intuitive for beginner users. (As they will likely want to use this easier/"more intuitive" interface and then run into errors)

For our distributed MultiVectors, we only consider views of columns, so in this case there would be no problems too. I'd have to ask Jonas if it would be beneficial to us to also consider views of not all the blocks, but I don't think so. And if that would be the case, your proposed interface also allows us to do that.

Regarding the non-contiguous views and the associated copying, I agree with what you say and think you mentioned the right way to go. Especially as having two interfaces would allow Tpetra to keep their "no hidden copies" mantra. As far as I can see, if the details are nicely hidden from users, there are no downsides. The time saved by a better cache performance due to improved locally may very likely be higher than the time it took for the allocation and the copying. But of course, this has to be measured :)

The generalized view idea sounds nice, and having only one of such view at the same time sounds fair. But what in the case where you want to have two disjoint views of the same object? So V = [V1 V2 V3] and you want to view V1 and V3 at the same time in the same scope. Would this be also possible then? I don't know if such things ever come up in practice, but it might be worth just thinking about these edge cases.

Thanks once more for the excellent reply!

Nigel

**Comment by mhoemmen** [comment]
@Novermars wrote:
> Ideally, for ease of use in this case, it would be nice to have the interface I proposed and if it is not locally replicated it throws an exception (or in a perfect world, a compile time error)....

I thought a little more about the interface since my last reply.  The current `offsetView*` methods just reinterpret local storage on each process using a new Map.  They don't use the new Map to decide what to view; they just apply the Map to some block of memory.  If that's what you want for the new interface, then it doesn't need communication.  (Making a new Map may need communication.)  This means it should work just fine with distributed (as well as locally replicated) multivectors.

> Regarding the non-contiguous views and the associated copying, I agree with what you say and think you mentioned the right way to go. Especially as having two interfaces would allow Tpetra to keep their "no hidden copies" mantra.
> ...
> The generalized view idea sounds nice...

The second statement seems to contradict the first.  A "generalized view" is a (deep) copy, that copies back (if the view is write-only or read-write) to the original when its destructor is called.  It "looks like a view," but is actually a copy.  That's literally a "hidden copy."

I would prefer a "strided assignment" interface, like (a generalization of) `Belos::MultiVecTraits::Assign`.

Thanks!
