### ISSUE TITLE
Pamgen,kokkos-kernels: NVCC build error with -D CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS=ON

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2221]
kokkos-kernels requires `-D CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS=ON` for CUDA builds, even with complex arithmetic disabled.

https://github.com/trilinos/Trilinos/issues/2115#issuecomment-357750048

However, Pamgen does not build, given those settings.

@trilinos/kokkos-kernels @trilinos/pamgen @trilinos/framework 
CC: @rrdrake @prwolfe

## Expectations

  1. Whatever flags kokkos-kernels needs to build on CUDA, they need not to block building other essential packages.
  2. kokkos-kernels needs to document its CMake requirements.
  3. kokkos-kernels needs to fail at configure time, with an informative message, if the CMake variables that it needs are not set.

## Current Behavior

```
$ make
[  0%] Linking CXX shared library libpamgen.so
nvcc fatal   : No input files specified; use option --help for more information
make[2]: *** [packages/pamgen/src/libpamgen.so.12.13] Error 1
make[1]: *** [packages/pamgen/src/CMakeFiles/pamgen.dir/all] Error 2
make: *** [all] Error 2
```

## Motivation and Context

Many downstream tests, including Belos and Ifpack2, depend on Pamgen.  This blocks adequate Trilinos testing on CUDA.

## Steps to Reproduce

```
$ module list
Currently Loaded Modulefiles:
  1) sems-env                    3) sems-cmake/3.3.2            5) kokkos-cuda/8.0.44
  2) kokkos-env                  4) sems-gcc/5.3.0              6) kokkos-openmpi/2.0.1/cuda
```
CMake configuration:
```
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
-D BUILD_SHARED_LIBS:BOOL=ON
-D Trilinos_ENABLE_OpenMP:BOOL=ON
-D Kokkos_ENABLE_OpenMP:BOOL=ON
-D Tpetra_INST_OPENMP:BOOL=ON
-D Trilinos_SHOW_DEPRECATED_WARNINGS:BOOL=ON
-D Trilinos_ENABLE_Fortran:BOOL=OFF
-D TPL_ENABLE_CUDA:BOOL=ON
  -D KOKKOS_ARCH="SNB;Kepler35"
  -D Kokkos_ENABLE_Cuda:BOOL=ON
  -D Kokkos_ENABLE_Cuda_UVM:BOOL=ON
  -D Tpetra_INST_CUDA:BOOL=ON
  -D Kokkos_ENABLE_Cuda_Lambda:BOOL=ON
  -D CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS:BOOL=ON
  -D CMAKE_CXX_FLAGS:STRING="-Wall"
  -D Trilinos_CXX11_FLAGS:STRING="-std=c++11 --expt-extended-lambda"
-D TPL_ENABLE_MKL:BOOL=OFF
-D TPL_ENABLE_Matio:BOOL=OFF
-D TPL_ENABLE_SuperLU:BOOL=OFF
-D TPL_ENABLE_Zlib:BOOL=OFF
-D TPL_ENABLE_Netcdf:BOOL=OFF
-D TPL_ENABLE_HDF5:BOOL=OFF
-D TPL_ENABLE_ParMETIS:BOOL=OFF
-D TPL_ENABLE_Boost:BOOL=OFF
-D TPL_ENABLE_BoostLib:BOOL=OFF
-D TPL_ENABLE_yaml-cpp:BOOL=OFF
-D TPL_ENABLE_MPI:BOOL=ON
```

## Your Environment

- develop branch, commit 400765e21e17dfb995e0f4a2759ce9c5f961b685 (likely not related)

## Related Issues

* Blocks #2115

**Comment by bartlettroscoe** [comment]
FYI: I just hit this but note that when using the CMake Ninja generator as if CMake 3.14 it will automatically switch to using `*.rsp` response files.  That is good for a 'static' library build where `ar` is used to create the `kokkoskenerls` library.  But that is bad when using 'shared' libs as the `nvcc` command itself is used to create the `kokkoskernels` library.  It turns out that you need to build with static libs.  Don't know what is going on with Pliris but we will find out soon enough due to the need for ATDM APP Gemma to enable Pliris at some point soon.

The core problem is that `nvcc` just does not support response files.  Therefore, if Trilinos is going to continue to build with `nvcc` wrapper and keep growning in the number of object files, we are not going to need to change how we build Trilinos code to avoid commandline-too-long errors :-(  In the meantime, I have asked Kitware to update future versions of CMake to allow us to control where CMake uses responses files with more control.  (I would really like this to be on a target-by-target and object-by-object bases if needed.)
