### ISSUE TITLE
Framework: Windows builds not reporting to dashboard

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#2237]
Again

**Comment by bmpersc** [comment]
@csiefer2 It looks like the build did run last night, but some how it didn't make it to the dashboard. According to the log the submissions were successful. I will look to see if there was an error that would have caused this, but I suspect this one might just have been a network fluke and we'll need to see if tonight's build will submit correctly.

**Comment by bmpersc** [comment]
@csiefer2, The issue seems to have been a recurrence of a previous issue. The job was actually submitting, but it was dying at the update step which stopped the job at that point. The issue was the too long filename issue when checking out a Kokkos-kernels files. I'm not sure why the previous solution of putting  longpaths = true into the git config stopped working. I was able to get the update working again by putting the above option into the git config that is in the installation. In some ways this is better, everyone has it now, in other ways this is evil that I've modified the base install.
