### ISSUE TITLE
Tpetra: logic mistake in map getMinGlobalIndex/getMinAllGlobalIndex

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#2250]
When a rank holds no GIDs the map will return 0 as its min global index. 

@trilinos/tpetra 

@mhoemmen @csiefer2 

## Expectations
The map should return the true minimum GID across ranks and not `indexBase` when a rank holds no GIDs. A reasonable value needs to be returned by `map.getMinGlobalIndex()` on a rank with no GIDs.

## Current Behavior
As explained above, a map will `map.getMinAllGlobalIndex()` return `indexBase` if a process holds no GIDs. That is always wrong if the GIDs in the map are offset from IndexBase.

## Motivation and Context
If you have the following distribution of GIDs:
p0: [7, 8, 9]
p1:  [10, 11, 12]
p2: [13, 14, 15]
p3: []

map.getMinGlobalIndex() returns 0 on rank 3 and map.getMinAllGlobalIndex() returns 0. This type of GID partition happens after repartitioning a problem. I believe that most people will have 0 as the first index in maps, but this is not the case for multi physics problem represented by Xpetra BlockedMatrix.

## Definition of Done                                                 
- [ ] `getMinGlobalIndex()` needs to return a sensible value when no GIDs are on the local rank
- [ ] `getMinAllGlobalIndex()` needs to compute the min based on the range of GIDs used in the map.

## Possible Solution
I think that returning `Teuchos::OrdinalTraits<GlobalOrdinal>::max()` when calling getMinGlobalIndex on a rank that holds no GIDs is reasonable. Using `Teuchos::OrdinalTraits<GlobalOrdinal>::invalid()` instead of max() can create issues when using MPI_reduce(MIN,...) since invalid could return 0 if the `GlobalOrdinal` type is `int` or some signed type.

## Steps to Reproduce
Create a map using GIDs strictly higher than 0 and assign no GIDs to one rank, then call `getMinGlobalIndex()` and `getMinAllGlobalIndex()`

## Additional Information
It might be useful to check what Epetra is doing in this situation, it could have a work around or might have the same bug...

**Comment by mhoemmen** [comment]
Thanks @lucbv !  It looks like you're pushing commits that intend to fix this.  Could you please submit them as a pull request instead, and assign @csiefer2 and I as reviewers?  It would also help to test downstream through Panzer / Drekar, since those packages depend heavily on Tpetra properties.

@lucbv wrote:
> I think that returning `Teuchos::OrdinalTraits<GlobalOrdinal>::max()` when calling `getMinGlobalIndex` on a rank that holds no GIDs is reasonable.

Epetra made the unfortunate choice to return an inclusive index range `[map.MinMyGID(), map.MaxMyGID()]`.  Tpetra imitated this behavior (FYI, that long predates me starting work on Tpetra).  This issue shows that returning an inclusive index range leads to ambiguity in the case where a process has no indices.

What should `getMaxGlobalIndex` return?  Users might like to write loops like this:
```
for (GO g = map.getMinGlobalIndex(); g <= map.getMaxGlobalIndex(); ++g) { /* ... */ }
```
Users can't do that right now on processes where `map` has zero indices, since both methods return the same number (the "index base").  If `getMinGlobalIndex` returns the max GO, then `getMaxGlobalIndex` could return one less than that; that would make it possible to write loops like the above loop.  Does that sound like a good idea?

> Using Teuchos::OrdinalTraits<GlobalOrdinal>::invalid() instead of max() can create issues when using MPI_reduce(MIN,...) since invalid could return 0 if the GlobalOrdinal type is int or some signed type.

`Teuchos::OrdinalTraits<T>::invalid()` returns -1 for signed integer T, and the max value for unsigned integer T.

**Comment by mhoemmen** [comment]
FYI I think the issue you observed is true for both the second (contiguous nonuniform) and third (noncontiguous) Map constructors.  Could you please include tests for both cases in your pull request?  Thanks!

**Comment by lucbv** [comment]
@mhoemmen I provided a pull request but haven't had time to test the behavior. I will continue to work on this tomorrow based on your comments above.
Thanks!

**Comment by mhoemmen** [comment]
@lucbv Thanks!  I posted some suggestions in the pull request review (#2251).

**Comment by aprokop** [comment]
> If getMinGlobalIndex returns the max GO, then getMaxGlobalIndex could return one less than that; that would make it possible to write loops like the above loop. Does that sound like a good idea?

I think that's the best option.

**Comment by cgcgcg** [comment]
Why not return the min GO? If min of an empty interval in infinity, shouldn't the max be -infinity?

**Comment by mhoemmen** [comment]
@cgcgcg Do you mean `getMinGlobalIndex`?  We have to be careful because Tpetra (still) has users who insist on unsigned GO types.  One of the plans for Tpetra is to eliminate GO as a template parameter, so that GO is always a signed 64-bit integer.  That would make it easier to do what you're suggesting.

**Comment by cgcgcg** [comment]
@mhoemmen No, the call for the local min should return +infinity as @lucbv proposed. I think that the call for local max should return -infinity aka min GO. The global min/max calls are not affected by that. And the looping example you gave above also works, no?

**Comment by lucbv** [comment]
@cgcgcg, do you want something along the following lines:
```
if(numLocalElements == 0) {
   minMyGID = Teuchos::OrdinalTraits<GO>::max();
   maxMyGID = Teuchos::OrdinalTraits<GO>::min();
}
```

**Comment by cgcgcg** [comment]
Yep, that's what I mean :-)

**Comment by mhoemmen** [comment]
@lucbv @cgcgcg I think that's OK, but if GO is unsigned, `maxMyGID_` should be `std::numeric_traits<GO>::max()-1` instead.

Note how I'm favoring `std::numeric_traits` instead of `Teuchos::OrdinalTraits`.... General pattern is to use standard library stuff whenever possible.  `Tpetra::Details::OrdinalTraits` only exists for CUDA device functions.  Hopefully later CUDA versions will fix standard library `constexpr` stuff.

**Comment by cgcgcg** [comment]
@mhoemmen For unsigned GO, the local min would be zero. Is there a use case that would create trouble?

**Comment by mhoemmen** [comment]
@cgcgcg It's troublesome to have two separate implementations, based on whether GO is signed or unsigned.  Tpetra::Map already needs to do that, though.  The main use case of interest is iterating from my min GID to my max GID.  In that case, it would help for my max GID to be less than my min GID when my process owns no indices.  That way, users would not need to check whether my process owns no indices (as they currently must do) before writing that loop.

**Comment by cgcgcg** [comment]
I am not sure I understand what you mean. If minLocalGID returns max<GO> and maxLocalGID returns min<GO>, then that does the job, no?

**Comment by mhoemmen** [comment]
@cgcgcg Yes, that is correct.  It might be nicer for my process' min and max GID both to be "large numbers" that look obvious when debugging, rather than zero.  Furthermore, we need to make sure that this approach works for the all-reduce (for computing the min and max GID over all processes) as well.

**Comment by lucbv** [comment]
Thanks all, the most recent auto-tester build passed without issues and @mhoemmen comments have been incorporated. All lights are green in the pull request so I merged it!

**Comment by mhoemmen** [comment]
Thanks @lucbv !  Thanks also @cgcgcg for comments!

**Comment by mhoemmen** [comment]
@lucbv Just curious -- why did you think this would be "Results Impacting"?  Would it change behavior on processes that didn't already have zero things?

**Comment by lucbv** [comment]
@mhoemmen I think that this might break packages down stream, I was not sure how to label that properly. Also we labelled it as a bug which is fine but I view it more as a design decision. If you are fine with returning a 0 when there is no GID on the local rank then maybe it's fine, it is just not very helpful?

**Comment by mhoemmen** [comment]
@lucbv wrote:
> I think that this might break packages down stream, I was not sure how to label that properly.

"Results Impacting" specifically means "users won't get the same bitwise results as before."  For example, if Ifpack2 were to change the order in which it does Gauss-Seidel, that would change the bits.

We're not supposed to push things that break packages downstream ;-) .

> Also we labelled it as a bug which is fine but I view it more as a design decision.

It was kind of a bug.  Now the global min GID makes more sense if some processes have zero indices.
