### ISSUE TITLE
Stokhos: failures in unit test using MueLu

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#2258]
The recent changes in MueLu to cache multivectors within the multigrid hierarchy apply appear to have broken a Stokhos [test](https://testing.sandia.gov/cdash/testDetails.php?test=44773426&build=3395325).

I can fix the error by using the right-hand side vector's map for the residual vector allocation, rather than the matrix's range map.  However, a number of other MueLu unit tests fail as a result.

@trilinos/muelu @trilinos/stokhos @csiefer2

**Comment by etphipp** [comment]
I'm not really sure what is peculiar about Stokhos to exhibit this problem, since it has to do with the maps and not the scalar type.  My only guess is the matrix that is passed to MueLu is constructed from a Kokkos::CrsMatrix with the row and column maps specified explicitly.  However the exception is thrown even when run with just a single processor, when the row, column, domain, range, and RHS maps are all the same.

**Comment by mhoemmen** [comment]
Is there something going on with the Kokkos::View hidden dimension?

**Comment by etphipp** [comment]
I guess it could, but I don't see how that is related to the map changes in Chris' commit.

It is curious that the exception says that axpy() is called with two vectors, one with dimension 100 and the other 10, and the hidden dimension is 10 in this case.

**Comment by mhoemmen** [comment]
I remember seeing this before somewhere in MueLu, but I don't remember quite why....

**Comment by jhux2** [comment]
Closing as a duplicate of #2254.
