### ISSUE TITLE
MueLu: efforts to consolidate input interfaces?

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#2269]
@trilinos/muelu 

## Question
Are there any efforts to consolidate and unify the various MueLu input interfaces?

## Motivation and Context
Right now, there are various ways to create a MueLu hierarchy, e.g.
- easy XML interface
- advanced XML interface
- C++ interface
- ML parameter list

Here are some of my thoughts:
- It seems to me that not all MueLu features are accessible from all input interfaces. Problems might arise in future if the discrepancy between capabilities between the input interfaces grows. How can this be addressed?
- Which of these interfaces are actually used? Can we get rid of the unused ones?

**Comment by jhux2** [comment]
@trilinos/muelu

**Comment by tawiesn** [comment]
@mayrmt I guess it is not that easy to get rid of any of these interfaces. The C++ "interface" is not supposed to be a user interface, but you cannot technically get rid of it. I don't know how many people are using the ML interface. This is certainly the most flaky one which you probably don't want to support.
I know that many think of the easy user interface to be the most convenient one. Even though i certainly understand that it is a design flaw and will cause a lot of trouble at some point as you cannot support it any more with a growing number of features (the cauliflower problem that you might know from other FEM code input decks). You will need to spend more time adding a feature to the easy input deck (supporting all necessary combinations) than for adding the feature itself. It is not scaling.
The advanced XML input deck is a one-to-one representation of the C++ input deck which should cost you zero time if you add a new Factory. If you need a new xml-related feature this costs you some time once. But first you should think whether it is the right approach to solve your problem. The advanced XML input deck is the only one (with the C++ interface) which perfectly scales with a growing source base. There is a reason why LEGO(TM) bricks are so successful. The only disadvantage is that you need a good understanding how it works.

**Comment by aprokop** [comment]
Advanced input deck is a) requires a developer knowledge of MueLu as @tawiesn, and b) from my admittedly old experience requires a significant investment in the writing one for a new capability. The second point is also done for the easy deck inside the interpreter.

I guess, my view on advanced input decks vs easy input decks is that in the former users exchange input decks, while in the latter people can write their own using user's manual.

Overall, C++ interface is not an interface. The ML interface should be frozen, and interpreted into one of the MueLu interfaces underneath. The main question is the difficulty of introducing new capabilities in the easy input deck. And (without fully looking into it) my guess would be that it really is the breakdown of the MueLu "independent" factory model, where you can't really independently swap factories out which leads to combinatorial explosion.

**Comment by mayrmt** [comment]
Regarding the ML interface, there seems to be a ```ML2MueLuParameterTranslator```. I don't know about its current state, but it looks like it could be used to replace a direct ML interface by doing two steps, namely
1. translate an ML parameter list to a MueLu list
2. use the regular MueLu Parameter list interpreter.

Or we could just get rid of ML input decks, because plain ML input decks probably don't work with MueLu, but we need to add MueLu specific parameters manually. At least, comments in the MLParameterListInterpreter suggest that.

**Comment by mayrmt** [comment]
@tawiesn If the C++ interface is not meant to be a user interface, can we at least _not_ advertise it in the tutorial? To me, it looks like the tutorial treats the xml and the C++ interface equally when it comes to using MueLu in your application code.

**Comment by tawiesn** [comment]
> @tawiesn If the C++ interface is not meant to be a user interface, can we at least not advertise it in the tutorial? To me, it looks like the tutorial treats the xml and the C++ interface equally when it comes to using MueLu in your application code.

Are we talking about the same tutorial? In the MueLu tutorial we have 11 chapters (on about 70 pages) about the easy and the advanced XML input decks. There is only one chapter (chapter 12 with 7 pages) which gives a very rough short example how to use MueLu through a plain C++ interface. Furthermore, chapter 12 is in the expert section of the tutorial and therefore clearly marked to be meant for experts only. I don't think that 7 versus 70 pages are an advertisment of the C++ interface and i cannot see that we treat the xml and the C++ interface _equally_ :-)
In contrast, i think, from a political point of view one should not forget about the C++ interface. There are many potential users out there who are afraid of xml input decks, who do not want to use additional solver-specific xml files or similar things just for the linear solver. There are many users who always solve the same kind of problem with the same identical settings, who would never think of using MueLu if there is not a C++ API, which allows to use the multigrid solver directly from within their C++ applications. Btw. there would be many more users if we would have a python interface to MueLu, too.

**Comment by mayrmt** [comment]
@tawiesn I didn't think of the use cases that you just outlined. Makes sense! Though, this still leaved the question: How can we keep all interfaces equipped with the same functionality and not implementing certain features in certain interfaces only?

**Comment by cgcgcg** [comment]
In principle, the C++ interface and the expert XML interface should be 1-to-1. In my opinion, the easy interface should just translate to the expert XML interface, not try to build something by itself. That way it is a subset of the expert interface. And the ML interface can just translate to the easy interface. But there are probably some use cases that I am forgetting..

**Comment by lucbv** [comment]
Let us not forget that we also have facade class...

**Comment by tawiesn** [comment]
@lucbv Yes, let's not forget about facade classes. But facade classes are not a real interface. Facade classes are templates. In a facade class you define a list of potential parameter that are then filled into pre-set templates. The template code can be written in any valid MueLu input style (easy-input-xml, extended xml and in principle also C++).

As a fun fact: we could implement the easy-input deck in a Facade class and completely get rid of the easy xml-input parameter list interpreter C++ code.

**Comment by tawiesn** [comment]
@cgcgcg I like that idea. The main reason why we started the easy input deck was, that many users wanted a shorter and more ML-like input deck. As a matter of fact: even for simple tasks, the extended-xml input deck can be quite long. There were no facade classes at that time.

**Comment by tawiesn** [comment]
> Though, this still leaved the question: How can we keep all interfaces equipped with the same functionality and not implementing certain features in certain interfaces only?

@mayrmt Yes, we should have the same functionality in all interfaces. The problem is, that the extended xml input deck does not the most general form of the keep mechanism (that we only have in the C++ interface and only if you really know what you are doing. It's not that easy in the C++ interface, too. It's some work in the extended input deck to add that feature. The current implementation is only a poor-mans-implementation: a quick hack to the the most important information (transfer operators and coarse matrices as those were easy to keep due to the NoFactory thing).

I'm very sure: once we have this full implementation of a keep mechanism in the extended input deck this solves all problems. Of course, it seems that the easy input deck now has more functionality than the extended input deck. But that's not really true. It's fake. It is. It's not flexible, it consists of many implicit assumptions or thousands of if-else statements. It's not scaling. It's a hack. Of course, it is easy to implement the keep functionality for "Aggregates" in the easy input deck, but what if we do not have aggregates, if we have structured multigrid if we have whatever? Then it starts to get messy. Well, it's already a mess...

Therefore, i'd suggest: if you do something, do the right thing. Adding the general keep mechanism to the extended input deck is certainly somewhat tricky and one has to think first about how the xml files should look like. The alternative could be introducing a "KeepFactory" which naturally fits into the existing framework. Within that factory you can store the data on the level class and set the keep flag and/or write it into files on the hard disk etc. pp.
There is a framework, so why not using it?

**Comment by aprokop** [comment]
Right now, easy input deck is really a converter to C++ interface. Converting easy deck to extended deck is no easier or harder than converting it to the C++ interface. The myriad of if/else statements is not going to disappear just because you convert it to something else. This is the price you pay for it to be simple. So I disagree with @tawiesn about it being a hack, rather consider it to be a tradeoff.

In addition, even the easy interface deck does not have the proper keep mechanism. It only has the necessary tools for hierarchy reuse for some simple scenarios, nothing more, nothing else.

I think some of the difficulties with a general approach to keeping objects is going to be because of the fact of duplicated names for objects. Thus, you'll need to keep both objects and generating factories, and the receiver would also need to figure out which generating factory produced the object. However, if the object you want has a unique name, the situation should be much easier.

**Comment by tawiesn** [comment]
@aprokop I'm fine with calling the easy-input deck a "tradeoff". More precisely: a 1500 lines tradeoff. A compromise which makes it as easy as possible for the end user at the costs that the code is not scalable and not maintainable. I'm working now with a lot of software architects and they would immediately reject the code not even looking at it, since it is a monolithic 1500 lines block.

In contrast, the extended xml input deck has much more functionality in less than 300 lines of code. The compromise is, that it is not as easy to use for the user, but it comes with the advantage that an average developer can understand and maintain that piece of code. Of course, this aspect is more important in industry where each line of code costs a certain amount of money. Maintaining 300 lines of code is much cheaper than 1500 + X lines of code. And less error-prone.

I agree with @aprokop that one of the challenges in adding the keep functionality in the extended xml input deck are the duplicated variable names. If you have a unique variable name, you do not need to provide the generating factory as we will return the uniquely associated data for the variable name. But i think this only works if it is a known variable name with an associated default factory in the factory manager. Other than that i'm not fully sure. Anyway: for the implementation the main challenge is to call the "Keep" routine for all variables to be kept after the "Request" but before the "Build" calls. You need to make sure, that all factories from the xml file are registered and that the inherent dependency tree has been built. And then you know which factory generates which data. Or vice versa: then you can exactly specify which variable (generated by which factory) to keep. Does that make sense?

**Comment by mayrmt** [comment]
Related to #550.
