### ISSUE TITLE
PyTrilinos: memory leak with repeated creation of CrsMatrix and solver.Iterate

### ISSUE THREAD

**Issue by guyer** [trilinos/Trilinos#2327]
Repeated creation of CrsMatrixen and AztecOO solvers causes memory to steadily leak

## Motivation and Context

We may be using PyTrilinos inappropriately, but [FiPy](https://github.com/usnistgov/fipy) creates a new CrsMatrix and AztecOO solver at each iteration. Because of this leak, we have no choice but to regularly checkpoint and kill the job.

## Steps to Reproduce

Running [this modified version of exAztecOO.py](https://gist.github.com/guyer/f4ea5a0443d7bb25c18348661b4634d3) with
```
mprof run python exAztecOO.py
```
produces this plot
![leak](https://user-images.githubusercontent.com/1830725/36928860-a22ab122-1e57-11e8-8ea7-890b89f5c32e.png)

## Your Environment

- **Relevant configure flags or configure script:**  Trilinos 12.10.1 installed from [this conda feedstock](https://github.com/guyer/trilinos-feedstock)
- **Operating system and version:**  Mac OS X 10.12.6 and Debian GNU/Linux 8 (jessie)

## Additional Information

Based on [earlier discussions on the FiPy mailing list](https://www.mail-archive.com/search?l=fipy%40nist.gov&q=subject:%22Memory+Leaks+with+Trilinos%22&o=newest) the leak may have been introduced after version 11.10.2

**Comment by maherou** [comment]
@wfspotz: Are you aware of this issue?  
@mhoemmen: How about you?

**Comment by mhoemmen** [comment]
@maherou Thanks for CCing me, but I don't contribute to PyTrilinos, other than for occasional Tpetra interface changes.  This is an Epetra + AztecOO + PyTrilinos (+ user script; see below) issue.

@guyer I'm not sure how PyTrilinos handles reference counting for deallocations, but it's interesting to me that the script you posted does not use the return value of the `main(comm,tol)` function (@maherou that's not the same thing as C/C++ "main"; it's just a function in this file / module).  The return value of `main` is an `Epetra_Vector`.  There's also a temporary involved in computing the return value, namely `x - exact`, which is also an `Epetra_Vector`.

My guess is that Python's garbage collection works like Java, in that one can define a "finalizer" that gets called whenever an object gets collected.  In this case, the finalizer should trigger `Epetra_Vector`'s destructor, I think via `RCP`'s destructor.  However, Python and Java do not necessarily promise that any object ever gets garbage collected.  This means that the finalizer might never get called.  The idiomatic fix for this in garbage-collected languages is to assign null or something like it to the variable; this makes it more likely that the object will show up as garbage and get collected sooner.

If my hypothesis holds, then there is no actual bug in Epetra, AztecOO, or PyTrilinos.  However, you should be able to rewrite the script so that it doesn't create so many large temporaries.  Instead of `main` creating an `Epetra_Vector` as a return value, change `main` so it takes an existing `Epetra_Vector` as an output argument.  Inside `main`, don't create a new `Epetra_Vector`; just call `Update` (or whatever it's called in Epetra / PyTrilinos) on it, so that it gets the result of `x - exact`.

Avoiding large temporary allocations is generally a good idea with many languages.  For example, it's standard advice for Matlab scripts.

It may make sense to change the PyTrilinos script so that it illustrates this good practice, but that's a separate issue.

**Comment by maherou** [comment]
@mhoemmen, thanks for looking at this and making these suggestions.

**Comment by mhoemmen** [comment]
@guyer wrote:
> ... but FiPy creates a new CrsMatrix and AztecOO solver at each iteration.

As you observed, this is not good practice for best performance.

First, if the graph structure (nonzero pattern) of your matrix does not change between iterations, then you can just keep the CrsMatrix and change its values.  This will save a LOT of MPI communication (that the first call of `CrsMatrix::FillComplete` needs to do in order to set up communication patterns for sparse matrix-vector multiply).  It is recommended best practice for all applications that use Epetra (or Tpetra, and presumably also "or PETSc or Hypre or ...").

Second, depending on the AztecOO solver and preconditioner you use, it may make sense to reuse the preconditioner.  Some preconditioners require MPI communication for setup.  Domain decomposition with nonzero overlap is a good example.  Other preconditioners do nontrivial local work.  "Domain decomposition with nonzero overlap, plus ILU" is a common AztecOO use case. 

@maherou , does AztecOO have a "numeric factorization" equivalent for preconditioners?  I know you can call something like `CreatePreconditioner` to force it to recompute the preconditioner, but I'm not sure if that reuses anything.

**Comment by wfspotz** [comment]
@guyer In FiPy, I assume you are creating your own Epetra.Map and Epetra.CrsMatrix objects, rather than getting them from Galeri?

**Comment by mhoemmen** [comment]
Thanks @wfspotz for the helpful explanations!

I still think avoiding unnecessary temporaries is a good idea; I'm hoping it will help @guyer .

**Comment by mhoemmen** [comment]
I'll call this one done; please feel free to reopen if the proposed script fixes don't help.  Thanks!

**Comment by guyer** [comment]
@mhoemmen  I realize that my modification of exAztecOO.py is a bit fictitious. The return value of `main()` *should* get garbage collected at each iteration of the loop. In our [production code](https://github.com/usnistgov/fipy/blob/654426c7d472712b628af057ec493d55b9812fbf/fipy/matrices/trilinosMatrix.py#L1350), we explicitly call  `del self._matrix` (an instance of `Epetra.CrsMatrix`) and, indeed, the Python ref count goes to zero at that point.

This chunk of code dates to a time when FiPy could not build coupled matrices, so to keep from exceeding memory, we only retained the matrix for one equation at a time. Changing that architecture is a deep change, even if it may present efficiency benefits.

**Comment by guyer** [comment]
@wfspotz Yes, we create our own `Epetra.Map` and `Epetra.CrsMatrix`. Using the Galeri code from your example seemed like the simplest way to illustrate the problem without getting into FIPy's idiosyncrasies.

In light of:
> The Python and C++ reference counts are hierarchical, meaning when a Python reference count goes to zero, the underlying C++ object gets deleted, but since that underlying object is an RCP, it may live on.

Is there any way for me to provoke an RCP garbage collection from Python?

**Comment by guyer** [comment]
Even after [calling `del` on everybody and their sister](https://gist.github.com/guyer/f4ea5a0443d7bb25c18348661b4634d3/revisions), it still leaks:
![leak2](https://user-images.githubusercontent.com/1830725/36996988-380f625c-2086-11e8-8296-c9329f42ba36.png)

I realize this isn't an optimal design, but shouldn't it be possible to *actually* delete Epetra objects?

**Comment by wfspotz** [comment]
@guyer Interesting question. Since Python does reference counting, I have tried to hide the `RCP`s from Python users, to reduce confusion. So a PyTrilinos `Epetra.CrsMatrix`, for example, will store a C++ `Teuchos::RCP<Epetra_CrsMatrix>` (instead of an `Epetra_CrsMatrix*`). But I have not provided wrappers to any of the `RCP` interface (such as `strong_count()` or `has_ownership()`).

A couple of things: (1) `Teuchos::RCP`s are supposed to be automatic and do their own garbage collection. If a program tries to end without deleting all of the underlying objects of `RCP`s, you are supposed to get an error message (and a pretty lengthy one at that). Are you seeing this type of error message upon exit? When I have come across them, they have always indicated bugs in PyTrilinos code I have written (as opposed to code generated by SWIG).

(2) I can see how querying a PyTrilinos object for its C++ reference count would be a useful debugging tool. It wouldn't be the same as manual garbage collection, but it could provide clues as to what is happening. Would adding this type of interface to PyTrilinos be helpful?

**Comment by guyer** [comment]
@wfspotz (1) The script exits cleanly. (2) Other than in a situation like this, I don't know that I'd ever use such a diagnostic interface. If it also gave me the ability to explicitly decrement an RCP refcount or otherwise force garbage collection, that could be useful (maybe not any more useful than figuring out why it's not happening automatically, though).

BTW, can we please re-open this issue? I don't think it's resolved.

**Comment by guyer** [comment]
@wfspotz Did you get notified of conda-forge/pytrilinos-feedstock#10?

**Comment by wfspotz** [comment]
@guyer I did get notified, but it flew under my radar somehow. Thanks for mentioning it.

**Comment by guyer** [comment]
For the record, it looks like somebody starts to clean up... eventually...
![leak3](https://user-images.githubusercontent.com/1830725/37001559-e8b7e2c4-2094-11e8-919e-f865e824e453.png)
