### ISSUE TITLE
KOKKOS_ARCH contains commas when doing make dashboard

### ISSUE THREAD

**Issue by crtrott** [trilinos/Trilinos#2330]
When trying to build on white and submit to the dashboard via "make dashboard" the KOKKOS_ARCH argument contains commas instead of semicolons which errors out the config. Any idea how to fix this?

@bartlettroscoe 

To reproduce get a Pascal node on white and run the new tpetra test script
```
bsub -Is -q rhel7G bash
${TRILINOS_ROOT}/sampleScripts/Sandia-SEMS/test_tpetra_sandia --report-to-cdash
```
The error can then be seen on the dashboard in an experimental build from site "white" and builldname "Tpetra_white_OpenMP_CUDA".

**Comment by bartlettroscoe** [comment]
@crtrott,

Is this due to this code in Kokkos:

* https://github.com/trilinos/Trilinos/blob/master/packages/kokkos/cmake/kokkos_settings.cmake#L26

which is:

```
string(REPLACE ";" "," KOKKOS_ARCH "${KOKKOS_ARCH}")
```

?

Otherwise, where is the comma-separated list `KOKKOS_ARCH=Power8,Pascal60` coming from?  CMake does not make any conversion like that automatically.  Why does it take a CMake list separated with semi-colons `;` and replace it with `,`?  is this for the makefile generation part?

In any case, in general, to avoid problems with bad interpretation of semicolons, CMake code needs to be set up to accept a list as a string with array elements either separated with semicolons `;` or commas `,` and then do the conversion from `,` to `;` internally.  You can see that TriBITS does this for many variables to avoid problems with semi-colons `;`.

This sounds silly, but I think the way you fix this is to make the following change to this file:

```
diff --git a/packages/kokkos/cmake/kokkos_settings.cmake b/packages/kokkos/cmake/kokkos_settings.cmake
index 850a74a..a909016 100644
--- a/packages/kokkos/cmake/kokkos_settings.cmake
+++ b/packages/kokkos/cmake/kokkos_settings.cmake
@@ -14,6 +14,7 @@
 #-------------------------------------------------------------------------------
 
 # Ensure that KOKKOS_ARCH is in the ARCH_LIST
+string(REPLACE "," ";" KOKKOS_ARCH "${KOKKOS_ARCH}")
 foreach(arch ${KOKKOS_ARCH})
   list(FIND KOKKOS_ARCH_LIST ${arch} indx)
   if (indx EQUAL -1)
```

So when you pass around as set of values as a string, use comas `,`.  But when you need to interpret it as an array in Cmake, replace the comas `,` with semi-colons `;`.  That is a hassle but in my experience that is the most robust way to use arrays in CMake (as long as the elements can't contain commas `,`).

If we can talk through what this code is supposed to be doing, I think we can easily fix situations like this.

**Comment by mhoemmen** [comment]
@crtrott might be out of commission for a few days so I'm CC'ing @ndellingwood and @ibaned .  I can also help; I just need some guidance from @ndellingwood since I haven't been tracking the latest Kokkos promotion push.

**Comment by ibaned** [comment]
@bartlettroscoe although there are issues with the CMake code in current Kokkos master, the Kokkos develop branch has several fixes from me to ensure that CMake keeps the comma- and semicolon-delimited versions nicely separated. It may be that @crtrott is running into the master branch issues, or something different.

**Comment by ibaned** [comment]
@bartlettroscoe I see you committed some changes to have it accept comma-delimited values. In the Kokkos develop branch, we still have it accepting only semicolon-delimited values, and there is a separate variable (`KOKKKOS_GMAKE_ARCH`) which stores the comma-separated values. I'd prefer that users use semicolons for the CMake value, this is more consistent with other variables such as `-DX_LIBRARIES:STRING="path/liba.a;path2/libb.a"`. Is it possible to have this test script provide the variable with semicolon delimiters?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe although there are issues with the CMake code in current Kokkos master, the Kokkos develop branch has several fixes from me to ensure that CMake keeps the comma- and semicolon-delimited versions nicely separated. It may be that @crtrott is running into the master branch issues, or something different.

> @bartlettroscoe I see you committed some changes to have it accept comma-delimited values. In the Kokkos develop branch, we still have it accepting only semicolon-delimited values, and there is a separate variable (KOKKKOS_GMAKE_ARCH) which stores the comma-separated values. I'd prefer that users use semicolons for the CMake value, this is more consistent with other variables such as -DX_LIBRARIES:STRING="path/liba.a;path2/libb.a". Is it possible to have this test script provide the variable with semicolon delimiters?

@ibaned, my experience is that you also want to allow lists like this to be provided coma separated as well.  That avoids some nasty problems when trying to pass through options like this in certain CMake code and in bash scripts.

And you don't even need `make dashboard` to reproduce this problem.  I just reproduced the problem as simply as:

```
$ cd Trilinos/
$ mkdir BUILD/
$ cd BUILD/
$ cmake -DTrilinos_ENABLE_KokkosCore=ON -DKOKKOS_ARCH="BDW;BDW" ..
$ cmake .
```

My PR also fixes the documentation for `KOKKOS_ARCH` as well so we will need to merge that if nothing else.

**Comment by ibaned** [comment]
@bartlettroscoe I'll try to get the Kokkos develop branch to accept comma-delimited `KOKKOS_ARCH`, but I still think its unnecessary complexity. I will admit that the current master version of Kokkos has many bugs in its CMake, as your example shows. Lets use your fix to just get the master version past this obstacle, and then the Kokkos promotion will bring it all the other fixes I've made.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I'll try to get the Kokkos develop branch to accept comma-delimited KOKKOS_ARCH, but I still think its unnecessary complexity. I will admit that the current master version of Kokkos has many bugs in its CMake, as your example shows. Lets use your fix to just get the master version past this obstacle, and then the Kokkos promotion will bring it all the other fixes I've made.

@ibaned,

Okay, then.  If you approve PR #2333, then after the auto PR testing completes, then I will merge and push it.

I do agree that having CMake code manage both semi-colon-separated and coma-separated lists introduces some extra complexity but I have not found a better way to address use cases that it fixes.

**Comment by crtrott** [comment]
This is fixed.
