### ISSUE TITLE
Framework: Develop-to-master promotion needs to test debug CUDA

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2344]
The change that resulted in #2334 got promoted to master, even though it broke the debug GPU build.  (The change fixed another bug, so it was a good thing.)  It would help if develop-to-master promotion tested debug CUDA builds.

@trilinos/framework @micahahoward

## Expectations

  - Develop-to-master promotion should only happen if all supported builds build.
  - CUDA debug and release should be supported builds.

## Motivation and Context

Micah Howard cares about this for his application, and wants to debug on GPUs.

**Comment by crtrott** [comment]
Note that originally both Release and Debug build were broken already. The change which then exposed #2334 just fixed the Release build, while #2335 then fixed the Release build. The issue here is that the CUDA build right now is not clean. I.e. we can't really make use of it as a criteria for promotion except if we exclude tests known to fail. But that would have excluded the test which exposed this new issue in the first place.

**Comment by jwillenbring** [comment]
Assigned to @william76 since he is putting together a CUDA build for PR testing.

**Comment by bartlettroscoe** [comment]
FYI: This should be solved automatically once the ATDM Trilinos CUDA builds are elevated to the "ATDM" group and they get maintained.  Then the process the @william76 is using to update from 'develop' to 'master' just needs to require that the ATDM builds be clean.

But note that these ATDM builds don't enable all of the packages that SPARC needs yet.  For example, see #2375.  That will be solved once EMPIRE is fully covered.

**Comment by bartlettroscoe** [comment]
FYI:

We are doing significnatly better with the ATDM Trilinos builds of CUDA on 'hansen' ('shiller') as shown yesterday, for example at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3451361

We are going to get that build clean pretty soon I think and promote it to the "ATDM" CDash Track/Group so that it sends out error emails.

But the CUDA tests are a mess on 'white'/'ride'.  I will submit some GitHub issues for those failures soon but I suspect that many if these failures is the dreaded mixed language bug for the compilers on that system analyzed in great detail in #1208 (which has never been resolved).

**Comment by william76** [comment]
#2423 is related to this... the first thing will be to get some kind of GPU build into the Experimental track and move that up to higher consequence tracks as things get sorted out.

I was planning to do this on White, but it's sounding like there are some issues with that system.  

I haven't had time to look into it too deeply just yet.

**Comment by william76** [comment]
This issue is really old.  Closing it out.
