### ISSUE TITLE
Blocked Thyra to Epetra Conversion

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#2356]
@trilinos/epetra, @trilinos/thyra

## Scenario
I have a matrix, A, and vector, x.  A is a 2x2 `Thyra::BlockedLinearOpBase`, where A00 is a `Thyra::LinearOpBase` and the other blocks are `Thyra::MultiVectorBase`s.  Likewise, x is a `Thyra::ProductVectorBase` with two sub-vectors.  I'm in a situation where I need to make A an `Epetra_CrsMatrix` and x an `Epetra_Vector`, but I'm at a bit of a loss to do just that.  I see Thyra has a `get_Epetra_Vector()` routine, but that requires passing in an `Epetra_Map`.  I see there's also a `get_Epetra_Map()` routine, which takes a `Thyra::VectorSpaceBase`, but if you give it a `DefaultProductVectorSpace` instead, it doesn't seem to work (I'm seeing `MPI_Abort` being called).

## Questions
*  Is there a way to convert the objects that I have to the ones that I need directly?
*  Is there a way to cram a `BlockedLinearOpBase` into a single `MultiVectorBase` and a `ProductVectorBase` into a single `VectorBase`, such that these Epetra/Thyra wrappers work?
*  If I'm able to convert the various pieces of my blocked objects into their Epetra counterparts, is there some way to cram four `Epetra_CrsMatrix`es into one, and two `Epetra_Vector`s into one?

## Motivation and Context
In Charon I've got a `ModelEvaluator` decorator that takes the original physics `ModelEvaluator` and augments it with blocks corresponding to constraints/parameters.  Solving the blocked system via a Teko blocked preconditioner is proving to be more finicky than we'd like in certain situations, so we're investigating collapsing the blocked system and throwing a standard solver at it to see what happens.

## Additional Information
@mhoemmen, this seems like the kind of thing you'd chime in on.

**Comment by bartlettroscoe** [comment]
@jmgate,

This should not be too hard.  Teko does lots of stuff like this and well as other places in Trilinos.  You just need to wrap your Epetra objects as Thyra objects and then it should be fairly easy to assemble your block operator.

Now for some of your specific questions:

> Is there a way to convert the objects that I have to the ones that I need directly?

You have to provide the original Epetra_Map objects that were used to create your objects but once you do that, the functions documented at:

* https://trilinos.org/docs/dev/packages/thyra/doc/html/group__Epetra__Thyra__Op__Vec__adapters__grp.html

>  Is there a way to cram a `BlockedLinearOpBase` into a single `MultiVectorBase` and a `ProductVectorBase` into a single `VectorBase`, such that these Epetra/Thyra wrappers work?

What are you suggesting?  You can never expect the implement the `Thyra::MultiVectorBase` interface just given a general `Thyra::LinearOpBase` object.  That would be like asking to implement a `Tpetra::MultiVector` object given a `Tpetra::CrsMatrix` object.  A `Tpetra::CrsMatrix` object just does not have the machinery to implement a `Tpetra::MultiVector` object.

> If I'm able to convert the various pieces of my blocked objects into their Epetra counterparts, is there some way to cram four `Epetra_CrsMatrix`es into one, and two `Epetra_Vector`s into one?

No, I don't think the Thyra interfaces can do that.  But you might find some code in Teko or Stokhos that does something like that.  But since Epetra and Tpetra does not have abstract Vector or MultiVector objects, this involves lots of copying of data.

@jmgate, do you have some time to just talk through this use case some?  A few minutes of discussion over Skype could save a lot of back and forth through GitHub.  You can contact my by email if you are interested.
