### ISSUE TITLE
Teuchos: YAML parser: Non-ascii characters in comments cause parser to fail

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#2371]
This is a cut-n-paste issue from my code, but it is trilinos.
[file.txt](https://github.com/trilinos/Trilinos/files/1804790/file.txt)

When a non-ascii character is in a comment, the parser fails and the simulation doesn't run.
Possible Solution
Steps to Reproduce

    Download this file that has four different unrecognized characters right at the top in their own comment sections: SingleParticle.yaml
    Run it.
    Shake fist angrily at computer.

Context

I was creating a test and put the experimental value in a comment with the unicode plus-or-minus sign along with the error.

**Comment by bathmatt** [comment]
```
**********************************************
*********** Caught Exception: Begin Error Report ***********
Error Type: Generic exception type thrown
error: Unexpected character code -61 at line 1 column 27 of SingleParticle.yaml
# offending character #1: �
                         ^


```

**Comment by bathmatt** [comment]
@ibaned probably your on the hook on this one..

**Comment by mhoemmen** [comment]
I'm guessing if we use `std::string`, i.e., `std::basic_string<char>`, then we're stuck with ASCII.  If we want non-ASCII characters to work, we'll need to invest in Unicode support.

**Comment by ibaned** [comment]
@bathmatt  this is definitely a known current limitation. Unicode makes simple things like "which column am I in" quite complicated (text can start moving right-to-left suddenly, some symbols are zero-width, etc). Unless there are strong reasons for having non-ASCII comments, I'm tempted to keep this limitation.

Note that the Teuchos XML parser should have the same limitation, i.e. not accepting non-ASCII characters.

**Comment by ibaned** [comment]
@trilinos/teuchos @bartlettroscoe

**Comment by bartlettroscoe** [comment]
@ibaned,

Is there a way to filter the non-ASCII unicode chars into some safe ASCII chars before they get processed?  Perhaps just the initial pre-processing reader could use `wchar_t` and then filter down to ASCII `char`?  Or, can a preprocessing phase in the parser could use `wchar_t` and specifically check for non-ASCII chars and if it funds one, report it and abort?

Does the YAML parser save comments or it just has to process the file that might have comments in it but the comments will be discarded?  If it just needs to read the initial file with comments first but will discard them, then an initial pre-processing filtering routine could be written using `wchar_t` and then discard the comments that might have non-ASCII chars before moving the filtered text without comments to the functions that expect `char` to do the actual YAML parsing. 

I don't think we would ever want to allow non-ASCII chars in a parameter list, would we?  I can't think of a good reason for this (except perhaps in fancy comments like @bathmatt mentions above).

> I was creating a test and put the experimental value in a comment with the unicode plus-or-minus sign along with the error.

@bathmatt,

Could you set up your text editor to use ASCII only chars and then use the valid ASCII chars `+/-` to replace the uni-code char that you tried to use?

**Comment by ibaned** [comment]
> the initial pre-processing reader could use wchar_t and then filter down to ASCII `char` ?

This is possible, but depending on how nice the filter is it could take a lot of work. I suppose a simple filter would replace every non-ASCII char with a common symbol like a question mark.

> can a preprocessing phase in the parser could use wchar_t and specifically check for non-ASCII chars and if it funds one, report it and abort

This is more or less what happens now

> Does the YAML parser save comments or it just has to process the file that might have comments in it but the comments will be discarded

Right now it discards them at some medium level of abstraction, but the ability to preserve comments in the future is appealing, and the lower levels do extract and keep comment lines in `std::string`.

> I don't think we would ever want to allow non-ASCII chars in a parameter list, would we?

Especially since readers mainly support `bool`, `int`, `double`, and `std::string`, for which I don't see a non-ASCII character value being applicable.

**Comment by bartlettroscoe** [comment]
Could we provide a simple exectuble in Teuchos that could be installed called something like `check-param-list-parsing.exe` that would read in any `*.yaml` or `*.xml` file and then parse it, convert it into a PL object in C++ and then pretty-print parsed PL?  That could be used by people like @bathmatt to help check for problems in their input `*.yaml` or `*.xml` files so that they don't blow up when trying to run a big simulation?

@bathmatt, would that be a helpful tool?

But really I think that every application code should have a utility that will parse the input files for a particular case and just make sure things look okay before trying to run some big simulation.  This would catch more problems than just non-ASCII chars in input files.  I think Dakota has a feature like this.

**Comment by bartlettroscoe** [comment]
> > can a preprocessing phase in the parser could use wchar_t and specifically check for non-ASCII chars and if it funds one, report it and abort
> 
> This is more or less what happens now

But what does the error message look like?  Does it say that `<some-unicode-char> is not a valid ASCII char and therefore parsing must be aborted` or does it crash with some type of vague error message?

**Comment by bathmatt** [comment]
@bartlettroscoe the error messae is the second comment on the thread.

**Comment by bathmatt** [comment]
@bartlettroscoe we do parse the whole file and validate before running, We could add an option like --dry-run simply.

I am not sure why the user wanted non-ascii comments. we are going to start collaboration with the french and they have all sorts of funny chars in français ...

**Comment by jmgate** [comment]
The expectation here was that the parser would disregard everything that comes after a comment character.  Why is that not the case?  Even if you run into unicode characters after a comment character, that shouldn't mess with indentation at all.

**Comment by bartlettroscoe** [comment]
>  the error messae is the second comment on the thread.

Okay, that is not a great error message.  It would be better if it actually printed the unicode char so the user could see it.

Could we just find a generic tool that checks any old file for non-ASCII chars and then prints them out as an initial pre-processor?  Then everyone could add that to their initial workflow.  But I do understand the desire to have all of these tools more gracefully handle non-ASCII chars.  I had to update several Python scripts for CASL years ago were people where putting in non-ASCII chars somehow.  But that sort of thing is easier to do with Python than C++ after the fact.

With emacs and my standard keyboard, I am not even sure how I would produce an non-ASCII char.  I only seem to be able to do that when I copy and paste from an MS Word document or something.

**Comment by bartlettroscoe** [comment]
Closed on accident., reopening.

**Comment by jmgate** [comment]
I use non-ASCII characters quite regularly.  Since the UTF-8 file encoding is pretty standard these days, it seems like our software should be able to handle it.

**Comment by bathmatt** [comment]
Yeah, I do the comment and close all the time :)  Stupid gitlab diff.

So, I just wrote a simple test function 

```
#include <iostream>
#include <string>
#include <fstream>

using namespace std;
int main() {
  ifstream in("foo.yaml", ios::in);
  string s;
  for (int i=0;i<10;++i) {
    in >> s;
    cout << s <<std::endl;
  }
}
```

and it outputs the expected stuff for that yaml file.

```
# offending character #1: ç
# offending character #2: è
```
yields 

```
dir-tmp (gcc) 13 $ ./a.out 
#
offending
character
#1:
ç
#
offending
character
#2:
è
```

So, I guess I don't understand @mhoemmen 's comment since it looks like std::string supports these chars

**Comment by ibaned** [comment]
@bathmatt I think your example works because the characters you chose still fit within [Extended ASCII](https://www.asciitable.com), and can be stored in a `char`. Maybe something like this will give different results:

௵

@jmgate The YAML parser is not a self-contained piece of code, but rather builds on infrastructure (TeuchosParser) for parsing any ASCII language. That infrastructure, in turn, relies on a few things that make Unicode difficult. The first layer of parsing is a deterministic finite automata, encoded as a state table. The number of columns in said table is the number of acceptable characters, which is currently at an acceptable size of 98. [More tables](https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/parser/src/Teuchos_chartab.cpp) convert `char` to these symbols and back. In other words, a lot of the design assumes that data structures sized by the number of possible characters are okay to store. Unicode supports 1,114,112 possible code points, which is not impossible to store but certainly much more expensive, and unrealistic to create tables by hand. So just carrying full Unicode support through to the level where the YAML backend can say "we are in a comment, ignore this character" or "keep this character" seems like a lot of work and re-design, more than I can sign up for without funding.
There are various levels of less-than-full support we could do, from a better error message to a special-case "wildcard" representation for anything non-ASCII, to pre-processor passes etc.
