### ISSUE TITLE
Amesos(2): SuperLUDist 5.0 is incompatible with current Amesos(2) interface

### ISSUE THREAD

**Issue by amklinv** [trilinos/Trilinos#245]
@trilinos/amesos2 @jdbooth @jwillenbring @srajama1 @bmpersc 

Sherry recently renamed the superlu_options_t struct to superlu_dist_options_t, which means SuperLUDist 5.0 does not work with our current Amesos and Amesos2 interfaces.  I'm planning to address this issue the same way Siva addressed the issue of the LUstructInit parameters changing in Verson 4.0.  I will add a check to FindTPLSuperLUDist.cmake to see whether we should use superlu_options_t or superlu_dist_options_t, then wrap all occurances of superlu_options_t with an ifdef.

Please let me know if this does not seem like a reasonable approach.  We need to fix this soon in order to meet our xSDK release deadline.

**Comment by jwillenbring** [comment]
CC @BarrySmith to keep him informed of progress on this.

**Comment by srajama1** [comment]
Jim: Just to update you we need to support older and newer versions of SuperLU_Dist

Alicia's fix is one way to do this. We detect which version at runtime (which we have had lots of trouble with in the past as it is not foolproof). In order to make sure we are able to support both versions, I requested a version macro from Sherry in SuperLU_Dist header files, so we can check it at compile time.
(We were both at Copper). Sherry will introduce it so we can use it to find versions.

Does Sherry has a github account ? Can Jim/Alicia add it here ?

**Comment by jwillenbring** [comment]
I believe Sherry's GitHub username is @xiaoyeli

**Comment by jwillenbring** [comment]
@bartlettroscoe may need to follow the status of this.

**Comment by amklinv** [comment]
@bartlettroscoe, if you start seeing weird errors in the build stage regarding a struct called "superlu_options_t", it's related to this.  If this gets in the way of your efforts to fix the circular dependency between Trilinos and PETSc, you can always try my branch, which fixes this issue in an inelegant way.

**Comment by bartlettroscoe** [comment]
I will try an older version of PETSc and SuperLUDist for now.  The changes I will make for that should be orthogonal to everything else and should not impact the current build of xSDKTrilinos as a TriBITS package in the CMake build.   That is if my laptop let's me work on this :-)

**Comment by jdbooth** [comment]
commit 7e355fb3be7dd3c665e203846bccd8f861c43386
Has been pushed on 3/29/16 using Superlu_dist new version macro. 
it has been tested by myself and @amklinv
