### ISSUE TITLE
Amesos2: Add example using scalar type with extended precision

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#2485]
This issue is an enhancement to Amesos2 to provide an example of using a solver (e.g. KLU2, Basker) with extended precision. 

This is motivated by a user request about providing an example for using types with arbitrary precision (from the library GMP) with Amesos2.

There are cases where users defined their own ensemble scalar types, requiring overloading of various operators in order for Amesos2 solvers to support the custom type. @srajama1 pointed out this [trilinoscouplings example](https://github.com/trilinos/Trilinos/blob/master/packages/trilinoscouplings/examples/fenl/) which can serve as a possible pattern/template (I believe Xyce and Stokhos also do something similar using Basker as the solver). 

@trilinos/amesos2

**Comment by ndellingwood** [comment]
@MicheldeMessieres is this something you would have time to take a look at?

**Comment by mhoemmen** [comment]
Tpetra supported some interesting scalar types circa 2009 -- I remember it supposedly had ARPREC support, ill tested though.  I added support in Tpetra for `__real128` via libquadmath a few years ago, which is a bit easier to test since it only takes a few extra build options and always works with GCC.
