### ISSUE TITLE
RBGenDriver build problem for CUDA build

### ISSUE THREAD

**Issue by micahahoward** [trilinos/Trilinos#2489]
I'm seeing this (short snippet below, there's a whole lot more) with current Trilinos/master when building with CUDA.

/tmp/tmpxft_00006ee7_00000000-2_RBGenDriver_EpetraMV_dlink.reg.c: At global scope:
/sierra/sntools/SDK/compilers/nvidia/cuda_9.0.176/bin/crt/link.stub:92:118: error: redefinition of ?const unsigned char def_module_id_str_54_tmpxft_0000799b_00000000_6_EpetraExt_MMHelpers_cpp1_ii_804a60dd []?
 static const unsigned char __DEFSTRNAME(id) [] __attribute__((aligned(1))) __attribute__((section ("__nv_module_id"))) = "def " __TO_STRING(id); \

@mhoemmen, @bartlettroscoe, who is the right person to look into this?

**Comment by bartlettroscoe** [comment]
CC: @srajama1, @hkthorn 

@micahahoward, it is not clear who is responsible for the RBGen code under Anasazi but Anasazi itself falls under the LinearSolvers product area for which @srajama1 is the Product Lead.

Note that the EMPIRE configuration of Anasazi of Trilinos does **not** enable this RBGen code as shown under:

* https://testing-vm.sandia.gov/cdash/viewNotes.php?buildid=3404201#!#note5

which shows:

```
Anasazi_ENABLE_RBGen:BOOL=OFF
```

This option is off by default so I don't think you should expect that there is **any** automated testing for this feature at in any automated Trilinos builds posting to the Trilinos CDash site.

What caused this option to get set `ON` in your build enabling RBGen?  Do you really need RBGen?   If so, then the default for `Anasazi_ENABLE_RBGen` needs to set to `ON` and then someone is going to need to support that.

**Comment by mhoemmen** [comment]
@micahahoward More importantly, do you actually need Anasazi?  You might need it for LOCA I suppose.

**Comment by micahahoward** [comment]
I believe this is related to an issue @nmhamster has been working with Nvidia.

We do use RBGen for our ROM capabilities.  In the short term, I've turned off RBGen when we build on a GPU platform.

Longer term, determining who/how this will be supported is important to me.  @bartlettroscoe, we still need to determine the common set of Trilinos packages between EMPIRE and SPARC.  This will help in ensuring our configuration of Trilinos for SPARC is being tested by the automated ATDM build/test processes.

**Comment by hkthorn** [comment]
@micahahoward Is RBGen integrated into your code directly, or do you use the RBGen Epetra driver to perform post-processing analysis of your data?  If you are not using it, the RBGen Epetra driver is a parameter-list-driven convenience that can be disabled.  Let me know if that would help.

**Comment by bartlettroscoe** [comment]
@micahahoward said:

> Longer term, determining who/how this will be supported is important to me.

I don't know the answer to that.  It think is something that the Trilinos lead @maherou, the Linear Solvers Product Lead for Anasazi @srajama1 and ATDM management will need to address.  You need to be very careful enabling anything that is disabled in a particular package by default because except for some rare exceptions (like `MueLu_ENABLE_Experimental` in ATDM builds of Trilinos), that code likley never gets tested in any automated builds posting to Trilinos.

> @bartlettroscoe, we still need to determine the common set of Trilinos packages between EMPIRE and SPARC. This will help in ensuring our configuration of Trilinos for SPARC is being tested by the automated ATDM build/test processes.

@micahahoward, I have been looking at the things that the SPARC configuration is enabling that the EMPRIRE configuration of Trilinos is not.  It is just a few extra TPLs, a few extra packages, and a few options like `Anasazi_ENABLE_RBGen:BOOL=OFF`.  The issue is going to be the timing of when we add these extra options to the ATDM builds of Trilinos that are getting set up outlined at:

* https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/ATDM+Builds+of+Trilinos

We can discuss this topic in our meeting later this week.

**Comment by micahahoward** [comment]
Understood on non-default packages.  However this makes me want to put more emphasis on getting the packages we use tested in the ATDM builds of Trilinos.  Why is the timing an issue?  We should do this as soon as possible.

**Comment by bartlettroscoe** [comment]
@micahahoward said:

> Understood on non-default packages. However this makes me want to put more emphasis on getting the packages we use tested in the ATDM builds of Trilinos. Why is the timing an issue? We should do this as soon as possible.

The issue is that if we add more things to this ATDM build of Trilinos, we may break its usage by EMPIRE since we are not running automated builds of EMPIRE against the ATDM build of Trilinos yet.

We could set up automated builds of EMPIRE against Trilinos right now, but given their new workflow, and other factors, it would be hard to know if the failures in EMPIRE builds and tests we were seeing were due to new regressions of Trilinos, or just an incompatible version of Trilinos with EMPIRE, or if these EMPIRE tests were already failing even with their officially accepted version of EMPIRE.

But all things considered, I think the risk of adding the SPARC packages, TPLs, and other configuration settings is pretty low and would help support SPARC right now (even before EMPIRE officially switched over to the new ATDM build of Trilinos).

But this work to add the SPARC enables will delay getting EMPIRE switched over to this new ATDM Trilinos build which means that we would need to keep maintaining both sets of scripts and tracking changes in their scripts.

We can discuss these issues in our meeting tomorrow.

**Comment by srajama1** [comment]
@micahahoward @bartlettroscoe : @hkthorn can help support Anasazi this year.

**Comment by micahahoward** [comment]
I believe we are using the RBGen Epetra driver.  @jfike would know.
Can someone fix this issue with RBGen?

**Comment by jfike** [comment]
The following code is from Albany, but we are doing something similar in SPARC.
```
RBGen::EpetraMVMethodFactory methodFactory;
  const RCP<RBGen::Method<Epetra_MultiVector, Epetra_Operator> > method = methodFactory.create(*rbgenParams);
  method->Initialize(rbgenParams, modifiedSnapshots);
  method->computeBasis();
```

**Comment by ikalash** [comment]
@jfike's guess that RBGen is off in the Albany CUDA build is correct.  MOR in Albany does not work on GPUs, so it is not built for GPUs and RBGen is not turned on in the Albany GPU build of Trilinos.

**Comment by bartlettroscoe** [comment]
So is this problem resolved then?

**Comment by micahahoward** [comment]
No.  We've just turned it off.

**Comment by bartlettroscoe** [comment]
Okay, then we will have to set up a "Specialized" build that enables this and then get someone to fix this on the side as we work to get that ATDM Trilinos build to support everything that SPARC needs.

**Comment by jfike** [comment]
After some discussion, our current plan is to remove the dependence on RBGen and just use calls to lapack.

**Comment by bartlettroscoe** [comment]
@micahahoward and @jfike, with SPARC no longer using RBGen, should we remove this from being an ATDM issue?  If so, we should remove the "ATDM" label to get this off of our backlog for unresolved "ATDM" issues.

**Comment by bartlettroscoe** [comment]
I removed the "ATDM" label from this issue since this problem is no longer affecting ATDM customers.
