### ISSUE TITLE
ROL: Tests failing nightly testing

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#2500]
@trilinos/rol 

We had some tests fail last night in the CLEAN track:
* [ROL_example_PDE-OPT_0ld_stefan-boltzmann_example_01_MPI_4][1]
* [ROL_example_PDE-OPT_0ld_stefan-boltzmann_example_02_MPI_4][2]

These tests show a consistent history of passing but there was a commit made to ROL yesterday (53b5cafc8a71ac2f2e1b0e473d60377260881b45) that may have contributed to these new test failures...  

[1]: https://testing-vm.sandia.gov/cdash/testDetails.php?test=44952386&build=3410616
[2]: https://testing-vm.sandia.gov/cdash/testDetails.php?test=44952387&build=3410616

## Definition of Done
- [ ] Nightly CLEAN track tests must all pass

@gregvw

**Comment by dridzal** [comment]
We are puzzled by this ... the first test simply hangs in globalAssemble's AllReduce.  In TotalView, we get

```
opal_progress,                                          FP=7ffcd70b7a90
     ompi_request_default_wait_all,                          FP=7ffcd70b7b00
     ompi_coll_tuned_allreduce_intra_recursivedoubling,      FP=7ffcd70b7c00
     PMPI_Allreduce,                                         FP=7ffcd70b7c50
     ...chos9reduceAllIiiEEvRKNS_4CommIT_EENS_14EReductionTypeES2_PKT0_PS7_, FP=7ffcd70b7e50
     ...sDeviceWrapperNodeINS1_6SerialENS1_9HostSpaceEEEE14globalAssembleEv, FP=7ffcd70b8830
     ...ERKN7Teuchos3RCPIKNS_3MapIiiS6_EEEESF_RKNS9_INS8_13ParameterListEEE, FP=7ffcd70b8da0
     ...9HostSpaceEEEE12fillCompleteERKN7Teuchos3RCPINS8_13ParameterListEEE, FP=7ffcd70b8fc0
     _ZN19StefanBoltzmannDataIdE7updateAERKSt6vectorIdSaIdEE, FP=7ffcd70b92b0
     ...straint_PDEOPT_StefanBoltzmannIdE5valueERN3ROL6VectorIdEERKS3_S6_Rd, FP=7ffcd70b9380
     _ZN3ROL17Constraint_SimOptIdE5solveERNS_6VectorIdEES4_RKS3_Rd, FP=7ffcd70b98c0
     _ZN3ROL24Reduced_Objective_SimOptIdE5valueERKNS_6VectorIdEERd, FP=7ffcd70b9930
     ...ateGradientERNS_9ObjectiveIdEERKNS_6VectorIdEERKSt6vectorIdSaIdEERd, FP=7ffcd70b9990
     _ZN3ROL19StochasticObjectiveIdE8gradientERNS_6VectorIdEERKS3_Rd, FP=7ffcd70b9a40
     ...iveIdE12checkHessVecERKNS_6VectorIdEES5_S5_RKSt6vectorIdSaIdEEbRSoi, FP=7ffcd70b9c70
     _ZN3ROL9ObjectiveIdE12checkHessVecERKNS_6VectorIdEES5_S5_bRSoii, FP=7ffcd70b9d20
     _ZN3ROL9ObjectiveIdE12checkHessVecERKNS_6VectorIdEES5_bRSoii, FP=7ffcd70b9d80
     _ZN3ROL19OptimizationProblemIdE5checkERSoii,            FP=7ffcd70ba0f0
     main,                                                   FP=7ffcd70bade0
     __libc_start_main,                                      FP=7ffcd70baea0
     _start,                                                 FP=7ffcd70baeb0
```

and the code just sits there.  No segfaults.  How does one debug this?

**Comment by bartlettroscoe** [comment]
This impacted an "ATDM" build as well as shown at:

* https://testing-vm.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3411117

so I added the "ATDM" label.

Note that this test was passing in under a minute every day before this as shown in the query:

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-04-03&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-gcc-7-2-0&field2=testname&compare2=61&value2=ROL_example_PDE-OPT_0ld_stefan-boltzmann_example_01_MPI_4&field3=buildstarttime&compare3=84&value3=now

If this can be fixed in the next day or so, I would recommend leaving it enabled.  But if it can't be fixed in a day or two, I would recommend temporarily disabling these tests (at least for the ATDM build) and then let a ROL developer debug these off line.  See the process for ATDM failures at:

* https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/ATDM+Builds+of+Trilinos#ATDMBuildsofTrilinos-Addressingfailures

For builds other than the ATDM builds, that is between the @trilinos/rol team and the @trilinos/framework team to decided how to handle this.

**Comment by dridzal** [comment]
Since we can't debug this quickly, we will disable the two tests.  This seems to be coming from Tpetra, see the reference to globalAssemble in https://github.com/trilinos/Trilinos/issues/2500#issuecomment-378307676, but it is also possible that ROL has a memory leak and that the above issue is just a symptom.  After all, it was a ROL commit that caused the hang-up.  We plan to debug the problem in a few weeks.  Mentioning @trilinos/tpetra, just in case.

**Comment by dridzal** [comment]
Our changes have been merged.  @william76 please let us know if the clean track has been fixed.  If so, feel free to close the issue.  @bartlettroscoe please let us know if these failures are now gone from the ATDM build.  Thanks.

**Comment by william76** [comment]
@dridzal The nightly tests passed, thanks!

Do you guys want us to keep this issue open until those tests are fixed and reintroduced or should we close it?

**Comment by dridzal** [comment]
Let’s keep it open, as a reminder.

**Comment by william76** [comment]
Closing this issue since it's been resolved.
