### ISSUE TITLE
Ifpack2: Some tests not instantiated if GO=int is OFF

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2520]
Some Ifpack2 tests aren't instantiated or run, if `GlobalOrdinal = int` is disabled upstream.  See discussion here: https://github.com/trilinos/Trilinos/pull/2515#issuecomment-379865709

@trilinos/ifpack2

**Comment by lucbv** [comment]
@mhoemmen the MueLu interface to Ifpack2 line partitioner is now merged in, see #2528.
As expected the code does not go through with std::complex<double>, so I am opening issue #2551 on that.

**Comment by mhoemmen** [comment]
@lucbv Does "code does not go through" mean that you just broke the build?  Sierra folks will be grumpy about that since they need to enable complex.

**Comment by lucbv** [comment]
@mhoemmen no it builds you get a run time error when Ifpack2 tries to extract the coordinates from its parameter list.
This would only happen to sierra folks use the line partitioner in Ifpack2 with MueLu, but since we added it yesterday I feel safe that they won't notice.
I am currently working on fixing this though.

**Comment by lucbv** [comment]
To be more precise, you can see the problem on [this](https://testing.sandia.gov/cdash/buildSummary.php?buildid=3497090) build.

**Comment by mhoemmen** [comment]
Fixed in develop by PR #2549, just merged.
