### ISSUE TITLE
Trilinos/README.md way out of date

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#26]
The file Trilinos/README.md that is displayed as the first thing people see on GitHub is way out of date (and has been for many months or more).  Most of the links are broken and the file names are way out of date.  This does not make for a good first impression for new people coming to look at Trilinos on GitHub.  At the very least, this should be gutted and just point to trilinos.org.  Then, if someone has time, this can be filled out.

**Comment by jwillenbring** [comment]
I should have referenced this in my commit message, but I did clean things up a bit.  I mostly gutted the file, but I did leave a few things, and fixed a couple others.  I don't really want to reproduce a ton of things from the site in this file, especially since this isn't the primary user portal.  We should probably add something about contributing when those details are hammered out. You can close this, or specify what else specifically should happen to close this ticket.

**Comment by bartlettroscoe** [comment]
Jim, the trimmed down file looks better.  I would recommend removing the link to the coverity results:

   https://scan.coverity.com/projects/1680

That links should be moved to a Wiki page on testing on the GitHub site but I don't think we want it front and center.

**Comment by bartlettroscoe** [comment]
I updated the README.md file back on May 24 to point to the updated INSTALL.rst document (which I also updated).  I think it is okay now.   The README.md file is short and mostly just provides links. The link to the coverity results is still there but we should get Trilinos developers to start paying attention to that.  The proposed standard :

https://github.com/linuxfoundation/cii-best-practices-badge/blob/master/doc/criteria.md

requires running at least one static analysis tool on a compliant open-source piece of software.  But that is another issue.

Closing as complete.
