### ISSUE TITLE
panzer example confiure out of date with package split

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#262]
@rppawlo the cmake stuff for main_driver didn't get updated correctly when panzer got split.

**Comment by rppawlo** [comment]
I will take a look on Monday.

**Comment by rppawlo** [comment]
@bathmatt are you talking about the example build scripts in "Trilinos/packages/panzer/maintenance"?

**Comment by bathmatt** [comment]
IF (${PACKAGE_NAME}_BUILD_SOLVER_DRIVERS_EPETRA)
   ADD_SUBDIRECTORY(main_driver)
ENDIF()
Trilinos/packages/panzer/adapters-stk/example

**Comment by rppawlo** [comment]
This was subtle. In the package split we change some optional dependencies (when it was all one package) to required dependencies for a particular subpackage. Tribits only defines the <PACKAGENAME>_ENABLE_* variables for optional dependencies, not required dependencies. So three panzer tests were automatically disabled due to a combined option check. Fixes are in place and being tested now.

**Comment by rppawlo** [comment]
Just pushed the fix. Closing.
