### ISSUE TITLE
Xpetra: Emulate dot product with CrsMatrixWrap and MultiVector possible?

### ISSUE THREAD

**Issue by chochmuth** [trilinos/Trilinos#2626]
Hello,
i would like to emulate a dot product of two vectors with a CrsMatrixWrap **A** and a MultiVector **x**.
The CrsMatrixWrap columns are distributed with the same map as the MultiVector.
Further, the CrsMatrixWrap RowMap is replicated and the RangeMap is a single index(scalar).

With A = (1, 1, 1, 1) and x = (1, 1, 1, 1)^T, the result y=A*x is dependent on the number of procs used:
-np 4, results in y=1
-np 2, results in y=2
-np 1, results in y=4
Only values, which also belong to RangeMap(scalar) are summed up and the rest is lost.

Is it somehow possible to make this work? I would like to use the BlockedCrsMatrix class and also need it for vectors, therefore I tried the above approach.

I attached a code example, I made by modifying "example/Simple/Xpetra_Laplace1D-Xpetra.cpp".

@trilinos/xpetra 
[EmulateDotProduct_Xpetra.cpp.zip](https://github.com/trilinos/Trilinos/files/1943512/EmulateDotProduct_Xpetra.cpp.zip)

**Comment by tawiesn** [comment]
@chochmuth I am not completely sure that i understand what you want and what you observe. So, you do not want the result of the regular matrix-vector product A * x where A is just a laying 1x4 vector, right? Because then, the result should always be y = 4 independent of the number of procs. I'm confused, since in your code snippet you define `numGlobalElements=4` and the std::cout line in the end states that "it should be 4"? I did not compile your example, i was just looking over the source code to understand what you do. Maybe you could clarify what you exactly want to do. In any case, i think the key is the column map of A. By default it should be a full map with four entries in your example making sure that the standard matrix-vector product A*x always sums up correctly communication all the off-processor values...

**Comment by chochmuth** [comment]
No, the regular matrix-vector product A * x where A is just a laying 1x4 is what I want. The result is a 1x1 scalar and in my case the result should always be 4, correct.
I want to distribute the columns of A, not the rows. 
You mentioned the column map, my map possesses 4 global entries, resulting in 4/numProcs local entries.
So in my case with -np 4 each proc gets a single column of A, with -np 2 each proc gets 2 columns.
The result of y = A * x  is just 1 global entry, owned uniquely by 1 proc. It seems that the off-processor values are not communicated, therefore I observe the above behaviour:
-np 4, results in y=1(wrong)
-np 2, results in y=2(wrong)
-np 1, results in y=4(correct, as no off-processor values exist)

**Comment by tawiesn** [comment]
@chochmuth Ok, now i see what you mean.

You create the matrix using the CrsMatrixWrap constructor using

`Xpetra::CrsMatrixWrap<...>(mapSingleRow,map, 4)`

with 

`map =
      Xpetra::MapFactory<...>::createUniformContigMap(lib, numGlobalElements, comm);`

If you look at the constructor of `CrsMatrixWrap` it expects a column map (colMap) as second argument.
Column maps are (in contrast to DomainMaps) supposed to be overlapping (if necessary). In your case, the column map would contain the global ids [0,1,2,3] on all processors, since the data of the matrix (the whole row) lies on one processor (probably proc 0) and all other processors have to communicate with that processor. But the MapFactory you are using is building a non-overlapping map with, e.g., ids [0,1] and [2,3] (for 2 processors).

You need to use the following `Build` routine from the `MapFactory` class:

`Build (UnderlyingLib lib,
           global_size_t numGlobalElements,
           const Teuchos::ArrayView<const GlobalOrdinal> &elementList,
GlobalOrdinal indexBase)`

to create the column map `map` in your code.
The parameters should be `numGlobalElements = 4`, `elementList = [0,1,2,3]` (you have to create a Teuchos::ArrayView from e.g. a std::vector containing [0,1,2,3] on all processors. You should find examples in the source code somewhere if you are unsure how to do that) and `indexBase =0` (that's in 99% of all cases the right choice).

Let me know whether this makes sense to you.

I could not test it, but i think that is what you need.

**Comment by chochmuth** [comment]
@tawiesn Thanks for your help. I'm sorry if I did not make myself clear. What you describe is also the default behaviour (no ColumnMap passed to the constructor) when constructing a matrix, right?
You state that 
" [...] the data of the matrix (the whole row) lies on one processor (probably proc 0). ",
and this is exactly what I don't want. That's why i tried to use the non-overlapping ColumnMap `map` in order to distribute the columns of the matrix. 

How do I distribute the columns (every processor owns all rows) of a matrix?

**Comment by tawiesn** [comment]
Well, in principle you should be able to do this using a locally replicated row map (that is, the row map would be [0,1,2,3]) and the same range map. But that would not help to get the "4" as you still need the fully replicated column map [0,1,2,3] to sum up the results over all columns. I never tried something like that.

Anyway, from a communication perspective doing something like that doesn't make sense. Why not creating a replicated matrix A. For, e.g., 3 processors you could build a 3x4 matrix filled with ones, the x would be a 4x1 vector distributed over 3 processors living on the domain map of A and y would be a 3x1 vector living on the range map containing on 4 in each row associated with the corresponding processor.
Then, whenever you calculate A*x, only the entries of x would be communicated to all processors.

You could even go one step further and avoid all communication by creating a block-diagonal matrix A of size nProcs x 4*nProcs with the following entries

> A = [ 1 1 1 1 0 0 0 0 0 0 0 0; 0 0 0 0 1 1 1 1 0 0 0 0; 0 0 0 0 0 0 0 0 1 1 1 1 ]

and x the expanded vector of size12x1 containing ones distributed again over the column map (= domain map in this case) of A. The range map of A would be identical to the row map of A (with one row associated with one processor). This way you can completely avoid inter-processor communication by locally replicating the matrices and vectors.

Another alternative would be to implement what you need by hand using the Teuchos::Comm interface (with sumAll, maxAll operating on Arrays). There should be plenty of examples how to do that througout the source code...

Does that make sense?

**Comment by chochmuth** [comment]
@tawiesn Thanks for your help, the approach you described makes perfect sense. I'm already using a custom implementation, which handles the above case separately. Now, I wanted to entirely use the BlockCrsMatrix class but I will try a workaround.
