### ISSUE TITLE
Ifpack2: multi-threaded Gauss-Seidel does not support damping

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#2665]
@trilinos/ifpack2 

## Current Behavior
The multi-threaded version of Gauss-Seidel accepts a damping factor as parameter, just as the serial version. This value, however, is never used, so that the damping factor is effectively always 1.

## Possible Solution
There are several options to deal with this issue:
- Change the underlying KokkosKernels implementation to allow damping.
- Display a warning when the damping factor != 1.
- Remove the damping factor parameter from the list of valid parameters.

**Comment by pwxy** [comment]
@cgcgcg beat me by 14 days.
I tried MTGS and MTSGS with damping, and it ignores the ifpack2 damping parameter (never even uses it).
This issue is not high priority, but eventually it would be good to have this implemented.
I agree with @cgcgcg that until MTGS and MTSGS recognizes the damping parameter, should implement his possible solutions #2 or #3 otherwise a user might not realized that the parameter was ignored.  
Making @jhux2 aware of this issue.
