### ISSUE TITLE
Tpetra: Micro-Benchmark MultiVector Update

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#2772]
1) Write a Tpetra vs. KokkosBlas vs. Raw Lambda micro-benchmark to compare MultiVector Update performance in serial. Check into Tpetra @csiefer2

2) Study to understand performance @crtrott 

Other potentially interested parties @jhux2 @srajama1

**Comment by csiefer2** [comment]
Looked at the kernel w/ @dsunder.  It appears that the sync (in MultiVector update) before we call KokkosBlas seems to be where our extra Tpetra time occurs.

If we have launch blocking we don't need the sync.  If we don't have lunch blocking, we'd like to be able to overlap kernel calls, so we probably want to get rid of the sync there too.  @mhoemmen your thoughts?

**Comment by mhoemmen** [comment]
@csiefer2 refers to line 3210 of Tpetra_MultiVector_def.hpp

https://github.com/trilinos/Trilinos/blob/3cc0152887609df06f04477ce483bca090fdab45/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp#L3210

**Comment by mhoemmen** [comment]
As @csiefer2 and I discussed today over chat:

  - sync is not a no-op; it fences
  - If `A` and `*this` are in the same space, we don't need to sync
  - Thus, we can fix this by checking `A.template need_sync<device_type>`; if true, sync `*this` to host, else don't

The reason we want to sync `*this` rather than `A`, is because `A` enters `update` read only, while `*this*` is read-and-write.

**Comment by csiefer2** [comment]
@mhoemmen  I've just prototyped out some code that seems to work. Will clean up and get to you for review

**Comment by csiefer2** [comment]
MultiVector routines that use sync (need further review):

copyAndPermuteNew - ???
unpackAndCombineNew - ???
multiVectorSingleColumnDot - issue confirmed by inspection
normWeighted - issue confirmed by inspection
scale - issue confirmed (at least for some of the scale functions)
reciprocal - issue confirmed by inspection
abs - issue confirmed by inspection
update(alpha,A,beta,B,gamma) - issue confirmed by inspection
elementWiseMultiply - issue confirmed by inspection
assign - issue confirmed by inspection 


Moreover, most functions which include a MV as an argument enforce a "The const is a lie rule" and this allow themselves to sync the const'd argument.  My updated update(alpha,A,beta) does not, but that is not the pattern in use elsewhere.

@mhoemmen

**Comment by csiefer2** [comment]
See #2791

**Comment by mhoemmen** [comment]
@csiefer2 wrote:
> Moreover, most functions which include a MV as an argument enforce a "The const is a lie rule" and this allow themselves to sync the const'd argument. My updated update(alpha,A,beta) does not, but that is not the pattern in use elsewhere.

FYI the original intent was to support a mix of solvers, some of which might work with device data, and some of which might only work with host data.  This implies the following guidelines, in decreasing order of priority:

  1. Only sync nonconst objects, if possible
  2. Let the biggest data structure stay put, if possible
  3. Preserve current sync status, if possible (this ensures that a host-only solver won't ping-pong data between host and device)

The problem is that we (@crtrott and I) didn't have time to implement these guidelines consistently, in the push to Kokkos-ize Tpetra circa 2014-15.  We had also planned to make Tpetra::Crs{Graph, Matrix} implement DualView semantics, like MultiVector, but didn't have time.  (BlockCrsMatrix actually does implement DualView semantics, for its values.  BlockCrsMatrix doesn't own its CrsGraph so it can't modify or sync its graph.)  This left Tpetra in an inconsistent state that more or less forced the UVM assumption and `CUDA_LAUNCH_BLOCKING=1`.  Consistent use of sync would fix the latter; DualView semantics for CrsGraph and CrsMatrix would help fix the former.

**Comment by mhoemmen** [comment]
@csiefer2 I realized an issue with the "original intent" presented above: Belos does not preserve sync state when it clones MultiVectors.  For example: https://github.com/trilinos/Trilinos/blob/75b13d9d1e975ab7c25ca175e07cde1d47536bd3/packages/belos/tpetra/src/BelosMultiVecTraits_Tpetra.hpp#L87

**Comment by csiefer2** [comment]
Policy decision: Kernel execuation will always happen on the device.  We will sync you there if we have to.

**Comment by csiefer2** [comment]
Policy decision(update): Non-unary kernel execution will always happen on the device. We will sync you there if we have to.

**Comment by csiefer2** [comment]
Current status:

multiVectorSingleColumnDot - updated for policy
normWeighted - is deprecated; will not fix
scale - scale(alpha,A) updated for policy
reciprocal - updated for policy
abs -updated for policy
update(alpha,A,beta,B,gamma) - updated for policy
elementWiseMultiply - updated for policy
assign - issue confirmed by inspection

Things I have not touched:

copyAndPermuteNew - not fixed yet
unpackAndCombineNew - not fixed yet
assign - Current code ensures *this copies the current state of the input argument on both host and device.  So data is *always* xfer'd between memory spaces on an assign.  I'm not sure we want to do this @mhoemmen

**Comment by mhoemmen** [comment]
@csiefer2 wrote:
> assign - Current code ensures *this copies the current state of the input argument on both host and device. So data is always xfer'd between memory spaces on an assign. I'm not sure we want to do this

How about this:
```
if input last modified on host:
  copy input host view to output host view
  allocate output device view
  mark output as modified on host
else: // either last modified on device, or host and device same 
  copy input device view to input device view
  allocate output host view
  mark output as modified on device
```

**Comment by csiefer2** [comment]
@mhoemmen I like.

**Comment by csiefer2** [comment]
The MultiVector cleanup (except for the pack/unpack routines) has been completed  And is available in the branch tpetra-multivector-sync-cleanup.  GPU performance is improved over develop and correctness does not seem to be impacted.

Start to think about application testing: @william76 @mhoemmen @kddevin

**Comment by csiefer2** [comment]
I make the initial syncs on the copy/unpack routines check need_sync first.

I don't want to muck any further with those unless we're sure there's an issue there.

Consider a fork stuck in my part of this guy.
