### ISSUE TITLE
Teuchos: Unit test system does not initialize Kokkos, if Kokkos is enabled

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#2774]
This has the side effect of making it impossible to use the Kokkos profiling tools on any of the unit tests.

This is the case because the unit test uses a Teuchos Timer, which tries to use a profiling region of an uninitialized Kokkos.  Segfaults ensue.

**Comment by mhoemmen** [comment]
Teuchos::GlobalMPISession doesn't initialize Kokkos, but it does nicely stash away command-line arguments so that Tpetra Nodes can initialize Kokkos on demand:

https://github.com/trilinos/Trilinos/blob/996e8c2c2423564955e16a322b8b786121c5d2f0/packages/teuchos/core/src/Teuchos_GlobalMPISession.cpp#L156

It's not hard to plug in a different unit test main that initializes Kokkos directly -- I can help w/ that.

**Comment by mhoemmen** [comment]
Actually it would make sense for Teuchos::GlobalMPISession to initialize Kokkos.  I don't see a good reason why it shouldn't.

**Comment by csiefer2** [comment]
We should do the thing!
