### ISSUE TITLE
Amesos-Pardiso: How do I change the number of threads?

### ISSUE THREAD

**Issue by ghtina** [trilinos/Trilinos#2807]
I am working with Pardiso and the examples provided by Amesos:  https://github.com/trilinos/Trilinos/tree/master/packages/amesos/example 
It works properly, but if I execute the compare-file, the time measured for Pardiso is worse than for Klu. Since it should work parallel, I expect better values. I think, the problem is that in Amesos_Pardiso.cpp  in https://github.com/trilinos/Trilinos/tree/master/packages/amesos/src the number of processes is only 1. I think I cannot change via ```omp_set_num_threads()```, the variable ``` num_procs ``` or alike. 
Does anybody now how to change the number of process or how I really apply OpenMP to the program?
Thanks in advance :)

**Comment by srajama1** [comment]
There is some confusion here between threads and ranks. We do not provide an i/f to distributed memory Pardiso. For the shared memory Pardiso, please check Pardiso documentation for correct usage of threads. It has to be balanced with the correct BLAS whether that is multithreaded or not. That said there are problems where Klu can do better than Pardiso (e.g. circuits).

**Comment by freaklovesmango** [comment]
Thank you. I looked into the documentation of Pardiso and found what I was looking for. I had to change IPARM(3) and therefore one must change OMP_NUM_THREADS e.g. in the shell.

Still, e.g. LAPACK produces better results and I try to figure out why. Do you have any more tips where I can recherche that or something because I think I didn't get the reason with BLAS so well. @srajama1 Thanks :)
