### ISSUE TITLE
Ifpack2::BlockTriDiContainer: Build warnings

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2853]
Here is a sample:
```
.../Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:1049:68: warning: typedef ‘using impl_scalar_type = typename impl_type::impl_scalar_type’ locally defined but not used [-Wunused-local-typedefs]
       using impl_scalar_type = typename impl_type::impl_scalar_type;
                                                                    ^
.../Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:1052:84: warning: typedef ‘using impl_scalar_type_4d_view = typename impl_type::impl_scalar_type_4d_view’ locally defined but not used [-Wunused-local-typedefs]
       using impl_scalar_type_4d_view = typename impl_type::impl_scalar_type_4d_view;
                                                                                    ^
.../Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:3366:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (Z.getNumVectors() != num_vectors)
                               ^
.../Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:996:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         btdm.is_diagonal_only = (nblocks() == ntridiags);
                                            ^
.../Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:1055:21: warning: unused variable ‘vector_length’ [-Wunused-variable]
       constexpr int vector_length = impl_type::vector_length;
                     ^
.../Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:1474:60: warning: ‘Ifpack2::BlockTriDiContainerDetails::ExtractAndFactorizeTridiags<Tpetra::RowMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> > >::flat_td_ptr’ will be initialized after [-Wreorder]
       const ConstUnmanaged<size_type_1d_view> pack_td_ptr, flat_td_ptr;
                                                            ^
.../Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:1474:47: warning:   ‘Ifpack2::BlockTriDiContainerDetails::ConstUnmanaged<Kokkos::View<long unsigned int*, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace> > > Ifpack2::BlockTriDiContainerDetails::ExtractAndFactorizeTridiags<Tpetra::RowMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> > >::pack_td_ptr’ [-Wreorder]
       const ConstUnmanaged<size_type_1d_view> pack_td_ptr, flat_td_ptr;
                                               ^
.../Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:1485:7: warning:   when initialized here [-Wreorder]
       ExtractAndFactorizeTridiags(const BlockTridiags<MatrixType> &btdm_,
       ^
```
This blocks Sierra promotion, as they build with signed / unsigned comparison warnings enabled.

**Comment by mhoemmen** [comment]
@trilinos/ifpack2

**Comment by mhoemmen** [comment]
@rrdrake @prwolfe

**Comment by kyungjoo-kim** [comment]
what is the cmake setup to prevent this happening ? 
```
Trilinos_ENABLE_STRONG_CXX_WARNING:BOOL=ON
```
Does this suffice to catch all warnings that can block promotion ?

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe Can we check warnings that are required to be removed for promotion in PR testing ?

**Comment by ndellingwood** [comment]
@kyungjoo-kim you could also try adding `-Wall` and `-Werror` to the `CMAKE_CXX_FLAGS` variable - it looks like the above error message was with an OpenMP build. I would avoid these with Cuda builds since there are lots of warnings in several packages that may prevent you from seeing those in Ifpack2.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Can we check warnings that are required to be removed for promotion in PR testing ?

@kyungjoo-kim, I think for that to occur, we would need to remove all warnings from these PR builds and then add `-Werror` to the compile options for these builds.  We should do that but that will require someone to do the work to clean up all of warnings in the Primary Tested packages for these PR builds.  I think the only people who could make this happen are the Trilinos product leads (@kddevin, @srajama1, @rppawlo, @mperego, @jwillenbring) and the Trilinos lead @maherou.  I think it would take that group of people and support from management for that to happen (because it is a lot of work and it is not sexy at all).

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim, it really needs to be zero warnings and use `-Werror` (but perhaps allow deprecated and other warnings with `-Wno-deprecated-warnings`).  It needs to be zero for the same reason that the  number of failing tests needs to be zero.  That is because 2 warnings (or failed tests) is indistinguishable (for all practical proposes) from  1 warning (or failed tests) and so on (i.e. the "broken window effect").

It is not all that hard to get to zero warnings for any particular compiler or piece of code (I have been doing it for 15+ years).  It just takes time and effort.  And once you have 0 warnings, it is pretty easy to maintain.

**Comment by ndellingwood** [comment]
@kyungjoo-kim you could try just adding `-Wall`, but also if you build with `make -k -jN` the `-k` means "keep going" so the build won't stop at the first error and this may help make it to the warnings that occurred.

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe In principle, I agree with you. In my opinion, generating warning free code is another issue. A problem is that a policy about the software quality is different (or differently enforced) in Trilinos and Sierra (or other applications). Something we are allowed to commit and push is not allowed in the application code according to their software quality policy. As PR testing is a gate keeper, it can control and guide developers to follow or enforce the required software quality. In this particular issue case, I wrote a code but did not know a certain types of warnings should be removed for promotion to Sierra. Then, Mark pointed out the problem. I think that this can be automated and it does not require someone's eye watching.

**Comment by mhoemmen** [comment]
Adding `-Wall` to the build isn't so hard.

**Comment by kyungjoo-kim** [comment]
The PR is merged. Thus, I am closing this issue.

**Comment by mhoemmen** [comment]
Thanks @kyungjoo-kim !  I know this seems like busy work, but it's really important to Sierra and the other applications.

**Comment by kyungjoo-kim** [comment]
@mhoemmen It is completely fine with me. I just hope that I have recorgnized this problem earlier and have fixed it in the first PR.

**Comment by mhoemmen** [comment]
@kyungjoo-kim I agree that it would make sense for PR testing to use `-Werror`.
