### ISSUE TITLE
Update scripts for python 3 (backward compatible with 2)

### ISSUE THREAD

**Issue by eric-c-cyr** [trilinos/Trilinos#290]
Currently the scripts fail if run with a python 3 interpreter. They work fine for python 2. It would be good to work for both.

**Comment by wfspotz** [comment]
I have this update done in a local branch on my laptop. I am currently trying to get PyTrilinos to work for Python 3, which is a taller order. Let me know if you want me to push.

**Comment by eric-c-cyr** [comment]
You changed over the panzer scripts as well? Do you have this change scripted, or is it manual?

**Comment by wfspotz** [comment]
I changed "all" the build-related files and scripts.  I big part of this was CMakeLists.txt files with something like the following:

    EXECUTE_PROCESS(COMMAND ${PYTHON_EXECUTABLE} -c "import sys; print sys.prefix" ...)

where the "print sys.prefix" would have to be changed to "print(sys.prefix)". As one example.

I said "all" above in quotes because I did not have all of the packages enabled. Panzer is included in the list of disabled packages. Before I push, I will have to test with all packages enabled.

If I do this:

    $ cd packages/panzer; find . -name *.py -print
    ./adapters-stk/example/MixedPoissonExample/convergence_rate.py

I only find 1 python script. Are there others?  What I did was manual, although there are scripts available for converting Python 2 to 3, although it is not always clear what the automatic change should be. In converting PyTrilinos, I have become familiar with all of the most common changes between Python 2 and 3, and some of the less common ones, so I am happy to be of help.

**Comment by eric-c-cyr** [comment]
I think we would appreciate the help. Do you know if the changes being made for python 3 will work with python 2? Or will we require python 3 interpreters (these are not yet universal, and in the archaic rhel6 they are still python 2).

**Comment by wfspotz** [comment]
It is possible to write code that is compatible with both Python 2 and Python 3. Often it is just changing `print` from a statement to a function. Sometimes it is changing deprecated syntax to non-deprecated. And then sometimes it requires a `from __future__ import ...` statement, which I believe puts some restrictions on what version of Python 2 you can use.

**Comment by eric-c-cyr** [comment]
Okay, I think we should go ahead and try to do this. It keeps hanging me up and most of the fixes work with python 2 and 3. @rppawlo any thoughts on this?

**Comment by rppawlo** [comment]
Definitely want support for both 2 and 3 due to COE. Do we have more scripts in Drekar that need to be converted?

**Comment by eric-c-cyr** [comment]
Yes, Drekar has a few scripts. I started but got nervous about the python2 and 3 versioning issues.

**Comment by wfspotz** [comment]
Update: I have been working to upgrade TriBITS to work under both Python 2 and 3, which is a prerequisite to getting Trilinos to work. I have 192 of the 193 TriBITS tests working, and have asked Ross to help with the last one. Once that is done, I will merge the PyTrilinos upgrade I have already completed. That will introduce the appropriate changes to the Trilinos build system (stuff like `${PYTHON_EXECUTABLE} -c` CMake commands). Then I can get to Panzer. Is Drekar in a different repository?

**Comment by jmgate** [comment]
I can tackle this for Panzer and Drekar if you like.  I've just gotten everything build on my RHEL7 machine and am seeing about a fifth of our tests fail due to these compatibility issues.  It doesn't look like the necessary changes should be too bad.

**Comment by jmgate** [comment]
Pushed changes to Panzer, Drekar, and Charon that should take care of all of our python 2/3 compatibility issues.  There may be an issue with python < 2.7&mdash;not sure about that.
