### ISSUE TITLE
 MueLu_UnitTestsTpetra_MPI_4 fails in all openMP builds

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#3035]
see #3003 and any openMP build
https://testing-vm.sandia.gov/cdash/testSummary.php?project=1&name=MueLu_UnitTestsTpetra_MPI_4&date=2018-06-28

@mhoemmen thinks this is related to some recent repartitioning work.

@trilinos/muelu 

## Expectations
I will turn this off for the 4.8.4 PR build, we will need to re-enable it when this is fixed.

## Related Issues
* Blocks #3034
* Related to #3003

**Comment by fryeguy52** [comment]
@bartlettroscoe 

This is also failing on 11 of the 15 openmp ATDM nightly builds.  Shown here: 

[Tests result for openmp builds 2018-07-01](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-07-01&filtercount=5&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=MueLu_UnitTestsTpetra_MPI_4&field2=buildname&compare2=63&value2=Trilinos-atdm&field3=buildname&compare3=63&value3=-openmp&field4=buildstarttime&compare4=83&value4=2018-07-01&field5=buildstarttime&compare5=84&value5=2018-07-02)

It has been failing since 6/28.  Is the temporary solution to disable this test?

**Comment by bartlettroscoe** [comment]
CC: @trilinos/muelu, @srajama1 (Trilinos Leader Solvers Product Area Lead)

Okay, I can see in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-07-02&limit=0&filtercount=3&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=MueLu_UnitTestsTpetra_MPI_4&field2=buildname&compare2=63&value2=Trilinos-atdm&field3=buildname&compare3=63&value3=-openmp) that of the 12 builds where this test runs, it fails in all but four builds on 'chama' and 'serrano'.  Specifically, the builds were it is failing are:

* Trilinos-atdm-hansen-shiller-gnu-debug-openmp 
* Trilinos-atdm-hansen-shiller-intel-debug-openmp
* Trilinos-atdm-hansen-shiller-intel-opt-openmp
* Trilinos-atdm-hansen-shiller-gnu-opt-openmp
* Trilinos-atdm-white-ride-gnu-opt-openmp
* Trilinos-atdm-rhel6-intel-opt-openmp
* Trilinos-atdm-rhel6-gnu-opt-openmp
* Trilinos-atdm-rhel6-gnu-debug-openmp

The test passed in the builds:

* Trilinos-atdm-chama-intel-opt-openmp
* Trilinos-atdm-chama-intel-debug-openmp
* Trilinos-atdm-serrano-intel-debug-openmp
* Trilinos-atdm-serrano-intel-opt-openmp

Therefore, we should not disable the test in those builds.  I am also changing the title of the issue so that it is clear that this test is not failing in **all** OpenMP builds.

**Comment by bartlettroscoe** [comment]
Actually, looking at the test output for one of the "passing" tests [here](https://testing.sandia.gov/cdash/testDetails.php?test=50297520&build=3664432), it does not look like that test actually passed (or it should not have passed) because it showed a bunch of errors after the printed end result "End Result: TEST PASSED" like:

```
Kokkos allocation "DualView::modified_host" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "DualView::modified_device" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "MV::DualView" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "DualView::modified_host" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
...
```

Note that this test also failed the standard post-push CI build starting 6/20/2018 as shown at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3640100

(Not sure why I did not get an email about that.)

**Comment by bartlettroscoe** [comment]
FYI: In the builds where this test actually fails like shown [here](https://testing.sandia.gov/cdash/testDetails.php?test=50276232&build=3664585) some unit tests we see the errors:

```
nNumProcsReb = 2 == expectedPartitions = 1 : FAILED ==> /jenkins/slave/workspace/Trilinos-atdm-rhel6-gnu-debug-openmp/SRC_AND_BUILD/Trilinos/packages/muelu/test/unit_tests/BlockedRepartition.cpp:378
...
[FAILED]  (0.0402 sec) BlockedRepartition_double_int_int_Kokkos_Compat_KokkosOpenMPWrapperNode_BlockedRAPFactory_UnitTest
 Location: /jenkins/slave/workspace/Trilinos-atdm-rhel6-gnu-debug-openmp/SRC_AND_BUILD/Trilinos/packages/muelu/test/unit_tests/BlockedRepartition.cpp:166
...
nNumProcsReb = 2 == expectedPartitions = 1 : FAILED ==> /jenkins/slave/workspace/Trilinos-atdm-rhel6-gnu-debug-openmp/SRC_AND_BUILD/Trilinos/packages/muelu/test/unit_tests/BlockedRepartition.cpp:378
...
 [FAILED]  (0.0384 sec) BlockedRepartition_double_int_longlong_Kokkos_Compat_KokkosOpenMPWrapperNode_BlockedRAPFactory_UnitTest
 Location: /jenkins/slave/workspace/Trilinos-atdm-rhel6-gnu-debug-openmp/SRC_AND_BUILD/Trilinos/packages/muelu/test/unit_tests/BlockedRepartition.cpp:166
...

The following tests FAILED:
    56. BlockedRepartition_double_int_int_Kokkos_Compat_KokkosOpenMPWrapperNode_BlockedRAPFactory_UnitTest ... 
    58. BlockedRepartition_double_int_longlong_Kokkos_Compat_KokkosOpenMPWrapperNode_BlockedRAPFactory_UnitTest ... 

Total Time: 40.5 sec

Summary: total = 465, run = 465, passed = 463, failed = 2

End Result: TEST FAILED
```

and then we see a bunch of `Kokkos::finalize` failures like:

```
Kokkos allocation "DualView::modified_host" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "DualView::modified_device" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "MV::DualView" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
```

This is why we need an OpenMP build in PR testing.

**Comment by mhoemmen** [comment]
@trilinos/muelu My guess is that MueLu is keeping around a Tpetra::MultiVector (maybe coordinates or a `MultiVector<int>`) inside an RCP in a ParameterList.

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-07-12&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=MueLu_UnitTestsTpetra_MPI_4&field2=groupname&compare2=62&value2=Pull%20Request&field3=groupname&compare3=62&value3=Experimental&field4=groupname&compare4=62&value4=Nightly&field5=groupname&compare5=62&value5=Specialized) yesterday, this test does not fail in any of the "Clean", "Continuous" or "ATDM" builds of Trilinos.  This test is shown missing in several of that ATDM builds and the CI build as expected.

I am marking this as "Disabled Tests".

@trilinos/muelu,

Would it be possible for a MueLu developer to see about getting this test fixed?  A test called "MueLu_UnitTestsTpetra" would seem to be pretty important and should be running the OpenMP builds so it would be good to fix at some point soon, no?

**Comment by srajama1** [comment]
@bartlettroscoe : We will take care of this next week. Folks are at SIAM PP this week.

**Comment by jhux2** [comment]
@fryeguy52 @bartlettroscoe For the dashboard tests where the MueLu unit test suite is failing, how many threads per MPI process are being used?

**Comment by bartlettroscoe** [comment]
@jhux2 said:

> For the dashboard tests where the MueLu unit test suite is failing, how many threads per MPI process are being used?

I think all of the builds in question you `OMP_NUM_THREADS=2`.

**Comment by bartlettroscoe** [comment]
The test `MueLu_UnitTestsTpetra_MPI_4` is shown passing in the PR #3020 GCC 4.8.4 build as shown [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=49436035&build=3665760).  Is that before OpenMP was actually enabled in that auto PR build?

Anyway, if you look at the post-push CI build that has been an OpenMP build for a long time shown [here](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_OPENMP_CI&field2=groupname&compare2=61&value2=Continuous&field3=buildstarttime&compare3=84&value3=now&field4=buildstarttime&compare4=83&value4=8%20weeks%20ago), you can see the first iteration where this test failed was on 6/20/2018 shown at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3640100

where the new commits pulled that CI iteration are shown at:

* https://testing-vm.sandia.gov/cdash/viewNotes.php?buildid=3640101#!#note1

which show:

```
550762c:  Merge pull request #2981 from aprokop/muelu_fix_partition
Author: Andrey Prokopenko <andrey.prok@gmail.com>
Date:   Wed Jun 20 14:47:17 2018 -0400

c2d8d1b:  MueLu: kokkos: fix computing numPartitions for multiple threads
Author: Andrey Prokopenko <prokopenkoav@ornl.gov>
Date:   Tue Jun 19 13:29:46 2018 -0400
```

@jhux2, could the commit c2d8d1b have been the original cause?

**Comment by lucbv** [comment]
@bartlettroscoe, as @jhux2 mentioned earlier, #3014 is really where this started and #3020 was just an attempt at fixing it although it apparently was not enough...

**Comment by jhux2** [comment]
@bartlettroscoe @prwolfe @fryeguy52 This should be resolved with the above commit. Here's a test that was failing on [Friday](https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3693925), and the same [today](https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3698666).  Please reenable the unit tests `MueLu_UnitTestsTpetra_MPI_4` for OpenMP.

**Comment by bartlettroscoe** [comment]
> This should be resolved with the above commit. Here's a test that was failing on Friday, and the same today. Please reenable the unit tests MueLu_UnitTestsTpetra_MPI_4 for OpenMP.

@jhux2, someone just needs to delete the `set(MueLu_UnitTestsTpetra_MPI_4_DISABLE ON ...)` statements from these recent commits:

```
$ [rabartl@crf450 Trilinos (develop)]$ git log-short --name-status -SMueLu_UnitTestsTpetra_MPI_4_DISABLE 

06b1ca0 "Disable MueLu_UnitTestsTpetra_MPI_4 for standard CI GCC 4.8.4 OpenMP build (#3035)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Fri Jul 6 15:19:49 2018 -0600 (2 weeks ago)

M       cmake/std/GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP.cmake

5e52db0 "Disable failing MueLu test in ATDM openmp builds"
Author: Joe Frye <jfrye@sandia.gov>
Date:   Tue Jul 3 07:38:57 2018 -0600 (3 weeks ago)

M       cmake/std/atdm/ATDMDevEnvSettings.cmake

06f6584 "Turn off failing MueLu/Tpetra test - see #3034 and #3035"
Author: Paul Wolfenbarger <prwolfe@sandia.gov>
Date:   Fri Jun 29 09:43:24 2018 -0600 (3 weeks ago)

M       cmake/std/PullRequestLinuxGCC4.8.4TestingSettings.cmake

c051b6c "Intel PR config now disables the 6 tests that fail"
Author: Paul Wolfenbarger <prwolfe@sandia.gov>
Date:   Thu May 24 09:23:17 2018 -0600 (9 weeks ago)

T       cmake/std/PullRequestLinuxIntelTestingSettings.cmake
```

Just needs to create one (or more) commits that deletes this `set()` statement and then post a PR for that.

**Comment by bartlettroscoe** [comment]
With the merge of PR #3172 to 'develop' on 7/27/2018, it looks like the test ??? is passing in all of the OpenMP ATDM Trilinos builds as shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-07-29&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=-openmp&field3=testname&compare3=61&value3=MueLu_UnitTestsTpetra_MPI_4&field4=groupname&compare4=61&value4=ATDM).

Therefore, it appears this issue is addressed and can be closed (and the "Disabled Tests" label can be removed).
