### ISSUE TITLE
MueLu: signed/unsigned comparison warning in master

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#3177]
@vbrunini reports a signed-unsigned comparison build error in Trilinos:master, in `packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_def.hpp:193`:
```
.../MueLu_TentativePFactory_def.hpp: In instantiation of 'void MueLu::TentativePFactory<Scalar, LocalOrdinal, GlobalOrdinal, Node>::BuildP(MueLu::TentativePFactory<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Level&, MueLu::TentativePFactory<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Level&) const [with Scalar = double; LocalOrdinal = int; GlobalOrdinal = long int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>; MueLu::TentativePFactory<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Level = MueLu::Level]':
    [REDACTED]:   required from here

.../MueLu_TentativePFactory_def.hpp:193:34: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
             for (LO lnode = 0; lnode < numNodes; lnode++) {
```

@trilinos/muelu

**Comment by lucbv** [comment]
@mhoemmen I'll take care of this one, it should be quick!

**Comment by lucbv** [comment]
@mhoemmen 
After a quick look, this is already fixed in develop, the line now looks like this:
```
for (LO lnode = 0; lnode < Teuchos::as<LO>(numNodes); lnode++) {
```
Is there a procedure to have this go from develop to master outside of the regular promotion?

**Comment by mhoemmen** [comment]
@lucbv wrote:
> Is there a procedure to have this go from develop to master outside of the regular promotion?

@william76 could tell you more, but I think any nonstandard procedure should be reserved for emergencies.  The point of Sierra's Trilinos integration build is to identify an integration candidate.

**Comment by william76** [comment]
@lucbv @mhoemmen 

There is not at this time since the develop -> master check is based on whether or not all the nightlies in the Clean track have passed.  We're working on an automated develop -> master test that would work via a special pull request which would make an attempt 2 or 3 times per day.

@jwillenbring any thoughts on how we'd address this?

**Comment by mhoemmen** [comment]
btw I don't think this is an emergency -- we Sierra folks are just trying to be proactive in getting the Sierra-Trilinos integration build to be clean as much as possible.  We would like to do a Trilinos integration soon, but doesn't _have_ to be today.

**Comment by mhoemmen** [comment]
On the other hand, maybe it's good if people think it's an emergency ;-)

**Comment by vbrunini** [comment]
How much time usually passes between successful develop -> master promotions? If it's normally just a couple of days I wouldn't worry about it. If cases like the most recent one where there were some ROL test failures and it took multiple weeks are common then we might need something sooner. The more changes to develop that happen between merges to master the harder it is for us to deal with issues that pop up on the Sierra side.

**Comment by mhoemmen** [comment]
@vbrunini If we discount the ROL issue as an anomaly, @william76 reports a successful develop-to-master integration about every other day.  I'm not sure what the stats are now.

**Comment by dridzal** [comment]
Just to confirm that the delay in ROL was an anomaly.  Consider this:

-- we passed all local ROL testing (with the standard pre-push check-in setup);
-- we passed Trilinos PR testing;
-- yet some tests failed in the Trilinos Clean build a few days later (??);
-- the ROL developers responsible for fixing this went on a 9-day foreign trip the following day, followed by a 10-day vacation, without access to the ROL testing infrastructure.  As a hard rule, we don't issue PRs to Trilinos without extensive testing in ROL.

One way to make sure that this doesn't happen again is to make PR builds equal to the Clean builds.  Why are they not?  @jwillenbring @bartlettroscoe maybe you can chime in?  Another option is to let the @trilinos/rol team know which settings are used for the Clean build, so that we can include it in ROL's nightly tests, or deploy it instead of the default pre-push testing that we use on the ROL side to synchronize ROL and Trilinos (prior to issuing PRs to Trilinos).  With the Clean build's configuration properly matched, we would have caught this in ROL long before it appeared in the Trilinos Clean track.  Still, I also think that PR testing should have caught this.  There is obviously a mismatch in the configurations.

**Comment by bartlettroscoe** [comment]
@dridzal, I think including the Clean builds in the ROL nightly builds is likely the best way to handle this.  From CDash, you can see the `*.cmake` file fragment that is included in the build with the `-C` CMake option.  But what you don't see there is the script needed to load the env.  If they the @trilinos/framework team can tell you that, then it should be pretty easy to set up nightly ROL builds that run these Clean builds as well (I can show you how to do that).

**Comment by mhoemmen** [comment]
We also could have simply reverted ROL's snapshot into Trilinos until the ROL developers came back.  It's totally OK to go on vacation :-)  Why didn't we just do that?

**Comment by bartlettroscoe** [comment]
@mhoemmen, what build has these warnings elevated into an error?

**Comment by mhoemmen** [comment]
@bartlettroscoe Are you talking about #3177?

**Comment by mhoemmen** [comment]
@bartlettroscoe Sierra's Trilinos integration build

**Comment by mhoemmen** [comment]
It's the usual set of Sierra warning options

**Comment by william76** [comment]
@mhoemmen @vbrunini 
I've been keeping stats on my dev->master pushes now since March... on average it's been a little less than 50% of the time I can do the merge.  Some weeks I can do one daily and other weeks I can't get one in at all.  The ROL issue was an anomaly that blocked the merge for almost a month though.

**Comment by dridzal** [comment]
@bartlettroscoe  I agree with your idea to use the Clean setup for ROL testing, however, can you explain why PR testing isn't equivalent to Clean testing?  If we are going to promote develop to master based on Clean, doesn't it make sense that the PR builds be identical to the Clean builds?  If the current PR build needs to be different for whatever reason, can we start multiple builds for PR testing, and require that _all_ pass before merging?

**Comment by lucbv** [comment]
@dridzal I am pretty sure that the Clean builds are more extensive and hence longer than the PR builds and the PR builds are already taking a few hours to complete. It might not be feasible or desirable to have such long waits before PR can be merged. I guess that some statistic could be gathered on how much capacity the auto-tester system has?

**Comment by bartlettroscoe** [comment]
@dridzal, I don't know why the Clean builds and the PR builds are different.  Really, the [additive test assumption of branches](https://docs.google.com/document/d/1uVQYI2cmNx09fDkHDA136yqDTqayhxqfvjFiuUue7wo/edit#bookmark=id.d1jneh8ubsyn) would require the PR builds to be included in the Clean builds but I don't think that is the case.  The current PR testing process does **not** guarantee that the 'develop' branch will pass all of the PR builds (for an example of this, see #3106).

I think the plan is to run another process that runs the PR builds along with the other Clean build post-push to 'develop' in order to update the 'master' branch.  You should talk with your Product Area Lead @rppawlo about these issues as he is your representative in the Trilinos Leadership Team.  I think he can represent your needs to the Trilinos Framework Product Area Lead.

**Comment by jhux2** [comment]
Closing, as the [commit](https://github.com/trilinos/Trilinos/commit/e446eabb1c14ed8831a37b4f098429c7372b21a0) that fixes the warning is now in master.
