### ISSUE TITLE
Epetra64: Epetra_CrsMatrix throws if given a Map with a 64-bit (long long) number of rows; 32-bit (int) number of rows is OK

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#3192]
I was working on #3139, in particular on an Ifpack2 BlockRelaxation test that @brian-kelley wrote, that compares Ifpack2 and ML performance.  My first pass of changes used a 64-bit (`long long`) value for the global number of rows, when building both an Epetra and a Tpetra Map.  The test threw in that case.  However, when I gave `Epetra_Map`'s constructor the global number of rows as a 32-bit (`int`) value, the test passed.

@trilinos/epetra @trilinos/tpetra @trilinos/ifpack2 @kddevin 

## Expectations

`Epetra_CrsMatrix` should behave the same, whether its row Map was created with a 64-bit or 32-bit global number of indices.

## Current Behavior

```c++
using GO = long long;
const GO localRows = 5000;

#ifdef EPETRA_MPI
Epetra_MpiComm ecomm(MPI_COMM_WORLD);
#else
Epetra_SerialComm ecomm;
#endif

// If I cast localRows to int, this code doesn't throw.
// Otherwise, something after the Epetra_Map constructor will throw.
Epetra_Map rowmap(localRows, 0, ecomm);

Teuchos::RCP<Epetra_CrsMatrix> crsmatrix = 
  Teuchos::rcp(new Epetra_CrsMatrix(Epetra_DataAccess::Copy, rowmap, 3));
int numRows = rowmap.NumGlobalElements();
double tile[3] = {-2, 4, -2};
int firstCols[] = {0, 1};
crsmatrix->InsertGlobalValues(0, 2, tile + 1, firstCols);
for(int row = 1; row < numRows - 1; row++)
{
  int cols[] = {row - 1, row, row + 1};
  crsmatrix->InsertGlobalValues(row, 3, tile, cols);
}
int lastCols[] = {numRows - 2, numRows - 1};
crsmatrix->InsertGlobalValues(numRows - 1, 2, tile, lastCols);
crsmatrix->FillComplete();
```

I see now that the code passes 32-bit global column indices into `InsertGlobalValues`.  Is it wrong to do that after creating a row Map with a 64-bit global number of rows?  That's very easy to do when writing Epetra vs. Tpetra comparisons.

## Motivation and Context

This hindered #3139.  Also, we're generally interested in Epetra vs. Tpetra performance comparisons.

## Related Issues
* Related to #3139

**Comment by maherou** [comment]
If I understand the situation correctly, what happens when the type of firstCols[], cols[] and lastCols[] is changed to GO?  I don't think the 32-bit InsertGlobalValues interfaces are compatible with matrices constructed using 64-bit values.

**Comment by mhoemmen** [comment]
@maherou I added a PR with a test that exhibits this issue: https://github.com/trilinos/Trilinos/pull/3199

I had to do two things to get the test to pass, when the Map was created with a `long long`:

  1. Call `NumGlobalElements64` instead of `NumGlobalElements`
  2. Use `long long` instead of `int` for `InsertGlobalValues`

Otherwise, Epetra throws.  `NumGlobalElements` doesn't even throw properly; it claims to have thrown `const char*`, but calls `std::terminate` directly; I can't even catch that `const char*`.

Is this how Epetra64 is supposed to behave?  I'm not a fan of `Epetra_Map` deciding to throw based only on the type of integer given to its constructor, but if it's supposed to be that way, then I'll close this issue.

**Comment by maherou** [comment]
Epetra’s convention for constructors is to throw an exception.  Epetra was designed to support Fortran and C wrappers by returning integers on method calls, but there was no way to do so with constructors, so we used exceptions, and the Fortran/C application code had to wrap constructors in another function if they wanted to protect against termination.  

When 64 int support was added, we used templates to make the implementation easier, but did not instantiate all possible combinations that might make sense.  Specifically, it would make sense that you could pass in an array of int’s for global column indices, even if the matrix was constructed with long long global IDs.  We didn’t see this as a common use case.

I think you could argue that the InsertGlobalValues method should use the macro EPETRA_CHK_ERR instead of calling ReportError, for this error condition since it is not a constructor.  I am not sure it is worth modifying the existing code to obtain this behavior, and the change may disrupt users who have already adapted to the current approach.

Thanks for your efforts.

**Comment by mhoemmen** [comment]
OK, that's fine.  I'll mark this issue as "wontfix" and close it.
