### ISSUE TITLE
ROL: ROL_example_PinT_parabolic-control_AugmentedSystem_test failing in nightly Clean track

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#3311]
@trilinos/rol 
@dridzal 
@trilinos/framework (FYI)

The test ROL_example_PinT_parabolic-control_AugmentedSystem_test is failing in the nightly Clean track for the `Linux-gcc-4.9.3-SERIAL_Release_gcc_4.9.3__DEV` build.

Test Output from [CDash][3]:
```
Test output
Teuchos::GlobalMPISession::GlobalMPISession(): started serial run
ERROR: -5016 MPI is not in good status.
ERROR: -5016 MPI aborting...
```

## Expectations
Nightly testing errors in the [Clean track][1] prevent the daily develop to master merge for Trilinos and is a high priority to fix.  

## Possible Solution
If this looks like it will take more than a day to fix, we can revert the merge from 8/14 ROL update: d54888e9b393bdb1c9d7c9a5a82ec1cda980ff8a

## Steps to Reproduce
CDash information for the build that could be used to reproduce the test is [here][2].

[1]: https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2018-08-16&filtercount=2&showfilters=1&filtercombine=or&field1=groupname&compare1=63&value1=Clean&field2=groupname&compare2=63&value2=Continuous
[2]: https://testing.sandia.gov/cdash/buildSummary.php?buildid=3733398
[3]: https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3733398

**Comment by dridzal** [comment]
@william76 , we have something in the works already; stay tuned.

@trilinos/framework @bartlettroscoe @mhoemmen @maherou @trilinos/rol , there is a major issue here that everyone seems to be ignoring.  To set the stage, ROL lives in its own repo, but it is synced with Trilinos through two-way merges and pull requests.  Before we issue a PR, we require 6 nightly clean builds on the ROL side.  Check.  Then we run two-way testing of ROL and Trilinos using the old pre-push testing infrastructure.  Check.  Then we issue a PR, which results in additional builds.  Check.  Then, we find out that a Clean build has failed.  This has happened with nearly half of recent ROL/Trilinos syncs.  There is something fundamentally wrong in how PR testing is done.  Thus far, PR testing hasn't caught a single issue that ROL's nightly testing or ROL/Trilinos two-way pre-push testing hasn't already flagged.  I strongly suggest that the Clean builds be included in PR testing.  Otherwise, it's close to meaningless.

Sure, we can add the Clean builds into ROL's nightly testing (and we will).  However, not every developer/team will have the infrastructure and resources needed to do so.  If the most important builds are the Clean builds, then PR testing must include them.   If they would take too long, then we need to rethink the PR testing infrastructure.

**Comment by mhoemmen** [comment]
It looks like the PR tests aren't configuring ROL in the same way that ROL's tests are.  Otherwise, ROL's tests would have seen the missing header files in `rol/adapters/mpi/src/CMakeLists.txt`.  We should be able to fix this by adding or changing a ROL test to use the same configuration as one of Trilinos' PR tests.

I would actually consider this issue a victory for PR testing, in that we caught a configuration case that ROL's tests didn't cover.  "We" here means both Trilinos' PR testing, and SPARC's Trilinos build.

**Comment by dridzal** [comment]
@mhoemmen , I think you're referring to a different issue.  Neither the missing header file nor the MPI issue (due to running an MPI-only test in serial) were caught by PR testing.  Other builds (Clean and Albany/SPARC) have found them.  I really think the Clean build needs to be part of PR testing.

**Comment by william76** [comment]
Closing this, I think it was fixed a while ago.
