### ISSUE TITLE
KokkosKernels and KokkosContainers tests timing out on ATDM waterman builds starting 8/16/2018

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3336]
CC: @trilinos/kokkos-kernels , @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe 
 
## Next Action Status

<status-and-or-first-action>

## Description

Some KokkosKernals test are timing out on the debug builds on waterman

The following tests are failing in the job `Trilinos-atdm-waterman-cuda-9.2-debug`:
* KokkosKernels_sparse_serial_MPI_1 
* KokkosContainers_UnitTest_Serial_MPI_1 

as shown [here](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-08-21&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-debug&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun) 

And the following tests are failing in the job `Trilinos-atdm-waterman-gnu-debug-openmp`:
* KokkosKernels_sparse_serial_MPI_1 
* KokkosContainers_UnitTest_Serial_MPI_1 
* KokkosKernels_sparse_openmp_MPI_1
* KokkosKernels_graph_serial_MPI_1

as shown [here](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-08-20&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-gnu-debug-openmp&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun) 

## Steps to Reproduce

One should be able to reproduce this failure on the machine <supported-atdm-machine> as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system <supported-atdm-system> are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman

The exact commands to reproduce this issue should be:

```

$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Kokkos=ON \
  $TRILINOS_DIR

$ make NP=20

$ bsub -x -Is -n 20 ctest -j20
```

**Comment by bartlettroscoe** [comment]
@trilinos/kokkos-kernels,  @trilinos/kokkos, @kddevin (Trilinos Data Services Product Lead),

This issue has not been touched since it was created on 8/22/2018.  The test ??? has been timing out every day since 8/16/2018 as shown [here](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-09-24&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-gnu-debug-openmp&field2=testname&compare2=61&value2=KokkosContainers_UnitTest_Serial_MPI_1&field3=buildstarttime&compare3=83&value3=2018-08-01).

Can we go ahead and (temporarily) disable these test?

**Comment by srajama1** [comment]
@bartlettroscoe This is being addressed in Kokkos Kernels by @ndellingwood

**Comment by bartlettroscoe** [comment]
As shown [in this query today](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-10-19&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-waterman-&field2=status&compare2=62&value2=passed), no Kokkos or KokkosKernels tests are timing out in any builds.  This is due to the PR #3660 merged on 10/18/2018 which disabled the test `KokkosContainers_UnitTest_Serial_MPI_1` in the build `Trilinos-atdm-waterman-cuda-9.2-debug`.  We see that test newly missing today [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?buildid=4068290).

Now that all of these Kokkos and KokkosKernels tests are run in the new `release-debug` builds, we have full runtime debug checking running in all of these tests.

I am closing this as complete (not as "Disabled Tests" because the `release-debug` builds are running these tests with runtime mode debug-mode checking but with optimized compiler options).
