### ISSUE TITLE
Framework: Recent STK update breaks ROL's downward dependency testing

### ISSUE THREAD

**Issue by dridzal** [trilinos/Trilinos#3407]
@trilinos/framework @trilinos/stk @trilinos/panzer @trilinos/rol 

## Expectations
Restore ROL's downward dependency testing.

## Current Behavior

https://testing-vm.sandia.gov/cdash/viewBuildError.php?buildid=3913799

Build error:

`/ascldap/users/dridzal/development/TEST/rol-trilinos/Trilinos/packages/stk/stk_util/stk_util/parallel/CommNeighbors.cpp: In member function ‘virtual ompi_communicator_t* stk::CommNeighbors::setup_neighbor_comm(stk::ParallelMachine, const std::vector<int>&, const std::vector<int>&)’: /ascldap/users/dridzal/development/TEST/rol-trilinos/Trilinos/packages/stk/stk_util/stk_util/parallel/CommNeighbors.cpp:81:30: error: ‘MPI_UNWEIGHTED’ was not declared in this scope    const int* weights = (int*)MPI_UNWEIGHTED;
                               ^
/ascldap/users/dridzal/development/TEST/rol-trilinos/Trilinos/packages/stk/stk_util/stk_util/parallel/CommNeighbors.cpp:86:43: error: ‘MPI_Dist_graph_create_adjacent’ was not declared in this scope                info, reorder, &neighborComm);                                            ^ /ascldap/users/dridzal/development/TEST/rol-trilinos/Trilinos/packages/stk/stk_util/stk_util/parallel/CommNeighbors.cpp: In member function ‘virtual void stk::CommNeighbors::perform_neighbor_communication(MPI_Comm, const std::vector<unsigned char>&, const std::vector<int>&, const std::vector<int>&, std::vector<unsigned char>&, std::vector<int>&, std::vector<int>&)’: /ascldap/users/dridzal/development/TEST/rol-trilinos/Trilinos/packages/stk/stk_util/stk_util/parallel/CommNeighbors.cpp:221:71: error: ‘MPI_Neighbor_alltoall’ was not declared in this scope                          (void*)recvCountsPtr, 1, MPI_INT, neighborComm);                                                                        ^ /ascldap/users/dridzal/development/TEST/rol-trilinos/Trilinos/packages/stk/stk_util/stk_util/parallel/CommNeighbors.cpp:236:78: error: ‘MPI_Neighbor_alltoallv’ was not declared in this scope        (void*)recvBufPtr, recvCountsPtr, recvDisplsPtr, MPI_BYTE, neighborComm);                                                                               ^`

## Possible Solution
I believe that MPI that is loaded for ROL's nightly testing (1.6.5??) no longer works for STK.  This needs to be updated ASAP.  I simply call

`$TRILINOS_DIR/cmake/load_sems_dev_env.sh "default"`

so the issue must be in load_sems_dev_env or the definition of "default".  I wonder why others are not seeing this issue.  Is the "default" abandoned or renamed?  On the other hand, pre-push test scripts seem to work just fine ... how are they different?

**Comment by prwolfe** [comment]
Is this a duplicate of #3390? See @mhoemmen's comment there about the age of this MPI version.

I will talk with the team.

**Comment by dridzal** [comment]
It's definitely related to #3390, but it's somewhat specific to fixing the load_sems_dev_env.sh script and/or the definition of "default" for this script.  The ATDM builds don't use this script -- do they?

**Comment by mhoemmen** [comment]
OpenMPI 1.6.5 is waaaaaaaay too old.  Sierra doesn't test with it, as far as I know.

**Comment by dridzal** [comment]
Agreed.  The bottom line is that Trilinos does **not** compile with the sems dev env defaults, due to the recent STK changes.  So we either change the defaults or retrofit STK with ancient MPI alternatives.  The change in the default/minimum MPI version would need to be communicated to the stakeholders.  An important question is if there are projects that track our master/develop branches but absolutely rely on OpenMPI 1.6.5 (have we heard from anyone?).  Their use case would no longer be supported.

**Comment by bartlettroscoe** [comment]
@dridzal, I will go ahead and make the default match the current CI build which is using OpenMPI 1.10.

**Comment by dridzal** [comment]
@jwillenbring @bartlettroscoe Is there a minimum version of MPI that Trilinos officially supports?

**Comment by dridzal** [comment]
Well, by allowing the STK failures and abandoning 1.6.5 testing, we are effectively setting the minimum MPI version ... to something higher than 1.6.5.  1.10.1?  1.8.7?

**Comment by mhoemmen** [comment]
Sierra had problems with OpenMPI 1.8.x, and decided to skip over it and require 1.10.y.

**Comment by alanw0** [comment]
Sorry I was out of town for a couple days and missed much of the discussion. I can easily add ifdefs to allow building with old mpi versions. The 'CommNeighbors' class which uses these missing MPI calls will then throw at run-time. Since it's a relatively new class, it is reasonable for any user of it to use a reasonably new MPI implementation. But then at least Trilinos will still build for existing users who aren't using this class and who have an old MPI installation. If ATDM builds are the issue, they aren't using STK anyway, so they shouldn't be impacted by a STK MPI version requirement.

**Comment by bartlettroscoe** [comment]
@alanw0 said:

> If ATDM builds are the issue, they aren't using STK anyway, so they shouldn't be impacted by a STK MPI version requirement.

FYI: The current ATDM Trilinos configuration that is modeled after the EMPIRE Trilinos configuration currently enables the following STK subpackages:

*  `Final set of enabled SE packages:  ... STKUtil STKSimd STKTopology STKMesh STKNGP STKIO STKMath STKTools STKExprEval STK ... 82`

as shown, for example, on CDash [here](https://testing-vm.sandia.gov/cdash/viewConfigure.php?buildid=3919447).

And the SPARC Trilinos configuration enables the STK subpackages:

* `Final set of enabled SE packages: ...STKUtil STKSearch STKTransfer STK ... 95`

as shown [here](https://software-sandbox.sandia.gov/jira/browse/TRIL-212?focusedCommentId=23177&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23177).

So that is a several STK subpackages being used by ATDM (at least as I currently understand things).

**Comment by alanw0** [comment]
@bartlettroscoe thanks for the info, that's certainly news to me.

**Comment by dridzal** [comment]
I need to sync the ROL repo with Trilinos develop today.  Let’s take another look tomorrow.


- - -

On September 11, 2018 at 7:21:39 AM MDT, Paul Wolfenbarger <notifications@github.com> wrote:

@dridzal<https://github.com/dridzal> - PR #3416<https://github.com/trilinos/Trilinos/pull/3416> should have solved this, but todays dashboard still shows an issue. Are you testing against develop or master?

**Comment by dridzal** [comment]
The sync won't be done until tomorrow, Sep. 12 (due to PR #3425), so we'll have to check the dashboard on Sep. 13.

**Comment by dridzal** [comment]
ROL's downward dependency tests are passing again.
