### ISSUE TITLE
Tpetra: Add option to specify arbitrary index offset for MatrixMarket I/O of sparse graphs & matrices

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#350]
@trilinos/tpetra Feature request by @crtrott , also desired by @tawiesn for Xpetra.

@crtrott would like Tpetra::CrsMatrix MatrixMarket input and output to let users specify an arbitrary starting offset for row and column indices.  Right now, it uses the index base, which is either 0 or 1.

**Comment by tawiesn** [comment]
What we do so far in Xpetra (see the IO routines in packages/xpetra/sup/Utils/Xpetra_IO.hpp) is to write/read the maps associated with a matrix in/from extra files. These maps can have arbitrary GIDs inside. The disadvantage is, that you have 5 files for storing one matrix: one matrix market file for each map (row,column,domain,range) and one with the actual matrix data. The map data also contain the matrix distribution over several MPI ranks.
Please note, the IO routines for blocked operators (with sparse large blocks) need some testing. See also issue #326 .
My experience tells me that (mis)using indexBase for a general offset is a very bad idea. IndexBase should be 0 or 1 (default = 0) and is meant only for the different indexing/counting schemes (i.e. 1 for the 1-index-based languages like fortran). That's why the Xpetra::StridedMap class has (beside the general striding data) an internal offset for GIDs which is independent of indexBase. Also the Xpetra::StridedMapFactory allows you to generate maps with that offset. But i also want to mention that i'd like to do some refactoring of the StridedMaps in Xpetra. However, there is currently no time for doing that.
