### ISSUE TITLE
Does Tpetra::MultiVector::get2dViewNonConst need a Kokkos::fence with CUDA, even if CUDA_LAUNCH_BLOCKING=1 ?

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#358]
I'm getting a UVM error when I run my code when I access editnonoverlap[j][i], however if I make this change it runs through it.

Now I have CUDA_LAUNCH_BLOCKING=1 when I run.
   ArrayView<const GO> owned_ids = gid_map->getNodeElementList();
   int which_id=0;
   ArrayRCP<ArrayRCP<GO> > editnonoverlap = non_overlap_mv->get2dViewNonConst();
+  Kokkos::fence();
   for(size_t i=0; i<non_overlap_mv->getLocalLength(); ++i){
     for(int j=0; j<numFields_; ++j){
       if(editnonoverlap[j][i]!=0){

@crtrott suggested
It might be that get2dView.. allocates memory. I have the suspicion that one needs an explicit fence after UVM allocations, and that CUDA_LAUNCH_BLOCKING only fences kernels. We do that for view allocations but I am not sure for the Tpetra MV thingies. If it is using the raw allocate function we might be in trouble.

@mhoemmen is this the case?

**Comment by bathmatt** [comment]
adding @rppawlo @eric-c-cyr

**Comment by mhoemmen** [comment]
Kokkos claims that all CudaUVMSpace allocations now fence by default.  Please refer to:

https://github.com/kokkos/kokkos/issues/230

**Comment by crtrott** [comment]
The Kokkos thing is a fence after a view allocation (i.e. after creating a view in UVMSpace). If you call the allocate function directly for raw memory it will not do that.

**Comment by mhoemmen** [comment]
@bathmatt Tpetra::MultiVector::get2dView* calls Kokkos::Compat::persistingView on the device View.  That returns a Teuchos::ArrayRCP which _views_ (does not copy) the _device_ View.

While this doesn't allocate, this is probably not what you want.  In particular, if you want to touch this data on host, you would need to fence first, to make sure that all device kernels are done.  

The correct thing to do in Tpetra::MultiVector would be for get2dView* to return the host version of the data.  This is what the get1dView* methods do.  In fact, this is what Chris Baker did originally; "view" methods that return ArrayRCP, actually are supposed to return a host "generalized view" of the data.  We don't implement the "generalized" part of that anymore (copying back to device on deallocation, if a nonconst view), because users are supposed to handle that manually via modify() and sync() calls.  However, those methods should always return host data.  You as the user are still responsible for calling modify() and sync() as needed, though.

**Comment by mhoemmen** [comment]
Just to make clear: My fix for this will make get2dView* sync to host, then return a host View.  get2dViewNonConst will also call modify() on host.  You are responsible for sync'ing back to device.

Please note that with CudaUVMSpace, Kokkos::DualView doesn't actually have a host View.  The "host View" is also in CudaUVMSpace.  Thus, you are still responsible for fencing if necessary.

**Comment by mhoemmen** [comment]
I shouldn't actually close this, given my remarks above.  Will have to wait for you folks to try it out.  It may still need fences, though.

**Comment by bathmatt** [comment]
Looks like this is resolved.  The fence is no longer needed.

**Comment by mhoemmen** [comment]
@crtrott and I just talked about this.  @bathmatt , do you create the MultiVector uninitialized (third bool argument false), then call get2dViewNonConst right away and attempt to fill on the host?  If so, that could be the reason why CUDA_LAUNCH_BLOCKING=1 didn't help.  The way Carter fixed it in Kokkos was to fence initialization, not allocations.

**Comment by mhoemmen** [comment]
@bathmatt My changes may have only fixed this "by accident," because get2dView(NonConst) now syncs the DualView.  That does a fence on both execution spaces when the memory spaces on host and device are the same.  This is indeed the case for CudaUVMSpace.  Thus, I added a fence for you.

Note that this may fix MultiVector, but it won't fix the underlying problem of needing fences around Kokkos::View allocations that don't initialize.

**Comment by bathmatt** [comment]
It is filled from an export, not sure when it was created.

  non_overlap_mv->doExport(*overlap_mv,e,Tpetra::ABSMAX);

....

  ArrayRCP<ArrayRCP<GO> > editnonoverlap = non_overlap_mv->get2dViewNonConst();

**Comment by mhoemmen** [comment]
@bathmatt MultiVector unpack uses a device kernel.  Touching UVM allocations first on device, then on host, without an intervening fence, may cause trouble.

**Comment by bathmatt** [comment]
I don't understand what you are saying, I understand that it uses a kernel,
I thought the design of the library was if we are using UVM and
CUDA_LAUNCH_BLOCKING we can use the memory anywhere we want whenever we
want.  Does the applicaiton need to do the fence?  How do we know which do
and don't?  I looked at the docs and it didn't say, (After this call you
must do a fence...)

**Comment by crtrott** [comment]
Mark, the situation you describe should be fine if CUDA_LAUNCH_BLOCKING is set, and no fence should be necessary. There are two things we need to check: (a) does it generally help to fence allocations of UVM memory in Kokkos itself, (b) is this simply a bug in the Cuda driver.

**Comment by bathmatt** [comment]
The latest change Mark made did make the symptom at least go away.  And, it
also goes away with bounds checking on.  Not sure what this all means.

**Comment by mhoemmen** [comment]
> Mark, the situation you describe should be fine if CUDA_LAUNCH_BLOCKING is set, and no fence should be necessary.

That makes sense.  doExport unpacks on the device, but it does so in a Kokkos::parallel_* kernel, so CUDA_LAUNCH_BLOCKING=1 will do the right thing (fence) there.  The issue was possibly that get2dView* was not sync'ing to host, so there might have been a missing fence somewhere.

Anyway, get2dView* semantics are correct now.  It syncs to host and returns a host View.  This will always be correct, even if we get rid of the UVM requirement and DualView actually views two different memory spaces.  Furthermore, get2dViewNonConst now calls modify on host, which correctly expresses users' intent.
