### ISSUE TITLE
STK: fix build warnings under CUDA

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#3619]
While working on #2674 on waterman, I'm seeing a lot of the following boost warnings during compilation of STK:
```
include/boost/mpl/for_each.hpp(78): warning: calling a __host__ function from a __host__ __device__ function is not allowed
```

@trilinos/stk @alanw0 @bartlettroscoe

**Comment by rppawlo** [comment]
@alanw0 - if it's any help we do have an mpl replacement that works both with and without kokkos. See Trilinos/packages/sacado/src/mpl

**Comment by mhoemmen** [comment]
@vbrunini

**Comment by jhux2** [comment]
> The stk team is working on these. Unfortunately it may be a non-trivial effort. I'll keep you posted.

@alanw0 Thank you for the update.

**Comment by bartlettroscoe** [comment]
Not to run anyone but is there any idea on the ETA on this?  I ask because this Issue shows up on our [ATDM Trilinos Defect issues query](https://github.com/trilinos/Trilinos/issues?utf8=%E2%9C%93&q=label%3AATDM+-label%3A%22Disabled+Tests%22+-label%3Aenhancement+-label%3AStalled+is%3Aopen+) and we are trying to keep that list down to 25 (or it goes to multiple pages).  If this might take a long time to address, we might add some "ATDM Priority" labels and and then filter this issue out of the higher-priority issues we are trying to stay on top of.

**Comment by khpierson** [comment]
We are actively working on the warnings this sprint. The most egregious warnings are coming from our use of boost. The team is considering removing boost from one of the stk products which would reduce complexity as well as remove the warnings. Unfortunately, this may take at least a sprint to sort out (~3 weeks). Note, we are seeing the same warnings with the Sierra builds.

**Comment by bartlettroscoe** [comment]
@khpierson, thanks for the update.

> The most egregious warnings are coming from our use of boost. 

We would have to check, by the ATDM Trilinos build of STK may not have any warnings coming from boost since those include directories may be passed into the build lines with `-isystem`.  But I would have to check to be sure.

@jhux2, what configuation settings are you using to generate these STK warnings?  Looking at that ATDM Trilinos builds for STK [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-10-16&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=subprojects&compare2=93&value2=STK), we don't seem to be seeing a lot of STK warnings.

**Comment by jhux2** [comment]
> what configuation settings are you using to generate these STK warnings?

@bartlettroscoe The same settings as in PR #3482.

**Comment by bartlettroscoe** [comment]
> > what configuation settings are you using to generate these STK warnings?
>
> @bartlettroscoe The same settings as in PR #3482.

@jhux2, I wonder why we are not seeing these warnings in our CDash builds of STK, for example on 'waterman' `cuda-9.2` build here:

* https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4059630

?

**Comment by alanw0** [comment]
The majority of the warnings we're working on are in the stk_topology module. Clicking on the link just provided by @bartlettroscoe I see that stk_topology is enabled, so I don't know why you aren't seeing the warnings. Must be a difference in compiler flags?

**Comment by bartlettroscoe** [comment]
@alanw0, @jhux2, @bathmatt,

Were these STK warnings fixed by the merge of PR #3765 last week?

**Comment by alanw0** [comment]
We'll have to take a look at them. We thought we had fixed nearly all of them, but yesterday did notice that they are showing up for certain builds. Long term we may need to stop using boost but hopefully we can quiet the warnings sooner than that.

**Comment by bartlettroscoe** [comment]
> We'll have to take a look at them. We thought we had fixed nearly all of them, but yesterday did notice that they are showing up for certain builds. Long term we may need to stop using boost but hopefully we can quiet the warnings sooner than that.

@alanw0, I heard from @ibaned that you can put in `#pragma`s in your code before you include boost header files and turn off these warnings.  Perhaps you can ask him how he does that?

**Comment by ibaned** [comment]
Unfortunately, the warning at the beginning of this comment thread I don't think can be silenced by GCC pragmas because it is within NVCC itself. For future reference, the pragma approach is:
```cpp
#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wshadow" //for example, pick the -W that applies to you
#endif 
void bad(int a) {
  int a;
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif 
```
we may be able to silence this warning with NVCC-specific compiler flags, but we'd need to do some research to figure out which one (if any) silences them. I the past what I've done for the `boost/mpl/for_each` warning was to edit the Boost headers to remove their CUDA-specific stuff. I know @dsunder who originally wrote much of STK has recently told me that Boost usage in STK could be entirely replaced with C++11 constructs today.

**Comment by rppawlo** [comment]
The mpl/for_each can also be replaced by the sacado version that has the correct kokkos markup for device. If you don't want to depend on sacado, we have discussed moving the mpl  implementation into a separate teuchos subpackage. We can do that also if you want.

**Comment by alanw0** [comment]
@ibaned Yes Dan did write stk_topology. We've been talking to Mark Hoemmen lately about ideas for doing something different there. If we can do anything like having a static array in a struct on the GPU, then it's easy and we can replace everything. Mark's working on that.
@rppawlo I did take a look at the sacado mpl. I think it would be tricky to make stk_topology depend on sacado… Also, we would prefer to not have anything like mpl if we can come up with a simpler solution. Thanks!

**Comment by mhoemmen** [comment]
The hope is to move away from Boost mpl vector stuff, towards constexpr stuff built into C++.

**Comment by bartlettroscoe** [comment]
FYI: I added this to the milestone "Initial cleanup of new ATDM builds of Trilinos" even though it impacts builds that have already been promoted to that "ATDM" CDash group for a long time.  But since these CUDA builds with these warnings are already promoted, we can't really add them to milestone "keep promoted ATDM Trilinos builds clean" since they were never clean.  I have added the "ATDM Nonblocker" label to make it clear that these warnings are not blocking ATDM apps from getting updated Trilinos versions.

**Comment by bartlettroscoe** [comment]
CC: @kddevin

@alanw0 and @micahahoward,

I just heard in Micah's email announcement that the updated Trilinos version has:

> 3)	An updated STK with no warnings for GPU builds

Is this true?  If so, can we close this issue?

**Comment by alanw0** [comment]
There are some puzzling things here... We did put in a stk update aimed at fixing gpu warnings, and I'm glad Micah saw benefit from it. But on the exawind project we are still seeing gpu warnings from stk_topology when building trilinos via cmake… So work still remains.

**Comment by rppawlo** [comment]
We are still seeing an issue in stk when building panzer on cuda as well. It is the same warning repeated probably a hundred times during our build:
```
/ascldap/users/projects/ppc64le-pwr9/boost/1.65.1/gcc/7.2.0/include/boost/mpl/for_each.hpp(78): warning: calling a __host__ function from a __host__ __device__ function is not allowed
```
If you get rid of this one, I think stk will be clean in our builds.

**Comment by khpierson** [comment]
I believe Alan and his team are working on removing boost mpl from the product which should also remove the warning. They will report on their progress at the toolkit review this Thursday. They have Skype access if that helps you attend to discuss this with the team. Let me know if I should foward the invite.

**Comment by bartlettroscoe** [comment]
FYI: Added label `Stalled` to get this off of our main list of active ATDM issues (as that list currently has 29 items and we try to keep it to 25 or under).

**Comment by alanw0** [comment]
Oh. Sorry, I lost track of this GitHub issue. The cuda warnings have been fixed. I don't see a "label" for fixed. Should I just close this issue?

**Comment by bartlettroscoe** [comment]
@alanw0 said:

> Oh. Sorry, I lost track of this GitHub issue. The cuda warnings have been fixed. I don't see a "label" for fixed. Should I just close this issue?

As shown in [this query](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2019-04-15&filtercount=3&showfilters=1&filtercombine=and&field1=subprojects&compare1=93&value1=STK&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=buildname&compare3=63&value3=cuda), if you drill down it shows warnings for only boost [here](https://testing.sandia.gov/cdash-dev-view/viewBuildError.php?type=1&onlydeltap&buildid=4888767).  We can make those go away by listing Boost as a direct dependency of STKBalance and using -isystem.

But since these are not STK warnings, I think this is safe to close.

Thanks!
