### ISSUE TITLE
MueLu_UnitTestsBlockedEpetra_MPI_1 failing on ATDM cee-rhel6-clang-opt-serial build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3640]
CC: @trilinos/muelu  , @srajama1  (Trilinos Linear Solvers Product Lead), @bartlettroscoe 
 
## Next Action Status

PR #4072 merged to 'develop' on 12/19/2018 for test `MueLu_UnitTestsBlockedEpetra_MPI_1` that was failing every day.  Test passed passed on 12/20/2018.

## Description

As shown in [this query](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-10-15&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-cee-rhel6-&field2=status&compare2=62&value2=passed) the tests:

* MueLu_UnitTestsBlockedEpetra_MPI_1

are failing in the builds:
* Trilinos-atdm-cee-rhel6-clang-opt-serial

failing due to seg fault
```
[ceerws1113:37972] *** Process received signal ***
[ceerws1113:37972] Signal: Segmentation fault (11)
[ceerws1113:37972] Signal code: Address not mapped (1)
[ceerws1113:37972] Failing at address: (nil)
```
## Steps to Reproduce

One should be able to reproduce this failure any CEE LAN RHEL6 SRN machine as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the CEE LAN RHEL6 SRN machines are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#cee-rhel6-environment

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cee-rhel6-clang-opt-serial

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON \
  $TRILINOS_DIR

$ make NP=16

$ ctest -j16
```

**Comment by srajama1** [comment]
@trilinos/muelu 
I think this is a new build, so slightly lower priority over other tests failing on currently green builds.

**Comment by bartlettroscoe** [comment]
> @trilinos/muelu
> I think this is a new build, so slightly lower priority over other tests failing on what used to be green builds.

@srajama1, this is not really a lower priority build just because it is in "Specialized" vs. "ATDM" CDash group.  As I tried to explain at the meeting last Friday, these 'cee-rhel6' builds support SPARC usage of Trilinos and SPARC otherwise has no automated testing to help protect changes of Trilinos breaking SPARC.  It is critical that we get these builds cleaned up so that we can start to protect SPARC.

**Comment by srajama1** [comment]
@bartlettroscoe I saw what you mentioned as well. However, with so many issues we just can't do all at once. If you think this is higher priority then builds in ATDM portion of CDash will get fixed slower. I didn't think that was good either.

**Comment by jhux2** [comment]
PR #4072 is intended to fix this.

**Comment by jhux2** [comment]
@bartlettroscoe @fryeguy52 This issue is fixed, as seen by this [query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-cee-rhel6-clang&field2=testname&compare2=65&value2=MueLu_UnitTestsBlockedEpetra&field3=buildstarttime&compare3=83&value3=2018-12-20T05%3A00%3A00%20UTC).

**Comment by bartlettroscoe** [comment]
FYI: PR #4072 merged to 'develop' on 12/19/2018 should fix this ...

@jhux2  said:

> @bartlettroscoe @fryeguy52 This issue is fixed, as seen by this query.

@jhux2, okay, as shown in [this query for just the test MueLu_UnitTestsBlockedEpetra_MPI_1 in the build Trilinos-atdm-cee-rhel6-clang-5.0.1-openmpi-1.10.2-serial-static-opt](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-cee-rhel6-clang&field2=testname&compare2=65&value2=MueLu_UnitTestsBlockedEpetra_MPI_1&field3=buildstarttime&compare3=83&value3=2018-12-01), the test `MueLu_UnitTestsBlockedEpetra_MPI_1` was failing every day (which suggests the test failure was not random) and the fact that it passed today after the merge of PR #4072 seems to suggest that this is fixed.

We usually want to see a couple of days of the test passing but given this test was failing every day and that is passed today, that should be good evidence that this issue is resolved.

Closing as complete!

**Comment by bartlettroscoe** [comment]
Closing as complete for real this time :-)
