### ISSUE TITLE
Seacas ParaviewCatalystIossAdapter CMakeLists file has the wrong comment type

### ISSUE THREAD

**Issue by jrood-nrel** [trilinos/Trilinos#3652]
https://github.com/trilinos/Trilinos/blob/develop/packages/seacas/libraries/ioss/src/visualization/ParaViewCatalystIossAdapter/parser/CMakeLists.txt has the wrong type of comments for CMake in it so it causes errors when trying to configure it.

**Comment by gsjaardema** [comment]
Will fix soon. Thanks for report

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gsjaardema** [comment]
Should be fixed with #3657

**Comment by jrood-nrel** [comment]
@gsjaardema Thanks, that solved some problems. However https://github.com/trilinos/Trilinos/blob/develop/packages/seacas/libraries/ioss/src/visualization/ParaViewCatalystIossAdapter/parser/catalystParser.l still has incorrect comment syntax.

Would it be possible to have whoever made this Catalyst adapter look everything over? If I remove those comments, I then get this error:

```
In file included from /....../Trilinos/packages/seacas/libraries/ioss/src/visualization/ParaViewCatalystIossAdapter/parser/catalystParser.l:6:0:
catalystParser.tab.hpp:328:38: error: unknown type name ‘parse_data’
 int catalystparse (yyscan_t scanner, parse_data& pd);
                                      ^~~~~~~~~~
make[2]: *** [parser/CMakeFiles/lexer.dir/lex.yy.c.o] Error 1
```

**Comment by tjotaha** [comment]
@jrood-nrel I believe that I have a fix for this issue that didn't make it into the Trilinos repository. There was some strange behaviour in newer versions of Bison that exposed C++ classes to the C compiler. The fix was to remove any reference to C++ in the parse interface functions. I've attached a new version of catalystParser.ypp that contains these changes. I've also attached a version of catalystParser.l that uses a C style comment for the NTESS legal header. Please try the files in your build. I used bison 3.04 and flex 2.5.37.

[catalystParser.tar.gz](https://github.com/trilinos/Trilinos/files/2554832/catalystParser.tar.gz)

**Comment by jrood-nrel** [comment]
@tjotaha Thanks for looking into this. It looks like those files succeed. Is it possible to get them into Trilinos? My goal with this issue was so I don't have to manage a `.tar.gz` file that has a working version of this adapter.

One more question. Is there an option to enable the Catalyst adapter when building and installing Trilinos itself? Or do I always need to build and install the adapter separately?

**Comment by tjotaha** [comment]
@jrood-nrel and @gsjaardema Right now you need to build the Catalyst adapter separately. I was talking with Jeff this morning about adding a third party library dependency in Seacas (included by Trilinos) on ParaView. This would allow for a selective build option in Trilinos to build the Catalyst adapter and ParaView as a third party library if desired. The drawback, of course, is that building ParaView on HPC machines can sometimes be major project.

@gsjaardema Should I open a pull request in Trilinos or Seacas to get the parser changes added?

**Comment by gsjaardema** [comment]
@tjotaha PR in seacas would be best.  I will then sync over to Trilinos

**Comment by tjotaha** [comment]
@jrood-nrel This change has made it into Seacas master and the Trilinos develop branch. I'm assuming that develop eventually gets rolled into Trilinos master

**Comment by jrood-nrel** [comment]
@tjotaha Cool, thanks! I'll try it out.

**Comment by jrood-nrel** [comment]
@tjotaha I tested the adapter in Nalu and I am getting errors for the 3 tests that involve Catalyst now. The errors can be seen here https://my.cdash.org/testDetails.php?test=43385442&build=1557672 . I'm using Paraview 5.4.1 for this. Anything I can do?

**Comment by jrood-nrel** [comment]
@tjotaha Actually it looks like Paraview 5.6.0 was finally just released, so it would be great to make sure this adapter will work with that now.

**Comment by tjotaha** [comment]
@jrood-nrel Okay. I consulted with Jeff. I've attached new versions of PhactoriDriver.py and phactori.py in phactori_files.zip. These should work with Paraview 5.4.1. Jeff is testing that they work with ParaView 5.6. Could you test these files with 5.4.1?
[phactori_files.zip](https://github.com/trilinos/Trilinos/files/2567145/phactori_files.zip)

**Comment by jrood-nrel** [comment]
@tjotaha I just tested Paraview 5.6.0 and got some errors. Here is the output: https://my.cdash.org/testDetails.php?test=43402892&build=1558132 . I can try to test 5.4.1 sometime, but probably after I am able to get 5.6.0 working.

**Comment by jeffmauldin** [comment]
Hello.  I just now tested those phactori.py and PhactoriDriver.py files against paraview 5.6 and they worked fine (yay!).  The problem you are seeing is due to some changes in the build/install structure after paraview 5.4.1.  You now (unfortunately) have to set a few additional environment variables (as follows) to tell the plugin where everything is--we'll be trying to take care of that if possible in the future but I'm afraid we might be stuck setting environment variables.

The environment variables you will have to set or alter are PYTHONPATH and LD_LIBRARY_PATH.
Assume you built paraview 5.6 using superbuild, and the path to the install directory inside the superbuild build is:
/mystuff/paraview_5_6_superbuild_build_dir/install

The environment variable setting commands (bash format, use "set" for csh) are:

>>>export PYTHONPATH=/mystuff/paraview_5_6_superbuild_build_dir/install/lib/python2.7/site-packages/vtkmodules:$PYTHONPATH

>>>export LD_LIBRARY_PATH=/mystuff/paraview_5_6_superbuild_build_dir/install/lib:$LD_LIBRARY_PATH

If you don't have a PYTHONPATH set before this, You'll need to leave off the ":$PYTHONPATH" part.

You'll still have to have the CATALYST_ADAPTER_INSTALL_DIR environment variable set to point to the plugin build as before.

This should work.  There is a small chance you'll have to add the .../install/lib/paraview-5.6 directory to the LD_LIBRARY_PATH as well, but probably not.  If something doesn't load you can go into .../install/lib and try a "find" command on the exact filename and see if it's in there and the directory needs to be added to LD_LIBRARY_PATH or PYTHONPATH.

My hope is to get rid of these environment variable requirements but we might be stuck with them for a while.  We may need to try to get these settings into supported module loads.

**Comment by jrood-nrel** [comment]
@jeffmauldin Great, thanks! I will work on accounting for these changes.

**Comment by jrood-nrel** [comment]
@tjotaha @jeffmauldin I have been testing Nalu which uses this Catalyst adapter successfully using the files given here and the latest Trilinos develop branch. If these are merged into Trilinos I will be able to close this issue.

**Comment by tjotaha** [comment]
@jrood-nrel I opened a pull request in Seacas to update the Phactori Python files that got merged into Seacas master. It should eventually make its way to Trilinos.

**Comment by jrood-nrel** [comment]
It looks like this made its way into Trilinos, so I think this issue is now resolved for me. Thanks for all the help everyone! (I don't remember if this is one of the projects where I'm not supposed to close my own issues, but feel free to close this anyone.)

**Comment by jrood-nrel** [comment]
This happened again https://github.com/trilinos/Trilinos/blob/develop/packages/seacas/libraries/ioss/src/visualization/ParaViewCatalystIossAdapter/CMakeLists.txt . Why do these comments get put into `CMakeLists.txt`?
