### ISSUE TITLE
Framework / TriBITS: download-cmake.py no longer points to a valid cmake

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#3700]
This guy: Trilinos/cmake/tribits/python_utils/download-cmake.py

Tries to download this: http://cmake.org/files/v2.8/cmake-3.10.0-Linux-i386.tar.gz

Which give ye ol' 404.

I discovered this in an initial setups of nightly testing on one of my machines.

@bartlettroscoe

**Comment by bartlettroscoe** [comment]
@csiefer2, sorry about that.  The script Trilinos/cmake/tribits/python_utils/download-cmake.py has not been used in years and therefore it is not surprising that it does not work anymore.  I talked with @jwillenbring and he agreed that this is not something that we want to support anymore.

There are other ways of getting an upgraded CMake that I can point you to.  For example, here is how the Tavis CI process for TriBITS gets CMake 3.10.3:

```
$ wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.3-Linux-x86_64.sh 
$ sudo mkdir /usr/local/cmake-3.10.3
$ sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local/cmake-3.10.3
$ export PATH=/usr/local/cmake-3.10.3/bin:$PATH
```

I have it on my todo list to update the script `install-cmake.py` to install updated versions of CMake.

**Comment by bartlettroscoe** [comment]
@csiefer2, we should take about how to set up automated builds of Trilinos without using the TriBITS Dashboard Driver system.  I did not use that for the ATDM Trilinos builds or the Trilinos CI build and I think that was a good decision.  Otherwise, I can see about ripping download-cmake.py out of TriBITS and out of the TriBITS Dashboard Driver tool if that is desirable.   (I just hate the TriBITS Dashboard Driver system too much to use it.  It was written by a contractor and has zero automated tests to protect it.  It is a real problem.)
