### ISSUE TITLE
Revise new developer checklist

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#372]
**CC:** @trilinos/framework 

**Description:**

The new developer checklist needs to be revised. In particular, to be up-to-date with the move to GitHub. Mentors can now decide when new students should get push access.

https://software.sandia.gov/trilinos/developer/sqp/checklists/newTrilinosDeveloper201508.txt

**Tasks:**
1. Initial update of checklist [Done]
2. Have set out for review and collect updates ... IN PROGRESS ...
3. Publish checklist to final location ...

**Comment by jwillenbring** [comment]
Checklist should be in google docs, and linked to from website.

**Comment by jwillenbring** [comment]
I have submitted a new draft version to the framework list for comment.

**Comment by bartlettroscoe** [comment]
Related emails.  It is important to archive this type of info.

----

From: Willenbring, James M 
Sent: Thursday, June 30, 2016 10:16 AM
To: Bartlett, Roscoe A; 'trilinos-framework@software. gov'
Subject: Re: Review request for new developer checklist

Ross,

Thanks for the updates. I updated a few things yesterday, but I agree that there are a large number of pages still out of date. I don’t think a final decision of github.io vs wiki has been made. It was only recently that I became aware that there are templates for sites available for github.io that are provided by github. This significantly lowers the overhead and maintenance of having a github.io site.

Jim

From: Roscoe Bartlett <rabartl@sandia.gov>
Date: Wednesday, June 29, 2016 at 11:03 PM
To: James Willenbring <jmwille@sandia.gov>, "'trilinos-framework@software. gov'" <trilinos-framework@software.sandia.gov>
Subject: RE: Review request for new developer checklist

Jim,
 
I reviewed the document and fixed a few small things (updated version is attached).  Just do a diff between the updated attached document and the copy you sent to see the differences.
 
Note that a lot of the material that is pointed to by this checklist is massively out of date.  Even a lot of the stuff copied to the Trilinos GitHub Wiki was significantly out of date (not sure how that happened).  I fixed several of these wiki pages but the pages on https://software.sandia.gov//trilinos/developer/ are painfully out of date  (and many just plain lie at this point).  These pages all need to be copied over to the Trilinos GitHub wiki and updated.
 
On that subject, have we decided to just keep going with the Trilinos GitHub Wiki for the Trilinos developers site or are we going to go with github.io sites written in Markdown?
 
Cheers,
 
-Ross
 
 
From: trilinos-framework-bounces@software.sandia.gov [mailto:trilinos-framework-bounces@software.sandia.gov] On Behalf Of Willenbring, James M
Sent: Wednesday, June 29, 2016 1:51 PM
To: 'trilinos-framework@software. gov'
Subject: [Trilinos-Framework] Review request for new developer checklist
 
All,
 
I have attached a draft version of an updated new Trilinos developer checklist. Please provide feedback if you would like to by COB tomorrow, June 30th. After that time, I plan to send the checklist through R&A, and make it accessible through the wiki. There is always time to update something like this as we have had a large number of revisions of this content already, but given the GitHub move, and other recent decisions, I wanted to get some feedback if anyone is interested.
 
Thanks
 
Jim

**Comment by jwillenbring** [comment]
After getting feedback on the new checklist, I put it through R&A. I then posted it in the Trilinos Google Doc folder. I am next going to work on a webpage for new developer notes that includes a link to the checklist.

**Comment by jwillenbring** [comment]
I put together a brief page on the topic of new developers. I would be interested to have any @trilinos/framework member or Trilinos developer review the page for possible corrections or additions.

https://github.com/trilinos/Trilinos/wiki/New-Trilinos-Developers

**Comment by bartlettroscoe** [comment]
I will review this.

**Comment by bartlettroscoe** [comment]
@jwillenbring, 

I reviewed the page:

* https://github.com/trilinos/Trilinos/wiki/New-Trilinos-Developers

It looks very good.  I made just a few small edits to improve understanding.  Please have a look at the diffs:

* https://github.com/trilinos/Trilinos/wiki/New-Trilinos-Developers/_compare/0666391bb163bde50134cce70e18d3d9802c9778...baafc4ef079d16444e470e96bcf46fe0f2f26f00?short_path=a34d418#diff-a34d418a3153b24958ade289d3da6012

I then reviewed the new developer checklist:

   https://docs.google.com/document/d/1QrnbxQVubimMGeQwmajr_zXtd-QLAksBbfsvTyMDGY4/edit

First a few overview questions:

1) What form is this document expected to be delivered?  Is this supposed to just be a raw text document?  Where is the final form of this document going to be provide?  I would say it should perhaps be an Trilinos GitHub wiki page that can have hyperlinks but then can be copied and pasted to an text document to fill it out.

2) How are these documents supposed to be collected and archived?  That is not mentioned anywhere on the checklist or the new developer wiki page.  I might suggest that they be archived in the Trilinos JIRA site as new Issue tickets, one for each new Trilinos developer.  That would make them secure and easy to search and find.  I think it is important to archive these (and any SQA auditor will appreciate and/or expect that).

I made a few small changes to the document to fix a few typos.  But otherwise, it looks every good.  You can see my changes by reviewing the history for the document.

I also reviewed some of the links provide in the document.

First, I see the changes you made to:

* https://github.com/trilinos/Trilinos/wiki/VC-%7C-Initial-Git-Setup

shown here:

* https://github.com/trilinos/Trilinos/wiki/VC-%7C-Initial-Git-Setup/_compare/9c32fbef16f3b8a9c7f6079bad146391fad51399...08aed85b828d9624eecacf95e080793c461a7596?short_path=684da76#diff-684da76f22106104c24ff3dc2549106f

Good improvements.

The big issue now is updating a lot of the info that is (indirectly) linked to from this document.  We need to add some stories for doing that at some point and get it done.

Otherwise, it looks good to deploy this to me.

Once this document is officially published, I think this Story is ready to close.
