### ISSUE TITLE
PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2 failing(timeout) in ATDM cuda builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3833]
CC: @trilinos/panzer , @mperego  (Trilinos Discretizations Product Lead), @bartlettroscoe 
 
## Description
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&field3=buildstarttime&compare3=84&value3=2018-11-08T00%3A00%3A00&field4=buildstarttime&compare4=83&value4=2018-11-07T00%3A00%3A00&field5=status&compare5=62&value5=Passed) the tests:
* PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2

are failing in the builds:
* Trilinos-atdm-white-ride-cuda-9.2-opt
* Trilinos-atdm-waterman-cuda-9.2-debug
* Trilinos-atdm-waterman-cuda-9.2-release-debug
* Trilinos-atdm-white-ride-cuda-9.2-opt
* Trilinos-atdm-white-ride-cuda-9.2-debug
* Trilinos-atdm-hansen-shiller-cuda-8.0-opt
* Trilinos-atdm-hansen-shiller-cuda-8.0-debug
* Trilinos-atdm-hansen-shiller-cuda-9.0-debug
* Trilinos-atdm-hansen-shiller-cuda-9.0-opt

Are these related to #2446 or #2751?

The timeouts started on 2018-10-31 for a few of the builds then others started in the following days. 
[shown here on waterman cuda-9.2-debug](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-debug&field2=testname&compare2=61&value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=2018-11-08T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2018-10-09T00%3A00%3A00)

The new commits that were pulled on 2018-11-03 that look like possible causes are:

```
e8051f3:  Panzer: update CurlLaplacian example
Author: Roger Pawlowski <rppawlo@sandia.gov>
Date:   Tue Oct 23 09:51:52 2018 -0600

de16afa:  Panzer: enable hierarchic parallelism in evaluators
Author: Roger Pawlowski <rppawlo@sandia.gov>
Date:   Thu Oct 18 15:18:43 2018 -0600
```
@rppawlo can you look and see if anything in these commits may have caused this test to start timing out?

## Current Status on CDash

The current status of these tests/builds for the current testing day can be found at:

* [current status on the test on all ATDM builds](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2)

## Steps to Reproduce

One should be able to reproduce this failure waterman as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md
More specifically, the commands given for the system waterman are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman
The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-waterman-cuda-9.2-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Panzer=ON \
  $TRILINOS_DIR

$ make NP=20

$ bsub -x -Is -n 20 ctest -j20
```

**Comment by rppawlo** [comment]
This will most likely be fixed when trilinos atdm builds on cuda enable the hierarchic dfad support in #3800 . The commits you mentioned changed panzer to using hierarchic dfad objects. But if this capability is not enabled in sacado at configure time, then the new code can be slower. AFter we see results from #3800 being pushed, we can revisit this ticket.

**Comment by rppawlo** [comment]
According to last night's build, everything is now passing. @fryeguy52 and @bartlettroscoe - can we close this?

**Comment by bartlettroscoe** [comment]
> According to last night's build, everything is now passing. @fryeguy52 and @bartlettroscoe - can we close this?

As shown in the below tables, for the past 3 days since the merge of PR #3800, this test is passing in all of the CUDA 'opt' builds or is disabled (missing) in the CUDA 'debug' builds.

Closing as  complete!

<h3>Tests with issue trackers Passed: twip=4</h3>
<table style="width:100%">

<tr>
<th>Site</th>
<th>Build Name</th>
<th>Test Name</th>
<th>Status</th>
<th>Details</th>
<th>Consec­utive Days Pass</th>
<th>Nopass last 30 Days</th>
<th>Pass last 30 Days</th>
<th>Tracker</th>
</tr>

<tr>
<td align="left">hansen</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-hansen-shiller-cuda-8.0-opt&amp;field2=site&amp;compare2=61&amp;value2=hansen&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2018-11-13T00:00:00&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2018-10-14T00:00:00">Trilinos-atdm-hansen-shiller-cuda-8.0-opt</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=59045338&amp;build=4164661">PanzerAdaptersSTK­_MixedPoissonExample-ConvTest-Hex-Order-2</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=59045338&amp;build=4164661">Passed</a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-hansen-shiller-cuda-8.0-opt&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=hansen&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">3</a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-hansen-shiller-cuda-8.0-opt&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=hansen&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">13</a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-hansen-shiller-cuda-8.0-opt&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=hansen&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">25</a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3833">#3833</a></td>
</tr>

<tr>
<td align="left">hansen</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-hansen-shiller-cuda-9.0-opt&amp;field2=site&amp;compare2=61&amp;value2=hansen&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2018-11-13T00:00:00&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2018-10-14T00:00:00">Trilinos-atdm-hansen-shiller-cuda-9.0-opt</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=59064304&amp;build=4165433">PanzerAdaptersSTK­_MixedPoissonExample-ConvTest-Hex-Order-2</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=59064304&amp;build=4165433">Passed</a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-hansen-shiller-cuda-9.0-opt&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=hansen&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">3</a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-hansen-shiller-cuda-9.0-opt&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=hansen&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">7</a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-hansen-shiller-cuda-9.0-opt&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=hansen&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">22</a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3833">#3833</a></td>
</tr>

<tr>
<td align="left">waterman</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-waterman-cuda-9.2-opt&amp;field2=site&amp;compare2=61&amp;value2=waterman&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2018-11-13T00:00:00&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2018-10-14T00:00:00">Trilinos-atdm-waterman-cuda-9.2-opt</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=59014223&amp;build=4163414">PanzerAdaptersSTK­_MixedPoissonExample-ConvTest-Hex-Order-2</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=59014223&amp;build=4163414">Passed</a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-waterman-cuda-9.2-opt&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=waterman&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">3</a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-waterman-cuda-9.2-opt&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=waterman&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">10</a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-waterman-cuda-9.2-opt&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=waterman&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">20</a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3833">#3833</a></td>
</tr>

<tr>
<td align="left">white</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-cuda-9.2-opt&amp;field2=site&amp;compare2=61&amp;value2=white&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2018-11-13T00:00:00&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2018-10-14T00:00:00">Trilinos-atdm-white-ride-cuda-9.2-opt</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=59039712&amp;build=4164832">PanzerAdaptersSTK­_MixedPoissonExample-ConvTest-Hex-Order-2</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=59039712&amp;build=4164832">Passed</a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-cuda-9.2-opt&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=white&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">3</a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-cuda-9.2-opt&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=white&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">7</a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-cuda-9.2-opt&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=white&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">22</a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3833">#3833</a></td>
</tr>

</table>

<h3>Tests with issue trackers Missing: twim=4</h3>
<table style="width:100%">

<tr>
<th>Site</th>
<th>Build Name</th>
<th>Test Name</th>
<th>Status</th>
<th>Details</th>
<th>Consec­utive Days Missing</th>
<th>Nopass last 30 Days</th>
<th>Pass last 30 Days</th>
<th>Tracker</th>
</tr>

<tr>
<td align="left">hansen</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-hansen-shiller-cuda-8.0-debug&amp;field2=site&amp;compare2=61&amp;value2=hansen&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2018-11-13T00:00:00&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2018-10-14T00:00:00">Trilinos-atdm-hansen-shiller-cuda-8.0-debug</a></td>
<td align="left">PanzerAdaptersSTK­_MixedPoissonExample-ConvTest-Hex-Order-2</td>
<td align="left">Missing</td>
<td align="left">Missing</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-hansen-shiller-cuda-8.0-debug&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=hansen&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">3</a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-hansen-shiller-cuda-8.0-debug&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=hansen&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">8</a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-hansen-shiller-cuda-8.0-debug&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=hansen&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">19</a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3833">#3833</a></td>
</tr>

<tr>
<td align="left">hansen</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-hansen-shiller-cuda-9.0-debug&amp;field2=site&amp;compare2=61&amp;value2=hansen&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2018-11-13T00:00:00&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2018-10-14T00:00:00">Trilinos-atdm-hansen-shiller-cuda-9.0-debug</a></td>
<td align="left">PanzerAdaptersSTK­_MixedPoissonExample-ConvTest-Hex-Order-2</td>
<td align="left">Missing</td>
<td align="left">Missing</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-hansen-shiller-cuda-9.0-debug&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=hansen&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">3</a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-hansen-shiller-cuda-9.0-debug&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=hansen&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">7</a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-hansen-shiller-cuda-9.0-debug&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=hansen&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">18</a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3833">#3833</a></td>
</tr>

<tr>
<td align="left">waterman</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-waterman-cuda-9.2-debug&amp;field2=site&amp;compare2=61&amp;value2=waterman&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2018-11-13T00:00:00&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2018-10-14T00:00:00">Trilinos-atdm-waterman-cuda-9.2-debug</a></td>
<td align="left">PanzerAdaptersSTK­_MixedPoissonExample-ConvTest-Hex-Order-2</td>
<td align="left">Missing</td>
<td align="left">Missing</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-waterman-cuda-9.2-debug&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=waterman&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">3</a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-waterman-cuda-9.2-debug&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=waterman&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">10</a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-waterman-cuda-9.2-debug&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=waterman&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">17</a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3833">#3833</a></td>
</tr>

<tr>
<td align="left">white</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-cuda-9.2-debug&amp;field2=site&amp;compare2=61&amp;value2=white&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2018-11-13T00:00:00&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2018-10-14T00:00:00">Trilinos-atdm-white-ride-cuda-9.2-debug</a></td>
<td align="left">PanzerAdaptersSTK­_MixedPoissonExample-ConvTest-Hex-Order-2</td>
<td align="left">Missing</td>
<td align="left">Missing</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-cuda-9.2-debug&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=white&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">3</a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-cuda-9.2-debug&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=white&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">7</a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-cuda-9.2-debug&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2&amp;field3=site&amp;compare3=61&amp;value3=white&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-13T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-14T00:00:00">18</a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3833">#3833</a></td>
</tr>

</table>

P.S. The above tables were copied and pasted from emails generated by the tool being developed in #2933.  In the (hopefully near) future, we will set up an automated job to update issues with info like this.
