### ISSUE TITLE
Framework: Add Wiki entry to describe useful email filters to help with github spam

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#3857]
@trilinos/framework 

A conversation came up today in our meeting with @bartlettroscoe about the email spam being sent out by github, especially since we started using the PR tester, which adds a few comments to every PR, which generates an email each time. We thought a wiki article for Trilinos would be useful to go over useful email filter settings to help cut down the spam.

Generally speaking, I think what many people do is they filter out all the spam unless there is an @mention to them or a team they're on... but I think many people don't do this. So an article we can point people to would be useful.

This relates to some old issues #1674 #668

**Comment by jmgate** [comment]
I've turned off email notifications entirely and I just look at my notifications page a few times a day.

**Comment by jhux2** [comment]
> I've turned off email notifications entirely and I just look at my notifications page a few times a day.

Ditto.  See [here](https://github.com/trilinos/Trilinos/wiki/GitHub-Notifications).

**Comment by csiefer2** [comment]
Or you could just turn off email notifications and not look at the notifications page...

**Comment by bartlettroscoe** [comment]
Just looking at your notifications page or ignoring all notifications and emails (hope that was a joke) is not good enough.  When someone @mentions you in a Trilinos GitHub issue it should result in you getting an unfiltered email to your main inbox and it should carry the same weight as if that person wrote a specific email to you.  If that is not that case, then we can't use GitHub or any other issue tracking system to replace email threads.

**Comment by jhux2** [comment]
> Just looking at your notifications page ... is not good enough.  When someone @mentions you in a Trilinos GitHub issue it should result in you getting an unfiltered email to your main inbox

@bartlettroscoe Frankly, I completely disagree with this statement.  How a developer chooses to see the notifications is up to him/her.   [And there are plenty of folks who don't constantly monitor their email anyway.]

>  and it should carry the same weight as if that person wrote a specific email to you

There's a lot less friction in @ mentioning someone than intentionally sending them an email.  So I think there are  caveats to even this.

**Comment by bartlettroscoe** [comment]
@jhux2 said:

> How a developer chooses to see the notifications is up to him/her. 

Here is the goal:

* If `@<someones-github-id` is included in an issue comment, they they will see that comment with just as much visibility as if they sent them a direct email.

Otherwise, in order to comment in a GitHub issue and get someone's attention, I need to:

1. Add the `@<someones-github-id>` in the issue comment.

2. Send an email to every person mentioned in that comment if they saw that comment.

That is what we are trying to avoid (because it is not good for either party, I will demonstrate).

> There's a lot less friction in @ mentioning someone than intentionally sending them an email. So I think there are caveats to even this.

We need to teach people that putting  `@<someones-github-id>` in a comment means the same thing as sending that person an email so if they don't want to send them an email, then just mention them by name and not with  `@<someones-github-id>`.  For example, if I send Si Hammond an email and I mention you in the email, if I don't want to bother you with an email, I just don't add you to the CC list, but I just say "Jonathan Hu said that ...".  Likewise, if I just want to mention you in a GitHub issue comment but not spam you with an email, I leave your @jhux2 out of the comment and just say "Jonathan H. ....".  But at lease with GitHub, if you want to find these mentions, you can by doing searches.  See, here are the issues where I was mentioned as "Ross" and not just @bartlettroscoe.

**Comment by jhux2** [comment]
@bartlettroscoe After someone is initially @ mentioned, then any further actions on the issue will appear in Notifications, regardless of of whether that person is explicitly mentioned.

**Comment by jmgate** [comment]
In case it's useful:  https://blog.github.com/2017-07-18-managing-large-numbers-of-github-notifications/

**Comment by bartlettroscoe** [comment]
@jhux2 said:

> After someone is initially @ mentioned, then any further actions on the issue will appear in Notifications, regardless of of whether that person is explicitly mentioned.

Yes, but if you create your own email filter then you will not see any of those other comments unless you are explicitly @ mentioned in a specific comments  That is the behavior that we want (that GitHub does not directly support but we can fix that using email filters on our end).

Make sense?

**Comment by bartlettroscoe** [comment]
@jmgate 

> In case it's useful: https://blog.github.com/2017-07-18-managing-large-numbers-of-github-notifications/

Excellent!  They tell you how to create your own robust email filters on your end at:

* https://help.github.com/articles/about-email-notifications/

They use gmail filters as an example.

Even GitHub understands the problem with GitHub notifications!

**Comment by jhux2** [comment]
We all know of folks who stopped receiving github emails due to bouncing from our corporate servers.  Afaik, there's no good way of knowing this without looking in the Notification center to see if there's stuff you've missed.   Dan S. mentioned that this does *not* happen with gmail, but of course, that's blocked.

**Comment by bartlettroscoe** [comment]
> We all know of folks who stopped receiving github emails due to bouncing from our corporate servers. Afaik, there's no good way of knowing this without looking in the Notification center to see if there's stuff you've missed. Dan S. mentioned that this does not happen with gmail, but of course, that's blocked.

If you contact GitHub and ask to have your github account unblocked and if you contact SNL IT and ask them stop bouncing GitHub emails, the problem will be fixed.  I have not not gotten a GitHub email in a year or more.  See:

* https://github.com/trilinos/Trilinos/wiki/GitHub-Notifications

@william76, actually, can we update that page:

* https://github.com/trilinos/Trilinos/wiki/GitHub-Notifications

to suggest writing email filters for `@<your-github-id>` so you see only those if you don't want to see anything else in Trilinos.
