### ISSUE TITLE
Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1 failing on ATDM builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3879]
CC: @trilinos/Intrepid2, @mperego (Trilinos Discretizations Product Lead), @bartlettroscoe, @fryeguy52 
 
## Next Action Status

PR #3882 that loosened tolerance merged on 11/15/2018 but this did not fix the failures in the `release-debug` builds on 'waterman'.  PR #3907 that loosed the tolerance some more was merged on 11/20/2018 to 'develop' that will also print out the numerical values to see why it is failing.  Next: Watch for results on 11/21 and beyond to see if these pass on all the builds (including the two `release-debug` builds on 'waterman').

## Description
As shown in [this query](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=65&value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1&field3=status&compare3=62&value3=Passed&field4=buildstarttime&compare4=84&value4=2018-11-14&field5=buildstarttime&compare5=83&value5=2018-11-13) the test:
* Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1

is failing in the builds:
* Trilinos-atdm-serrano-intel-opt-openmp
* Trilinos-atdm-waterman-cuda-9.2-release-debug
* Trilinos-atdm-waterman-gnu-release-debug-openmp
* Trilinos-atdm-hansen-shiller-intel-opt-serial

This looks like a new test added recently.

## Current Status on CDash

The current status of these tests/builds for the current testing day can be found [here](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=65&value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1&field3=status&compare3=62&value3=Passed)

## Steps to Reproduce

One should be able to reproduce this failure on waterman as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md
More specifically, the commands given for waterman are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman
The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-waterman-gnu-release-debug-openmp
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Intrepid2=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -n 20 ctest -j20
```

**Comment by mperego** [comment]
Thanks @fryeguy52. This new test are failing because of a tolerance that seems too tight on these machines. Should I wait a little bit too see if there are other failures so that I can address them all at once?

**Comment by fryeguy52** [comment]
@mperego yes I think that seems reasonable. Everything should be finished running by this afternoon.  I will add any new builds that I see to this issue.  Thanks for looking into this

**Comment by mperego** [comment]
@fryeguy52 I included a fix for this in PR #3882. Hope this fix the problem.

**Comment by bartlettroscoe** [comment]
@mperego, as shown [here](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-11-16&limit=0&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=65&value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1&field3=status&compare3=62&value3=Passed) there are still failures for the builds:

* Trilinos-atdm-waterman-cuda-9.2-release-debug
* Trilinos-atdm-waterman-gnu-release-debug-openmp

There may be more as more builds show up on the dashboard.

Looks like the fully optimized `opt` and full debug `debug` builds are fixed but the hybrid `release-debug` builds are not?

I am removing the label "in review".

**Comment by bartlettroscoe** [comment]
@mperego,

Is it okay to disable this test in the last 2 `release-debug` builds on 'waterman' where it is failing or is this something that you want to try to fix?  This test is passing in 29 other ATDM Trilinos builds including CUDA builds as shown [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&date=2018-11-18&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1).

Please let us know.  Otherwise, we will go ahead disable this tests in these two builds soon.

<h3>Tests with issue trackers Failed: twif=2 (2018-11-18)</h3>
<table style="width:100%" boarder="1">

<tr>
<th>Site</th>
<th>Build Name</th>
<th>Test Name</th>
<th>Status</th>
<th>Details</th>
<th>Consec&shy;utive Days Nopass</th>
<th>Nopass last 30 Days</th>
<th>Pass last 30 Days</th>
<th>Tracker</th>
</tr>

<tr>
<td align="left">waterman</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-waterman-gnu-release-debug-openmp&amp;field2=site&amp;compare2=61&amp;value2=waterman&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2018-11-19T00:00:00&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2018-10-20T00:00:00">Trilinos-atdm-waterman-gnu-release-debug-openmp</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=59516322&amp;build=4186339">Intrepid2_&shy;unit-test_&shy;Projection_&shy;Serial_&shy;Test_&shy;InterpolationProjection_&shy;HEX_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=59516322&amp;build=4186339"><font color="red">Failed</font></a></td>
<td align="left">Completed (Failed)</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-waterman-gnu-release-debug-openmp&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=waterman&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-19T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-20T00:00:00"><font color="red">6</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-waterman-gnu-release-debug-openmp&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=waterman&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-19T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-20T00:00:00"><font color="red">6</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-waterman-gnu-release-debug-openmp&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=waterman&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-19T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-20T00:00:00"><font color="green">0</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3879">#3879</a></td>
</tr>

<tr>
<td align="left">waterman</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-waterman-cuda-9.2-release-debug&amp;field2=site&amp;compare2=61&amp;value2=waterman&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2018-11-19T00:00:00&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2018-10-20T00:00:00">Trilinos-atdm-waterman-cuda-9.2-release-debug</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=59519176&amp;build=4186222">Intrepid2_­unit-test_­Projection_­Serial_­Test_­InterpolationProjection_­HEX_­MPI_­1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=59519176&amp;build=4186222"><font color="red">Failed</font></a></td>
<td align="left">Completed (Failed)</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-waterman-cuda-9.2-release-debug&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=waterman&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-19T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-20T00:00:00"><font color="red">6</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-waterman-cuda-9.2-release-debug&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=waterman&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-19T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-20T00:00:00"><font color="red">6</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-waterman-cuda-9.2-release-debug&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=waterman&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2018-11-19T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2018-10-20T00:00:00"><font color="green">0</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3879">#3879</a></td>
</tr>

</table>

**Comment by mperego** [comment]
@bartlettroscoe It's probably better to fix it, it's most likely an issues with tolerances being too tight. Do you know what's the machine epsilon for double precision on those machines?

**Comment by mperego** [comment]
@bartlettroscoe thanks. Let's hope that PR #3907 fixes it.

**Comment by mperego** [comment]
It seems that the issue has been resolved. Closing.
