### ISSUE TITLE
Tpetra::Experimental::BlockCrsMatrix: Use functor for GPU Kokkos-ization of getLocalDiagCopy

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#391]

**Comment by ambrad** [comment]
I think there are two compile-time issues in the Cuda build:

1. Trilinos/packages/kokkos/core/src/KokkosExp_View.hpp(1121): error: static assertion failed with "Incompatible View copy construction"
          detected during:
            instantiation of "Kokkos::Experimental::View<DataType, Properties...>::View(const Kokkos::Experimental::View<RT, RP...> &) [with DataType=double **, Properties=<Kokkos::LayoutRight, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos\
::CudaUVMSpace::memory_space>, Kokkos::MemoryTraits<1U>>, RT=double **, RP=<Kokkos::LayoutStride, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryTraits<1U>>]"
Trilinos/packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_def.hpp(151): here

Could just write auto D_out = ... instead of little_block_type D_out = ...

2. COPY calls are missing KOKKOS_INLINE_FUNCTION annotations.

**Comment by mhoemmen** [comment]
Ugh, sorry about that, I wanted to get the GCC 4.7.2 build fixed right away since that breaks so many customers' builds, so I pushed after doing GCC 4.7.2 and GCC 4.9.2 builds without testing CUDA.

**Comment by mhoemmen** [comment]
I'm on it right now.

**Comment by mhoemmen** [comment]
MPI_DEBUG_CUDA passed TpetraCore and Ifpack2 tests.  Now testing MPI_RELEASE_CUDA.
