### ISSUE TITLE
Teuchos: Stacked timer should build by default, & be enable-able via run-time option

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#3937]
@trilinos/teuchos @rppawlo @micahahoward

## Motivation and Context

  - Stacked timer does not build by default.  
  - @jjellio found that it would be super useful for ATDM work.
  - Combinatorial explosion of build options is bad.  See e.g., [Jed Brown's essay](https://arxiv.org/pdf/1407.2905.pdf).
  - Run-time option to enable this could still be off by default, for backwards compatibility.  (Users may depend on timer output format.)

## Related Issues

* Related to #2727

**Comment by rppawlo** [comment]
>     * Stacked timer does not build by default.
@mhoemmen - can you clarify this? If the Teuchos Comm subpackage is enabled, the StackedTimer is built. There is no explicit code to enable/disable in the CMakeLists.txt file as far as I can tell.

**Comment by mhoemmen** [comment]
There's a macro, `HAVE_TEUCHOS_ADD_TIME_MONITOR_TO_STACKED_TIMER`, that seems to control whether TimeMonitor does things with the stacked timer.  For example: https://github.com/trilinos/Trilinos/blob/804743a6d175cf36f3d9124f600dcacb75422691/packages/teuchos/comm/src/Teuchos_TimeMonitor.cpp#L261

**Comment by rppawlo** [comment]
That's for TimeMonitor to inject its data into StackedTimer. It's always on by default. The user has to disable it manually in their build. Here's the code in the top level teuchos cmake file:

```
TRIBITS_ADD_OPTION_AND_DEFINE(
  ${PACKAGE_NAME}_ENABLE_STACKED_TIMER_IN_TIME_MONITOR
  HAVE_TEUCHOS_ADD_TIME_MONITOR_TO_STACKED_TIMER
  "Adds timings from TimeMonitor to the StackedTimer object."
  ON
  )
```

There are corner cases where we do need to use that flag.

**Comment by mhoemmen** [comment]
@rppawlo OK, thanks!  Does this mean that TimeMonitor just plain always uses StackedTimer now by default?

**Comment by rppawlo** [comment]
Yes - by default TimeMonitor injects all its data into stacked timer. You can disable this at runtime with that configure flag. I can't remember why but at the time we needed it to be configure and not a runtime decision. I could revisit. The reason we allow it to be disabled is that StackedTimer is slightly less flexible that TimeMonitor. For a StackedTimer, the child timers have to be both started and stopped before its parent timer stops. You can't have overlapping timers. TimeMonitor does not have this restriction because it treats each timer independently. The disable exists to allow for overlapping timers. It turns out that in all cases of overlapping timers that we have seen, the reason was not intentional overlap but a reassignment of the timer in an RCP. The dtor of the old timer was called after the creation of the new timer in the RCP assignment. So we could remove that flag if we want to restrict TimeMonitor like StackedTimer.

**Comment by mhoemmen** [comment]
@jjellio could you please specify the desired requirements here?

**Comment by jjellio** [comment]
@mhoemmen I can't point to the specific reasons each App chooses to enable/disable. I know for people interested in MueLu setup, the Tpetra MMM timers cause problems.

My As for the performance tracking work I've done, I've standardized on using the flat Teuchos TimeMonitor report table.  If stacked timers could output a flat format, then it would integrate w/out any changes on my end.

e.g., Given stacked output like:
RegionA
--Timer1
--Timer2
--RegionA.1
----Timer1
----Timer2
 Then 'flat' output: (which requires the timer labels be prepended with some region information
RegionA_Timer1
RegionA-Timer2
RegionA_RegionB_Timer1
RegionA_RegionB_Timer2


It also isn't obvious how to incorporate the extra data that stacked timers expose (remainders)
A simple solution would be:
RegionA_remainder
RegionA.1_remainder

Stddev would fit naturally as another column in the table.

All of the above could be accomplished with some post processing (I think), I just have not had time to think about new things, since I have too many old things to do.
