### ISSUE TITLE
Trilinos:  what issues should be pinned?

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#4091]
Github now allows up to 3 issues to be "pinned" at the top of the issues tab.  Here are some ideas of what the Trilinos project might want to highlight:

- Getting started for new users.
- Usage statistics.
- News/updates/release info.

What are some other ideas?

**Comment by bartlettroscoe** [comment]
@jhux2, hard to pick 3 issues that should be globally displayed.  Not sure I want issues like this displayed on every query page.  Just takes way from vertical space and confuses things.  For example:

* https://github.com/trilinos/Trilinos/issues?utf8=%E2%9C%93&q=label%3AATDM+label%3Abug+-label%3A%22Disabled+Tests%22+-label%3AStalled+is%3Aopen+

**Comment by bartlettroscoe** [comment]
@trilinos/framework, @jwillenbring 

Do you have an opinion on this?  My opinion is that, for now, we should not use pinned issues because it does not make sense in the context of specific queries like the open ATDM Trilinos 'bug' issues:

* https://github.com/trilinos/Trilinos/issues?utf8=%E2%9C%93&q=label%3AATDM+label%3Abug+-label%3A%22Disabled+Tests%22+-label%3AStalled+is%3Aopen+

Seems like GitHub should only show pinned issues if it matches the Issues filter criteria (or allow you to hide pinned issues as a filter field or something).

**Comment by mhoemmen** [comment]
We could use the opening README to link to Wiki pages.  That might be a way to make sure new users find commonly wanted information.

**Comment by bartlettroscoe** [comment]
@trilinos/framework, @jhux2,

I will unpin this issue for now but this issue can stay open.  Then someone can work on this offline.

**Comment by bartlettroscoe** [comment]
I suspect that "pinned" issues are more useful in a smaller project with a more aligned set of development efforts.

**Comment by jwillenbring** [comment]
@jhux2 @mhoemmen @bartlettroscoe 

I agree with Mark about using the README to link to Wiki pages, and with Ross about it being hard to pick specific issues to highlight for the project. I would be interested in other specific ideas concerning how to pick specific issues to highlight. This is something we can keep an eye on, but I don't see right now how to get enough value to justify the lost screen real estate when searching for issues. I wish by default pinned issues showed up, but they were easy to hide or were hidden by default when a search doesn't match them.

I will close this for now, but if someone wants to continue the conversation, please reopen it. It just often happens that something like this gets left in a place like this and the issue stays open for (literally) years.
