### ISSUE TITLE
ShyLU/Tacho: Incorrectly gets disabled when all-caps version of RDC CMake option is used

### ISSUE THREAD

**Issue by theguruat12** [trilinos/Trilinos#4160]
@trilinos/framework @mhoemmen 

When we use the all-caps `KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE:BOOL=ON` instead of the CamelCase `Kokkos_ENABLE_Cuda_Relocatable_Device_Code:BOOL=ON`, Tacho doesn't get disabled, and CMake stops with the error that @bartlettroscoe set up in #2580.

## Possible Solution

Fix both `shylu/shylu_node/tacho/CMakeLists.txt` and `cmake/RepositoryDependenciesSetup.cmake` to use the following:
```
  SET(SHYLUNODE_ENABLE_RDC OFF)
  IF (DEFINED Kokkos_ENABLE_Cuda_Relocatable_Device_Code)
    IF (DEFINED KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE)
      IF ((Kokkos_ENABLE_Cuda_Relocatable_Device_Code AND (NOT KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE)) OR ((NOT Kokkos_ENABLE_Cuda_Relocatable_Device_Code) AND KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE))
        MESSAGE (FATAL_ERROR "You set two different capitalizations of the RDC flag with different values; this is a bad idea.")
      ENDIF ()
    ENDIF ()
  ENDIF ()
  IF (DEFINED Kokkos_ENABLE_Cuda_Relocatable_Device_Code AND Kokkos_ENABLE_Cuda_Relocatable_Device_Code)
    SET(SHYLUNODE_ENABLE_RDC ON)
  ENDIF()
  IF (DEFINED KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE AND KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE)
    SET(SHYLUNODE_ENABLE_RDC ON)
  ENDIF()

  IF (NOT SHYLUNODE_ENABLE_RDC)
    MESSAGE(WARNING "ShyLu/Tacho requires CUDA relocatable device code to be enabled if CUDA is enabled. Set: KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE=ON ")
  ENDIF()
```

## Related Issues
* Related to #2580

**Comment by kyungjoo-kim** [comment]
@theguruat12 I don't think that kokkos will accept the capitalized cmake option. 
@crtrott Does kokkos accept capitalized cmake options ? 

As the code follows kokkos cmake option, unless kokkos supports capitalized cmake options, changes only in the tacho is meaningless.

**Comment by mhoemmen** [comment]
@jhux2 The comments in CMakeCache.txt suggest that the CamelCase versions of options are meant only for backwards compatibility.  It looks like the intent is for Kokkos and thus Trilinos to support both capitalizations now, and possibly at some point to deprecate and remove the CamelCase versions.

In any case, I suggested the above solution for Sam.  Sierra needs this to work so that they can support CUDA builds with Trilinos, using Trilinos' CMake build system (rather than bjam).  The fix is just a drop-in replacement in two different places.  I also propose the following:

  1. Add a CMake option to `shylu_node` that says whether RDC is enabled.  (It would use the above logic for setting `SHYLUNODE_ENABLE_RDC`.)
  2. That way, Tacho could just test `shylu_node`'s CMake option, rather than duplicating the above logic.

**Comment by kyungjoo-kim** [comment]
@mhoemmen A problem is that ``KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE:BOOL=ON`` does not really turn on the RDC feature in Kokkos. Without Kokkos enabling RDC, Tacho cannot be used on GPUs. 

Tacho is fully dependent on Kokkos tasking. Testing the RDC option in Tacho is not meaningful as it must confirm that kokkos RDC option is indeed ON if the code works on GPUs. 

I am not sure why this breaks Trilinos build. Tacho is almost header only code (it has some wrapper object files for blas and lapack). With RDC OFF, the cmake will show warning message only. It should not stop configuration.

**Comment by kyungjoo-kim** [comment]
@theguruat12 You are right. Kokkos define capitalized cmake options and backward compatible camelcase options. This means if you define ``KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE:BOOL=ON``, it also defines ``Kokkos_ENABLE_Cuda_Relocatable_Device_Code:BOOL=ON``. So, Tacho is definitely not disabled and this is a correct behavior.

**Comment by kyungjoo-kim** [comment]
@theguruat12 I read your first comment again. Do you want to disable Tacho with RDC ON ? or do you want to disable Tacho with RDC OFF ? If you want to disable Tacho with RDC ON, you should disable Tacho explicitly. With RDC OFF, Tacho just create a dummy library if it is not explicitly disabled.

**Comment by mhoemmen** [comment]
@kyungjoo-kim What we want is that if RDC is OFF, Tacho gets disabled. 

The error message we get is the `FATAL_ERROR` in `cmake/RepositoryDependenciesSetup.cmake`.

**Comment by bartlettroscoe** [comment]
The problem seems to be that if someone explicitly enables Tacho then the existing logic will error out instead of overriding that enable with a disable.  I am fine with changing the CMake code to issue a warning when Tacho is enabled but RDC is not enabled and have it force the disable of Tacho (after printing a "NOTE" about the disable).  That is actually the way I prefer in general, to have disables trump enables.

**Comment by kyungjoo-kim** [comment]
@mhoemmen Can you give more concrete message about how dependencies went wrong  from which package ? The error does not seem to happen in Tacho's cmake file. The problem looks like simply Tacho is not disabled in your default cmake setup. If you know you don't need Tacho, why don't you just disable the package explicitly ?

**Comment by srajama1** [comment]
I believe Tacho is enabled so it could be used with SD/SM. However, I don't know the reason for RDC is OFF, but those two are not compatible. 

Aside from this issue, @crtrott Any chance we will get rid of RDC requirements for Kokkos tasking ?

**Comment by theguruat12** [comment]
Error message:
{{{
Processing Project, Repository, and Package dependency files and building internal dependencies graph ...

CMake Error at cmake/RepositoryDependenciesSetup.cmake:11 (message):
  ERROR: Trilinos_ENABLE_ShyLU_NodeTacho=ON but TPL_ENABLE_CUDA='ON' AND
  Kokkos_ENABLE_Cuda_Relocatable_Device_Code='' which is not allowed!
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:967 (INCLUDE)
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1536 (TRIBITS_READ_ALL_PACKAGE_DEPENDENCIES)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:160 (TRIBITS_READ_PACKAGES_PROCESS_DEPENDENCIES_WRITE_XML)
  cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:90 (TRIBITS_PROJECT)


-- Configuring incomplete, errors occurred!
}}}

Note that I explicitly turned ON ShyLU_NodeTacho and passed: -DKOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE:BOOL=ON

**Comment by theguruat12** [comment]
@kyungjoo-kim I think that is backwards.  We see the error if we pass the all-caps version (-DKOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE), but if we pass CamelCase (-DKokkos_ENABLE_Relocatable_Device_Code), the error is not displayed and Tacho is turned on correctly.  Mark's comment (immediately previous to this one) is correct; both are recognized by Kokkos, but only one is properly recognized by the shylu_node/tacho stuff.

**Comment by kyungjoo-kim** [comment]
@theguruat12 Okay. Finally I understand your problem. Thank you for being patient with me. So, the problem is Kokkos supports both cmake options and its backward compatibility (if either of all caps or camel case is defined, the other is defined). However, ``RepositoryDependenciesSetup.cmake`` is processed before kokkos cmake is processed; thus, it can only see either of them whatever is already defined by a user. 

@bartlettroscoe I think that it is okay to change the ``Kokkos_ENABLE_Relocatable_Device_Code`` with all CAPS  in the ``make/RepositoryDependenciesSetup.cmake``. 

1. Trilinos uses the PacakageName_ENABLE_BLAH_BLAH_WITH_ALLCAPS. Following the same rule, it should be ``Kokkos_ENABLE_RELOCATABLE_DEVICE_CODE`` instead of ``KOKKOS_RELOCATABLE_DEVICE_CODE``.   
2. To make Kokkos as a part of Trilinos, Kokkos should also follows the Trilinos cmake rules. @crtrott Can we do this ?
