### ISSUE TITLE
Many (50-80) Panzer tests failing on all ATDM cuda builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#4174]
CC: @trilinos/panzer, @mperego (Trilinos Discretizations Product Lead), @bartlettroscoe, @fryeguy52
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm&field2=buildname&compare2=63&value2=cuda&field3=buildstarttime&compare3=83&value3=2019-01-11&field4=buildstarttime&compare4=84&value4=2019-01-12) about half of the Panzer tests started failing on 2019-01-11 on all the cuda 9.2 ATDM builds the failures are too numerous to list here but the largest groups are:

* `PanzerAdaptersSTK_*` 
* ` PanzerDiscFE_*`
* ` PanzerDofMgr_*`
* ` PanzerMiniEM_MiniEM-BlockPrec_*`

the affected builds are:
* Trilinos-atdm-waterman-cuda-9.2-debug 
* Trilinos-atdm-waterman-cuda-9.2-opt 
* Trilinos-atdm-waterman-cuda-9.2-release-debug 
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug 
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release 
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug 

the tests are failing with segmentation faults
```
0. tFilteredUGI_equivalence_test_UnitTest ... --------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 0 on node white22 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

@rppawlo there were a couple new commits that touched panzer files that you made yesterday. Can you see if these are what caused the new failures?
```
cf5e5a3:  Panzer: hack for gcc 4.8 compiler
1333649:  Panzer: fix all shadow warnings
```

## Current Status of these builds on CDash

The status of these builds for the current testing day can be found at:

https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm&field2=buildname&compare2=63&value2=cuda

## Steps to Reproduce

One should be able to reproduce this failure on ride or white as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for ride or white are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Panzer=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by bartlettroscoe** [comment]
CC: @mperego, @fryeguy52, @trilinos/framework 

@rppawlo, with so many test failures in every CUDA build, I have labeled this with [`ATDM Sev: Critical`](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/ATDM-Specific+Trilinos+GitHub+Labels#ATDM-SpecificTrilinosGitHubLabels-LabelsforSeverity/Criticality) since this will basically blind our ability to detect new test failures (and we don't want to be adding hundreds of failing tests to our `TrilinosATDMStauts/*.csv` files).

All things considered, I think it would be best to detect the breaking commit (or merge commit) and back it out since the ECP meeting is next week. The only problem is that there are many commits and PRs pushed to 'develop' yesterday and pulled in today shown [here](https://testing.sandia.gov/cdash-dev-view/viewNotes.php?buildid=4400616#!#note2) that may have broken these Panzer tests.  Can you see which one might have broken this?  Otherwise, we will need to do a short manual bisection study and try to figure out which PR branch merge broke all of this.  That will take a few hours of compute time likely.

@trilinos/framework, 

FYI: Any CUDA build on any platform looks like it would have caught this.  We could really use that CUDA PR build (see #2464).

Any CUDA build

**Comment by rppawlo** [comment]
I'm working on it now. Not sure how warning cleanup could have broken anything but...

**Comment by rppawlo** [comment]
PR with fix will be up in a minute.

**Comment by rppawlo** [comment]
Fix for this was merged this morning.

**Comment by mperego** [comment]
@bartlettroscoe can we close this issue?

**Comment by fryeguy52** [comment]
Closing this issue. Shown [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm&field2=buildname&compare2=63&value2=cuda) the tests are passing again.  Thanks @rppawlo
