### ISSUE TITLE
Xpetra: Is there an equivalent to Epetra's ReplaceDiagonalValues()?

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#4202]
@trilinos/xpetra 
@lucbv 

In Epetra, the diagonal of a matrix can be replaced by `Epetra_CrsMatrix::ReplaceDiagonalValues()`. Is there an equivalent routine in Xpetra?

I know how to extract a copy of the diagonal via `Xpetra::Matrix::getLocalDiagCopy()`, but I couldn't find a mechanism to specifically replace the diagonal. 

I can think of a workaround using `Xpetra::Matrix::replaceLocalValues()` with proper row and col addressing, i.e. col being an array with just a single entry, namely the row index.

## Related Issues
* Part of #4084

**Comment by lucbv** [comment]
@mayrmt, looking at the documentation for `Tpetra::CrsMatrix`, it looks like you can get a copy of the diagonal but I did not find a method to set the diagonal. This would explain why the functionality is not offered in `Xpetra`.
Of course we could write a wrapper in `Xpetra` that implements it for the `Tpetra` case but I am not sure that it makes too much sense to do so.
@csiefer2 do you have an opinion on this?

**Comment by csiefer2** [comment]
It would make more sense to just implement it in Tpetra and then wrap  both in Xpetra.

@mayrmt How soon do you need this?

**Comment by mhoemmen** [comment]
Y'all are gonna do this in the slowest way possible, I'm sure.  Check out how I wrote the "get copy of diagonal using known offsets" code in Tpetra.  It's not a hard kernel to write.

**Comment by jhux2** [comment]
:turtle: 

> Y'all are gonna do this in the slowest way possible, I'm sure. Check out how I wrote the "get copy of diagonal using known offsets" code in Tpetra. It's not a hard kernel to write.

:turtle:

**Comment by csiefer2** [comment]
If you want to take a crack at it, @mhoemmen or I could certainly check it over.

**Comment by mhoemmen** [comment]
Please make it a free function, not a member function :-)

**Comment by mayrmt** [comment]
@mhoemmen Do you mean to write a function `Tpetra::replaceCrsMatrixLocalDiagonal(matrix, diagVector)` that takes the matrix `matrix` and a vector `diagVector` with the new diagonal values as input argument and internally does some `replaceLocalValues()` to actually set the values? Could you point me to an example, that I can get some inspiration from?

Finally, just for my education: Why should this be a free function, not a member function?

**Comment by mhoemmen** [comment]
@mayrmt wrote:
> Why should this be a free function, not a member function?

See Scott Meyers, "Effective C++", 3rd edition, Item 23: "Prefer non-member non-friend functions to member functions."

1. If you _can_ implement this using the public interface of CrsMatrix, then you _should_.  Otherwise, you're violating encapsulation by introducing yet another pass-through.

2. Less code in `Tpetra_CrsMatrix_def.hpp` means shorter build times.

3. Separate implementation means separate testing, in a separate test file (please create a new .cpp file for testing this; don't just stuff it into an existing .cpp file).  It's more useful to see on the Dashboard that a new function "replace the local diagonal" failed, than just to get it all lumped into "CrsMatrix unit tests."

**Comment by mhoemmen** [comment]
@mayrmt See also http://www.drdobbs.com/cpp/how-non-member-functions-improve-encapsu/184401197 .

**Comment by mayrmt** [comment]
@mhoemmen I looked at `tpetra/core/src/Tpetra_Details_getDiagCopyWithoutOffsets_*.hpp` and deduced the following steps:
- Add files `tpetra/core/src/Tpetra_Details_replaceDiagWithoutOffsets_*.hpp` that contain the actual implementation as a free function.
- Add member function `replaceDiag(const Vector<>& newDiagValues)` to `Tpetra::CrsMatrix` that internally calls the free function "details" implementation (similar to [`getLocalDiagCopy()`](https://github.com/trilinos/Trilinos/blob/28ff0dfc58c87f8444a582f707811ccbba09166d/packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp#L2977)

Are these deductions correct or did I misunderstand the concept?

**Comment by mhoemmen** [comment]
@mayrmt If the function is called `replaceDiag`, I would call the header file "replaceDiag" to match.  It would make sense for replaceDiag at some point to get an overload that takes the offsets, in which case it wouldn't make sense to put the function in a header file with "without offsets" in its name.  Otherwise, this is a good plan; thanks!

**Comment by mayrmt** [comment]
@mhoemmen I've created (and pushed) and empty framework, where the free function `Tpetra::replaceDiagonalCrsMatrix(matrix, newDiagonal)` is supposed to replace the diagonal entries of `matrix` with those given in `newDiagonal`. I also added a test `tpetra/core/test/CrsMatrix/CrsMatrix_ReplaceDiagonal.cpp` that invokes that function (though the test doesn't perform an actual test, yet.).

Looking at `getDiagCopyWithoutOffsets()` as you suggested, implies that I need a `struct CrsMatrixGetDiagCopyFunctor` where the `oeprator()` implements the actual replacement of the diagonal entries. And then, I need a `Kokkos::parallel_for()` using that functor. 

I have two questions now:
- Is anything I wrote above correct? 
- Where do I have to put the `Kokkos::parallel_for()`? I guess it's going right into the free function `Tpetra::replaceDiagonalCrsMatrix(matrix, newDiagonal)`?

**Comment by mhoemmen** [comment]
Hi there!  I'm in meetings all week and may need to delay GitHub posts until night.

@mayrmt wrote:
> I've created (and pushed) an empty framework,

What commit is this?  I'm not seeing it in develop.  I'm glad :-) because I wouldn't want a function that says it does something but doesn't actually do anything in develop quite just yet.

The other things you said are pretty close.  I would say, if you're not sure how to write a thread-parallel implementation just yet, you could start with a sequential implementation that just uses `replaceGlobalValues` etc.  (Be sure to issue `execution_space::fence()` before the code, since it works on UVM data and since some device kernel may be running before your code runs on host.)  Write that implementation, write the test, and get the test to pass.  If you have time to worry about threads after that point, go for it.

**Comment by mayrmt** [comment]
@mhoemmen I started a WIP pull request #4297 where I added a test and did a first implementation using `Tpetra::CrsMatrix::replaceLocalValues()`. I'm looking forward to get some feedback on that. 

I will have to wrap this into Xpetra later. Right now, I'm postponing that until this is acceptable from the Tpetra point of view.

**Comment by mhoemmen** [comment]
@mayrmt Thanks for working on this!  I made some comments on the PR.

**Comment by lucbv** [comment]
@mayrmt PR #4297 was merged, there is still some work to be done for the integration in `Xpetra` but I should have a PR covering it soon enough, so no need to worry about it.

**Comment by mayrmt** [comment]
@lucbv Thanks! Let me know if I can be of any assistance.

**Comment by lucbv** [comment]
@mayrmt with PR #4419 merged we can now close this issue. But let me know if you have any issues using the Xpetra code.
