### ISSUE TITLE
Tpetra: ImportExport2_UnitTest & FixedHashTable tests fail in debug mode; Teuchos::ArrayView ctor issue

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#4225]
@trilinos/tpetra @trilinos/teuchos @bartlettroscoe @ibaned 

Some Tpetra tests have been failing in debug mode.  For example, FixedHashTable's test fails.  `Teuchos::ArrayView`'s constructor that takes a pointer and a length throws, because the length is zero but the pointer is nonnull.  When I stop `ArrayView`'s constructor from throwing, the test passes just fine.

This is a bit of a problem, because `Kokkos::View` permits a View with a zero length to have a nonnull pointer.  I can see the value of the test, but it is a bit troublesome to have to do an extra test to convert from `Kokkos::View` to `Teuchos::ArrayView`.  Furthermore, `std::vector` behaves just like `Kokkos::View`, in that `.data()` need not return `nullptr` if the vector's length is zero.

My plan was to go through Tpetra, find all instances of that constructor, and fix them.  I plan to modify the relevant conversion functions in the TeuchosKokkosCompat subpackage, and only use those.  However, it seems like this could lead to trouble when attempting obvious conversions from `std::vector` to `Teuchos::ArrayView`.  Should we consider removing this debug test?

See e.g., https://github.com/trilinos/Trilinos/issues/184 .

## Expectations

Conversions from zero-length `std::vector` or `Kokkos::View` to `Teuchos::ArrayView` should not require an extra branch just to make the pointer null if the length is zero.

**Comment by bartlettroscoe** [comment]
@mhoemmen, I believe there is a good bit of code in Trilinos that relies on `Teuchos::ArrayView::getRawPtr()` (and `Teuchos::ArrayView::get()`) to return `nullptr` when the size is 0.

Can't we just write a conversion function (or update an existing conversion function) that converts between `Kokkos::View` to `Teuchos::ArrayView` to set the pointer to `nullptr` when passing in a zero size?  I think that is what @crtrott and myself agreed to several months ago.

@mhoemmen, can we talk for a minute about this?

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> Can't we just write a conversion function (or update an existing conversion function) that converts between `Kokkos::View` to `Teuchos::ArrayView` to set the pointer to `nullptr` when passing in a zero size? I think that is what @crtrott and myself agreed to several months ago.

I'm doing this right now.  The problem is that developers have to remember to use this function.  It's yet another thing they have to remember, and it's hard enough already to keep Trilinos developers from going bonkers with all the things they need to remember.

> @mhoemmen, can we talk for a minute about this?

Sure, just call me :-)

**Comment by mhoemmen** [comment]
@kddevin @trilinos/tpetra `Tpetra_ImportExport2_UnitTests` was failing for the same reason, namely `Teuchos::ArrayView`'s constructor throwing if it gets a nonnull pointer and a zero length.

@bartlettroscoe points out that some Trilinos code may rely on `Teuchos::ArrayView` to have a null pointer if its length is zero.  However, that is a different issue.  ArrayView's constructor could perfectly well set the pointer to null if the length is zero, in order to maintain the invariant on which downstream Trilinos code depends.

Here is an example of code that could break, given ArrayView's current behavior:
```c++
std::vector<int> vec;
if (some_condition) {
  vec.resize (nonzero_size);
}
// DOOM LURKS HERE IN A DEBUG BUILD
Teuchos::ArrayView<int> av (vec.data (), vec.size ());
```

**Comment by mhoemmen** [comment]
I added a PR to work around ArrayView's debug checking in a way that makes Tpetra's tests pass for me:

https://github.com/trilinos/Trilinos/pull/4233

It's likely that downstream code will still create `Teuchos::ArrayView` from `std::vector` or `Kokkos::View`, though.

**Comment by mhoemmen** [comment]
@bartlettroscoe See #4234.  My plan is to fix ArrayView's constructor so that it sets its pointer to null if the input pointer is nonnull but the input length is zero.  If you have any objections, please feel free to voice them at #4234.  Thanks!

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe See #4234. My plan is to fix ArrayView's constructor so that it sets its pointer to null if the input pointer is nonnull but the input length is zero. If you have any objections, please feel free to voice them at #4234. Thanks!

@mhoemmen, I guess I am not apposed to changing the pre-conditions and post-conditions for `Teuchos::ArrayView::ArrayView(T* ptr, Ordinal size)` to allow `ptr!=nullptr` when `size==0` and then to discard `ptr` in this case.  Technically that use case was invalid so if we make it valid, I don't think we can break backward compatibility (unless some code relies on the exception to be thrown but it only does so in a debug-mode build so that would be stupid code).

We would just need to update the unit tests to cover this case.  (Hopefully existing unit tests would fail if `Teuchos::ArrayView::ArrayView(T* ptr, Ordinal size)` where changed but no tests were updated.)

But we also need conversion functions (explicit or implicit) to and from `Teuchos::ArrayView` and `Kokkos::View`.   (That is the Teuchos way.  See "Figure 3. Conversions between array memory management types" in [Teuchos Memory Management Classes](https://trilinos.org/docs/dev/packages/teuchos/doc/html/TeuchosMemoryManagementSAND.pdf).)

Would there be any harm in just allowing implicit conversions from `Kokkos::View` to `Teuchos::ArrayView`?  We currently allow implicit conversions from `std::vector` and `Teuchos::ArrayRCP` to `Teuchos::ArrayView`.

**Comment by mhoemmen** [comment]
@kddevin @trilinos/tpetra 

I just merged a Tpetra work-around into develop.
