### ISSUE TITLE
Teuchos::ArrayView constructor should set its pointer to null if input pointer is nonnull but length is zero

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#4234]
@trilinos/teuchos @trilinos/tpetra @kddevin @jhux2 @csiefer2 

See #4225 discussion.

## Expectations

It should be trivial to create a Teuchos::ArrayView from an std::vector or (host) Kokkos::View.  Users should not have to test whether the pointer is null if the length is zero.

## Related Issues

* Related to #4225

**Comment by bartlettroscoe** [comment]
@mhoemmen, I guess I am not apposed to changing the pre-conditions and post-conditions for `Teuchos::ArrayView::ArrayView(T* ptr, Ordinal size)` to allow `ptr!=nullptr` when `size==0` and then to discard `ptr` in this case.  Technically that use case was invalid so if we make it valid, I don't think we can break backward compatibility (unless some code relies on the exception to be thrown but it only does so in a debug-mode build so that would be stupid code).

We would just need to update the unit tests to cover this case.  (Hopefully existing unit tests would fail if `Teuchos::ArrayView::ArrayView(T* ptr, Ordinal size)` where changed but no tests were updated.)

But we also need conversion functions (explicit or implicit) to and from `Teuchos::ArrayView` and `Kokkos::View`.   (That is the Teuchos way.  See "Figure 3. Conversions between array memory management types" in [Teuchos Memory Management Classes](https://trilinos.org/docs/dev/packages/teuchos/doc/html/TeuchosMemoryManagementSAND.pdf).)

Would there be any harm in just allowing implicit conversions from `Kokkos::View` to `Teuchos::ArrayView`?  We currently allow implicit conversions from `std::vector` and `Teuchos::ArrayRCP` to `Teuchos::ArrayView`.  If we allowed for implicit conversions from `Kokkos::View` to `Teuchos::ArrayView` in addition to this change, then that would make it even easier, no?  The only danger in allowing for the implicit conversion is that it opens the set of problems described in in section "5.7.3 Implicit type conversion problems and shortcomings" in [Teuchos Memory Management Classes](https://trilinos.org/docs/dev/packages/teuchos/doc/html/TeuchosMemoryManagementSAND.pdf).

**Comment by mhoemmen** [comment]
Thanks @bartlettroscoe !  

Just to clarify for other readers: The main reason for this proposed change, is that neither `std::vector` nor `Kokkos::View` promise that their pointer (result of `.data()`) is null when their length is zero.  Thus, the logical way of creating an ArrayView from either of these objects might throw, only in debug mode (`Teuchos_ENABLE_DEBUG`).  Furthermore, many developers do not test in debug mode, nor does PR testing turn on debug mode.

Here is the obvious way to create a `Teuchos::ArrayView`` from an `std::vector` or `Kokkos::View` `vec`:
```c++
// WARNING: will throw in debug build if vec.size() is zero!
Teuchos::ArrayView<int> av (vec.data (), vec.size ()); 
```

**Comment by ibaned** [comment]
> Can't understand what possible value there is in returning a non-null pointer that you are not allowed to de-reference . For an empty view, begin() and end() can both be null and standard logic like begin() != end() and begin() == end() are still valid (which means an empty range). And you are not allowed to increment and iterator if begin() == end() anyway. What is the logic here?

There is a reason `malloc(0) != nullptr` on many platforms. A memory allocator creates an allocation with associated overhead metadata, which is a very real and memory-consuming thing, there just happens to be no space for user's data. Likewise with subviews, they are a range [begin(), end()), just because the span of that range is zero does not mean that the endpoints have to both be at zero. If someone wants to write a complex mergesort-like algorithm using subviews, they may very well care whether `A.end() == B.begin()`, regardless of whether `A.begin() == A.end()`. I think its bad for containers to be full of `return (empty() ? nullptr : real_ptr)` type logic. Just let the users make use of the address, it contains meaningful information.

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> Can't understand what possible value there is in returning a non-null pointer that you are not allowed to de-reference

Regardless of the possible value, the [C++ Standard](http://eel.is/c++draft/vector.data) says nothing about the result of `.data()` on an empty`std::vector`.  (An empty range is a valid range.)  The gloss is that [it could return nonnull](https://en.cppreference.com/w/cpp/container/vector/data).

Suppose that you create an empty vector.  Nothing in the Standard says that an empty vector must have zero capacity.  Most vectors have a small number of elements, so a reasonable optimization would be to do an initial short allocation.  It would be troublesome (and may hinder inlining) for `data()` to have to branch on size, just because of this case.

For Views, it would be annoying to have to check all dimensions for zero size before assigning the pointer.  Subviews need to use minimal code, so that they run fast on GPUs.  Otherwise, users won't use them, precisely where they add the most value (in helping people write correct computational kernels).

**Comment by bartlettroscoe** [comment]
@mhoemmen,

That is the problem with C++, it is always speed over safety.  But in this case, we are talking about a single if statement to construct the view.  There are no if statements in using a view's functions in a non-debug-mode build.

For any functions on array of data to be efficient, you have to have a pretty big chunks of data so the small O(1) overhead of constructing a view would be nothing compared to accessing the data in the view.

The deal for  `std::vector` is different because you can incrementally expand and contract the size of the object, one element at a time.  Nothing like that exists (or should exist) for a type like `Teuchos::ArrayView` (or `std::span`).

**Comment by crtrott** [comment]
`Kokkos::View` has a header which is located right now at `view.data()-128bytes`. `view.data()!=null` indicates you got a non-default initialized view for that matter. As mentioned above it also matches the semantics of C++ containers with regards to data and length. So I vote very strongly for relaxing that restriction in ArrayView. Either change the semantics of its data pointer or make the conversion (`data = (size!=0)?ptr:null`) in the constructor.

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> how would you feel about relaxing this restriction in ArrayView's constructor?

@crtrott said:

> Either change the semantics of its data pointer or make the conversion `(data = (size!=0)?ptr:null)` in the constructor.

I am okay with relaxing the preconditions to allow `ptr!=nullptr` when `size==0` but we have to maintain the post-condition that when `size==0` then `this->getRawData()==nullptr`.  Therefore, `(data = (size!=0)?ptr:null)` is the way to go.

You can always loosen pre-conditions or tighten post-conditions and maintain backward compatibility but you can't tighten pre-conditions or lessen post-conditions or you break backward compatibility.  (This is also an issue for the LSP of OO programming in order for subclasses to be substitutable for their base classes.)

**Comment by crtrott** [comment]
Ok lets do that then 👍 
Who volunteers?

**Comment by mhoemmen** [comment]
Thanks @bartlettroscoe ! :-D  I agree that we should maintain the invariant that `Teuchos::ArrayView` always has a null pointer if its size is zero.

> Who volunteers?

I'll be happy to try it out, unless Ross or somebody else wants to.  If it turns out that this breaks downstream code, though, I would revert the change and put it off in favor of a more comprehensive approach (that fixes downstream code to use direct conversion functions to and from Kokkos::View and std::vector).

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> I'll be happy to try it out, unless Ross or somebody else wants to. If it turns out that this breaks downstream code, though, I would revert the change and put it off in favor of a more comprehensive approach (that fixes downstream code to use direct conversion functions to and from Kokkos::View and std::vector).

@mhoemmen, there is about zero chance of this breaking downstream code.  Again, the suggested change loosens the pre-conditions without impacting post-conditions so the only impact should be the need to update a couple of Teuchos unit tests that actually trigger the exception in a debug-mode build.

If you would be willing to implement this I can review.

Thanks!

**Comment by mhoemmen** [comment]
@bartlettroscoe I think `Teuchos::arcp` does the analogous debug-mode check.  For example, I fixed some other crashing tests in Tpetra by changing how `Kokkos::View`-to-`Teuchos::ArrayRCP` conversion works.  I don't think we need to change `arcp`'s behavior, though, since it's not such a good idea to use a primarily owning idiom (ArrayRCP) for a nonowning view.

**Comment by mhoemmen** [comment]
Note that the provided `ArrayView(std::vector<T>&)` and `ArrayView(const std::vector<T>&)` conversion functions already make `ptr_` null if the input `std::vector` is empty.

**Comment by mhoemmen** [comment]
The nonmember "constructor" `Teuchos::arrayView` already checks if the input size is zero.

**Comment by mhoemmen** [comment]
PR: https://github.com/trilinos/Trilinos/pull/4253

**Comment by bartlettroscoe** [comment]
@mhoemmen, thanks for looking into this. 

I am wondering if GitHub issue overhead could be avoided by just creating a single GitHub issue with a title like "Teuchos Memory Management view classes should require null input pointers for zero size" and then have that cover all of this?

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> I am wondering if GitHub issue overhead could be avoided by just creating a single GitHub issue with a title like "Teuchos Memory Management view classes should require null input pointers for zero size" and then have that cover all of this?

I think it makes sense to keep `ArrayView` separate from `ArrayRCP`.  Creating an `ArrayRCP` with a nonnull pointer and a zero length is more likely to be user error.  On the other hand, even `malloc(0)` may return nonnull: https://en.cppreference.com/w/c/memory/malloc
