### ISSUE TITLE
Belos tests timing out on ATDM intel-18 mpich build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#4260]
CC: @trilinos/belos, @srajama1 (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52
  
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in the links below the tests:
* [Belos_rcg_hb_MPI_4](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&field2=buildstarttime&compare2=84&value2=2019-01-25&field3=buildstarttime&compare3=83&value3=2019-01-01&field4=testname&compare4=61&value4=Belos_rcg_hb_MPI_4)
* [Belos_gcrodr_hb_MPI_4](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&field2=buildstarttime&compare2=84&value2=2019-01-25&field3=buildstarttime&compare3=83&value3=2019-01-01&field4=testname&compare4=61&value4=Belos_gcrodr_hb_MPI_4) 

are randomly timing out in the build:
* Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt

## Current Status on CDash

The current status of the Belos tests on this build for the current testing day can be found [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&field2=buildstarttime&compare2=84&value2=today&field3=buildstarttime&compare3=83&value3=yesterday&field4=testname&compare4=65&value4=Belos_)

## Steps to Reproduce

One should be able to reproduce a build where this is randomly failing on a machine with a cee rhel6 environment as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for a machine with a cee rhel6 environment are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#cee-rhel6-environment

The exact commands to reproduce the build where this issue is randomly occurring should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Belos=ON \
 $TRILINOS_DIR
$ make NP=16
$ ctest -j16
```

**Comment by srajama1** [comment]
@fryeguy52 @bartlettroscoe I missed this issue somehow. 

@hkthorn This looks like something we have seen before in another platform. We might have disabled this test there and might have to do the same here. Can you please check and let us know ?

**Comment by bartlettroscoe** [comment]
Since the merge of #4702, we have been seeing the timeouts disappear for this build.  The recent history is shown below

Therefore, we can close this.

----


<h3><font color="green">Tests with issue trackers Passed: twip=2 (on 20190-03-27)</font></h3>
<table style="width:100%" boarder="1">

<tr>
<th>Site</th>
<th>Build Name</th>
<th>Test Name</th>
<th>Status</th>
<th>Details</th>
<th>Consec&shy;utive Pass Days</th>
<th>Non-pass Last 30 Days</th>
<th>Pass Last 30 Days</th>
<th>Issue Tracker</th>
</tr>

<tr>
<td align="left">cee-rhel6</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=site&amp;compare2=61&amp;value2=cee-rhel6&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2019-03-28T00:00:00&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2019-02-26T00:00:00">Trilinos-atdm-cee-rhel6_&shy;intel-18.0.2_&shy;mpich2-3.2_&shy;openmp_&shy;static_&shy;opt</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=72354539&amp;build=4787318">Belos_&shy;gcrodr_&shy;hb_&shy;MPI_&shy;4</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=72354539&amp;build=4787318"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=testname&amp;compare2=61&amp;value2=Belos_gcrodr_hb_MPI_4&amp;field3=site&amp;compare3=61&amp;value3=cee-rhel6&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-03-28T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-02-26T00:00:00"><font color="green">8</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=testname&amp;compare2=61&amp;value2=Belos_gcrodr_hb_MPI_4&amp;field3=site&amp;compare3=61&amp;value3=cee-rhel6&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-03-28T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-02-26T00:00:00"><font color="red">12</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=testname&amp;compare2=61&amp;value2=Belos_gcrodr_hb_MPI_4&amp;field3=site&amp;compare3=61&amp;value3=cee-rhel6&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-03-28T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-02-26T00:00:00"><font color="green">18</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/4260">#4260</a></td>
</tr>

<tr>
<td align="left">cee-rhel6</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=site&amp;compare2=61&amp;value2=cee-rhel6&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2019-03-28T00:00:00&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2019-02-26T00:00:00">Trilinos-atdm-cee-rhel6_&shy;intel-18.0.2_&shy;mpich2-3.2_&shy;openmp_&shy;static_&shy;opt</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=72354546&amp;build=4787318">Belos_&shy;rcg_&shy;hb_&shy;MPI_&shy;4</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=72354546&amp;build=4787318"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=testname&amp;compare2=61&amp;value2=Belos_rcg_hb_MPI_4&amp;field3=site&amp;compare3=61&amp;value3=cee-rhel6&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-03-28T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-02-26T00:00:00"><font color="green">8</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=testname&amp;compare2=61&amp;value2=Belos_rcg_hb_MPI_4&amp;field3=site&amp;compare3=61&amp;value3=cee-rhel6&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-03-28T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-02-26T00:00:00"><font color="red">9</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt&amp;field2=testname&amp;compare2=61&amp;value2=Belos_rcg_hb_MPI_4&amp;field3=site&amp;compare3=61&amp;value3=cee-rhel6&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-03-28T00:00:00&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-02-26T00:00:00"><font color="green">21</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/4260">#4260</a></td>
</tr>

</table>
