### ISSUE TITLE
Tpetra::Map::locallySameAs slow when running computations on GPU

### ISSUE THREAD

**Issue by ambrad** [trilinos/Trilinos#433]
Tpetra::DistObject::doImport calls Map::operator!= even when ! defined HAVE_TPETRA_DEBUG. That means isSameAs and locallySameAs must be fast.

If pointer equality, contiguity, uniformity, etc. checks fail, then locallySameAs iterates over GIDs on the host. This is very expensive relative to GPU computations.

I don't require an urgent fix for this problem, as I can work around this, but I'm opening this issue because I think the problem needs to be fixed at some point.

**Comment by mhoemmen** [comment]
> Tpetra::DistObject::doImport calls Map::operator!= even when ! defined HAVE_TPETRA_DEBUG. That means isSameAs and locallySameAs must be fast.

That's totally wrong.  The test should go inside HAVE_TPETRA_DEBUG.  (Yes, `git blame` says I wrote it ;-) have a hard time believing that I would have let that stand, though.  It probably just doesn't pop up as a performance issue often, because apps usually hit the fast path (e.g., pointer equality).

**Comment by mhoemmen** [comment]
I've got a fix ready.  Running CUDA tests now, will do non-CUDA tests for the push.

**Comment by mhoemmen** [comment]
@csiefer2 would you object to removal of comparable tests from transferAndFillComplete etc.?
