### ISSUE TITLE
Build failures in SPARC 'master' + Trilinos 'develop' starting 2/5/2019 due to break in Teuchos::SerialDenseMatrix

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4330]
CC: @trilinos/teuchos , @jwillenbring (Trilinos Framework Product Lead), @bartlettroscoe, @fryeguy52, @sebrowne, @micahahoward

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this SPARC CDash query for 2019-02-05](http://compsim-dashboard.sandia.gov/cdash/index.php?project=SPARC&date=2019-02-05&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-trildev), the version of Trilinos 'develop' for testing day 2019-02-05 has broken the new SPARC 'master' + Trilinos 'develop' builds (see [TRIL-243](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-243)) which detect defects in Trilinos 'develop' which break SPARC.  These build failures did not exist in those builds the previous day as shown in [this SPARC CDash query for 2019-02-04](http://compsim-dashboard.sandia.gov/cdash/index.php?project=SPARC&date=2019-02-04&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-trildev).

The 'clang-5.0.1' build shows just one build failure [here](http://compsim-dashboard.sandia.gov/cdash/viewBuildError.php?buildid=92804) which shows:

```
sparc-ear99/src/solver-analysis/ROLInterface.C:313:14: error: invalid operands to binary expression ('std::ofstream' (aka 'basic_ofstream') and 'Teuchos::SerialDenseMatrix' (aka 'SerialDenseMatrix'))
      cov_out << cov;
     ~~~~~~~ ^  ~~~
```

That SPARC 'master' build was built against Trilinos 'develop' for testing day 2019-02-05 for the build `Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt` shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4494553). 

## Current Status on CDash

The current status of the SPARC 'master' + Trilinos 'develop' builds for the current testing day can be see [here|http://compsim-dashboard.sandia.gov/cdash/index.php?project=SPARC&date=2019-02-05&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-trildev] (internal link).

## Steps to Reproduce

For one that has access to the SPARC development resources, one can reproduce the build failures using the `sparc-tril-build-helper` scripts.

**Comment by bartlettroscoe** [comment]
Looking over the new commits in Trilinos pulled on 2019-02-05, it looks like this was triggered by the Trilinos commit 0598e02:

```
0598e02:  Teuchos: Issue #4258 (Remove SerialDense matrix inheritance from Object)
Author: Russell Hooper <rhoope@sandia.gov>
Date:   Tue Jan 22 10:52:11 2019 -0700

M	packages/teuchos/numerics/example/DenseMatrix/cxx_main.cpp
M	packages/teuchos/numerics/example/DenseMatrix/cxx_main_sym.cpp
M	packages/teuchos/numerics/example/LAPACK/cxx_main.cpp
M	packages/teuchos/numerics/src/Teuchos_SerialBandDenseMatrix.hpp
M	packages/teuchos/numerics/src/Teuchos_SerialDenseMatrix.hpp
M	packages/teuchos/numerics/src/Teuchos_SerialSymDenseMatrix.hpp
M	packages/teuchos/numerics/test/DenseMatrix/cxx_main.cpp
```

pushed in PR #4259 merged to 'develop' on 2/4/2019.

@rhoope, my guess is that this change broke the output operator for `Teuchos::SerialDenseMatrix`.   And it looks like this was detected in a change to the test file:

* packages/teuchos/numerics/test/DenseMatrix/cxx_main.cpp

Can you please work with the SPARC developers to deal with this output operator?  Is there a way to achieve what is desired without breaking backward compatibility?

NOTE: We are getting zero benefit from SPARC 'master' + Trilinos 'develop' testing after this change because it brings down almost all of the SPARC tests.

**Comment by bartlettroscoe** [comment]
@mseldre asked:

> Can I ask what you were using the provided ostream insertion operator for?

@mseldre, it is being used by SPARC.

Seems reasonable for a class to have a basic `operator<<(std::ostream, ...)` function that prints something useful.  My guess is that existing clients like SPARC just want some debug output and don't care about how detailed it is.

I can show you how to create really flexible ostream output operators that let you print whatever you want.  An example if this is the [operator<<(std::ostream&, const DescribableStreamManipulator&)](https://trilinos.org/docs/dev/packages/teuchos/doc/html/Teuchos__Describable_8hpp_source.html#l00245) function.  you use it like:

```
std::cout << "This is my object:\n" << describe(obj, VERB_HIGH);
```

This way you can layer on your own ostream output operators to print anything you like.

**Comment by bartlettroscoe** [comment]
@mseldre said:

> Also see issue #4259 for discussion of removing this long-deprecated code.

The deprecations mentioned by @hkthorn in the comment referenced in #4258 was to remove the base `Teuchos::Object` class, but there was no mention of removing the ostream operator.

**Comment by mhoemmen** [comment]
oops, sorry, my bad

**Comment by hkthorn** [comment]
@bartlettroscoe @mseldre The removal of the ostream operator has also broken Xyce and Charon (and Xychron).

**Comment by bartlettroscoe** [comment]
@hkthorn said:

> @bartlettroscoe @mseldre The removal of the ostream operator has also broken Xyce and Charon (and Xychron).

Given that is the case, can we please add back the `operator<<()` function for now (or just revert the entire PR)?  I am going to hit this later today as part of adding strong warnings to the ATDM Trilinos 'cee-rhel6' builds as part of work toward #3178 and [TRIL-255](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-255).  Any objection to me adding back `operator<<()` and a unit test for this?

**Comment by hkthorn** [comment]
Sorry, this is a big issue for downstream applications that leverage the Teuchos SDM so the operator<<() function has to be returned.

**Comment by mhoemmen** [comment]
@bartlettroscoe I don't object to reverting this.

**Comment by mhoemmen** [comment]
@hkthorn Does Xyce actually build against current Trilinos?  I had thought y'all were using 12.12.1.

**Comment by rhoope** [comment]
Would it be possible to add operator<< to the individual Teuchos classes to avoid them all inheriting from Teuchos::Object?  This would avoid the bloat associated with Object strings inherited by what would otherwise be much smaller derived classes (and is the original motivation for breaking inheritance in Issue #4258)?

**Comment by hkthorn** [comment]
@mhoemmen For releases we use 12.12.1, but the developers (like myself) that are using newer Trilinos packages build against develop.  Charon, that uses the Tpetra stack, builds against Trilinos develop/master and that means that Xychron (Xyce+Charon) must build against Trilinos develop/master.  Clear as mud?

**Comment by bartlettroscoe** [comment]
@hkthorn said:

> Sorry, this is a big issue for downstream applications that leverage the Teuchos SDM so the operator<<() function has to be returned.

@mhoemmen said:

> @bartlettroscoe I don't object to reverting this.

Okay, I will go ahead and create a PR that reverts PR #4259 and then can someone create a new Issue to figure out a solution?

**Comment by bartlettroscoe** [comment]
FYI: I created PR #4336 to revert PR #4259.

Can someone create a new GitHub issue for removing `Teuchos::Object` but maintain `operator<<()`?

**Comment by bartlettroscoe** [comment]
@rhoope asked:

> Would it be possible to add operator<< to the individual Teuchos classes to avoid them all inheriting from Teuchos::Object? This would avoid the bloat associated with Object strings inherited by what would otherwise be much smaller derived classes (and is the original motivation for breaking inheritance in Issue #4258)?

Yes, that would be the right thing to do.  There should be minimal code duplication with an approach like that and it would give the smallest objects.  We don't need polymorphic `operator<<()` function in a case like this.

**Comment by mseldre** [comment]
> @mseldre asked:
> 
> > Can I ask what you were using the provided ostream insertion operator for?
> 
> @mseldre, it is being used by SPARC.
> 
> Seems reasonable for a class to have a basic `operator<<(std::ostream, ...)` function that prints something useful. My guess is that existing clients like SPARC just want some debug output and don't care about how detailed it is.
> 

I will note that the std library does not provide iostream insertion/extraction operators, presumably to avoid causing difficulty for applications from ADL rules.  Yes, there are work-arounds as you suggest, and we had a number of them previously -- and were very happy to see them go!  So I would advocate for a compromise where we add back these default iostream insertion/extraction operators but put in a separate header that applications can choose include or not.  Codes that want this capability will have to be very slightly modified to add the header.

**Comment by mseldre** [comment]
One other general thing -- as noted in #4259, the Dakota team would be happy to wait until a Trilinos release or other appropriate time to sync local changes and help resolve any impacts.  But it sounded like these opportunities have become scarce/non-existent such that moving forward now was as good as any other time.  Happy to be informed of other opportunities.

**Comment by bartlettroscoe** [comment]
@mseldre,

My opinion is that code like `Teuchos::SerialDenseMatrix` has been around too long and used in too much user code to make a non-backward compatible change like this without a very strong technical reason (the ship has sailed).  The massive changes that it took in the original PR #4259 should have been a warning about the impact of this change. 

Using the approach I outline [above](https://github.com/trilinos/Trilinos/issues/4330#issuecomment-461042814), you can print whatever you want by adding a short function call to your output statements.  If you put in in your namespace it can be a single letter like:

```
std::cout << p(MyMatrix};
```

That is three extra chars.

**Comment by mseldre** [comment]
Thanks for the thoughts.

@rhoope would have to comment on the extent of previous changes, but they could be quite minimal (i.e., a one-liner in an upstream client header) if there was an optional header include for the ostream insertions (Teuchos_SerialDenseIO.hpp or similar).

We already had workarounds exactly like this all over our code, so you are not suggesting anything new. They are gone now but could be reverted easily enough if that is the only option that we have.  We will have to discuss our options.

**Comment by bartlettroscoe** [comment]
@mseldre and @rhoope,

What we could do to avoid breaking backward compatibility bug give you want you want is to split the current header file and source files `Teuchos_SerialBandDenseMatrix.[hpp,cpp]` into `Teuchos_SerialBandDenseMatrix_Class.[hpp,cpp]` and  `Teuchos_SerialBandDenseMatrix_IO.[hpp,cpp]` (where you remove the `Teuchos::Object` base class) and then make `Teuchos_SerialBandDenseMatrix.hpp` include `Teuchos_SerialBandDenseMatrix_Class.hpp` and `Teuchos_SerialBandDenseMatrix_IO.hpp`.  Then Dakota could just include `Teuchos_SerialBandDenseMatrix_Class.hpp` and not get the `operator<<()` function that you don't want.

That does not break any backward compatibility and still gives you want you want (no `operator<<()` function).

Everyone okay with that solution?

P.S. Hopefully PR #4336 testing will come back clean soon.

**Comment by mseldre** [comment]
I think that could work so long as there isn't any header bleed elsewhere that causes problems.  For example, SerialDenseHelpers pulls SerialDenseMatrix which would pull IO.  So there would need to be careful review/revision of internal dependencies to enable clients to exclude IO, but seems do-able.

**Comment by mseldre** [comment]
Same story for all the Solver classes.

**Comment by mhoemmen** [comment]
@bartlettroscoe I was advocating the `operator<<(std::ostream&, const Wrapper&)` approach -- I think that's the best way to get the behavior they want without breaking backwards compatibility -- but in general, overloading `operator<<` is kinda uncool due to ADL.

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> I was advocating the `operator<<(std::ostream&, const Wrapper&)` approach -- I think that's the best way to get the behavior they want without breaking backwards compatibility

> but in general, overloading `operator<<` is kinda uncool due to ADL.

That is true for any overloaded operator function.  But when dealing with concrete types like this, I can't see an issue with that.

**Comment by mseldre** [comment]
Hi Ross,
The issue is that these classes are not just any concrete type, they are data containers.  So here's the argument, for the record -- as clients of container classes, you would generally use them for importing data, performing operations, and exporting/printing that data.  By defining an ostream insertion operator in the Teuchos namespace, argument-dependent lookup takes away some of the ability for clients to define how they want to export their data, forcing work-arounds that are do-able but annoying/less convenient -- thus the "kinda uncool" argument (and the reason why std:: containers do not define these operators).  The insertion operator in question was defined for a deprecated class (operator<<(ostream&, Teuchos::Object)), and it should _also_ be viewed as deprecated as it currently exists, due to ADL.

So to move forward, I am happy to pursue one of several options in creating another PR, if we can reach a consensus/compromise.  These options are listed roughly in order of increasing preference:

- _break backwards compatibility at an appropriate time (option 1):_ when syncing with an upstream branch or adopting a new Trilinos version, clients would include a new Teuchos IO header if they want to continue to use this deprecated operator.  In codes that I am most familiar with, this would be a one-line addition in an appropriate upstream header.  Based on the feedback in these trackers, there doesn't seem to much support for this option in general, nor a defined future release plan.
- _retain backwards compatibility (option 2):_ separate Class and IO headers using the approach you suggest above.  This is similar to option 1 in terms of creating separate IO header(s), but with the addition of making the main container class header files (e.g., SerialDenseMatrix.hpp) dependent on the IO headers (SerialDenseMatrix_IO.hpp) to preserve backwards compatibility.  A number of internal inclusions of the container headers (e.g., Helpers and Solvers) will need to be revised to isolate the IO dependence, so this is a fairly significant change.  But these dependencies should separate cleanly since we did not have internal Teuchos problems when the operator was essentially removed in the previous PR.
- _retain backwards compatibility (option 3):_ Protect these operators with compile-time macros that default to the old behavior, e.g., #ifndef DISABLE_TEUCHOS_IO around the operator declaration.  Then clients can move towards deprecation on their own timetable by defining this macro when they are ready, and it's a minimal isolated change with no major surgery required.
- _retain backwards compatibility (option 4):_ If we defined the Teuchos ostream operator(s) in the global namespace rather than the Teuchos namespace, I _think_ this circumvents ADL by not taking precedence over namespace-specific operators: _"For a name used in a user-declared namespace outside of any function or class, this namespace is searched before the use of the name, then the namespace enclosing this namespace before the declaration of this namespace, etc until the global namespace is reached."_  So the global namespace is searched last, allowing clients to either use the default global operator or override it with an operator specific to their namespace.  If successful, this is the only option of the 4 that also avoids potential synchronization problems for codes that link with both Trilinos and Dakota (Xyce, ALEGRA, Albany, etc.), since uses of the current operator and client-tailored operators can cleanly coexist.

**Comment by mhoemmen** [comment]
Option 4 could be confusing if clients want to work in a different namespace or forget to include some header that overrides the operator.

**Comment by bartlettroscoe** [comment]
In my opinion, option-2 is ideal but I understand why it is hard.  Option-3 would work as well but is very fragile since there will be no automated Trilinos tests that will define `DISABLE_TEUCHOS_IO` (and that name is too general anyway).  I would prefer option-1 over option-3 but it would make it more difficult for customers that do daily integration testing with Trilinos at the same time they build against an older stable version of Trilinos (as we are now doing with SPARC).  But I can image how option-1 could be made to work with SPARC and other codes (but adding the Trilinos version number to the generated `Trilinos_version.h` file and then have the APPs ifdef on that).

All of these options will take a lot of work in Trilinos and in existing down-stream customers (except option-2).  If it were me, I would just go with the `ostream<<(std::ostream&, const Wrapper&)` approach outlined above.  But of someone wants to go through all of this trouble, my preferred solutions (in order) would be:

1. option-2: Maintain perfect backward compatibility and split out header and source files.
2. option-1: Make a break in backward compatibility and put stream operators in new header files
3. option-3: Use preprocessor macro to remove stream operators that Dakota does not like

Given what I know about C++ and ADL and namespacing (e.g. see "D.2 Amendments for ’using’ declarations and directives" in [Thyra Coding and Documentation Guidelines](https://trilinos.org/docs/dev/packages/thyra/doc/html/ThyraCodingGuideLines.pdf)), I don't think option-4 should be considered.  It is asking for trouble and will break user code, I can almost guarantee it.

**Comment by bartlettroscoe** [comment]
FYI: Eight PR testing attempts over the last 4 days to merge PR #4336 have failed.  I am taking action to fix the SPARC 'master' + Trilinos 'develop' builds (see https://github.com/trilinos/Trilinos/issues/3276#issuecomment-462198925).

**Comment by bartlettroscoe** [comment]
FYI: With PR #4336 now merged and with the actions I took in [TRIL-260](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-260) to get SPARC Trilinos Integration testing working, we can put this issue in review.

**Comment by bartlettroscoe** [comment]
FYI: As predicted the SPARC Trilinos Integration builds pointing to the 'atdm-develop-nightly' branch are now passing the builds (with just one failing test) as shown by [this SPARC CDash query](http://compsim-dashboard.sandia.gov/cdash/index.php?project=SPARC&date=2019-02-11&filtercount=1&showfilters=1&field1=buildname&compare1=66&value1=-trildev).

Closing as complete.

@mseldre, @rhoope, @hkthorn, and @mhoemmen,

Further discussion of how to deal with Dakota requirements and backward compatibility concerns for `Teuchos::SerialDenseMatrix` should be conducted in a new GitHub Issue.
