### ISSUE TITLE
Question: Single-reduce iterative solvers in Belos

### ISSUE THREAD

**Issue by srajama1** [trilinos/Trilinos#4360]
Do we have two "single-reduce" iterative methods in Belos ? One by Ichi that is Tpetra specific and one that can work with Epetra  ? I would appreciate any pointers, new information on when to use one vs another, differences etc.

@hkthorn @cgcgcg @egboman @mhoemmen

**Comment by cgcgcg** [comment]
@srajama1 Yep, that's correct. We haven't compared them yet, but I think we could hack something into the MueLu driver that allows to run both types of solvers at scale..

**Comment by srajama1** [comment]
@cgcgcg : Silly question, why did we write two ? :) Comparing performance will be great, but I am also wondering if there are algorithmic differences.

**Comment by cgcgcg** [comment]
The Tpetra one uses non-blocking all-reduces, which is not generally available in the Belos MultiVectorTraits. The Tpetra implementation also seems to do right-preconditioning only, but that should be easy to change. Moreover, it detects convergence based on the preconditioner-induced norm, whereas the other implementation can do 2-norm or preconditioner norm.
(@mhoemmen please correct me if I am wrong about this.)

**Comment by mhoemmen** [comment]
@cgcgcg is right.  More specifically, pipelined CG and GMRES depend on nonblocking all-reduces.  Belos' "generic" solvers can only use operations in Belos::MultiVecTraits and Belos::OperatorTraits.  We can't add new methods to MultiVecTraits without breaking backwards compatibility.  The only way around this is to add a new traits class to Belos, with a default implementation that does something sensible.  @hkthorn likely remembers that we did this in order to fix Anasazi and Belos for 64-bit global ordinals.  If y'all want to do that, go ahead.

There are other reasons to have Tpetra-specific solvers.  For example, Tpetra could fuse linear algebra kernels in ways that would be hard in a generic implementation.  (When I say "generic," don't think "Epetra"; think more black-box, like Thyra block multivectors.)  Ichi and I have done some of this, but there are more opportunities for linear algebra - specific optimizations, especially once we get farther with the RTI stuff that I woke up again for the Amanzi developers a couple months ago.

**Comment by srajama1** [comment]
The right preconditioning and the norm seem to be small differences that can be added to Tpetra implementation. Is that right ? Is it possible to have one implementation for the user where it is a Tpetra input Belos calls the non-blocking-all-reduces, it resorts to the other method when for non-Tpetra code ?

**Comment by srajama1** [comment]
@srajama1 : My github page updated with @cgcgcg 's comment but not with @mhoemmen 's comment. @mhoemmen has already addressed some of the questions I raised in the comment above. I will let @hkthorn and belos developers decide if she wants to go the new traits with default implementation route. Ideally, I would like the non-blocking all-reduce implementation to be available to Thyra/Stratimikos users (when we know Tpetra is the underlying concrete implementation). That is what I was going after because that is what the application is doing. That is a new feature request, though. May be when @iyamazaki comes here :)

Thanks for answering this question. Closing it.

**Comment by mhoemmen** [comment]
> I would like the non-blocking all-reduce implementation to be available to Thyra/Stratimikos users (when we know Tpetra is the underlying concrete implementation)

That would take work in Thyra, especially if using block operators and block vectors.

**Comment by egboman** [comment]
I believe the algorithms are different but did not see any comments on that. 
The CG algorithm in BelosCGSingleRedIter.hpp (by @hkthorn ) is based on the paper by Chronopolous & Gear. What algorithm did Ichi & Mark implement?

**Comment by mhoemmen** [comment]
@egboman Ask Ichi :)

**Comment by mhoemmen** [comment]
Answered.
