### ISSUE TITLE
Kokkos: Intel not supported with CUDA?

### ISSUE THREAD

**Issue by amklinv** [trilinos/Trilinos#4379]
@trilinos/kokkos @mhoemmen 

## Expectations
Trilinos builds with CUDA support using Intel for the host compiler.  Alternatively, document that this is not supported.

## Current Behavior
When I try to build Trilinos with CUDA support using the nvcc_wrapper and Intel as the host compiler, I get an error message during the build
> nvcc fatal   : Option --expt-extended-lambda (-expt-extended-lambda) is unsupported with the icc compiler

## Your Environment
- CUDA 9.1
- Intel 16.0.4 
- CentOS 7

Relevant CMake flags
- CMAKE_CXX_FLAGS='--expt-extended-lambda'
- KOKKOS_ARCH="SKX;Volta72"

**Comment by ibaned** [comment]
It looks like NVCC gave us the answer in this case: CUDA lambdas don't work with the Intel compiler, and I think Tpetra now requires CUDA lambdas in order to compile with CUDA. Therefore, this is not supported. I'm not sure how to document this.

**Comment by amklinv** [comment]
Maybe include it in the CUDA build instructions?  Or check for this case at configure time and output an error message then?

**Comment by mhoemmen** [comment]
@ibaned We could just have Kokkos (at least through the TriBITS build system) error out at configure time, if it encounters that combination of options.  We could also try newer CUDA and Intel versions (CUDA 10 claims that it works with Intel 18).

**Comment by crtrott** [comment]
There is a list of officially supported compiler combos in the README of Kokkos. But I think we can't do much about this right now. There is basically only three choices:

 * Do what we do now: i.e. document what we test and leave the rest to the user. 
 * Have a white list of compilers: i.e. if you use something we don't test error out. 
 * Have a black list of compiler combos: i.e. black list everything we know doesn't work. 

But  I think the white list solution is something people wouldn't like, because you can only use a fraction of the compilers which would actually work. And keeping a black list up to date is too much work. 

ICC + CUDA is not on our list right now, since none of our production platforms now or in the foreseeable future will be able to run that.

**Comment by mhoemmen** [comment]
I could just add something to Kokkos' TriBITS logic that forbids ICC + CUDA if CUDA lambdas are enabled.  I'm not sure if Kokkos wants to maintain that going forward, though.

**Comment by crtrott** [comment]
I mean the benefit over the fatal message you are already getting is pretty small I would argue. And shouldn't you get that message already during configure at some point?

**Comment by crtrott** [comment]
If configure doesn't fail, maybe the better answer would be to add a step at the end of configure which tries to build a dummy file with the full set of compiler flags which we add.

**Comment by mhoemmen** [comment]
@crtrott wrote:
> If configure doesn't fail, maybe the better answer would be to add a step at the end of configure which tries to build a dummy file with the full set of compiler flags which we add.

I like that better -- more general, and no more compiler-specific state to maintain.

**Comment by ibaned** [comment]
It would catch a ton of other reported issues like too-old assemblers not recognizing vector instructions.
