### ISSUE TITLE
Download with mandatory sign-up

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#45]
There are many straightforward ways to get Trilinos nowadays:
- `git clone` from GitHub
- [download a release from GitHub](https://github.com/trilinos/Trilinos/releases)
- get it from [Debian](https://tracker.debian.org/pkg/trilinos)
- get it from the [nightly PPA](https://launchpad.net/~nschloe/+archive/ubuntu/trilinos-nightly/)

Oh, and of course the [official download page](https://trilinos.org/download/) which [requires you to sign up before download](https://trilinos.org/oldsite/download/login.html?tid=tr12042bz2). Rather than helping the distribution of Trilinos, the sign-up hinders it. The gain that one supposedly gets from that is a user statistics, but in the light of the alternative download methods listed above, this statistic is practically worthless.

I suggest to remove the sign-up requirement from the download page.

**Comment by jhux2** [comment]
@maherou @jwillenbring @bmpersc

**Comment by egboman** [comment]
Do we need so many places to download from? Could Trilinos.org point to GitHub or vice versa?

**Comment by bmpersc** [comment]
one thing to point out is the releases that github is showing are not the releases that we make. It looks like github noticed that we have tags with the word "release" in the name and decided to try and be smart. Unfortunately that means it also picks up tags like when we mark the root of a branch and others that we don't officially release. In my very quick looking I didn't see a way to disable this, but I haven't even tried googling yet.

I suspect that we won't want to use github's tarballs for a couple obvious reasons. One they are larger than what we release since we do cull stuff from our tarballs. Two they only work on the repo level so they won't include any of the external repo packages like Sundance which have previously been included in releases and we still intend to include last I heard. Using the github tarballs to get Trilinos and the external packages would require someone to download multiple tarballs to get the complete release.

As for the PPA and debian releases. I know Nico has put in a lot of effort there and I'm thankful he has done that since it solved a problem he saw. However, I personally still don't see that being a major part of our official release offerings. Every time we've looked to create a general one Trilinos to rule them all kind of thing we've failed to come to a consensus that makes it possible for a reasonably sized group to gain benefit, even internally. SEMS just went through a very restricted exercise of attempting to find a common configure for 3 major users and discovered that we needed 3 mutually exclusive configures for them. I'm not opposed to the existence of such distributions, but for us to officially support them seems like more effort than the benefit they provide. When someone else is supporting these even if they are only doing the configure that they need/want then that changes things. The cost/benefit clearly is good enough for them and if even one person other than their audience benefits from it then that is extra goodness.

**Comment by nschloe** [comment]
I didn't mean to suggest to _remove_ the download section from trilinos.org. Quite the contrary: I would like to see it more accessible!

**Comment by jwillenbring** [comment]
@maherou If we update how downloads are tracked, I would like to move to a different system for downloads. Either tracking with google analytics, or a WordPress plugin, or something else. I agree that mandatory sign up is at best old-fashioned. This implies a break in the current download database that Mike H is always interested in. I don't think it makes sense to try to change this to track downloads in a different way than we have. This would fundamentally change what we are tracking and make previous data less accurate in a sense. This data is already not accurate because of all the other ways to get Trilinos.

In particular, other strategies could  track country of origin perhaps, but couldn't track industry/academic/personal use.
