### ISSUE TITLE
Re-enable the ROL_NonlinearProblemTest_MPI_4 test for cuda testing

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#4573]
This was disabled in #4572 to keep PRs moving. There are a large number of ROL tests disabled for CUDA as well indicating some issue with code, threading, etc.

@trilinos/rol 

## Expectations
Discover the underlying problem and re-enable this test when possible to support downstream users.

## Current Behavior
This test runs in about 10 seconds on CPU, but varies from 400-600 second on white and ride.

## Motivation and Context
This kept several unrelated pull requests from testing cleanly over the past week.

**Comment by dridzal** [comment]
@etphipp 
The problematic test uses Sacado to compute all derivative information.  On a CPU we are seeing test times of under 10 seconds.  On white and ride, we are looking at 10 minutes.  I think that some of this is due to bad threading.  However, I'm also wondering if the use of Sacado (possibly incorrect or GPU-incompatible) may be to blame.  Are there any pitfalls in using Sacado in this context?  We are computing first and second derivatives of simple functions with a handful of variables.  Is there anything special that needs to be set in the environment for smooth CUDA operation?
(Including @gregvw , as he is the author of the test.)

**Comment by etphipp** [comment]
Are you using DFad?  If you build Sacado with CUDA enabled, all dynamic memory allocations will be on the GPU and accessed on the CPU via UVM.  This is because if you enable CUDA, Sacado assumes you are going to run Sacado through CUDA parallel kernels, and hence allocations should be on the GPU.  If you change to SFad or SLFad, you won't have this issue.

**Comment by dridzal** [comment]
@gregvw can comment on this.  My guess is that there is no need for DFad, as problem sizes are known ahead of time.  @etphipp --just to clarify-- the DFad route would be much slower?

**Comment by etphipp** [comment]
> @gregvw can comment on this. My guess is that there is no need for DFad, as problem sizes are known ahead of time. @etphipp --just to clarify-- the DFad route would be much slower?

Yes.  On the GPU, dramatically slower.

**Comment by dridzal** [comment]
@gregvw could you please check if (1) DFad is used and (2) if so, if it is needed.  This particular test has been a headache for many developers, and if the solution is as simple as switching to SFad, we should do it.  Having said that, I don't know the ROL/Sacado interface well enough to say that the switch is actually simple (it depends on how general the interface is supposed to be).
(Including @jwillenbring @bartlettroscoe @srajama1 )
