### ISSUE TITLE
MueLu: deprecate code in preparation for next release

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#4728]
@trilinos/muelu 

If there are features that we want to deprecate in MueLu, we should do so before the next minor release, which is around April 15.

**Comment by lucbv** [comment]
@jhux2 @csiefer2 @cgcgcg @rstumin 
I would like to deprecate a bunch of the: CreateX/T/EpetraPreconditioner() interfaces in order to keep only:
```
CreateXpetraPreconditioner(Teuchos::RCP<Xpetra::Matrix<Scalar,LocalOrdinal,GlobalOrdinal,Node> > op, const Teuchos::ParameterList& inParamList)
CreateXpetraPreconditioner(Teuchos::RCP<Xpetra::Matrix<Scalar,LocalOrdinal,GlobalOrdinal,Node> > op, const std::string& xmlFileName)
```

We would then ask users to put their coordinates and nullspace on the parameter list directly even if that is the only thing that is on said list.

Any objections or comments?

**Comment by cgcgcg** [comment]
@lucbv RefMaxwell is currently passing coordinates as argument, but that's simple to fix.

**Comment by lucbv** [comment]
@cgcgcg this would just be a deprecation, you would have time to adapt to the new interface.

**Comment by jhux2** [comment]
> I would like to deprecate a bunch of the: CreateX/T/EpetraPreconditioner() interfaces

I approve!

**Comment by lucbv** [comment]
@jhux2 I think this can be closed now?
