### ISSUE TITLE
PanzerAdaptersSTK test timing out in ATDM build on white/ride

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#4778]
CC: @trilinos/panzer, @mperego (Trilinos Discretizations Product Lead), @bartlettroscoe, @fryeguy52

 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug&field2=testname&compare2=61&value2=PanzerAdaptersSTK_MixedCurlLaplacianExample-ConvTest-Tri-Order-1&field3=site&compare3=61&value3=white&field4=buildstarttime&compare4=84&value4=2019-03-31&field5=buildstarttime&compare5=83&value5=2019-02-28) the test:
* PanzerAdaptersSTK_MixedCurlLaplacianExample-ConvTest-Tri-Order-1

is failing (timeout) in the build:
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug

It started to timeout on ride on 2019-03-20.  Prior to that day it was taking about 9 minutes to complete. A list of commits on that day can be found [here](https://testing.sandia.gov/cdash/viewNotes.php?buildid=4755222#!#note1)

## Current Status on CDash

The current status of this test can be seen [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug&field2=testname&compare2=61&value2=PanzerAdaptersSTK_MixedCurlLaplacianExample-ConvTest-Tri-Order-1&field3=buildstarttime&compare3=84&value3=today&field4=buildstarttime&compare4=83&value4=yesterday)

## Steps to Reproduce

One should be able to reproduce this failure on ride or white as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for ride or white are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Panzer=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug&field2=testname&compare2=61&value2=PanzerAdaptersSTK_MixedCurlLaplacianExample-ConvTest-Tri-Order-1&field3=site&compare3=61&value3=ride&field4=buildstarttime&compare4=84&value4=2019-05-02T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-04-02T00%3A00%3A00) this test has been passing in this build every day (except one day had a random build error on 2019-04-15) and passes in less than 4 minutes since 4/2/2019.

Closing as complete.
