### ISSUE TITLE
Percept: integrate as a new package into trilinos

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#4807]
Percept used to be a subpackage in STK during the "classic stk" era. When STK was refactored, percept was no longer ported over. Since percept is tied strongly to STK and the two must be in sync, it makes sense to start snapshotting percept into trilinos along with stk once again.  This issue is to set up percept build as a tribits package.

Percept is developed in sierra and is thoroughly test with sierra. The tests will not be ported into trilinos - only a few small acceptance tests and some panzer tests will be in trilinos. This will prevent a large size increase in the Trilinos code base from binary mesh files.

1. [DONE] Set up snapshot tool. Port src directory only.
2. [DONE] Set up config file to mirror compile time defines.
3. Hide dependencies on cgns and open nurbs behind ifdefs so we can compile without those TPL requirements.
4. Setup test scripts for Brian and Byron to build against.
5. Coordinate with STK team on snapshots.

**Comment by bartlettroscoe** [comment]
CC: @bathmatt, @mperego 

@rppawlo,

FYI: After the merge of PR #5829 yesterday to bring in Percept, it is getting disabled in all of the ATDM Trilinos builds due to:

```
-- Setting Trilinos_ENABLE_Percept=OFF because Percept has a required library dependence on disabled package Intrepid
```

You can see this, for example, in the builds [Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt](https://testing-dev.sandia.gov/cdash-dev-view/viewConfigure.php?buildid=4854720) and [Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug](https://testing-dev.sandia.gov/cdash-dev-view/viewConfigure.php?buildid=4856091).

Does this mean that the ATDM Trilinos builds must allow the enable of Intrepid or does more work need to be done to replace the Intrepid dependence with Intrepid2?

**Comment by rppawlo** [comment]
For now Percept does require the use of intrepid 1. Changing to Intrepid2 would have to be handled by the Percept team. @bcarnes - can you comment on this? Maybe we should leave it disabled in ATDM builds until we sort this out?

**Comment by rppawlo** [comment]
This is completed.
