### ISSUE TITLE
Framework: Non-framework machines no longer able to report to Cdash

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#4809]
And for that matter, the entire Nightly track is gone.  SAD!

(Originally noticed by @lucbv)

@trilinos/framework  

@trilinos/tpetra This will impact deprecation work after the release if it is not resolved by then.

**Comment by csiefer2** [comment]
@trilinos/framework I have not been able to verify if this is still occurring because the cdash page won't load at all.

**Comment by prwolfe** [comment]
Ummm, loaded for me just now and earlier this morning.  Which url are you using?

**Comment by csiefer2** [comment]
https://testing.sandia.gov/cdash/index.php?project=Trilinos&subproject=MueLu

**Comment by csiefer2** [comment]
Looking at the Trilinos as a whole, non-framework machines still aren't posting to cdash.

**Comment by prwolfe** [comment]
if I run a filter using https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=63&value1=nightly&field2=buildstarttime&compare2=83&value2=3/29/2019 it shows that there are not submissions since the 29th. I think this is when testing-vm stopped accepting connections.  You should check to see that your jobs are going to testing.sandia.gov instead.

@bartlettroscoe  - is this possibly in a script @csiefer2 is pulling from tribits? I thought you and Henry changed all of those.  If not we will have to check with the admins to see whats going on at the CDash end.

**Comment by bartlettroscoe** [comment]
This is likely due to a recent change in TriBITS that impacted the deprecated [TriBITS Dashboard Driver system](https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-dashboard-driver) but not the [TriBITS CTest Driver system](https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-ctest-cdash-driver) which is used by all of the ATDM Trilinos builds.  This is likely why I did not notice any problem (because it was not impacting the ATDM Trilinos builds).

I will take a look at what is going on.

**Comment by csiefer2** [comment]
@bartlettroscoe  Thanks!

**Comment by jhux2** [comment]
@bartlettroscoe I looked at the cron logs from two different MueLu test machines, and there's a common error:
```
C) Configure /data/nightlyTesting/TDD_BUILD ...
SetCTestConfiguration:BuildDirectory:/data/nightlyTesting/TDD_BUILD
SetCTestConfiguration:SourceDirectory:/data/nightlyTesting/Trilinos/cmake/ctest/drivers
SetCTestConfiguration:ConfigureCommand:"/projects/sems/install/rhel7-x86_64/sems/utility/cmake/3.10.3/bin/cmake" "-GUnix Makefiles" "/data/nightlyTesting/Trilinos/cmake/ctest/drivers"
Configure project
Configure with command: "/projects/sems/install/rhel7-x86_64/sems/utility/cmake/3.10.3/bin/cmake" "-GUnix Makefiles" "/data/nightlyTesting/Trilinos/cmake/ctest/drivers"
Run command: "/projects/sems/install/rhel7-x86_64/sems/utility/cmake/3.10.3/bin/cmake" "-GUnix Makefiles" "/data/nightlyTesting/Trilinos/cmake/ctest/drivers"
-- TDD_FORCE_INNER_CMAKE_INSTALL='1'
-- ENV_TRIBITS_TDD_USE_SYSTEM_CTEST='1'
-- TRIBITS_TDD_USE_SYSTEM_CTEST='1'
CMake Error at /data/nightlyTesting/Trilinos/cmake/tribits/core/utils/MessageWrapper.cmake:45 (INCLUDE):
  INCLUDE could not find load file:

    /core/utils/GlobalSet.cmake
Call Stack (most recent call first):
  /data/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsGeneralMacros.cmake:42 (INCLUDE)
  /data/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsConfigureCTestCustom.cmake:40 (INCLUDE)
  /data/nightlyTesting/Trilinos/cmake/tribits/dashboard_driver/TribitsDriverCMakeLists.cmake:76 (include)
  CMakeLists.txt:19 (include)
```

**Comment by jhux2** [comment]
This is also reported in issue #4796.

**Comment by jhux2** [comment]
Closing in favor of #4796.
