### ISSUE TITLE
Setting kokkos-ndevices in the ctest. 

### ISSUE THREAD

**Issue by kyungjoo-kim** [trilinos/Trilinos#4812]
A question or a suggestion.

When we run ctest, we in general use 4 mpi ranks. In cuda test (assuming we use ride or white), it would be better if we use ``--kokkos-ndevices=4`` as it can reduce the testing time on cuda. When I just run the ctest, it does not append the kokkos option. Is there anyway to append the option in nightly tests ? This can also reduce time over failures in PR testing. 

@bartlettroscoe @trilinos/framework @crtrott

**Comment by mhoemmen** [comment]
@kyungjoo-kim Do you want to append the option in _all_ tests, or just a certain set of tests?

**Comment by bartlettroscoe** [comment]
Since it seems likely that we can't apply `--kokkos-ndevices=4` to **all** Trilinos tests but only tests that use Kokkos, we would likely need to work this as part of the larger issue #2422 which will address managing running tests to efficiently using hardware, including GPUs, effectively (Kitware is working on that basic issue but there is a lot of work to do).

But for now, if you want to just make a few tests run faster, you can use:

```
-D <fullTestName>_EXTRA_ARGS="--kokkos-ndevices=4" \
```

Until we have a way in TriBITS to tag these tests automatically, it would be a lot of work to add this argument to every test that uses Kokkos and runs on the GPU correctly.

See:

* https://tribits.org/doc/TribitsDevelopersGuide.html#adding-extra-commandline-arguments-externally-tribits-add-test

Otherwise, the cost of nightly CUDA tests is not so terrible since these run offline. This would be a bigger deal for PR testing but there are much larger issues there.

**Comment by kyungjoo-kim** [comment]
Thanks for the explanation. It was just a thought as a computation node in general has multiple gpus. Closing this issue.
