### ISSUE TITLE
MueLu: MMKernel test failing on Cuda

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#5025]
## Bug Report
@trilinos/muelu @jjellio 

### Description
The MMKernelDriver is not compiling with Cuda enabled on geminga.
This seems to be caused by raw openmp calls in the driver, maybe adding appropriate guards would fix these?

### Steps to Reproduce
Look at [this build](https://testing.sandia.gov/cdash/buildSummary.php?buildid=4960432) on geminga

**Comment by jjellio** [comment]
I can take a look at this, I don't know if that Driver was ever intended to for Cuda use.

The OpenMP can surely be guarded though

**Comment by jjellio** [comment]
@lucbv Curiously, this test will work on many Cuda machines, because the test beds use OpenBLAS for the system BLAS, which is compiled with OpenMP - so that shared library ends up pulling in the symbols to define the OpenMP stuff.

I suppose Geminga is using regular redhat lapack/blas installed through YUM or DNF, which doesn't use threads.

I'll push the change with a guard added, but on White, I cannot verify this will fix the problem on Geminga, since the white link line will have OpenMP libs on it. You'll just have to trust in the fact that I always fix things in one shot.

**Comment by lucbv** [comment]
@jjellio, I am happy that someone is looking at it. We will have to wait until tomorrow to see it pulled by the nightly tests but if something goes wrong we can always go back to it and fix some more.
Thanks for working on it.

**Comment by lucbv** [comment]
@jjellio the test is now building correctly on the nightly tests. Thanks for taking the time to fix it!
