### ISSUE TITLE
Framework: Autotester runs not reporting

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#5070]
#5067 #5066 

@trilinos/framework @jwillenbring @william76

**Comment by csiefer2** [comment]
RuntimeError: ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'sems-env'

**Comment by cgcgcg** [comment]
Ditto #5063

**Comment by william76** [comment]
FYI @prwolfe @jwillenbring

**Comment by william76** [comment]
@csiefer2 @cgcgcg  Paul sent out an email to the framework team this morning... It looks like there was an issue with the Jenkins jobs that the tester launches which run the tests.  He pushed in a fix this morning so that should sort things out.  <knock on wood>
He's out the rest of the day, but I'll check in on these PR's from time to time today.

**Comment by prwolfe** [comment]
@csiefer, is there anything outstanding on this or should we close it?

**Comment by csiefer** [comment]
@prwolfe 
unfortunately I'm not csiefer2 but csiefer.  :)

**Comment by prwolfe** [comment]
@csiefer - sorry about that, thanks for pinging me!
@csiefer2 -  is there anything outstanding on this or should we close it?

**Comment by prwolfe** [comment]
Closing as not answered for 4 months.
