### ISSUE TITLE
Piro: 'Rythmos' vs 'Rythmos Solver'

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#5079]
## Question
@trilinos/piro
@trilinos/rythmos

Can someone explain me the difference? It seems the two syntaxes are almost equivalent (mutatis mutandis), however, during some refactor in Albany, I came upon an example in which using `Rythmos Solver` causes an exception to be thrown inside some Thyra model evaluator that Rythmos creates, with a message sayng that both `W` and `W_op` are present, and that case is not supported. Switching the input file to `Rythmos` syntax works. The details are the same (integrator type, stepper, nonlinear solver (NOX)...).

So to make the question short: is there a reason why one should use the 'Rythmos' list syntax instead of 'Rythmos Solver' inside Piro (or viceversa)?

**Comment by mhoemmen** [comment]
OP's tags didn't take, so I'm retagging: @trilinos/piro @trilinos/rythmos

**Comment by bartgol** [comment]
Pinging in case some of the Rythmos folks did not see it yet.

**Comment by sconde** [comment]
Perhaps @ccober6, @rppawlo, @ikalash can comment?

**Comment by ikalash** [comment]
I think I noticed this at some point and had a discussion with @rppawlo about it, but can't remember now the details.  Roger, do you remember?

**Comment by rppawlo** [comment]
I don't remember the details. Tried to look through the git log, but didn't find much. At some point I think we decided to change the parameter list format but had a ton of code using the old format and left both around for backwards compatibility.

**Comment by ikalash** [comment]
When I commented, I was looking at the question about W_op vs. W, not the title of the issue .  I think "Rythmos Solver" is a wrapper around Rythmos.  I seem to remember that Rythmos Solver is more general than Rythmos - there are some things you can't call through Rythmos, but you can through the Rythmos Solver.  My guess is all the relatively new tests use Rythmos Solver, and one could switch all the tests to use it.  Alternatively, one could switch all the tests to Tempus, Rythmos's replacement; but that would be a more involved task.

**Comment by agsalin** [comment]
Yes, some history here. One of the lists (Rythmos I presume) was created early on for Piro to parse in order to set up a Rythmos solver. Later, Rythmos developed its own parameter parsing capability, so we created a sublist that could just be sent to Rythmos to parse itself. I think there are a few things needed by Piro still (invert mass matrix, matrix free options) that need to be a level higher than the sublist just passed to Rythmos to parse itself, so I expect the "Rythmos Solver" list has some things needed by Piro that Rythmos itself doesn't use.

Hope that helps explain why it got that way. Can definitely be cleaned/removed.

**Comment by ikalash** [comment]
@agsalin - thanks, what you wrote is consistent with my recollection.  I would say Rythmos Solver encompasses Rythmos.  Things like mass lumping / inversion you need Rythmos solver for, like Andy said.

**Comment by bartgol** [comment]
Thanks for the info. I'll go ahead and close.
