### ISSUE TITLE
Tpetra: Node should not call Kokkos::initialize (or finalize) if it was called externally

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#510]
@trilinos/tpetra @ndellingwood @aprokop @trilinos/muelu 

Node should _not_ call Kokkos::$EXECUTION_SPACE::finalize if $EXECUTION_SPACE was already initialized before Node's constructor got to it.  This should help prevent Kokkos::initialize being called after Kokkos::finalize.  That was always forbidden, but upcoming changes to Kokkos will actually throw an exception if this happens.

Use the same machinery that Tpetra::initialize uses to fix this issue.

**Comment by mhoemmen** [comment]
Note that this alone will not fix unit tests that will fail due to Kokkos::$EXECUTION_SPACE::initialize being called after Kokkos::$EXECUTION_SPACE::finalize.  One also needs to change the unit test main() function so that it initializes and finalizes Kokkos.  My changes to the TpetraCore_ExpBlockView unit test yesterday show how to do that.  (You can put the main() function right in the test.)

**Comment by mhoemmen** [comment]
Fix implemented, with lots of checks.  Debugging one failing Tpetra test with this fix now.

**Comment by mhoemmen** [comment]
Just pushed a fix.

**Comment by kddevin** [comment]
With commit 17ae6009451fa0ae2de8f493d3da0bd0fd117a5a, some Zoltan2 tests produce the  error message below.  The error message was not there before this commit.  Zoltan2 tests may still pass, if PASS is printed before the error is thrown, but if the error is thrown before printing PASS, the Zoltan2 tests will fail.
Is something new needed in test programs as a result of this change?  Zoltan2 does not use Kokkos directly, so it does not make any Kokkos calls from its tests.  Zoltan2 uses Kokkos only indirectly through Zoltan2's dependence on Tpetra.
Having a work-around or solution soon would be helpful, as we are seeing some tests fail only due to this problem.  Please advise.  Thanks.

terminate called after throwing an instance of 'std::logic_error'
  what():  /home/kddevin/code/Trilinos/packages/teuchos/kokkoscompat/src/KokkosCompat_ClassicNodeAPI_Wrapper.hpp:276:

Throw number = 1

Throw test that evaluated to true: count == 0 && nodeResponsibleForFinalizingExecutionSpace_ && ExecutionSpace::is_initialized ()

Kokkos::Compat::KokkosDeviceWrapperNode<ExecutionSpace=N6Kokkos6SerialE, MemorySpace=N6Kokkos9HostSpaceE > destructor: count == 0 and the Node is responsible for finalizing ExecutionSpace, but its destructor did not.  Please report this bug to the Tpetra developers.

**Comment by mhoemmen** [comment]
@kddevin also says:

> After some experimentation, it appears this error message is caused by commit 17ae6009451fa0ae2de8f493d3da0bd0fd117a5a for issue #510.  A checkout before this commit does not have the error message, while a checkout with this commit does have the error.

**Comment by mhoemmen** [comment]
Looking at zoltan2/test/partition/MultiJaggedTest.cpp now.  It _should_ be innocuous but it's not.  Putting explicit calls to Kokkos::initialize and Kokkos::finalize in main() doesn't help.

**Comment by mhoemmen** [comment]
@kddevin I wrote a Tpetra test that does the following:
```
for (int k = 0; k < numTimesToCreateMap; ++k) {
  Tpetra::Map map (...); // create new Map that implicitly creates a Node
  map.describe (...); // do something with the Map
}
```
The test passes just fine, with CUDA too.  This more or less imitates the way that the Zoltan2 tests create Tpetra::Map instances.  That makes me wonder whether Zoltan2 objects are creating Node instances on their own.

**Comment by mhoemmen** [comment]
@kddevin I found out that Zoltan2 tests may create Node instances on their own.  See lines 878 and 1032 of zoltan2/test/helpers/UserInputForTests.hpp (search for "new default_znode_t").  Fortunately, I think we can get rid of both instances.

**Comment by mhoemmen** [comment]
@kddevin When I changed Zoltan2's tests not to create Node instances explicitly, the tests passed (with CUDA too).  I'll commit this minor change to Zoltan2.  I'm running check-in tests now.

**Comment by mhoemmen** [comment]
My latest commit fixed this issue in Zoltan2.
