### ISSUE TITLE
Zoltan2 definition of part_t = int causes problems with ETI when GO != int

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#537]
@trilinos/zoltan2 @trilinos/tpetra 

Zoltan2 defines part_t (part numbers) to be int, consistent with MPI ranks.

For task mapping, we map MPI ranks to allocated cores; thus, all entities are labeled with part_t.  For some operations, we use Tpetra::Map<part_t, part_t>, Tpetra::CrsMatrix<double, part_t, part_t>, etc.  

When ETI is enabled and Tpetra_INST_INT_INT=OFF, the task mapping code will not link, as Tpetra doesn't instantiate Tpetra::Map<part_t, part_t>, Tpetra::Import<part_t, part_t>, etc.

Possible solutions are below; are there others?
1.  Always require LocalOrdinal=int and GlobalOrdinal=int in ETI when Zoltan2 is enabled.  This solution would not be popular with the folks trying to reduce code size for Sierra.  Sierra needs Zoltan2.
2.  Template Tpetra classes on lno_t and gno_t, even though part_t would be more natural and self-documenting; cast part_t data to gno_t or lno_t in the task mapping code whenever needed for Tpetra.  This solution would be awkward and less descriptive in the code, as it is needed only to satisfy ETI.  But it may be necessary.
3.  Change part_t to be GlobalOrdinal.  This solves half the ETI problem, but it breaks backward compatibility, as Zoltan2's interface returns values of type part_t (e.g., PartitioningSolution.getPartListView()).

Other ideas, anyone?  Meanwhile, I'll start looking at the 2nd idea.

**Comment by kddevin** [comment]
A fourth option:

4.  Replace the Tpetra machinery with our own communication.  This approach will be more work to write, but may run faster since it will be specialized to our needs (i.e., building only what we need instead of everything that Tpetra matrices need in general).  

@mndevec Did you say the Tpetra steps in getCoarsenedPartGraph were slow?  Maybe this approach would speed them up.

**Comment by mhoemmen** [comment]
> Replace the Tpetra machinery with our own communication.

What do you folks actually need?  I've been thinking for a while about separating out Tpetra classes into "communication operations" and "solver / numerical methods operations."  For example, most use of Vector for communication doesn't need norms or dot products, as far as I can tell; it just needs to push integer entries around and add them together.  That suggests Vector could have a base class that communicates, and a subclass that does solver stuff.

Just, please don't reroll your own neighborhood collectives.  Use MPI 3's if you don't want to use Tpetra's.  (Zoltan2 already rerolls MPI_Alltoallv, which made me sad when I saw it.)

**Comment by mhoemmen** [comment]
> The problem is that we want to do things with LO,GO=part_t,part_t=int,int, where part_t is an identifier for a part in a partition. In this case, we are collecting a distributed weighted graph into a global graph stored on every processor. Each processor starts with a not-necessarily-unique set of vertices and weighted edges, which it inserts into a matrix (insertGlobalValues). Then we let FillComplete and Import do the magic of combining the vertices/edges and copying the matrix to each processor.

  1. This means you make a Tpetra::CrsMatrix<int, LO, GO>, right?
  2. Must LO and GO be the same as part_t?  Could you, for example, use the default LO and GO, as long as they are big enough?  I ask because Tpetra already instantiates Vector, etc. for Scalar=int, because some packages use this to communicate MPI process ranks.
  3. Do you need to do anything else with this matrix, other than inserting weighted edges and letting fillComplete / Import communicate and combine them?  For example, do you need to do sparse matrix-vector products, or compute a matrix norm?

What I mean by (3), is that we could split Tpetra::CrsMatrix into 
  - a subclass that only lets users change the matrix and communicate (DistObject subclass), and
  - a class with the current full interface, that does both communication and computation.

> Yes, it is sad that Teuchos::Comm doesn't provide AlltoAllv.

Rather, it's sad that people didn't feel empowered to ask to change Teuchos::Comm to support what they wanted :-)  I'm hoping things are different now.

**Comment by kddevin** [comment]
A fifth option:
-  Enhance the Zoltan directory to enable accumulation of user data (ie., contributions from several processors) and operations on user data (sum, max, min, etc.), and use that for assembling the graph.

**Comment by kddevin** [comment]
Solution here will benefit #223
