### ISSUE TITLE
Make Trilinos' use of ETI consistent

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#546]
Trilinos wants to move to ETI to be enabled by default. This requires that all packages use the same ETI system. Currently there are 3, maybe more in Tpetra, Muelu and ifpack2. The goal is to make sure that turning on ETI will not make obscure builds fail due to combining packages that aren't normally during  our testing.

**Comment by tawiesn** [comment]
One must not forget ETI in Stokhos...
In MueLu, (most) ETI files are automatically generated through CMakeLists.txt. Be aware, that in MueLu we can switch between the Tpetra inspired ETI system (which splits the cpp files and generates one per configuration) or the Ifpack2 inspired system (which produces one cpp file for each class containing all instantiations for all enabled configurations). By default we use the second approach as it is easier to handle. For MueLu we could not observe an advantage of splitting the cpp files (smaller libraries, faster compilation), probably because of the lack of ETI in Xpetra. The files in the muelu-interface sub-library are not covered by the automatic MueLu ETI system so far. We just do it "by hand". We've decided not to migrate these files to the new ETI system as long as it is not clear what is the right (hopefully) unique ETI system in Trilinos.

**Comment by mhoemmen** [comment]
> Currently there are 3, maybe more in Tpetra, Muelu and ifpack2.

Thyra has its own system that lives in Teuchos.  The two interact (in sometimes less than fortunate ways) in Thyra's Tpetra wrappers, and downstream.  I faced this issue when I wanted to add a new Scalar type (__float128) to Tpetra.

**Comment by mhoemmen** [comment]
@trilinos/tpetra @trilinos/ifpack2 @trilinos/muelu

**Comment by bartlettroscoe** [comment]
> Trilinos wants to move to ETI to be enabled by default. This requires that all packages use the same ETI system. 

I don't think moving the ETI means needing to have a consistent system for ETI across all of the packages.  Instead, each package just needs to generate explicit instantiations for the requested types.   That is it.  Users and people at the framework level should not care how an individual package decides to do ETI, that is there business.   And some packages have special considerations that would make a general ETI system hard to create.

Now that there top Trilinos-level configuration options for enabling or disabling `float`, `complex<float>`, and `complex<double>` (see #362).  (We can also add other options for more exotic types or a more general type request system as well but starting with these types would satisfy 99% of our important customers.)

Therefore, I have created the new issue #1388 to push the usage of ETI, but not with a consistent system.

Therefore, I am putting this issue into review and suggesting that it be closed.  (Not because a consistent system would not be nice, it is just because no one is going to stand up and take this on and we don't really need it to provide reduction in build and rebuild times.)

**Comment by bartlettroscoe** [comment]
> Thyra has its own system that lives in Teuchos. The two interact (in sometimes less than fortunate ways) in Thyra's Tpetra wrappers, and downstream. I faced this issue when I wanted to add a new Scalar type (__float128) to Tpetra.

But if you stick with top-level configure options, this is not a problem.  We should not try to bother with partial instantation sets across packages.  That will be a mess.
