### ISSUE TITLE
Tpetra:  TpetraCore_­AddProfiling_­UnitTests_­MPI_­4 randomly timing out in atdm waterman builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5525]
## Bug Report
CC: @trilinos/tpetra, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe, @fryeguy52 
 
## Next Action Status

PR #5626  merged on 8/1/2019 should fix.  Next: Watch dashboard and close if no failures by 9/1/2019 ...
 
## Description
 
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=8&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=cuda-9.2&field3=buildname&compare3=63&value3=opt&field4=buildname&compare4=64&value4=shared&field5=testname&compare5=61&value5=TpetraCore_AddProfiling_UnitTests_MPI_4&field6=site&compare6=61&value6=waterman&field7=buildstarttime&compare7=84&value7=2019-07-15T04%3A01%3A00UTC&field8=buildstarttime&compare8=83&value8=2019-06-15T04%3A01%3A00UTC) the test:
* TpetraCore_AddProfiling_UnitTests_MPI_4

is randomly timing out the builds:
* Trilinos-atdm-waterman-cuda-9.2-opt
* Trilinos-atdm-waterman_­cuda-9.2_­fpic_­static_­opt

## Current Status on CDash

The current status of these tests/builds for the current testing day can be found [here](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=8&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=cuda-9.2&field3=buildname&compare3=63&value3=opt&field4=buildname&compare4=64&value4=shared&field5=testname&compare5=61&value5=TpetraCore_AddProfiling_UnitTests_MPI_4&field6=site&compare6=61&value6=waterman&field7=buildstarttime&compare7=84&value7=today&field8=buildstarttime&compare8=83&value8=yesterday)

## Steps to Reproduce

One should be able to reproduce this failure on waterman as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for waterman are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-waterman-cuda-9.2-opt
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Tpetra=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -n 20 ctest -j20
```

**Comment by bartlettroscoe** [comment]
FYI: As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug&field2=testname&compare2=61&value2=TpetraCore_AddProfiling_UnitTests_MPI_4&field3=site&compare3=61&value3=sems-rhel7&field4=buildstarttime&compare4=84&value4=2019-08-01T04%3A01%3A00UTC&field5=buildstarttime&compare5=83&value5=2019-07-02T04%3A01%3A00UTC), we are also seeing this test randomly timing out in the build:

* Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug

failing 7 out of the last 30 days.

The failure showed:

```
5. Tpetra_AddProfiling_std_complex0double0_int_longlong_Kokkos_Compat_KokkosCudaWrapperNode_different_col_maps_UnitTest ... Running "different col maps" add test on 4 MPI ranks.
[ascicgpu14:10216] *** An error occurred in MPI_Allreduce
[ascicgpu14:10216] *** reported by process [3026321409,3]
[ascicgpu14:10216] *** on communicator MPI_COMM_WORLD
[ascicgpu14:10216] *** MPI_ERR_IN_STATUS: error code in status
[ascicgpu14:10216] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[ascicgpu14:10216] ***    and potentially your MPI job)
```

**Comment by brian-kelley** [comment]
#5626 should fix both of these. At least, I think the timeouts are a manifestation of the matrix being wrong, and making the all-reduce deadlock.

**Comment by brian-kelley** [comment]
#5626 was merged. I'll close this issue tomorrow after checking that those nightly tests passed.

**Comment by bartlettroscoe** [comment]
> I'll close this issue tomorrow after checking that those nightly tests passed.

@brian-kelley, actually, since these tests are randomly failing we need to let them run for a long time before closing the issue.

**Comment by bartlettroscoe** [comment]
[This query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-09-01&end=2019-09-30&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=62&value2=Trilinos-atdm-mutrino-intel-opt-openmp-HSW&field3=testname&compare3=61&value3=TpetraCore_AddProfiling_UnitTests_MPI_4&field4=status&compare4=61&value4=failed) shows this test failed 4 times and [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-09-01&end=2019-09-30&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=TpetraCore_AddProfiling_UnitTests_MPI_4&field3=status&compare3=61&value3=failed&field4=testoutput&compare4=97&value4=cudaGetDeviceCount.*cudaErrorUnknown) shows that every failure showed:

```
p=0: *** Caught standard std::exception of type 'std::runtime_error' :
 
  cudaGetDeviceCount( & m_cudaDevCount ) error( cudaErrorUnknown): unknown error /home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug/SRC_AND_BUILD/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:204
  Traceback functionality not available
```

This seems to be some system problem with the node on 'waterman1' and not a code problem (see https://github.com/kokkos/kokkos/issues/2377).

In fact, the last time we saw any error that looks like it could be a code-related error was back in 2019-08-01 as shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-08-01&end=2019-09-30&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=TpetraCore_AddProfiling_UnitTests_MPI_4&field3=status&compare3=61&value3=failed&field4=testoutput&compare4=95&value4=%60View%20bounds%20error%20of%20view%20FixedHashTable%3A%3Apairs%60%20failed.) showing:

```
5. Tpetra_AddProfiling_std_complex0double0_int_longlong_Kokkos_Compat_KokkosCudaWrapperNode_different_col_maps_UnitTest ... Running "different col maps" add test on 4 MPI ranks.
:0: : block: [0,0,0], thread: [0,226,0] Assertion `View bounds error of view FixedHashTable::pairs` failed.
...
[ascicgpu14:40327] *** Process received signal ***
[ascicgpu14:40327] Signal: Floating point exception (8)
[ascicgpu14:40327] Signal code: Integer divide-by-zero (1)
[ascicgpu14:40327] Failing at address: 0x7fa90de352da
```

But that was 2 months ago.  When this issue was first created, the tests were timing out almost every day as shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=8&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=cuda-9.2&field3=buildname&compare3=63&value3=opt&field4=buildname&compare4=64&value4=shared&field5=testname&compare5=61&value5=TpetraCore_AddProfiling_UnitTests_MPI_4&field6=site&compare6=61&value6=waterman&field7=buildstarttime&compare7=84&value7=2019-07-15T04%3A01%3A00UTC&field8=buildstarttime&compare8=83&value8=2019-06-15T04%3A01%3A00UTC). 

Therefore, it looks like PR #5626 merged on 8/1/2019 fixed the problem.

Closing as complete.
