### ISSUE TITLE
Panzer:  PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_4 failing randomly on ATDM waterman build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5526]
## Bug Report
CC: @trilinos/panzer, @mperego (Trilinos Discretizations Product Lead), @bartlettroscoe, @fryeguy52
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman_cuda-9.2_shared_opt&field2=testname&compare2=61&value2=PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_4&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=2019-07-15T04%3A01%3A00UTC&field5=buildstarttime&compare5=83&value5=2019-06-15T04%3A01%3A00UTC) the tests:
* PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_4

is failing in the build:
* Trilinos-atdm-waterman_cuda-9.2_shared_opt

## Current Status on CDash

A 2 current week history of the build/test can be found [here](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman_cuda-9.2_shared_opt&field2=testname&compare2=61&value2=PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_4&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=today&field5=buildstarttime&compare5=83&value5=2%20weeks%20ago)

## Steps to Reproduce

One should be able to reproduce this failure on waterman as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for waterman are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#<system-section-name>

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-waterman_cuda-9.2_shared_opt
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Panzer=ON \
 $TRILINOS_DIR
$ make NP=16
$ <system-run-tests-command>
```

**Comment by bartlettroscoe** [comment]
FYI: As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-09-08&end=2019-10-08&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_4&field3=status&compare3=61&value3=failed&field4=testoutput&compare4=96&value4=srun%3A%20error%3A%20Slurm%20job%20.*%20has%20expired) this test failed 4 times between 2019-09-08 and 2019-10-08:


Site | Build Name | Test Name | Status | Time | Proc Time | Details | Build Time | Processors
-- | -- | -- | -- | -- | -- | -- | -- | --
waterman | Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug | PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_4 | Failed | 9s 380ms | 37s 520ms | Completed (Failed) | 2019-09-25T07:25:50 MDT | 4
waterman | Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug | PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_4 | Failed | 16s 90ms | 1m 4s 360ms | Completed (Failed) | 2019-09-24T03:04:19 MDT | 4
waterman | Trilinos-atdm-waterman-cuda-9.2-release-debug | PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_4 | Failed | 9s 350ms | 37s 400ms | Completed (Failed) | 2019-09-23T09:31:38 MDT | 4
waterman | Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug | PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_4 | Failed | 9s 140ms | 36s 560ms | Completed (Failed) | 2019-09-17T03:05:10 MDT | 4

And as shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-09-08&end=2019-10-08&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_4&field3=status&compare3=61&value3=failed&field4=testoutput&compare4=97&value4=terminate%20called%20after%20throwing%20an%20instance%20of&field5=testoutput&compare5=97&value5=cudaGetDeviceCount.*m_cudaDevCount.*error.*cudaErrorUnknown.*unknown%20error) all of the failures contain output like:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaGetDeviceCount( & m_cudaDevCount ) error( cudaErrorUnknown): unknown error /home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug/SRC_AND_BUILD/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:204
Traceback functionality not available
```

However, as shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-09-08&end=2019-10-08&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=status&compare2=61&value2=failed&field3=testoutput&compare3=97&value3=terminate%20called%20after%20throwing%20an%20instance%20of&field4=testoutput&compare4=97&value4=cudaGetDeviceCount.*m_cudaDevCount.*error.*cudaErrorUnknown.*unknown%20error) there were mass test failures in those builds on those days as described in [ATDV-205](https://sems-atlassian-srn.sandia.gov/browse/ATDV-205) and https://github.com/kokkos/kokkos/issues/2377.  

Therefore, it does not look like there has been any failures of this test in the last month in all builds.

When this test started failing in the 5 failures originally reported above shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman_cuda-9.2_shared_opt&field2=testname&compare2=61&value2=PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_4&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=2019-07-15T04%3A01%3A00UTC&field5=buildstarttime&compare5=83&value5=2019-06-15T04%3A01%3A00UTC) it failed due to failures like:

```
mpiexec noticed that process rank 3 with PID 0 on node waterman10 exited on signal 11 (Segmentation fault).
```

or 

```
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
[waterman2:39206] *** Process received signal ***
[waterman2:39206] Signal: Aborted (6)
[waterman2:39206] Signal code:  (-6)
```

as shown in [this Test Output query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman_cuda-9.2_shared_opt&field2=testname&compare2=61&value2=PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_4&field3=site&compare3=61&value3=waterman&field4=testoutput&compare4=97&value4=(terminate%20called%20after%20throwing%20an%20instance%20of%7Csignal%2011%20.*Segmentation%20fault..*)&field5=buildstarttime&compare5=84&value5=2019-07-15T04%3A01%3A00UTC&field6=buildstarttime&compare6=83&value6=2019-06-15T04%3A01%3A00UTC).  So the original errors are not seen at least in the last month.

Therefore, I think this test is fixed so I will close this issue.

**Comment by bartlettroscoe** [comment]
As per above, closing as complete.

**Comment by bartlettroscoe** [comment]
As per above, closing as complete.
