### ISSUE TITLE
TpetraCore_ImportExport2_UnitTests_MPI_4 failing in build Trilinos-atdm-waterman-cuda-9.2-opt starting before 2019-07-15

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5528]
## Bug Report
CC: @trilinos/tpetra, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe, @fryeguy52
 
<Checklist>
<???: Add label "ATDM">
<???: Add label "bug"?>
<???: Add label for affected packages (e.g. "MueLu", "Tpetra", "Kokkos", etc.)>
<???: Add milestone "Initial cleanup of new ATDM builds of Trilinos" or "Keep promoted ATDM builds of Trilinos clean">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-opt&field2=testname&compare2=61&value2=TpetraCore_ImportExport2_UnitTests_MPI_4&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=2019-07-15T04%3A01%3A00UTC&field5=buildstarttime&compare5=83&value5=2019-06-15T04%3A01%3A00UTC) the test:
* TpetraCore_ImportExport2_UnitTests_MPI_4

is randomly failing in the build:
* Trilinos-atdm-waterman-cuda-9.2-opt

```
[waterman3:133082] *** An error occurred in MPI_Allreduce
[waterman3:133082] *** reported by process [617218049,0]
[waterman3:133082] *** on communicator MPI_COMM_WORLD
[waterman3:133082] *** MPI_ERR_OTHER: known error not in list
[waterman3:133082] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[waterman3:133082] ***    and potentially your MPI job)
```

## Current Status on CDash

A current 2 week history of this build/test can be found [here](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-opt&field2=testname&compare2=61&value2=TpetraCore_ImportExport2_UnitTests_MPI_4&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=today&field5=buildstarttime&compare5=83&value5=2%20weeks%20ago)

## Steps to Reproduce

One should be able to reproduce this failure on waterman as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for waterman are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-waterman-cuda-9.2-opt
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Tpetra=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -n 20 ctest -j20
```

**Comment by bathmatt** [comment]
@kddevin @srajama1 This is a high priority issue for the EMPIRE team that was brought up at todays meeting, tagging another issue as well

**Comment by fryeguy52** [comment]
When this fails it looks like:
```
[waterman3:133082] *** An error occurred in MPI_Allreduce
[waterman3:133082] *** reported by process [617218049,0]
[waterman3:133082] *** on communicator MPI_COMM_WORLD
[waterman3:133082] *** MPI_ERR_OTHER: known error not in list
[waterman3:133082] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[waterman3:133082] ***    and potentially your MPI job)
```

It did this 3 times in a week from 7/7 to 7/14 but I have not seen it fail since then.  
@bathmatt it sounds like you are still seeing this?

**Comment by bartlettroscoe** [comment]
CC: @bathmatt 

@trilinos/tpetra, @kddevin, @srajama1 

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-07-01&end=2019-10-03&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-opt&field2=testname&compare2=61&value2=TpetraCore_ImportExport2_UnitTests_MPI_4&field3=site&compare3=61&value3=waterman), this test has not failed since 7/14/2019.  Did something change in Trilinos to fix this test or is this test passing for the last 2.5 months dumb luck?

**Comment by srajama1** [comment]
I think it is the later, otherwise whoever fixed it would have closed this :)

**Comment by bartlettroscoe** [comment]
@kddevin, the 2 weeks of history linked to [above](https://github.com/trilinos/Trilinos/issues/5528#issue-468224090) in the section "Current status on CDash" shown [here](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-opt&field2=testname&compare2=61&value2=TpetraCore_ImportExport2_UnitTests_MPI_4&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=today&field5=buildstarttime&compare5=83&value5=2%20weeks%20ago) showed all passing for this test in this build.  But since this test was randomly failing, it is wise to look over more builds.  [This query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-12-14&end=2020-01-14&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=groupname&compare2=62&value2=Experimental&field3=testname&compare3=61&value3=TpetraCore_ImportExport2_UnitTests_MPI_4) shows 1837 runs of this test across all of the non-Experimental ATDM Trilinos builds over the last about 60 days and shows just 5 falures:


Site | Build Name | Test Name | Status | Time | Proc Time | Details | Build Time | Processors
-- | -- | -- | -- | -- | -- | -- | -- | --
sems-rhel7 | Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug | TpetraCore_ImportExport2_UnitTests_MPI_4 | Failed | 10m 170ms | 40m 680ms | Completed (Timeout) | 2019-12-09T03:33:13 MST | 4
sems-rhel7 | Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug | TpetraCore_ImportExport2_UnitTests_MPI_4 | Failed | 10m 190ms | 40m 760ms | Completed (Timeout) | 2019-12-08T03:33:12 MST | 4
sems-rhel7 | Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug | TpetraCore_ImportExport2_UnitTests_MPI_4 | Failed | 10m 200ms | 40m 800ms | Completed (Timeout) | 2019-11-23T03:33:14 MST | 4
sems-rhel7 | Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug | TpetraCore_ImportExport2_UnitTests_MPI_4 | Failed | 10m 150ms | 40m 600ms | Completed (Timeout) | 2019-11-22T03:33:13 MST | 4
sems-rhel7 | Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug | TpetraCore_ImportExport2_UnitTests_MPI_4 | Failed | 10m 240ms | 40m 960ms | Completed (Timeout) | 2019-11-14T03:33:15 MST | 4

Those failures don't show any error output, they just timeout at 10 minutes while running different numbers of unit tests.  Those failures appear to be unrelated.  But the last of those failures was over one month ago on 2019-12-09.

I think it is safe to close this as complete.

Thanks for checking up on this!
