### ISSUE TITLE
Build failures in ATDM cuda 9.2 "pt" builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5599]
## Bug Report
CC: @trilinos/rol, @trilinos/panzer  @trilinos/domi @trilinos/shylu @trilinos/stokhos @trilinos/trilinoscouplings 

@rppawlo @kddevin @mperego @srajama1  @bartlettroscoe 
 
<Checklist>
<???: Add label "ATDM">
<???: Add label "bug"?>
<???: Add label for affected packages (e.g. "MueLu", "Tpetra", "Kokkos", etc.)>
<???: Add milestone "Initial cleanup of new ATDM builds of Trilinos" or "Keep promoted ATDM builds of Trilinos clean">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=66&value2=-pt&field3=buildstarttime&compare3=83&value3=2019-07-01) the builds:
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug-pt

have been failing since 2019-07-15.  This timing is consistent with merge of #5527.  The failure is cause nearly 300 tests to not be run in the following packages:
* Domi
* Panzer
* Piro
* ROL
* ShyLU_DD
* Stokhos
* TrilinosCouplings

build errors can be found [here](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=5370473)

## Current Status on CDash

The current status of these builds for the current testing day can be found [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=66&value2=-pt&field3=buildstarttime&compare3=83&value3=yesterday&field4=buildstarttime&compare4=84&value4=today)

## Steps to Reproduce

One should be able to reproduce this failure on ride or white as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for ride or white are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Rol=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by bartlettroscoe** [comment]
@rppawlo (Trilinos Nonlinear Solvers Product Area Lead)
@kddevin (Trilinos Data Services Product Area Lead)
@mperego (Trilinos Discretizations Product Area Lead)
@srajama1 (Trilinos Linear Solvers Product Area Lead)

These `pt` builds enable all Primary Tested packages, beyond what ATDM needs.  We set up and monitor these builds as a broader service to other Trilinos customers like Sierra (which is the same reason we are running Anasazi tests, for example).  If you have a desire to keep these builds running, then we need to resolve the build errors.  Otherwise, we can remove the `client: ATDM` label and relegate these builds to the `Experimental` and let them run but not actively monitor and triage them. Or, we could just turn them off.  But note that these may be the only automated CUDA and CUDA+RDC builds testing these other non-ATDM packages.  (NOTE: By definition, at least one SNL Trilinos customer is using one of the PT packages as was determined in [TRIL-59](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-59)).  So please let us know what you want us to do with these packages.  (We are looking at ways to reduce our time maintaining builds of Trilinos in a way that will not negatively impact ATDM.)

**Comment by fryeguy52** [comment]
@bartlettroscoe can any of these be closed?

#3543 "ROL tests failing in targeted CUDA PR build Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt"

#4551 "New STKUnit test failing in ATDM CUDA PT build on white"

#3749 "TrilinosCouplings build and test failures in the build Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt starting 2018-10-24"

#4042 "Zoltan test diff failures in targeted CUDA PR build Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt"

**Comment by bartlettroscoe** [comment]
CC: @mhoemmen 

@jfrye asked:

> @bartlettroscoe can any of these be closed?

Since these are failures that are almost guaranteed to bite at some point (since GO=int is going away soon), we should keep these issues open.  But we might just remove the `client: ATDM` label and wash out hands of them and these `-pt` builds.  Some of those issue have been open for nearly a year.

**Comment by bartlettroscoe** [comment]
No response from anyone in 10 days so we will remove monitoring of these builds and all test failures associated with them.  That should remove about 5 GitHub issues from our ATDM bugs list.

**Comment by etphipp** [comment]
FYI, thanks to the hard work of @mhoemmen and @tjfulle, the Stokhos build failures were fixed.  I also fixed the TrilinosCouplings/FENL failures since I maintain that example.

**Comment by bartlettroscoe** [comment]
Eventually all of these build errors will need to be fixed as global ordinal int is going away.

**Comment by bartlettroscoe** [comment]
Defects with Primary tested code not currently used by ATDM is not really an ATDM issue so I am removing the "client: ATDM" label to get this off our list of active issues.
