### ISSUE TITLE
Panzer: Memory access bug

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#5636]
## Bug Report
@trilinos/panzer 

@seamill this is yours

### Description

In this file
Panzer_LocalPartitioningUtilities.cpp
you have a memory access bug, not sure what it is supposed to be doing but 

around line 360 you do 

```

   for(LO partition=0;partition<num_partitions;++partition){

      // Make sure end of partition maxes out at num_owned_cells
      const LO partition_end_index = std::min(partition_start_index + splitting_size, num_owned_cells);

      partition_cells.resize(partition_end_index - partition_start_index,-1);
      for(int i=partition_start_index;i<partition_end_index;++i){
        partition_cells[i] = i;
      }

```

partition_cells.size() is less values of i is partition_start_index > 0

Found with address sanitizer..

**Comment by bathmatt** [comment]
@rppawlo @eric-c-cyr

**Comment by seamill** [comment]
Ha, I remember this one. @bathmatt Why are you using ghosted worksets in EMPIRE? Maybe the L2 projection... I'll fix this.

**Comment by seamill** [comment]
@bathmatt If you want a quick fix on the empire side, you should just be able to set the workset size to -1 (== pazer::WorksetSizeType::ALL_ELEMENTS). The issue here is we're trying to partition a workset containing connectivity information, and doing it poorly (hasn't been setup yet). If you include all elements in the workset (like EMPIRE-Fluid does), you won't have this issue. This is currently being fixed in #5236, but I can put in a quick fix before that gets pushed.

**Comment by bathmatt** [comment]
I'm not trying to use it, just ran the unit tests and found it

**Comment by seamill** [comment]
Which unit tests?

**Comment by bathmatt** [comment]
380:PanzerDiscFE_LocalMesh_Tests_MPI_1
