### ISSUE TITLE
EpetraExt HDF5 interface fails at runtime with HDF5 1.10

### ISSUE THREAD

**Issue by bavier** [trilinos/Trilinos#566]
With Trilinos 12.6.3 configured with EpetraExt and HDF5 1.10.0, the `epetraext/example/inout/HDF5_IO.cpp` example fails with the following output:

```
Writing objects to HDF5 file myfile.h5...

HDF5-DIAG: Error detected in HDF5 (1.10.0) MPI-process 0:
  #000: H5D.c line 123 in H5Dcreate2(): not a datatype ID
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.0) MPI-process 0:
  #000: H5D.c line 375 in H5Dget_space(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.0) MPI-process 0HDF5-DIAG: Error detected in HDF5 (1.10.0) MPI-process 3:
  #000: H5D.c line 123 in H5Dcreate2(): not a datatype ID
    major: Invalid arguments to routine
HDF5-DIAG: Error detected in HDF5 (1.10.0) MPI-process 2:
  #000: H5D.c line 123 in H5Dcreate2(): not a datatype ID
    major: Invalid arguments to routine
HDF5-DIAG: Error detected in HDF5 (1.10.0) MPI-process 1:
  #000: H5D.c line 123 in H5Dcreate2(): not a datatype ID
    major: Invalid arguments to routine
...
```

HDF5 1.10 changed the definition of its `hid_t` type: https://www.hdfgroup.org/HDF5/doc/ADGuide/Changes.html

It seems there are a few places in the EpetraExt interface that use the `int` type, which worked with HDF5 1.8, but is no longer appropriate.  Better is to use the `hid_t` type directly, which the attached patch does.
[trilinos-epetraext-hdf5-1.10-compat.patch.txt](https://github.com/trilinos/Trilinos/files/425638/trilinos-epetraext-hdf5-1.10-compat.patch.txt)

**Comment by mhoemmen** [comment]
Just to summarize for other readers: The release notes (https://www.hdfgroup.org/HDF5/doc/ADGuide/Changes.html) suggest that hid_t has been around for a while, and was already in use as "the type . . . for all HDF5 identifiers" before 1.10.0.  The change is that hid_t was a 32-bit type before, and is now a 64-bit type.

@bavier It sounds like the only way this could break backwards compatibility, is if HDF5 at one time used int explicitly for HDF5 identifiers, instead of the hid_t typedef.  Would you happen to know if this is the case, and if so, the last version of HDF5 that did so?

**Comment by bavier** [comment]
@mhoemmen The earliest version of hdf5 that EpetraExt is API compatible with is 1.8.0 (e.g. number of arguments to H5Gcreate).  I was able to successfully build EpetraExt against that version and run the HDF5_IO.cpp example with this patch.
