### ISSUE TITLE
Tpetra::MatrixMatrix::Add: Why is setUnion branch commented out?

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#5774]
## Question
@trilinos/muelu @trilinos/tpetra @vbrunini 

In the implementation of `Tpetra::MatrixMatrix::Add`, in `TpetraExt_MatrixMatrix_def.hpp`, [Line 1026](https://github.com/trilinos/Trilinos/blob/514bfb9db3caed9fd1854b96f98349eba1465952/packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp#L1026) comments out the branch that optimizes by using `Import::setUnion`.  Is there something wrong with that branch?  What happened there?  The code just does an `#if 0` without comment.

**Comment by lucbv** [comment]
@mhoemmen it looks like you did this and [here](https://github.com/trilinos/Trilinos/commit/d31b8c58426c96dc14fe539033c775f65919617d) is the commit with some explanations

**Comment by mhoemmen** [comment]
@lucbv wrote:
> it looks like you did this and [here](https://github.com/trilinos/Trilinos/commit/d31b8c58426c96dc14fe539033c775f65919617d) is the commit with some explanations

Oops -- thanks for doing the research for me ;-) Does MueLu actually call this function, ever?  It turns out that we will need it for something else.

**Comment by lucbv** [comment]
@mhoemmen yes MueLu is using it in `PetrovGalerkin`, `RAPShift`, `RefMaxwell` and in `SchurComplementFactory`.

**Comment by mhoemmen** [comment]
begone autobot

**Comment by brian-kelley** [comment]
@lucbv Since the codepath in question can't work with C passed in as RCP-by-value, and was removed in 75333e4ed9915, is there anything left to do for this issue? If we want to replace calls to this ``TpetraExt::MatrixMatrix::Add()`` with the one of the Kokkos-ified versions (``TpetraExt::MatrixMatrix::add()``) in MueLu, that could probably be its own issue.
