### ISSUE TITLE
Tpetra/Kokkos: Can I select an execution space at initialization/runtime?

### ISSUE THREAD

**Issue by DABH** [trilinos/Trilinos#5942]
I compiled Trilinos with MPI, CUDA, OpenMP all enabled.

I set things up in my program by creating a Tpetra::ScopeGuard.

Based on this as mentioned in https://github.com/kokkos/kokkos/wiki/Initialization , Kokkos seems to pick CUDA as the default execution space.

Is it possible to override this by passing a flag to my program or changing something in my C++ code?  E.g. I'd like to tell Kokkos to use OpenMP even though CUDA is available.

Or is the only way to achieve this linking against a Trilinos that was built without CUDA support?

Thanks!

**Comment by ndellingwood** [comment]
Great to see you're picking up Kokkos so quickly :)

> Is it possible to override this by passing a flag to my program or changing something in my C++ code? E.g. I'd like to tell Kokkos to use OpenMP even though CUDA is available.

To indicate that Kokkos should use OpenMP as the execution space, when CUDA is enabled, you'll need to make changes in your C++ code, specifically by providing a policy (e.g. `RangePolicy`, `TeamPolicy`) that is passed to the `parallel_*` to explicitly set the execution space via template parameter. I'd suggest using `Kokkos::DefaultHostExecutionSpace` in these cases rather than `Kokkos::OpenMP`- if you hard-code `Kokkos::OpenMP` then you will set yourself up for compilation errors if you choose a configuration that fails to enable OpenMP but uses another host space like Serial or Threads (alternatively you could use preprocessor if-guard macros, but that likely results in clunkier code ultimately resulting in the execution that using the `DefaultHostExecutionSpace` would likely provide).

An important distinction to recognize when explicitly requesting a non-default execution space on the host (i.e. OpenMP when CUDA is enabled) is the distinction between execution space and memory space - when CUDA is enabled via configuration at compile time, it is the default execution space, and the corresponding default memory space in this configuration is `CudaSpace` (memory space indicates where data will be allocated). Control of where a View's memory is allocated can be explicitly provided by users via memory space template parameter, but whenever you create a View without explicitly providing a memory space, by default the memory allocation will occur in a space that is accessible by the default execution space - so if CUDA is enabled then the default is `Kokkos::CudaSpace`.

If you pass a View to a `parallel_*` computational body (through functor or lambda capture) without explicitly indicating the memory space and in a CUDA-enabled configuration, then the data allocation will be on device. But in this situation, where the `parallel_*` is explicitly set to execute on the host via a host execution space (e.g. `parallel_for( Kokkos::RangePolicy<Kokkos::DefaultHostExecutionSpace>,...`), then you would run into a memory access violation (caveat - enabling UVM allows this to work). 
To prevent this there are a couple options - 1) if the data is intended to only be used on the host, then explicitly indicate `Kokkos::HostSpace` as the memory space to the corresponding views, or 2) if the data may also need to be accessed on the device, then you should follow the pattern of creating the View (default memory space is fine), then create a "host mirror" of the View, and copy between them as necessary. Note - when following the pattern of creating a view, a host mirror, and deep copying between, when only host execution spaces are enabled then the deep copy call is essentially free as the view and its host mirror will point to the same data (think of the view like a shared_ptr), so this is a good pattern to follow for portability + performance. 

If the terminology I used above is too Kokkos-specific, e.g. "host mirror", I suggest looking at the memory spaces section of the [kokkos-tutorial pdf link here](https://github.com/kokkos/kokkos-tutorials/blob/master/Intro-Full/Slides/KokkosTutorial_BNL19.pdf) and the codes in exercise 3 [sample code](https://github.com/kokkos/kokkos-tutorials/tree/master/Intro-Full/Exercises/03), if you compare the Begin to Solution codes that should help provide some syntax details for explicitly controlling memory spaces.

**Comment by DABH** [comment]
Thanks, very slowly getting up to speed... :)

Really appreciate the thorough explanation.  In particular thinking about the "gotcha" of having mismatched execution/memory spaces is really useful, that will likely prevent some bugs in my code in the future :)

So now I understand how I can override the execution/memory space for some _particular_ Kokkos code I'm writing, e.g. some parallel_for.  However, my ultimate goal is to use a bunch of the higher-level packages in Trilinos which only call Kokkos under the hood (i.e. I don't see a way to tell Tpetra, MueLu, etc. which execution/memory spaces to use for their various operations).  Is there a _global_ way (e.g. a global #define in my main, some argument to Tpetra::ScopeGuard [which calls Kokkos::initialize() for me], etc.) to essentially overwrite Kokkos' default execution and memory spaces?  The point is that this would be easier than building separate copies of Trilinos that have CUDA/OpenMP/Threads enabled or not -- I "just" want a (relatively) painless way of trying out my code in serial, with OpenMP, and with CUDA.

**Comment by massimiliano-leoni** [comment]
I got here looking for an answer to the exact same question. @DABH did you eventually find a way to do this?

**Comment by DABH** [comment]
I think what I ultimately did was just maintain a couple copies of Trilinos on my computer, one configured for CUDA, and one configured only for CPU parallelism.  For setting the execution space of specific operations, you can see the above answers, but for global/default changes, having different configurations of Trilinos was the best solution I found.  (There might be better ways, I just didn't figure them out...)

**Comment by jhux2** [comment]
@trilinos/tpetra @trilinos/kokkos

**Comment by brian-kelley** [comment]
@DABH @massimiliano-leoni There isn't a way to change the default execution space at runtime, since ``Kokkos::DefaultExecutionSpace`` is a type decided at compile time.

The Tpetra stack lets you set the Node (or device) type for every class and operation. This goes top-down, so you plug in a Node type into some Tpetra class or function, and everything below that will use the same Node. The specific instantiations of Node are in teuchos/kokkoscompat/src/KokkosCompat_ClassicNodeAPI_Wrapper.hpp if you're curious. For example, Kokkos::Compat::KokkosOpenMPWrapperNode will always use Kokkos::OpenMP as the execution space, and Kokkos::Serial as the memory space.

MueLu wraps this up nicely so that the app will choose the device based on command line flags, e.g. ``--cuda`` or ``--openmp``. In muelu/test/scaling/Driver.cpp:190, there is a ``main_(argc, argv)`` function templated on Scalar, two ordinal types and the Node. Then the real ``main()`` calls logic in muelu/test/unit_tests/MueLu_Test_ETI.hpp to dispatch to an instantiation of ``main_`` with the chosen node type at runtime. So you can run ``./Driver.exe --cuda ...`` to have everything happen on the Cuda device, or ``./Driver.exe --serial ...`` to have everything happen on host, but the actual logic of Driver is generic across them.

**Comment by massimiliano-leoni** [comment]
@brian-kelley thanks for the thorough reply! I didn't mean to change the execution space at runtime, compile time would be fine. The idea would just be to have a single directive at the beginning of a program, like `using myNode = something::something::CUDA` and then pass it on to all the instances, to later be able to change it to `using myNode = something::something::OpenMP`, recompile [my code, not all of Trilinos!], and use a different execution space.
From your answer, I understand this is actually possible setting Tpetra's `Node` type.
