### ISSUE TITLE
Zoltan2:  Add 2D Matrix partitioning and MatrixPartitioningProblem or MatrixPartitioningSolution

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#595]
We have demonstrated the effectiveness of 2D matrix partitioning for data-oriented problems
(SC13 Boman, Rajamanickam, Devine), but we do not have that capability in Zoltan2.

This work will include providing capability for Cartesian partitions of the matrix and associated vector partitions.

It will also include matrix distribution.

May include matrix sampling to accelerate hypergraph partitioning and experiments with PuLP.

**Comment by mhoemmen** [comment]
FYI, best performance would depend on Tpetra implementing distribution and redistribution by nonzeros, rather than by rows.

**Comment by nmhamster** [comment]
@mhoemmen I think I sent you results of doing this on a KNL recently. This is balanced approximately by nonzeros rounded to nearest rows. There is a reasonable performance improvement possible on platforms like KNL and POWER8 where prefetchers etc can kick in to deliver stronger performance. I do not think that we need to do this with inspect/execute since we could hide the partitioning information in the Kokkos Sparse structure. I will note that my implementation executes OpenMP directly and not via Kokkos for initial prototyping.

**Comment by mhoemmen** [comment]
@nmhamster Sorry I didn't clarify -- I was referring specifically to MPI distribution, and to how Tpetra::DistObject works.  DistObject has a Map; its Map expresses the distribution of its entries over processes.  CrsGraph and CrsMatrix are DistObject subclasses.  Currently, the Map of CrsGraph and CrsMatrix is the same as their row Map.  This means that these objects are distributed by rows -- 1-D distribution.  2-D distribution works, sorta kinda, because we allow overlapping row Maps and arbitrary column Maps.  However, redistribution (Export / Import) currently uses the row Map, which means extra communication.  It would be better if the DistObject Map were based on (i,j) triples, rather than rows (i only).
