### ISSUE TITLE
Framework and Tpetra:  Rebuilding Tpetra files when not needed

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#5986]
## Bug Report
@trilinos/framework @trilinos/tpetra 

### Description

A minor annoyance:
Changing a CMakeLists.txt file in Zoltan2 (to add a new test) causes files in Tpetra to be recompiled:

[ 72%] Building CXX object packages/tpetra/core/src/CMakeFiles/tpetra.dir/Tpetra_LocalCrsMatrixOperator_INT_SERIAL.cpp.o
[ 72%] Linking CXX static library libtpetra.a

Tpetra should not rebuild files solely because I add a test in Zoltan2.  It seems whenever cmake is rerun, something in Tpetra is touched, causing this file to rebuild.  Note that I do not explicitly enable Tpetra, nor am I building its tests or examples.

### Steps to Reproduce
1. SHA1:  5c5bf18e9051763ad217d68d177321514ddafdc2
1. Configure script:  see below
1. Do this.  touch zoltan2/test/driver/CMakeLists.txt
1. Do that.  make
1. Watch Tpetra rebuild a file

```
cmake \
-D CMAKE_BUILD_TYPE:STRING="DEBUG" \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
\
-D MPI_BIN_DIR:PATH=${SEMS_OPENMPI_ROOT}/bin \
-D TPL_ENABLE_MPI:BOOL=ON \
-D MPI_EXEC_MAX_NUMPROCS:STRING=64 \
\
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
\
-D Trilinos_ENABLE_Epetra:BOOL=ON \
-D Trilinos_ENABLE_Pamgen:BOOL=ON \
-D Trilinos_ENABLE_Galeri:BOOL=ON \
\
-D Trilinos_ENABLE_Zoltan2:BOOL=ON \
-D Zoltan2_ENABLE_TESTS:BOOL=ON \
-D Zoltan2_ENABLE_EXAMPLES:BOOL=ON \
...
```

**Comment by kddevin** [comment]
Oops, I didn't find #5772 when I searched.  Sorry, @jhux2

**Comment by jhux2** [comment]
@kddevin No worries.  I looked at this a little bit, and as I recall, there's some special cmake logic specifically for this file.

**Comment by prwolfe** [comment]
This is occurring due to the code starting at https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/src/CMakeLists.txt#L403

Basically the file gets created when GO=LONG_LONG and then reset when GO=INT. It's that change which triggers it's being rebuilt when any configure is done.

I'm not sure I understand the need for considering the global ordinal in this case at all.  To me it makes more sense just to make a local copy of the scalar list and add int to it if needed, then iterate over that.  I did not find Mark in his office and he was the last to work on this so I will talk to him next time he's around and follow up.

Paul

**Comment by mhoemmen** [comment]
@prwolfe see my e-mail :)

**Comment by mhoemmen** [comment]
Paul and I talked about this today, and came up with a possible solution.  The current implementation of `TPETRA_PROCESS_ALL_SLGN_TEMPLATES` looks like this:
```
for all enabled Node types NT:
    for all enabled GlobalOrdinal types GO:
        for all enabled LocalOrdinal types LO:
            for all enabled Scalar types SC:
                if ((instantiate for Scalar=int) and SC==int) or (SC is not some GlobalOrdinal type) or (SC==GO):
                    Generate ETI .cpp file for (SC, LO, GO, NT)
                end if
            end for
        end for
    end for
end for
```
For classes that actually take all four template parameters (SC, LO, GO, NT) or one-to-one mappings of them (e.g., `device_type` instead of `Node`), this code only generates a .cpp file for each instantiation once.  However, `Tpetra::LocalCrsMatrixOperator` only takes three template parameters (MultiVectorScalar, MatrixScalar, Device), and only gets instantiated for `(SC, SC, NT::device_type)`.  Thus, if multiple GO or LO types are enabled, the above loop will generate the same ETI .cpp file multiple times.

When CMake "generates the ETI .cpp file," it first checks to see if the generated file exists already and would not change.  CMake only writes the file if it doesn't exist or would be different.  That would normally make the above loop not write the file multiple times.  However, in this case, the implementation treats SC=int as a special case.  It needs to, since Tpetra needs to instantiate SC=int regardless of whether GO=int is enabled.  (Zoltan2 needs SC=int in CrsMatrix.  This wasn't Tpetra's idea.)  If GO=int is enabled, then the generated file uses the appropriate GO macro (this is a by-product of Sierra's bjam build system, but it's still a good idea to avoid issues with left-over .cpp files in a build directory).  SC=int doesn't use a special macro.  Thus, it's possible that the file might get generated twice: 

1. using SC=GO with GO=int, with the "inst int int" macro in the file; and
2. using SC=int with GO=long (or long long), with the `inst int long" macro in the file.

The file's contents change each time, so it always gets overwritten.  This triggers rebuild of the file.

Tpetra has deprecated being able to enable multiple GlobalOrdinal types.  Thus, the above situation should only occur if deprecated code is enabled, and it should no longer be possible in Trilinos 13.

If we still want to fix this, we could change the loop order and extract out the `SC=int` special case, like this:
```
for all enabled Scalar types SC:
    for all enabled LocalOrdinal types LO:
        for all enabled Node types NT:
            for all enabled GlobalOrdinal types GO:
                if is_not_GlobalOrdinal(SC) or SC==GO:
                    Generate ETI .cpp file for (SC, LO, GO, NT)
                end if
            end for # all GO
        end for # all NT
    end for # all LO
end for # all SC

# SC=int special case.  If we've already instantiated SC=GO,
# then we don't need to do it again here.
if instantiate_for_Scalar_int and (not enable_GlobalOrdinal_int):
    for all enabled LocalOrdinal types LO:
        for all enabled Node types NT:
            for all enabled GlobalOrdinal types GO:
                 Generate ETI .cpp file for (SC, LO, GO, NT)
            end if # all GO
        end for # all NT
    end for # all LO
end if
```
This shouldn't be hard to do, but it does risk changing Tpetra's ETI logic at a time when Tpetra has a long-running branch (for deprecation) about to be merged in.  Thus, I won't start this work until I hear from the rest of the @trilinos/tpetra team.
