### ISSUE TITLE
MueLu:  Create Xpetra::BlockedCrsMatrix out of one Tpetra::CrsMatrix

### ISSUE THREAD

**Issue by kliegeois** [trilinos/Trilinos#6025]
## Question
@trilinos/muelu 
@tawiesn 

I am wondering how to efficiently create a Xpetra::BlockedCrsMatrix, with a 2x2 block structure for instance, out of a Tpetra::CrsMatrix.

To be more precise, let say that I have a _strode_ Tpetra::CrsMatrix, for instance with a stride of 2 such that all rows and columns with even global ID are related to a physic and all the others are related to a second physic, and let say that I want to have a BlockedCrsMatrix with the diagonal block such that the first one is related to the first physic, the second diagonal block related to the second physic, and the off-diagonal blocks related to the coupling between physics. 

I would like to do so in order to use a block GS smoother in a thermomechanical simulation with different smoothers or smoother parameters for each diagonal block individually.

Is there a way to efficiently create blocks out of the matrix given the row and column maps of each block (or equivalently the Xpetra::BlockedMap of the blocked operator)?

Thanks a lot for your inputs.

**Comment by tawiesn** [comment]
@kliegeois One can create a BlockedCrsMatrix by splitting a CrsMatrix. You might want to look at the tests "SplitMatrix" in [here](https://github.com/trilinos/Trilinos/blob/master/packages/xpetra/test/BlockedCrsMatrix/BlockedCrsMatrix_UnitTests.cpp). But splitting a CrsMatrix is not efficient as you always need to create new submatrices for the single big blocks by copying around data. I am not aware of an efficient way to split the CrsMatrix object.
Therefore, the only reasonable way to go would be to create a BlockedCrsMatrix object during the matrix assembly. That's how we've done in Munich for our multiphysics codes as well as for the Sandia multiphysics codes. The "CreateBlockDiagonalExampleMatrix{Thyra}" routines [here](https://github.com/trilinos/Trilinos/blob/master/packages/xpetra/test/BlockedCrsMatrix/BlockedMatrixTestHelpers.hpp) should be helpful how to create a blocked Crs Matrix from single blocks with a special focus on how to split the maps and organize them in MapExtractor objects (which are just there to administrate the submaps relative to the full maps of the overall block matrix). An important point why you want to create a blocked crs matrix during assembly is also that you then can easily use the Thyra style GID ordering. Thyra-style means, that each block of the matrix (e.g. the velocity block and the pressure block) have always consecutive GIDs starting from zero, rather than strided unique GIDs throughout the full system with holes in it (e.g. 0,1,3,4,6,7 and 2,5,8,...). Certain block smoothers do not work well with matrices based on maps with wholes or when the GIDs do not start from zero.

Long in short: for quick experiments and tests or proof of concepts that a certain solution algorithm works as expected you can try to split the Tpetra CrsMatrix and create a 2x2 Xpetra::BlockedCrsMatrix from it. But as soon as performance gets important you might need to assemble the diagonal blocks of the Xpetra::BlockedCrsMatrix first into single CrsMatrices and then just create the BlockedCrsMatrix out of it.

**Comment by kliegeois** [comment]
@tawiesn Thanks a lot for your answer. 
In my case, the main interest is to test the influence of the preconditioner on the iteration count of the GMRES.
Therefore, I might use the `SplitMatrix` first and change the matrix assembly process afterwards. 

Thanks again!
