### ISSUE TITLE
Teuchos - enable stacked timer info to go to std::out

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#6043]
## Enhancement
@trilinos/teuchos 
The stacked timers are great for understanding timings after the fact, but I've started using them to trace the code.  I add std::out << name ...  to trace execution to narrow down a fault.  I'd like to be able to do this on the fly

What I want

export TEUCHOS_ENABLE_VERBOSE_TIMERS=1

Then I run and  I see something like this to the screen

```
STARTING MueLu RefMaxwell: solve
STARTING MueLu RefMaxwell: smoothing
STARTING Ifpack2::Chebyshev::apply
STOPPING Ifpack2::Chebyshev::apply
STARTING Ifpack2::Chebyshev::apply
STOPPING Ifpack2::Chebyshev::apply
STOPPING MueLu RefMaxwell: smoothing

```

**Comment by bathmatt** [comment]
@bartlettroscoe @rppawlo

**Comment by bartlettroscoe** [comment]
Okay, I think we want to be careful to print to [Teuchos::VerboseObjectBase::getDefaultOStream()](https://trilinos.org/docs/dev/packages/teuchos/doc/html/classTeuchos_1_1VerboseObjectBase.html#ab9b501211e8b48b597e5ce3a83e4aaf7) (or with an `Teuchos::FancyOStream` object configured with the stacked tracer machinery) so that we don't get every MPI process printing this over and over again.

**Comment by bathmatt** [comment]
I want everyone to print this every time to standard out..  I want it
interleaved with every other output,

**Comment by rppawlo** [comment]
@bathmatt - this capability is in PR:

https://github.com/trilinos/Trilinos/pull/6044

can you test out and make sure it is what you want?
