### ISSUE TITLE
Tpetra::Map: Deprecate & remove getIndexBase() method

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#616]
@trilinos/xpetra @trilinos/tpetra @tawiesn @csiefer2 

Issues like #613 point out the uselessness of the Tpetra::Map::getIndexBase() method.  Users often think that "index base" means "0 for C or C++; 1 for Fortran."  This is _not_ the case; Tpetra::Map confusingly requires that the index base equal the globally minimum global index.  (Tpetra inherited this requirement from Epetra; Epetra_Map also has this requirement.)  This makes the index base redundant.  Even if Tpetra::Map didn't have this requirement, the getIndexBase() method serves no useful purpose. 

The indexBase argument to the contiguous Tpetra::Map constructors _does_ serve a useful purpose, because it tells the Map the globally minimum global index.  However, after construction, users can just ask the Map for its globally minimum global index.

**Comment by tawiesn** [comment]
I think even 
> Tpetra::Map confusingly requires that the index base equal the globally minimum global index

is not a "requirement". If it would have been a requirement my code would never have worked properly. 
IndexBase is used in the constructor as some kind of "offset" for GIDs in some constructors. Tpetra requires the indexBase to be the same over all processors (which is a reasonable requirement even though i don't really see what it is good for. It's only checked in the debug mode).

In Xpetra we have the indexBase since both Epetra and Tpetra have it, but it is not really used. The Xpetra::StridedMaps have a separate "offset" parameter which serves as GID offset similar to how indexBase is used in the constructors of Epetra/Tpetra.

**Comment by mhoemmen** [comment]
> I think even
>  > Tpetra::Map confusingly requires that the index base equal the globally minimum global index
> is not a "requirement".

By "requirement," I meant "Map's constructor checks this condition (in a debug build at least) and throws if it is not true."

> IndexBase is used in the constructor as some kind of "offset" for GIDs in some constructors.

It would be better, perhaps, if Tpetra called this "global starting index."

> Tpetra requires the indexBase to be the same over all processors (which is a reasonable requirement even though i don't really see what it is good for. It's only checked in the debug mode).

One of my long-term projects is to rewrite Tpetra so that error states get disseminated whenever communication naturally needs to happen, rather than forcing barriers or all-reduces to check things.  In any case, just because Tpetra doesn't check, doesn't mean you're allowed to do it ;-)

**Comment by mhoemmen** [comment]
> The Xpetra::StridedMaps have a separate "offset" parameter which serves as GID offset similar to how indexBase is used in the constructors of Epetra/Tpetra.

Does this "offset" parameter mean something different than the globally min global index?

**Comment by tawiesn** [comment]
> Does this "offset" parameter mean something different than the globally min global index?

Yes and no. It has a similar intention than the classic indexBase and has only a real meaning for constructing the maps. But the offset parameter does not necessarily and generally denote the minimal global id. Let me give an example: Let's say we have a NS Stokes problems with 3 velocity and 1 pressure dofs per node (we denote this by the vector notation {3,1} in the stridedInfo variable). Since it is embedded in a multiphysics problem we want the maps to start with GID 1000 (i.e. offset = 1000). Assume you want to create a map which only contains the pressure GIDs (i.e. 1003, 1007, 1010,...), the minimum GID is 1003, the offset is 1000, the indexBase could be 0. Offset and indexBase don't really matter  for the calculations once the map is constructed. Please note, that you may want to merge in the pressure vector in some kind of global vector representing not only the Navier Stokes part but also other physics with GIDs starting from zero. Messing around with different indexBase numbers is not helpful here.

**Comment by mhoemmen** [comment]
Thanks @tawiesn !  I think I understand better now.

Do you think it would be useful for Tpetra to have these strided Maps?

**Comment by tawiesn** [comment]
>  Do you think it would be useful for Tpetra to have these strided Maps?

I don't think so. It is an abstract extension of Epetra/Tpetra maps about the internal meaning of the GIDs in a map. There is nothing which would be Epetra or Tpetra specific, so i think Xpetra is the right place for it to live.

Furthermore, i'm not super happy with my current implmeentation. So, if someone wants to have such a functionality directly in Tpetra we should talk first about a better way to implement it. Not sure whether that makes sense. If you want to use multigrid solvers which actually make use of that information, you need MueLu, i.e. you have to use Xpetra anyway.

**Comment by mhoemmen** [comment]
I'm calling this a "task," but if you take this, please be careful to check downstream packages.
