### ISSUE TITLE
Piro: compilation error with clang compiler

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#6225]
Trilinos did not compile in a couple of the Albany Clang builds due to an issue having to do with Piro + ROL: 

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=90557 
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=90556 

@trilinos/piro

**Comment by ikalash** [comment]
Also on mayer: https://my.cdash.org/viewBuildError.php?buildid=1724437 .

**Comment by jewatkins** [comment]
That looks like my fault.

**Comment by bartlettroscoe** [comment]
As shown [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=5851266) this also broke the `Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt` build too.

This go fixed with the commit fdaa367f94.

It would be great if the @trilinos/framework team could add a Clang build to the set of PR builds.

**Comment by ikalash** [comment]
I can confirm that the issue has been resolved.  I agree with Ross's comment: 

> It would be great if the @trilinos/framework team could add a Clang build to the set of PR builds.

I thought based on the SART meetings that this was close to getting set up a few months ago?

**Comment by jewatkins** [comment]
Ah okay this is fixed already? I'll cancel my PR.

**Comment by ikalash** [comment]
Yes it's fixed.  Sorry about the confusion!
