### ISSUE TITLE
Tempus: Add StepperExplicitRK::takeStep_modify

### ISSUE THREAD

**Issue by ccober6** [trilinos/Trilinos#6318]
## Enhancement
@trilinos/tempus 

Would like to implement a new takeStep usage that:
- eliminates observers
- explicitly shows what solution variables can be modified (e.g., const/nonconst) 
- and at what point in the explicit RK algorithm (e.g., begin/end of stepper, begin/end of stages).
- the modify function has a single interface (e.g., modify(RCP<Thyra::VectorBase<Scalar> > x, Modify_ENUM selector))
- Modify_ENUM would specify what variable at what location is being modified (e.g., MOD_XSTAGE_BEGIN_STAGE)

**Comment by ccober6** [comment]
pining folks @krcb @eric-c-cyr @seamill @bathmatt @egphill @rppawlo @sconde @asteyer

**Comment by ccober6** [comment]
@krcb @eric-c-cyr @seamill @bathmatt @egphill @rppawlo @sconde @asteyer

The issue description above is a first cut of what I recall from today.  Please make additions/corrections.  

I will start a branch implementing this.

**Comment by seamill** [comment]
@ccober6 What exactly is the design here (our meeting didn't really cover that part)? Are we adding an observer-like object that has a modify call on it, or are we adding a virtual modify function to the RK stepper that we override in a derived class?

**Comment by ccober6** [comment]
@seamill I am open to suggestions, but to start with a strawman I would lean towards "an observer-like object that has a modify call on it" so the application does not need to derived the stepper itself.  Thoughts?

**Comment by ccober6** [comment]
@krcb @eric-c-cyr @seamill @bathmatt @egphill @rppawlo @sconde @asteyer

Also it occurred to me this morning that I suggested yesterday that we could implement the solution limiting on the Tempus side.  I now believe that may not be possible, since the limiting likely needs spatial information and/or "near-by" solution values (e.g., solution values within the element) and Tempus does not have this information because of the "method of lines" assumption.

Is this true or does the limiting not require that type of information?

**Comment by eric-c-cyr** [comment]
Yes, the spatial information is important. Tempus would have to know about the meshing and I suspect that is not really the right scope.

Sent from my iPad

On Nov 21, 2019, at 7:57 AM, Curtis Ober <notifications@github.com> wrote:

﻿

@krcb<https://github.com/krcb> @eric-c-cyr<https://github.com/eric-c-cyr> @seamill<https://github.com/seamill> @bathmatt<https://github.com/bathmatt> @egphill<https://github.com/egphill> @rppawlo<https://github.com/rppawlo> @sconde<https://github.com/sconde> @asteyer<https://github.com/asteyer>

Also it occurred to me this morning that I suggested yesterday that we could implement the solution limiting on the Tempus side. I now believe that may not be possible, since the limiting likely needs spatial information and/or "near-by" solution values (e.g., solution values within the element) and Tempus does not have this information because of the "method of lines" assumption.

Is this true or does the limiting not require that type of information?

**Comment by ccober6** [comment]
Closing in favor of new design in #6711
