### ISSUE TITLE
Retrospective for #594

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#632]
Write a retrospective for #594, per Trilinos Leaders' Meeting discussion on Tue 20 Sep 2016.
@jhux2

**Comment by jhux2** [comment]
@maherou @jwillenbring

**Comment by maherou** [comment]
@spdomin: We discussed issue #594 during the Trilinos leaders meeting yesterday and decided to use the experience as the first instance of a new retrospective process for Trilinos issues.  We intent to invoke the retrospective process for issues that have the potential to teach us a better way to work.  We welcome your participation in completing the retrospective for #594.

**Comment by spdomin** [comment]
@maherou I would be happy to help. Let me know if it is too late and, if nota, how I can help. I also a, not getting these notifications to my email, just the tiny bell when I sporadically look at the Nalu GH webpage. I will try to make sure that I change my settings so that I do not miss them.

Also, my production run on gcc4.8.5 is still failing at the same step.

**Comment by mhoemmen** [comment]
@spdomin Just curious -- do the notifications show up when you go to the Notifications page on the Github website?  If not, then we need to fix that.

**Comment by spdomin** [comment]
Yes. Notifications light up the tiny bell.

**Comment by mhoemmen** [comment]
FYI here are some guidelines about e-mail filtering for Github notifications:

https://help.github.com/articles/about-notification-emails/

People vary in their practice.  Some prefer the e-mails; others prefer to check the tiny bell periodically.
