### ISSUE TITLE
Updating PR tester env

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#6346]
## Enhancement
@bartlettroscoe 

How do you feel about switching `atdm-ninja_fortran/1.7.2` for `sems-ninja_fortran/1.8.2`, it would be both an update of the ninja version and would also allow the scripts to run using only sems modules instead of a combination of sems and atdm modules.

Also I noticed that @ZUUL42 has been performing some tests to build with more up-to-date compilers, would it make sense to also have a build that uses the new `sems-openmpi/4.0.2` which is a significant upgrade from `sems-openmpi/1.10.1`?

**Comment by bartlettroscoe** [comment]
> How do you feel about switching atdm-ninja_fortran/1.7.2 for sems-ninja_fortran/1.8.2?

@lucbv, fine by me but I don't have any say in the Trilinos PR builds.  The @trilinos/framework team needs to okay this.  Otherwise, you can go ahead and try making the change and posting a Trilinos PR.  I think we already switched most of the ATDM Trilinos builds to `sems-ninja_fortran/1.8.2`.

> would it make sense to also have a build that uses the new sems-openmpi/4.0.2 which is a significant upgrade from sems-openmpi/1.10.1?

Also fine by me but not my say.

Note that we will be updating the 'cee-rhel6' builds to OpenMPI 4.0.1 as per https://sems-atlassian-srn.sandia.gov/browse/ATDV-237.
