### ISSUE TITLE
Zoltan2: MultiJagged issue on Spectrum MPI

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#6423]
## Bug Report
@trilinos/zoltan2 

### Description
When running on lassen, MultiJagged is bugging out with the following message:
```
[lassen258:148413] coll:ibm:allreduce: GPU awareness in PAMI requested. It is not safe to defer to another component.
[lassen258:148413] *** An error occurred in MPI_Allreduce
[lassen258:148413] *** reported by process [2154496201,11]
[lassen258:148413] *** on communicator MPI COMMUNICATOR 6 DUP FROM 5
[lassen258:148413] *** MPI_ERR_UNSUPPORTED_OPERATION: operation not supported
[lassen258:148413] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[lassen258:148413] ***    and potentially your MPI job)
```
It seems that there is an issue with certain things not being supported by Spectrum MPI:
https://www.olcf.ornl.gov/for-users/system-user-guides/summit/summit-user-guide/#open-issues

**Comment by kddevin** [comment]
Do we have a stack trace for this error?
The allreduce calls in Multijagged do not use a user-defined MPI datatype, but they do use a user-defined reduction operation.  This use-case differs from the documentation in the link.
The user-defined operator is not new to the Kokkos version of Multijagged, although now we are providing device buffers to it.  
Can we demonstrate bad behavior with a simple reproducer and a user-defined operation?

**Comment by mhoemmen** [comment]
"CUDA-aware" MPI doesn't necessarily mean that CUDA buffers work with MPI collectives.

**Comment by MicheldeMessieres** [comment]
@cgcgcg PR #6431 I expect will fix this, but I don't have Lassen access so you may want to just try it. We should do this change anyways.

**Comment by cgcgcg** [comment]
@MicheldeMessieres Sure, I will give this a shot and report back. Thanks!

**Comment by MicheldeMessieres** [comment]
@cgcgcg Can you clarify the context you saw the bug? Was it running zoltan2 tests or another program calling multi jagged? @mhoemmen was pointing out the fix should do nothing for UVM space and I was making an assumption we were talking about the UVM off zoltan2 tests (which I'm realizing now was probably not correct.)  If you were looking at zoltan2 tests it would be useful to know which pass/fail on that setup, since some run UVM on and some UVM off. If it's something else are you running the default UVM space? Then I think the fix will do nothing. I may need to refactor all HostMirrors in MJ and other spots to be pure host as @mhoemmen suggested to make it work on this system. @kddevin

**Comment by cgcgcg** [comment]
@MicheldeMessieres I was running EMPIRE, which uses MueLu. MueLu uses Zoltan2 MJ for rebalancing. Yep, it's using UVM.

**Comment by mhoemmen** [comment]
@MicheldeMessieres wrote:
> I may need to refactor all HostMirrors in MJ and other spots to be pure host as @mhoemmen suggested to make it work on this system.

The only place you _should_ need to do that is if you're giving buffers to MPI.  Tpetra has chosen to query MPI for CUDA-awareness, but CUDA-awareness might only involve point-to-point communication, not necessarily collectives or other things.
