### ISSUE TITLE
Zoltan2: Zoltan2_mjTest_geomgen_nomjparts_MPI_3 is randomly failing

### ISSUE THREAD

**Issue by MicheldeMessieres** [trilinos/Trilinos#6440]
## Bug Report
@trilinos/zoltan2 

Zoltan2_mjTest_geomgen_nomjparts_MPI_3 is randomly failing.

https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-11&end=2019-12-11&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=testname&compare2=61&value2=Zoltan2_mjTest_geomgen_nomjparts_MPI_3&field3=status&compare3=61&value3=failed

### Description
The new zoltan2 tests with PR #5332  run twice and compare results so they can catch indeterminate behavior. Several times this causes a test failure. One time there was a seg fault. One time there was a file error I am not sure about yet.

**Comment by bartlettroscoe** [comment]
Info on random failures ...

It looks like one of these randomly failing tests `Zoltan2_mjTest_geomgen_nomjparts_MPI_3` is impacting the standard post CI build as shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-11&end=2019-12-11&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Continuous&field2=buildname&compare2=61&value2=Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_OPENMP_CI&field3=status&compare3=61&value3=failed) showing 2 failures in since 2019-12-04.  And it looks like this test has killed several Trilinos PR iterations (5 total) since 2019-11-21 as shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-11&end=2019-12-11&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=testname&compare2=61&value2=Zoltan2_mjTest_geomgen_nomjparts_MPI_3&field3=status&compare3=61&value3=failed).

**Comment by MicheldeMessieres** [comment]
@bartlettroscoe @kddevin Query shows this test has not had any failures in the past 2 months so I think we can close this issue:

https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-11&end=2020-02-21&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=testname&compare2=61&value2=Zoltan2_mjTest_geomgen_nomjparts_MPI_3&field3=status&compare3=61&value3=failed

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-11&end=2020-02-21&filtercount=8&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=groupname&compare2=62&value2=Experimental&field3=testname&compare3=61&value3=Zoltan2_mjTest_geomgen_nomjparts_MPI_3&field4=status&compare4=61&value4=failed&field5=testoutput&compare5=94&value5=Error%3A%20Remote%20JSM%20server%20is%20not%20responding%20on%20host&field6=testoutput&compare6=94&value6=Error%20initializing%20RM%20connection.%20Exiting&field7=testoutput&compare7=94&value7=srun%3A%20error%3A%20Unable%20to%20create%20step%20for%20job&field8=testoutput&compare8=94&value8=Open%20MPI%20was%20unable%20to%20obtain%20the%20username%20in%20order%20to%20create%20a%20path), we have not seen a non-system failure in this test in ATDM Trilinos builds since 2019-12-26.
