### ISSUE TITLE
Remove Unnecessary Amesos2 dependence on Amesos

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#649]
Currently Amesos2 depends on Amesos, only because it needs SuiteSparse, which is currently located in Trilinos/packages/amesos/src/SuiteSparse. It has been determined that SuiteSparse should be moved to Trilinos/packages/common/auxiliarySoftware and setup as a TriBITS package in that location. Amesos and Amesos2 would then have dependencies on SuiteSparse, but Amesos2 would no longer depend on Amesos. This would make Trilinos more usable for users who wish to use Amesos2, but have no need for the old Epetra stack of Trilinos. These changes will also lay the foundation for additional work to add new solver interfaces to Amesos2.

Here are the steps required to accomplish this:
1. Move SuiteSparse to Trilinos/packages/common/auxiliarySoftware/SuiteSparse
2. Make the necessary TriBITS changes to set SuiteSparse up as a package (including adding it to the top-level list of packages with a comment saying this is auxiliary software).
3. Make the TriBITS changes necessary to Amesos to reflect the removal of SuiteSparse from its directory structure.
4. Remove the Amesos2 dependence on Amesos.
5. Make the TriBITS changes necessary to Amesos and Amesos2 to add dependencies on SuiteSparse (see package/cmake/Dependencies.cmake).
6. Test all changes. (Incremental changes may also make sense, but definitely need to test here.)
7. Issue a pull request. Mention @srajama1 in the pull request.

@srajama1 Did I forget anything? Are there any particular options that should be used when building Trilinos to test this to enable certain parts of Amesos2?

**Comment by jwillenbring** [comment]
@MicheldeMessieres Could you review this ticket and see if you have any questions or concerns about these activities? Would you need to speak with Siva or I prior to working on this? If not, you can start on this effort.

**Comment by srajama1** [comment]
Jim, this is a good description. We should make sure Amesos2 works with -D Amesos2_ENABLE_KLU2:BOOL=ON  after doing this.

**Comment by krcb** [comment]
Some questions regarding this effort:

1) The version of SuiteSparse available in Trilinos/packages/amesos/src/SuiteSparse is name spaced to Amesos. Is it desirable that this name spacing be maintained or should all references to Amesos be removed?

2) SuiteSparse files in Trilinos/packages/amesos/src/SuiteSparse are not currently compiled into separate libraries, which are then linked into Amesos. Instead, it appears that these are simply compiled into the Amesos library. If we make SuiteSparse into a separate package, is the desire to build the various components into libraries, which other packages could then link against?

3) In Trilinos/packages/amesos2/src/ there is SuiteSparse/KLU2. Is it desired that this component also be moved to the new SuiteSparse package in common/auxiliarySoftware/SuiteSparse?

4) The directory common/auxiliarySoftware does not appear to exist in the public repository. Will conflicts result if this is created?

**Comment by srajama1** [comment]
@krcb , Thanks for going through this quickly.

1) It is better to change the namespace to trilinos rather than amesos or amesos2.

2) Yes, that is the goal for moving into a separate package. Suitesparse will have its own library, probably namespaced as trilinossuitesparse to avoid conflicts.

3) This is an interesting question. KLU2 is derived work from KLU, but it works with Amesos2. We don't have plans to release it by itself, so it can be left in Amesos2. 

4) I am not sure what kind of conflicts you are thinking about. I can't think of any.

**Comment by krcb** [comment]
Thanks for the answers, this is very helpful. A couple of follow ups:

3) If KLU2 is to remain part of Amesos2, can we move it out of the SuiteSparse subdirectory (or at least rename the SuiteSparse subdirectory)? I can forsee that confusion will arise if we have a SuiteSparse package and a subdirectory with the same name in Amesos2.

4) I was wondering whether there were private versions of Trillinos that already had such a directory in existence and this would lead to conflicts. However, it sounds like this is not the case.

**Comment by mhoemmen** [comment]
> We should make sure Amesos2 works with -D Amesos2_ENABLE_KLU2:BOOL=ON after doing this.

As a first step, we could write CMake logic in Amesos2 to report an informative error if KLU2 is not enabled.  The error message would tell people how to enable KLU2.

If we want to preserve existing behavior with `-D Amesos2_ENABLE_KLU2:BOOL=ON`, then we have to enable KLU2 by default by making it PS.

**Comment by srajama1** [comment]
@mhoemmen : KLU2 is enabled by default for some time. I said it has to be enabled explicitly because I know use cases where people turn it off forcibly :)

**Comment by srajama1** [comment]
@krcb 
3) I agree. The SuiteSparse directory in Amesos2 could be just renamed to KLU2 as I don't foresee anything else going there.

**Comment by krcb** [comment]
Reviewed progress 10/27:
- To-date AMD, BTF, CAMD, CCOLAMD have been re-namespaced.
- Namespace changes impact ShyLu and EpetraExt in addition to Amesos and Amesos2
- Testing has been done on amesos, amesos2. Need to add ShyLu (Basker, Taco) and EpetraExt testing.
- CHOLMOD implementation in amesos/SuiteSparse is broken. Since this functionality is available through a TPL, it was decided to remove CHOLMOD from TrilinosSuitSparse.
- PARAKLETE will also be removed from TrilinosSuiteSparse and all references to PARAKLETE removed from Trilinos. If a user tries to configure with PARAKLETE enabled a configure time exception will be thrown.

**Comment by srajama1** [comment]
Adding @hkthorn as she should be aware of these changes.

**Comment by srajama1** [comment]
Nalu issue : https://github.com/NaluCFD/Nalu/issues/2 

depends on this.

**Comment by spdomin** [comment]
Is this still an issue? My master and develop Trilinos branch is still complaining.

commit 2938143
Author: Alejandro Mota amota@sandia.gov
Date: Fri Dec 2 16:44:47 2016 -0800

*** ERROR: Setting Trilinos_ENABLE_Amesos2=OFF which was 'ON' because Amesos2 has a required library dependence on disabled package Amesos!

**Comment by srajama1** [comment]
Yes,  We are working with Tech-X on this. As you can see it involves lot of packages and Xyce dependencies.

**Comment by krcb** [comment]
We reviewed progress on 12/9. The majority of the renaming, relocation and dependency modification is complete. A new package, TrilinosSS has been created in packages/common/auxiliarySoftware. After initial review @srajama1 requested some minor changes, which have now been completed. The code is available for general review and testing under PR#918.

**Comment by krcb** [comment]
We have found that Ifpack, ShyLU, TrilinosCouplings depend on SuiteSparse under Amesos.
Those dependencies have been redone so that these packages depend on the new TrilinosSS package. These packages (Ifpack, ShyLU, TrilinosCouplings) need to be tested to verify that the refactor has not introduced problems. We would like to get input from @hkthorn to verify that the TrilinosCouplings interface utilized by Xyce performs as expected. It would also be useful if @spdomin could test this with Nalu to make sure that it resolves the amesos2/amesos dependency issue.

**Comment by spdomin** [comment]
Is this part of master or develop? I can test today or tomorrow if you send me the line that specifies the new package dependency.

**Comment by krcb** [comment]
PR918 is up-to-date with code in develop. If you check out PR918, then you should be able to build Nalu against that checkout.

**Comment by srajama1** [comment]
Stefan: This is neither in master or develop, yet. We are waiting for some Xyce testing and few other Trilinos failures before I click the green button for merging the PR.

**Comment by krcb** [comment]
Update from @hkthorn "Xyce serial and parallel testing with the proposed changes checks out."

**Comment by krcb** [comment]
Ifpack tests pass; ShyLUBasker tests pass with the update from @ndellingwood.

**Comment by srajama1** [comment]
@krcb: Is there anything else that is blocking you in this issue ?

**Comment by krcb** [comment]
@srajama1: There currently does not appear to be tests for ShyLUTacho/refactor. The PR needs to be run through the checkintest script using the SEMS environment (which I don't have access to). Once those two issues are addressed, you can go ahead and merge the PR from my perspective.

**Comment by krcb** [comment]
@spdomin: did you have the opportunity to try out #918 with Nalu? If so, does it resolve #900?

**Comment by srajama1** [comment]
@krcb: I will take care of the nalu use case. I forgot the Tacho one. Let me check that.

**Comment by spdomin** [comment]
Sorry, I am booked with other tasks. I will need someone from our ECP team to test out nalu builds with removal of the Epetra solver stack.

**Comment by krcb** [comment]
@srajama1 asked me to test out MueLu configured with Amesos2, Tpetra enabled, but Epetra, Amesos disabled. This results in a compilation error in packages/muelu/test/scaling/ImportPerformance.cpp
which has dependencies on Epetra functionality. However, this is not related to the Amesos changes made here.

**Comment by spdomin** [comment]
Yes, my guess is that it would be more than just this dependency. There probably should be a ticket (I actually think that there is possibly) to have a clean break from Tpetra given @maherou's comment that it has been deprecated.

**Comment by srajama1** [comment]
Ok, let us keep this issue for Amesos2 and Amesos dependency. We can create another one for the broader issues (if one doesn't exist).

**Comment by krcb** [comment]
I've opened issue #934 to address the MueLu issue.

**Comment by krcb** [comment]
@jhux2 resolved #934. MueLu now builds without Epetra and passes tests.

**Comment by spdomin** [comment]
Lots of traffic. Should I simply wait? Develop is still showing the issue.
   ***
   *** ERROR: Setting Trilinos_ENABLE_Amesos2=OFF which was 'ON' because Amesos2 has a required library dependence on disabled package Amesos!
   ***

**Comment by srajama1** [comment]
Yes, please wait. There are two issues left. One in Tacho and one in Ifpack2. Hopefully nothing else pops up. This is like a whack-a-mole so far.

**Comment by srajama1** [comment]
Looks like there was never an issue create for Tacho. At least I am not able to find it. @krcb can you file an issue with what you are seeing and assign it to me and @kyungjoo-kim ?

**Comment by krcb** [comment]
ShyLUTacho has reviewed PR #918 and signed off. #918 has now been merged to develop. @spdomin you should be able to try this out now.

**Comment by srajama1** [comment]
I will test this with a Nalu version before @spdomin can take over. @krcb: Thank you for all your help and patience in getting this done. This was a ton of work ! Thanks !

**Comment by spdomin** [comment]
Sound great! Please send me the config file when you have it tested. Also, I will be interested in executable size as well. 

This effort will be a great advancement for the core design of Trilinos and in managing dependencies for the path forward solver stack. I wonder if we can make this a retro so that we firmly implant the notion of dependency control?

**Comment by srajama1** [comment]
I am building on our testbeds. I can add the config file here once that is done. 

I don't understand the last statement. If it means we will not introduce Epetra stack dependency again, then yes ! We are not going to let that happen. This is part of the movement towards product model that @maherou mentioned couple of weeks ago in SART meetings.
