### ISSUE TITLE
In Ifpack2::RILUK::initialize(), there is a sometimes-unnecessary memory transient.

### ISSUE THREAD

**Issue by ambrad** [trilinos/Trilinos#676]
#570 focused on making RILUK reusuable. As a side effect, it confined a memory transient (a CRS copy of the matrix) to initialize(); previously, it persisted over the lifetime of the RILUK object.

The objective of this issue is to remove the transient completely in most use cases.

**Comment by aprokop** [comment]
Yes, I noticed this issue too back in Jan when working on reuse. I have a patch (see https://github.com/muelu/Trilinos/commit/43b0fdb7334dc5d5fe75baa2a8e63f683fc4a2c0) which converts some classes to be templated on RowMatrix instead of CrsMatrix. This way this conversion only being done if necessary.

Unfortunately, the patch has to be rebased  on top of the recent changes which may require some work.

**Comment by mhoemmen** [comment]
@kddevin FYI, not sure if this is still an issue.
