### ISSUE TITLE
Tpetra: missing symbol with clang-debug

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#6951]
## Bug Report
@trilinos/tpetra 

### Description

When I build trilinos (in this case panzer) using clang and debug (clang-openmp-debug-shared) I get missing symbols

```
packages/tpetra/core/src/libtpetra.so.12.17: undefined reference to `Tpetra::Details::CrsPadding<int, long long>::create_from_sames_and_permutes'
packages/tpetra/core/src/libtpetra.so.12.17: undefined reference to `Tpetra::Details::CrsPadding<int, long long>::create_from_imports'

```

is anyone else seeing this??

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

**Comment by bathmatt** [comment]
This only happens in shared obj builds.  not static builds

**Comment by bathmatt** [comment]
@bartlettroscoe  do we have any shared obj debug builds going??  Are they passing?  Is this only clang?

**Comment by bartlettroscoe** [comment]
@bathmatt, we don't have any ATDM Trilinos clang+shared+dbg builds going.  In fact, the only clang build we have running right now is:

* Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-4.0.2_serial_static_opt

which you can see from:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2020-02-27&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=clang

We have a todo to set up some sems-rhel7 clang7 builds as per:

* https://sems-atlassian-srn.sandia.gov/browse/ATDV-291

but that is still in the backlog.  If you want a clang+openmp+shared+dbg build, please comment in that issue.

Also, note that we have almost no builds at all going since last Friday due to problem with jenkins-srn.sandia.gov.  See:

* https://sems-atlassian-srn.sandia.gov/browse/ATDV-299

To be fair, I am constantly being told that I am running too many ATDM Trilinos build configurations in support of ATDM yet you see all of the holes in the build coverage ...

**Comment by bartlettroscoe** [comment]
@bathmatt, note that you did not provide any reproducability info so there is little chance that anyone is going to help fix this.

**Comment by bathmatt** [comment]
To reproduce use this configure 
[configure-trilinos.log](https://github.com/trilinos/Trilinos/files/4288725/configure-trilinos.log)



```
git clone Trilinos
export BUILD_COMMAND=ninja
export WORKSPACE=`pwd`
export INSTALL_DIR=/tmp
. ./Trilinos/cmake/std/atdm/load-env.sh clang-debug-shared-openmp
mkdir build
cd build
.  configure-trilinos.log
ninja
```

**Comment by jhux2** [comment]
@bathmatt I'll have a look.

**Comment by bathmatt** [comment]
Nope, cut and pasted
l /usr/lib64/libm.so && :
packages/tpetra/core/src/libtpetra.so.12.17: undefined reference to `Tpetra::Details::CrsPadding<int, long long>::create_from_sames_and_permutes'
packages/tpetra/core/src/libtpetra.so.12.17: undefined reference to `Tpetra::Details::CrsPadding<int, long long>::create_from_imports'
clang-7: error: linker command failed with exit code 1 (use -

**Comment by jhux2** [comment]
Ok, I can reproduce.

**Comment by jhux2** [comment]
@mhoemmen The two methods that result in undefined references have in common that they are `static constexpr`.  Any ideas?

**Comment by mhoemmen** [comment]
@jhux2 We could just refactor that class to get rid of the tags; it turns out they have no value anyway, since we have to consider merges from both copyAndPermute and unpackAndCombine all at once.

**Comment by jhux2** [comment]
Ok, I saw those methods were empty, wasn't sure why.  So remove the methods `create_from_sames_and_permutes` and `create_from_imports`?

**Comment by jhux2** [comment]
@mhoemmen Thank you for the suggestion, that worked.  PR is up.

**Comment by mhoemmen** [comment]
@jhux2 wrote:
> Ok, I saw those methods were empty, wasn't sure why.

My first pass for solving #6663 assumed that I could treat copyAndPermute and unpackAndCombine separately.  However, it turned out to be easier to treat them using the same code path and data structure.

Fun fact: CrsPadding is more or less just a DynamicProfile CrsGraph ;-) .

**Comment by jhux2** [comment]
@bathmatt PR is merged to develop, could you please test?

**Comment by bathmatt** [comment]
will do, my desktop network is down

**Comment by bathmatt** [comment]
It passes

**Comment by bartlettroscoe** [comment]
@bathmatt, just to be clear, we missed this because we did not have a clang+shared+dbg build, right?  The fact that it was also openmp was irrelevant, right?
