### ISSUE TITLE
PR Testing: Use C++14 standard for GCC 8.3 build

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#6968]
## Enhancement
@trilinos/framework

We are going to add -std=c++14 to the GCC 8.3 build (and remove -std=c++11). We will for the time being also keep the GCC 4.8.4 build, which will continue to insure compatibility with C++11. While some packages are looking to use C++14 (and C++17) features, this will at least move us in the right direction and ensure that customers will be able to build Trilinos with c++14.

This incremental step is consistent with discussions at this week's Trilinos Product Leaders meeting and is related to #6260.

**Comment by jwillenbring** [comment]
The PR has been merged, so I am closing this.

**Comment by jwillenbring** [comment]
As noted in #6260 this fix may not have done what was expected. I am going to reopen.

**Comment by bartlettroscoe** [comment]
CC: @crtrott, @mwglass 

@jwillenbring, the issue of C++14 PR builds for Trilinos just came up again today in the ATDM PI meeting.  Is there is a PR build that has C++14 support enabled?  Do we need to merge PR #6814 before this gets addressed?  NOTE: I think you can just set `-D Trilinos_CXX_FLAGS="-std=c++14` for now until we get PR #6814 (and the related Kokkos and TriBITS PRs) merged.

**Comment by bartlettroscoe** [comment]
CC: @trilinos/framework, @ibaned 

> NOTE: I think you can just set `-D Trilinos_CXX_FLAGS="-std=c++14"` for now until we get PR #6814 (and the related Kokkos and TriBITS PRs) merged.

I checked into that and that trick no longer works as we have given up all handling of C++ options to Kokkos.

@crtrott,

As discussed at the ATDM PI Meeting today, can we put in a short term hack to the Kokkos version in Trilinos to allow us to add `-std=c++14` to the commandline instead of `-std=c++11` to allow the setup of a C++14 PR ASAP?  Perhaps we  set a temporary (undocumented) cache var like:

```
-D Kokkos_USE_CXX_STD=14
```

that would result in the Kokkos CMake logic putting in `-std=c++14` instead of `-std=c++11`?  We might even be able to hack that into the file:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/ProjectCompilerPostConfig.cmake

(by pulling out `-std=c++11` and putting in `-std=c++14`)?

Otherwise, I have a few things that need to get done and then I can push to get #6814 merged (and the related Kokkos and TriBITS PRs merged).  (And finish getting SPARC ready for this.)

**Comment by bartlettroscoe** [comment]
CC: @crtrott 

@trilinos/framework,

@ibaned just reported in an offline email that setting:

```
-DKokkos_CXX_STANDARD=14
-DCMAKE_CXX_EXTENSIONS=OFF
```

Should result in `-std=c++14` getting added to the Trilinos compile line instead of `-std=c++`.

Can you please try that out and update the GCC 8.3 PR to use that to turn on C++14 support in Trilinos?

**Comment by bartlettroscoe** [comment]
CC: @prwolfe, @jwillenbring, @crtrott, @ibaned, @rppawlo, @mwglass 

FYI: PR #6814 is now merged to 'develop' so Trilinos now allows you to set:

```
-DCMAKE_CXX_STANDARD=14
```

Now sure how this will with the Kokkos option `Kokkos_CXX_STANDARD`.

Also note that now Trilinos has `CMAKE_CXX_EXTENTIONS=OFF` set by default as well.

Now someone just needs to update the GCC 4.8.3 PR to enable C++14.

**Comment by jwillenbring** [comment]
The PR for this has been merged, but this wasn't yet closed. Closing now.
