### ISSUE TITLE
Framework: correct location of mirrored repo for nightly testing?

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#6971]
@trilinos/framework @jwillenbring @bartlettroscoe 

Has the location of the mirrored Trilinos repo on software changed?  MueLu's nightly tests pull from `software.sandia.gov:/space/git/nightly/Trilinos`, but it looks like this hasn't been updated since July 2019:

```commit 4442eef9d9a9e670a5fb6eea5be8972cf0a4a3f1 (HEAD -> develop, origin/develop, origin/HEAD)
Merge: bd9ea512b8 04d3bbb122
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Mon Jul 15 16:53:15 2019 -0600

    Merge Pull Request #5529 from rppawlo/Trilinos/phalanx-remove-dim-tags-files
    
    Automatically Merged using Trilinos Pull Request AutoTester
    PR Title: Phalanx remove deprecated code
    PR Author: rppawlo


```

**Comment by bartlettroscoe** [comment]
@jhux2, why are these builds not building against Trilinos 'develop' in git@github.com:trilinos/Trilinos.git?  If you want a branch that gets updated the same time each day and then stays constant all day, you might consider testing against the 'atdm-nightly' branch in this git repo.

Better question is how is it that it takes until March 2020 to notice that builds are not getting updated since July 2019?

**Comment by jhux2** [comment]
> why are these builds not building against Trilinos 'develop' in [git@github.com](mailto:git@github.com):trilinos/Trilinos.git? If you want a branch that gets updated the same time each day and then stays constant all day, you might consider testing against the 'atdm-nightly' branch in this git repo.

Because that's the way we were advised to do things years ago, and how Brent P. had set things up.

**Comment by jhux2** [comment]
From an email:
"The experimental and continuous builds should be pulling from github directly.  This is done mostly so that the those builds don¹t have to wait for the nightly repo to update. Everything else pulls from the nightly repo on software to ensure that they are all building the same version of Trilinos. Otherwise we could run into an issue where one build fails, someone fixes the problem and then other builds don¹t have the same error making it seem like the one build was a fluke."

**Comment by rppawlo** [comment]
At one point we needed the software mirror for testing because we were hitting github so much that the repo pulls would timeout. The mirror fixed the timeouts. We needed the same strategy for Drekar as well. I suspect someone's cron job that did the updating is no longer working. There were special scripts that Brent had for this.

**Comment by bartlettroscoe** [comment]
If you space out starting the git clone/pull then you don't see problems pulling directly form github.  At least that is the experience over the last 1.5 years of ATDM Trilinos testing.  Git pulls from github have been pretty robust.

**Comment by jhux2** [comment]
We've resolved this by having the MueLu nightly tests pull from a fork that is updated at the same time every evening.  This basically the same process as before, but not using the machine "software".

**Comment by cgcgcg** [comment]
Looking at the dashboard, it seems that all ascic builds are still trying to pull from 'software'..

**Comment by jhux2** [comment]
@cgcgcg Good catch.  I don't see those in the drivers subdirectory, so maybe those are jenkins controlled.
