### ISSUE TITLE
 Add new cdash "Nightly" build tracks/groups

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#702]
@trilinos/framework @maherou 

We spoke on Tuesday morning about creating a new track for test results in CDash for build that must pass. Currently, we have nightly, release, and experimental. The focus of this ticket will be to create a new track, tentatively called "clean" for builds that we want to require to be 100% clean. For builds that are more than experimental, but people don't want to enforce 100% clean status, they could continue to use nightly. When a nightly build is clean, we can promote it. Part of this would also be to not notify people of failures on the nightly track anymore.

Please comment if you would prefer a different strategy. The goal is to establish an expectation that certain builds must always pass. If they aren't passing, they need to move to a different track, the build needs to be modified, or hopefully in most cases, the defect reflected in the failure will be fixed.

**Comment by bartlettroscoe** [comment]
Sounds like a good approach.  It would be good if CDash would allow people to create their own CDash accounts and then sign up to get CDash emails for specific builds they care about.

**Comment by bartlettroscoe** [comment]
As described in https://github.com/trilinos/Trilinos/issues/1182#issuecomment-292621320, We are doing this right now.

**Comment by jwillenbring** [comment]
The updated plan is to create 2 new tracks "Clean" and "Specialized". While some of the exact details of the long-term policy are still in flux, due to anticipated changes in pull-request and develop->master testing, and determinations of exactly how many builds there will eventually be, etc, here are the definitions of the new tracks, as well as the slightly repurposed "Nightly" track. These changes recognize the fact that currently there is no granularity in our dashboards results. Failures are either important "Nightly" or not important "Experimental". Therefore there is no way to flag the highest priority builds, and everything is treated as medium priority because if everything is the highest priority, then nothing is.

Clean: This track will contain the highest priority builds.  For stable builds of project-wide interest. Notifications will be sent for all failures on this track.

Nightly: This track is for stable builds of project-wide interest. These builds are to be kept clean, but with a lower priority than the "Clean" track. Failures in these builds should be by-definition important. If it is found that cleaning up a failure is not a high priority, the failing test or part of the build should be disabled, or the whole build should be moved to the Specialized or Experimental track. One category of builds that MIGHT end up on this track is builds that are harder for a typical developer to reproduce the failures in due to resource or accessibility limitations of some kind.

Specialized: This track is for builds that are important, but less important than Nightly builds. For example, the builds might be important primarily to an individual package team or customer. While some builds of narrower interest might be included in NIghtly builds, that would be determined by Trilinos leadership. Another category of builds appropriate for this track is new builds that are in the process of being actively stabilized. A key difference between Clean/Nightly and Specialized builds is that Trilinos developers at large are not responsible for monioring failures in Specialized-track builds. That is not to say that other Trilinos developers should not be responsive to issues filed for Specialized builds. The stability of Specialized builds will depend largely, but not exclusively on the level of effort that the build "sponsor" invests in achieving stability.

**Comment by bartlettroscoe** [comment]
Overall, this seems like a rational strategy.  But there are a few details that need to be dealt with.

First, we should name these new tracks "Nightly Clean" and "Nightly Specialized".  That is because CDash treats "Nighty" builds (actually called "Build Type" "Daily" in the CDash Group configuration settings) in a special way (i.e.  only the results from the latest build are shown for the testing day; previous results are ignored and hidden).  Also, the precedent for the "Nightly" prefix has already been established by the release testing groups like "Nightly Release 12.10" (and not just "Release 12.10 ")

Second, what about CDash emails?  What CDash tracks will CDash emails go out for to the various registered package regressions lists?  I would argue that initially, they should only go out for "Clean Nightly" and only builds that have 100% passing builds and tests can be moved to that category.  
I am not sure about project-wide CDash emails for the "Nightly" builds.  My guess is that it will take a long time (if ever) for builds in this category to get clean.  And we can't be spamming people with CDash emails for long standing failures.  That has to stop right now and we need to get people to delete all of their CDash email filters.  Note that we can't ever turn on project-wide CDash emails for the new "Nightly Specialized" group.  Therefore, the only way that interested stakeholders are going to get email notifications is if we get Kitware to implement more flexible email notification schemes (such as described in [this backlog item](https://docs.google.com/document/d/1TLHRp8eTNKw7udOhwIxrOYShXQUbxAzsXeOq5cwWnKM/edit#bookmark=id.vzxu6mcftmqo)).

Third, what build groups will be included in the "Subproject Summary" page:

* http://testing.sandia.gov/cdash/viewSubProjects.php?project=Trilinos

?  This should likely contain just "Nightly Clean" and "Nightly" and not "Nightly Specialized".  But if we can get Kitware to implement filters for that page (as described in [this backlog item](https://docs.google.com/document/d/1TLHRp8eTNKw7udOhwIxrOYShXQUbxAzsXeOq5cwWnKM/edit#bookmark=id.jruax0qqqfuc)), then it would make sense to perhaps also include "Nightly Specialized" builds as well.  But that is not a big of an issue IMO.

The most important things to fix right now are:

1) Stop spamming people with never ending CDash error emails so that they can delete their email filters.

2) Make it clear what the important builds are (and I think this proposal does that).

3) Get Trilinos developers to pay attention to and to fix the important builds ASAP (and only getting CDash emails for the important build will help with this).

Also note that we are now allowed to use tags like "Sierra" and "ATDM" in our GitHub issues, and I would also assume, our Trilinos builds shown on CDash.  So we can add "ATDM" to the names of ATDM-targeted builds and "Sierra" to Sierra-targed biulds.

This set of new tracks should be documented on the Trilinos wiki page:

* https://github.com/trilinos/Trilinos/wiki/Policies--%7C-Testing

either before or as this gets implemented.

**Comment by jwillenbring** [comment]
> First, we should name these new tracks "Nightly Clean" and "Nightly Specialized". That is because CDash treats "Nighty" builds (actually called "Build Type" "Daily" in the CDash Group configuration settings) in a special way (i.e. only the results from the latest build are shown for the testing day; previous results are ignored and hidden). Also, the precedent for the "Nightly" prefix has already been established by the release testing groups like "Nightly Release 12.10" (and not just "Release 12.10 ")

Has this been fixed to actually work this way? The behavior I have seen is that multiple nightly builds are just stacked into the same row in the dashboard, making them even harder to decipher than the experimental section. I strongly dislike this behavior, but I thought that is what they had to do since there were multiple labels submitted per row anyway.

> Second, what about CDash emails?

The tentative plan is to have "normal" emails for "Clean"/"Nightly Clean" track, and either no emails, or maybe if we can get them to work nicely and in a way that is obviously distinct from the clean builds, we might try the "summary" email option for the nightly track. Unless we can get very targeted emails for the "Specialized"/"Nightly Specialized" builds, I don't plan to send emails for those.

> That has to stop right now and we need to get people to delete all of their CDash email filters.

I won't go this far. The requirement should be that people deal with failures quickly, if they can filter and do that, I think it is too intrusive to specify at a fine level of granularity what process they should use.

> Third, what build groups will be included in the "Subproject Summary" page

At a first pass, I think clean and nightly, whatever they are called. Those are the tracks the whole project will be asked to monitor.

> This set of new tracks should be documented on the Trilinos wiki page

Yes

**Comment by jwillenbring** [comment]
The new "Clean" and "Specialized" tracks have been created. I still need to add a discussion of the tracks on the Trilinos wiki. @william76 is working on a plan to divide existing builds into these three tracks (2 mentioned plus Nightly).

**Comment by william76** [comment]
Adding a link to the issue in Tribits that's related to this issue w/rt pointing test builds at different tracks in CDash: [Tribits:189](https://github.com/TriBITSPub/TriBITS/issues/189) 

@jwillenbring I can start moving builds over to "Clean" and "Specialized" later today.  I'd like to fill in a couple details first:
- "Clean" is the high-tier CDash (rank 1)
- "Specialized" is the low-tier track in CDash (rank 3)
- What's the mid-tier track named?  I don't believe I have that written down anywhere :(

I can start moving builds over to "Clean" and "Specialized" later today in my fork per the initial sorting that I sent you as part of issue #1182 since it's related to this issue as well.

**Comment by jwillenbring** [comment]
These tracks have been created, so I am closing this ticket. Next is to document the track as stated in #1293, and to clean up all Clean builds, which I will file ticket for soon.
