### ISSUE TITLE
TriBITS:  Need to specify dependencies between sub packages

### ISSUE THREAD

**Issue by srajama1** [trilinos/Trilinos#7053]
TriBITS does not allow dependencies between sub packages requiring round about ways to specify dependencies. See for example the dependencies between ShyLU-DD and ShyLU. We have to do this because of TriBITS.

@bartlettroscoe

**Comment by bartlettroscoe** [comment]
@srajama1, this goes back many years but adding the ability for subpackages to intermeingle dependencies with other subpackages would massively increase the complexity of TriBITS.

Let's talk about what is trying to be achieved with the ShyLU, ShyLU_DD and ShyLU_Node TriBITS packages and what will fix that problem and help users avoid problems encountered by trying to do:

```
  -DTrilinos_ENABLE_ShyLU=ON \
  -DTrilinos_ENABLE_ShyLU_DD=OFF \
```

and them getting the error:

```
   ***
   *** ERROR: Setting Trilinos_ENABLE_ShyLU=OFF which was 'ON' because ShyLU has a required library dependence on disabled package ShyLU_DD!
   ***
```

(which happened to SPARC).

**Comment by srajama1** [comment]
-DTrilinos_ENABLE_ShyLU=ON \
  -DTrilinos_ENABLE_ShyLU_DD=OFF \

This option is not supported, SHYLU_DD is required for ShyLU and users should just enable ShyLU or not. This issue is request for TriBITS, if you don't want to do it you can close it won't fix. I will have it as a documentation as why we need to jump through hoops in ShyLU.

**Comment by bartlettroscoe** [comment]
> This issue is request for TriBITS, if you don't want to do it you can close it won't fix. I will have it as a documentation as why we need to jump through hoops in ShyLU.

As the maintainer of TriBITS, I feel this allowing subpackages put in dependencies on subpackages both upstream and downstream adds a level of complexity, breaking hundreds of TriBITS packages, and adds significant configure-time expense (because you need to sort all of your subpackages by their dependencies) is not worth benefit we get from it.  Again, we should talk about this and see if what is there now is best serving users (given the current constraints of the TriBITS framework and the relationship between TriBITS packages and subpackages).
