### ISSUE TITLE
MueLu: building tutorial does not generate proper executables

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#7061]
@trilinos/muelu 

Reported by a user:

"I am trying to work through the MueLu tutorial https://trilinos.github.io/pdfs/MueLu_tutorial.pdf and ran into an error when doing the first example:
 
![image](https://user-images.githubusercontent.com/12970120/77177047-23f87680-6a82-11ea-86ae-bb12ef4ba97a.png)

The example complains that it cannot find the executable, MueLu_tutorial_laplace2d.exe. I noticed a file called laplace2d.cpp in the src folder so I tried to compile it:
 
Do you have a recommended process for compiling this file…and the other one that is required in the tutorial, MueLu_tutorial_MLParameterList.exe (I would guess coming from MLParameterList.cpp)?"

**Comment by mayrmt** [comment]
@jhux2 Have MueLu tests and examples been enabled via configure options `-D MueLu_ENABLE_TESTS:BOOL=ON` and `-D MueLu_ENABLE_EXAMPLES:BOOL=ON`? The tutorial's [README lists them as required](https://github.com/trilinos/Trilinos/blob/master/packages/muelu/doc/Tutorial/README#L4).

This should generate the executables. Yet, there's another known issue due to changes in screen output when attempting to re-build the tutorial document. See #3758.

I happened to talk to @tawiesn recently about the MueLu tutorial on a more general note. I'll keep this in mind for our next meetings.

**Comment by jhux2** [comment]
@mayrmt Thank you for the suggestions, I'll forward them to the person who asked.

**Comment by mayrmt** [comment]
A student has ported the tutorial to another format, such that testing the build of the tutorial is possible. Still need to include this into the build system...

I hope to share a first implementation in the first weeks of January.

**Comment by mayrmt** [comment]
Closing, since there seems to be no problem anymore. (Other issues related to the MueLu tutorial are covered by #10608, #3758.)
