### ISSUE TITLE
Teuchos: Encapsulate Kokkos profiling region + Teuchos::TimeMonitor

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#7072]
## Enhancement
@trilinos/teuchos @rppawlo 

### Summary

We want an interface that abstracts over Kokkos profiling regions, `Teuchos::TimeMonitor`, stack timers, and all sorts of timing things.  We want this for the following reasons:

  1. (Seriously, do I need to explain why encapsulating N different timer libraries in one interface is a good idea?)
  2. Kokkos profiling regions currently incur overhead due to extra fences, so Trilinos wants to be able to turn off using them even if the user has loaded a profiling library at run time.
  3. We've seen stack timers incur overhead for large numbers of timers and/or deep stacks, so users might want to turn them off, perhaps even at run time.

### Desired features

  - The interface should live in Teuchos, so that downstream solver packages like MueLu that do not require Kokkos can use it, and so that Kokkos is not forced to be MPI-aware.
  - It should be able to distinguish recursive calls (e.g., for different levels of a multigrid hierarchy in MueLu), and in general should have features like those of `Teuchos::StackedTimer`.

### What's annoying about current interfaces

  - There are too many of them (`Teuchos::Time`, `Teuchos::TimeMonitor`, `Teuchos::StackedTimer`, Kokkos profiling regions, whatever MueLu's thing is, ...).
  - They all look and behave differently.
  - Developers don't use all of them consistently, so users see different timers, depending on which interface(s) they enable.
  - Some interfaces (e.g., `Teuchos::Time`) have an option to use other interfaces (e.g., Kokkos profiling regions), so unwitting developers may be "double-timing" some regions.
  - Developers have a habit of selectively enabling some timers at compile time by sprinkling macros like `HAVE_TPETRA_MMM_TIMINGS` all over the code.  Whatever is inside those macros doesn't get tested and might not even build.  Users don't have a way to enable those timers without manually changing the code and rebuilding.
  - Developers have a habit of doing ugly things like managing scope guards by pointer instead of by value.  This leads to issues like https://github.com/trilinos/Trilinos/issues/2804 .

### What we have now

It turns out that `Teuchos::Time`, and therefore `Teuchos::TimeMonitor`, already have an option to use Kokkos profiling regions, in addition to its native timer.  `Teuchos::Time` calls `pushRegion` [here](https://github.com/trilinos/Trilinos/blob/4e2aa2f8354d3826292a7e68dda3875a0d1ca161/packages/teuchos/core/src/Teuchos_Time.cpp#L129) and `popRegion` [here](https://github.com/trilinos/Trilinos/blob/4e2aa2f8354d3826292a7e68dda3875a0d1ca161/packages/teuchos/core/src/Teuchos_Time.cpp#L152).  (`HAVE_TEUCHOS_KOKKOS_PROFILING` is defined by default if you have both Kokkos and Teuchos enabled.)

This is not true of `Teuchos::StackedTimer`, which for some reason doesn't use `Teuchos::Time`.  I'm not sure what the MueLu thing does.

`Tpetra::Details::ProfilingRegion` is currently just a wrapper around Kokkos' profiling regions.

### Suggested solution

  1. Decide on an interface.
  2. Use it consistently.

Don't repeat the `ParameterList` debacle.  Pick something and use it consistently throughout Trilinos.  Put it somewhere where every package can use it.

**Comment by csiefer2** [comment]
Already working on a Tpetra::Details::ProfilingRegion band-aid for this.

**Comment by mhoemmen** [comment]
@csiefer2 `Teuchos::StackedTimer` doesn't use `Teuchos::Time`, though.  Perhaps that would be the one fix for this issue.

**Comment by csiefer2** [comment]
@mhoemmen Correction. I'm using Teuchos::TimeMonitor (which is what MueLu does), which plays nicely with Teuchos Timers, either flat or stacked.

**Comment by csiefer2** [comment]
(As an aside, a nice, unified timing interface, implemented in Teuchos, sounds nice).

**Comment by ibaned** [comment]
![](https://imgs.xkcd.com/comics/standards.png)

**Comment by csiefer2** [comment]
@ibaned So, so true...

**Comment by bartlettroscoe** [comment]
We don't need "the standard" interface, just the Trilinos standard interface.

**Comment by rppawlo** [comment]
A quick comment. The StackedTimer was never meant to be used internally in Trilinos packages. It requires an explicit stop() so it is not exception safe. It was meant to be complementary to TimeMonitor to get out the extra information about levels. It was added to trilinos so that it could include time monitor information. There are ifdefs to disable StackedTimer independent of TimeMonitor if StackedTimer was causing unacceptable overhead. I thought the official  interface for Trilinos was TimeMonitor due to the exception safety issue. Maybe Ross's old Trilinos developer guide had a section on that?

That being said, the apps have not been bothered by the exception safety issue and actually prefer to use StackedTimer directly. So both empire and sparc are using it.

@bathmatt also wrote a custom kokkos-tool that adds kokkos profiler info to stacked timer.

What would be the drawbacks to making TimeMonitor the official interface? What is the appeal of using the Teuchos::Timer directly?

**Comment by csiefer2** [comment]
TimeMonitor is what we use in MueLu, so that's fine by me.  I like how you can use it with StackedTimer (via Teuchos::TimeMonitor::setStackedTimer() ) or not, your choice.

Nobody seems to really care about exception safety, it seems like the vast majority of exceptions issued in Trilinos aren't caught and lead to direct termination anyway.

**Comment by bartlettroscoe** [comment]
> Nobody seems to really care about exception safety, it seems like the vast majority of exceptions issued in Trilinos aren't caught and lead to direct termination anyway.

There are some exceptions that are used for exceptional (i.e. rare) flow control that are not just errors that should always abort a program.  For example, see the exception `CatastrophicSolveFailure` thrown from the function [`Thyra::LinearOpWithSolveBase::solve()`](https://docs.trilinos.org/dev/packages/thyra/doc/html/classThyra_1_1LinearOpWithSolveBase.html#ac7c5b4c8553833778e88e3fb627c4009).  I would argue this is exactly is exactly where you want to use an exception (since local code usually can't deal with a catastrophic solve failure).  (But higher-level code can often deal with a catastrophic solve error like shortening the timestep or adding larger positive values to the diagonal, etc.)

Let's not be "that code" that is not exception safe/correct.

**Comment by bartlettroscoe** [comment]
> Maybe Ross's old Trilinos developer guide had a section on that?

Yup, there was an attempt at that.  See "GCG 19: Use Teuchos::Timer and Teuchos::TimeMonitor" in the draft document "Trilinos C++ Coding and Documentation Guidelines".  It says:

> GCG 19: Use `Teuchos::Timer` and `Teuchos::TimeMonitor` to provide timing
information, always namespace the names of timers to avoid name collisions, and allow
users to control when they are enabled or not [Strongly Recommended, Interoperability,
Common Look & Feel]: To properly support timers in Trilinos, do the following (where
`<UCPACAKGENAME>` is the upper-case package name such as `THYRA`, `RYTHMOS`, etc.):
>
> – Add `PACKAGE ADD ENABLE TEUCHOS TIME MONITOR OPTION()` to the package’s top-level
`CMakeLists.txt file`.
> – Add `@<UCPACAKGENAME> TEUCHOS TIME MONITOR DECLARATIONS@` to the packages
`${PACKAGE NAME} config.h.in` file.
> – To add timers to specific C++ functions, in the body of the functions add calls to
`<UCPACAKGENAME> FUNC TIME MONITOR("<PACKAGENAME>: Somefunction()")` and
`<UCPACAKGENAME> FUNC TIME MONITOR DIFF("<PACKAGENAME>: Somefunction():
some part", SomePart)` (the latter when there is more than one timer in a function).
>
> The macros `<UCPACAKGENAME> FUNC TIME MONITOR[ DIFF]` have empty definitions when
timers are disabled.

Since that document did not go anywhere (there was a vocal minority that pushed back at any common guidelines in Trilinos), where would Trilinos standards/guidelines/recommendations even get expressed where people would see them?

Where did the TrilinosDoc git repo even go to?  I think there is where that draft was.

**Comment by mhoemmen** [comment]
@rppawlo wrote:
> the apps have not been bothered by the exception safety issue

I'm sad about that as a purist, but I'm not so worried about that in practice.  My main concern is the lack of a common interface.  Apps won't be able to take advantage of all the tools going into Kokkos profiling, if their timing interface doesn't use Kokkos' interface.  Multiple redundant interfaces hinder fixing bugs and plugging in new features, and they make life hard for new developers.

@bartlettroscoe wrote:
> there was a vocal minority that pushed back at any common guidelines in Trilinos

I think it would pay to reevaluate that decision, especially since I suspect more Trilinos developers these days are responsible to apps and have software-related deliverables.  There are plenty of developers who are eager to appear like they care about software quality, and approving and following a set of guidelines might help them achieve that goal.

**Comment by mhoemmen** [comment]
begone autobot, this issue is important
