### ISSUE TITLE
Trilinos::Initialize() or Trilinos::ScopeGuard() capability

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#7123]
## Enhancement

Many packages (e.g., @trilinos/zoltan2, @trilinos/muelu) are adding dependence on Kokkos.  Thus, applications using them need to call Kokkos::initialize before using the package.  But users may not know that they now need to call Kokkos::initialize, especially if they are not using Kokkos directly.  Runtime error messages may not indicate what the real problem is (e.g., #7117 ).

One solution would be to create a Trilinos::ScopeGuard(narg, argv) or Trilinos::initialize(narg, argv) function that would ensure that all the relevant libraries/packages (MPI, Kokkos) are initialized.  Kokkos and Tpetra both have ScopeGuard functions, but a user of higher-level packages may not know that Kokkos and Tpetra are needed for the higher-level package that they are using.   

Another solution would be for each package to have Package::ScopeGuard(narg, argv) or similar that initializes what the package needs.  For example, @trilinos/zoltan has Zoltan_Initialize(narg, argv), and @trilinos/tpetra has Tpetra::ScopeGuard(narg, argv).  The challenge with this approach is ensuring that command-line arguments narg and argv are passed to the appropriate place for use in the package-level initialization (so they can be passed to MPI and Kokkos).

What are your thoughts?  What other approaches might work?

@rppawlo @srajama1 @jhux2 @csiefer2 @jwillenbring @mperego @bartlettroscoe @hkthorn

**Comment by csiefer2** [comment]
Is Zoltan2 using Tpetra under the hood in a way that isn't obvious to the user?

In the case of Ifpack2/Xpetra/MueLu the user is handing in a Tpetra object (if we're using Tpetra), so the initialize() call has to be done way before it gets to us...

**Comment by bartlettroscoe** [comment]
Can't we just add Kokkos initialization by default to [`Teuchos::GlobalMPISession()`](https://docs.trilinos.org/dev/packages/teuchos/doc/html/classTeuchos_1_1GlobalMPISession.html) if Kokkos is enabled?  There is already a bunch of code that calls that to initialize MPI (like for unit test harness, etc.).  The TeuchosCore subpackage where that exists already optionally depends on the KokkosCore subpackage that defines `Kokkos::initialize()`.  In fact, the current implementation of  `Teuchos::GlobalMPISession()` is already calling `Kokkos::finalize_all()` automatically.  Why don't we have it also call `Kokkos::initialize()` too?

We can set it up so that `Teuchos::GlobalMPISession()` does not call `Kokkos::initailize()` if a particular APP does not want that (by passing in another optional argument to the constructor). But for unit testing, this makes things so much easier.

What about that plan?

**Comment by kddevin** [comment]
@bartlettroscoe Conceptually, I don't mind adding Kokkos::Initialize to Teuchos::GlobalMPISession.  Aesthetically, initializing Kokkos in something called GlobalMPISession seems wrong, since Kokkos has nothing to do with MPI and, indeed, can be used in non-MPI applications.

The bigger issue is that applications don't have to call Teuchos::GlobalMPISession.  If one uses Tpetra::ScopeGuard, for instance, one doesn't call Teuchos::GlobalMPISession.  We're hacking lots of different mechanisms into Trilinos to accomplish, essentially, Trilinos::initialize().

@csiefer2 captures the problem in Zoltan2.  The user may pass data to Zoltan2 in a non-Kokkos, non-Tpetra data structure (e.g., Epetra CrsMatrix or  C arrays).  But under-the-covers, Zoltan2 uses Kokkos and Tpetra to do some of its operations.  So the user may have no idea about Kokkos, Teuchos, or Tpetra and, thus, not know to initialize them.

**Comment by bartlettroscoe** [comment]
@kddevin, okay this is targeted to users primarily, not code in Trilinos?  Is it the customer who is expected to call this thing or code inside of Trilinos itself?  I am guessing this will be at the top of the customer's `main()` function?

But the name "ScopeGuard" is a terrible name for something that read/writes `argv` and `argc`.  That name makes one thing of RAII (Resource Allocation Is Initialization) but one does not expect such a thing to read from `argv` and `argc` which is a major program initialization thing.

The name "initialize" by itself is not the greatest because it would be nice if it was an object that called finalize on destruction (RAII style) when it went out of scope.  That is why it would be nice to associate this with program initialization and finalization and therefore MPI initialization and finalization.

And having the name `Trilinos` seems non-ideal because "Trilinos" is not going to be precisely defined in the future at some point.

Given all of this, I guess `<PackageName>::GlobalInitalizerFinalizer globalInitFinal(argc, argv)` as the constructor for a stack-based object of type `<PackageName>::GlobalInitalizerFinalizer` in `main()` is the most general and obvious, but that creates a lot of boiler-plate code and files in every Trilinos package (or at least several of them).
