### ISSUE TITLE
Best way to eliminate warnings

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#722]
@trilinos/xpetra  Xpetra has a number of these types of warnings:

```
Xpetra_EpetraIntVector.hpp(385): warning: statement is unreachable

385      int dot(const Vector<Scalar,LocalOrdinal,GlobalOrdinal,Node> &a) const { XPETRA_MONITOR("EpetraIntVectorT::dot"); TEUCHOS_TEST_FOR_EXCEPTION(-1, Xpetra::Exceptions::NotImplemented, "TODO"); return -1; }
```

It would be great to keep the exception and eliminate the warning, without removing the return value, which would generate another type of warning.  Is this possible, short of implementing the method?

Pragmas are not an option it seems, as the option `--Wunreachable-code` has been a no-op in g++ for a long time;  see this [link](https://gcc.gnu.org/ml/gcc-help/2011-05/msg00360.html).

**Comment by mhoemmen** [comment]
Compilers are smart enough these days to realize that the function doesn't return.  I've found that I'm able to remove the superfluous return statements without causing warnings.

btw, I would recommend using `TEUCHOS_TEST_FOR_EXCEPTION(true, ...)` instead of -1 (-1 is true only because it doesn't equal 0, whereas `true` is, well, true ;-) ).

**Comment by jhux2** [comment]
> Compilers are smart enough these days to realize that the function doesn't return. I've found that I'm able to remove the superfluous return statements without causing warnings.
> 
> btw, I would recommend using TEUCHOS_TEST_FOR_EXCEPTION(true, ...) instead of -1 (-1 is true only because it doesn't equal 0, whereas true is, well, true ;-) ).

@mhoemmen Thanks, I'll try your suggestion.

**Comment by jhux2** [comment]
Superceded by #1148.
