### ISSUE TITLE
All CUDA builds: many warnings about "host/device annotation ignored on explicitly defaulted fn"

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#7314]
## Question

On any CUDA build, in several packages, I see a lot of warnings like this:
```
/ascldap/users/bmkelle/PerfTesting/Trilinos/packages/sacado/src/KokkosExp_View_Fad_Contiguous.hpp(1030): warning: __host__ annotation is
ignored on a function("~ViewMapping") that is explicitly defaulted on its first declaration
```

The lines causing these look like ``KOKKOS_INLINE_FUNCTION type foo() = default;``. My question is, does nvcc automatically generate device versions of explicitly defaulted functions? If it does, we should try to remove the KOKKOS_INLINE_FUNCTION from these to stop the warnings.

**Comment by brian-kelley** [comment]
Maybe @trilinos/kokkos knows the answer to this

**Comment by rppawlo** [comment]
@etphipp

**Comment by etphipp** [comment]
If I recall, the issue here was that early cuda versions required __device__ on these functions for correct behavior, and then later cuda versions started warning about it. In fact, I believe it was the case (at least for cuda 9?) that even though nvcc warned about it, you still had to have __device__ annotations for correct code.  Maybe this has been fixed now.

**Comment by brian-kelley** [comment]
@etphipp OK, thanks! I'll just close this then, since I don't think it's worth making a version-specific macro for defaulted functions. Maybe in the future when we don't support CUDA 9 we can get rid of the annotations.

**Comment by ibaned** [comment]
Just for completeness, I can explain what is going on here. Let's say you have a defaulted function like this:
```cpp
class foo {
  double member;
 public:
  foo(foo const& other) = default;
};
```
If class `foo` is to be copy constructed on the device, then the requirements for the copy constructor vary by CUDA version:
1. CUDA 8 and earlier required the following:
```cpp
  __host__ __device__ foo(foo const&) = default;
```
2. CUDA 9 will say that `__host__ __device__` is ignored on this function, but that is a lie because if you remove them your code will segfault. So it still requires:
```cpp
  __host__ __device__ foo(foo const&) = default;
```
3. CUDA 10 says the same thing, but this time it is true, and if you remove `__host__ __device__` then the function will work fine in device code anyways:
```cpp
  foo(foo const&) = default;
```
Kokkos implemented the following strategy for dealing with this:
1. CUDA 8 and earlier:
```cpp
#define KOKKOS_DEFAULTED_FUNCTION __host__ __device__
```
2. CUDA 9: add to the build system a special diagnostic suppression flag (did I mention CUDA 9's warning can't be silenced in the usual sane way?) and still do this:
```cpp
#define KOKKOS_DEFAULTED_FUNCTION __host__ __device__
```
3. CUDA 10:
```cpp
#define KOKKOS_DEFAULTED_FUNCTION
```
So when using Kokkos you want to use that macro:
```cpp
class foo {
  double member;
 public:
  KOKKOS_DEFAULTED_FUNCTION foo(foo const& other) = default;
};
```
And also make sure you use the flags Kokkos gave you in your build system. If there are functions in Kokkos that don't use that macro, then first please ensure you're using the latest version of Kokkos and if so file an issue with Kokkos.

**Comment by brian-kelley** [comment]
@ibaned Awesome, had no idea that macro exists. When I get a chance I'll go through and squash those warnings. (When I opened this issue, I was doing a CUDA 10 build, so as far as I know the CUDA 9 warning suppression works)

**Comment by brian-kelley** [comment]
Opened #7324 to fix all of these.
