### ISSUE TITLE
pytrilinos in 12.8.1 breaks

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#744]
See attachment.
[100crash.txt](https://github.com/trilinos/Trilinos/files/556839/100crash.txt)

**Comment by mhoemmen** [comment]
Here is what appears to be the most relevant line of the above build failure:

```
.../trilinos/build-12.8.1/packages/PyTrilinos/doc/Doxygen/Tpetra_dox.i:16046: Error: Syntax error in input(1).
```

**Comment by wfspotz** [comment]
Tpetra_dox.i is a generated file, so I would need to see it to diagnose the error.

**Comment by mhoemmen** [comment]
@wfspotz I just e-mailed Victor to ask him for the file, in case he doesn't get e-mail notifications from Github.

**Comment by mhoemmen** [comment]
@VictorEijkhout wrote:
> That means that one of your files has a syntax error, right? I don’t see how this could be caused by anything that I do.

Don't worry, @wfspotz is not blaming you :-)  It's just that seeing that generated file would help him figure out what SWIG or PyTrilinos may be doing wrong.  It's hard to tell from the error message alone.  (It may also depend on the SWIG version, etc.)

**Comment by VictorEijkhout** [comment]
On Oct 27, 2016, at 3:46 PM, Bill Spotz <notifications@github.com<mailto:notifications@github.com>> wrote:


Tpetra_dox.i is a generated file, so I would need to see it to diagnose the error.

Attached.

Victor.

**Comment by wfspotz** [comment]
@VictorEijkhout, I don't see an attachment. I can see 100crash.txt, but not Tpetra_dox.i.

**Comment by VictorEijkhout** [comment]
Here it is again.

Victor.

On Oct 28, 2016, at 1:12 PM, Bill Spotz <notifications@github.com<mailto:notifications@github.com>> wrote:


@VictorEijkhout<https://github.com/VictorEijkhout>, I don't see an attachment. I can see 100crash.txt, but not Tpetra_dox.i.

**Comment by VictorEijkhout** [comment]
Ok. Beats me why people use git and github. Git is an unintelligible system (see xkcd) and github is a broken hosting platform.

Apparently github ignores my emailed attachements. 

Let's do it here in this web page.

Oh great "We don't support that file type". But apparently that's not worth sending me an error about.

Hold on let me rename it to .txt.
[Tpetra_dox.i.txt](https://github.com/trilinos/Trilinos/files/559173/Tpetra_dox.i.txt)

Totally stupid.

V.

**Comment by VictorEijkhout** [comment]
Sorry. 

V.

**Comment by wfspotz** [comment]
If I enable Tpetra and PyTrilinos and build, and then compare the Tpetra_dox.i I get against Victor's, I see differences between the files associated with changes in the Doxygen documentation comments in the Tpetra header files (note that the Tpetra_dox.i files are over 17,000 lines long, so a complete check by hand is non-trivial, even with ediff). My version compiles just fine. For Victor's, I assume the issue is some funny formatting in the documentation comments, although I wasn't able to track it down specifically.

I think if you pull the latest version of Trilinos from the repository, this should get cleared up. Let me know what happens.

**Comment by VictorEijkhout** [comment]
On Oct 28, 2016, at 6:20 PM, Bill Spotz <notifications@github.com<mailto:notifications@github.com>> wrote:


I think if you pull the latest version of Trilinos from the repository, this should get cleared up. Let me know what happens.


Same problem.

Victor.

**Comment by VictorEijkhout** [comment]
On Oct 28, 2016, at 6:20 PM, Bill Spotz <notifications@github.com<mailto:notifications@github.com>> wrote:

I think if you pull the latest version of Trilinos from the repository, this should get cleared up. Let me know what happens.

FWIW it’s not a compiler issue. It breaks the same way with gcc.

Victor.

**Comment by VictorEijkhout** [comment]
Say, is there a flag to switch off doxygen? I don’t particularly care about the documentation.

Victor.

**Comment by wfspotz** [comment]
Yes, try

    `-D PyTrilinos_DOCSTRINGS:BOOL=OFF`

**Comment by VictorEijkhout** [comment]
> `-D PyTrilinos_DOCSTRINGS:BOOL=OFF`

And with that my build succeeds.

Victor.

**Comment by mhoemmen** [comment]
@wfspotz Does this have something to do with some code upstream of PyTrilinos that we could perhaps fix?  @tjfulle wondered if his introduction of @ Doxygen comments broke something.

**Comment by wfspotz** [comment]
What is happening here is that the build system, during configuration, uses specialized Doxyfiles to generate a set of XML files for each Trilinos package within PyTrilinos. Then a script converts this XML to a SWIG .i file that can be included in the regular .i files. The contents are SWIG directives that add docstrings to the generated Python, the end result being PyTrilinos class and function definitions that contain Doxygen documentation.

This capability has been around since 2007, although originally I would generate the .i files by hand and commit them to the repository. Since August 2014, it has been an automated part of the build system.

The script that converts XML to SWIG has had to be updated a couple times as people have added exotic things to their Doxygen comments. Such as mismatched single or double quotes or Unicode. For the most part, it has been pretty stable.

Any Doxygen syntax should be handled correctly by Doxygen when it creates the XML files. So I don't suspect the `@` directive. I suspect some goofy Doxygen comment, but I haven't found it yet. And my collection of tools processes everything correctly.

**Comment by wfspotz** [comment]
For now, if configuration fails during the creation of PyTrilinos docstrings, the workaround is to set

    -D PyTrilinos_DOCSTRINGS:BOOL=OFF

in your `cmake` invocation.
