### ISSUE TITLE
Panzer: Build times for Cuda are very long

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#7532]
## Enhancement
@trilinos/panzer 

While attempting to sort out the issues on ride I looked to see what was causing the up to 9 hour build times. Turns out two files account for most of this time.

packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_PointValues2.cpp.o
packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_IntegrationValues2.cpp.o

Each of these takes over 6.5 hours to compile both for the Forrester and Garrison nodes. They also consume a good bit of memory during that compile, but the machine has enough to handle that. The rest of Trilinos finishes around 1.5 hours and these two run until the library they are in finally links, then dependencies finish up.

**Comment by bartlettroscoe** [comment]
CC: @rppawlo 

@prwolfe, we are we not seeing anything like this in the ATDM Trilinos builds on 'ride' with Panzer as shown here yesterday:

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2020-06-21&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride-cuda&field2=buildname&compare2=64&value2=-exp

?

Actually, we can go back a few days to last Thursday's results here:

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2020-06-18&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride-cuda&field2=buildname&compare2=64&value2=-exp

that triggered a rebuild of Panzer files (since there were changes to Tpetra) and it showed:

## ATDM

| Site | Build Name | Update | Update Time | Conf Err | Conf Warn | Conf Time | Build Err | Build Warn | Build Time | Test Not Run | Test Fail | Test Pass | Test Time | Test Proc Time | Start Test Time | Labels |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
ride | Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug | 822a15 | 12s | 0 | 21 | 4m 19s | 0 | 41 | 43m 22s | 0 | 2 | 2050 | 1h 43m 34s | 6h 7m 40s | Jun 18, 2020 - 04:06 MDT | (26 labels)
ride | Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug | 822a15 | 12s | 0 | 21 | 3m 12s | 0 | 41 | 1h 49m 32s | 0 | 0 | 2084 | 2h 22m 16s | 8h 41m 42s | Jun 18, 2020 - 04:05 MDT | (26 labels)
ride | Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release | 822a15 | 12s | 0 | 21 | 4m 41s | 0 | 40 | 10m 27s | 0 | 0 | 2085 | 41m 17s | 2h 21m 56s | Jun 18, 2020 - 05:03 MDT | (26 labels)
ride | Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug | 822a15 | 24s | 0 | 21 | 3m 46s | 0 | 41 | 16m 7s | 0 | 0 | 2084 | 1h 10m 54s | 4h 1m 52s | Jun 18, 2020 - 04:07 MDT | (26 labels)

## Experimental


| Site | Build Name | Update | Update Time | Conf Err | Conf Warn | Conf Time | Build Err | Build Warn | Build Time | Test Not Run | Test Fail | Test Pass | Test Time | Test Proc Time | Start Test Time | Labels |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
ride | Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug-pt | 822a15 | 12s | 0 | 2 | 8m 31s | 50 | 49 | 4h 9m 45s | 27 | 17 | 3108 | 3h 38m 18s | 13h 39m 55s | Jun 18, 2020 - 04:19 MDT | (54 labels)
ride | Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt | 822a15 | 12s | 0 | 2 | 4m 57s | 1 | 49 | 22m 58s | 12 | 19 | 3106 | 1h 55m 12s | 6h 56m 17s | Jun 18, 2020 - 04:03 MDT | (54 labels)

Even the crazy-expensive CUDA RDC build `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug-pt` finished in just over 4 hours (rebuilding everything from Tpetra on down).

Why are things so bad with the Trilinos PR CUDA build compared to the ATDM Trilinos CUDA builds on that exact same system?

**Comment by bartlettroscoe** [comment]
CC: @cgcgcg, @rppawlo 

FYI: Once we can merge PR #7508 and once the Trilinos Framework team can fix #7547, then we will be able to see these build stats directly on CDash as part of Trilinos PR testing.

**Comment by prwolfe** [comment]
@bartlettroscoe - I have not triaged the differences, just noted the behavior.

**Comment by prwolfe** [comment]
@bartlettroscoe - can you get me the flags used in your atom build for the Panzer_PointValues2.cpp.o compile please? I would also expect that tpetra would be a dependency on this file, but I would have to verify that this file rebuilt (I know your system gets fewer rebuilds as your history traversal is linear and ours is not.)

Thanks!

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe - can you get me the flags used in your atom build for the Panzer_PointValues2.cpp.o compile please? 

See:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite
* https://github.com/trilinos/Trilinos/tree/develop/cmake/std/atdm/ride

**Comment by prwolfe** [comment]
Wow - if you are clear as to what compile flags show up for that .o from this you are far ahead of me. I just pulled it from the ninja file for ours.

**Comment by bartlettroscoe** [comment]
> if you are clear as to what compile flags show up for that .o from this you are far ahead of me

@prwolfe, compile flags are owned by Kokkos based on the kokkos arch options.  And, of course, you can just build targets side-by-side with `make VERBOSE=1 <target-name>` if you want to see the full compiler flags.

But to compare that ATDM Trilinos configuration and the Trilinos PR configuration, I would recommend using:

*  https://gitlab-ex.sandia.gov/atdm/trilinos-config-diff

**Comment by rppawlo** [comment]
I don't know if we can fix this quickly. Those two files are calling a ton of intrepid2 code. I can try to break up the functions into separate .o files. If that doesn't work we might need to look at adding ETI to intrepid2.

**Comment by prwolfe** [comment]
I wanted to confirm the difference with the ATDM build. The ATDM builds use "-g -O0" and the PR builds use "-O3". I set up the build using

> module li
No Modulefiles Currently Loaded.
> cd tmp.prw/atdm_build/
> source ../Trilinos/cmake/std/atdm/load-env.sh cuda
> cmake -GNinja -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake -DTrilinos_ENABLE_TESTS=ON  -DTrilinos_ENABLE_Panzer=ON
> time make CMakeFiles/panzer-disc-fe.dir/Panzer_PointValues2.cpp.o
ninja -C ../../../..  packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_PointValues2.cpp.o
ninja: Entering directory `../../../..'
[1/1] Building CXX object packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_PointValues2.cpp.o

real	247m51.405s
user	247m46.648s
sys	0m2.589s
> time make CMakeFiles/panzer-disc-fe.dir/Panzer_IntegrationValues2.cpp.o
ninja -C ../../../..  packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_IntegrationValues2.cpp.o
ninja: Entering directory `../../../..'
[0/1] Building CXX object packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_IntegrationValues2.cpp.o
real	340m9.225s
user	340m3.172s
sys	0m3.851s

So even with -O0 either of these files took longer than all the rest of Trilinos at -O3 (120 minutes).

**Comment by bartlettroscoe** [comment]
> The ATDM builds use "-g -O0" and the PR builds use "-O3"

@prwolfe, in short, no.  Debug ATDM Trilinos builds use `-g -O0` but optimized builds use `-O3`.  How did you determine this?

The compiler flags used depend on the value of `CMAKE_BUILD_TYPE` being set which is set indirectly in the build-name with the `<release-debug>` keyword.  See:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#release_debug

For example, the ATDM Trilinos build `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug` on CDash shown at:

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2020-06-23&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug&field2=buildname&compare2=64&value2=-exp

uses the compiler flags `-expt-extended-lambda -lineinfo -arch=sm_37  -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored -O3 -DNDEBUG   -std=c++11`.  You can actually see that on CDash at:

* https://testing-dev.sandia.gov/cdash/viewBuildError.php?buildid=5559673

showing `"-expt-extended-lambda" "-lineinfo" "-arch=sm_37" "-Xcudafe" "--diag_suppress=esa_on_defaulted_function_ignored" "-O3" "-DNDEBUG" "-std=c++11"`.

**Comment by prwolfe** [comment]
> How did you determine this?

I used 'ps | grep' during the compilation using the connamds in the note above.

**Comment by bartlettroscoe** [comment]
> I used 'ps | grep' during the compilation using the connamds in the note above.

@prwolfe, what build keywords did you use?  What build name did you pass into `source cmake/std/atdm/load-env.sh <build-name>`?

Also note that when using ninja, you can just grep the generated `<build-dir>/build.ninja` to see the build flags.  And you can also see them directly by building with `make VERBOSE=1 <target-name>` (with "Ninja" and "Unix Makefiles" CMake generators).

**Comment by bartlettroscoe** [comment]
CC: @rppawlo, @prwolfe, @etphipp 

Long story short, the ATDM Trilinos builds on 'ride':

*  `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug`
* `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug` 

are also showing nearly 7 hour build times for the object file:

```
packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_IntegrationValues2.cpp.o
```

See the evidence below for this.  (We can see this due to the new build stats functionality running in the 'atdm-nightly' branch as part of PR #7508.)

Unfortunately, we did not have the these build stats going back in time so we can't tell when things changed in Trilinos that might have impacted this but I suspect this might have been due to Sacado changes pulled in from PR #7477 from looking at the commits pulled on testing day 2020-06-07 [here](https://testing-dev.sandia.gov/cdash/build/5516129/notes#note1) which triggered a 6h 48m rebuilt time for the build `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug`?  This build should be equivalent to the Trilinos CUDA PR build (which is not an accident because I created that configuration based on the ATDM Trilinos CUDA configuration).  But that is just a guess.

In the meantime, I will need to lengthen the LSF time for these builds on 'ride' until Panzer can get fixed to resolve this issue.

----

**DETAILS**


FYI: The `TrilinosBuildStats_Results` test for PR #7508 for the CUDA build on 'ride' shown [here](https://testing.sandia.gov/cdash/testDetails.php?test=117988277&build=7337158) showed the very long build time for the object file:

```
Full Project: max(elapsed_real_time_sec) = 25003.51 (packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_IntegrationValues2.cpp.o)
```

That 6.9 hours!

Comparing that to ATDM Triilnos builds running on 'ride' with the `TrilinosBuildStats_Results` test shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2020-06-25&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride&field2=testname&compare2=61&value2=TrilinosBuildStats_Results&field3=testoutput&compare3=97&value3=Full%20Project%3A%20max%5B(%5Delapsed_real_time_sec%5B)%5D) (hint: click the link "Show Matching Output" at the top right), one can see that this is consistent with the worst times which are for the builds `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug` showing:

```
Full Project: max(elapsed_real_time_sec) = 23365.96 (packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_IntegrationValues2.cpp.o)
```

and `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug` showing:

```
Full Project: max(elapsed_real_time_sec) = 26942.56 (packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_IntegrationValues2.cpp.o)
```

Interestingly, the full optimized build `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release` with no debug-mode checking built in shows:

```
Full Project: max(elapsed_real_time_sec) = 527.62 (packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_IntegrationValues2.cpp.o)
```

or just 9.5 minutes.

Looking at the history of the build `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug` in since 2020-06-01 in [this query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-06-01&end=2020-06-25&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug&field2=buildname&compare2=64&value2=-exp) you see the worst-case build time of `6h 48m 14s` on testing day 2020-06-07.  But that was before the build stats branch in PR #7508 was merged to the 'atdm-nightly-manual-updates' branch that first occurred in commit 9bdb736 which then first impacted testing day 2020-06-19.    But as shown in [this query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-06-19&end=2020-06-25&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug&field2=buildname&compare2=64&value2=-exp) the worst case re-build time was just 36m on 2020-06-20.  But there is a missing build for the testing day 2020-06-24.  The jenkins driver for that build at:

* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug/539/console

shows the build timed out after running for 6 hours during the build.

So what must have happened was that the object file:

```
packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_IntegrationValues2.cpp.o
```

must have gotten build yesterday (generating the corresponding `*.timing` file for it) before the full jenkins job timed out.  And then the build today finished off remaining build targets (which only took 10 minutes).

**Comment by etphipp** [comment]
I doubt PR #7477 is related, as I don't think there is anything in that PR that would actually affect Panzer.  If any Sacado change is causing this, it is probably PR #7410.  My guess is we went over a memory threshold and the machine is now swapping to disk when compiling that file.  Do you do these builds on the login node or a compute node?

**Comment by etphipp** [comment]
@bartlettroscoe I am confused.  In the early comments on this issue, you say you do not observe this for the ATDM builds, but now you are saying you are.  What changed?

**Comment by etphipp** [comment]
@bartlettroscoe I would like to try and reproduce this.  I want to see if the configuration change introduced in PR #7410 changes things.  Should I do the Cuda PR build or the ATDM build, or does it matter?

**Comment by bartlettroscoe** [comment]
> Do you do these builds on the login node or a compute node?

@etphipp, the builds take place on a compute node.  I don't think compute nodes on 'ride' have any swap space (because they have no local disk).  I think the compiler just errors out with signal 11 (out of memory) when you run out of RAM.  But I guess it would not be too hard see what is happening.

It would be possible to use git bisect on the first-parent commits to determine what changed to cause the build time for these Panzer files to skyrocket like this but that would take a long time to execute (because each build of these object files takes nearly 7 hours to complete).  This might be a fun test case for using git bisect though, right?

>  In the early comments on this issue, you say you do not observe this for the ATDM builds, but now you are saying you are. What changed?

@etphipp, good question.  That comment was based on superficial analysis from looking at CDash for a couple of days.  Even looking at [this query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-06-01&end=2020-06-25&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug&field2=buildname&compare2=64&value2=-exp) it is not obvious.   We only see one build since 2020-06-01 that comes anywhere close to 8.5 hours like we see for most of the PR iterations for my PR #7508 as shown in [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-7508-test-Trilinos_pullrequest_cuda_9.2&field2=buildstarttime&compare2=84&value2=NOW).  One of those builds took 9h 22m!!!!!

But in my more detailed digging and analysis shown [above](https://github.com/trilinos/Trilinos/issues/7532#issuecomment-649716726), I saw that we did see a rebuild one day that took 6.5 hours and digging into the missing build results for 2020-06-24 I think showed this large build time for this file.

**Comment by bartlettroscoe** [comment]
> Should I do the Cuda PR build or the ATDM build, or does it matter?

@etphipp, I don't think it matters.  As I mentioned above, I created the Trilinos PR CUDA configuration to match the ATDM CUDA configuration on 'ride' so they should be almost identical.  (And if they are not, then they need to be made so that they are protecting ATDM.)

**Comment by bartlettroscoe** [comment]
Looking at [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-06-01&end=2020-06-25&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Clean&field2=buildname&compare2=63&value2=cuda_9.2), we see a huge jump in the build CUDA build time from "Jun 09, 2020 - 10:49 MDT" to "Jun 09, 2020 - 00:17 MDT" that updated from commit b89a1ac to commit e17d462.

**Comment by etphipp** [comment]
I did my own Cuda PR build on ride and reproduced the long compile time (I didn't wait for it to finish, but stopped the build after those files had been compiling for about 80 minutes).  I then reconfigured with
```
-D Sacado_NEW_FAD_DESIGN_IS_DEFAULT:BOOL=OFF \
```
and recompiled Panzer_IntegratorValues2.o, which recompiled in about 24 minutes.  So it looks like PR #7410 is the likely culprit, which changed this to be ON by default.  

I'm not sure what to do about it.  I don't know that we will go back to the old design as it fixes several Intel issues for SPARC.  As a temporary workaround, you could add that configure option for this build, although I plan to remove the old design permanently at some point.

**Comment by bartlettroscoe** [comment]
CC: @rppawlo, @prwolfe 

>  As a temporary workaround, you could add that configure option for this build, although I plan to remove the old design permanently at some point.

@etphipp that seems like a good short-term solution for the CUDA PR build.  For the ATDM Trilinos builds, we can leave the log build times to better protect ATDM usage.  Long-term, these Panzer files should likely be broken up into smaller pieces to get around this problem.  Or, we may not just care about this platform going forward because we don't see any problems on more relevant platforms like ATS-2.

**Comment by bartlettroscoe** [comment]
FYI: I should not need to increase the build times for the ATDM Trilinos builds on 'ride' as they are already set to 12 hours as shown at:

* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug/539/console

which showed:

```
<...>
06:07:10 Using white/ride compiler stack CUDA-9.2_GNU-7.2.0 to build RELEASE-DEBUG code with Kokkos node type CUDA and KOKKOS_ARCH=Power8,Kepler37
06:07:11 + bsub -x -Is -q rhel7F -n 16 -J Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug -W 12:00 /home/jenkins/ride/workspace/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug/Trilinos/cmake/ctest/drivers/atdm/ctest-s-driver.sh
06:07:11 ***Forced exclusive execution
06:07:11 Job <5059> is submitted to queue <rhel7F>.
06:07:11 <<Waiting for dispatch ...>>
06:07:24 <<Starting on ride14>>
06:07:24 
06:07:24 Start: ctest-s-driver.sh
06:07:24 
06:07:24   ==> Wed Jun 24 04:07:24 MDT 2020
<...>
06:10:56 Building all targets ...
06:10:56 
06:10:56 Build project
06:10:56    Each symbol represents 1024 bytes of output.
06:10:56     ..................................................  Size: 49K
<...>
07:23:54     ..................................................  Size: 4300K
07:26:43     .............................................FATAL: command execution failed
13:04:42 java.io.IOException
13:04:42 	at hudson.remoting.Channel.close(Channel.java:1447)
13:04:42 	at hudson.remoting.Channel.close(Channel.java:1403)
13:04:42 	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:868)
13:04:42 	at hudson.slaves.SlaveComputer.kill(SlaveComputer.java:835)
13:04:42 	at hudson.model.AbstractCIBase.killComputer(AbstractCIBase.java:89)
13:04:42 	at jenkins.model.Jenkins.access$2100(Jenkins.java:316)
13:04:42 	at jenkins.model.Jenkins$19.run(Jenkins.java:3494)
13:04:42 	at hudson.model.Queue._withLock(Queue.java:1392)
13:04:42 	at hudson.model.Queue.withLock(Queue.java:1269)
13:04:42 	at jenkins.model.Jenkins._cleanUpDisconnectComputers(Jenkins.java:3488)
13:04:42 	at jenkins.model.Jenkins.cleanUp(Jenkins.java:3366)
13:04:42 	at hudson.lifecycle.UnixLifecycle.restart(UnixLifecycle.java:70)
13:04:42 	at jenkins.model.Jenkins$22.run(Jenkins.java:4313)
13:04:42 Caused: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@4887f727:ride": Remote call on ride failed. The channel is closing down or has closed down
```

So this was not a timeout but instead the Jenkins slave process crashed for some reason.

**Comment by prwolfe** [comment]
Talking with @jwillenbring on Wed we wanted to see if this related to the length of out Intel builds. I set up multiple builds and came up with this data


  | File |   | Panzer_PointValues2.cpp.o | Panzer_IntegrationValues2.cpp.o
-- | -- | -- | -- | --
Time |   |   |   |  
  |   |   |   |  
PR-ride-cuda-opt |   |   | 395m | 543m
atdm-ride-cuda |   | 247m | 340m
gcc 7.2 opt |   |   | 2m | 1m
gcc 8.3 opt |   |   | 1m | 1.2m
gcc 7.2 dbg |   |   | 0.45m | 0.55m
Intel 17 opt |   |   | 2.25m | 2.75m
atdm-ride-cuda-opt |   | 4.5m | 5.5m
atdm-ride-cuda-dbg |   | 247m | 340m

So it looks like this is isolated to Cuda and oddly not related to opt/debug. I am looking at the two closest builds I have (the atdm cuda-opt vs atdm cuda-dgb) to try and see the difference. I did find that whatever is going on is a generated file as

* both builds used the same source directory
* I was able to use the compile command from the opt build in the dbg build directory and demonstrate the issue.

**Comment by prwolfe** [comment]
@bartlettroscoe - I was incorrect about when this started happening to the PR builds. I did a query (https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-05-01&end=2020-06-25&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=63&value1=pull&field2=buildname&compare2=63&value2=cuda_9.2&field3=testspassed&compare3=43&value3=2800&field4=builderrors&compare4=41&value4=0) and came up with an initial long build at Jun 03, 2020 - 20:54 MDT - very consistent with the May 27th date you and @etphipp are looking at with #7410

**Comment by etphipp** [comment]
It would be interesting to understand exactly what is different between the PR-ride-cuda-opt and atdm-ride-cuda-opt builds.  Regardless, I think we should just add 
```
-D Sacado_NEW_FAD_DESIGN_IS_DEFAULT:BOOL=OFF \
```
for these builds for the time being.

**Comment by bartlettroscoe** [comment]
>It would be interesting to understand exactly what is different between the PR-ride-cuda-opt and atdm-ride-cuda-opt builds

@etphipp, when I first created the PR CUDA build, it was identical to the ATDM CUDA 'relese-debug' build.  But through time, they have diverged some.  It would not be hard to use: 

* https://gitlab-ex.sandia.gov/atdm/trilinos-config-diff

to diff them and determine the exact differences.

**Comment by prwolfe** [comment]
@bartlettroscoe - as we discussed I did check two changes using Panzer_IntegrationValues2.cpp.o as a proxy.


Default PR build |   |    543m
-- | -- | --
With ﻿Kokkos_ENABLE_DEBUG_BOUNDS_CHECK:BOOL=OFF |   | 5m20s
With ﻿Sacado_NEW_FAD_DESIGN_IS_DEFAULT:BOOL=OFF |   | 24m45s

I agree that turning off the Kokkos bounds check would be the more dangerous solution, and this confirms the time frame that @etphipp saw. I will talk with Jim Monday, but I concur that the second option is best until the panzer team gets this fixed.

Thanks guys!

**Comment by etphipp** [comment]
> @etphipp @rppawlo Do we understand why Sacado new fad design has such a big impact on build time for those two Panzer files on Cuda?

Not exactly.  Seems to be due to the combination of the new design, Kokkos bounds-checking, and something peculiar to these files.  Even with bounds-checking on using the old design, Panzer_IntegrationValues2.cpp takes ~24 min to compile, which is quite large by itself.  I believe based on comments from @rppawlo these files instantiate a lot of Intrepid2 code, so probably hitting some nonlinear complexity in the compiler that either splitting the files or ETI in Intrepid2 would help.

**Comment by mperego** [comment]
> > @etphipp @rppawlo Do we understand why Sacado new fad design has such a big impact on build time for those two Panzer files on Cuda?
> 
> Not exactly. Seems to be due to the combination of the new design, Kokkos bounds-checking, and something peculiar to these files. Even with bounds-checking on using the old design, Panzer_IntegrationValues2.cpp takes ~24 min to compile, which is quite large by itself. I believe based on comments from @rppawlo these files instantiate a lot of Intrepid2 code, so probably hitting some nonlinear complexity in the compiler that either splitting the files or ETI in Intrepid2 would help.

I see. Thanks.

**Comment by rppawlo** [comment]
@prwolfe - Some changes were pushed a week ago. Can you verify that the build times have been reduced and close?

**Comment by prwolfe** [comment]
@rppawlo - Looks good at this point - Thanks!

**Comment by mperego** [comment]
> 
> 
> @prwolfe - Some changes were pushed a week ago. Can you verify that the build times have been reduced and close?

Thanks Roger for this!
