### ISSUE TITLE
Get Trilinos to adopt the XSDK configure standards

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#76]
Trilinos needs to adopt the updated xSDK configure options (see [SDK-1](https://ideas-productivity.atlassian.net/browse/SDK-1) and [SDK-2](https://ideas-productivity.atlassian.net/browse/SDK-2)).  I have this done and integrated into TriBITS (see [TriBITS #107](https://github.com/TriBITSPub/TriBITS/issues/107)) but it needs some review.  @jwillenbring, given that you are also funded on the IDEAS project, do you think you can give  [TriBITS #107](https://github.com/TriBITSPub/TriBITS/issues/107) a review?  You can also manually test that it is behaving according to the [xSDK configure standard](https://docs.google.com/document/d/18028D6nsuhIrCvJnX6c07r8m_Np4SH-aGXMX4svMs1w).

Anyway, I am about to snapshot the updated TriBITS to the Trilinos 'master' branch.

**Comment by bartlettroscoe** [comment]
There appears to be some problem with the ORNL network and access to github.  I am getting:

```
[8vt@u235 Trilinos (master)]$ git pull
ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Hopefully this will be fixed by tomorrow morning so that I can push.

**Comment by bartlettroscoe** [comment]
I snapshotted TriBITS to the branch `tribits_github_snapshot` and merged to `master`.  I tested the XSDK defaults quickly with:

```
$ env CC=`which gcc` CXX=`which g++` FC=`which gfortran` 
  cmake -DUSE_XSDK_DEFAULTS=ON ../../../Trilinos

...

-- XSDK: Setting default BUILD_SHARED_LIBS=TRUE

...

-- USE_XSDK_DEFAULTS='ON'
-- XSDK: Setting CMAKE_C_COMPILER from env var CC='/projects/vera/gcc-4.8.3/toolset/gcc-4.8.3/bin/gcc'!
-- XSDK: Setting CMAKE_CXX_COMPILER from env var CXX='/projects/vera/gcc-4.8.3/toolset/gcc-4.8.3/bin/g++'!
-- XSDK: Setting CMAKE_Fortran_COMPILER from env var FC='/projects/vera/gcc-4.8.3/toolset/gcc-4.8.3/bin/gfortran'!
-- XSDK: Setting default CMAKE_BUILD_TYPE=DEBUG
-- CMAKE_BUILD_TYPE='DEBUG'
-- BUILD_SHARED_LIBS='TRUE'

...

```

I then tested without setting XSDK defaults:

```
$ rm -r CMake*
$ env CC=`which gcc` CXX=`which g++` FC=`which gfortran` \
  cmake ../../../Trilinos 

...

-- USE_XSDK_DEFAULTS='FALSE'
...
-- Check for working C compiler: /projects/vera/gcc-4.8.3/toolset/gcc-4.8.3/bin/gcc -- works
...
-- Check for working CXX compiler: /projects/vera/gcc-4.8.3/toolset/gcc-4.8.3/bin/g++ -- works
...
-- Check for working Fortran compiler: /projects/vera/gcc-4.8.3/toolset/gcc-4.8.3/bin/gfortran  -- works
...
```

and there was no other sign of XSDK.

Looks good to me.

I was finally allowed to do the push.

I pushed the commits:

```
17853e0 "Merge branch 'master' of github.com:trilinos/Trilinos"
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Sun Jan 10 22:26:58 2016 -0500 (57 seconds ago)

c9a9b31 "Merge branch 'tribits_github_snapshot' (Trilinos #76)"
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Sun Jan 10 21:21:03 2016 -0500 (67 minutes ago)

16592af "Automatic snapshot commit from tribits at 906db00"
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Sun Jan 10 20:38:06 2016 -0500 (2 hours ago)

M       cmake/tribits/ci_support/CheckinTest.py
M       cmake/tribits/ci_support/checkin-test.py
M       cmake/tribits/core/package_arch/TribitsAddTestHelpers.cmake
M       cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake
M       cmake/tribits/doc/build_ref/TribitsBuildReferenceBody.rst
M       cmake/tribits/doc/developers_guide/TribitsDevelopersGuide.rst
A       cmake/tribits/xsdk/XSDKDefaults.cmake
```

I would appreciate if someone could review the updated documentation [here](https://tribits.org/doc/TribitsBuildReference.html) (just search for 'xsdk').  See the changes in the commits mentioned in [TriBITS #76](https://github.com/TriBITSPub/TriBITS/issues/107).  Jim (@jwillenbring), is this something you could do?  If there are typos in the documentation, we can safely fix these on the release branch then use format-patch and am to get this back into TriBITS proper.

**Comment by jwillenbring** [comment]
I can review the documentation changes and report back.

**Comment by bartlettroscoe** [comment]
Thanks Jim (@jwillenbring).  Looks like the Trilinos documentation is already updated [here](https://trilinos.org/docs/files/TrilinosBuildReference.html).  Don't you love automated processes :-)

**Comment by jwillenbring** [comment]
The only real comment that I have is that

The compilers in MPI mode TPL_ENABLE_MPI=ON or serial mode TPL_ENABLE_MPI=OFF will be read from the environment variables CC, CXX and FC if they are set but the cmake cache variables CMAKE_C_COMPILER, CMAKE_C_COMPILER and CMAKE_C_COMPILER are not set. Otherwise, the TriBITS default behavior is to ignore these environment variables in MPI mode.

is mentioned in the summary, but not in section 5.4. All other changes to behavior were mentioned both in the applicable section, and in the summary. Was this intentional?

**Comment by jwillenbring** [comment]
Also, I just wanted to confirm that the automated updating of the equivalent document for Trilinos is working since:

https://trilinos.org/docs/files/TrilinosBuildReference.html

contains the xSDK changes.

**Comment by bartlettroscoe** [comment]
> The only real comment that I have is that
>
> The compilers in MPI mode TPL_ENABLE_MPI=ON or serial mode TPL_ENABLE_MPI=OFF will be read from the environment variables CC, CXX and FC if they are set but the cmake cache variables CMAKE_C_COMPILER, CMAKE_C_COMPILER and CMAKE_C_COMPILER are not set. Otherwise, the TriBITS default behavior is to ignore these environment variables in MPI mode.
>
>is mentioned in the summary, but not in section 5.4. All other changes to behavior were mentioned both in the applicable section, and in the summary. Was this intentional?

These env variables are mentioned in Section 5.4 in the sentence:

"If these the CMake cache variables are not set, then CMake will use the compilers specified in the environment variables CC, CXX, and FC for C, C++ and Fortran."

I think what is really missing is a more detailed discussion of this in section 5.9 "Configuring with MPI support".  A think a paragraph or two should be added to that section to explain how the MPI compilers are selected in more detail.  I will try do that later today.  But I likely will not bother updating the release branch for this, just the main development branch.

One thing we need to consider is if Trilinos will turn on the XSDK defaults automatically for Trilinos 13.0.0?  The biggest impact is that would give users a default slow but debuggable build with shared libraries (instead of a fast static build).  We should also consider turning on ETI by default as well (but that is another issue).

**Comment by jwillenbring** [comment]
I think what is really missing is a more detailed discussion of this in section 5.9 "Configuring with MPI support". A think a paragraph or two should be added to that section to explain how the MPI compilers are selected in more detail. I will try do that later today. But I likely will not bother updating the release branch for this, just the main development branch.

-This all sounds good to me. 

One thing we need to consider is if Trilinos will turn on the XSDK defaults automatically for Trilinos 13.0.0? The biggest impact is that would give users a default slow but debuggable build with shared libraries (instead of a fast static build). We should also consider turning on ETI by default as well (but that is another issue).

-That is a good question. I think we could look at each item individually if necessary. Changing defaults, even if communicated carefully, is not a decision to take lightly because any level of announcement will be missed by many. That is not to say we shouldn't do it.

**Comment by bartlettroscoe** [comment]
Jim (@jwillenbring), I added updated documentation for how the compiler wrappers are selected (see tribitspub/tribits#107 and commit tribitspub/tribits@f4891e2c7).  When this updates over night, can you take a look at the updated [Section 5.9](https://trilinos.org/docs/files/TrilinosBuildReference.html#configuring-with-mpi-support)?

**Comment by bartlettroscoe** [comment]
@jwillenbring, for some reason the Trilinos build of this document has not updated yet.  But you can look at the updated section in the generic build of this document [here](https://tribits.org/doc/TribitsBuildReference.html#configuring-with-mpi-support).

Let me know if you can review.  This is the last thing to do so that I can close this ticket.

**Comment by jwillenbring** [comment]
I think the new material looks fine. I find this behavior somewhat odd, but recognize that this is what was agreed on. One last note is that the Trilinos documentation updates in the morning, not overnight, so I expect the changes to be in place within the next hour or so (it is running now). I think you can close this ticket at this point.

**Comment by bartlettroscoe** [comment]
Thanks @jwillenbring.  Did you not find any typos?  I can't believe that I wrote this in one shot with no typos.

> I find this behavior somewhat odd, but recognize that this is what was agreed on.

What behavior specifically did you find odd?

I see problems/inconsistencies with the current behavior:

1. The find of the C++ and Fortran compilers is not restricted to the same directory as the C compiler, like is the case with raw CMake.  We should change that so that it is.

2. When XSDK mode is turned on (`USE_XSDK_DEFAULTS=TRUE`), then the CMake cache vars `MPI_[C,CXX,Fortran]_COMPILER` are ignored if the env vars `CC`, `CXX` and `FC` are set.

But in retrospect, since we always use the MPI compiler wrappers directly for the CMake cache vars `CMAKE_[C,CXX,Fortran]_COMPILER`, we should have likely never defined the cache vars `MPI_[C,CXX,Fortran]_COMPILER`.   But removing `MPI_[C,CXX,Fortran]_COMPILER` would break backward compatibility in a major way so I think we may be stuck with supporting these.

But changing the default search behavior so that it is consistent with raw CMake seems like that would be a reasonable thing to do.  Do you agree?

Anyway, we can close this particular Issue ticket and can create a new issue ticket for making the compiler search behavior more consistent.

**Comment by bartlettroscoe** [comment]
Closing as complete

**Comment by jwillenbring** [comment]
I was referring specifically to 2. I have wondered in the past why we had the MPI_*_COMPILER options when you could just enable MPI, and set the compilers directly. I agree that removing those options would be a major change. That said, we could bomb configure with a very helpful message in this case, and people shouldn't get hung up on it forever - basically if those options are set, stop and tell them what needs to happen. Not sure if I endorse that idea, but at least it wouldn't be a silent change of behavior. I think the new behavior makes sense in a way, and it is more consistent, but given the options exist, even if they maybe shouldn't, I find it odd to ignore them. That said, I think it would be very rare that this would actually bite someone.

I might have added some commas if it were me or very slightly reworded some spots, but I didn't see anything obvious other than that, and that is somewhat just style dependent for people, so I left it. There was one place where you didn't leave a space after a -D, but that is how I like to specify options anyway ever since it bit us to have the space in there for nightly testing.

**Comment by bartlettroscoe** [comment]
> I have wondered in the past why we had the MPI_*_COMPILER options when you could just enable MPI, and set the compilers directly. 

I think the reason we supported `MPI_<LANG>_COMPILER` was because we were replacing the messed up [standard FindMPI.cmake module](https://cmake.org/cmake/help/v2.8.4/cmake.html#module:FindMPI) (as you can see that version only recognized a C++), and that is how that module made you select the MPI compiler wrappers.  So here were Trilinos developers who were setting  `MPI_<LANG>_COMPILER` and having trouble and when we replaced the implementation, we kept supporting those variables.  Unfortunately, I can't find any Bugzilla ticket that even mentions FindMPI.cmake.  But that is my memory and I will put in a note about that in the documentation.
