### ISSUE TITLE
Add Trilinos::initialize (and Trilinos::finalize)

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#763]
Result of Kokkos / Tpetra meeting.  We will fill this in.

@crtrott @jjellio @rppawlo @maherou  

I didn't ask for this.  This came up at the Kokkos / Tpetra meeting today.

**Comment by jjellio** [comment]
This issue is related to (and motivated by) #718, but the solution to 718 requires more thought than simply pushing a change to Tpetra ctor or Teuchos::GlobalMPISession.

There are two immediate issues:

1) Who owns initialization of low level packages.
2) How are command line arguments (or parameters in general) passed to these low level packages.

(1) Initialization
Currently, Teuchos::GlobalMPISession() initializes MPI and caches a copy of argv that Teptra then uses to initialize Kokkos.

Another option is to let Tpetra do all initialization via Tpetra::initialize().

The broader problem is that this is pushing unrelated initialization calls into packages and the logic and semantics of calling foo::initialize() is not consistent. Specifically, users wish to *not* initialize some packages, because a third party library may already do this (e.g., multiple packages that all want to call MPI_Init() ). Related to (2), is how arguments owned by a subpackage are handled so that they do not impact high level user code.

(2) Argument handling
Currently, Kokkos promises to remove kokkos prefixed arguments during Initialize(). This allows user code to parse argv and never end up with unknown --kokkos-* options. (As long as the user calls Kokkos::Initialize() prior to parsing the arguments.)

A poor solution would be to tell users to simply ignore unknown command line options.  This is error prone and a poor design decision. Related to (1), Teuchos::GlobalMPISession does not promise this behavior, and that is not a bug or deficiency in Teuchos (#718). 

Semantics for initializing packages and dealing with package parameters is needed as well as an API.

**Comment by mhoemmen** [comment]
I think we can separate #718 from this issue.  In #718, the problem is that Kokkos does not get initialized until first use in Tpetra, if it has not already been initialized.  This means that the relative order when Kokkos / Tpetra strips out these command-line arguments, vs. when the application does so, is not obvious to users.  That's a different issue than this one.  Here, the issue is, "Who initializes MPI, CUDA, OpenMP, etc.?"

**Comment by mhoemmen** [comment]
I know that @maherou wants us to get out of the business of global initialization.  However, I don't think applications would accept Kokkos getting out of that business.  Kokkos has to do a lot of complicated things to make threads work right.  It's impossible to ask users to do all that.  Thus justifies Kokkos::initialize, and perhaps even Tpetra::initialize.

**Comment by jjellio** [comment]
@mhoemmen Yes, they are two separate issues. But the solution to #718 depends heavily on this issue. (I.e., doing 718 independent of this one would be probably be a poor use of time). For 718, part of the issue is caching argv and having initializers operate on the cache. The real issue is that GlobalMPISession and Teptra::initialize are becoming dumping grounds for work that is not in the scope of their design criteria. E.g., Tpetra depends on Kokkos, but that doesn't mean Tpetra should be initializing it. Nor should Teuchos::GlobalMPISession take ownership of initializing Tpetra. In the future, should another package accept special args and need an initialize will Tpetra own its init too?

**Comment by maherou** [comment]
The use of a global init/finalize is antithetical to embedded library software.  

Consider a multiphysics/multiscale coupling situation with two code that were considered the universe.  Whose global init do you use?  

Consider embedding a solver into an existing large code.  How do you do so without breaking encapsulation?  If you want to embed two solvers in a large code and they want different init behaviors, how do you handle that?

Kokkos can get away with this abuse because it is primarily a programming environment for loops over multidimensional dense arrays, and apps tend to use it directly for their own code.  But even there, if we wanted to insulate the code from the fact that Kokkos was being used, the same issues mentioned above would also arise.

If we were to go toward a global init model, I would like to see that we can handle encapsulation effectively, even though it will surely be inelegant.

**Comment by rppawlo** [comment]
My comments at the meeting earlier are summed up by @maherou. When we couple multiple applications, some libraries/TPLs may try to own initialization. We hit this more often than you would think. An example would be an executable that couples two applications where a subset of mpi processes runs one application that requires a kokkos enabled solver, but another subset of mpi processes runs a second application that uses non-kokkos thread initialization. While we might use a teuchos the global mpi session across all processes, we might want to initialize kokkos only on a subset of processes.  We have seen similar collisions at the MPI process level.

While it might be nice to offer such a capability for convenience for simple use cases, I would ask that Trilinos::initialize()/finalize be a completely optional thing. Do not require all Trilinos users to have to call a global initialize.

**Comment by mhoemmen** [comment]
I didn't suggest this thing.  Teuchos::GlobalMPISession exists because it's what the unit tests use, and it captures command-line arguments because I needed a way to pass them into Kokkos initialization.  @jjellio 's complaint about command-line argument parsing relates to GlobalMPISession.

**Comment by mhoemmen** [comment]
> If we were to go toward a global init model, I would like to see that we can handle encapsulation effectively, even though it will surely be inelegant.

Here is how I handle this in Tpetra::initialize:
```
For X in [MPI, Kokkos]: // ordered list
  If X is not already initialized:
    Initialize X
    Remember that I initialized X
  Endif
Endfor
```
and in Tpetra::finalize:
```
For X in [Kokkos, MPI]: // ordered list
  If I initialized X in Tpetra::initialize:
    Finalize X
  Endif
Endfor
```
Any rational library should behave like this.  If a library (not an application) just blindly calls MPI_Init without first checking MPI_Initialized, then that library is not correctly encapsulated; it's not a real library.  If every library obeys these rules, then the main issue remaining is expressed by #718.
