### ISSUE TITLE
Nightly and PR testing with float/complex_float

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#7651]
@bartlettroscoe Is there any chance you could add ``-DTrilinos_ENABLE_FLOAT`` and ``-DTrilinos_ENABLE_COMPLEX_FLOAT`` to a build on Jenkins? This could just be a typical Serial node build, it doesn't need to be a CUDA build or use any particular compiler. We just want to catch issues sooner, like the one fixed by #7649. Ideally one of the PR testing builds also uses those flags (again, doesn't need to be on the RIDE build which I know is overloaded). This was requested specifically by @jennloe but I also think it's going to be an important case to cover.

**Comment by bartlettroscoe** [comment]
@brian-kelley, for the nightly ATDM Trilinos, we would never enable `-DTrilinos_ENABLE_FLOAT=ON` and `-DTrilinos_ENABLE_COMPLEX_FLOAT=ON` in any builds because (by definition) none of the ATDM customers need that or want that.  (In the past, we tried setting up some "extra" builds but the Trilinos developers just ignored them because they were not impacting ATDM.)

So someone else needs to set up builds for that and make sure they stay passing.  But if you do nightly builds, they will get ignored.  So you have to add this to one of the Trilinos PR builds.  So this is really a question for the @trilinos/framework team and the Trilinos product area leads (@maherou, @jwillenbring, @srajama1, @kddevin, @rppawlo, @mperego).  It is outside the scope of ATDM so I don't have a place to comment further on this.

**Comment by jennloe** [comment]
@srajama1  This needs to work for when we add future multiprecision capabilities....

**Comment by cgcgcg** [comment]
I think it's a good idea to enable float and complex in the serial PR build.

**Comment by brian-kelley** [comment]
@cgcgcg I think that's reasonable. @bartlettroscoe To be honest, you're absolutely right, if there had been a build on CDash failing since last week I wouldn't have seen it. It does need to be in a PR build.
