### ISSUE TITLE
Belos:  Scaling with small initial residual norm

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#7669]
## Question
@trilinos/belos 

Situation:
We're using a Krylov solver to solve a time-dependent problem. The tolerance gets scaled by the initial residual norm in each time step. Since the time-dependent problem has some ramp-up phase, for some time steps the initial residual is really small, but non-zero. Effectively, this means that the tolerance after scaling can be way below machine tolerance, and bad things happen.

I'm wondering if there should be a check to see if tolerance*scaling is below machine epsilon, and option to adjust the tolerance in that case.

**Comment by vbrunini** [comment]
We're also interested in this for Sierra.

**Comment by csiefer2** [comment]
Can do this with the existng composite convergence criterion for Belos?

**Comment by cgcgcg** [comment]
I'd think so. So instead of 
`maxIterTest or convTest(tolerance)`, 
we'd use 
`maxIterTest or convTest(tolerance) or conTest(machineEps)`?

**Comment by cgcgcg** [comment]
I'm just worried about users that like to set convergence criteria of 1e-100, in the hope that this somehow gives them a better solution. This would definitely change their runs.

**Comment by hkthorn** [comment]
I would not do this by default.  This would have to be an option for applications to enable.

**Comment by dridzal** [comment]
@cgcgcg , what's wrong with having an absolute convergence tolerance of 1e-100 if the effective relative tolerance is 1e-10?  Are you referring to relative tolerances of 1e-100 (which, I agree, are not wise, unless we are working with arbitrary-precision arithmetic)?  In any case, the linear solvers should be scale invariant.  Otherwise, our nonlinear solver and optimization stack is in big trouble.  On a separate note, we have also observed inconsistent iteration numbers during the ramp-up phase for a transient code that's a derivative of miniEM, but we can trace this behavior back to using a mixture of relative and absolute convergence criteria in subsolvers.

**Comment by cgcgcg** [comment]
@dridzal Yes, relative tolerance of 1e-100.

**Comment by dridzal** [comment]
Agreed, there should probably be some default safeguard, tied to the epsilon given by working precision (to support multiprecision applications).
