### ISSUE TITLE
num rows for nuncontiguous CrsMatrix does not behave as doxygen says

### ISSUE THREAD

**Issue by davidHysom** [trilinos/Trilinos#770]
from Tpetra CrsMatrix:getGlobalNumRows(): " If you want the number of rows in the matrix, ask the range map for its global number of elements, using the following code: global_size_t globalNumRows = getRangeMap()->getGlobalNumElements()"
The attached example is for a small 2D mapped matrix, and demonstrates the problem.
Attached files: 
  out.log - output from the executable 
  Makefile 
  build.script - script I used to compile Trilinos 
  cmake.log - output from running the script
  test_1.cpp - driver

Partial output form test_1:
We build a dense matrix with 8 rows and columns
rows 0,1,2,3 go to P_0 and P_1
rows 4,5,6,7 go to P_2 and P_3
columns 0,1,2,3 go to P_0 and P_2
columns 4,5,6,7 go to P_1 and P_3
=====
P_0
A->getRowMap()->getGlobalNumElements(): 16
 (should be 16, since each row is 'owned' by two processors)

A->getGlobalNumEntries(): 64
 (should be 64)

A->getRangeMap()->getGlobalNumElements(): 16
 (this is what the Tpetra docs say to use; should be 8)

[dh_files.tar.gz](https://github.com/trilinos/Trilinos/files/567742/dh_files.tar.gz)

**Comment by mhoemmen** [comment]
The matrix's domain and range Maps must be one to one.  If you call fillComplete with no arguments, it uses the row Map by default as the domain and the range Map.  This is incorrect for your case, since your row Map is overlapping.  You need one-to-one domain and range Maps.  If you don't know what they should be, you may call Tpetra::createOneToOne (see Trilinos/packages/tpetra/core/src/Tpetra_Map_decl.hpp) to make a one-to-one version of a given Map.
