### ISSUE TITLE
ATDM scripts: how to clean up environment afterwards?

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#7701]
## Question
@bartlettroscoe 

When I do ATDM builds, my usual procedure is to do some variation of the following:

1. source ${TRILINOS_DIR}//cmake/std/atdm/load-env.sh cee-rhel7-gnu-opt-serial
2. `cmake -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake ...`
3. make

If I do `module purge`, there are still a lot of ATDM environment variables defined, which seems problematic if I were later to do other ATDM builds.  Is there a step or command to clear those?  Or would a later ATDM script clear or override those variables?

**Comment by jhux2** [comment]
Example when on cee-build013 (RHEL7):

```
(.../tpetra/intel-opt-2) module list
No Modulefiles Currently Loaded.
(.../tpetra/intel-opt-2) printenv | grep ATDM | head
(.../tpetra/intel-opt-2) source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh cee-rhel7-intel-opt-serial
Hostname 'cee-build013' matches known ATDM host 'cee-build013' and system 'sems-rhel7'
Setting compiler and build options for build-name 'cee-rhel7-intel-opt-serial'
Using SEMS RHEL7 compiler stack INTEL-18.0.5 to build RELEASE code with Kokkos node type SERIAL
	WARNING: sems-gcc dependency already found but does not match listed dependency sems-gcc/6.1.0
	I will use the sems-gcc you have loaded but correct behavior is not guaranteed
	WARNING: sems-gcc dependency already found but does not match listed dependency sems-gcc/4.9.3
	I will use the sems-gcc you have loaded but correct behavior is not guaranteed
(.../tpetra/intel-opt-2) module list
Currently Loaded Modulefiles:
  1) sems-env                     5) sems-gcc/7.2.0               9) sems-openmpi/1.10.1         13) sems-boost/1.59.0/base
  2) sems-git/2.10.1              6) sems-intel/18.0.5           10) sems-hdf5/1.10.6/parallel   14) sems-superlu/4.3/base
  3) sems-cmake/3.12.2            7) atdm-env                    11) sems-netcdf/4.7.3/parallel
  4) sems-ninja_fortran/1.8.2     8) atdm-mkl/18.0.5             12) sems-zlib/1.2.8/base
(.../tpetra/intel-opt-2) printenv | grep ATDM | head
ATDM_CONFIG_MAX_NUM_CORES_TO_USE=20
ATDM_CONFIG_CUSTOM_COMPILER_SET=0
ATDM_CONFIG_KNOWN_HOSTNAME=sems-rhel7
ATDM_CONFIG_JOB_NAME=cee-rhel7-intel-opt-serial
ATDM_CONFIG_KNOWN_SYSTEM_NAME=sems-rhel7
ATDM_CONFIG_USE_CUDA=OFF
ATDM_CONFIG_LAPACK_LIBS=-mkl
ATDM_CONFIG_REAL_HOSTNAME=cee-build013
ATDM_CONFIG_COMPILER=INTEL-18.0.5
ATDM_CONFIG_SYSTEM_DIR=/home/jhu/trilinos/Trilinos/cmake/std/atdm/sems-rhel7
(.../tpetra/intel-opt-2) module purge
(.../tpetra/intel-opt-2) printenv | grep ATDM | head
ATDM_CONFIG_MAX_NUM_CORES_TO_USE=20
ATDM_CONFIG_CUSTOM_COMPILER_SET=0
ATDM_CONFIG_KNOWN_HOSTNAME=sems-rhel7
ATDM_CONFIG_JOB_NAME=cee-rhel7-intel-opt-serial
ATDM_CONFIG_KNOWN_SYSTEM_NAME=sems-rhel7
ATDM_CONFIG_USE_CUDA=OFF
ATDM_CONFIG_LAPACK_LIBS=-mkl
ATDM_CONFIG_REAL_HOSTNAME=cee-build013
ATDM_CONFIG_COMPILER=INTEL-18.0.5
ATDM_CONFIG_SYSTEM_DIR=/home/jhu/trilinos/Trilinos/cmake/std/atdm/sems-rhel7
```

**Comment by bartlettroscoe** [comment]
@jhux2 

> Is there a step or command to clear those? 

You can just run:

```
$ source ${TRILINOS_DIR}/cmake/std/atdm/utils/unset_atdm_config_vars_all.sh
```

to wipe out all of the `ATDM_CONFIG_XXX` and related vars.

See:

* https://github.com/trilinos/Trilinos/blob/master/cmake/std/atdm/utils/unset_atdm_config_vars_all.sh

I wrote this just for that purpose.

> Or would a later ATDM script clear or override those variables?

@jhux2, they get carefully cleared out and reset by sourcing the the scripts `${TRILINOS_DIR}/cmake/std/atdm/utils/unset_atdm_config_XXX.sh`.

So you can just stay in the same shell and load new envs.

If you really care about this stuff, I would create a new shell and then load the ATDM env, configure, build and test.  The problem is that doing `module purge` can break some systems so you can't rely on that.  Also, note that we don't claim that you will get back the same env you started with because a `module purge` will wipe out any modules you might have loaded before you first sourced `atdm/load-env.sh <build-name>`.

Should we add a section to the file:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

on loading multiple envs and clearing out the env?  The advice that I would add there is that if you really care about your env, then start with a clean shell and then exit that shell when you are done.

**Comment by jhux2** [comment]
@bartlettroscoe Yes, I think having it in the documentation like you suggest would be helpful.

You're correct that a module purge wouldn't restore the environment.  My experience, however, is that `module unload FOO` will unset (restore) any environmental variables that were set (modified) by `module load FOO`.

Anyway, thank you for the explanation.
