### ISSUE TITLE
Tpetra: Make CrsGraph do thread-parallel pack & unpack

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#799]
@trilinos/tpetra 
Story: #797

**Comment by mhoemmen** [comment]
Not needed for FY17 Q4 goals, so moving to backlog.

**Comment by tjfulle** [comment]
No, I don’t believe It does yet.  `[im,ex]portAndFillComplete` is thread parallel and `pack` could be made thread parallel quite easily.  `unpack` would require a different approach than is currently used since the local `CrsGraph` does not support inserting indices (that is my recollection of why I didn’t complete the `pack/unpack` when I was working on the `transferAndFillComplete`).

**Comment by mhoemmen** [comment]
@tjfulle Oops!  Sorry about that!  I was looking at `pack` and didn't realize it was doing a host-thread-parallel loop.
