### ISSUE TITLE
Tpetra: Make CrsMatrix::transferAndFillComplete do thread-parallel pack & unpack

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#802]
@trilinos/tpetra 
"Superstory": #797 

Tpetra::CrsMatrix::transferAndFillComplete implements a specialized pack and unpack for CrsMatrix.  Tpetra's sparse matrix-matrix multiply uses this. 

Try to share as much code with #800 as possible.  See e.g., packRow in Trilinos/packages/tpetra/core/src/Tpetra_Import_Util2.hpp.  It would make sense to adapt PackTraits methods for use inside Kokkos::parallel_*.  That would call for changes to Stokhos and perhaps also Sacado.

**Comment by mhoemmen** [comment]
Task breakdown, discussed today (13 Jul 2017) with @tjfulle , tagging @csiefer2 : 

  1. Does MueLu only need #802 (transferAndFillComplete) for sparse matrix-matrix multiply? or will they also need ordinary Import / Export?
  2. Does MueLu need the target graph / matrix to be DynamicProfile, StaticProfile, or fixed structure?  That is, does the target graph / matrix need to be able to change its structure, based on incoming data from the source graph / matrix?
  3. Thread-parallelize pack and unpack with PIDs, not counting graph structure changes
  4. If structure changes needed (see (2) above), get rid of state in CrsGraph blocking thread safety of `insert{Local,Global}*`.  This means `nodeNumEntries_` and `nodeNumAllocated_`.  Instead, compute them on demand.
  5. If needed (see (2) above), make StaticProfile structure changes thread safe and scalable.
  6. If needed (see (2) above), make DynamicProfile structure changes thread safe and scalable.

**Comment by csiefer2** [comment]
1. TAFC only.
2. I presume you mean the target of the Import?  TAFC assumes that the output matrix will be generated from scratch and fillCompleted on output (aka fixed structure).
3. This task will collide w/ the reverse comm work by  @DrBooom  at some point.  Coordination will be needed.

Does that answer your questions?

**Comment by mhoemmen** [comment]
Thanks @csiefer2 for the quick reply! :-D

> I presume you mean the target of the Import?

Yes, the target graph / matrix of the Import / Export.

> TAFC assumes that the output matrix will be generated from scratch and fillCompleted on output (aka fixed structure).

Thanks for reminding us of that distinction -- it means that the target Crs{Graph,Matrix} doesn't even need to exist until TAFC returns it, so there is no such thing as "DynamicProfile" or "StaticProfile" for it.  This implies that we can use whatever data structure we want for the target, since users only see the fill complete version of it.

> This task will collide w/ the reverse comm work by @DrBooom at some point. Coordination will be needed.

Do you expect interface or pack format changes?

**Comment by tjfulle** [comment]
The packing portion of TAFC now uses `Tpetra::Details::packCrsMatrix` and friends, which are thread parallel.  It remains to thread parallelize `unpackAndCombineCrsArrays`, repurposing as much of `Tpetra::Details::unpackCrsMatrixAndCombine` as possible.

**Comment by tjfulle** [comment]
Adding, #1569 addresses the packing portion

**Comment by mhoemmen** [comment]
Fixed in develop.  See PR #1569.

**Comment by tjfulle** [comment]
@mhoemmen , it's not totally fixed.  The packing portion is, but `unpackAndCombineIntoCrsArrays` needs to be thread parellelelelized.  This part, however, is a much smaller effort because of the work on #798 and #800 (as part of #1569) to make a common pack/unpack interface.  I plan on finishing it this week.

**Comment by mhoemmen** [comment]
@tjfulle thanks for the clarification!  If you like, you may either open up a new issue for the work left to do, or reopen this issue.

**Comment by tjfulle** [comment]
I've "completed" thread parallelizing `unpackAndCombineIntoCrsArrays`.  Tests pass on my blade with/without OpenMP node and `OMP_NUM_THREADS>1`.  I am building and CUDA now (`ride` had a system upgrade that wiped my home directory, so I've got to start from scratch).  When the build is done and tested I'll open a new PR.

I say "completed" because there are two parts of the algorithm that are not easily thread parallelizable and are still serial.  These parts deal with local matrix rows that have contributions from multiple other processors.  Thread parallelizing the current algorithm/data structures results in local row quantities being touched and updated by concurrent threads, leading to clashes and failures.  I've got to think about whether a `parallel_scan` might be possible instead of a `parallel_for`.  The other alternatives are to leave as is (the offending parts not thread parallel) or redo some of the data structures to avoid collisions.

**Comment by mhoemmen** [comment]
@tjfulle Awesome!!! :-D  btw watch out for potential merge conflicts with my #1088 fix, coming in soon (possibly today).

btw `ride` saved home directories in `/home_old`, if I remember right, so you might not have to start over completely from scratch :-) .

@tjfulle wrote:
> These parts deal with local matrix rows that have contributions from multiple other processors.

Could you please clarify?  As long as the target matrix's structure does not change, then it sounds like you could just use atomic updates to resolve these thread conflicts.

**Comment by tjfulle** [comment]
@mhoemmen wrote:

> Could you please clarify? As long as the target matrix's structure does not change, then it sounds like you could just use atomic updates to resolve these thread conflicts.

Perhaps I can clarify, but it would probably be easier to show you.  Let me try.  The difficulty is that data for a row is packed sequentially as

```
[data for row N from proc P0][data for row N from proc P1]...[data for row N from proc PN]
```

After unpacking `[data for row N from proc P0]` an offset counter is incremented so that on the next pass `[data for row N from proc P1]` is unpacked.  The current offsets for row `N` are stored in an array and can probably be updated atomically, but I can't say for certain yet.

Did that make any sense?

**Comment by tjfulle** [comment]
@mhoemmen wrote:

> btw ride saved home directories in /home_old, if I remember right, so you might not have to start over completely from scratch :-) .

Now you tell me!  I'm running in to other `CUDA` issues now anyway...

**Comment by mhoemmen** [comment]
> Perhaps I can clarify, but it would probably be easier to show you.

Could you send me a meeting invite, say for tomorrow afternooon?  That might be easier.  Thanks!

**Comment by tjfulle** [comment]
@mhoemmen, what, that didn't make sense?

Meeting invite sent

**Comment by tjfulle** [comment]
Just got my `CUDA` issues resolved.  All Tpetra tests pass on `CUDA`.  The score card is all standard CI tests pass on my blade with/without OpenMP and Tpetra tests pass on `CUDA`.  Two more small sections remain to be thread parallelized (referenced earlier).  After discussing them with @mhoemmen, I'll get them fixed, tested, and PR opened.

**Comment by tjfulle** [comment]
@mhoemmen, can this issue be closed?  Or, is there more to be done?

**Comment by mhoemmen** [comment]
@tjfulle It's done -- thanks! :-D Great work btw!
