### ISSUE TITLE
ATDM DevOps:  `MAKE_INSTALL` Logic

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#8022]
## Question
@bartlettroscoe, @e10harvey, EMPIRE used to configure Trilinos with only
```bash
-D Trilinos_MAKE_INSTALL_GROUP=wg-atdm-empire
```

but then we noticed that group and other were getting more permissions than intended.  We switched it to
```bash
-D Trilinos_MAKE_INSTALL_GROUP=wg-atdm-empire
-D Trilinos_MAKE_INSTALL_GROUP_WRITEABLE:BOOL=OFF # note the typo
-D Trilinos_MAKE_INSTALL_WORLD_READABLE:BOOL=OFF
```

to effectively achieve a `chmod -R g-w,o-rx`.  That removed the permissions for other, but left the group write permissions due to the typo.  When we switched it to
```bash
-D Trilinos_MAKE_INSTALL_GROUP=wg-atdm-empire
-D Trilinos_MAKE_INSTALL_GROUP_WRITABLE:BOOL=OFF # typo fixed
-D Trilinos_MAKE_INSTALL_WORLD_READABLE:BOOL=OFF
```

that not only removed group write permissions, but also removed group read and execute as well.  Is that intentional behavior?  I can't find the logic in Trilinos that seems to say "by default, give group all permissions, but if write is turned off, remove all group permissions, unless read is explicitly turned on, in which case allow group read and execute."

Note that the fix on our end was just to use
```bash
-D Trilinos_MAKE_INSTALL_GROUP=wg-atdm-empire
-D Trilinos_MAKE_INSTALL_GROUP_READABLE:BOOL=ON # turn on read explicitly
-D Trilinos_MAKE_INSTALL_GROUP_WRITABLE:BOOL=OFF
-D Trilinos_MAKE_INSTALL_WORLD_READABLE:BOOL=OFF
```

so we're not in any need of an urgent change or anything.  I'm just confused by the logic that's baked in.

**Comment by bartlettroscoe** [comment]
@jmgate, looking at the documentation I wrote for this TriBITS feature at:

```
https://docs.trilinos.org/files/TrilinosBuildReference.html#setting-install-ownership-and-permissions
```

that these options are only changing the default permissions if asked to do so.  But I think the issue we are having here is how the group readable/writable options relate to each other if one or the other are explicitly set.  We can also consider changing how the defaults are set to be more intuitive.  You ca see how the defaults are sets starting at:

* https://github.com/TriBITSPub/TriBITS/blob/master/tribits/core/package_arch/TribitsGlobalMacros.cmake#L315

We can also consider changing how these options are applied in the code:

* https://github.com/TriBITSPub/TriBITS/blob/master/tribits/core/package_arch/TribitsAddInstallGroupAndPermsFixups.cmake

But I think that code is doing what is should if you remember that these options are only changing the default install permissions and not setting absolute permissions.

If you want to be explicit about what permissions you want independent of the default install permissions provided by CMake and by the user running the install, you need to set all of these vars to the desired values as you have shown with:

```
-D Trilinos_MAKE_INSTALL_GROUP=wg-atdm-empire
-D Trilinos_MAKE_INSTALL_GROUP_READABLE:BOOL=ON # turn on read explicitly
-D Trilinos_MAKE_INSTALL_GROUP_WRITABLE:BOOL=OFF
-D Trilinos_MAKE_INSTALL_WORLD_READABLE:BOOL=OFF
```

Otherwise, does that section need some more example for other use cases like the one described above for EMPIRE (where the group can only read/exectute the content of the install but only the owning user has write permissions).  Or, should we consider selecting better defaults or changing behavior?

**Comment by bartlettroscoe** [comment]
@jmgate, are you satisfied with the response [above](https://github.com/trilinos/Trilinos/issues/8022#issuecomment-692202302) or does more need to be done here?

**Comment by bartlettroscoe** [comment]
> @jmgate, are you satisfied with the response [above](https://github.com/trilinos/Trilinos/issues/8022#issuecomment-692202302) or does more need to be done here?

@jmgate, anything more to do here?  If not, can you close this?

**Comment by bartlettroscoe** [comment]
Enough time for a review and since this has been working well for a long time, closing as complete.
