### ISSUE TITLE
Test scripts for apollo, ride, shiller, and artemis incorrectly enable pthreads

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#805]
@bmpersc It appears that the nightly test scripts for ride, artemis, and schiller are always enabling Pthreads because of this line:
```
"-DKokkos_ENABLE_Pthreadi:BOOL=$ENV{JENKINS_DO_PTHREAD}"
```

I've fixed this with commit b260ac05.

**Comment by bmpersc** [comment]
@jhux2 @crtrott Thanks for catching this. All of those tests were based on the same set of scripts so it isn't shocking that this was common to all of them. I'm not sure when that got in and no one has complained about it until now. However, since it is fixed it doesn't matter too much. I will check some of our other tests that were based on the same scripts to see if they also suffer from this.

**Comment by jhux2** [comment]
@bmpersc  @crtrott What led me to this are some failing tests on apollo.  Presumably the intent of [the dashboard](http://testing.sandia.gov/cdash/buildSummary.php?buildid=2613959) ```Linux-gcc-4.8.4-MPI_RELEASE_DEV_DownStream_ETI_SERIAL-ON_OPENMP-OFF_PTHREAD-OFF_CUDA-ON_COMPLEX-OFF``` is to disable Pthreads.  However, Pthreads clearly being enabled during [configure](http://testing.sandia.gov/cdash/viewConfigure.php?buildid=2613959).   I believe the cmake configure line have the additional option ```-DTPL_ENABLE_Pthread=OFF```.

**Comment by jhux2** [comment]
As the configure stands now, some part of Kokkos is being activated because of Pthreads:
```
Enabling all optional package TPL support for currently enabled TPLs ...
-- Setting KokkosCore_ENABLE_Pthread=ON since TPL_ENABLE_Pthread=ON
```

**Comment by bmpersc** [comment]
That is an interesting point. In theory disabling pthreads for only Kokkos could cause issues with other packages that are checking their own enable or the Trilinos level enable. However, Disabling it for everyone could cause other issues. If packages depend on pthreads only for use with Kokkos they should probably configure based on the Kokkos' setting. I believe there is very little that actually depends on pthreads so the likely hood of actually causing issues by disabling pthreads completely would be low. However, it does potentially change what is being tested elsewhere.

Since these are @crtrott's tests I'll let him decide on whether disabling pthreads for all packages is appropriate.

**Comment by mhoemmen** [comment]
Tpetra and downstream don't use Pthreads by default, even if it is enabled in Kokkos.  Enabling it in Tpetra requires setting another option which is OFF by default.

**Comment by jwillenbring** [comment]
@bmpersc @mhoemmen Can this be closed?

**Comment by mhoemmen** [comment]
@jwillenbring I think so.  Thanks!
