### ISSUE TITLE
PyTrilinos: Contributing by writing wrappers for missing functions

### ISSUE THREAD

**Issue by hakeemo** [trilinos/Trilinos#806]
As I gradually build my application using pyTrilinos, I find myself wanting to use functions in Trilinos which have no python interface. I would like to have some guidance in how to implement a python wrapper for a specific function. As a concrete example I would like to wrap ML_Epetra::EpetraMatrix2MLMatrix. How can this be done? I would gladly start pull requests with my updated code.
@wfspotz

**Comment by mhoemmen** [comment]
@hakeemo, thanks for your enthusiasm!  I'm not a PyTrilinos developer, but I've looked at some of its wrappers now and then.  Its ML wrappers appear to live in Trilinos/packages/PyTrilinos/src/ML.i.  PyTrilinos uses SWIG (with hand-written interface (.i) files) to wrap Trilinos functionality.  @wfspotz is the package lead and can answer more questions.  Best practice for pull requests is to make them against Trilinos' develop branch, because that's where they will go if they get approved.  Thanks!

**Comment by wfspotz** [comment]
There is a developers guide in PyTrilinos/doc/DevelopersGuide. It is not too long. If you want to build the html version, you will need docutils installed. If you want the PDF version, you will need docutils and pdflatex installed. Or you can just read the .txt files.

Most of the developers guide should be fine, but it has been a while since I have updated it, so it might have some inaccuracies. Adding to an existing wrapped module should be fairly easy. Read through the guide, and let me know if you have questions.
