### ISSUE TITLE
const of subview model in intrepid2

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#813]
@eric-c-cyr @kyungjoo-kim @rppawlo 
I tested some of the kokkos refactor branch in intrepid2.  I was looking at the serial getValues inside of a kokkos parallel_for.  Here is a simple code

`
struct foo{
  DynRankView<double> in, out;
  foo(DynRankView<double> in_,DynRankView<double>  out_):in(in_),out(out_){}
  KOKKOS_INLINE_FUNCTION
  void operator ()(int i)const {
    typedef Basis_HGRAD_TRI_C1_FEM Basis;
    Basis::Serial<Intrepid2::OPERATOR_VALUE>::getValues(subview(out,i,ALL()), subview(in,i,ALL()));
  }
};

`

and a hard coded version
` 
void operator ()(int i)const {
   out(i,0) = 1. - in(i,0) - in(1,1);
    out(i,1) = in(i,0);
    out(i,2) = in(i,1);
  }
`

Now when I call this with 10M length view on a single core it takes 0.09s, if I skip the subview step and hard code the response it takes 0.03s

From that I'm assuming that the subview creation is roughly 0.06s of the run time.  

This is lower than i assumed it would be, but still 70% of the cost.   Not suggesting we fix this today, but we may want to in the future.

**Comment by bathmatt** [comment]
Also, I don't get github and the code insert, why isn't the line breaks preserved sometimes??  Does anyone know?

**Comment by kyungjoo-kim** [comment]
Hi Matt, 

Thank you for testing the refactored Intrepid2. Since we finished the conversion of dynrankview, we consider some performance test and evaluation in the application sense is very important. 

The subview overhead depends on the workload (this varies) per subviewed unit and subview construction overhead (this is constant). From your example, you tested for C1 triangle element. The workload is quite small. If you tested with C2 element, the overhead ratio probably drops down to 20%.  

Since the serial interface is designed for a single point evaluation, the subview mechanism here adds  overhead relatively higher than other use cases. If you want to increase the workload per subview, we can also evaluate multiple points at a time (this may not be your use case though). Using subviews is convenient and increase code reusability. Now, the serial interface provides you a way to use the Intrepid2 code in your functor, which is not allowed in the previous version. If you compare the subview code with direct indexing, it is always slow. A question is whether the slowness is acceptable or not. 
 
Regarding to subview overhead, there are a few possibilities to improve it. The subview overhead in dynrankview mostly comes from stride calculation (it computes strides for all 8 dimensions if I remember correctly while static views comute strides for its rank only). Since the subview happens in compile time (I mean the rank is compile time), possibly we can remove unnecessary stride calculation. Anyway subview implementation is very complicated and performance gain is small compared to the invested man power.  We can ask Kokkos developers about further plan about subview.
