### ISSUE TITLE
Zoltan2:  Add utility to compute seed matrix for automatic differentiation based on graph coloring

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#8356]
## Enhancement
@trilinos/zoltan2 @trilinos/tpetra

Add a utility to compute the seed matrix for automatic differentiation.  
Given a Tpetra CrsMatrix, compute the Seed matrix in a Tpetra::MultiVector.
Use partial distance-2 coloring when available; use distance-1 coloring of modified matrix if not.

@egboman @etphipps

**Comment by kddevin** [comment]
I added the colorer classes to Zoltan2; for now, they are on branch zoltan2_8356

An example using the colorer is here: https://github.com/trilinos/Trilinos/blob/zoltan2_8356/packages/zoltan2/test/core/TpetraCrsColorer/TpetraCrsColorer.cpp .  The interface is a little different from Eric's original design.  I moved the choice of coloring algorithm into the class, rather than having the user decide whether to use a Zoltan or Zoltan2 colorer object.  (The user can still specify that choice through a parameter, but the code will assign a default algorithm.)  

A few questions for @etphipp :

*    In the Colorer interface, about which functions does an application care?  Is the application interested in getting the actual colors, the seed matrix, and/or the compressed matrix? 
*    Is the reconstructMatrix operation useful only for testing, or would applications want it, too?
*    Is having computeSeedMatrixFitted in the public interface useful?  I plan to make just one public interface, computeSeedMatrix.  I would move the test for isLocallyFitted to computeSeedMatrix and do the import there only if needed.  Then there would be fewer chances that the users pick the wrong interface.  (Similar plan for reconstructMatrix.)
 *   Would users ever use the same Colorer object for more than one coloring (say, a second coloring with different parameters)?  If not, I will eliminate method computeColoring and move its work to the constructor.

A few questions for @egboman :

*    Does the logic for selecting the coloring method look correct? https://github.com/trilinos/Trilinos/blob/9881c99b085a1b8cab6c7da54a9728f03d2e2a1d/packages/zoltan2/core/src/TpetraCrsColorer/Zoltan2_TpetraCrsColorer.hpp#L207
 *   Do the parameters look sufficient to handle the cases (matrix type, symmetrization, etc.) that you care about?  What other parameters do we need?
*    What other tests are needed?  I know we still need to exercise the different libraries (zoltan vs zoltan2); those tests will be more relevant when Ian's work is available.  #8363 

Thanks, @etphipp and @egboman

**Comment by etphipp** [comment]
* In principle the user needs all of the methods in TpetraCrsColorer except for getColor().  I believe that one is only needed for additional testing the user may want to do (we use it in SPARC).  The general workflow is to compute the coloring, get the number of colors so the user can allocate the seed matrix and compression matrix with the appropriate number of columns, and compute the seed matrix entries.  The user then computes the compression matrix using their code, and then reconstructs the full sparse matrix.
* The reconstructMatrix operation is a critical step in the process.  That's how the full sparse matrix is computed from the compressed matrix the user provides.
* Explicitly having the fitted versions of the functions isn't necessary.  However is the locally-fitted test quick?  If not, it is nice to avoid it if the user knows the answer.
* I don't see why the user would want to do more than one coloring, but I believe I did it this way because in SPARC's initialization, the coloring can't be computed at the same time the coloring object is created (because other parts of the code haven't been setup yet).  I don't think that is critical, because the coloring object could probably be created later.

**Comment by etphipp** [comment]
BTW, the test looks great!

**Comment by egboman** [comment]
Thanks, Karen. I waited till I was able to actually build and run the tests. My comments:

- the logic mapping Jacobian/Hessian to coloring algorithm is correct

- the test parameters are good, but only Jacobian mode is tested so I will add a test for Hessian

- we should probably also look at the # colors, but perhaps it is OK to do manually so does not have to be part of the PASS/FAIL test

I should look at the symmetrization. I think GRAPH_SYMMETRIZE=TRANS is very conservative, bipartite graph will give less colors but perhaps it does not work correctly. Also, the A+A' symmetrization assumes square Jacobians, which is often the case but not always.

**Comment by egboman** [comment]
On second thoughts, I do not see why "symmetrize" need to be a user parameeter. I think this is an implementation detail and could be hidden from the user. Further, it is unclear to me why the colorer code has to build the transpose graph. In theory, Zoltan could do this using the GRAPH_SYMMETRIZE options. I am fine having this code as a temporary work around but we should check if some functionality is missing in Zoltan (or might potentially be a bug).

**Comment by etphipp** [comment]
You'll have to excuse my memory of the code, it has been quite a while since I wrote it.  There appear to be two paths:  one for symmetric/symmetrized graphs, and one for non-symmetric.  The transposed graph is only needed for the non-symmetric path.  In SPARC, we always hardcode the symmetrized path.  I don't remember why (and of course, I left no documentation/comments as to why).  My guess is the code does not work for some reason using an unsymmetric graph and not symmetrizing.  If necessary I can try changing this and recompiling SPARC to see what happens.  However I do believe the SPARC and Albany use-cases are always square.

**Comment by kddevin** [comment]
Actually, there appears to be a problem when using the compute_transpose_graph for the Zoltan callbacks; I can get invalid colorings when the domain/range map don't match the row map.  I will look into it.  
`mpirun -np 4 Zoltan2_TpetraCrsColorer.cpp --xdim=10 --ydim=20 --zdim=30`
The solution for now (and, perhaps, forever) is to use Zoltan's symmetrization (that is, set default value of symmetrize parameter to true or remove it as an option) as @egboman recommends.  This is consistent with what @etphipp did for SPARC.
@egboman is working on tests with nonsymmetric input; my test was symmetric but followed the symmetrization path because I didn't give the "symmetric" matrix clue.

**Comment by etphipp** [comment]
I never tested the case where the domain/range maps don't match the row map, so I guess it is no surprise there is a problem there.

**Comment by kddevin** [comment]
The initial version of the code is now ready for friendly users.

An example using the Colorer is in
zoltan2/test/core/TpetraCrsColorer.cpp; see method buildAndTestSeedMatrix.

Relevant parameters are
-  matrixType = Jacobian or Hessian :  we use this value to guess whether your matrix is symmetric
-  symmetric = true/false : alternatively, you can just tell us whether your matrix is symmetric
-  symmetrize = true/false : this parameter will eventually go away, but for now, it specifies how we symmetrize non-symmetric matrices.  The current default (true) is symmetrize as A+A^t and use distance-2 coloring; setting it to false will do bipartite symmetrization and use partial-distance-2 coloring.

For now, we require square matrices.

I will close this issue; we'll open new issues for future enhancements and/or bug fixes needed.
