### ISSUE TITLE
Panzer: Keeping Parent Elements in the regularly refined PerceptMesh changes most behavior

### ISSUE THREAD

**Issue by GrahamBenHarper** [trilinos/Trilinos#8475]
## Bug Report
@trilinos/panzer 
@rppawlo 

### Description
This bug was introduced in #8365. Since this is new functionality that I assume is only being used by me at the moment, the most important thing is to document this for posterity. When using the new feature, the underlying `stk::mesh` will have some buckets which contain only parent elements. Since Panzer never had to worry about this before, it makes sense that keeping this information can cause issues under the hood.

In the Q1 discretization case on Poisson physics, all this does is affect the assembly, and there is probably assembly occurring on parent elements. However, for Q2 and higher discretizations, this also changes the number of DOFs since DOFs will start living on mesh topology ranks which can have children, which is quite a large can of worms.

### Steps to Reproduce
I can reproduce this in #8440 with this new feature, but any test that uses `STK_ExodusReaderFactory` (for example, `adapters-stk/example/PoissonInterfaceExample` or `adapters-stk/example/PoissonInterfaceTpetra`) is fine for testing. Essentially you just need a parameter list for the factory that looks like this:
```
    mesh_pl->set("File Name",pamgenFileName);
    mesh_pl->set("File Type","Pamgen");
    mesh_pl->set("Levels of Uniform Refinement",1);
    mesh_pl->set("Keep Percept Data",true);
    mesh_pl->set("Keep Percept Parent Elements",true);
```
I can provide more information as needed.

### Steps to Fix
If I'm pointed in the right direction, I can personally take some steps to fix this. There are a couple approaches:
1. Have Panzer delete the parent elements under the hood right before assigning DOFs & assembling matrices. -- I'm fine with this, since the goal is to quickly save the mesh hierarchy upon mesh creation to later inform the MueLu preconditioner. This should have the smallest impact on performance.
2. Change all loops over the mesh to ignore parent element buckets since parent elements seem to be stored in separate `stk::mesh::Bucket`s. -- This is not hard, but tedious, and may impact performance. It also means there may be if statements in loops over mesh buckets, which could impact performance.

I'm open to other ideas as well, but this list is just a start.

**Comment by alanw0** [comment]
It sounds like the parent elements are in a certain stk::mesh::Part. If you get your buckets using some selector like this:
`stk::mesh::Selector selector = ownedPart & stk::mesh::selectUnion(myElementBlockParts);
stk::mesh::BucketVector& buckets = bulkData.get_buckets(ELEM_RANK, selector);`

Then if you know that the parent elements are in some part, you may be able to exclude them from your selector using something like this: `selector = selector & !parentElemPart;` prior to getting buckets.

Then you wouldn't need to adjust the logic for your loops over buckets.

**Comment by GrahamBenHarper** [comment]
Thanks @alanw0! That's a good point. I was looping over the `stk::mesh::BucketVector` obtained by `buckets = mesh->get_bulk_data()->buckets(ranks[i])` since I didn't know about selectors. Does that have a performance overhead?

**Comment by alanw0** [comment]
@GrahamBenHarper  getting buckets with a selector usually gives a performance advantage because BulkData does some internal selector-to-bucketvector caching such that if you have gotten buckets with a certain selector before, it will be much faster on subsequent times. Furthermore, when you then loop over the buckets to operate on them, you don't need any if logic to exclude the buckets you don't want. In certain scenarios it can make a big difference. If you have a big mesh with thousands of buckets, and your current algorithm only needs to operate on a few of them, then it can make a difference to not have to continually loop over all buckets of rank and check if each is selected.

**Comment by rppawlo** [comment]
@GrahamBenHarper - there are tons of examples of selector use in Panzer. Run git grep -i selector in the top level Panzer directory. We typically use them for selecting cells in specific element blocks since we allow for different equation sets in different element blocks, sidesets for boundary conditions and subcell connectivity. 

I would prefer choice #1 since there are probably too many places where we grab element lists and connectivity. It is probably application specific as to when to erase the parent elements as well. Maybe just having a function on stk_interface that deletes the parent elements is a start. I can look at where to add that call in the example problems. No rush on this. We should also add a warning to the doxygen and ParameterList validator for anyone using this feature.

**Comment by GrahamBenHarper** [comment]
@rppawlo that sounds good to me! I'll work on a PR for a delete parent elements call and adding some warnings.

**Comment by GrahamBenHarper** [comment]
@alanw0 @rppawlo I found something in Percept (UniformRefinerPattern.cpp line 490) that suggests we can filter out mesh parts by ones that contain parent elements. I'm having a little trouble making use of it. Any pointers?
`isOldElementsPart = ( (part->name()).find(UniformRefinerPatternBase::m_oldElementsPartName) != std::string::npos);`

**Comment by alanw0** [comment]
@GrahamBenHarper I guess that code is suggesting that the names of parts that contain parent elements, contain m_oldElementsPartName as a substring? That must imply something about the logic in either percept or panzer, but I'm not sure. stk itself doesn't impose that.

**Comment by GrahamBenHarper** [comment]
@alanw0 that's right. The last 3 parts of the mesh, "urp_oldElements3", "urp_oldElements2", and "urp_oldElements1", are likely the parts of the mesh I want to ignore. Is there a way to tell Panzer to ignore those when assembling information?

**Comment by alanw0** [comment]
@GrahamBenHarper I'm not familiar enough with panzer. There are basically two options: either delete the elements in these parts before panzer does its assembly, or if there is a central place where panzer creates a Selector for the element-blocks to process, you could remove these parts from the selector there by doing something like 'selector &= !urp_oldElementsPart'.
If panzer has something like an 'active' part that is already used when selecting things to process, you could make sure the elements in these parts are not active and then they would get skipped also.
