### ISSUE TITLE
Autotester Offline?

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#8529]
Been stuck in the queue w/o testing for 3 days

#8528

**Comment by allevin** [comment]
@csiefer2 @jwillenbring The Autotester jobs seem to be failing due to proxy issues.  Other projects are affected as well.  IT is looking to the issue.

**Comment by csiefer2** [comment]
Thanks for looking into this so quickly!

**Comment by csiefer2** [comment]
@allevin  Is this related to the proxy issue that has been blocking github access on a bunch of RHEL7 machine?  If so, that's been unresolved for *months*...

**Comment by allevin** [comment]
@csiefer2 I don't think so this seems to have started on the 29th and is affecting multiple OS platforms on multiple projects.

**Comment by atdm-devops-admin** [comment]
Looks like the main CDash site is down as well:

* https://testing.sandia.gov/cdash

Interestingly, the site:

* https://testing-dev.sandia.gov/cdash

looks to still be up.  (Therefore, we are still getting ATDM Trilinos and other Trilinos builds  that use the Trilinos TriBITS CTest driver.)  See:

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2021-01-03&filtercount=1&showfilters=1&field1=site&compare1=63&value1=

But most of the ATDM Trilinos builds are broken due to HTTPS authentication problems as described at:

* https://sems-atlassian-srn.sandia.gov/browse/ATDV-417

Switching to SSH authentication with GitHub seems to solve the problem.

**Comment by atdm-devops-admin** [comment]
FHI: With the main CDash site down:

* https://testing.sandia.gov/cdash

I don't think the autotester can work.

**Comment by crtrott** [comment]
Is there any update? Who is working on fixing this?

**Comment by william76** [comment]
@csiefer2 this is from Jan 4th. I'll close this out since it's probably not related to the most recent proxy problems that have been breaking the PR system.
