### ISSUE TITLE
kokkos:  when will the kokkos in trilinos support ROCm 4.0?

### ISSUE THREAD

**Issue by ipe-zhangyz** [trilinos/Trilinos#8533]
## Question
@trilinos/\<kokkos\>

I'm trying to build trilinos from source with ROCm 4.0 on AMD MI25 GPU and CentOS 7.4, and encounter some weird problems like "cannot reference a __host__ function from __host__ __device__ functions", which are all  from the kokkos package. I can build the kokkos alone from its develop branch on the same machine, but if I replace the kokkos in trilinos with the kokkos from https://github.com/kokkos/kokkos.git, there will be more other errors when building trilinos. I notice that the kokkos in trilinos are from the kokkos github repository, but not the latest commit. I wonder up to which version of ROCm I can use to build trilinos on my machine, and when it will  support ROCm 4.0. Thanks!

**Comment by jhux2** [comment]
@ipe-zhangyz Kokkos is developed on its own and snap-shotted into Trilinos, so the Trilinos version will always lag Trilinos develop.  @crtrott @trilinos/kokkos can answer your version question.

**Comment by crtrott** [comment]
Generally the 3.3.1 release we are waiting for to merge into Trilinos will likely work with 4.0 (note we didn't qualify it for 4.0). That does NOT mean Trilinos works though. Trilinos itself has a bit of work to do. Partly that is because it has a lot of places where it hardcodes stuff like Kokkos::Cuda or Kokkos::OpenMP. Furthermore, Trilinos relies on UVM for NVIDIA. That doesn't currently exist for AMD so we need to do a rather rude fallback to using HostPinnedMemory instead, which will make code run REALLY slow (talking like 100x slower or so). On top of that our initial experiments with Tpetra that Trilinos will run into a number of known bugs in HIP which will prevent correct execution. We are working with AMD to get that fixed.

**Comment by ipe-zhangyz** [comment]
Thanks for your reply!
