### ISSUE TITLE
Trilinos CMake large version bump

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#8682]
## Bug Report
@trilinos/All

### Description
CMake 3.17.0 or higher is required.  You are running version 3.12.3

Seems like a large bump in Cmake requirements? My guess is that I missed this new requirement. Any place that this was well socialized?

Best,

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

**Comment by spdomin** [comment]
Is this a Mac-only change? My gcc and intel builds are fine while my Mac OS nightly build and test is failing with the above config error.

**Comment by spdomin** [comment]
https://github.com/trilinos/Trilinos/commit/200c5cba447bf9bca55c5668c36c7b45a9ec03df

@william76 seems to have bumped this up. Any guidance would be appreciated.

**Comment by rppawlo** [comment]
@spdomin - This was announced in early December: github ticket (https://github.com/trilinos/Trilinos/issues/8401), trilinos email lists, and every week since December at the SART and Trilinos Developers meetings. We recently created a list of trilinos stakeholders for communicating such changes. We will make sure you are added (@ccober6 ).

This is an across the board update requested by many teams looking to use "modern" cmake. After a thorough review of what was installed on important internal machines (see ticket above) we could not bump the version any higher even though some teams wanted 3.18 specifically.

**Comment by spdomin** [comment]
Okay, sounds good. I will try to tune into these updates.

Now, I am investigating a Mac set of failures that seem to be related to skin_mesh in stk... @alanw0, not sure if Nalu-Wind still activates primitive STK-based hole cutting. A bisect will tell me for sure...

**Comment by alanw0** [comment]
@spdomin I'm not sure about the hole cutting. Perhaps that is what Shreyas has been replacing with the Tioga library?

**Comment by rppawlo** [comment]
FYI - trilinos also now requires c++14 as the minimum standard. This was required for the latest kokkos snapshot that went in on Monday.

**Comment by spdomin** [comment]
I think that c++ 14 was captured in gcc versions as early as 4.9-ish...

Thanks, I am all set (and I found the bug in Nalu from using a pre-mature null part in a selector).
