### ISSUE TITLE
Tpetra: Finish tools to determine OpenMP and MPI binding / affinities

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#872]
@trilinos/tpetra 
Assigned to: @jjellio
CC: @tjfulle 

James has tools, but needs to clean them for POSIX compatibility.
Affinity checking is done.
OpenMP is not done yet.  May need to getenv to figure this out.

**Comment by nmhamster** [comment]
@trilinos/tpetra what does this entail? Something like `OMP_DISPLAY_ENV=TRUE` might be sufficient for finding which binding domains are being used. It would be good to use the standard tools/environment variables if possible.

**Comment by mhoemmen** [comment]
@jjellio says "Yes."  He uses VERBOSE for that variable.  aprun from Cray dumps all info from all procs to Proc 0.  It confuses information from the different processes.  Will need to figure that out.

**Comment by jjellio** [comment]
@nmhamster I use the environment variable currently (OMP_DISPLAY_ENV=verbose). There are a few issues with it:
1) Some process launchers funnel all outputs to rank 0, and the OMP ENV stuff does not use the host name (or some other identifier) to make it clear which display corresponds to which rank.

2) The "environment" variables in OMP_DISPLAY_ENV, are not system environment variables, so you can't do something like getenv("FOO"), unless FOO was explicitly set prior to launch. E.g., you can programmatically access the variables if they are using their default values

I currently have a tool that figures out 'local ranks', e.g., MPI processes that share the same hardware. With this information, I then want to add the OMP information so I can record the state of each MPI process and reason about whether the environment looks correct. Currently, the tool pulls affinity information using the pthreads API (pthread_getaffinity_np). The idea is to then combine the OMP info, with affinity info, with hwloc-ls, and automate the discovery of bad mappings. For now, I simply want to capture the OMP info at the process level, I have the other stuff already complete. I can do the actual analysis using Python.

**Comment by nmhamster** [comment]
@jjellio any chance we can do this without hwloc? It would make it easier on some machines if we could just directly hit NUMA calls.

**Comment by jjellio** [comment]
I don't need hwloc actually.  The pthread api allows you to get good affinity info, but I am not sure how well it is supported by Cray/Intel threads. On Bowman/Shepard, this tool reports exactly the same affinity info as KMP_AFFINITY=verbose or OMP_DISPLAY_ENV verbose.

I like Hwloc though, because I can then work out the actual topology of 'where' the threads in a processes ran on a node. So my goal is to use hwloc if available to get nodal topology info (where CPUSETS map physically). I think I could do the same thing with libnuma though.

The point for me, is to make sure that the jobs I run look credible. That way, when something is not performant I will have as much relevant data as possible to narrow down issue.

**Comment by kddevin** [comment]
Resolve at Kokkos / job scheduler level
