### ISSUE TITLE
Tpetra: Determine provisional data storage format (w/ metadata) for performance testing

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#874]
@trilinos/tpetra 
Assigned to: @tjfulle , @jjellio

**Comment by srajama1** [comment]
Adding @krcb as he is planning to do it for KokkosKernels. This could all be shared or related.

**Comment by mhoemmen** [comment]
@jjellio emphasizes here the importance of capturing metadata relating to process and thread affinity and binding.  The same approach could also apply to CUDA -- e.g., environment variables like CUDA_LAUNCH_BLOCKING.

**Comment by mhoemmen** [comment]
Clarification: In discussion with @crtrott and @kddevin , we resolved that this is more properly a Trilinos Framework issue.  Tpetra is already instrumented using Kokkos profiling hooks (both parallel loops and regions), which a Framework-based tool could collect and display, without any changes to Tpetra.

**Comment by jjellio** [comment]
We standardized around Teuchos Timers and YAML output. This is extremely coarse, but it is sufficient for identifying general performance trends. The output is also supported by all relevant Trilinos apps.

**Comment by nmhamster** [comment]
@jjellio - we have plans underway to integrate Kokkos profiling hooks into performance testing. The hooks are available /outside/ of Trilinos and so are important in that they connect to the application as well. This sounds like it needs a careful though, perhaps even integration of the Kokkos hooks into Teuchos as well if we want to capture application and Trillinos performance information in the same runs. BTW - we collect more than just timers in the Kokkos hooks.

**Comment by nmhamster** [comment]
@jjellio - just FYI as well, the Kokkos timer connectors can also dump YAML. Perhaps, there is a way to blend the YAML outputs as well as an alternative?

**Comment by mhoemmen** [comment]
@nmhamster @jjellio See feature request to add Kokkos profiling region hooks to `Teuchos::TimeMonitor`: https://github.com/trilinos/Trilinos/issues/1914

**Comment by mhoemmen** [comment]
@jjellio `Teuchos::TimeMonitor` could do both.  If not linking with the Kokkos profiling library, the profiling hooks have very little overhead.  Actually using profiling may have some overhead, but it shouldn't have more than what Teuchos already does (start and stop timers).

**Comment by ibaned** [comment]
Can someone post an example or description of this YAML format? Is there code in Trilinos to output this that we can use as a reference?

**Comment by mhoemmen** [comment]
@jjellio Is the YAML format to which you refer just the output format of `Teuchos::TimeMonitor::report`?  If so, the source code would be the best documentation.

**Comment by jjellio** [comment]
@ibaned @mhoemmen

I've used report() with YAML output requested. The only thing you need to do if pass a parameter list that specifies YAML rather than TABLE. You can also control whether YAML is compact or spacious.

All of that said, see #1917, I hunted down an annoying bug that was causing some hell in my performance scripts. This likely means that specific code path will be refactored either by me or @jhux2

@ibaned, we should talk if you are interested in YAML. I've tried to do some freaky things with YAML output in other areas. Namely, I tried to write a Teuchos::ParameterList to a std::stringstream, then turn around and parse the supposed YAML compliant output using YAML-cpp. The motivation for doing this is to be able to build a parameter list in my app, and then write that plist to YAML. Effectively using the plist as a poorman's hdf5 repository of goodness. This doesn't work currently, and is low priority on my end. So, I haven't waded into why.

All of my dialog is off topic for this issue though.

**Comment by ibaned** [comment]
@jjellio thanks for the info! I think I've tricked myself into maintaining Teuchos's YAML code, so feel free to email me regarding these issues

**Comment by mhoemmen** [comment]
@ibaned You _did_ write a YAML parser ;-) .
