### ISSUE TITLE
Tpetra::CrsMatrix: Optimize sumIntoLocalValues for common case where input is shorter than # entries in matrix row

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#877]
@trilinos/tpetra 
CC: @crtrott, @nmhamster 

  1. Strip-mine input indices and values by some small compile-time constant K (e.g., 8)
  2. Copy those K indices and values into a temporary buffer of length K
  3. #887: Sort the indices and values jointly by indices (Tpetra::sort2 or equivalent algorithm)
  4. Use (sorted, sorted) search (different than findRelOffset) so that you pass over the entries in the matrix's row at most once

**Comment by mhoemmen** [comment]
Notes for the sort:

  - Use a sorting network: http://pages.ripco.net/~jgamble/nw.html
  - In the sorting network, use the SWAP operation here: http://stackoverflow.com/questions/2786899/fastest-sort-of-fixed-length-6-int-array

**Comment by nmhamster** [comment]
@mhoemmen we might be able to produce very fast intrinsics based variants for KNL and Haswell. I think you might want to consider some form of preprocessor definitions around this call so we can drop in the faster variants if we can work them out?

**Comment by mhoemmen** [comment]
@nmhamster I was planning on separating out the custom sort into a function anyway.  I could definitely add some macros (e.g., through CMake) so you could substitute in your own awesome code :-D  The only wrinkle is that I would need a "sort2," that is, sort by indices and use them as keys to reorder the corresponding values.

**Comment by mhoemmen** [comment]
@nmhamster I'm moving this to Q2, since planning and other Q1 tasks took more time than expected.

**Comment by mhoemmen** [comment]
See also #834 and #941.  Some work I've been doing for those is related.

**Comment by vbrunini** [comment]
I spent a bit of time today putting together a little benchmark for findRelOffset that compares doing it on unsorted input indices to sorting the input indices and then doing a linear search using the offset of the last column index as the starting point. A few takeaways:

1. The default linear search threshold of 16 in findRelOffset is too conservative. I was testing for rows with 27 indices in them and linear search was significantly faster than binary on Sandybridge, Haswell, and KNL. I didn't test larger row lengths but that is probably worth investigating.
2. Doing the sort and then changing the linear search portion of findRelOffset to take advantage of the hint so that only a single pass through the column indices happens was a win on all 3 platforms.
3. I think for finite element use cases embedding the sort into sumIntoLocalValues for a single row is going to miss out on some optimization opportunity. Typically we are iterating elements and then applying contributions to the matrix rows for the nodes of that element where the column indices used for every row are the same (they are just the indices of the nodes in the element). I would propose a strategy like this:

- Sort the column indices that will be used for every row contribution in this element, and save the permutation from the original ordering to the sorted ordering.
- For each row of contributions in the element apply the permutation that was saved to the row values that need to be inserted, and then call sum into with the sorted column indices and appropriately permuted contribution values.

That way we only have to do the sort once per # nodes/element calls to sumInto. I'd be open to either having functions that sort & create the permutation and then another to apply the permutation available and we can do it on our end, or creating a new sumInto interface that uses the same column indices for multiple rows and handles all this behind that interface.

**Comment by mhoemmen** [comment]
Hi @vbrunini !  Thanks for working on this!  I've been out of band this week and will be for a couple more days.  I had an implementation of the sorted input + sorted rows search strategy in progress on my workstation, but got locked out of that temporarily last week.

I like your approach of optimizing for multiple rows.  I was thinking of a related optimization, namely strip-mining the input into sorted chunks, so that the sorted temporary array would take constant (e.g., SIMD length) storage.  However, if we just sort on the first pass and reuse those indices, that could be more effective yet.  Let's talk more when I get back :-)

**Comment by mhoemmen** [comment]
@vbrunini tested the approach of sumInto-ing a whole element at once.  Here's how it works:

  1. Sort the row/column indices (the function assumes the same indexing for both); remember the permutation
  2. Pass in the whole element, and do linear single passes over each row's column indices, with (atomic) +=.

Performance was better, though not astonishingly better.  @vbrunini also found that the linear->binary switch threshold should perhaps be 64 (higher than what it is now).

**Comment by mhoemmen** [comment]
We tried optimizing the element-at-a-time case further, but didn't get very far.  The next step might be to outer-loop-vectorize across multiple elements, by pushing the SIMD element things inside.

@crtrott @nmhamster @vbrunini

**Comment by mhoemmen** [comment]
My commit 85d8d9e2b582b03cdb85b69a59cf7f8eb6db82ce partly addresses this.
