### ISSUE TITLE
seacas: 'decomp' script isn't installed

### ISSUE THREAD

**Issue by jrobbin** [trilinos/Trilinos#8776]
## Bug Report
@trilinos/seacas

### Description
After installing trilinos using spack, seacas binaries are in the installation/bin directory, but seacas scripts (i.e., decomp) are not.  

### Steps to Reproduce
```shell
git clone https://github.com/spack/spack.git
source spack/share/spack/setup-env.sh
spack install trilinos
spack load trilinos
which exodiff
which decomp
```
The exodiff binary is found as expected, but the decomp script is not.

**Comment by gsjaardema** [comment]
I will take a look.  I know it works correctly with a "spack install seacas; spack load seacas".

I will have to figure out what is different when installed as part of Trilinos instead of by itself...

**Comment by gsjaardema** [comment]
The reason that decomp is not installed is that `chaco` is disabled which means that `nem_slice` is disabled which means that `decomp` is disabled.  Supposedly `chaco` is disabled due to a global symbol `divide` which leads to symbol clashes...

If you install `trilinos+chaco`, then you should get `decomp`

I will look into chaco and see if I can rename `divide` to some more obscure symbol.

**Comment by gsjaardema** [comment]
Expanding on my previous comment.  The Trilinos spack package has chaco explicitly disabled:
```
    # chaco is disabled by default. As of 12.14.1 libchaco.so
    # has the global symbol divide (and maybe others) that can
    # lead to symbol clash.
    variant('chaco',       default=False,
            description='Compile with Chaco from SEACAS')
```
This then causes nem_slice to be disabled:
```
        if '+chaco' in spec:
            options.extend([
                define('Trilinos_ENABLE_SEACAS', True),
                define('Trilinos_ENABLE_SEACASChaco', True),
            ])
        else:
            # don't disable SEACAS, could be needed elsewhere
            options.extend([
                define('Trilinos_ENABLE_SEACASChaco', False),
                define('Trilinos_ENABLE_SEACASNemslice', False)
            ])
```
If you look at the rules for `decomp` in `packages/seacas/scripts/CMakeLists.txt`, you see:
```
ASSERT_DEFINED(${PROJECT_NAME}_ENABLE_SEACASNemspread)
ASSERT_DEFINED(${PROJECT_NAME}_ENABLE_SEACASNemslice)
IF (${PROJECT_NAME}_ENABLE_SEACASNemspread AND ${PROJECT_NAME}_ENABLE_SEACASNemslice)
  CONFIGURE_FILE(
	${CMAKE_CURRENT_SOURCE_DIR}/decomp.in
	${CMAKE_CURRENT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/decomp
	@ONLY
	)
  FILE(COPY ${CMAKE_CURRENT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/decomp
       DESTINATION ${CMAKE_CURRENT_BINARY_DIR}
       FILE_PERMISSIONS OWNER_READ OWNER_WRITE
         OWNER_EXECUTE GROUP_READ GROUP_EXECUTE)
  INSTALL(PROGRAMS ${CMAKE_CURRENT_BINARY_DIR}/decomp DESTINATION bin)
ENDIF()
```
Since `Nemslice` is not enabled, then the decomp script will not be installed since it requires both nem_slice and nem_spread.

However, I did verify that `spack install trilinos+chaco` does build `nem_slice` and `chaco`. 

I'm not sure why having the `divide` symbol in the chaco library causes much issue for Trilinos in general since AFAIK, only nem_slice links to chaco and there should be no way that the chaco library can pollute symbols unless an application explicitly links to the chaco library.  I have renamed `divide` to `chaco_divide` in chaco and will sync that over to Trilinos in my next seacas snapshot.  At that point, maybe I/someone can modify the Trilinos spack package to enable chaco by default.

**Comment by gsjaardema** [comment]
Closing as there has been no discussion in the past 6 months.  I think I have adequately answered the question.
