### ISSUE TITLE
Zoltan2::EvaluatePartition - calculates metric inside the constructor

### ISSUE THREAD

**Issue by mndevec** [trilinos/Trilinos#881]
EvaluatePartition has a shared constructor in which the all available metrics are calculated. This created some issues when I inherit a new class from EvaluatePartition. 

I am currently working on the mapping problem. Many classes in mapping problem inherit from the classes of partitioning problem, since a mapping problem is also a partitioning problem with extra considerations including the underlying network topology. MappingSolution inherits PartitioningSolution, EvaluateMapping inherits EvaluatePartition, so that I can add new functionalities with minimal code.

I was adding virtual metric calculation functions to EvaluatePartition so that EvaluateMapping would over-write them. However, since these functions are called within the constructor, virtual functions do not work, as the constructor of the child class hasn't overwrite the virtual functions. 

This is not an issue for EvaluatePartition class itself, but moving the metric calculation out of EvaluatePartition would make the life much easier for EvaluateMapping class. This will require addition of evaluate function (as 3rd line below), which requires updates all over the code. I am willing to do this change, if you agree on this.

```c++
typedef Zoltan2::EvaluatePartition<my_adapter_t> quality_t;
RCP<quality_t> metricObject_1 = rcp(new quality_t(input_adapter,problemParams,comm,solution));
metricObject_1->evaluate();
metricObject_1->printMetrics(cout);
```

@trilinos/zoltan2

**Comment by MicheldeMessieres** [comment]
@kddevin, @mndevec hi Mehmet - I currently have some work in progress (PR #849) which does quite a bit of reorganizing on those classes. I do not think those changes really impact what you are dealing with but just wanted to be aware. Since you are working on a derived version of EvaluatePartition I expect merging your changes with mine will not cause any great difficulty.

One idea might be to set a flag bMetricsCalculated false and then have the functions which access it check that flag and calculate the metrics if they haven't been done already.  That would avoid forcing users to call the extra method and give you the polymorphic structure you need - this might be easier for you as well.

You could place that check into the methods getAllMetricsOfType and printMetrics - I think that will cover you for everything in EvaluatePartition. Then if Karen agrees, I could make the appropriate modifications so this works generally with the new refactoring (I would put that flag into the new EvaluateBaseClass).

Also as I continue working on this, I am curious if you needed to just shut off some stuff in the EvaluatePartition constructor or was there anything else you needed to override? If so, the new changes may help with this and hopefully not hinder but any further information might help me organize.

**Comment by mndevec** [comment]
Michel, 
If I understood correctly, bMetricsCalculated flag can solve my problem. 
-In that case,
1) constructor will have a boolean parameter to whether to calculate metrics in the constructor or not.
2) shared_constructor function still needs to be changed to evaluate function that can be called publicly. When this function is called bMetricsCalculated will be set to true. 
3) when printMetrics is called, if bMetricsCalculated is not set to true, it will call the evaluate function first then print metrics. 

This won't require any change in the calls. PartitionMapping can force to call evaluate function outside of the constructor as well. 

Does that sound right?

- I added message metrics to GraphMetricsUtility class, and EvaluatePartition calls this function. My edits are minimal in EvaluatePartition. I just wrapped all graph metric calculations within a virtual function in the class, so that I can overwrite it in EvaluateMapping class.

**Comment by mhoemmen** [comment]
Hi @mndevec !  Sorry to elbow my way into this conversation, but one thing that could help here would be to hide your new class' constructor, and only make available instances of the class through a nonmember function.  This function would construct an instance of the class, then tell the class to compute metrics, and then finally return the fully constructed object.  That way, users would never see a partially constructed object.

**Comment by MicheldeMessieres** [comment]
@mndevec @kddevin I'm guessing there will be some requirements to keep the API consistent and not changed so I think we'd have to get Karen's feedback before making any API formatting changes.

I think Mark's idea is bette, gives us a more general solution, and would be less confusing. That might involve changing slightly how users call the construction so I think we'll have to find out exactly what the constraints are on changing the API. Or we'd put EvaluatePartition in a factory with lots of API wrappers which seems awkward.

We have the parameter list as well - possibly it is appropriate to use that to customize the construction of the class. Doesn't seem like that is best here but it could be used for a short term solution to minimize changes to the current EvaluatePartition setup.

Having a polymorphic construction by some means seems like it would be a good goal here but we'll need to Karen to clarity what is allowed.

**Comment by mndevec** [comment]
@mhoemmen Thanks for the help! But I could not yet understand your suggestion, I will stop by office to ask about that.

@MicheldeMessieres, currently the modifications I have done (to be able to pass this point) are:
 - add one more constructor to EvaluatePartition class. In that constructor the sharedConstructor is not called, and that is the constructor called by EvaluateMapping class.
 - I call sharedConstructor from the constructor within EvaluateMapping. This requires sharedConstructor to be protected, rather than private.

I will try to talk to @mhoemmen  and @kddevin ,  whenever I have chance, and see how to proceed.

**Comment by mhoemmen** [comment]
@mndevec wrote:
> Thanks for the help! But I could not yet understand your suggestion, I will stop by office to ask about that.

I'll likely be out of office all week, since my mother is visiting.  Here is an example:
```
// The base class.  
// DerivedClass (below) represents the class you want to implement.
class BaseClass {
public:
  BaseClass ();
};

// The "factory" that creates an instance of DerivedClass, 
// and optionally tells it to compute its metrics,
// before returning a pointer to the instance.
// Caller is responsible for freeing the instance.
BaseClass* createInstance (const bool doComputeMetrics);

// The derived class, that you want to implement.
class DerivedClass : public BaseClass {
private:
  // Constructor is private, and does NOT compute metrics.
  // Users must call createInstance to get an instance of DerivedClass.
  DerivedClass ();

  // Give createInstance permission to call DerivedClass' constructor.
  friend BaseClass* createInstance (const bool doComputeMetrics);

public:
  // Compute metrics; this is collective over the object's communicator.
  void computeMetrics ();
};

// Implementation of createInstance.
BaseClass* createInstance (const bool doComputeMetrics) {
  DerivedClass* dc = new DerivedClass ();
  if (doComputeMetrics) {
    dc->computeMetrics ();
  }
  return dc;
}
```

**Comment by mhoemmen** [comment]
I forgot one thing.  Suppose that you want users still to be able to call DerivedClass' constructor, and you want this explicit call to DerivedClass' constructor to compute metrics (so that it behaves just like BaseClass).  However, you want createInstance _not_ to compute metrics.  Here is an example (I omit some things that don't change from above).
```
class DerivedClass : public BaseClass {
public:
  // Constructor for users; always computes metrics.
  DerivedClass ();

private:
  // "Tag" to mark use of DerivedClass' private constructor
  struct DerivedClassPrivateConstructorTag {};

  // Private constructor, that NEVER computes metrics.
  DerivedClass (DerivedClassPrivateConstructorTag);

  // Give createInstance permission to call DerivedClass' constructor.
  friend BaseClass* createInstance (const bool doComputeMetrics);

public:
  // Compute metrics; this is collective over the object's communicator.
  void computeMetrics ();
};

// Implementation of createInstance.
BaseClass* createInstance (const bool doComputeMetrics) {
  // Use the tag to select the private constructor.
  // Otherwise, you would get the public constructor, 
  // that does compute metrics.
  DerivedClass* dc = new DerivedClass (DerivedClass::DerivedClassPrivateConstructorTag ());
  if (doComputeMetrics) {
    dc->computeMetrics ();
  }
  return dc;
}
```
You only need to use the tag technique if the two constructors otherwise would take the same arguments.  If the two constructors take different arguments, then you don't need a tag to distinguish them.

**Comment by mhoemmen** [comment]
oops, sorry, closed this by mistake.

**Comment by mhoemmen** [comment]
btw the above technique is called "tag dispatching."  The C++ Standard Library uses this to select the most efficient generic algorithm, based on whether a standard container's iterators implement certain features.
