### ISSUE TITLE
checkin-test-sems.sh cannot find module command from non-bash shells

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#906]
In #895, it was discovered that checkin-test-sems.sh could not find the "module" command from shells that were not bash shells.  The problem is not specific to Mac OS X; I can reproduce it on a RHEL system.  Thus, I am starting a new issue (but leaving much of the background in #895).

I think the issue with bash vs other shells is that
/usr/local/opt/modules/Modules/init/bash
defines the "module" command as a function for bash, while for other shells, "module" is defined as an alias (e.g., /usr/local/opt/modules/Modules/init/tcsh).

Aliases don't get transferred to the bash script checkin-test-sems.sh in the same way that the module function is.  
http://unix.stackexchange.com/questions/1496/why-doesnt-my-bash-script-recognize-aliases

Thus, checkin-test-sems.sh fails to find the module command, and eventually fails.

A workaround is to run checkin-test-sems.sh from a bash script that first sources /usr/local/opt/modules/Modules/init/bash.  Doing so is only a little hassle, but it allows checkin-test-sems.sh to at least launch correctly.  If this workaround is the final solution, it needs to be documented somewhere (besides here).  But perhaps there is a better solution that can be implemented within checkin-test-sems.sh.

**Comment by kddevin** [comment]
@bartlettroscoe @trilinos/framework

**Comment by bartlettroscoe** [comment]
@kddevin, I think we can accommodate the tcsh as well as bash.  It will create some duplication but it is not the end of the world.  We support tcsh and bash with the checkin-test.py driver for CASL VERA for example.

For me to reproduce this, I will have to be able to duplicate exactly what other developers would do.  Given that my default shell is bash, how would I reproduce this so that I can fix this?  I guess I could change my default shell when I log in?

In any case, we will get this fixed.

**Comment by bmpersc** [comment]
Very likely the solution to this would be to setup the SEMS NFS for both csh and bash on any machine that will be using the checkin test script. The SEMS instructions for setting up the NFS cover how to do both shells. That way when any bash scripts are invoked they will properly load all of the setup for the modules.

**Comment by bartlettroscoe** [comment]
> The SEMS instructions for setting up the NFS cover how to do both shells. That way when any bash scripts are invoked they will properly load all of the setup for the modules.

How would I effectively test this to make sure that it works?  Would I need to temporarily change my default shell to tcsh so that when I first log in that it would just be on tcsh right from the very beginning?

Anyway, I think supporting (t)csh in addition to bash is important for the basic usage of the checkin-test-sems.sh script in #482 so I would like to get this fixed sooner rather than later.

**Comment by bartlettroscoe** [comment]
We are no longer going to purse extending the checkin-test-sems.sh (or checkin-test.py) script for Trilinos.  See https://github.com/trilinos/Trilinos/issues/482#issuecomment-266124179.

Closing and won't fix.
