### ISSUE TITLE
Framework:  Autotester merged PR that isn't passing

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#9375]
## Bug Report
@trilinos/framework 
### Description
The autotester merged PR #9210 even though it hasn't passed all of the required PR testing.

**Comment by jhux2** [comment]
@prwolfe @jwillenbring @ZUUL42

**Comment by ZUUL42** [comment]
I think we figured out what happened...
9210 was 1 commit, [SHA d3730e35954b8addc7a292ede109f47bf9dbec43](https://github.com/trilinos/Trilinos/pull/9210/commits).
[Searching for that SHA](https://github.com/trilinos/Trilinos/pulls?q=d3730e35954b8addc7a292ede109f47bf9dbec43), I find that #9371 did pass and includes that same commit.
The system sees that and so marks 9210 as merged since it's changes have already been merged in.

**Comment by jhux2** [comment]
@ZUUL42 Thank you for the explanation.  I'm guessing this is a really rare occurence.

**Comment by jwillenbring** [comment]
@jhux2 The hint that @william76 caught was that there was no testing prior to the merge, no action seemingly taken, and none of the usual comments from the autoteter that would have said it was merged. This happens all the time for dev->master merges, but I suspect it is much more rare outside of the dev->master testing as you say.
