### ISSUE TITLE
Panzer: Add IOSS information records to the output

### ISSUE THREAD

**Issue by tkordenbrock** [trilinos/Trilinos#9436]
## Enhancement
@trilinos/panzer 

Develop a way for Panzer clients to add Information Records to their IOSS output.

**Comment by gsjaardema** [comment]
Since this may not be documented very well (or at all), here is a little information:

- You can include the contents of a file (for example the application input file) in the information records by setting the database property `input_file_name`.  The contents of this file will be embedded in the info records.  Lines longer than 80 characters will be split and a `\` appended to the line.
- The application can also add lines to the `informationRecords` which is a `std::vector<std::string>>`.
- You get access to it via `region->get_database()->get_information_records()` which returns a reference to the vector.  You can then push_back lines to it for use in info records

In addition to the above information, the info records will also include the configuration details for the build of IOSS including library versions and parallel status...

**Comment by gsjaardema** [comment]
And just for completeness/more information, the application name and version can be put in the QA records with the database properties:

- `code_name`
- `code_version`

Both can be up to 32 characters in length.  The database title is set with the database property `title` which can be up to 80 characters.

**Comment by tkordenbrock** [comment]
Thanks @gdsjaar .  When you use `input_file_name`, does the entire contents of the file get added as a single info record?

**Comment by gsjaardema** [comment]
No, each line of the input file is a separate line or more (split into 80-character pieces) of the contents of the file.
