### ISSUE TITLE
checkin-test-sems.sh with GCC 4.7.2 fails on RHEL 7

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#945]
Using the new checkin-test-sems.sh script on a SEMS-enabled RHEL 7 machine fails.

Obviously, the script loads the modules
`sems-gcc/4.7.2` and `sems-cmake/3.5.2`

The `cmake` call crashes with the following error message

> cmake: /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/4.7.2/base/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by cmake)

This is obviously a problem with the SEMS module for cmake.

**Comment by tawiesn** [comment]
A workaround is to manually load a newer compiler module, e.g.
`module load sems-gcc/4.9.3`

The `checkin-test-sems.sh` script then complains

> TRILINOS_DIR = '../../Trilinos'
> Loading Trilinos SEMS Dev Env = 'sems-gcc/4.7.2 sems-openmpi/1.6.5 sems-cmake/3.5.2'!
> sems-gcc/4.7.2(3):ERROR:150: Module 'sems-gcc/4.7.2' conflicts with the currently loaded module(s) 'sems-gcc/4.9.3'
> sems-gcc/4.7.2(3):ERROR:102: Tcl command execution failed: conflict sems-gcc sems-intel sems-pgi sems-clang
> 
> Currently Loaded Modulefiles:
>   1) sems-env                       3) sems-cmake/3.5.2               5) sems-python/2.7.9              7) sems-zlib/1.2.8/base           9) sems-netcdf/4.3.2/parallel    11) sems-superlu/4.3/base
>   2) sems-openmpi/1.6.5             4) sems-gcc/4.9.3                 6) sems-boost/1.55.0/base         8) sems-hdf5/1.8.12/parallel     10) sems-parmetis/4.0.3/parallel
> File local-checkin-test-defaults.py already exists, leaving it!

but it proceeds and works as expected.

What is the right way to fix this? Either fix the problem with the SEMS module or choose a different compiler depending on RHEL 6 or RHEL 7?

**Comment by tawiesn** [comment]
@trilinos/framework 
@bartlettroscoe

**Comment by bartlettroscoe** [comment]
> The cmake call crashes with the following error message
>
> >    cmake: /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/4.7.2/base/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by cmake)
>
> This is obviously a problem with the SEMS module for cmake.

I wonder if we can find a way to get the GCC 4.7.2 SEMS env to work on RHEL 7?  We really don't want to push changes to Trilinos only testing with GCC 4.9 since GCC 4.9.3 will accept C++11 code that GCC 4.7.2 will not.  We had an example of this happening a few weeks ago.  We have a very important internal SNL customer that requires GCC 4.7.2 so it would be bad if we did not test with GCC 4.7.2 before we push to the 'develop' branch.

If someone gives me a login to a RHEL 7 machine then I can see if I can get the SEMS env to work with GCC 4.7.2 and otherwise submit a help ticket to the SEMS team to see if we can fix this.

**Comment by tawiesn** [comment]
The SEMS GCC 4.7.2 compiler works with the SEMS cmake 2.8.x modules on RHEL 7. So, one can load
`module load sems-cmake/2.8.12`
but then the configure call fails since it cannot find Parmetis 4.0.3.
I checked the `sems-parmetis/4.0.3/parallel` module and it looks fine to me. I don't know why the configure script fails. It should not.
Where can i post SEMS tickets?

**Comment by tawiesn** [comment]
Here is the output of the configuration run:
[configure.out.txt](https://github.com/trilinos/Trilinos/files/664692/configure.out.txt)

Using the following command
`tawiesn@enigma.sandia.gov:~/checkin/Trilinos/CHECKIN-SEMS$ ./checkin-test-sems.sh --do-all`
results in
> TRILINOS_DIR = '../../Trilinos'
> Loading Trilinos SEMS Dev Env = 'sems-gcc/4.7.2 sems-openmpi/1.6.5 sems-cmake/3.5.2'!
> sems-cmake/3.5.2(3):ERROR:150: Module 'sems-cmake/3.5.2' conflicts with the currently loaded module(s) 'sems-cmake/2.8.12'
> sems-cmake/3.5.2(3):ERROR:102: Tcl command execution failed: conflict sems-cmake
> 
> Currently Loaded Modulefiles:
>   1) sems-env                       3) sems-parmetis/4.0.3/parallel   5) sems-python/2.7.9              7) sems-boost/1.55.0/base         9) sems-hdf5/1.8.12/parallel     11) sems-superlu/4.3/base
>   2) sems-cmake/2.8.12              4) sems-gcc/4.7.2                 6) sems-openmpi/1.6.5             8) sems-zlib/1.2.8/base          10) sems-netcdf/4.3.2/parallel
> File local-checkin-test-defaults.py already exists, leaving it!
> 
> Script: checkin-test.py \
>   --src-dir='/home/tawiesn/checkin/Trilinos/cmake/tribits/ci_support/../../..' \
>   --default-builds='MPI_RELEASE_DEBUG_SHARED_PT' \
>   --extra-repos-file='' \
>   --extra-repos-type='' \
>   --extra-repos='' \
>   --require-extra-repos-exist \
>   --enable-packages='' \
>   --enable-extra-packages='' \
>   --disable-packages='Rythmos' \
>   --enable-all-packages='auto'\
>   --enable-fwd-packages \
>   --continue-if-no-updates \
>   --continue-if-no-changes-to-push \
>   --continue-if-no-enables \
>   --extra-cmake-options='' \
>   --test-categories='BASIC' \
>   -j4 \
>   --make-options='' \
>   --ctest-options='' \
>   --ctest-timeout=300.0 \
>   --no-show-all-tests \
>   --st-extra-builds='' \
>   --extra-builds='' \
>   --send-email-to='tawiesn@sandia.gov' \
>   --skip-case-no-email \
>   --send-build-case-email=always \
>   --send-email-for-all \
>   --send-email-to-on-push='trilinos-checkin-tests@software.sandia.gov' \
>   --no-force-push \
>   --do-push-readiness-check \
>   --rebase \
>   --append-test-results \
>   --do-all \
> 
>
and finally the checkin test fails during the configuration because of the Parmetis problem.

**Comment by bartlettroscoe** [comment]
> The SEMS GCC 4.7.2 compiler works with the SEMS cmake 2.8.x modules on RHEL 7. So, one can load
`module load sems-cmake/2.8.12` but then the configure call fails since it cannot find Parmetis 4.0.3.
I checked the sems-parmetis/4.0.3/parallel module and it looks fine to me. I don't know why the configure script fails. It should not.

That is interesting.  I found the same problem with CMake 3.7 .0.  I don't see anything wrong with the SEMS-installed ParMETIS libs either.  But I only see this problem with this particular ParMETIS install, and none others.  We can avoid this problem by writing out long-hand the location of the libraries (which avoids the find).  Let me try that with CMake 3.7.0 and CMake 2.8.12 and see if that fixes the find problem for ParMETIS.

> Where can i post SEMS tickets?

You can report problems like this here:

* https://sems.sandia.gov/content/submit-service-request

I have also alerted our Kitware contacts of this problem as well.

**Comment by tawiesn** [comment]
@bartlettroscoe Thanks
Using `sems-gcc/4.9.3` with the `sems-cmake/3.5.0` module works fine on RHEL 7. No problems with the `sems-parmetis/4.0.3` module in that configuration...

**Comment by bartlettroscoe** [comment]
@tawiesn, I have just pushed an updated version of `checkin-test-sems.sh` in the Trilinos commit dde3ea7 that will allow you load your own env first then run and it will leave it.  That will allow you to load exactly what will work on your RHEL 7 system based on what you have reported above (and I fixed the find problem with ParMETIS in commit 0960c82).  Just run with:

```
$ cd CHECKIN/
$ source ../cmake/load_ci_sems_dev_env.sh   # Does 'module purge' first!
$ module unload sems-cmake/3.5.2
$ module load sems-cmake/2.8.12
$ env TRILINOS_CHECKIN_TEST_SEMS_SKIP_MODULE_LOAD=1 \
  ./checkin-test-sems.sh --do-all --push
```

You can test locally by replacing `--do-all --push` with `--enable-packages=MueLu --local-do-all`.  That should hopefully pass.

Actually, if you don't mind, now that the CI build is fixed (see [here](http://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Linux-GCC-4.7.2-MPI_RELEASE_DEBUG_SHARED_PT_CI&field2=groupname&compare2=61&value2=Continuous&field3=buildstarttime&compare3=84&value3=now)), can you please run with `--enable-all-packages=on --local-do-all` and see if everything passes on your RHEL 7 machine?

Also, we should dig into why the SEMS env is not working for GCC 4.7.2 and CMake 3.5.2 and see if we can get this to work (or report a problem to the SEMS team with this env so that they can fix it).




Please let me know if this works for you now

**Comment by tawiesn** [comment]
@bartlettroscoe 

Fyi:
```
$ env TRILINOS_CHECKIN_TEST_SEMS_SKIP_MODULE_LOAD=1 \
  ./checkin-test-sems.sh --enable-packages=MueLu --local-do-all
```
with the old cmake (2.8.x) works fine on my RHEL 7 machine. I'll try `--enable-all-packages=on --local-do-all` next.

**Comment by tawiesn** [comment]
@bartlettroscoe 
```
$ env TRILINOS_CHECKIN_TEST_SEMS_SKIP_MODULE_LOAD=1 \
  ./checkin-test-sems.sh --enable-all-packages=on --local-do-all
```
gives
```
  Pull: Not Performed
  Configure: Passed (7.07 min)
  Build: Passed (113.30 min)
  Test: Passed (71.04 min)
  
  100% tests passed, 0 tests failed out of 2270
```
I think we can close this issue and update the Wiki.

**Comment by bartlettroscoe** [comment]
> I think we can close this issue and update the Wiki.

So what is the exact hack to get this to work on RHEL 7?    Is it as I said:

```
$ cd CHECKIN/
$ source ../cmake/load_ci_sems_dev_env.sh   # Does 'module purge' first!
$ module unload sems-cmake/3.5.2
$ module load sems-cmake/2.8.12
$ env TRILINOS_CHECKIN_TEST_SEMS_SKIP_MODULE_LOAD=1 \
  ./checkin-test-sems.sh [arguments]
```

?

Then we can open a separate issue and dig into why we have to use CMake 2.8.12 (as that is very slow compared to CMake 3.3.+).

**Comment by tawiesn** [comment]
Yes. It is exactly what you said. Load the CI SEMS environment, load Cmake 2.8.12 by hand and use the TRILINOS_CHECKIN_TEST_SEMS_SKIP_MODULE_LOAD=1 environment variable.
I added the comments in the [wiki](https://github.com/trilinos/Trilinos/wiki/Policies-|-Safe-Checkin-Testing). We can create a new issue for RHEL 7 and cmake 3.3

**Comment by bartlettroscoe** [comment]
@tawiesn, thanks for adding this to the Wiki!   I created the follow-on story #1001 to try to get the standard CI build for Trilinos to work correctly out of the box.

But note that this problem might go away (or we may have new problems) once we switch to GCC 4.9.3 (see #1002).

**Comment by tawiesn** [comment]
@bartlettroscoe I can state that the CMake problem will go away when using SEMS in a RHEL 7 environment and GCC 4.9.3. I have a set of docker containers which contain a subset of the SEMS environment based on SEMS GCC 4.9.3 and SEMS cmake 3.5.2 in CentOS 7.
