### ISSUE TITLE
Tpetra::Details::idot continuous test failure

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#946]
http://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2662728

@trilinos/tpetra 

I haven't been able to replicate this, even when using the new checkin-test-sems.sh check-in test script.  Will take a look.

**Comment by mhoemmen** [comment]
This test must be using an old MPI version.  With old MPI versions, Tpetra is forced to use MPI_Allreduce instead of MPI_Iallreduce to implement the nonblocking all-reduce.

Hm, how do I change the MPI version with the new checkin-test-sems.sh script?  I'll have to figure that out I guess.  @bartlettroscoe , any ideas?

**Comment by tawiesn** [comment]
@mhoemmen Try to load an old MPI version module by hand before you run the checkin-test-sems.sh script. It should be preserved and not overwritten by the checkin-test-sems.sh script. I know, this works for compilers, it should also work for the MPI libraries.

**Comment by mhoemmen** [comment]
@tawiesn Thanks!  It looks like checkin-test-sems.sh is _supposed_ to load OpenMPI 1.6.5 if nothing else has been loaded yet, and I know that version of OpenMPI is sufficiently old.  I'll just try a `module purge` and running the script again to see if that works.

**Comment by mhoemmen** [comment]
@tawiesn I was able to replicate the bug by purging modules before running the checkin-test-sems.sh script.  Now for debugging fun :)

**Comment by bartlettroscoe** [comment]
> 'll just try a module purge and running the script again to see if that works.

I am thinking that we need to run these bash scripts with `#!/bin/bash -e` to catch any problems loading the standard CI env and then die before running the inner checkin-test.py command.

Any objections to this?

**Comment by bartlettroscoe** [comment]
Actually, what load_sems_dev_env.sh and therefore checkin-test-sems.sh should do is to 'module purge' and then always load the env from scratch.  It looks like this is the only safe way to do this in case people have incompatible envs loaded already.  But since checkin-test-sems.sh runs in its own shell, this will not impact the users outer env, unless they need to reproduce a build.  I will fix this tomorrow unless there are objections.

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> Actually, what load_sems_dev_env.sh and therefore checkin-test-sems.sh should do is to 'module purge' and then always load the env from scratch. It looks like this is the only safe way to do this in case people have incompatible envs loaded already. But since checkin-test-sems.sh runs in its own shell, this will not impact the users outer env, unless they need to reproduce a build. I will fix this tomorrow unless there are objections.

I'm OK with that -- thanks!  It wasn't really a big deal -- it just took me a while to see that the script was using my existing modules, rather than loading the modules it wanted.

**Comment by rppawlo** [comment]
Can you make the module purge optional with default of enabled? A module purge caused a checkin test script to fail for me yesterday. I use a newer git version, loaded by a module, and some git options (set in my .gitconfig file) aren't supported in older versions of git. When I purged my environment and loaded the sems env, the checkin test script was failing on simple git commands with the following:

```
***
*** 2) Get repo status
***

error: Malformed value for push.default: simple
error: Must be one of nothing, matching, tracking or current.
fatal: bad config file line 13 in /ascldap/users/rppawlo/.gitconfig
error: Malformed value for push.default: simple
error: Must be one of nothing, matching, tracking or current.
fatal: bad config file line 13 in /ascldap/users/rppawlo/.gitconfig
error: Malformed value for push.default: simple
error: Must be one of nothing, matching, tracking or current.
fatal: bad config file line 13 in /ascldap/users/rppawlo/.gitconfig
---------------------------------------------------------------
| ID | Repo Dir        | Branch | Tracking Branch | C | M | ? |
|----|-----------------|--------|-----------------|---|---|---|
|  0 | Trilinos (Base) |        |                 |   |   |   |
---------------------------------------------------------------
```

**Comment by bartlettroscoe** [comment]
> Can you make the module purge optional with default of enabled? A module purge caused a checkin test script to fail for me yesterday. I use a newer git version, loaded by a module, and some git options (set in my .gitconfig file) aren't supported in older versions of git. 

@rppawlo, that is an interesting problem.  The load_sems_dev_evn.sh does not currently load a git module so that means that you are getting the default git version on RHEL 6 which is very old:

```
[rabartl@crf450 ~ (master)]$ /usr/bin/git --version
git version 1.7.1
```

We could make the 'module purge' optional, but (as have seen) the SEMS modules don't just prepend paths, they crash when they detect incompatible modules are loaded and that makes the current approach very fragile (which allowed @mhoemmen to push code that broke the CI build because the wrong MPI version was being used which lead to this issue).

I can think of a few ways to address this issue using `module purge`:

1) Update load_sems_dev_env.sh to load the module `sems-git/2.10.` (but then that assumes that the user's .gitconfig settings will work with the newer version of git).

2) Set the path to your updated git in `PATH` manually avoiding the usage of modules.  For example, you could do `export PATH=/projects/sems/install/rhel6-x86_64/sems/utility/git/2.10.1/bin$PATH` (this is essentially what I do but with git 2.6.4 installed with `install-git.py` which is why I did not see this issue).

Is one of the above approaches acceptable?  Unless I hear back from you otherwise, I will add sems-git/2.10.1 to load_sems_dev_env.sh.

Otherwise, the other way to address the module problem would be to just run all of these scripts with `#!/bin/bash -e` and crash if the modules are not loaded correctly.  But that would just crash the `checkin-test-sems.sh` script and might make people just give up on the usage of `checkin-test-sems.sh`.

**Comment by rppawlo** [comment]
@bartlettroscoe If you load the git module, then you force the users .gitconfig to be consistent with that version. Approach 2 is more flexible in this regard but rules out the use of modules for picking git version. I can work with either choice. I think the typical user of this script is going to use the sems modules anyway so choice 1 is probably the best.

**Comment by mhoemmen** [comment]
@bartlettroscoe I'm with @rppawlo ; feel free to let the script load a sensible git module.  Git is as much a part of our test environment as the compiler, so the check-in test script should load the version of git that it wants, just like it loads the compiler and MPI versions that it wants.

**Comment by mhoemmen** [comment]
Debugging progress: The following cases work (don't segfault or report an error in `MPI_Allreduce`):
  - `Tpetra::Vector` inputs and raw pointer output
  - `Tpetra::Vector` inputs and rank-0 `Kokkos::View` output

The following case triggers the error:
  - `Tpetra::MultiVector` inputs (with multiple columns) and raw array output

The following case has not yet been tested:
  - `Tpetra::MultiVector` inputs (with multiple columns) and rank-1 `Kokkos::View` output

Next step is to exercise the not-yet-tested case, because the error-triggering case reduces to that case (except that the error-triggering case internally creates an unmanaged `Kokkos::View`, so the one difference could be whether the View is managed).

**Comment by mhoemmen** [comment]
Huh, the not-yet-tested case reports a link error.  Will need to poke around a bit more.

**Comment by bartlettroscoe** [comment]
> If you load the git module, then you force the users .gitconfig to be consistent with that version. 

I have found that in most cases, git 1.x .gitconfig settings are mostly respected with git 2.0+ but git may print a nasty warning.  The problem is going the other way (which is what @rppawlo reported [above](https://github.com/trilinos/Trilinos/issues/946#issuecomment-268514491)).

> I think the typical user of this script is going to use the sems modules anyway so choice 1 is probably the best.

I agree.

> I'm with @rppawlo ; feel free to let the script load a sensible git module. Git is as much a part of our test environment as the compiler, so the check-in test script should load the version of git that it wants, just like it loads the compiler and MPI versions that it wants.

Okay, that is the plan then (i.e. do `module purge` then add `sems-git/2.10.1` to list of modules loaded by load_sems_dev_env.sh) .  I will go ahead and make these changes and push.

**Comment by bartlettroscoe** [comment]
NOTE: This failing CI test is not so damaging to others trying to push with the checkin-test-sems.sh script because Tpetra only depends on the upstream packages Kokkos, Teuchos, and Epetra as shown in the configure output:

* `Final set of enabled packages:  Kokkos Teuchos Epetra Tpetra 4`
* `Final set of enabled SE packages:  KokkosCore KokkosContainers KokkosAlgorithms Kokkos TeuchosCore TeuchosParameterList TeuchosComm TeuchosNumerics TeuchosRemainder TeuchosKokkosCompat TeuchosKokkosComm Teuchos Epetra TpetraClassic TpetraKernels TpetraTSQR TpetraCore Tpetra 18`

Therefore, only people enabling all packages and/or Kokkos, Teuchos, or Epertra will have their pushes stopped do to this failing test.  Testing of downstream packages are not affected.

I was able to push last night even with this failing test because I knew this test was already failing (because I always look at the CI build on CDash before I run the checkin-test-sems.sh script to test and push) and I disabled it for my push (and only my push) as per:

* https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing#disable_already_failing

**Comment by mhoemmen** [comment]
Hm, in the `MPI_VERSION < 3` case, I wasn't using `MPI_IN_PLACE` when I should have been.  Must not have had `Tpetra::Details::iallreduce` coverage for that case.  `Tpetra::Details::idot` prefers to exercise `MPI_IN_PLACE` if the input communicator is not an intercommunicator, since that avoids a temporary buffer allocation.

**Comment by mhoemmen** [comment]
Tests pass with both MPI_VERSION < 3 (OpenMPI 1.6.5) and MPI_VERSION >= 3 (OpenMPI 1.10.1).  Check-in test script only did the first of these; I did the second on my own.  Thanks all!

**Comment by bartlettroscoe** [comment]
>  I think the typical user of this script is going to use the sems modules anyway so choice 1 is probably the best.

@rppawlo, I updated the script load_sems_dev_env.sh to also load sems-git/2.10.1.  Please give this a try again and let me know (offline) if this works for you or not.

> Check-in test script only did the first of these; I did the second on my own. Thanks all!

@mhoemmen, right, we can only pick one MPI version for our pre-push CI build for a reasonably fast pre-push testing process.   We just need to pick the one that is most important to our must important customers.

**Comment by mhoemmen** [comment]
> @mhoemmen, right, we can only pick one MPI version for our pre-push CI build for a reasonably fast pre-push testing process. We just need to pick the one that is most important to our must important customers.

Not a criticism ;-) I could always rig up a metascript to run multiple test configurations.
