### ISSUE TITLE
KokkosKernels: SPMV performance comparison test

### ISSUE THREAD

**Issue by crtrott** [trilinos/Trilinos#948]
This adds a performance comparison test without MPI for just SPMV kernel. Can compare the KokkosKernel function, a custom Kokkos implementation, CuSparse and MKL. 
This can read MatrixMarket format, and also generate a binary matrix storage file, which it can read again. Depending on your system reading the binary format back in can be 10x faster than the text file. 

I had that written quite a while ago I just cleaned it up now.

**Comment by crtrott** [comment]
For now this only has a gnu make build and is not incorporated into CMake build system

**Comment by crtrott** [comment]
Here is a build command for Bowman (Assuming you loaded the intel devpack; you can do that in any build directory for out-of-source build):
```
make -f ~/Trilinos/packages/tpetra/kernels/perf_test/spmv/Makefile KOKKOS_ARCH=KNL KOKKOS_DEVICES=OpenMP BUILD_MKL=1 BUILD_TRILINOS=1 CXX=icpc -j
```

Here is the usage (--help):
```
  -s [N]          : generate a semi-random banded (band size 0.01xN) NxN matrix
                    with average of 10 entries per row.
  --test [OPTION] : Use different kernel implementations
                    Options = kk,mkl,cusparse,kk-kernels

  -f [file]       : Read in Matrix Market formatted text file 'file'.
  -fb [file]      : Read in binary Matrix files 'file'.
  --write-binary  : In combination with -f, generate binary files.
  --offset [O]    : Subtract O from every index.
                    Useful in case the matrix market file is not 0 based.

  -rpt [K]        : Number of Rows assigned to a thread.
  -ts [T]         : Number of threads per team.
  -vl [V]         : Vector-length (i.e. how many Cuda threads are a Kokkos 'thread').
```

On Bowman you can find matrices under: /home/projects/matrix-market

**Comment by mhoemmen** [comment]
Yo @jjellio and @tjfulle -- this may be useful.  Also, I need to open an issue about the new "region" interface that Kokkos Profiling offers.  That would be a handy option for doing the kind of layered performance studies that @jjellio is working on now, while still letting us work in the main Trilinos repo instead of a branch that doesn't see performance improvements.

**Comment by nmhamster** [comment]
@crtrott @mhoemmen @jjellio @tjfulle I have added an `OpenMP-Static`, `OpenMP-Dynamic` and `OpenMP-SmartStatic` (which I had discussed in a talk in August) to my fork. Of course, since doing that the upstream has changed so I will need to modify the code and get you a pull request, I'll work on that next. Attached is a set of performance comparisons against base Kokkos (`KK`) in a spreadsheet, you probably want to look at the relative-to-KK column. The numbers (in the left set of columns) are SpMV-GF/s as reported by the benchmark when running in DDR on KNL using `OMP_NUM_THREADS=256 OMP_PLACES=threads OMP_PROC_BIND=close`. I have HBM results as well and will also compile them and provide the spreadsheet shortly. I will go back to the statements that I made in August that I think a relatively simple non-zero balancer should provide a very good level of performance since it doesn't really make sense to me that anything dynamic can out-perform it when there is matrix reuse across multiple SpMV calls for processors like KNL, Haswell, POWER8 or ARM. The balancer in my implementation can be tuned but I haven't done that yet, this is something very simple to provide you with an estimate rather than the "best implementation". I'd be interested to hear your thoughts on the results. Pull-Request to follow.

[spmv_impl_compare.xlsx](https://github.com/trilinos/Trilinos/files/683278/spmv_impl_compare.xlsx)

**Comment by nmhamster** [comment]
See PR #967 for the code which was used to generate these results.

**Comment by nmhamster** [comment]
And here is a spreadsheet which also has HBM-only results. These show that there are potentially greater gains when running out of HBM (and are therefore more sensitive to overheads).

[spmv_impl_compare.xlsx](https://github.com/trilinos/Trilinos/files/683366/spmv_impl_compare.xlsx)

**Comment by nmhamster** [comment]
I noticed a small bug where thread-0 might have done more work than needed and potentially cause a failed test for very small matrices. This is fixed and updated results here. In general it makes the OpenMP-SmartStatic code perform slightly better for small matrices and identically for medium to large matrices.

[spmv_impl_compare.xlsx](https://github.com/trilinos/Trilinos/files/683533/spmv_impl_compare.xlsx)

**Comment by ambrad** [comment]
@nmhamster, in these results, is establishSmartSchedule called at each matvec?

For #threads << @rows, a binary search instead of the linear search at OpenMPSmartStatic_SPMV.hpp:90 might be useful. In HTS, the function partition_ir, here:

https://github.com/trilinos/Trilinos/blob/master/packages/shylu/hts/src/shylu_hts_impl_def.hpp#L1084

does that. ir is equivalent to matrixRowOffsets in establishSmartSchedule.

**Comment by nmhamster** [comment]
@ambrad it is called once and saved in a rather embarrassingly simple NULL check. Thank you for the pointer. The purpose of this kernel is to show what a nonzero balancer can do. I can think of hundreds of ways we could improve this further if we are interested.

**Comment by nmhamster** [comment]
And here is an updated set of runs with KNL-Cache mode included, now sorted by matrix size. Graphing the results shows the inspector-based methods do quite well for smaller matrices, the OpenMP Smart-Static does better when using HBM and cache mode, for DDR the OpenMP Smart Static and Kokkos-Inspector do similar but not always on the same matrices which most likely reflects the different optimization points. Lots of discussion with @ambrad on the importance of smaller matrices to overall higher-level algorithm performance (thank you!)

[spmv_impl_compare.xlsx](https://github.com/trilinos/Trilinos/files/683858/spmv_impl_compare.xlsx)

**Comment by nmhamster** [comment]
Updated to include POWER8 with IBM XL. Results show a similar trend.

[spmv_impl_compare.xlsx](https://github.com/trilinos/Trilinos/files/685321/spmv_impl_compare.xlsx)

**Comment by mhoemmen** [comment]
Thanks @nmhamster and @crtrott !  I really would like to integrate this into the CMake build system.  That would involve changing the macros.  Would you all object to that?

**Comment by nmhamster** [comment]
@mhoemmen I will fix the issues you have highlighted and raise a second PR for you.

**Comment by mhoemmen** [comment]
@nmhamster awww, i can do it!  please don't feel obligated to learn all these CMake details :)

**Comment by nmhamster** [comment]
@mhoemmen how about I fix the code for you. You can then do the CMake :-). @maherou has made it clear that we all need to take responsibility for our own code to meet standards and I agree with that as a project ethos. Will get you a PR shortly.

**Comment by mhoemmen** [comment]
@nmhamster sorry for the trouble!  I'll be happy to do the CMake part of this.  CMake generates the TpetraKernels_config.h header file in the build directory, so you could include that.  KokkosKernels doesn't have a non-TriBITS build system yet, so I'm not sure if a Makefile-based build system makes sense for the benchmark.

**Comment by crtrott** [comment]
Please wait with the cmake part. This is by no means ready for it. The benchmark will horribly break for example if Cuda is enabled.

**Comment by crtrott** [comment]
We'll fix it up in the end when we are done and no what to pull into Kokkos kernels.

**Comment by nmhamster** [comment]
@mhoemmen I am adding the tempting for `LocalOrdinal` and `Scalar` as requested. The runs are in the queue now to check they have not materially damaged the runtime.

**Comment by nmhamster** [comment]
@mhoemmen the templating you requested is added in #986. Take a look and let me know if you need anything else added.
