### ISSUE TITLE
LOCA: allow skipping DfDp via ParameterList

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#950]
LOCA's computeDfDp logic perturbs parameters by some epsilon. In Albany, we are running into trouble because the perturbed parameter is outside of a certain domain. In particular, users specify piecewise functions of the parameter and if it is perturbed outside the user-specified domain then the user function can't be evaluated. I noticed LOCA has a "skipDfDp" option in parts of the code, but it is currently hardcoded to false. Would it be okay to expose this boolean via parameter lists ? what is the best way to do that ?

@trilinos/nox

**Comment by rppawlo** [comment]
@etphipp

**Comment by etphipp** [comment]
You can certainly expose skipDfDp as a parameter if you want.  All you would need to do is extract it from the "continuationParams" list where setConstraints() is called in line 80 of LOCA_MultiContinuation_ArcLengthGroup.C.

However I'm not sure that's what you really want.  If you turn on skipDfDp, then arc-length continuation becomes natural continuation and you won't be able to go around turning points anymore (and skipDfDp was added as an option to make natural continuation more efficient since it isn't necessary for that method).

Are you saying the perturbation size is too large resulting in invalid parameter values?  If so you might want to instead enable more control over how the perturbation size is computed.  The perturbation is handled by the LOCA::DerivUtils class which takes a perturbation size as a constructor argument.  You could create your own DerivUtils class with your own perturbation size and pass it into your LOCA::Abstract::Group.

**Comment by ibaned** [comment]
So, is it true that Natural continuation will always skip the DfDp evaluation ? If so, I simply need to switch from Arc Length to Natural, because we are not doing any kind of sophisticated continuation.

**Comment by etphipp** [comment]
Natural continuation defaults to skipping the DfDp evaluation, but it is modifiable through the parameter list:

bool skip_dfdp = continuationParams->get("Skip Parameter Derivative", true);
Teuchos::RCP<LOCA::MultiContinuation::ConstraintInterface> cons
    = Teuchos::rcp(new LOCA::MultiContinuation::NaturalConstraint(
    globalData, Teuchos::rcp(this, false)));
LOCA::MultiContinuation::ExtendedGroup::setConstraints(cons, skip_dfdp);

**Comment by etphipp** [comment]
I guess this can be closed then?

**Comment by ibaned** [comment]
Yes, thank you.
