### ISSUE TITLE
Tpetra::CrsMatrix: Feature request for replaceDiagonalValues and invRowSum

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#959]
@mhoemmen 
@jrobbin 
@trilinos/tpetra 

I would like to request the addition of the following methods to the Tpetra::CrsMatrix class: 

- replaceDiagonalValues
 - invRowSum 

These methods are needed in the Albany code.

**Comment by mhoemmen** [comment]
The `invRowSum` method would be the equivalent of Epetra_CrsMatrix::InvRowSums.  That method takes an output Epetra_Vector, and stores `1 / (sum |A(i,j)|)` in each entry i of the Epetra_Vector.  

For Tpetra, I recommend implementing this as a nonmember function, since the public interface of Tpetra::CrsMatrix suffices to write a performant implementation.

**Comment by mhoemmen** [comment]
The `replaceDiagonalValues` method should be straightforward to implement using existing Tpetra::CrsMatrix methods.  The one issue is that there is no method to get direct nonconst access to the entries, other than to get the KokkosSparse::CrsMatrix directly.  Otherwise, one could precompute relative offsets (via `A.getCrsGraph()->getLocalDiagOffsets(relOffsets)`) and then just write directly to the diagonal entry in each row.  I would still recommend using the KokkosSparse::CrsMatrix directly, if the matrix has been fill-completed at least once.

**Comment by mhoemmen** [comment]
I would say, `Tpetra::leftAndOrRightScaleCrsMatrix` and `Tpetra::computeRowAndColumnOneNorms` achieve the aims of this feature request, so I'm closing it.
