### ISSUE TITLE
Tpetra: Feature request to add "min" CombineMode

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#960]
@mhoemmen 
@jrobbin 
@trilinos/tpetra 
I would like to request the addition of a method equivalent to Epetra_Min to the Tpetra exporter class.  It is needed in the Albany code.

**Comment by mhoemmen** [comment]
Just to clarify: This would be a new CombineMode.  In Epetra, Epetra_Min actually means minimum, not minimum of the absolute values.  Thus, in Tpetra, we would need to specialize this, depending on whether Scalar is real (use less-than) or complex (pick the number whose absolute value is the least).

**Comment by maherou** [comment]
It might be worth considering a generic form of comparison operator, rather than add to the finite list of operations.  This way the user could define their own operator.  This would have been the next step for Epetra, if we had more requests for operations.  I am guessing this would be fairly easy to support.

**Comment by mhoemmen** [comment]
@maherou You filed this as a feature request in 2011, as Bugzilla Bug 5196:

https://software.sandia.gov/bugzilla/show_bug.cgi?id=5196

(Our apologies to users who don't have access to the Bugzilla bug tracking system that we used before we switched to GitHub.  One of the advantages of GitHub is that issues are always public.)

Your request _sounds_ like an easy thing to do.  I brought up the main concern already in 2014 in the first full year of the effort to refactor Tpetra to use Kokkos 2.0.  This is that Tpetra needs to be able to call this user-provided function in a thread-parallel way, on GPUs as well as CPUs.  This requirement may restrict users in unexpected ways.  For example, std::min won't work with CUDA, since it is not a `__host__ __device__` function.  Closures or classes with global state won't work even on CPUs, unless that state is thread safe, and they may perform badly even if they work.  

If users really insist on custom combine operators, then my plan, as discussed in the above Bugzilla bug discussion, would be to have a fast path for the predefined CombineModes.  This would avoid function call overhead in inner loops.

No one has ever given me a good example of a custom combine operator that is not in the list of operators that at least one of {Epetra, Tpetra} already implement.  It's not hard for me to add the equivalent of Epetra_Min to Tpetra.

**Comment by ikalash** [comment]
@mhoemmen We found a workaround in Albany, in which we use the ABSMAX combine mode, so adding the CombineMode equivalent to Epetra_Min to Tpetra is no longer urgent for us.  I thought I'd share this information to help you prioritize tasks.  Thanks!

**Comment by mhoemmen** [comment]
Thanks @ikalash !
