### ISSUE TITLE
Set up automated develop->master testing

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#982]
@trilinos/framework 

To set up an automated test for develop->master testing we need to finish the following tasks:

1. Reconcile differences between the two current CI builds. Default in the direction of changing the old CI build to match the new one. (@jwillenbring)

2. Test reliability of return codes for automated builds. Strategy: modify existing Jenkins-initiated build with failures to a subset with no failures and see if build reports "pass". (@bmpersc) 

3. Solve the issue of how we will push directly within a Jenkins job to master (authentication issue). 

4. Set up a Jenkins job to run the automated testing that can also push to master when tests 100% pass.

**Comment by bartlettroscoe** [comment]
Someone also has to fix the Jenkins-run CI server as it is not even running continuously.  It just runs in the morning and then dies.  I sent out an email about this a long time ago.

Also, this build needs to exactly match the pre-push CI build and env with load_ci_sems_dev.sh and checkin-test-sems.sh or I will have to keep running my CI server to protect pushes to the Trilinos using that script (i.e. my pushes).

But obviously you can build and test more to gate the update from 'develop' to 'master'.   That is a different story.

Also, please use explicit merge commits and put "Build/Test Cases Summary" in the merge-commit log message.  That way we can allow people to robustly bisect Trilinos commits.  See:

* https://github.com/trilinos/Trilinos/issues/482#issuecomment-255533714
* https://tribits.org/doc/TribitsDevelopersGuide.html#using-git-bisect-with-checkin-test-py-workflows 

If you don't people will experience "half of the commits don't even configure" as per above.

**Comment by jwillenbring** [comment]
@bartlettroscoe any idea why   SET_DEFAULT( Trilinos_ENABLE_SECONDARY_TESTED_CODE OFF)
is not turning off secondary tested code for the old CI build? I noticed in your new CI build you use both this SET_DEFAULT option, as well as a SET option for the same variable. I can do that too, but then it seems that the SET_DEFAULT option simply isn't working. The only thing slightly abnormal I see about the SET_DEFAULT option is the spacing after the ( and before the ) is inconsistent. Is this possibly an issue? The spacing before and after your SET brackets, and the spacing for nearly every other other option for the vast majority of builds is consistent.

**Comment by bartlettroscoe** [comment]
> I noticed in your new CI build you use both this SET_DEFAULT option, as well as a SET option for the same variable. 

Note sure why both are set.  This is likely due to a copy and paste I suspect.  The SET_DEFAULT() should do it but it does not matter what version you use.  An env var with that name will always override what you set internally by any means.  Can you attach or point to the output from the `ctest -S <script>` invocation you are running?  That will tell you what value for Trilinos_ENABLE_SECONDARY_TESTED_CODE is actually getting used for the outer and inner configures.

NOTE: I recently fixed a problem in TriBITS with Trilinos_ENABLE_SECONDARY_TESTED_CODE not getting passed through into the inner configure correctly (see TriBITS commits related to TriBITSPub/TriBITS#163).  Therefore, you should not need to mess with that at all.

NOTE: We need to revise the outer driver process to log the outer ctest -S script and manage it better.  I don't think the Jenkin's job as it is currently define does a very good job of that.  And the CI driver I am running is not logging the ctest -S script output either.  I think a simpler CTest/CDash system would do the trick.

**Comment by jwillenbring** [comment]
I looked at the build output and Trilinos_ENABLE_SECONDARY_TESTED_CODE='ON' appears 55 times, and it never says the option is off. I will have to do some more digging.

**Comment by jwillenbring** [comment]
@allevin is working on this now in #1154 so I am going to close this ticket.
