### ISSUE TITLE
Possible to change residual norm scaling for Belos::BlockCGSolMgr?

### ISSUE THREAD

**Issue by vbrunini** [trilinos/Trilinos#989]
When using Belos::BlockGmresSolMgr I am able to change the residual norm scaling by adding "Implicit Residual Scaling" or "Explicit Residual Scaling" parameters to the Teuchos::ParameterList I construct the solver with. Is it possible to do the same with the Belos::BlockCGSolMgr? I don't see anything about residual scaling in its validParameters() method.

**Comment by mhoemmen** [comment]
@trilinos/belos @hkthorn

**Comment by hkthorn** [comment]
Hi Victor,

You are correct that I don't see the ability to change the scaling type for BlockCGSolMgr.  The PseudoBlockCGSolMgr does let you change the residual scaling type using the "Residual Scaling" and "Implicit Residual Scaling" parameters.  That can be added to the BlockCGSolMgr as well.  For the current CG implementations there isn't a notion of explicit vs. implicit residual scaling because the CG iteration always computes the recursive residual vectors as a by-product of the iteration.  We can add the same options from pseudo-block CG to the block CG solver manager.

Thanks for pointing this out.

Heidi

--

Heidi K. Thornquist
Electrical Models & Simulation
Sandia National Laboratories
Albuquerque, NM  87185-1323

**Comment by vbrunini** [comment]
Thanks Heidi. What's the difference between the BlockCGSolMgr and PseudoBlockCGSolMgr (other than this parameter handling)?

**Comment by amklinv** [comment]
Block CG constructs a single Krylov subspace for all RHS, whereas a separate Krylov subspace is constructed for each RHS in the pseudo-block case.  Pseudo-block CG is mathematically equivalent to solving each linear system independently, block-CG is not.  Block methods are good when your right hand sides are linearly dependent, or very close to it.

**Comment by vbrunini** [comment]
In that case I'm happy just using the PseudoBlockCGSolMgr since I only have a single rhs anyway.

That makes actually updating BlockCGSolMgr a low priority for me, but it would be nice if there was a user guide or something for Belos documenting what the (hopefully consistent) parameter interface for the solvers is (maybe there is and I just haven't looked in the right place?).

Thanks,
Victor

**Comment by hkthorn** [comment]
The "Implicit Residual Scaling" parameter has been added to the BlockCGSolMgr and the required logic to recreate the residual status tests has been updated to respect any changes to this parameter.
