### ISSUE TITLE
MueLu test failure in updated CI build

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#992]
@trilinos/muelu 

A test is failing after updating the Trilinos CI build on sadl30906.

[link to failure](http://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2694233)

There are 3 general possible causes for this failure:

1) MueLu was changed and this caused the new failure.

2) The changes to the CI build parameters since the last one uncovered the failure, and the failure is valid.

3) The changes to the CI build parameters were made somehow in an invalid way and the parameters need to be updated. The failure is invalid, but rather a misconfiguration issue.

**Comment by jhux2** [comment]
@jwillenbring It's not clear from the output what happened.   MueLu wasn't updated, so it doesn't appear to be a change to MueLu itself.  The [passing/failing graph ](http://testing.sandia.gov/cdash/testDetails.php?test=36149150&build=2694233) also shows the test passing previously.

![screenshot-cdash trilinos - mozilla firefox-1](https://cloud.githubusercontent.com/assets/12970120/21816630/9ac784ee-d715-11e6-8794-22ca50416798.png)

We've seen transient failures on sadl30906 in the past and never been able to identify the root cause.

**Comment by jwillenbring** [comment]
For the next run, this test passed. If it passes tomorrow, I will just close this.

**Comment by jhux2** [comment]
@trilinos/framework Since this might be related to the test machine environment and/or hardware resources.

**Comment by jwillenbring** [comment]
Since this passed today and there have been odd failures observed in the past, I am going to close this, at least for now.
