### ISSUE TITLE
Belos: Change GMRES default orthogonalizer from DGKS to ICGS 2-pass

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#994]
@trilinos/belos @jjellio @hkthorn

**Comment by hkthorn** [comment]
Why?

--

Heidi K. Thornquist
Electrical Models & Simulation
Sandia National Laboratories
Albuquerque, NM  87185-1323

**Comment by mhoemmen** [comment]
@jjellio reported this.  DGKS is slow.  ICGS 2x is the AztecOO default.

**Comment by jjellio** [comment]
Something I added to my trilinos fork was a slight change in the labels used by the OrthoManagers.

Basically, set the orthoManager's label to be: label_ = label + ':DGKS' + "(orthoPasses)", or ICGS, etc...

That way, atleast if you are looking at timers, Belos would report:
Belos:Orthogonalization:ICGS(2) (inner product)
Belos:Orthogonalization:ICGS(2) (update)
Belos:Orthogonalization:ICGS(2) (norm)

Rather than just Orthogonalization.

I think that is a better "fix" than changing the default.

**Comment by jhux2** [comment]
This seems to be relevant again for some recent EMPIRE scaling results.

**Comment by mhoemmen** [comment]
I'm labeling this "results impacting," because, well, it is ;-) .  That's not bad, though.

**Comment by bartlettroscoe** [comment]
@mhoemmen, @jhux2, @jjellio, and @srajama1 (the Product Lead for Belos),

Is this issue still active or can it be closed?  Is there anything that is going to be done for this?  If not, then it should be closed or have have the "Stale" label added to it perhaps to get it off of the list of ATDM issues that I go over periodically.

**Comment by mhoemmen** [comment]
@bartlettroscoe We would like to fix this still.  Please feel free to add the "Stale" label if it helps.

Reason for low priority is that users can easily work around with an appropriate parameter.

**Comment by bartlettroscoe** [comment]
Added the label "Stalled" (not "Stale").
