### ISSUE TITLE
CrsMatrix->getLocalRowView() slow in debug builds.

### ISSUE THREAD

**Issue by blsteve** [trilinos/Trilinos#9944]
Possibly related to issue #9939. If it is, the relation is not obvious.
I'm trying to diagnose an issue where some Sierra/SD trivially small models are unusually slow on debug builds of the code, preventing some tests from completing on our nightly dashboard.

Profiling traced the slowdown to a Teuchos::CrsMatrix->getLocalRowView() call from within a matrix multiply operation.
I'm attaching a unit test, which I've tailored to mimic the construction and usage of this particular CrsMatrix in Sierra/SD as faithfully as I could manage.

I've included some test timings in the comments for the unit test. In that context, the compile options "debug", "dev", and "release-symbols" refer to the build flags used by Sierra's "bake" system.
Example: "bake -e dev Salinas"
Roughly speaking:
 - debug has symbols, and minimal compiler optimizations
 - dev is (roughly) debug without the symbols
 - release-symbols has both compiler optimizations and symbols.

[MultiVectorTest.txt](https://github.com/trilinos/Trilinos/files/7557417/MultiVectorTest.txt)
Pardon the extension of the attached source file. Github wouldn't let me upload a ".C" file.

**Comment by cgcgcg** [comment]
@trilinos/tpetra

**Comment by kddevin** [comment]
@blsteve -- I was able to reproduce the performance that you see in your reproducer; with gcc, the debug version takes at least 40x longer than the release version.  Thanks for the reproducer.

0.  I assume you are doing your own matrix multiplication, right?  I did not see getLocalRowView used in Tpetra's SpMV.  If you are seeing this performance in Tpetra's SpMV, please let me know.
1.  The version of getLocalRowView that takes Teuchos::ArrayView arguments that is in your test is deprecated.  The new version takes Kokkos::View arguments.  With gcc and the new version, the debug build takes only 5-7x longer than the release build.
2.  getLocalRowView will incur overhead for host/device safety checking for each row.  Alternatively, you can use getLocalMatrixHost to get all row indices and values in one call, and then offset into the Kokkos views for each row.  This approach incurs the safety checks only once.  Again, it was 5-7x slower in the debug build versus the release build.

For an example using getLocalRowView with Teuchos::ArrayView and Kokkos::View, and getLocalMatrixHost, see branch tpetra_9944, file tpetra/core/test/CrsMatrix/Bug9944.cpp.  I used this test in my performance evaluation, but I will not merge it into the repo (especially since it is designed to compare against deprecated code).

**Comment by kddevin** [comment]
@blsteve may I close this issue as resolved?

**Comment by blsteve** [comment]
I think so.
I haven't had time to come back to this in a while.
